### ISSUE TITLE
Switch away from gulp-server-livereload

### ISSUE THREAD

**Issue by dpeukert** [getferdi/ferdi#1002]
gulp-server-livereload hasn't been updated in four years and is the source of quite a lot of vulnerabilities reported by `npm audit`. It also doesn't run on node.js >= 14 because of this bug in one of its outdated dependencies: https://github.com/yuanchuan/node-watch/issues/94. I'll try looking at some alternatives, but I'm not familiar with the gulp ecosystem, so any tips or recommendations are appreciated.

**Comment by vraravam** [comment]
@dpeukert - I dont think this is still valid - i couldn't find references to `gulp-server-reload` in the `ferdi` repo. Please close if this is correct.

**Comment by dpeukert** [comment]
@vraravam Yep, thanks for the heads-up, closing.
