### ISSUE TITLE
Service forgets site cookies

### ISSUE THREAD

**Issue by OliverCole** [getferdi/ferdi#1007]
**Bug description:**

Adding a 'Custom Website' service for https://focus.nirvanahq.com/ works, but is logged out within a day.

Bug also occurs in Rambox, so it's definitely site-specific. However it didn't occur in Station v1, so it is possible to make it work. Naturally the site works fine in Chrome and Firefox.

**Steps to reproduce:**

1. Sign up a free account with https://focus.nirvanahq.com/
1. Create Custom Website service.
1. Login
1. Wait a day or less (and refresh if needed)

**Expected behavior**
Stays logged in.

**Environment:**

- Operating System: Win 10
- Ferdi Version: 5.5.0
- Server: No account

- Debug information:
There's some personal information in there, prefer not to share.

**Comment by OliverCole** [comment]
Still an issue.

**Comment by vraravam** [comment]
Duplicate of #872
