### ISSUE TITLE
Review social card image

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#101]
- [x] Change name from "Ferdi" to "Ferdi Messenger"
- [x] "All your services in one place" to "All your messaging services in one place"
- [x] Include icons of supported services that are famous enough to catch the eye

![Screen Shot 2019-10-04 at 3 27 33 PM](https://user-images.githubusercontent.com/412895/66193377-9b953d80-e6bc-11e9-8f45-4ebd0b7977ca.png)

@vantezzen Can you share the PSD if you have any?

**Comment by kytwb** [comment]
Got it via https://github.com/getferdi/ferdi/commit/473a84824d86a7e9f1178bbcbc45b230eeae2921, thanks @vantezzen.

**Comment by g-ravity** [comment]
@kytwb I would like to work on this, if this is still unassigned

**Comment by kytwb** [comment]
@g-ravity feel free to!

**Comment by g-ravity** [comment]
@kytwb @vantezzen I looked at the PSD file, but I can't get the font used in the PSD, since the font layer has been rasterized. I browsed through the project and saw that Open Sans has been used in the project. Can you tell the font used in the social preview PSD or should I use Open Sans instead?

**Comment by kytwb** [comment]
@g-ravity I have checked the PSD file and tried to type "Ferdi" with Open Sans to compare, but it doesn't seem to be that font; I'll let @vantezzen answer on this.

**Comment by vantezzen** [comment]
I just checked:
I used the ["Circular Std"](https://www.npmjs.com/package/circular-std) font in the social preview, you can however use another font if it fits better or if you don't have that font.

**Comment by g-ravity** [comment]
I'm not being able to make the design better as per your checklist. Anybody else wanna try, then go ahead

**Comment by kytwb** [comment]
No problems @g-ravity, taking over!

**Comment by kytwb** [comment]
@vantezzen WDYT? Does that work for now?

![social-preview](https://user-images.githubusercontent.com/412895/67148662-2769b500-f2cc-11e9-9c17-8b6dc500ceb2.jpg)

**Comment by kytwb** [comment]
[Twitter Card Validator](https://cards-dev.twitter.com/validator):

![Screen Shot 2019-10-20 at 12 03 35 AM](https://user-images.githubusercontent.com/412895/67148765-56345b00-f2cd-11e9-99e0-c0b8c9509dde.png)

[Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fgithub.com%2Fgetferdi%2Fferdi):

![Screen Shot 2019-10-20 at 12 04 33 AM](https://user-images.githubusercontent.com/412895/67148766-56345b00-f2cd-11e9-9225-e8c990d46493.png)

[LinkedIn Post Inspector](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fgithub.com%2Fgetferdi%2Fferdi):

![Screen Shot 2019-10-20 at 12 06 08 AM](https://user-images.githubusercontent.com/412895/67148780-76fcb080-f2cd-11e9-9778-568e90b7a627.png)

**Comment by kytwb** [comment]
I pushed the updated PSD, we can iterate if needed. FYI, I've shared the links to the Twitter/Facebook/LinkedIn developer tools for links previews. You can refresh the social networks previews caches after updating the social preview on GitHub by just resubmitting the repository URL for Twitter/LinkedIn, or by pressing the "Scrape Again" button for Facebook.

**Comment by kytwb** [comment]
The font: [circular_std_font_family_by_ybtoffical_dd40z3q.zip](https://github.com/getferdi/ferdi/files/3746977/circular_std_font_family_by_ybtoffical_dd40z3q.zip)
