### ISSUE TITLE
telegram wont load images or stickers

### ISSUE THREAD

**Issue by rica01** [getferdi/ferdi#1015]
**Bug description:**

While using Telegram, I cannot see the images, stickers of video messages I am sent.

**Steps to reproduce:**

1. Go to Telegram
2. Look up for any message with said multimedia.
3. See that there's nothing.

**Expected behavior**

I want to be able to see the multimedia.

**Screenshots**

![image](https://user-images.githubusercontent.com/11340563/95677897-8e653580-0bd1-11eb-80bb-d445febf2076.png)

**Environment:**

- Operating System: win 10 64bit
- Ferdi Version: 5.5.0 
- Server: Ferdi

- Debug information:

{"host":{"platform":"win32","release":"10.0.19041","screens":[{"id":2528732444,"bounds":{"x":0,"y":0,"width":1536,"height":864},"workArea":{"x":0,"y":0,"width":1536,"height":834},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1536,"height":864},"workAreaSize":{"width":1536,"height":834},"scaleFactor":1.25,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"discord","version":"1.1.3"},{"id":"facebook","version":"1.0.1"},{"id":"instagram","version":"2.0.0"},{"id":"messenger","version":"1.1.0"},{"id":"slack","version":"1.0.15"},{"id":"steamchat","version":"1.1.2"},{"id":"telegram","version":"3.0.0"},{"id":"whatsapp","version":"2.0.3"},{}],"devRecipes":[],"services":[{"id":"37e3b504-395f-4aa2-b867-79aab8fc5290","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"7cbb8905-6979-4f54-b887-ba20d08b25f0","recipe":"steamchat","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"df671345-b8ab-4968-92f7-2ecc9dfa4a16","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"5087447f-ba35-4688-ba3a-7028d0032a89","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"bdec6587-0fdd-4247-82aa-00d3a87d0abd","recipe":"telegram","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"6fc7d076-9acf-47b8-b1d0-6eedd1750ac0","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"a764ac98-67d4-436c-9705-537e92a12235","recipe":"instagram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Uncaught TypeError: Cannot read property 'reload' of null","C:\\Users\\rroman\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\@sentry\\browser\\dist\\helpers.js",91,13,{}]},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in WindowControls\n    in div\n    in Unknown (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)"]}],"workspaces":[],"windowSettings":{"width":800,"height":603,"x":0,"y":0,"displayBounds":{"x":0,"y":0,"width":1536,"height":864},"isMaximized":true,"isFullScreen":false},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":true,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":false,"spellcheckerLanguage":"en-us","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":"","serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":"55","iconSize":"30","sentry":false,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by mahadevans87** [comment]
@rica01 I could not reproduce this. What happens when you try to send stickers? Are they showing up?

**Comment by rikroe** [comment]
I had the same issue, persisting over restarts.
Then I manually reloaded the Telegram service (Right-click > Reload) and now all Images etc. are shown.

**Comment by rica01** [comment]
thts what i have been doing, but still no permanent fix...

**Comment by morgangrubb** [comment]
I'm reproducing this issue with the latest deb on Ubuntu. The right click -> reload thing does not appear to work.

**Comment by rubencm** [comment]
Same here with archlinux.

I don't know if is related, but also I can't send images with control+v, the upload is stuck in 0%

**Comment by dbogdanov** [comment]
Same here with the latest deb on Ubuntu.

**Comment by selvin910** [comment]
Fix This Issue By This Video Link : https://youtu.be/nvMdA62sqUs

https://user-images.githubusercontent.com/86956871/124451467-09dfc600-dda3-11eb-9da3-bfffc80d036d.mp4

**Comment by Drexl** [comment]
I'm having this issue. The proposed fix by @selvin910 doesn't work because "advanced" Telegram settings are not present on the web interface, which of course Ferdi uses.

**Comment by vraravam** [comment]
There are 2 recipes for using telegram within Ferdi: `Telegram` and `Telegram React`. I use the latter, and dont have any problems. Could you please try with the `Telegram React` recipe and report back?

**Comment by Drexl** [comment]
@vraravam Telegram React solved the problem. Thank you.

**Comment by mhatvan** [comment]
I can also recommend the `telegram-react` recipe, works flawlessly, using it daily.
