### ISSUE TITLE
[macOS] Open Ferdi in fullscreen mode if it was closed in fullscreen mode

### ISSUE THREAD

**Issue by sy6sy2** [getferdi/ferdi#1025]
**Bug description:**

Ferdi is open in fullscreen, you CMD-Q it, you re-open it and Ferdi does not open in fullscreen mode.

**Steps to reproduce:**

1. Open Ferdi
2. Put it in fullscreen mode
3. Quit it with CMD-Q
4. Open Ferdi again
5. Ferdi opens in window mode instead of fullscreen mode

**Expected behavior**

If you quit Ferdi while in fullscreen mode, next time you open it, it should open in fullscreen mode (like Message or Safari behavior).

**Screenshots**

**Environment:**

- Operating System: macOS Catalina 10.15.6
- Ferdi Version: 5.5.0 (5.5.0.2116) 
- Server: Ferdi

- Debug information:

**Comment by mhatvan** [comment]
Cannot reproduce this on macOS Big Sur. This was probably fixed in the meantime.

Please reply in case this still occurs.
