### ISSUE TITLE
Ferdi email login should be case insensitive

### ISSUE THREAD

**Issue by mattdeitke** [getferdi/ferdi#1030]
**Bug description:** Ferdi email login should be case insensitive.

**Steps to reproduce:** Simply try signing in with Ferdi using a different email casing (e.g., youremail@gmail.com vs. YourEmail@gmail.com) and you'll notice that only the casing you used when signing up works.

**Expected behavior** All casing variations of an email are equivalent when logging into Ferdi.

**Comment by vantezzen** [comment]
Thank you for your bug report. We are already discussing this at https://github.com/getferdi/server/issues/24
