### ISSUE TITLE
Rename/Replace Riot.im to Element

### ISSUE THREAD

**Issue by batisteo** [getferdi/ferdi#1031]
The Matrix client Riot.im was quite recently [renamed as Element](https://element.io/blog/welcome-to-element/) and so the Service should be updated!

![element-logo](https://user-images.githubusercontent.com/2727048/96227702-c2a37200-0f94-11eb-8c77-ea9f94a44603.png)

**Comment by vantezzen** [comment]
Thank you for your report. Riot has already been renamed a few weeks ago - this change will be released with the next update of Ferdi.

**Comment by batisteo** [comment]
Great, thanks, can’t wait!

__(well, I can, np ^^)__
