### ISSUE TITLE
FB Messenger doesnt work - It work fine in chrome and franz(!)

### ISSUE THREAD

**Issue by Daij-Djan** [getferdi/ferdi#1032]
all I get from it is:
![Bildschirmfoto 2020-10-16 um 13 34 17](https://user-images.githubusercontent.com/156799/96253690-5a648880-0fb4-11eb-8c4c-cbd9ef43c32c.png)

Meaning it wants me to proceed to FB to complete my sign in.. but the button doesnt do anything :(

**Comment by jcuker** [comment]
Same issue here.

**Comment by jiehanzheng** [comment]
Probably a Messenger website bug

**Comment by endiz** [comment]
Same issue here, just reinstalled Ferdi and i can't get past "Please verify you Facebook account" splash.

**Comment by austkel** [comment]
It's 2-factor authentication. It should still work with it enabled. But I tried disabling and it worked. Enabled it once I logged back in - it broke it. :(

**Comment by nafarinha** [comment]
> It's 2-factor authentication. It should still work with it enabled. But I tried disabling and it worked. Enabled it once I logged back in - it broke it. :( Can't just keep 2 factor disabled.

Thanks for the tip, it worked! Weird that the app passwords don't work though

**Comment by endiz** [comment]
Agreed its because of MFA, but i would prefer not to disable it.

**Comment by austkel** [comment]
> Agreed its because of MFA, but i would prefer not to disable it.

Agreed, this might be worth switching to Franz 🤷‍♂️

**Comment by jcuker** [comment]
Perhaps this is something that will get fixed when the next version of Ferdi comes out with an updated Franz core?

**Comment by marcolussetti** [comment]
Clunky workaround:

Option 1, via console:
- Right click anywhere on the messenger page & select `Inspect Element`
- Open the `Console` tab
- Type `document.location.href="https://facebook.com"` and then press enter
- Log onto Facebook normally
- Back in the console, type `document.location.href="https://messenger.com"`

Option 2, via browsing:
- Enter email, password normally
- At the please `Verify your Facebook Account` screen, select `Not on Facebook?` from bottom left
- At the facebook `Create a new Account` screen, select `Log into Existing Account`
- Enter credentials
- Enter 2FA code when prompted
- Remember browser when prompted
- After reaching the facebook homepage, disable & enable service to go back to messenger.

**Comment by austkel** [comment]
> Clunky workaround:
> 
> Option 1, via console:
> 
> * Right click anywhere on the messenger page & select `Inspect Element`
> * Open the `Console` tab
> * Type `document.location.href="https://facebook.com"` and then press enter
> * Log onto Facebook normally
> * Back in the console, type `document.location.href="https://messenger.com"`
> 
> Option 2, via browsing:
> 
> * Enter email, password normally
> * At the please `Verify your Facebook Account` screen, select `Not on Facebook?` from bottom left
> * At the facebook `Create a new Account` screen, select `Log into Existing Account`
> * Enter credentials
> * Enter 2FA code when prompted
> * Remember browser when prompted
> * After reaching the facebook homepage, disable & enable service to go back to messenger.

Awesome tip - it worked for me! Thank you so much

**Comment by endiz** [comment]
> Clunky workaround:
> 
> Option 1, via console:
> 
> * Right click anywhere on the messenger page & select `Inspect Element`
> * Open the `Console` tab
> * Type `document.location.href="https://facebook.com"` and then press enter
> * Log onto Facebook normally
> * Back in the console, type `document.location.href="https://messenger.com"`
> 
> Option 2, via browsing:
> 
> * Enter email, password normally
> * At the please `Verify your Facebook Account` screen, select `Not on Facebook?` from bottom left
> * At the facebook `Create a new Account` screen, select `Log into Existing Account`
> * Enter credentials
> * Enter 2FA code when prompted
> * Remember browser when prompted
> * After reaching the facebook homepage, disable & enable service to go back to messenger.

Thank you, that worked!

**Comment by Rodancoci** [comment]
Looks like it's a problem with Facebook/Messenger's login process :s

**Comment by mhatvan** [comment]
I use Facebook Messenger with 2FA enabled daily and it works fine with https://github.com/getferdi/nightlies/releases/tag/v5.6.1-nightly.33. 

Just went through the login process with a clean install and encountered no issues. 

Clicking the button "proceed" on the "Please confirm your FB account" is mandatory for accounts with 2FA enabled afaik and it redirected me to FB as expected.

Please report back to me if the login works as expected with newer Ferdi versions.

**Comment by jcuker** [comment]
> 
> 
> I use Facebook Messenger with 2FA enabled daily and it works fine with https://github.com/getferdi/nightlies/releases/tag/v5.6.1-nightly.33.
> 
> Just went through the login process with a clean install and encountered no issues.
> 
> Clicking the button "proceed" on the "Please confirm your FB account" is mandatory for accounts with 2FA enabled afaik and it redirected me to FB as expected.
> 
> Please report back to me if the login works as expected with newer Ferdi versions.

At least for me, v5.60 no longer has this issue.

**Comment by vraravam** [comment]
Closing the issue since there has been corroboration that this is now fixed.
