### ISSUE TITLE
Account settings display "Franz" (side-effect of "Premium by default")

### ISSUE THREAD

**Issue by bittner** [getferdi/ferdi#1040]
**Bug description:**

The "Account" page of Ferdi's settings dialog displays "Franz" as a side-effect of our strategy to make all users Premium users.

Source code location: [components/settings/account/AccountDashboard](https://github.com/getferdi/ferdi/blob/master/src/components/settings/account/AccountDashboard.js#L250-L261)

![ferdi-account-says-franz](https://user-images.githubusercontent.com/665072/96787101-7cfe0380-13f1-11eb-9e4e-eaaf9506e694.png)

**Steps to reproduce:**

1. Register an account with Ferdi (probably optional?)
1. Start Ferdi, log in with your Ferdi credentials
1. Click on the gear icon :gear: in the sidebar (to pull up the settings dialog)
1. Go to the "Account" page
1. See "Franz" and the asterisk icon :asterisk: next to it, followed by your email address below all that

**Expected behavior**

What we probably want is a behavior similar to Franz' unprivileged account: The "Account" page should display:

1. the Ferdi logo and
1. the user's first and last name (from the account details, if available)

![franz-account-shows-users-name](https://user-images.githubusercontent.com/665072/96787121-84bda800-13f1-11eb-85c5-c4bdda0c4a6b.png)

**Environment:**

- Operating System: Ubuntu Bionic 18.04.5 LTS
- Ferdi Version: 5.5.0-2116 (Debian package)
- Server: Ferdi

**Comment by ArviTheMan** [comment]
Franz ads are also visible in the sidebar. I find this so annoying that I'm sticking with Rambox until this is fixed.
![image](https://user-images.githubusercontent.com/73516201/99699271-6c958300-2a9a-11eb-91de-016eb7f8af73.png)

**Comment by ArviTheMan** [comment]
I'd be interested in contributing a pull request to fix this "one day" but unfortunately that day is still a long way off.

**Comment by vantezzen** [comment]
> Franz ads are also visible in the sidebar

That is not a "Franz Ad" - that is just Franz Todo. You can change the Todo provider in Ferdi's settings to any other Todo service you want or disable the Todo sidebar altogether.
We kept it there to make it easier for Franz users to move to Ferdi and keeping it familiar.
