### ISSUE TITLE
Service pane should use all available pixels (1 pixel wasted on right hand side)

### ISSUE THREAD

**Issue by skewty** [getferdi/ferdi#1044]
### Is your feature request related to a problem? Please describe.

When I size Ferdi to use all horizontal space on a portrait oriented monitor there is a purple colored line 1px in size on the right hand side of all my services.  It looks like the service pane is 1px too small.  See attached image.

![image](https://user-images.githubusercontent.com/9087223/97197975-85e13300-176b-11eb-8f34-617a0b7aa965.png)

### Describe the solution you'd like

I'd like the service pane to use all the available space and for that bright colored line to not be displayed.

### System Info

Win 10 Ent
Ferdi 5.5.0 x64
Electron 8.2.4
Node.js v12.13.0
Platform: win32

**Comment by Lazza** [comment]
Check if you have enabled the To-Dos in the preferences. I had enabled them without realizing and it was showing similar to that.

**Comment by kris7t** [comment]
Fixed in #1398
