### ISSUE TITLE
Reddit 'comments' button always opens a new window

### ISSUE THREAD

**Issue by ackstorm23** [getferdi/ferdi#1049]
**Bug description:**

Clicking on 'comments' always pops up a new window

**Steps to reproduce:**

1. Go to 'Reddit service in Ferdi'
2. Click on '(xxx) comments' for any post
3. See new window pop-up

**Expected behavior**

Post with comments loads within the original window

**Screenshots**

Can provide if asked

**Environment:**

- Operating System: Manjaro Linux
- Ferdi Version: 5.6.0-beta1
- Server: Ferdi

- Debug information:

Prefer not to paste this in public

**Comment by ackstorm23** [comment]
I no longer use your product. 



Close this.

**Comment by vraravam** [comment]
Just fyi - this has been fixed.
