### ISSUE TITLE
AppVeyor maximum storage exceeded

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#105]
**Describe the bug**
"Maximum allowed artifact storage size of 50000 Mb will be exceeded." is the message from AppVeyor and It is showing error on the build and dosn't give .exe since there is no free space.
https://ci.appveyor.com/project/kytwb/ferdi/builds/27917120

**To Reproduce**

1. Do a commit/merge/pull request

**Expected behavior**
Should do the build as before

**Comment by kytwb** [comment]
I have sent a message to AppVeyor support to get the limit increased.

**Comment by kytwb** [comment]
Escalated to a ticket: https://help.appveyor.com/discussions/problems/25122-maximum-allowed-artifact-storage-will-be-exceeded

**Comment by kytwb** [comment]
@Makazzz fixed, artifacts available again at https://ci.appveyor.com/project/kytwb/ferdi/build/artifacts

**Comment by Makazzz** [comment]
@kytwb @vantezzen The problem is now re-happening with the last 2 build :/ 

> Maximum allowed artifact storage size of 80000 Mb will be exceeded.

**Comment by kytwb** [comment]
As mentioned [here](https://help.appveyor.com/discussions/problems/18191-setting-autodelete-policies-for-deleting-old-artifacts):

> We do not expose deletion of specific artifacts. For those who collect them faster than our retention policy we are OK to increase as long as we do not see and abuse.

I will ask to increase our limit again temporarily, and enable artifacts collection on master and tags build only in `appveyor.yml`, that should fix the issue.

**Comment by kytwb** [comment]
Artifacts collection is now restricted to master/tags builds. I have followed-up on the [ticket](https://help.appveyor.com/discussions/problems/25122-maximum-allowed-artifact-storage-will-be-exceeded) for another temp limit increase in the meantime.

**Comment by kytwb** [comment]
Someone from AppVeyor followed up on the [ticket](https://help.appveyor.com/discussions/problems/25122-maximum-allowed-artifact-storage-will-be-exceeded) to say it's been extended.
