### ISSUE TITLE
Remove unused translation strings

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#1053]
Thanks to @madsmtm for the feedback via https://github.com/getferdi/ferdi/pull/979#issuecomment-719693822.

We could remove unused strings as to clarify the codebase and reduce the number of unused strings submitted for translation to contributors on [Crowdin](https://crowdin.com/project/getferdi).

**Comment by mhatvan** [comment]
I upgraded `react-intl` and moved from deprecated `babel-plugin-react-intl` to `babel-plugin-formatjs` in https://github.com/getferdi/ferdi/pull/1920

`formatjs` detects unused translation strings automatically and deletes them.
