### ISSUE TITLE
High CPU use even when idle

### ISSUE THREAD

**Issue by squalou** [getferdi/ferdi#1054]
Hi,

I'm trying ferdi, comparing it to other electron app around.
It's a really pleasant product but I noticed some weird CPU use.
More precisely:
- linux box with decent cpu (core i7 from 2018)
- ferdi configured with only one service (google chat if you wanna know)
- using ferdi 5.5.0
- no todos
- disabled telemetry (to eliminate potential background task)
- display in systray
- dont quit on close
- 'close' to reduce in systray
- wait a bit

There are constantly 2 processes eating up 2 to 3 % cpu each.
To do ... nothing or barely.
`/opt/ferdi/ferdi --type=renderer` and `/opt/ferdi/ferdi --type=gpu-process`

When window is not minimized (but not in foreground either : masked by another window), it eats around 25% cpu constantly

I understand that the underlying service is a pain itself : having google chat own electron app or inside chrome tab is also 'heavy' on resources, but not as much.

A bare electron app dedicated to this service, in hidden mode, would eat 1-2% 

I also tried the 'hibernate' feature : it has absolutely no effect.

Even if electron and nodejs are not known not be energy efficient, when compared to something like visual code that *does* lots of things, it feels like there's room for improvement on ferdi side.

I would be glad to help anyhow, 

thanks for reading

**Comment by kris7t** [comment]
Universal Dark Mode (Settings > Appearance > Enable universal Dark Mode) is known to cause this with some services (in conjunction with some Electron versions). See https://github.com/getferdi/ferdi/issues/62 for more details.

Note that hibernation only suspends the services that are not currently selected, even if Ferdi is minimized. So you may try to disable the service manually to make sure it's unloaded even if selected in the sidebar (for testing purposes only, of course, as this would be unworkable for prolonged use).

The upcoming Ferdi 5.6.0 with updated Electron might alleviate some of these issues.

**Comment by squalou** [comment]
Thx ! 
indeed : univsersal dark mode seems to be the one to blame.

Now it's "on par" with my other electron app, great news.
