### ISSUE TITLE
Adapt app icon for macOS 11.0 Big Sur

### ISSUE THREAD

**Issue by MarceloAvalos** [getferdi/ferdi#1056]
**Is your feature request related to a problem? Please describe.**
macOS 11.0 Big Sur is launching over the next few weeks and it introduces a new rounded-rectangle shape for app icons (like iOS app icons, but not 100% equal). Apps that adapt to the new icon specs feel more native and familiar in the OS.

**Describe the solution you'd like**
Adapt the Ferdi app icon for the macOS build, following the [specs provided by Apple](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/).

**Describe alternatives you've considered**
N/A

**Additional context**
The app package can only store one icon, and it's fine that users on previous versions of macOS see the new icon (this will happen with most apps as they adapt to the new icon specs.)

**Comment by alopix** [comment]
I've created an icon, if you want to use it.

[Ferdi.sketch.zip](https://github.com/getferdi/ferdi/files/5654654/Ferdi.sketch.zip)

**Comment by MarceloAvalos** [comment]
@alopix thank you! I've never used Sketch, would you mind posting the highest res version here as a PNG file please?

I found this guide that shows how to change the icon for any Mac app you have: https://9to5mac.com/2019/01/17/change-mac-icons/

**Comment by alopix** [comment]
@MarceloAvalos you can find the img in the linked #1100 ticket

**Comment by Akecel** [comment]
+1

It would be really cool as an update, I just switched to Ferdi from Franz, I'm glad but the little icon problem on BigSur is hurting my maniac side 😌

**Comment by kris7t** [comment]
Fixed in #1333
