### ISSUE TITLE
WhatsApp is not being able to read the QR Code

### ISSUE THREAD

**Issue by lisandrocarmona** [getferdi/ferdi#1058]
Hi, Ferdi is working like a charm and I can add all the services I need.
However, WhatsApp can't be added as the QR Code can't be read. I can add the account using Chrome (both Windows and Linux), but Ferdi does not read the QR Code.
Is it only me? Any hint to let me add WhatsApp?

Other app that is not working is Asana (Browser not supported).

Thank you.

**Comment by vantezzen** [comment]
Do you have Ferdi's dark mode enabled? If so, please disable the darkmode in settings before trying to scan WhatsApp's QR Code. You can reenable it afterwards

**Comment by lisandrocarmona** [comment]
Thank you for reaching out. If disable both "universal dark mode" and the "dark mode" into WhatsApp settings. Quit and restarted Ferdi, but it did not work.

**Comment by lisandrocarmona** [comment]
Tested again and it worked (disabling the dark mode). Thank you.

Asana not loading continue to be an issue.

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case. I am able to scan the WhatsApp QR code in both dark mode as well as light mode on macos Big Sur.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)
