### ISSUE TITLE
WhatsApp does not work with 5.6 beta 2

### ISSUE THREAD

**Issue by alopix** [getferdi/ferdi#1061]
**Bug description:**
WhatsApp keeps showing the message that it only works with Google Chrome 60+

**Steps to reproduce:**
Update to 5.6 beta 2 and add a WhatsApp service on macOS.

**Expected behavior**
WhatsApp works as it did in 5.5 😉

**Screenshots**
![image](https://user-images.githubusercontent.com/124467/98453584-c1f49a80-2152-11eb-947f-d6e9508b7dc8.png)
![image](https://user-images.githubusercontent.com/124467/98453592-c9b43f00-2152-11eb-8036-d9e531223497.png)

**Environment:**

- Operating System: macOS 10.15.7
- Ferdi Version: 5.6-beta.2
- Server: Ferdi

**Comment by qrft** [comment]
It works for me, if you update the browser agent to the new chrome. Just go to the recipe folder and create an index.js file with following content:

`"use strict";

module.exports = Franz => class Messenger extends Franz {
  overrideUserAgent() {
    return "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36"
  }
};`

**Comment by bikasv** [comment]
@qrft this works for me

**Comment by Shankar1598** [comment]
How do I go to the "recipe" folder? where is it located? :)

**Comment by qrft** [comment]
> How do I go to the "recipe" folder? where is it located? :)

Under Linux it should be in ${XDG_CONFIG_HOME}/Ferdi/recipes/whatsapp

But you can check and open the folder if you open your Whatsapp Service in the Ferdi Settings and Select "Open user.js" to open the containing folder.

**Comment by lavjau** [comment]
Thanks you, it works for me too ;)

**Comment by nilicule** [comment]
This worked for me too, but I had to remove and re-add WhatsApp.

Force reloading didn't seem to do the trick.

**Comment by jsondhelm** [comment]
worked for me, but now whatsapp badge does not work

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case. I run Ferdi with WhatsApp on all the time.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

**Comment by alopix** [comment]
I just downloaded the latest nightly and did not even have to manually upgrade recipes (auto update services worked).

**Comment by vraravam** [comment]
@alopix - did you get the nightlies from the github repo or my gDrive? I am also trying to validate the versions that I am uploading into gDrive - so that info would be helpful.

**Comment by alopix** [comment]
@vraravam Sorry, I downloaded it from the github repo. The -mac.zip did not work btw (You do not have permission to open the application “Ferdi.app”.) but the dmg worked fine.

**Comment by vraravam** [comment]
This a security thing from macos Catalina onwards, you will have to run `sudo xattr -rd com.apple.quarantine </path/to/Ferdi.app>` to fix the issue. This occurs for all apps that are not downloaded from the Mac App Store.

**Comment by alopix** [comment]
I actually did think it would be the new security feature, but it somehow wasn’t. Had tried unsetting that attribute but it had not worked at all somehow. You have not started signing releases again, have you? I do suspect that might be the issue, since I do allow App Store and Signed Devs.

**Comment by vraravam** [comment]
Unfortunately, that's the step we are grappling with atm. The security cert has expired and waiting for @kytwb who is following up with issuing company. Once that is put in, we should be able to start releasing nightlies.
