### ISSUE TITLE
Custom Service not workin

### ISSUE THREAD

**Issue by Askerion** [getferdi/ferdi#1065]
**Bug description:**
I am desperately trying to add my own service, unfortunately the login window does not appear on the Ferdi Client

**Screenshots**
![2020-11-10 17_35_53-](https://user-images.githubusercontent.com/25051192/98703544-e4b5c780-237b-11eb-916a-170f38a067a7.png)
]
**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.5.0

**Comment by vantezzen** [comment]
Ferdi doesn't currently have any support for basic authentification on websites

**Comment by francwalter** [comment]
> Ferdi doesn't currently have any support for basic authentification on websites. This is due to Electron not supporting is by default

Is there a list of supported websites (services) in Ferdi?
I want to add schul.cloud, **with** (permanent) login, which is in (buggy) Rambox possible, but I don't see how to add it in Ferdi (in Franz it was not possible, as I remember).
Thanks.frank

**Comment by vantezzen** [comment]
@francwalter You can find a list of supported services at https://getferdi.com/services/. If you want to create your own service ("recipe") we have written a guide about that at https://github.com/getferdi/recipes/blob/master/docs/integration.md

**Comment by francwalter** [comment]
OK, [Hamsket](https://github.com/TheGoddessInari/hamsket) is it :)
A clone of Rambox without its abandoness ;)

**Comment by vraravam** [comment]
@francwalter - were you able to find a solution for this issue? Can we close it?

**Comment by francwalter** [comment]
Yes, the solution is Hamsket ;)
Can close.
