### ISSUE TITLE
GVoice Couldn't sign you in

### ISSUE THREAD

**Issue by Dukko** [getferdi/ferdi#1067]
When I try to login as of last week, I am greeted with this page.

![image](https://user-images.githubusercontent.com/1922688/98984507-ea302080-24e7-11eb-91e2-d62aac151c26.png)

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

**Comment by mhatvan** [comment]
Closing due to no response and old issue.
