### ISSUE TITLE
Linux version doesn't connect and can't be used

### ISSUE THREAD

**Issue by stefanobartoletti** [getferdi/ferdi#1069]
I'm testing this on openSUSE, I'm using Flatpak version but this also happens on the `.rpm`.

Once installed and launched, the main window appears but the app can't connect to the online services, and I can't proceed further than this initial screen.

![Screenshot_20201116_121647](https://user-images.githubusercontent.com/36746429/99246744-190b0700-2806-11eb-923a-e70588086b36.png)

I wish to use Ferdi without an account, but clicking on that button apparently has no effect. 

Also, as you can see on my screenshot, the white box that is supposed to display icons for supported services is completely empty.

Is this problem something related to my local configuration?

Please let me know if you need more info to help me solve this problem.

**Comment by bundyo** [comment]
Can confirm this - also on openSUSE.

**Comment by bundyo** [comment]
This helped:

https://github.com/getferdi/ferdi/issues/396#issuecomment-890928962

> Seems localhost in /etc/hosts is the problem. If specified like this:
> 
> ```
> 127.0.0.1     localhost
> ```
> 
> Ferdi refuses to connect. If static hostname is also added:
> 
> ```
> 127.0.0.1     localhost hostname
> ```
> 
> Ferdi works. Not a problem with any other software with this, looks like a bug to me.

**Comment by stefanobartoletti** [comment]
Right now the flatpak version works fine for me

**Comment by vraravam** [comment]
Is this still an issue?

**Comment by bundyo** [comment]
Looks like it is working with 5.6.1-beta.1.
