### ISSUE TITLE
How to backup and restore

### ISSUE THREAD

**Issue by dorukkarinca** [getferdi/ferdi#1074]
When uninstalling and reinstalling Ferdi, I would like to recover things that aren't synced to the servers such as custom darkmode.css.

What is the standard way to backup and restore? Is it sufficient to zip up the `recipes` folder and then unzip?

**Comment by vantezzen** [comment]
Yes, backing up the recipes folder is sufficient. If you want to, you can also backup the config folder to restore all your settings
