### ISSUE TITLE
[Windows] can't password protect

### ISSUE THREAD

**Issue by HpVaC** [getferdi/ferdi#1086]
whenever i try to enable the password protect option i get an "an error has ocurred" message, then screen goes either full purple or black, and nothing can make it work again, i have to uninstall and erase the full folder, deleting settings.json does not work

**Bug description:**

**Steps to reproduce:**

**Expected behavior**

**Screenshots**

**Environment:**

- Operating System: 
- Ferdi Version: 
- Server: 

- Debug information:

**Comment by GillesWHC** [comment]
I've got the same issue on Arch with KDE.
