### ISSUE TITLE
Should allow an option to "minimize to taskbar" but "close to tray"

### ISSUE THREAD

**Issue by IAmNotAJerk** [getferdi/ferdi#1087]
As titled. I'm a Windows 10 user, not sure if this is applicable to other OS.
In the current settings, we are only able to either "close and minimize to tray", or "close and minimized to taskbar", which is pretty stupid for those two keys becomes the same thing. 
(This is useful in the occations like sometimes you want to keep Ferdi "alt-tab-able" while sometimes you don't but you want to keep receiving notifications. 
Franze does not have this feature as well. On the other hand, Rambox does this.

**Comment by JustCarousell** [comment]
Previously I've also raise up this issue before but there wasn't a follow up to it when it seems like it's a simple solution and hope this new open issue might highlight this again and hope they can make the change.
