### ISSUE TITLE
Page not found when using Skype

### ISSUE THREAD

**Issue by minhduc0711** [getferdi/ferdi#1090]
**Bug description:**

Skype would just show a Page not found screen. It worked normally until today. 
Re-adding the services and re-login makes it work again, but only for a while before the error happens again.
Update: it randomly works again as well

**Steps to reproduce:**

Log into Skype and close/reopen the app a few times.

**Expected behavior**

Skype does not show this page not found screen.

**Screenshots**

![image](https://user-images.githubusercontent.com/34294427/100696555-62428580-33c6-11eb-90d7-856e935f45b7.png)

**Environment:**

- Operating System: Arch Linux 
- Ferdi Version: 5.5.0 
- Server: Ferdi 

- Debug information: https://pastebin.com/raw/5yj45h7P

**Comment by leandrogehlen** [comment]
👍

**Comment by huyhoang8398** [comment]
Same issue in version 5.6.0 nightly build

**Comment by indeed-a-genius** [comment]
Workaround: instead of re-adding the service and re-login, you can:
- click on the "Go to Skype.com homepage" link
- scroll to the bottom and click the blue "Chat now" button

**Comment by mhatvan** [comment]
Cannot reproduce this with the latest releases. This was probably a temporary issue.

![Screenshot from 2021-09-19 20-58-57](https://user-images.githubusercontent.com/16797721/133939531-bffe3291-8e02-4dd1-ad76-bf8328e21d00.png)
