### ISSUE TITLE
Flickering on other services when using Riot/Element

### ISSUE THREAD

**Issue by hng** [getferdi/ferdi#1092]
**Bug description:**

If Riot/Element is added as a service other services start flickering if activated (e.g. Mattermost and Telegram). If Riot/Element is removed the flickering stops.

Tried ferdi 5.5.0 and 5.6.0-beta2 both have this issue.

**Steps to reproduce:**

1. Add Riot/Element as a new service
2. Switch to another service, move mouse and see flickering
3. Log in to Riot/Element
4. Use other service and notice flickering
5. Disable or remove Riot/Element service
6. No more flickering with other services

Used with https://app.element.io and https://riot.im/app/ as service URLs.

**Expected behavior**

There should be no flickering.

**Environment:**

- Operating System: macOS Big Sur
- Ferdi Version: 5.5.0 and 5.6.0-beta2
- Server: Using without an account

**Comment by YoussefChachia** [comment]
I am having the same issue with Ferdi 5.6.0-beta5.

If I add riot or element, all other services start to flicker.

**Comment by vraravam** [comment]
Please try with the latest nightlies and/or report the information about which version of Ferdi you are using?

**Comment by YoussefChachia** [comment]
I do not reproduce the issue with the latest nighly build, thank you !

**Comment by vraravam** [comment]
@hng - could you also please try the workaround with the latest recipes? and if it works, please close this bug?

**Comment by hng** [comment]
@vraravam I've tested the nightly build on macOS and it looks like the issue is fixed now. Thanks! :)
