### ISSUE TITLE
Can't login to Gmail when service was already created

### ISSUE THREAD

**Issue by tswistak** [getferdi/ferdi#110]
**Describe the bug**
It's impossible to log in to Gmail account for already existing services. After creating a new service, everything works OK, I'm redirected to the login page and I can log in without problems. But, when I want to login to existing Gmail service (or I reload a new one) I'm redirected to Gmail's home page, where clicking on Login redirects me to an external browser, therefore it's impossible to log in.

**To Reproduce**

1. Create a Gmail service
2. Open it. Login window should be visible
3. Right-click on a service icon and click Reload
4. Click Login link to redirect to login

**Expected behavior**
I should be redirected to Gmail's login page inside Ferdi app, not in an external browser

**Screenshots**
![image](https://user-images.githubusercontent.com/9076255/66563046-35e1ff00-eb5d-11e9-829b-fa7c82b3ef3f.png)

**Desktop (please complete the following information):**

- OS: macOS 10.14.6 (I was also able to reproduce it on Windows 10)

**Additional context**
I don't know whether this bug appears also in Franz. I haven't seen it in their Issues list.

**Comment by tswistak** [comment]
5.3.3.157

**Comment by Makazzz** [comment]
Ok I did the test on the 5.3.3 stable release and I have the same result. The service when is reload after restarting the app become with only external link and not the same connection page.

**Comment by vraravam** [comment]
I had the same experience. I deleted my gmail service, readded it, and the account login screen showed up and I was able to login. Once done, I clicked and dragged it to the requisite order I wanted in the services-tabs ribbon.

**Comment by tswistak** [comment]
That's not exactly a solution when you're working on multiple computers with Ferdi cloud synchronization. After removing and readding on the first computer, I'll run into the same issue on a second computer.

**Comment by vantezzen** [comment]
There seems to be a new version of the gmail recipe available - will update the recipe repository

**Comment by probablykasper** [comment]
For anyone who doesn't want to delete and re-add their service, you can click View > Open Service Developer Tools and type this into the console:
```js
location.replace('https://accounts.google.com/AccountChooser?service=mail&continue=https://mail.google.com/mail/')
```

**Comment by kytwb** [comment]
Alternatively, v5.4.0 comes with a settings option to show the address bar in services. This can be used to temporarily remediate this kind of issues.
