### ISSUE TITLE
Closing the GUI app doesn't terminate electron processes

### ISSUE THREAD

**Issue by morrieinmaas** [getferdi/ferdi#1101]
Closing Ferdi doesn't kill all running electron processes. When I close Ferdi via the GUI as one normally would by hitting the x button in the top bar Ferdi closes and appears to not be running as indicated in the Gnome dock. Looking at htop though there are still electron processes running and they are quite hungry. I made sure I had no other elelctron-based apps running like VSCode or sth similar.   

OS/env:
Using GNOME 3.38.2  on Arch Linux with kernel 5.9.11

**Steps to reproduce:**
Use Gnome shell on arch, install Ferdi, install a few services like whatsapp, telegram and gmail, use them, close the app. check system processes e.g. with htop.

**Expected behavior**
Killing the app via the GUI kills all app processes.

**Screenshots**
App open and running:
![Screenshot-20201205223754-933x641](https://user-images.githubusercontent.com/10432473/101266051-f6587800-374b-11eb-905c-b3d1b96119d1.png)

App closed:
![Screenshot-20201205223919-1113x646](https://user-images.githubusercontent.com/10432473/101266056-fce6ef80-374b-11eb-8161-f9151b13d3c8.png)

**Comment by mhatvan** [comment]
@morrieinmaas can you reproduce this with the latest Ferdi Version? We now use electron 13 instead of electron 8, so that makes a big difference.

**Comment by mhatvan** [comment]
Tried to reproduce this with `htop` same like the author. 

All Ferdi electron processes are correctly terminated on app quit.

Verified on macOS Big Sur running 5.6.1-nightly.27
