### ISSUE TITLE
Gmail blocks open in a new window

### ISSUE THREAD

**Issue by isabellatimossi** [getferdi/ferdi#1102]
Hello, 

I'm experiencing this issue where every time I click on a link from Gmail it won't let me open it and a window comes up saying that popups are likely blocked. Any other service works correctly (links on Whatsapp, Telegram, etc). Any idea of how I should fix it? It's very important to be able to me to click on the links I receive by email.

Thank you!

**Comment by vraravam** [comment]
This is now fixed by https://github.com/getferdi/ferdi/pull/1474 - which has just been merged! Please pull and rebuild from source, or wait for tonight's nightly build.
