### ISSUE TITLE
Slack won't continue to sign-in screen using single sign-on

### ISSUE THREAD

**Issue by christowiz** [getferdi/ferdi#1104]
**Bug description:**

When attempting to log in using an account that uses single sign-on the page just reloads and is unable to continue the log in process.

**Steps to reproduce:**

1. Slack account displays a login screen
2. Click on "Sign in with XXX ID"
3. Page refreshes

**Expected behavior**

When clicking on "Sign in…" button it should take the user to the Google account login screen.

**Screenshots**

![image](https://user-images.githubusercontent.com/597282/101399240-0ecbae00-3884-11eb-9675-d0feba5e0656.png)

**Environment:**

- Operating System: macOS Mojave
- Ferdi Version: Version 5.5.0 (5.5.0.2116)
- Server: Franz

- Debug information:

[ferdi_debug.txt](https://github.com/getferdi/ferdi/files/5655082/ferdi_debug.txt)

**Comment by vraravam** [comment]
Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

**Comment by roa-nyx** [comment]
@vraravam I was hoping that I could just upgrade the recipes without having to download the nightlies at this point, but that didn't work for me.

Do you know if this is something you will merge back to the master branch? It feels like not being able to sign into Slack is a bit of a showstopper.

**Comment by vraravam** [comment]
@roa-nyx - the nightlies are being built from the main codebase / repo /  branch - ie all this is already merged.

btw - I use the nightlies as they get built - (eating our own dogfood)

**Comment by roa-nyx** [comment]
@vraravam good to know. I guess I'll switch to nightlies for now and keep an eye out for a new release.

**Comment by roa-nyx** [comment]
@vraravam just tried nightly Ferdi. On first launch it crashed. On second launch I could continue signing into various services, but Slack still wouldn't sign in, so I thought I would try to update the recipes again. So I turned off Ferdi, updated the recipes, and tried running Ferdi again. It just keeps crashing on every load now.

**Comment by vraravam** [comment]
@roa-nyx - which version of Ferdi are you using? What does the recipe's version show up as ?

I use Slack recipe version 1.0.16 (in the recipe/service preferences screen - scroll at the way to the end)

**Comment by vraravam** [comment]
And, at least on mac, Ferdi keeps crashing on app-start (I dont have an explanation for this), but randomly switching the registered services using `Cmd+<number>` tends to overcome the crash-point and then Ferdi is usable as normal. I haven't been able to investigate when this crash started or why its happening.

**Comment by roa-nyx** [comment]
Installed from Ferdi-Setup-5.6.0-nightly.57.exe

This time it didn't crash. I think maybe I triggered the settings window and that pre-empted the crash somehow.

Recipe screen reports: 1.0.16

I still can't sign in with Google SSO (I don't know what OKTA-based corporate login/auth means).

I didn't do any modifications to any recipe files.

**Comment by vraravam** [comment]
I think there's a version that's even newer than v57 - please try that one.

Yes - we also use Google SSO - and its working with that for my company's setup.

**Comment by roa-nyx** [comment]
I got the latest release from: https://github.com/getferdi/nightlies/releases

Am I looking in the wrong place maybe?

**Comment by vraravam** [comment]
Sorry, yes, that is the main repo (but, currently broken due to the code signing bit not working).

I have been running the same code/build steps and publishing *unsigned* [here](http://github.com/vraravam/nightlies/releases). Please try from here.

Also - this is my corporate slack with the notification blue circle: 
<img width="33" alt="Screen Shot 2021-06-25 at 7 45 36 PM" src="https://user-images.githubusercontent.com/69629/123438265-2420e380-d5ee-11eb-89c2-011ce822020a.png">

**Comment by roa-nyx** [comment]
@vraravam Sorry again, the link you provided is the same link I provided. Did you maybe copy paste the wrong link?

**Comment by roa-nyx** [comment]
Nevermind. I see the difference! One moment while I try it.

**Comment by roa-nyx** [comment]
Now opening the settings menu or trying Ctrl+# to switch tabs doesn't pre-empt the crashes anymore...

I think this isn't a viable solution for me at this point. I appreciate the support, but I definitely don't feel I can rely on this as it stands.

**Comment by Quentin-M** [comment]
Also having issues signing in with SSO due to the old browser version detected by our SSO system when Ferdi loads the page. Ideally would either bump the internal browser version/library, or let us log in in a regular browser, then back into Ferdi.

**Comment by vraravam** [comment]
For the technical users here:
Most websites use the `user-agent` that the request hits the server with - to determine whether the browser is old/accepted/supported or not. In the latest nightlies (found [here](http://github.com/vraravam/nightlies/releases)) - there is now the ability *for the user* to set a global value or also a value for a specific recipe.

As mentioned above, I am also on slack, with a SSO login - and am not facing any issues (even without overriding the `user-agent` setting) - but, at least this ability to override will allow you to proceed farther. Please try it out and report back.

**Comment by mhatvan** [comment]
Core issue seems to be outdated, closing.

Please open a separate ticket for unrelated issues, in case they still occur.
