### ISSUE TITLE
Create ARM64 build for Apple arm64 architecture

### ISSUE THREAD

**Issue by kdlancer** [getferdi/ferdi#1106]
**Is your feature request related to a problem? Please describe.**
Electron apps compiled for X86-64 run very poorly on computers using the new Apple arm64 architecture using the Rosetta 2 translation layer.

**Describe the solution you'd like**
It would be amazing to have a build of franz using the new Electron version 11 that has support for Apple arm64.

**Describe alternatives you've considered**
There are currently no alternatives to this, so you'd likely be the first!

**Additional context**

**Comment by gidehault** [comment]
it will be so useful ! I love Ferdi but I have to admit that I have to keep it closed to my new Mac M1, as it ruins performances of the whole OS

**Comment by reisub0** [comment]
@vantezzen Any idea what would be required to get a build working? I just wanted to get a build running and couldn't due to the following error 
```
> ferdi@5.6.0-nightly.13 prebuild
> gulp build

[15:18:41] Requiring external module @babel/register
/Users/g/ferdi/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Unsupported runtime (88)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.0
    at module.exports (/Users/g/ferdi/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/g/ferdi/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (/Users/g/ferdi/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (/Users/g/ferdi/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
npm ERR! code 1
npm ERR! path /Users/g/ferdi
npm ERR! command failed
npm ERR! command sh -c gulp build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/g/.cache/npm/_logs/2021-01-22T09_48_42_372Z-debug.log
```

**Comment by danielporto** [comment]
@gidehault is it still that bad?
I was about to install it.

**Comment by titolopolous** [comment]
I would also love to have an ARM build for Macs. I do not know how relevant this is, but I think Electron supports Apple Silicon for a while now.

**Comment by titolopolous** [comment]
I would also love to have an ARM build for Macs. Electron supports Apple Silicon for a while now.

**Comment by vraravam** [comment]
+1 - I am on a mac M1 and would love a version that runs natively as opposed to through rosetta.

**Comment by arioki1** [comment]
https://github.com/getferdi/ferdi/issues/875

**Comment by arioki1** [comment]
> @vantezzen Any idea what would be required to get a build working? I just wanted to get a build running and couldn't due to the following error
> 
> ```
> > ferdi@5.6.0-nightly.13 prebuild
> > gulp build
> 
> [15:18:41] Requiring external module @babel/register
> /Users/g/ferdi/node_modules/node-sass/lib/binding.js:13
>       throw new Error(errors.unsupportedEnvironment());
>       ^
> 
> Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Unsupported runtime (88)
> For more information on which environments are supported please see:
> https://github.com/sass/node-sass/releases/tag/v4.14.0
>     at module.exports (/Users/g/ferdi/node_modules/node-sass/lib/binding.js:13:13)
>     at Object.<anonymous> (/Users/g/ferdi/node_modules/node-sass/lib/index.js:14:35)
>     at Module._compile (node:internal/modules/cjs/loader:1108:14)
>     at Module._compile (/Users/g/ferdi/node_modules/pirates/lib/index.js:99:24)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
>     at Object.newLoader [as .js] (/Users/g/ferdi/node_modules/pirates/lib/index.js:104:7)
>     at Module.load (node:internal/modules/cjs/loader:973:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
>     at Module.require (node:internal/modules/cjs/loader:997:19)
>     at require (node:internal/modules/cjs/helpers:92:18)
> npm ERR! code 1
> npm ERR! path /Users/g/ferdi
> npm ERR! command failed
> npm ERR! command sh -c gulp build
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/g/.cache/npm/_logs/2021-01-22T09_48_42_372Z-debug.log
> ```
did you manage to run `npx lerna bootstrap` on m1 I did not

**Comment by vraravam** [comment]
Looks like we will need to run electron v11 (which also brings in upgrades to node/npm) so that it can be run on M1 machines.
Link: https://www.electronjs.org/blog/electron-11-0

**Comment by vraravam** [comment]
> did you manage to run `npx lerna bootstrap` on m1 I did not

nope - just tried the same, and the version of node is too old for this architecture (`arm64`).

**Comment by arioki1** [comment]
why not try using the latest version electron, it also seems to support m1 @vraravam

**Comment by arioki1** [comment]
do you know to fix the issue when running `npx lerna bootstrap` failed

**Comment by vraravam** [comment]
Unfortunately, I'm not a nodejs developer to be able to quickly fix the
issue since its a major-version change in electron, it might involve code
changes to be compatible (I just dont know).

**Comment by arioki1** [comment]
me as getting this error when wanting to upgrade electron 10.2.0 to latest
```
➜  ferdi git:(develop) npm install electron@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react-dom@16.12.0
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"16.12.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-dom@"16.7.0" from forms@1.2.1
npm ERR! packages/forms
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/yogasetiawan/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yogasetiawan/.npm/_logs/2021-04-13T02_49_20_144Z-debug.log
```

**Comment by vantezzen** [comment]
Closing this issue in favor of #875 so we don't have two issues where we discuss Ferdi on ARM.
