### ISSUE TITLE
Install service Lastpass

### ISSUE THREAD

**Issue by artesan0** [getferdi/ferdi#1107]
Hi,
I'm new trying Ferdi, but I need Lastpass, yes or yes.

I saw the service in Ferdi website, that's one of the main reasons why I chose Ferdi, but when I try to install it, I cannot find it.

Could you help me, please?

**Comment by tofran** [comment]
@artesan0 LastPass is only available in the new [nightlies releases](https://github.com/getferdi/nightlies)
Unfortunately the website is showing automatically all the new [recipes](https://github.com/getferdi/recipes/) creating this confusion for some users.

**Comment by vraravam** [comment]
Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)
