### ISSUE TITLE
Facebook Messenger Doesn't Work

### ISSUE THREAD

**Issue by entozoon** [getferdi/ferdi#1108]
I can log into messenger no problem, but all my conversation icons are greyed out and can't send messages.

Using latest Ferdi on Mac OS, and the problem should be something obvious to a dev because the console is logging errors:

```
GET https://www.messenger.com/rsrc.php/v3/yD/r/rlA4pw-3d_K.png 404
ErrorUtils caught an error:
Client disconnected

WebSocket connection to 'wss://edge-chat.messenger.com/chat?region=lla&sid=8371693053542399&cid=41305cd6-bd4b-444f-810f-18a93d017933' failed: Error during WebSocket handshake: Unexpected response code: 503
```

I know Franz has been having an issue for a few days where messenger shows the [entirety of Facebook](https://github.com/meetfranz/franz/issues/1937) so I'm wondering if the Facebook Overlords™ have elected to block apps like this, forcing us to use their app?

UPDATE: I appear to  be getting the same websocket error even on facebook.com in a browser, so perhaps the whole system is janked?

**Comment by JoelPintoRibeiro** [comment]
+1

**Comment by kris7t** [comment]
There seems to be an ongoing major outage at Facebook: https://developers.facebook.com/status/dashboard/
