### ISSUE TITLE
Expose Electron version information in "About Ferdi"

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1109]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but imo, exposing the Electron version in the "about" dialog will enable others to know if/when there's a security-related issue discovered in an older version of electron.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pandruszkow** [comment]
I can +1 that. I've had certain sites break on on older Electron engines when I used Rambox, so it's good to be able to check the version quickly to eliminate this as the source of the issue.

**Comment by vraravam** [comment]
please remove staleness

**Comment by kris7t** [comment]
At least for me, there's a menu item `? > About Ferdi` in the main menu, which exposes Electron and Node.js version information.

![ferdi-version](https://user-images.githubusercontent.com/38888/116332309-cc265600-a7d1-11eb-8765-30be9d1b87af.png)

(Pay no attention to the Ferdi version, it's not a nightly build, but a local commit.)

**Comment by vraravam** [comment]
<img width="276" alt="Screen Shot 2021-04-28 at 7 00 11 AM" src="https://user-images.githubusercontent.com/69629/116332454-6cd73e80-a7ef-11eb-8d9a-49ee35336a22.png">

This is what I get on macOS :(

**Comment by kris7t** [comment]
Ah, so for some odd reason, Electron has an about dialog vastly reduced in usefulness under macOS. That's very odd.

**Comment by vraravam** [comment]
oh - is this the default "about dialog" from Electron? Then, I should raise the FR with them, i suppose? As opposed to raising it here within Ferdi?

**Comment by vraravam** [comment]
thanks - i have raised [this issue](https://github.com/electron/electron/issues/28879) - please upvote.

**Comment by vraravam** [comment]
I just raised a [PR](#1309) - please upvote.
