### ISSUE TITLE
Ferdi dock icon randomly bounce

### ISSUE THREAD

**Issue by SylvainCecchetto** [getferdi/ferdi#111]
**Describe the bug**
Randomly, the dock icon of Ferdi just bounce one time, but I have no notification on any of my services.

**To Reproduce**
Work on any app on your app and just wait until the icon bounce.

**Expected behavior**
No bounce?

**Desktop (please complete the following information):**

- OS: macOS 10.14.6
- Version 5.3.3 (5.3.3.157)

**Comment by vantezzen** [comment]
Have had this happen to me with Franz before.
When this happens, can you do the following:
- In Ferdi's menubar, under "View" click "Toggle Developer Tools"
- In the now opened Developer Tools, in the top row, click "Console" (you may have to click on the two arrows to see it)
- Scroll down if needed and take a screenshot of the last few messages
- Upload this screenshot here

**Comment by SylvainCecchetto** [comment]
I just had a bounce, this is a screenshot of the console.
The penultimate line is a message from a friend on the Riot service (but I get his message at least one hour before the bounce).
And the last line seems to be related to the  penultimate line because of a missing image in the Riot message of my friend jp.

So I guess there is nothing in this screenshot concerning the bounce :-/

![Capture d’écran 2019-10-14 à 15 13 02](https://user-images.githubusercontent.com/11562279/66754228-cdb15700-ee95-11e9-801d-5fd49c195a7a.png)

Let me know if you need something else ;-)

**Comment by kytwb** [comment]
The dock icon will bounce on Mac if an update is available/downloaded: https://github.com/getferdi/ferdi/blob/d8d5df6e72163b00e035f729b1013a957fed2321/src/stores/AppStore.js#L147 Maybe we should put a notification badge on the settings icon when that's the case?

**Comment by SylvainCecchetto** [comment]
Thank you for the explanation, but I'm on 5.3.3 and it's the latest release available.
Is this function also check for beta versions on GitHub? Maybe it's better to only bounce if a new release is available?

**Comment by kytwb** [comment]
Do you have the "include beta versions" toggled on?

**Comment by SylvainCecchetto** [comment]
Oh yes, my bad :-/

**Comment by kytwb** [comment]
No worries! What do you think of:

> Maybe we should put a notification badge on the settings icon when that's the case?

**Comment by SylvainCecchetto** [comment]
As long as we are on the updates topic. If "include beta versions" is toggled on and if I click on the "Check updates button" nothing happen. What the real purpose of this button?

**Comment by kytwb** [comment]
It is supposed to look for the latest update available on GitHub (beta or not based on if the toggle is on or off). I'm a bit confused as it seemed your dock icon bounced because of an available/downloaded update, so I was expecting it to work. When working, it looks like this: https://github.com/getferdi/ferdi/issues/61#issuecomment-534587648

**Comment by kytwb** [comment]
We started to sign/notarize our macOS app from [v5.3.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.3.4-beta.3):

> Fix in-app updates #61 for macOS

You might need to update manually to that version for in-app updates to work.  
Sorry for the inconvenience.

**Comment by SylvainCecchetto** [comment]
Ok thank you for the details.
Maybe my fault if the built-in update feature is broken --> I installed Ferdi throw brew.
I don't know if it's related?

**Comment by kytwb** [comment]
Keeping the original issue as it so other people can find it if needed.

**Comment by 2V3EvG4LMJFdRe** [comment]
How about never bouncing ever for updates? I've never had an app do this.
