### ISSUE TITLE
Missing services

### ISSUE THREAD

**Issue by p-vernaeckt** [getferdi/ferdi#1114]
Hi.

I've been using Ferdi 5.5.0 for a while now, with Teams, Discord and Whatsapp.

I just tried to add Feedly, and I noticed that a *LOT* of services are missing in Ferdi's UI. Here, I see that Feedly's recipe exists in [recipes repo](https://github.com/getferdi/recipes/tree/master/recipes), but it's not present in UI:

![image](https://user-images.githubusercontent.com/4655239/102061660-0cbd9e00-3df4-11eb-8580-21e80abcfa26.png)

I tried with Ferdi 5.5.0/5.6.0-beta2 on macOS Big Sur 11.0.1.

**Comment by p-vernaeckt** [comment]
Oh and as you can see, a lot of icons are missing.

**Comment by vraravam** [comment]
@p-vernaeckt - the way Ferdi works is that the recipes that existed _at the time of building Ferdi_ will be bundled into the installable application. Newer recipes that were contributed to the recipes repo will only get bundled for the next version of Ferdi.

While you are waiting, you can always download the recipes into the profile folder, restart Ferdi and they should be available for your use.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

**Comment by vraravam** [comment]
Closing since this should now be fixed.
