### ISSUE TITLE
Changing logo and branding

### ISSUE THREAD

**Issue by sysuin** [getferdi/ferdi#1115]
I'm building Ferdi on my Windows laptop by following this: https://github.com/getferdi/ferdi/blob/develop/README.md. I want to replace the Ferdi logo with a custom logo and "Ferdi" name with a custom name say "Test_App". Apart from _package.json_, I want to know the places where I can make changes to achieve these two things.

**Comment by vraravam** [comment]
Please grep the whole codebase - you will find references to `Ferdi` in a lot of places.
