### ISSUE TITLE
ferdi not loading properly with 5.6.0-beta4 on windows.

### ISSUE THREAD

**Issue by M0UL** [getferdi/ferdi#1122]
**Bug description:**
i am only seeing a purple screen when starting version 5.6.0-beta.4. on windows 10.  20h2

**Steps to reproduce:**

1. install beta 4.
2. start ferdi.

![image](https://user-images.githubusercontent.com/5436726/102713170-6d524c80-42c6-11eb-9fdf-28d029ef0b27.png)

**Comment by Nosudrum** [comment]
Same issue here. Same Ferdi and windows versions.

**Comment by PlaceboPRS** [comment]
I get the same except it's a black screen.

**Comment by M0UL** [comment]
fixed in beta5

**Comment by Jashnok** [comment]
Happens to me even in beta5 for some reason. When I open ferdi, i get the purple screen but nothing's loading. if i minimize and open it again it's just black. It used to work right after install though

**Comment by jmartsch** [comment]
The solution here also was: Right clicking on Ferdi icon in taks bar and then "Move Ferdi to Current Display"

**Comment by PlaceboPRS** [comment]
It's still relevant, every time I launch Ferdi I get the purple screen and have to right click the icon and click "Show Ferdi" for it to load properly, and that's using 5.6.0 beta 5.

**Comment by mhatvan** [comment]
Cannot reproduce this with Windows 10 Pro, running on v5.6.1-nightly.48.msi

Anyone still experiencing this with a recent version?
