### ISSUE TITLE
Vertical Sytle and "sidebar" size

### ISSUE THREAD

**Issue by akhater** [getferdi/ferdi#1123]
**Bug description:**
When I enable "use vertical style" the size of the "sidebar" is fixed, it cannot be change through the "sidebar width"

**Expected behavior**
I'd like to be able to "use vertical style" and use "Extremely slim sidebar at the same time"

**Environment:**

- Operating System: Win 10
- Ferdi Version: e.g. 5.6.0 bata.5

**Comment by mhatvan** [comment]
Cannot reproduce this, both vertical and horizontal mode work with any sidebar width set.

Please try with the latest nightly from: https://github.com/getferdi/nightlies/releases
