### ISSUE TITLE
No notification counter for WhatsApp

### ISSUE THREAD

**Issue by gabrielwhite** [getferdi/ferdi#1126]
**Bug description:**

When I receive a message on WhatsApp, no counter appears on the app icon the left-hand navigation.

When I restart Ferdi, and I have several pre-existing unread messages, the counter does not appear.

All notifications are enabled in Ferdi and WhatsApp web app. This problem existed in 5.5.0 and still exists in 5.6.0-b5.

I have removed and re-added the service, and this has no effect.

**Steps to reproduce:**

1. Add WhatsApp service
2. Receive new message

**Expected behavior**

I would expect unread message count to be shown on the application icon.

**Environment:**

- Operating System: MacOS 11.1 (20C69)
- Ferdi Version: Version 5.6.0-beta.5 (5.6.0-beta.5.2741)
- Server: Franz

**Debug information:**

`{"host":{"platform":"darwin","release":"20.2.0","screens":[{"id":69733632,"bounds":{"x":0,"y":0,"width":1440,"height":900},"workArea":{"x":0,"y":25,"width":1440,"height":875},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":30,"colorSpace":"{primaries:SMPTEST432_1, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":10,"size":{"width":1440,"height":900},"workAreaSize":{"width":1440,"height":875},"scaleFactor":2,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.0-beta.5","electron":"9.3.2","installedRecipes":[{"id":"gmail","version":"1.3.5"},{"id":"googlemeet","version":"1.0.2"},{"id":"linkedin","version":"1.0.0"},{"id":"messenger","version":"1.1.0"},{"id":"msteams","version":"2.0.0"},{"id":"skype","version":"2.1.0"},{"id":"slack","version":"1.0.16"},{"id":"whatsapp","version":"2.0.8"},{}],"devRecipes":[],"services":[{"id":"c3e200a2-f7fc-44b2-b572-8b0658090fc0","recipe":"whatsapp","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"21f01795-2c92-422e-9cc2-cfadba6d86b8","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"2f6b853c-c098-4d1c-a791-8c3b3e7cedd5","recipe":"msteams","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"a8703c1f-5f0a-4251-a12e-d0be2f6eb84d","recipe":"msteams","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"1e14779f-e469-4101-9247-8527907851ea","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"de68827b-94a9-4e6a-a0e3-3d23c8aaa70c","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"1eb9d261-df0c-4666-8911-8ab2496a4382","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"94827dce-5dec-4b05-a566-6f2f6ee2653e","recipe":"skype","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"b3bc6466-28ef-4d70-8a8c-4760e74fead3","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"7813c0d4-640c-46a0-be3a-ac3676a5c70c","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"91857306-61b6-4ad1-aa5e-0820a73948b2","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":5645400672,"wasExecuted":true,"method":"getAppCacheSize"},"error":{"errno":-2,"code":"ENOENT","syscall":"lstat","path":"/Users/gabe/Library/Application Support/Ferdi/Partitions/service-91857306-61b6-4ad1-aa5e-0820a73948b2/Cache/1eebd1831094467f_0"},"response":{},"server":"https://api.getferdi.com"}],"workspaces":[],"windowSettings":{"width":1385,"height":813,"x":45,"y":46,"displayBounds":{"x":0,"y":0,"width":1440,"height":900},"isMaximized":false,"isFullScreen":false},"settings":{"autoLaunchInBackground":false,"runInBackground":false,"reloadAfterResume":true,"enableSystemTray":false,"startMinimized":false,"minimizeToSystemTray":false,"privateNotifications":false,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"\"en-us\"","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":false,"hibernationStrategy":"1800","inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":false,"adaptableDarkMode":false,"accentColor":"#7367f0","serviceRibbonWidth":"68","iconSize":"10","sentry":false,"nightly":false,"navigationBarBehaviour":"never","useVerticalStyle":false,"alwaysShowWorkspaces":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}`

**Comment by the-nic** [comment]
Modify `webview.js` for whatsapp and edit the line for `const elements = ` to :
```
const elements = document.querySelectorAll("#pane-side .VOr2j");
```

**Comment by gabrielwhite** [comment]
Thanks @the-nic - worked!

**Comment by arioki1** [comment]
sepertinya anda perlu membuat PR untuk issue ini ke 
https://github.com/getferdi/recipes

**Comment by rafaeljustinox** [comment]
> Modify `webview.js` for whatsapp and edit the line for `const elements = ` to :
> 
> ```
> const elements = document.querySelectorAll("#pane-side .VOr2j");
> ```

I can confirm that this solution works. Thanks!

**Comment by otichy** [comment]
> Modify `webview.js` for whatsapp and edit the line for `const elements = ` to :
> 
> ```
> const elements = document.querySelectorAll("#pane-side .VOr2j");
> ```

This solution used to work for me too, but stopped working about 2-3 days ago.

**Comment by juanluisbaptiste** [comment]
None of the suggested fixes worked for me on 5.6beta5.

**Comment by bikrtw** [comment]
Right now I have 
`const elements = document.querySelectorAll('._38M1B');`
and it is working totally fine.

**Comment by rafaeljustinox** [comment]
> Right now I have
> `const elements = document.querySelectorAll('._38M1B');`
> and it is working totally fine.

Works! Thanks

**Comment by juanluisbaptiste** [comment]
> Right now I have
> `const elements = document.querySelectorAll('._38M1B');`
> and it is working totally fine.

Yes it works !! thanks !!

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

Please feel free to reopen the bug once you try the above.
