### ISSUE TITLE
Cookies support for "recipe-custom-website"

### ISSUE THREAD

**Issue by isgroup** [getferdi/ferdi#1128]
**Bug description:**

["recipe-custom-website"](https://github.com/meetfranz/recipe-custom-website) forget cookies when Ferdi is closed.

**Steps to reproduce:**

1. Create a custom website
2. Login
3. Close Ferdi
4. Open Ferdi
5. The website will ask for credentials again

**Expected behavior**

The webapp stays authenticated as for Slack or other integrations.

**Screenshots**

N/A

**Environment:**

- Operating System: Linux
- Ferdi Version: 5.5.0
- Server: Ferdi, without an account

- Debug information:

N/A

**Comment by therealgorgan** [comment]
This even happens to me for the built-in Discord service too.... I dislike having to log in to each service every time.

**Comment by vraravam** [comment]
Duplicate of #872
