### ISSUE TITLE
download link for 5.6.0-beta.5 .deb

### ISSUE THREAD

**Issue by kkplein** [getferdi/ferdi#1129]
In the releases link (https://github.com/getferdi/ferdi/releases) there are only windows and mac downloads.
Where can we download a .deb for the latest 5.6.0 beta 5?

Thanks for a great piece of software!

**Comment by vantezzen** [comment]
<img width="975" alt="Screenshot 2020-12-23 at 08 09 11" src="https://user-images.githubusercontent.com/10333196/102969574-3bbfc800-44f6-11eb-8765-c52049118631.png">

All files are under "assets". These are just quick links above

**Comment by kkplein** [comment]
I feel stupid for not having noticed that the assets menu could be 'opened'. Thanks for pointing out what should have been obvious. :-)
