### ISSUE TITLE
Adding a remote desktop APP from microsoft

### ISSUE THREAD

**Issue by gamersalpha** [getferdi/ferdi#1130]
Hello all, 

i really like this apps, can u know if i can add a remote desktop app on it please ?

**Comment by vantezzen** [comment]
Remote Desktop doesn't seem to offer a web version, thus we cannot add it

**Comment by stevecharon** [comment]
It is not something proper for home use but there is Remote Desktop Web Gateway which you could look into.
Same thing DOES work in conjunction with Azure Applicationproxy
