### ISSUE TITLE
Password Auto locking and loading messages

### ISSUE THREAD

**Issue by ammarmalhas** [getferdi/ferdi#1136]
**Bug description:**

I started using Ferdi v 5.5 again a week ago. The password lock (automatic after x minutes) is not working! I also notices that when I click on a notification of received WhatsApp or Telegram or SMS messages on my Mac OS Catalina, Ferdi windows gets focus (opens) and is unlocked without entering a password! I think thing were better in the version before this one, not sure what version number.

UPDATE: It is now working well after restarting Ferdi! Something is wrong when on one start it does the above and on restart it works fine!

**Steps to reproduce:**

**Expected behavior**

Should simply lock the app after x minutes!
Should load the messages fromservices much faster.
Should not cause Typinator to stop working (deactivated).

**Screenshots**

**Environment:**

- Operating System: MacOS Catalina -->
- Ferdi Version: 5.5.0.2116
- Server: Ferdi -->

- Debug information:

**Comment by ammarmalhas** [comment]
macOS is Big Sur

**Comment by vraravam** [comment]
@ammarmalhas - please confirm if this is still an issue with the 5.6.0 release that was just released. Thanks!

**Comment by ammarmalhas** [comment]
The issue seems to be resolved, thank you all.
