### ISSUE TITLE
Add Confirm before Deleting Service

### ISSUE THREAD

**Issue by YisroelTech** [getferdi/ferdi#1137]
**Is your feature request related to a problem? Please describe.**
When right-clicking on a Service one of the options is Delete Service, it's too easy to mistakenly Delete the service (when intending to Disable it) and it's consequential because re-adding the service you need do the whole login/setup from fresh.

**Describe the solution you'd like**
Add a Confirm dialog popup when clicking Delete Service.

**Comment by vraravam** [comment]
This has been already implemented in #1328
