### ISSUE TITLE
External links don't open in 5.6.0-beta.5

### ISSUE THREAD

**Issue by benwaffle** [getferdi/ferdi#1138]
**Bug description:**
External links in apps such as discord and telegram do not open when clicked. Right clicking > Open Link works fine though.

**Steps to reproduce:**

1. Go to telegram or discord
2. Click on an external link
3. See error

**Environment:**

- Operating System: Arch Linux
- Ferdi Version: 5.6.0-beta.5
- Server: no account

- Debug information:
https://gist.github.com/benwaffle/0a948068dd7c3b421c411b965dae49c7

**Comment by martin131** [comment]
Same problem on Windows. FB Messenger and Slack

Version: 5.6.0-beta.5

**Comment by arioki1** [comment]
you can try CTRL + Click Link

**Comment by wiggisser** [comment]
MiddleClick also works ...

**Comment by webworker01** [comment]
Related to https://github.com/getferdi/ferdi/issues/941 but at least the external links don't open in a Ferdi window which is *never* desired.

**Comment by raabmar** [comment]
I confirm on macOS 11.1 with Ferdi 5.6.0-beta.5 - right-click -> Open Link works. CMD + Click also works. Just clicking on a link doesn't do anything.

**Comment by vraravam** [comment]
This is now fixed by https://github.com/getferdi/ferdi/pull/1474 - which has just been merged! Please pull and rebuild from source, or wait for tonight's nightly build.
