### ISSUE TITLE
Where is the data stored without an account

### ISSUE THREAD

**Issue by dbieber** [getferdi/ferdi#1139]
If I run ferdi from source with `DEBUG=Ferdi:* npx misty` and use it without an account, where is the data stored?
It seems to persist if I start and stop ferdi, so somewhere on disk? Can I find the path?

And also, what data does Ferdi store? Does this include account passwords? Or just cookies?

Forgive me if these question are already answered, I've been poking around at the docs and Issues for a bit to see if I could figure it out myself. I haven't figured it out yet. I'll keep looking, but if someone else can provide the answer faster than I can find it myself, all the better!

**Comment by kris7t** [comment]
See here: https://github.com/getferdi/ferdi/issues/1062#issuecomment-723657380 about where and what data is saved. Passwords aren't saved, but cookies are.

I think the same applies to dev mode, too, but with `$XDG_CONFIG_HOME/FerdiDev` (or similar) instead of `$XDG_CONFIG_HOME/Ferdi`.

**Comment by dbieber** [comment]
Thanks. $XDG_CONFIG_HOME wasn't set. I found the data in the end though.
For me it was in ~/Library/Application Support/FerdiDev/.
The settings (e.g. services and workspaces) data live in sqlite in `~/Library/Application Support/FerdiDev/server.sqlite`.

**Comment by kris7t** [comment]
Oh, sorry, I automatically assumed you were on Linux. 😅  Indeed, on Mac OS, the equivalent is `~/Library/Application Support/`.
