### ISSUE TITLE
App size reduction

### ISSUE THREAD

**Issue by probablykasper** [getferdi/ferdi#114]
Got some suggestions for reducing Ferdi's app size, because it's rather big and takes a while to download from GitHub's servers:

1. Ferdi comes with 133 MB worth of spellchecking. Is it possible to use the OS spellchecker? Otherwise, the spellchecking could dynamically download the appropriate language.

2. Judging by app.asar, Ferdi's code seems to not be fully minified. [UglifyJS](https://www.npmjs.com/package/uglify-js) is probably a good bet. Is tree shaking in use?

2. The app.asar is 70 MB, which is quite a bit (Discord, for instance, is 5MB). I guess there's some bloat that could be removed?

**Comment by vantezzen** [comment]
1. We could download spellchecker files into the user folder when the user selects a language. Alternatively, we could think about switching to [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker) as it looks to have a functionality like this implemented by default.
2. I'll add this to our gulp buildfile

**Comment by vantezzen** [comment]
I now added minification for production builds via 362d034. We'll see if that improves the size.

**Comment by vantezzen** [comment]
I now implemented the switch from the custom spellchecker solution to `electron-spellchecker` via 64824a6. This reduced the size of Ferdi's `build` folder from ca. 150MB to ca. 15MB.

`electron-spellchecker` will use the system's dictionaries or download the dictionaries into the appdata folder as needed.

**Comment by kytwb** [comment]
@vantezzen well done!
