### ISSUE TITLE
Big Sur menu icon does not change to black

### ISSUE THREAD

**Issue by Depechie** [getferdi/ferdi#1140]
<img width="207" alt="Screenshot 2021-01-04 at 10 18 40" src="https://user-images.githubusercontent.com/351693/103519704-46734900-4e76-11eb-80c0-b0be82eeecfb.png">
On Big Sur, when setting the dark theme, the icons should also change to black in the menu bar. Otherwise the white is almost not visible.

Ferdi does not yet change.

**Comment by Depechie** [comment]
This is what needs to change : https://stackoverflow.com/questions/41664208/electron-tray-icon-change-depending-on-dark-theme

**Comment by smark91** [comment]
Still relevant. On Big Sur icon stay white.

**Comment by jchlanda** [comment]
And on Monterey.

**Comment by kytwb** [comment]
Related https://github.com/electron/electron/issues/25478#issuecomment-966595183
