### ISSUE TITLE
Hide Online Status for Telegram, Facebook and Whatsapp?

### ISSUE THREAD

**Issue by rusagent** [getferdi/ferdi#1141]
Any possiblity to achieve this?

**Comment by CalAlaera** [comment]
Just as a heads up, this appears to be against [Telegram's API ToS](https://core.telegram.org/api/terms):
> It is forbidden to interfere with the basic functionality of Telegram. This includes but is not limited to (...) implementing a 'ghost mode

**Comment by rusagent** [comment]
In the telegarm app i can be shown as offline...

**Comment by vraravam** [comment]
This is not specific to Ferdi. Closing the issue
