### ISSUE TITLE
Windows - Reload services needed when Laptop wakes up from standby

### ISSUE THREAD

**Issue by dark0ni** [getferdi/ferdi#1150]
**Bug description:**
When the laptop set to standby/hibernate and wakes up again all services in Ferdi need a reload

**Steps to reproduce:**
1. Start Ferdi
2. Close laptop or go to power save mode
3. Start laptop again
4. All services need a reload to display

**Expected behavior**
That all services still loaded and in memory

**Environment:**

- Operating System: Windows 10 Build 1909
- Ferdi Version: 5.5.0 (x64)

**Comment by davidszp** [comment]
I have the same issue specifically with Skype. After waking up from every sleep, I need to manually "reload Ferdi" in order to make Skype work again.

**Comment by JKubovy** [comment]
I have same problem with Facebook Messanger, WhatsApp and GitHub. It's irritating specially with laptop because I put it in sleep mode quite often and every time I have to click on reload button.

**Comment by pH142857** [comment]
Maybe a duplicate of #931.

**Comment by MartinX3** [comment]
Still the same issue with all my services on ferdi compiled from git.
9298a120

**Comment by vraravam** [comment]
Unfortunately, I don't run AUR or windows - and will not be able to help you folks here.

**Comment by vraravam** [comment]
Closing since this seems like a duplicate of #931
