### ISSUE TITLE
No Emojis is visible in MS Teams

### ISSUE THREAD

**Issue by gunalabs** [getferdi/ferdi#1163]
![image](https://user-images.githubusercontent.com/67857588/104987130-ed411300-5a3a-11eb-867b-cb3a689bb0cc.png)
Emojis are actually there but nothing is visible anywhere.
This happens for Chats, reactions and all emojis.

**Comment by mhatvan** [comment]
Cannot reproduce this with Ferdi 5.6.1-nightly.33

Emojis display as expected inside Microsoft Teams, running Ubuntu 21.04

Please comment on this issue in case you still encounter this.
