### ISSUE TITLE
Maximized Application Border Bleeds Onto Next Monitor

### ISSUE THREAD

**Issue by canuckbrian** [getferdi/ferdi#1164]
**Bug description:**
This is by no means an application breaking bug, but more of a visual annoyance. When using Ferdi in a multi monitor configuration, maximizing the application on one screen causes the purple border of Ferdi to be displayed on the adjacent screens. It bleeds over by 1px on any adjacent screen.

When I put Ferdi on my middle monitor and maximize it, the purple border displays on the adjoining edges of the left and right monitor. I took a screenshot of my entire desktop spanning all 3 monitors and when I measure the window size of Ferdi when maximized it measures 1922 pixels in width. So there is a 1px bleed onto adjacent monitors.

**Steps to reproduce:**

1. Open Ferdi
2. Maximize the window
3. Window border is visible on adjacent screens.

**Expected behavior**
Window border would not be visible on adjacent screens. When the window is maximized it's width would match the resolution of the screen it's on and not exceed it by 1px on any side.

**Screenshots**
![Full_Desktop](https://user-images.githubusercontent.com/5985280/105200461-b4fe0b00-5af4-11eb-86e8-c9948a776c2b.png)
![Ferdi_1922](https://user-images.githubusercontent.com/5985280/105200488-bdeedc80-5af4-11eb-8c36-b4e705680ba9.png)

**Environment:**

- Operating System: Windows 10 Pro fully updated
- Ferdi Version: 5.5.0
- Server: Ferdi
- Monitor Configuration: 3 monitors @ 1920x1080

- Debug information:
https://pastebin.com/sTr4v0U9

**Comment by standerksen** [comment]
Same issue here, Windows 10. Three monitors (one center 1920x1080 and two 1680x1050 sides).

**Comment by canuckbrian** [comment]
This issue is still relevant. No update has been released to address this minor UI bug. Just commenting so the "stale bot" knows it's still active.

**Comment by Silun** [comment]
The issue is still there in version 5.5.0. I enjoy Ferdi so far, a fix to this would be lovely, as it is quite annoying when one has Ferdi open on one monitor constantly.

**Comment by vraravam** [comment]
Since Ferdi has moved to the latest versions of Electron (v13.x) - I would request all of you to upgrade to the latest nightlies found [here](http://github.com/vraravam/nightlies/releases) and then report back whether this is still an issue or not.

**Comment by Silun** [comment]
It seems fixed in 5.6.0-nightly.66, thank you.

**Comment by vraravam** [comment]
@canuckbrian @standerksen - could you also please upgrade? If you are on 5.5, I guarantee you that you will have a much better experience with all the fixes that have been done in the recent past couple of months! Closing this ticket (please reopen if you find otherwise)

**Comment by standerksen** [comment]
@vraravam Thank you for notifying me. Do you guys have any indication when the official 5.6 release will launch?

**Comment by vraravam** [comment]
sorry @standerksen - unfortunately, that is not visible atm. Currently, we have done some major internal changes as well (for eg moved from `travis-ci` and `appveyor` consolidating the CI process into `github-actions`, upgrades to `Electron`, etc) - but, the app-signing process is broken for the past few months. Till @kytwb can fix that, we are stuck with only nightly releases. Please bear with us.
