### ISSUE TITLE
No login available for Google Drive

### ISSUE THREAD

**Issue by Jixal** [getferdi/ferdi#1165]
Hi,

There seems to be no ability to login into Google Drive via Ferdi. 

I've copied an image of what I'm seeing.
![image](https://user-images.githubusercontent.com/59186468/105253809-f57c8800-5bcb-11eb-8db6-abfad62830da.png)

All that is available is "Go to Drive" which then sends you to a browser. 

Gmail and Calendar work fine as one would expect. 

Perhaps the Google Drive can't operate inside Ferdi? Or is this some bug I'm experiencing?

Cheers,
Jonny

**Comment by WallStreet14** [comment]
This is actually an issue for all apps (or even custom apps) that support a google login via a popup or popup redirect. Figma, Drive, and many other custom apps are examples of this. Any workarounds?

**Comment by lappie** [comment]
You can rightclick "Open Drive" -> "Open in Ferdi"

**Comment by mmoya** [comment]
> You can rightclick "Open Drive" -> "Open in Ferdi"

Tried this and got logged out of Gmail.

**Comment by vraravam** [comment]
Please see the workaround in #1018 - you will have to edit a file in the ferdi profile folder.

**Comment by vraravam** [comment]
Please refer to the brand new [self-help documentation](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv) - which might solve the issue.

**Comment by vraravam** [comment]
Sorry - this PR has now been merged into the main Ferdi repo: https://github.com/getferdi/ferdi/#troubleshooting-recipes-self-help

**Comment by vraravam** [comment]
Does the above workaround (new recipes) work?

**Comment by k-y** [comment]
> Please see the workaround in #1018 - you will have to edit a file in the ferdi profile folder.
I don't see the workaround to edit a file in the ferdi profile folder explained in #1018

**Comment by vraravam** [comment]
@k-y - What version of Ferdi are you seeing this behavior in? If you are not on the [latest nightly](https://github.com/getferdi/nightlies/releases), I would suggest that you switch to that as the first step.

After that, please try the workaround that has been suggested.

**Comment by k-y** [comment]
> @k-y - What version of Ferdi are you seeing this behavior in? If you are not on the [latest nightly](https://github.com/getferdi/nightlies/releases), I would suggest that you switch to that as the first step.
> 
> After that, please try the workaround that has been suggested.

Happy to report that running 5.6.1-nightly.3 is working happily with Google Drive

**Comment by vraravam** [comment]
Thanks for getting back @k-y . I'm closing the issue now.
