### ISSUE TITLE
Jira hosted/on-prem server support

### ISSUE THREAD

**Issue by pandruszkow** [getferdi/ferdi#1169]
**Is your feature request related to a problem? Please describe.**
Ferdi appears to support only Atlassian-hosted JIRA. I'd like to be able to do the same with hosted JIRA under my own domain.

**Describe the solution you'd like**
Ideally, it should be possible to add a JIRA tab with a custom server, much like the Roundcube tab supports an arbitrary webmail URL.

**Describe alternatives you've considered**
I think it could be added as a custom service, but I don't think that notification integration would be quite as good.

**Additional context**
I know that on-prem Jira support is basically deprecated, but I'm sure some people will be still running the Data Center edition. Or even the old Server edition even though it's been EOLed, since the licenses are perpetual.

**Comment by pandruszkow** [comment]
Bump.

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)
