### ISSUE TITLE
Some shortcut in Gmail are not working

### ISSUE THREAD

**Issue by Fr-486** [getferdi/ferdi#1172]
**Bug description:**

Some shortcut in Gmail are not working such as:
- ctrl+enter to send
- ctrl+shift+v to copy without format (in this case it copy the text 2 times)

**Steps to reproduce:**

1. Go to 'gmail'
2. Click on 'new message'
3. paste text with shortcut ctrl+shift+v
4. try to send with shortcut ctrl+enter

**Expected behavior**

- ctrl+enter should send the open message
- ctrl+shift+v should copy without format

**Screenshots**

**Environment:**

- Operating System:  windows 10 
- Ferdi Version:  5.5.0
- Server:  default

- Debug information:

{"host":{"platform":"win32","release":"10.0.18363","screens":[{"id":2528732444,"bounds":{"x":-1536,"y":216,"width":1536,"height":864},"workArea":{"x":-1536,"y":216,"width":1536,"height":824},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1536,"height":864},"workAreaSize":{"width":1536,"height":824},"scaleFactor":1.25,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":2779098405,"bounds":{"x":0,"y":0,"width":1920,"height":1080},"workArea":{"x":0,"y":0,"width":1920,"height":1040},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1040},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"gmail","version":"1.3.1"},{"id":"googlecalendar","version":"1.0.3"},{"id":"whatsapp","version":"2.0.3"},{}],"devRecipes":[],"services":[{"id":"d4595e35-0397-4667-af97-82262fd7648d","recipe":"gmail","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"ad37ca2d-2d91-4a4d-8305-a22e62466401","recipe":"googlecalendar","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"65ca823e-a238-4add-b6ee-a7327bce274f","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in WindowControls\n    in div\n    in Unknown (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)"]},{"type":"log","info":["log","Onboarding",{"icon":"https://calendar.google.com/googlecalendar/images/notification_2020q4/calendar_macos_26_1x.png","body":"10:00 – 13:00","tag":"cal-evt-MmYyMHYycmxpODdzaGFyMWd0NnNqaDFmY28gZnJhbmNlc2NvLm1vdHRhQGRvY2Viby5jb20","requireInteraction":true,"silent":true}]},{"type":"log","info":["log","Zoom",{"body":"Michael Broomhead has joined your meeting - Onboarding","icon":"//ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_envelope_1x.png","tag":"en_francesco.motta@docebo.com"}]},{"type":"log","info":["log","Yann / Francesco",{"icon":"https://calendar.google.com/googlecalendar/images/notification_2020q4/calendar_macos_26_1x.png","body":"14:15 – 14:45","tag":"cal-evt-N2Q4OGM0dG8wZmp1MWdqcTEwaXZ2MjluYzcgZnJhbmNlc2NvLm1vdHRhQGRvY2Viby5jb20","requireInteraction":true,"silent":true}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by Jss(inject-_class2-with-stores-actions))\n    in Jss(inject-_class2-with-stores-actions) (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)"]}],"workspaces":[],"windowSettings":{"width":800,"height":600,"x":34,"y":73,"isMaximized":true,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":false,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":true,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":false,"adaptableDarkMode":false,"accentColor":"#0465ac","serviceRibbonWidth":"45","iconSize":"30","sentry":true,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by Maicon-Moreira** [comment]
Yeah that is really anoying for people who use Gmail without a mouse.

Another non functioning shortcuts:
- *ALT+LEFT_ARROW* -> should return to the previous page, but does nothing.
- *ALT+RIGHT_ARROW* -> should return to the next page, but does nothing.

Are there any workarounds for this?

**Comment by vraravam** [comment]
@Maicon-Moreira - I use gmail (but on macos) via Ferdi.
As far as the double-pasted text, this has been fixed a couple of months ago.
As far as the shortcut keys, does this _ALT+LEFT_ARROW_ work on other services? (In my case, on mac, the shortcut to "navigate back" is _Cmd+LEFT_ARROW_ - and it works perfectly.

btw - are you reporting this against the latest version of Ferdi (5.6.2)? We are unable to support v5.5.0 unfortunately.

**Comment by Maicon-Moreira** [comment]
@vraravam Yeah sorry, I noticed after that CTRL+LEFT_ARROW actually works exactly like ALT+LEFT_ARROW on Ferdi, which is weird at least on Windows apps and shortcuts.

**Comment by vraravam** [comment]
@Maicon-Moreira - I have merged a fix for this. It'll be available in the next nightly (**after** 5.6.3-nightly.20)
