### ISSUE TITLE
Gmail login issue is back! (Unsafe Browser)

### ISSUE THREAD

**Issue by GovindKrishnan** [getferdi/ferdi#1173]
**Bug description:**
 The Gmail login issue is back as it now says browser is unsafe. It's related to user agent like discussed earlier. High chances of this issue being a duplicate & close if you like to.

**Steps to reproduce:**

1. Go to Gmail
2. Try to sign in
3. See error

**Expected behavior**
 Expected to be able to login normally.
**Screenshots**

**Environment:**

- Operating System: Windows 10 
- Ferdi Version: Latest beta 
- Server: Ferdi 

- Debug information:

**Comment by cangulostudios** [comment]
This worked for me  : https://github.com/getferdi/ferdi/issues/264#issuecomment-567138371

Windows 10
Ferdi 5.6.0-Beta.5

1. Delete the Gmail service
2. Close Ferdi
3. Change the code in %appdata%/Ferdi/recipes/gmail/index.js

```js module.exports = Franz =>
    class GoogleVoice extends Franz {
        overrideUserAgent() {
            return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0";
        }
    };

**Comment by vraravam** [comment]
This is also happening with the latest version of the nightly: `Version 5.6.0-nightly.15 (5.6.0-nightly.15.2890)`
and the above fix does not seem to work.

**Comment by vraravam** [comment]
ok - I found that commenting out the `modifyRequestHeaders` function in the same config file above did the trick. I am now able to login into gmail. As stated earlier, I'm using the nightly version: `5.6.0-nightly.15 (5.6.0-nightly.15.2890)`

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

**Comment by vraravam** [comment]
Please try with the nightly builds from [here](http://github.com/vraravam/nightlies/releases) - this exposes the ability to the user to control the user-agent via the UI as opposed to editing files in the Ferdi profile. Please do be aware of the **unsigned nature** of the builds in this repo - while we work on fixing the issue with signing of our build artifacts.

**Comment by laureho** [comment]
> With the latest version of Ferdi and the latest recipes, this should no longer be the case.
> 
> Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?
> 
> If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

I just followed the instructions on windows 10 for v. `5.6.1-beta.1` and that fixed it for one of my Gmail services that I couldn't log back into for the past few months. 🥳 
Thank you very much @vraravam!

**Comment by vraravam** [comment]
tx @laureho - btw, the newer nightlies are also good. in fact, tomorrow's one will fix some more bugs. Please see https://github.com/getferdi/nightlies/releases for new releases

**Comment by laureho** [comment]
Thanks @vraravam, I'll also check the nightlies out.
