### ISSUE TITLE
No 'unread messages badges' 

### ISSUE THREAD

**Issue by glyko54** [getferdi/ferdi#1195]
Hello everyone, 

I recently installed Ferdi, and I love it, but I've been running into the following issue (at least I think): 

I don't see any 'unread messages badges', be that in the app's tab bar
![image](https://user-images.githubusercontent.com/62068242/107414150-e5443280-6b11-11eb-9943-1e2e62fea142.png)
or in the Windows status bar
![image](https://user-images.githubusercontent.com/62068242/107414265-10c71d00-6b12-11eb-9b8f-2ffc36217e4b.png)

Did I misunderstand this feature and it's working as intended? Or is something wrong? If yes, how do I get the badges to appear?

Thank you for helping out this newbie.

**Comment by kris7t** [comment]
It's a continuous cat-and-mouse game to maintain recipes (programs that allow Ferdi to support various messaging services) as provides change their applications. This means occasionally a recipe can break and need to be updated to be able to display the unread message count. This process is specific for each messaging service and be done by hand even if provider don't make it deliberately difficult to do (but often there is some "protection" against using a client like Ferdi in the service).

You should report the broken services individually in the https://github.com/getferdi/recipes/ repository.

**Comment by glyko54** [comment]
Thank you for clarifying things! I just checked on Franz, and the count is working there, why is this the case. Are the recipes maintained separately?

**Comment by kris7t** [comment]
Yes, the recipes are also forked and maintained separately.
