### ISSUE TITLE
Google Drive show Website version instead of Login to Service

### ISSUE THREAD

**Issue by drunkkent** [getferdi/ferdi#1197]
**Bug description:**

hi i using google drive, and when i add it it show a website version instead of login form to using service. i already tried reload service, delete and re add, reload ferdi and not of them work

**Screenshots**

![image](https://user-images.githubusercontent.com/56915219/107605310-652ee180-6c65-11eb-8be8-3c8003ca00e4.png)

**Environment:**

- Operating System:  Manjaro KDE
- Kernel: 5.10.15-1
- Ferdi Version:  5.5.0 (x64)
- Server:  ferdi server

- Debug information: [debug.txt](https://github.com/getferdi/ferdi/files/5963309/debug.txt)

**Comment by lappie** [comment]
You can rightclick "Open Drive" -> "Open in Ferdi"

**Comment by lappie** [comment]
Note that issue #359 "You are not signed in" still exists though.

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

**Comment by vraravam** [comment]
Closing since there is a fix (and a separate workaround) - and this does not seem to be affecting other users.
