### ISSUE TITLE
Customizable accent color

### ISSUE THREAD

**Issue by pawelantczak** [getferdi/ferdi#120]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Selectable color palette allowing to pick favorite color.

**Describe alternatives you've considered**
Leave as it is.

**Additional context**
Accent color, purple-ish, is clearly related to logo color. 
I would be perfect to be able to pick color of choice.

**Comment by vantezzen** [comment]
I just pushed 942466e which implements this feature, it should be shipped with the next Beta build.

The accent color can now be changed inside Settings > Accent color.

**Comment by kytwb** [comment]
Available in [v5.4.0-beta.1](https://github.com/getferdi/ferdi/releases/tag/v5.4.0-beta.1).

<img width="648" alt="Screen Shot 2019-10-18 at 10 33 29 AM" src="https://user-images.githubusercontent.com/412895/67063975-dace8e80-f192-11e9-9a8c-26ea9c2e52a1.png">
