### ISSUE TITLE
just a purple rectangle

### ISSUE THREAD

**Issue by SusanneMuc** [getferdi/ferdi#1201]
I am having problems with the Ferdi program.
 The field where the messanger service was before is now only purple. I have already deleted and reinstalled the program several times. I can't find the config / settings.json "and" config / proxy.json "files on my computer. The program ran completely normally on my Windows-computer before, I tried to generate an account when everything turned purple. What is to be done? 

![grafik](https://user-images.githubusercontent.com/79018675/107877382-657ce600-6ecc-11eb-9919-7518260a57e9.png)

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

**Comment by mhatvan** [comment]
Closing due to no response by the author. I will reopen this issue if it still occurs.
