### ISSUE TITLE
Rocket Chat logo does not appear

### ISSUE THREAD

**Issue by pH142857** [getferdi/ferdi#1203]
**Bug description:**

When creating a new Rocket Chat self-hosted service, the Rocket Chat icon briefly appears then vanishes. When trying to manually upload a custom image, it fails as well.
**Steps to reproduce:**

1. Add new service (ctrl+N)
2. Choose Rocket Chat, then Self-Hosted and enter a valid URL
3. Validate and observe the RC icon disappear in an deafening silence
4. Try to upload a new picture: the frame remains blank
5. Reflect on the meaning of life

Please note: the error appears even though the RC install is brand new. The way of retrieving the wanted picture needs fixing, but also, if the image is not where it's supposed to be, Ferdi should fallback to the default service logo.

**Environment:**

- Operating System: Ubuntu 18.04
- Ferdi Version: 5.5.0 (x64)

**Comment by ajaeger** [comment]
I can confirm this.

**Comment by ajaeger** [comment]
This is fixed in 5.6.0 Beta5 for me.

**Comment by vraravam** [comment]
@pH142857 - could you also please confirm whether this is fixed? If so, we can close the ticket.

**Comment by pH142857** [comment]
Fixed indeed in the latest. Thanks!
