### ISSUE TITLE
Homebrew cask is not notarized

### ISSUE THREAD

**Issue by sarndt** [getferdi/ferdi#1204]
Trying to install Ferdi via homebrew leads to the message:

`“Ferdi” cannot be opened because the developer cannot be verified.`
I believe this is because the homebrew cask is not notarized.

It would be great if you could notarize your build, makes it easier to use the application.

**Comment by vraravam** [comment]
We have introduced the notarization of the mac builds - but, our build process is currently broken. Once that is fixed, you should not see this error any more. Closing for now. Thanks for logging the bug.
