### ISSUE TITLE
2nd (business) Whatsapp account logs out frequently

### ISSUE THREAD

**Issue by psychowood** [getferdi/ferdi#1209]
**Bug description:**
I'm using two differente Whatsapp services on Ferdi (macOS , local install, no cloud sync), and the business one keeps getting logged out periodically.

**Steps to reproduce:**

- Add two whatsapp web accounts, tied to two different numbers, one WA "standard" and the other WA Business
- Use them more or less with the same frequency, daily
- Do nothing specifically
- See the WAB account presenting a QR Code to login again.

I can confirm that in the Android App the old logins are still tracked as active; it looks like it's Ferdi losing the cookie.
I was using RamBox previously and this behaviour was not present, I'd say it is not a time limitation of WAB, AFAIK.

**Expected behavior**

Keep being logged in?

**Screenshots**

Nothing to see here.

**Environment:**

- Operating System: macOS Big Sur (currently 11.3 Beta (20E5172i), same behaviour with previous non beta versions)
- Ferdi Version: 5.5.0.2116
- Server: Using without an account

- Debug information:

I can provide the debug file but I see a lot of personal data/messages in that, is there an easy way to clean it up?

**Comment by SinTan1729** [comment]
I'm facing a similar issue, described [here](https://github.com/getferdi/ferdi/issues/1745).

**Comment by vraravam** [comment]
@SinTan1729 - is your issue related this one or the other. They both are related to Whatsapp - but, the erroneous behavior seems to be distinct/different.

**Comment by vraravam** [comment]
@psychowood - Since we have release 5.6.0, and are no longer able to support v5.5 of Ferdi, I would request you to either close this ticket or try out with 5.6 and report back as to whether its still an issue.

**Comment by psychowood** [comment]
@vraravam I was writing right now that the issue is not happening anymore. I'm on 5.6.0-beta.7 but afair it stopped before updating... perhaps there was something going on in the WA servers (different cookie settings or something else).

Anyway, let's close it :)

**Comment by vraravam** [comment]
btw - 5.6.0-beta.7 is older than the public release. Please upgrade to 5.6.0 for the latest fixes on the stable build.

**Comment by SinTan1729** [comment]
@vraravam I'm the poster of that other issue. This issue simply looked similar.

**Comment by psychowood** [comment]
> btw - 5.6.0-beta.7 is older than the public release. Please upgrade to 5.6.0 for the latest fixes on the stable build.

Thanks, I didn't notice that Homebrew stopped notifiyng Ferdi updates, I had to force it.
