### ISSUE TITLE
hibernation only for period of time

### ISSUE THREAD

**Issue by dumprop** [getferdi/ferdi#1216]
**Is your feature request related to a problem? Please describe.**
In hibernation, it doesn't get notification

**Describe the solution you'd like**
Automatically load it every N (for example 5) minutes, checks for notification and hibernate it again

**Additional context**
I expected that it mean period of time in hibernation, so expected automatic updating every 5 minutes
<img width="259" alt="image" src="https://user-images.githubusercontent.com/34004367/108636231-dea3ac80-747b-11eb-8c1b-6fd3254dd753.png">

**Comment by vraravam** [comment]
Is this related to #1486 ?

**Comment by dumprop** [comment]
> 
> 
> Is this related to #1486 ?

Probably yes

**Comment by vraravam** [comment]
On further thought, this is the exact opposite of #1486 . In there (as was the original implementation/intent in Ferdi), the service would go to sleep after a period of inactivity - that was called going into hibernation/hibernating.

But, if I understand what you want, I think you want to the hibernating service to wake up after X seconds. Is that explanation correct?

**Comment by dumprop** [comment]
> But, if I understand what you want, I think you want to the hibernating service to wake up after X seconds. Is that explanation correct?
Yes
In hibernation it doesn't get any update (notification), so it need a some wake up (for 5 seconds every 5 minutes)

**Comment by vraravam** [comment]
<img width="554" alt="Screenshot 2021-07-23 at 9 27 31 PM" src="https://user-images.githubusercontent.com/69629/126809209-a89bef03-9fb7-422a-ae19-19dd228a536e.png">

Would this depict what you are looking for? I have a service for Gmail, which I have configured to hibernate as soon as its alive (and unused) for 30s; and once hiberated, it will sleetp for 60s and then wake up again. The cycle will continue.

The user is free to play around with the hibernation and wakeUp strategies:
<img width="507" alt="Screenshot 2021-07-23 at 9 30 10 PM" src="https://user-images.githubusercontent.com/69629/126809533-23b6b600-63a1-4062-a302-5b8eae0477dd.png">
and
<img width="506" alt="Screenshot 2021-07-23 at 9 30 00 PM" src="https://user-images.githubusercontent.com/69629/126809585-45962640-7aeb-420b-9b13-a0adf1271f73.png">

**Comment by dumprop** [comment]
> 
> 
> <img alt="Screenshot 2021-07-23 at 9 27 31 PM" width="554" src="https://user-images.githubusercontent.com/69629/126809209-a89bef03-9fb7-422a-ae19-19dd228a536e.png">
> 
> Would this depict what you are looking for? I have a service for Gmail, which I have configured to hibernate as soon as its alive (and unused) for 10s; and once hiberated, it will sleep for 60s and then wake up again. The cycle will continue.
> 
> The user is free to play around with the hibernation and wakeUp strategies:
> <img alt="Screenshot 2021-07-23 at 9 30 10 PM" width="507" src="https://user-images.githubusercontent.com/69629/126809533-23b6b600-63a1-4062-a302-5b8eae0477dd.png">
> and
> <img alt="Screenshot 2021-07-23 at 9 30 00 PM" width="506" src="https://user-images.githubusercontent.com/69629/126809585-45962640-7aeb-420b-9b13-a0adf1271f73.png">

Yes, cool !

**Comment by vraravam** [comment]
This has been merged - and will be in the next nightly (in a few hours' time)
