### ISSUE TITLE
Close window icon on the About box

### ISSUE THREAD

**Issue by pH142857** [getferdi/ferdi#1221]
**Is your feature request related to a problem? Please describe.**
It is puzzling not to find the usual "close window" cross in the About box.

**Describe the solution you'd like**
Add the GNOME "close window" cross in the top right-hand corner of the "About Ferdi" box.

![Capture d’écran de 2021-03-05 12-18-36](https://user-images.githubusercontent.com/11050141/110108900-09133500-7dad-11eb-89d4-7e0a9a731759.png)

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

**Comment by pH142857** [comment]
It is fixed in the latest, thanks.
