### ISSUE TITLE
Ferdi does not follow macOS Do Not Disturb mode

### ISSUE THREAD

**Issue by erikw** [getferdi/ferdi#1223]
**Bug description:**
Ferdi does not adhere to macOS Do Not Disturb mode. Even if DnD is activated in macOS, Ferdi will still make audible notifications. This is very bad as I expect my computer to be silent when DnD is enabled, but then suddenly a very loud audible alert comes from Ferdi.

The expected behavior is that Ferdi's own "Disable notifications & Audio (Cmd + Shift + M)" follows macOS DnD current setting. 

**Steps to reproduce:**

1. Make sure Ferdi notifications is on (see screenshot) 
<img width="64" alt="Screen Shot 2021-02-26 at 18 08 40" src="https://user-images.githubusercontent.com/175286/109332361-48e29580-785e-11eb-87d4-654448a7f576.png">

2. Make sure macOS notifications are enabled (DnD=false)
3. Enable macOS DnD e.g. by opt-clicking the clock 
4. Wait for a message to be send to a service set up in Ferdi / or send a message to your self
5. Hear that Ferdi still makes sounds (a very loud) audio bell when the message is received. The Ferdi notification mode is unchanged i.e. still enabled.

**Expected behavior**
When setting macOS DnD=true, Ferdi notifications&audio should be false.

**Environment:**
- Operating System: macOS 11.2.1
- Ferdi Version: 5.5.0.2116
- Server: Franz

**Comment by vraravam** [comment]
Please check in the next nightly (v5.6.1-nightly.36) whether this is fixed. The related PR is #1823

**Comment by jaklan** [comment]
@vraravam Version: 5.6.3, it's still not fixed - when I turn on DnD, it seems I don't get notifications, but I still got these annoying audio bells (e.g. new message in Google Chat). The option in settings doesn't change:
![image](https://user-images.githubusercontent.com/24907857/141687803-e3f6fdff-89b6-42d0-b038-db6567145ad2.png)
and moreover - it's still one option and it's not decoupled as mentioned in #1823...

**Comment by erikw** [comment]
I can confirm @jaklan's update!

**Comment by klement** [comment]
I am too experiencing this bug.

**Comment by briankendall** [comment]
I can contribute a bit more info:

I noticed notification sounds were still coming through with do not disturb turned on when running Ferdi 5.6.2. I came here to check whether someone had reported the bug.

I then updated to 5.6.4, and I'm noticing now that Ferdi's "enable notifications / audio" button automatically matches whether I have do not disturb turned on.

I'm running macOS 10.14.6.

**Comment by jaklan** [comment]
Also updated to 5.6.4 and turning on / off DnD mode doesn't change anything in Ferdi.
