### ISSUE TITLE
WhatsApp not working

### ISSUE THREAD

**Issue by Kellett** [getferdi/ferdi#1224]
**WhatsApp not working:**

Updated this morning and now my whatsapp service just shows the following message
![image](https://user-images.githubusercontent.com/1553850/109492339-bb33bf80-7a82-11eb-9d2c-7c82c2d8e922.png)

**Steps to reproduce:**

1. Try to open the whatsapp service

**Environment:**

- Operating System: Linux
- Ferdi Version: 5.5.0
- Server: Franz

- Debug information:

{"host"
:{"platform":"linux","release":"5.9.16-1-MANJARO","screens":[{"id":1252062888304830,"bounds":{"x":1920,"y":0,"width":1920,"height":1080},"workArea":{"x":1920,"y":0,"width":1920,"height":1080},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:INVALID, transfer:INVALID, matrix:INVALID, range:INVALID}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1080},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":1251801291210966,"bounds":{"x":0,"y":0,"width":1920,"height":1080},"workArea":{"x":0,"y":28,"width":1920,"height":1052},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6409, 0.3498],  [0.3393, 0.6206],  [0.1574, 0.0554]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1052},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.5.5","installedRecipes":[{"id":"android-messages","version":"1.3.0"},{"id":"discord","version":"1.1.3"},{"id":"gmail","version":"1.3.1"},{"id":"googlecalendar","version":"1.0.3"},{"id":"messenger","version":"1.1.0"},{"id":"msteams","version":"1.1.0"},{"id":"telegram","version":"3.0.0"},{"id":"whatsapp","version":"1.0.24"},{}],"devRecipes":[],"services":[{"id":"78649bd1-5e25-4b34-9b9b-dc661c6715d5","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"a3dbbabb-2187-48ff-8d05-d58a4fe46c32","recipe":"whatsapp","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"4702a6f5-5e24-408c-9cc9-df0662125da2","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"2c9ff454-e2d0-45e6-a0a2-20c62c6a6aec","recipe":"android-messages","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"124d3ccc-c733-48f0-a59b-998fa7f4e991","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"4320269e-961d-47a3-a8e6-14ed54717c73","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"84bc6c4e-8844-4bfd-b0fd-0ae50a91d144","recipe":"googlecalendar","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Downloading recipe from server"]},{"type":"log","info":["log","/home/kellett/.config/Ferdi/recipes/temp/gmail/recipe.tar.gz"]},{"type":"log","info":["log","[ServerApi::getRecipePackage] Downloading recipe from server"]},{"type":"log","info":["log","/home/kellett/.config/Ferdi/recipes/temp/whatsapp/recipe.tar.gz"]}],"workspaces":[],"windowSettings":{"width":1440,"height":752,"x":261,"y":139,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080}},"settings":{"autoLaunchInBackground":false,"runInBackground":false,"reloadAfterResume":true,"enableSystemTray":false,"startMinimized":false,"minimizeToSystemTray":"","privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-gb","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":"","serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by redeaconstrutora** [comment]
Same here
![image](https://user-images.githubusercontent.com/78929153/109704540-7c326680-7b75-11eb-840b-86b24b5a66c8.png)
![image](https://user-images.githubusercontent.com/78929153/109704571-85233800-7b75-11eb-9aa6-e1df0723c3dc.png)

**Comment by porfirioribeiro** [comment]
It's because of the electron version that is builded with a older chrome version that whatsapp web does not support.

If you are on a Arch based system you can install the nightly version on [AUR](https://aur.archlinux.org/packages/ferdi-nightly-bin/)

**Comment by redeaconstrutora** [comment]
> It's because of the electron version that is builded with a older chrome version that whatsapp web does not support.
> 
> If you are on a Arch based system you can install the nightly version on [AUR](https://aur.archlinux.org/packages/ferdi-nightly-bin/)
> 
> ![imagem](https://user-images.githubusercontent.com/499246/109809022-bce6ba00-7c1f-11eb-83a6-39f0a650b9ba.png)

Thank you, problem solved.

**Comment by carlosnewmusic** [comment]
I can't send files or audios on whatsapp.
![imagen](https://user-images.githubusercontent.com/19379457/114904683-653f8f00-9e18-11eb-9268-603ea6c61455.png)
![imagen](https://user-images.githubusercontent.com/19379457/114904774-7e484000-9e18-11eb-9f69-c80c3cab71ad.png)

**Comment by vraravam** [comment]
@Kellett - if your problem is solved (and since you opened this ticket for a specific behavior), could you please **close** the ticket?
@carlosnewmusic - please open a different ticket with all details. Did you try with the latest version of the recipe and the beta/nightly of Ferdi? (again - please log it as a separate ticket number)

**Comment by vraravam** [comment]
Closing the bug due to inactivity
