### ISSUE TITLE
Ferdi wants to export "com.apple.identities" from your keychain

### ISSUE THREAD

**Issue by steve-manes** [getferdi/ferdi#1226]
Periodically, with no predictable time frame, Ferdi will freeze with a spinning beach ball and a popup will appear:

'Ferdi wants to export "com.apple.identities" from your keychain'

I'm definitely not interested in granting Ferdi access to my admin login so I fill in my password and click "Deny".  Ferdi remains boinked and I have to use Force Quit to kill it.

There are no observable steps to reproduce this.  It just happens.

I can't.
![Screen Shot 2021-03-01 at 5 45 06 PM](https://user-images.githubusercontent.com/60283625/109570383-f13f6680-7ab7-11eb-814f-e2acf82a0159.png)

**Screenshots**

**Environment:**

- Operating System: MacOS 11.2.1 (Big Sur)
- Ferdi Version: 5.5.0 (5.5.0.2116)
- Server: Using without an account
![Screen Shot 2021-03-01 at 5 45 06 PM](https://user-images.githubusercontent.com/60283625/109571424-b0e0e800-7ab9-11eb-932f-52206d080278.png)

- Debug information:

{"host":{"platform":"darwin","release":"20.3.0","screens":[{"id":441049458,"bounds":{"x":0,"y":0,"width":2560,"height":1440},"workArea":{"x":0,"y":25,"width":2560,"height":1330},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6693, 0.3290],  [0.3283, 0.6204],  [0.1558, 0.0400]], transfer:0.0777*x + 0.0000 if x < 0.0450 else (0.9495*x + 0.0495)**2.3955 + 0.0003, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2560,"height":1440},"workAreaSize":{"width":2560,"height":1330},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":441041724,"bounds":{"x":-2560,"y":0,"width":2560,"height":1440},"workArea":{"x":-2560,"y":25,"width":2560,"height":1415},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6693, 0.3290],  [0.3283, 0.6204],  [0.1558, 0.0400]], transfer:0.0777*x + 0.0000 if x < 0.0450 else (0.9495*x + 0.0495)**2.3955 + 0.0003, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2560,"height":1440},"workAreaSize":{"width":2560,"height":1415},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"facebook","version":"1.0.1"},{"id":"hangouts","version":"1.0.2"},{"id":"messenger","version":"1.1.0"},{"id":"skype","version":"1.3.0"},{"id":"whatsapp","version":"2.0.3"},{}],"devRecipes":[],"services":[{"id":"1781ad30-7fe2-46df-bbcd-aed56bddb5af","recipe":"hangouts","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"7a3767cb-eadd-493b-ac31-2dad8e72fb2b","recipe":"hangouts","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"e6858ce1-ed70-400f-ba09-71f07e522dcc","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"616de625-a7c1-4182-90fb-9158c930f4db","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"c6c6a9fa-d655-49f6-bad0-23fac11fcb05","recipe":"skype","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"fdbb355d-8eb4-4936-9fed-fb2a9cc85fd7","recipe":"facebook","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"}],"workspaces":[],"windowSettings":{"width":962,"height":1047,"x":-981,"y":28,"displayBounds":{"x":-2560,"y":0,"width":2560,"height":1440},"isMaximized":false,"isFullScreen":false},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"navigationBarBehaviour":"never","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by mhatvan** [comment]
Hey @steve-manes, can you still reproduce this with the latest nightly from: https://github.com/getferdi/nightlies/releases ?

**Comment by steve-manes** [comment]
I have not.
