### ISSUE TITLE
Include the internal server when building ferdi

### ISSUE THREAD

**Issue by valerius21** [getferdi/ferdi#1227]
Hello there,

I am working/experimenting with adding some features to my fork of ferdi. 

After building and installing my fork on a VM I've come to an error, which yields that it lacks the internal server. 
I really don't wanna use an external server in my case and keep it locally.

Is there any way to include it in the installation?

![image](https://user-images.githubusercontent.com/10323945/109884115-bcc8d780-7c7c-11eb-885a-5a4296f707ed.png)

**Comment by vraravam** [comment]
@valerius21 - the `internal-server` is a git submodule. Please refer to the [CONTRIBUTING.md](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) file to ensure that you are following all steps exactly as described while building Ferdi from source.

The internal server code *is packaged* inside of the Ferdi distributable artefact.
