### ISSUE TITLE
Jitsi empty service

### ISSUE THREAD

**Issue by juanluisbaptiste** [getferdi/ferdi#1228]
**Bug description:**
Jitsi service window appears empty.

**Steps to reproduce:**

1. Click on Add new service
2. Search for Jitsi ans click on it
3. Click on save service
4. Go to the newly added service on the panel on the left
5. The window appears empty instead of showing jitsi.

**Expected behavior**
Jitsi app should appear, so it can be used.

**Screenshots**
![Screenshot_20210304_185651](https://user-images.githubusercontent.com/2113585/110047171-63fc4c00-7d1b-11eb-867d-46f3950a22c0.png)

**Environment:**

- Operating System: Kubuntu 20.04
- Ferdi Version:5.5.0
- Server: Using without account

- Debug information:
https://pastebin.com/8jDiWWf5

**Comment by juanluisbaptiste** [comment]
It works on the 5.6 beta.

**Comment by korbendallaskoop** [comment]
how about other instances, like https://fairmeeting.net/ or any self hosters? Is that doable somehow?
