### ISSUE TITLE
How to store credentials for a custom website ?

### ISSUE THREAD

**Issue by juanluisbaptiste** [getferdi/ferdi#1229]
Hi,

If I create a "custom website" service, is there a way for it to store its credentials ? currently I have to enter them each time I open ferdi, or when the website session times out or when the service gets hibernated. Other services like gmail do remember them, but looking at the recepies I don't see anything specific to this.

Thanks.

**Comment by nullket** [comment]
It is most likely that you custom website simply has a session cookie with a quite short life time. This means you will get logged out once you are too long inactive. Ferdi does not save password for other services like gmail. At those you log in once and then a cookie expressing how long this login is valid is stored in the cache of Ferdi. This somewhat of a comfort-function of the gmail website while the person being responsible for your custom website considers it as a security risk (shared computers etc.).

You can this outside ferdi in your regular browser (without auto filling passwords). Are you still logged in (in your custom website) after closing the browser/rebooting/waiting. Or do you (or your browser/password manager) have fill in the credentials again? 

If yes, then there is litte you can do (this is a policy set by the operator of your custom service). There are some tricks for regular browser but those might not work in Ferdi (Support of Addons etc.). 

I have the very same problem. I solved it in a way that would create a highly dangerous "security concearn" if you have other boundary conditions: I saved this password as plain text in a script which auto fills the credentials once the login page shows up. It should be obvious why this is bad: Everyone who can access this file has your password! Access could also mean somebody finds your laptop and connects your unencrypted hard drive directly without needing to login. This is extremely dangerous if you do not have unique passwords and the service is of high importance. 

As I have this problem only for a "ultra low-importance/low-risk" thing and the part of my drive with the password is encrypted before and shortly again after boot, I have created a `user.js` (look around the ferdi docs, it is a file to inject custom java script) which detects the login page and fills out the forms. 

Here is a snippet of such a `user.js`. Of course the path is and the IDs of the elements could be different (look into the console tools of your browser while being on the login page). 

**Again: Do not use this for if you do not know the security risk you are creating. Your password will be saved in plain text and could easily be stolen** 

```
if( currentPath === "/NameOfLoginPageInHtmlPhpAspx.html"){
		document.getElementById('username').value="def";
		document.getElementById('password').value="abc";
		document.forms[0].submit();
  }
```

**Comment by juanluisbaptiste** [comment]
@nullket , many thanks for the explanation. Indeed the website I'm adding to Ferdi does timeout the session after sometime. When opening it from a browser this is not an issue as the password manager makes it easy to log back in with a single click (as the login form is already filled in), but on ferdi I have to type them each time I need to access it which is very annoying.

About your workaround I completely understand your concerns but I will give it a try it anyways and look for a way to minimize the risk.

TY

**Comment by vraravam** [comment]
Closing the ticket since this doesn't seem to be something Ferdi can control.

**Comment by vraravam** [comment]
Please see this comment: https://github.com/getferdi/ferdi/issues/1118#issuecomment-926967173 for a "workaround"
