### ISSUE TITLE
No Notifications

### ISSUE THREAD

**Issue by EddieMaiale** [getferdi/ferdi#1232]
So I am not sure if this is a feature that is already included, but since I have added services to Ferdi, I have yet to see a notification or hear a notification sound come through Windows. I am using the latest build of Windows 10. Am I perhaps doing something wrong? I checked the notification settings on each app and they all state "enabled" for notifications.

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

**Comment by mhatvan** [comment]
I am running v5.6.1-nightly.48 and you can see in my screenshot that whatsapp is working correctly and delivering service, taskbar and tray notifications:

![Screenshot 2021-09-05 084735](https://user-images.githubusercontent.com/16797721/132118488-677faace-b538-4a10-8611-1a59d98b16fc.png)

Please comment on this issue in case you can reproduce this with a recent version of Ferdi.
