### ISSUE TITLE
Ferdi loading bug

### ISSUE THREAD

**Issue by devfelipereis** [getferdi/ferdi#1235]
I installed ferdi and everything was working fine. After restart the application, I got this behavior.

**Bug description:**
Application will open and will not load the service. Can't click in other services.
It opens loading Notion but I can't click anything.

![image](https://user-images.githubusercontent.com/5348752/110841042-31ef6a80-8284-11eb-93a8-d08e1c17d766.png)

After some time, application will show this screen.

![image](https://user-images.githubusercontent.com/5348752/110841103-45023a80-8284-11eb-86b6-90ab7fd38732.png)

**Steps to reproduce:**
Just close and open the application.

**Expected behavior**
Services must load.

**Environment:**

- Operating System: Fedora 33 (download rpm package)
- Ferdi Version: 5.6.0-beta.5
- Server: I created an account but I don't know wich server (I don't remeber to change anything).

- Debug information:
Can't get this infos. 

**EDIT**

I uninstalled it and remove everything from ~/config/Ferdi. Then, I installed it again and without a login this time, I did configure everything again. Until now, everything is working fine.
I restarted the application several times without any issues.

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

Also, if the issue fixed, please close the ticket in the future.
