### ISSUE TITLE
rebrand Riot to Element

### ISSUE THREAD

**Issue by aha999** [getferdi/ferdi#1238]
Riot renamed to Element, please change it in the Ferdi, also the logo and what goes with it.

Old riot link (redirects to Element): https://riot.im/
New website domain: https://element.io/

From Wikipedia:

> Element (formerly Riot and Vector) is a free and open-source software instant messaging client implementing the Matrix protocol.
> In July 2020, Riot was renamed to Element.

**Comment by vraravam** [comment]
From a tech perspective, this is already done. There is a newer recipe called 'Element'. Could you please try with the newer build of Ferdi? (maybe try with a beta or nightly version?)

**Comment by vraravam** [comment]
Closing the issue since this is now fixed and waiting for a new release.

**Comment by gnouts** [comment]
Will I need to delete old Riot and create new Element, or will my old Riot will automagically update and be rebranded as Element ?

**Comment by vraravam** [comment]
Yes - that will ensure the safest/surest way to achieve this.
