### ISSUE TITLE
Back to Service URL 

### ISSUE THREAD

**Issue by MosheGross** [getferdi/ferdi#1242]
**Is your feature request related to a problem? Please describe.**
Whenever following a link in Ferdi that takes me to a different site, it's rather complicated to get back to the original service URL.

Because even after hibernation or service reload (CTRL+R) it stays on the current page, and going back (CTRL+<) doesn't work in such a case.

Furthermore Clicking CTRL+HOME or Go to home page context menu takes me to the base of the current domain,
But in a case that the domain is now different, it will take to the domain's base not the service URL,
or in a case that the service URL is not the domain base (e.g. the default service URL for Github is https://github.com/notifications) it will take me to the domain base and not the service URL

**Describe the solution you'd like**
Add a context menu item or item in the top menu to take back to the service URL, and maybe a keyboard shortcut.

Alternatively changing the CTRL+HOME and Go To Home Page context menu to the service URL instead of the domain's base

**Describe alternatives you've considered**
Reloading Ferdi (CTRL+SHIFT+R) which obvs isn't ideal.

**Comment by vraravam** [comment]
This feature request has been implemented and merged in PR #900 and can be closed.
