### ISSUE TITLE
Bug: Android Messages "Use Messages for web here"

### ISSUE THREAD

**Issue by 8227846265** [getferdi/ferdi#1245]
**Bug description:**
When on Ferdi loads for the first time on boot up. Android Messages shows this pop up
![Ferdi_sL1rAMsUeS](https://user-images.githubusercontent.com/66582769/111178607-4ca84300-85e6-11eb-81be-ebf837087662.png)

I don't have another desktop app running that has Android Messages signed in nor another computer running that might cause the conflict.

Perhaps, it's because I'm using a VPN though I don't experience this issue in Rambox.

**Steps to reproduce:**
1. Add Android Messages as a service
2. Sign in
3. Reboot or completely closed Ferdi and open Ferdi again
4. Access Android Messages
5. Issue appears

**Expected behavior**
Pop up shouldn't appear

**Environment:**

- Operating System: Windows 10 x64
- Ferdi Version: 5.5.0
- Server: Ferdi

**Comment by vraravam** [comment]
This has nothing to do with Ferdi. Google's server has identified that there are 2 IPs associated with the android messages (web) - thus, in effect counting them as 2 different sessions. Once this scenario is deduced, then the popup gets triggered - from/by the server.

To fix this issue, you should use your Android Messages mobile app, go into the three-vertical-dots on the top right (called the context menu), and select "Messages for web". Here, all active sessions will show up - and you can evict the ones that are old.
