### ISSUE TITLE
Bug: Zoho Mail Landing Page Issue

### ISSUE THREAD

**Issue by 8227846265** [getferdi/ferdi#1246]
**Bug description:**
Every time I open Zoho Mail for the first time in every boot on Ferdi. It doesn't send me to my Zoho Mail Inbox and "Access Zoho Mail" page keeps appearing as default landing page.

**Steps to reproduce:**
1. Add "Zoho Mail" as a service
2. Sign in to Zoho Mail
3. Reboot or completely close Ferdi and open it again
4. Select Zoho Mail

**Expected behavior**
If already signed in. It should directly send me to my Zoho Mail inbox next time I open it.

**Screenshots**
![image](https://user-images.githubusercontent.com/66582769/111179314-ea9c0d80-85e6-11eb-8311-603996a7b6b6.png)

**Environment:**

- Operating System: Windows 10 x64
- Ferdi Version: 5.5.0
- Server: Ferdi

**Comment by vraravam** [comment]
Though the above page comes up, clicking on the "Access Zoho mail" green button takes you into the zoho mail page without forcing a new login. Please try with the latest nightly build of Ferdi and check / close this issue.
