### ISSUE TITLE
Nightly not present after 5.6.0-nightly.15 (5.6.0-nightly.15.2890)

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1254]
I see commits into the master branch that talk about higher nightly versions, but this is not present in the nightlies project. Could someone please investigate?

**Comment by vraravam** [comment]
@kytwb - tagging you here for some help.

**Comment by kytwb** [comment]
@vraravam there is a build error on AppVeyor so some assets are missing from the nightly release draft: https://ci.appveyor.com/project/kytwb/ferdi/builds/38350916#L82

![Screen Shot 2021-03-24 at 1 33 37 PM](https://user-images.githubusercontent.com/412895/112311052-8c85bf00-8ca5-11eb-8c7e-89f03c8b5c95.png)

**Comment by vraravam** [comment]
thanks for getting back @kytwb - is someone looking to fix the issue?

**Comment by kytwb** [comment]
@vraravam I took a quick look at it but the source of the error isn't obvious to me; I will have to take another look at it.

**Comment by kytwb** [comment]
The error is `RangeError: Invalid string length`. I think we are running out of memory.

**Comment by vraravam** [comment]
@kytwb - would it be possible to get access to the assets that you have shown in the screenshot above? I couldn't find it myself. Maybe I can run the mac dmg file, and report back on any memory issues that I face?

**Comment by kytwb** [comment]
@vraravam I'm concerned publishing the release with missing assets will have unexpected side effects for users currently subscribed to nightly releases on Windows via the auto-updater.

Please wait until I get time to investigate more and fix the issue, thank you.

**Comment by vraravam** [comment]
no @kytwb - since I am on macos, if you can send me a direct download link for the dmg file, i can test.

either ways - your call. i can wait too.

**Comment by vraravam** [comment]
@kytwb - would it be possible to release a new nightly ?

**Comment by vraravam** [comment]
ping - any news on this please?

**Comment by vraravam** [comment]
sorry - but, at this time, it looks like there's no interest in this project? After repeated pings and requests on various issues and PRs - and even some activity on forks, where PRs have been raised, there's no traction. :(

**Comment by vraravam** [comment]
@kytwb @vantezzen - any idea if you had been able to fix the appveyor issue? Its been a month since I opened this issue, and I was hopeful for a new nightly to get the latest.
If you are not able to provide it, please do say so - so that we can stop having hopes and move on from ferdi.

**Comment by keunes** [comment]
@vraravam I'm also hoping that they will find the time and motivation to continue working on this great project. However, with all due respect, spamming them every week probably has an adverse effect. So let's be patient, and create a fork or reach out to them with a proposal to take over the project if it in a month or two the project appears dead.

**Comment by vraravam** [comment]
Sorry @keunes - I only partially agree with your statement.

I have been patiently waiting - and have even contributed as per the guidelines in the "help wanted" issue that has been pinned on top of the issues page. (in terms of testing a forked release to check if it works on an ARM mac, as well as replying to other issues, and even did a PR last night for some security fixes.) I have offered to test the appveyor artefacts. Not sure what else I can do to help. If there is no response at all, it does not allow us to think any other way.

I have also tried to build the latest code on my local - but, have faced issues both on the non-ARM as well as the ARM-based macs. If there's anyone who can help with the above, then I would go to the next step and offer to take over/fork and continue to carry the torch.

The product is great - no doubt about it. And as an OSS contributor for the past 20 years, I can understand the demands on time can be overwhelming, but, staying mum is kind of defeating the purpose of OSS collaboration.

Sorry to rant so much early on a Sunday morning (at least here in India)

**Comment by vraravam** [comment]
Finally - I was able to build the latest codebase with the upgraded node version `12.22.1`. Signing is not possible due to not having the certificates available - but, the `Ferdi.app` was built on the `out/mac/` folder - and I am posting this message from within Ferdi nightly 18.

**Comment by vraravam** [comment]
@kytwb - is there a way that you can add me or one of the other active contributors - so that we can try to debug and fix the appveyor issue?

**Comment by nullket** [comment]
@vraravam I see you do a lot to update Ferdi and fix the nightly builds! Thanks a lot, I assume there are more like me, following your and kris7t commits being super happy to see all that progress. 

I had a quick glance at the logs. Is it correct that only the osx builds are still broken?

**Comment by vraravam** [comment]
thanks @nullket - The windows and macos builds are also broken atm: 
[Travis Nightly broken build](https://travis-ci.org/github/getferdi/ferdi/jobs/769710346) - errored out while notarizing the app
[Appveyor builds broken due to expired certificate](https://ci.appveyor.com/project/kytwb/ferdi/history)

**Comment by vantezzen** [comment]
@vraravam Thank you for your active participation in this project! I have given you some extended permissions for the repo so you should be able to access release artifacts, @kytwb would need to give you access to AppVeyor as I can't seem to give you those permissions myself.

**Comment by vraravam** [comment]
thank you @vantezzen.

**Comment by vraravam** [comment]
For those folks following along on this issue, if you are on macos, I am building the code and publishing on a frequent basis into [this gDrive folder](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv). This is NOT an official artifact repository - just to enable those of us who are die-hard fans of Ferdi to continue to use it while @kytwb and others try to fix the broken nightly process.

**Comment by nullket** [comment]
As nightly build (for Linux) are still broken I thought would give it a try mussels. I used your recently introduced docker method for building and it built well, but the Linux amd64 binary crashed on start (a module was missing - I know not sufficient description of the failure but I am on mobile and this particular failure is not my point here). Are you already in the stage that we should create issues for such things or is everything too much subject to change right now?

**Comment by vraravam** [comment]
@nullket - could you please raise a separate issue for the docker builds on linux? I am on a mac, and so can't verify/help.

Please include as much of the stack trace as you can to help others debug the issue. Thanks!

**Comment by vraravam** [comment]
Closed since we now have nightlies 🎉
