### ISSUE TITLE
OpenCollective suggested tiers

### ISSUE THREAD

**Issue by beck** [getferdi/ferdi#1262]
Sorry this is not a "bug" but more-so a suggestion/ask about donation.

**As is**

The suggested monthly amounts are $5 / $10 / $25 / $50

The lowest one can contribute is $60/year and if you try to subscribe monthly, say $24/year, OpenCollective throws an error saying you're below the minimum.

Granted, one can always do a one-time donation but IMO backing software with a monthly sub is nicer because they can somewhat project future income.

**Suggestion**

Set the minimum to $1 so folks can donate at any price point.

**Comment by vantezzen** [comment]
Thank you for this feedback. We mostly left the tiers on the default setting which was $5 - I now reduced the minimum amount to $1

<img width="635" alt="Screenshot 2021-04-13 at 10 56 21" src="https://user-images.githubusercontent.com/10333196/114526012-e47d6900-9c46-11eb-9d26-8f04210a0055.png">
