### ISSUE TITLE
Invalid recipes

### ISSUE THREAD

**Issue by Rovaro** [getferdi/ferdi#1267]
### Bug description:

It seems that there are some issues when downloading new services. The recipes are invalid.

I try to add a new service as follows:
1. Click on "Add new service"
2. Fetch for a service (Feedly for example) and click on it
3. Nothing happens

Watching the console inside the Developers Tools, I can see the following:
> /home/\<user\>/.config/Ferdi/recipes/temp/feedly/package.json: ENOENT: no such file or directory, open '/home/\<user\>/.config/Ferdi/recipes/temp/feedly/package.json

Also, the file `/home/<user>/.config/Ferdi/recipes/temp/feedly/recipe.tar.gz` has been downloaded, which is in fact a JSON file:
```json
{"message":"Recipe not found","code":"recipe-not-found","recipeId":"feedly"}
```
---
I've seen this behaviour for some services (not all of them). I haven't checked every single service in the catalog:
* Services in which I have encountered this issue:
    * Feedly
    * Fleep
    * Airtable
    * Evernote
    * ...
* Services without issues:
    * Github
    * Instagram
    * ...
---
### Environment:

- Operating System: `5.4.105-1-MANJARO`
- Ferdi Version: `5.5.0` (from Official Repositories of Arch Linux - Community)
- Server: https://api.getferdi.com - With & without an account

**Comment by BlueDrink9** [comment]
Happening for me as well with Manjaro, but with local server

**Comment by vantezzen** [comment]
This is unfortunately a problem with Ferdi 5.5.0 and the new recipe book. Can you try upgrading to a Ferdi 5.6 beta to see if that fixes it?
We are currently in the process of finally releasing 5.6 but our build chain is causing some problems.

**Comment by vraravam** [comment]
@Rovaro , @BlueDrink9 : Could you please try the step that @vantezzen suggested? And get back to us whether this is still a problem or not? IF so, we will try to prioritize it and get it solved asap.

**Comment by BlueDrink9** [comment]
Problem seems gone for me using `ferdi-manjaro-5.6.0.beta.5.r150.g0aaaaeb1-1.1`

**Comment by vraravam** [comment]
@Rovaro - could you also please confirm? We can then close this ticket.

**Comment by Rovaro** [comment]
I've moved to `ferdi-bin 5.5.0-3` (AUR repositories, as commented in https://github.com/getferdi/ferdi/issues/1267#issuecomment-814602733) and it works for me now :ok_hand:.
