### ISSUE TITLE
Show Ferdi changelog for updates

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#127]
**Describe the bug**
When an update is available, the "What's new" page display Franz changelog.

**To Reproduce**

1. Check for updates
2. Wait for updates to download
3. Click on "What's new" in the bottom bar inviting to restart to apply the update

**Expected behavior**
Changelog in What's new should show Ferdi changelog instead of Franz's.

**Screenshots**

<img width="736" alt="Screen Shot 2019-10-18 at 10 26 39 AM" src="https://user-images.githubusercontent.com/412895/67063764-13ba3380-f192-11e9-8351-81fa948d3776.png">

**Comment by vantezzen** [comment]
Are you on the latest commit in develop? I should have fixed that yesterday (<https://github.com/getferdi/ferdi/blob/develop/src/features/announcements/api.js#L15>)

**Comment by kytwb** [comment]
@vantezzen It happened with my production Ferdi if I remember correctly. All good then! 👍
