### ISSUE TITLE
Hangouts pop-up window cannot be opened

### ISSUE THREAD

**Issue by crzsotona** [getferdi/ferdi#1271]
**Bug description:**

**Steps to reproduce:**

1. Add Hangouts service
2. Login
3. Select any contact
4. Start call with contact

**Expected behavior**

New pop-up window with call is opened
**Screenshots**
![image](https://user-images.githubusercontent.com/13541485/114071970-64ec4480-98aa-11eb-922b-7ff50b8d7981.png)

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.5.0
- Server: No account

- Debug information: https://gist.github.com/crzsotona/0a92bc5d09abf4a2e06b78f2a0a4d317

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

**Comment by vraravam** [comment]
@crzsotona - the latest nightlies are supposed to fix audio calling with different services - please get back to us whether this is still a problem. If so, please reopen the ticket. Till then, I am closing this ticket.

**Comment by crzsotona** [comment]
@vraravam I've rechecked on v5.6.0, and it seems that problem is gone, kudos to developers team!
