### ISSUE TITLE
Ferdi 5.5.0 freezes Linux Mint 20

### ISSUE THREAD

**Issue by wiligl** [getferdi/ferdi#1272]
When I am running Ferdi 5.5.0 with 12 different  social media platforms on Linux Mint 20.x on a Samsung 900X notebook (8G RAM), average cpu usage is about 80-100% (fan turns louder) and usually after working for 15 minutes (especially with MatterMost) the computer freezes and needs reboot. This never happens with other apps.

**Steps to reproduce:**

**Expected behavior**

**Screenshots**

**Environment:**

- Operating System: 
- Ferdi Version: 
- Server: 

- Debug information:

**Comment by vraravam** [comment]
With the latest version of Ferdi, this should no longer be the case.

Can you please try with the linux builds that I have shared [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)? I do not know if they are packaged correctly - so, please provide feedback whether they are working or not.

**Comment by wiligl** [comment]
Thanks, I need access! /Wilmar--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 22/05/2021, 11:06 Vijay Raghavan Aravamudhan ***@***.***> wrote:

   
  With the latest version of Ferdi, this should no longer be the case. 
  Can you please try with the linux builds that I have shared here? I do not know if they are packaged correctly - so, please provide feedback whether they are working or not.

**Comment by kris7t** [comment]
@wiligl Nightlies should now be available at https://github.com/getferdi/nightlies/releases
