### ISSUE TITLE
Android Messages no longer loads

### ISSUE THREAD

**Issue by michaeldrouin** [getferdi/ferdi#1278]
**Bug description:**

Android Messages now only produces a blank screen. It seemed like it started after AM displayed a message saying "A new version of Messages is available, please reload the page." or something along those lines
**Steps to reproduce:**

Just open Android Messages

**Expected behavior**
Android Messages to load

**Screenshots**

![Screenshot 2021-04-14 082930](https://user-images.githubusercontent.com/7315656/114737138-924a4f80-9cfb-11eb-8268-2495c77ee96f.png)
**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.6.0-beta.5 (x64)
- Server: Ferdi

- Debug information:

[ferdi.json.txt](https://github.com/getferdi/ferdi/files/6311912/ferdi.json.txt)

**Comment by mastercko** [comment]
I just saw this as well. 

This is my Ferdi info window:
![image](https://user-images.githubusercontent.com/6900268/114757205-6be2df00-9d10-11eb-8a23-46cecfd54d9b.png)

Other information:
- OS: Windows 10 Version 10.0.19042 Build 19042
- Server: Franz

**Comment by michaeldrouin** [comment]
my full ferdi info:

![Screenshot 2021-04-14 111500](https://user-images.githubusercontent.com/7315656/114759183-b1a0a700-9d12-11eb-97c0-c470ca128627.png)

**Comment by zkhcohen** [comment]
Yep. It's dead:

![image](https://user-images.githubusercontent.com/12313533/114763380-92f0df00-9d17-11eb-8980-0edb3fedd6d9.png)

**Comment by michaeldrouin** [comment]
so interestingly i switched over my my linux partition and it works fine. i'll note that my linux partition has a different version of everything:

Ferdi: 5.5.0 (x64)
Election: 8.2.3
Node.js: v12.13.0

System: Ubuntu 18.04.5

**Comment by michaeldrouin** [comment]
i just downgraded my Windows partition's installed version to the 5.5.0 release and can confirm Android Messages is working again.

**Comment by mastercko** [comment]
Yeah, same here. I also downgraded after I saw your first note about it working and 5.5.0 is working for me, too.

**Comment by mastercko** [comment]
So I needed to go back to 5.6.0 because I was having issues with Teams on 5.5.0.

So I'm back to Messages being broken. That said, I checked the Developer Tools and it looks like it's throwing errors based on attempting (and failing) to access the property `_electron.webFrame.session.setSpellCheckerLanguages` in the following line of `spellchecker.js`

```javascript
    if ("darwin" !== t) try {
        debug("Trying to load dictionary", e), _electron.webFrame.session.setSpellCheckerLanguages([...e, "en-US"]), debug("Switched dictionary to", e), _isEnabled = !0
    } catch (e) {
        console.error(e)
    }
```

Full error is below:
```
    C:\Users\MasterCKO\AppData\Local\Programs\ferdi\resources\app.asar\webview\spellchecker.js:1 TypeError: Cannot read property 'setSpellCheckerLanguages' of undefined
    at switchDict (C:\Users\MasterCKO\AppData\Local\Programs\ferdi\resources\app.asar\webview\spellchecker.js:1)
    at _temp.update (C:\Users\MasterCKO\AppData\Local\Programs\ferdi\resources\app.asar\webview\recipe.js:1)
    at C:\Users\MasterCKO\AppData\Local\Programs\ferdi\resources\app.asar\webview\recipe.js:1
    at reactionRunner (C:\Users\MasterCKO\AppData\Local\Programs\ferdi\resources\app.asar\node_modules\mobx\lib\mobx.js:2097)
    at trackDerivedFunction (C:\Users\MasterCKO\AppData\Local\Programs\ferdi\resources\app.asar\node_modules\mobx\lib\mobx.js:759)
    at Reaction.track (C:\Users\MasterCKO\AppData\Local\Programs\ferdi\resources\app.asar\node_modules\mobx\lib\mobx.js:1787)
    at Reaction.onInvalidate (C:\Users\MasterCKO\AppData\Local\Programs\ferdi\resources\app.asar\node_modules\mobx\lib\mobx.js:2078)
    at Reaction.runReaction (C:\Users\MasterCKO\AppData\Local\Programs\ferdi\resources\app.asar\node_modules\mobx\lib\mobx.js:1753)
    at runReactionsHelper (C:\Users\MasterCKO\AppData\Local\Programs\ferdi\resources\app.asar\node_modules\mobx\lib\mobx.js:1890)
    at reactionScheduler (C:\Users\MasterCKO\AppData\Local\Programs\ferdi\resources\app.asar\node_modules\mobx\lib\mobx.js:1868)
```

**Comment by mastercko** [comment]
Looking into it some more, the spellchecker.js I'm seeing in my currently installed build (5.6.0.nightly.15 build) is totally different from the one the [latest commit](https://github.com/getferdi/ferdi/blob/e3898e2f47db4d056c03708221901d58eb47c8f5/src/webview/spellchecker.js) in overall structure and in the specific call to `session.setSpellCheckerLanguages`. So I'm guessing this might be solved if the team can get another nightly build published.

**Comment by stacksjb** [comment]
I downloaded the latest nightly and it resolved the issue for me.

**Comment by mastercko** [comment]
What is the information on your environment? I am still unable to use it on 5.6.0.nightly.15, which as far as I know is the latest build. 

- OS: Windows 10
- Version: 10.0.19042 Build 19042
- Ferdi About Window
![image](https://user-images.githubusercontent.com/6900268/115070181-708ecb00-9ea9-11eb-90f1-501e305899bd.png)

**Comment by stacksjb** [comment]
OS: Mac OS X Big Sur 11.2.3 (20D91)
Ferdi About Window:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/2865491/115070968-dfbced00-9eb2-11eb-9b5f-85280e4d29f9.png">

**Comment by mastercko** [comment]
Huh, that's interesting that it works on Mac, but not windows...

**Comment by crunchysoft** [comment]
Is there anyone who was able to get it working on Windows?

**Comment by binarymelon** [comment]
Still not loading for me on the latest nightly (win10).

**Comment by stormy1777** [comment]
Same thing here :) any w/a ?

**Comment by Dunkh4n** [comment]
Same thing for me :'(

**Comment by vraravam** [comment]
I just reimaged my mac - and its not working. I'm also running the same Ferdi nightly version.
@kytwb @vantezzen - any help please?

**Comment by vraravam** [comment]
Update: On my newly reimaged MBP (non M1), I manually installed the nightly (v15) and now, Android Messages works without any issues. Please try it out and get back with updates here so as to help the maintainers with new information.

**Comment by dylan-k** [comment]
I have this issue also, on Windows 10 Pro, running Ferdi 5.6.0.-beta.5 (x64)

fwiw I tried tinkering with spell check settings, since an earlier comment suggested that could be related, but nothing fixed it there.

**Comment by vraravam** [comment]
@dylan-k - please check the recipes in [this folder](https://github.com/getferdi/recipes/tree/master/recipes/android-messages) - most likely, you might have to replace your local `webview.js` and `index.js` from the above url into your local installation. Please try this after closing/quitting Ferdi first, applying the latest version and restarting Ferdi. If you want, you should take a backup of your older versions in case you want to rollback.

If the above works, then please be sure to upvote this [feature request](https://github.com/getferdi/ferdi/issues/1302) since it provides a user-centric (non-techie) way to address this problem for the future.

**Comment by vraravam** [comment]
@michaeldrouin - please test the above - and if it works, please close this issue.

**Comment by mastercko** [comment]
Did not work in my environment (5.6.0-nightly.15)

**Comment by michaeldrouin** [comment]
> 
> 
> @michaeldrouin - please test the above - and if it works, please close this issue.

did not work on neither the nightly nor the beta. these files are exactly the same as what's in my local installation on both anyway.  currently still having to downgrade to the current stable release for it to work.

**Comment by 8restcoop8** [comment]
It started working for me again today on 5.6.0-nightly.15

**Comment by binarymelon** [comment]
> It started working for me again today on 5.6.0-nightly.15

Same here

**Comment by mastercko** [comment]
Yep, same here. I wonder if something changed on the Google side?

**Comment by dylan-k** [comment]
Yes it works for me now after updating to the latest nightly, 5.6.0-nightly.15

**Comment by Dunkh4n** [comment]
it works for me now on Windows 10 Pro, running Ferdi 5.6.0.-beta.5 (x64)

**Comment by michaeldrouin** [comment]
as others are saying, the problem seems to have fixed itself in both the beta and nightly. there must have been something with Google that temporarily broke it. closing the issue now.
