### ISSUE TITLE
Update Chrome

### ISSUE THREAD

**Issue by fabiodiamix** [getferdi/ferdi#1279]
The Chrome I use in Windows is version 90, but in Ferdi it appears as 83. How do I update the version in Ferdi's Chrome, because the Harvest application shows problems with the browser version.
Tks
![ScreenClip](https://user-images.githubusercontent.com/5331908/115113162-45ff4980-9f5f-11eb-92c5-b7295302e2ad.png)

**Comment by vraravam** [comment]
I have the same /similar error. I'm on ferdi nightly 15 - but, even that is considered old. please release a new nightly or a new GA version.

**Comment by fabiodiamix** [comment]
Hi @vraravam , I have updated to the nightly version, but the problem persists, on the computer the chrome version is current but not in Ferdi. Thank you for your help.

**Comment by vraravam** [comment]
The version of Chrome cannot be upgraded unless the maintainers of Ferdi release a new version. Even then, they are themselves limited to whatever comes across in Electron.

If this is being inferred from the user-agent setting, you might be able to follow directions in other blogs/help/wikis to change the user-agent and try it out - YMMV though.
