### ISSUE TITLE
Enhance announcements feature

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#128]
I tried to disable the announcement feature with https://github.com/getferdi/ferdi/commit/1a6017c81d3a8fc385b0f637ce5a7417ee768e9a (until we have our own announcements coming from our own server), but it is still making requests to the announcements API. Moreover, it seems to be making the request every time I switch services, which can slow things down.

![Kapture 2019-10-18 at 12 54 33](https://user-images.githubusercontent.com/412895/67069377-20955200-f1a7-11e9-9d50-6c3a1f12d1bc.gif)

**Comment by vantezzen** [comment]
Just as an information: Ferdi will always fetch the announcements from the server you select - we do already have announcements coming from `api.getferdi.com`, e.g. I created an announcement for 5.4.0.

**Comment by kytwb** [comment]
I think it's preferable to get the announcements from the Ferdi API then as to not cause confusion to Ferdi users with Franz API announcements?

**Comment by vantezzen** [comment]
Yes, I think your idea is better.

**Comment by vantezzen** [comment]
I just looked into this: You havn't actually disabled announcements with 1a6017c:
You only disabled the local default settings. These settings [will be overwritten](https://github.com/getferdi/ferdi/blob/develop/src/stores/FeaturesStore.js#L58) by the server's settings in the store. The ferdi-server will [enable announcements](https://github.com/getferdi/server/blob/master/app/Controllers/Http/StaticController.js#L21) again. 
You could add an option to the settings store to disable announcements on the client side.

**Comment by kytwb** [comment]
@vantezzen Understood, thanks for the explanation; I reverted and let it enabled in the local default settings now the announcements are always coming from Ferdi's API.
