### ISSUE TITLE
Remove Franz side bar on Ferdi

### ISSUE THREAD

**Issue by thomasplt** [getferdi/ferdi#1282]
> 
<img width="1532" alt="Capture d’écran 2021-04-19 à 12 15 35" src="https://user-images.githubusercontent.com/82810630/115220825-4f2c1a00-a109-11eb-9f42-52694dc45ea1.png">

Hi, I use the mac app version of Ferdi. Can you please let me know how to remove Franz sidebar on Ferdi? Please find attached a screenshot. Thank you, Thomas

**Comment by ThiruIO** [comment]
CMD + T should hide the Franz Todos drawer.

**Comment by kris7t** [comment]
You can disable the todo sidebar by setting _Settings > Generat > Enable Ferdi Todos_ to off.

**Comment by vraravam** [comment]
@thomasplt - The ToDos sidebar is a feature that other users use. As @kris7t posted above, if you don't want it, please disable in prefs.

Or is your issue more towards asking to fix the content so it reflects Ferdi-branding as opposed to Franz?

**Comment by keunes** [comment]
Happy to read that you now have necessary rights in this repo @vraravam :)

I guess it would be good to 'correct' the branding. What would be needed to do so?

**Comment by vraravam** [comment]
@keunes - I will try to follow the code and see where this sidebar is coded - and try to rebrand to Ferdi.

I assume that the original OP's question is answered though: if (as a user) you want to disable the TODO's drawer, you can do that in the menu up on top. Also, you can disable the feature completely in the Settings/Preferences window.
