### ISSUE TITLE
Whatsapp notifications don't go to conversation

### ISSUE THREAD

**Issue by lupus2k** [getferdi/ferdi#1284]
When i click to a Whatsapp notification, it switch to whatsapp service but it won't open the conversation of the notification...
Anyone has this problem? I'm on MAC

**Comment by leoheck** [comment]
Same here on 5.5.0

**Comment by lupus2k** [comment]
Any news on this ?

**Comment by vraravam** [comment]
We are constructing the logic of the service, message, etc for the notification in the same manner for all services. If WA does not behave this way, then I think its a problem on the WA side as opposed to something that we can control.

**Comment by mhatvan** [comment]
Does anyone know if e.g. Rambox handles this correctly and jumps to the conversation of the notification? If not then we can close this since we can't control it.

**Comment by lupus2k** [comment]
I think it's a Whatsapp problem, I tried Rambox, Ferdi, and another one I did not remember now and neither goes to the message, only the WHATSAPP APP!

**Comment by vraravam** [comment]
thanks for confirming @lupus2k - I will close this ticket now.
