### ISSUE TITLE
Grammarly support for Ferdi

### ISSUE THREAD

**Issue by Schmouly** [getferdi/ferdi#1285]
Hello guys, 
I know that this topic is also covered in some issues on the franz repo but yet as franz is quite dead 😅 I wanted to put it out there again !
I would love to be able to have the ability to have Grammarly and other languages chrome extension on my side when using Ferdi 🤓

**Comment by Jendker** [comment]
It would make sense to verify if Grammarly is compatible with Electron's Chrome extensions https://www.electronjs.org/docs/api/extensions

**Comment by vraravam** [comment]
Also - please move this feature request to the [recipes](https://github.com/getferdi/recipes/issues) repo.

**Comment by vraravam** [comment]
Extensions support is being tracked in #113 - closing this ticket.
