### ISSUE TITLE
no confirmation dialog is shown for deleting a service

### ISSUE THREAD

**Issue by beppe9000** [getferdi/ferdi#1286]
**Is your feature request related to a problem? Please describe.**
people can easy misclick delete for disable in the service icon contextual menu

**Describe the solution you'd like**
yes/no confirmation dialog

**Describe alternatives you've considered**
requiring shift + right click to show the delete item, but it is hard to discover for users

**Comment by vraravam** [comment]
@beppe9000 - As seen in the linked PR, this has been implemented and merged into the `develop` branch.

Which operating system are you running Ferdi on? and which version of Ferdi are you currently on?

**Comment by beppe9000** [comment]
![image](https://user-images.githubusercontent.com/6625123/118264465-05d8ab80-b4b8-11eb-92d1-beeeec7ea292.png)
![image](https://user-images.githubusercontent.com/6625123/118264434-f8bbbc80-b4b7-11eb-8f99-60406ab89368.png)

**Comment by vraravam** [comment]
Thanks for the info @beppe9000 - unfortunately I dont have a way to build for windows. Will have to wait for the nightly builds to get fixed for this to get resolved.
cc @kytwb

**Comment by beppe9000** [comment]
If this is already in the code we can probably close the issue and reopen if necessary.
