### ISSUE TITLE
Add visual indicator when new update is available

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#129]
Related to https://github.com/getferdi/ferdi/issues/111, as otherwise the dock icon is bouncing to get the user attention (on the available update) without any visual clue to where to look at. Proposing to add a red dot on the settings icon if an update is available.

**Comment by vantezzen** [comment]
Very good idea, I now implemented this as of cf62335. The settings icon will get a red dot, which will blink a few times when an update just became available (as the user might not notice the dot after the icon bounced in their dock).

![Screen Recording 2019-10-18 at 10 59 45](https://user-images.githubusercontent.com/10333196/67081121-e02dd800-f196-11e9-9d1a-7d9484b13561.gif)
(The video is a looping GIF, that is why you see it blinking, stopping at a solid color and then suddenly disappearing again).

**Comment by kytwb** [comment]
@vantezzen LGTM 👍

**Comment by incace** [comment]
Unfortunately, this overlays the unread messages notification. Very cool but maybe top right corner is better?

![image](https://user-images.githubusercontent.com/61343/67623411-35469b00-f7e2-11e9-8081-d8ed407c4d61.png)

**Comment by vantezzen** [comment]
@incace The indicator you are writing about is the [hibernation indicator](https://github.com/getferdi/ferdi/issues/75) - services with this indicator are currently hibernating.

Regardless, I moved the hibernation indicator to the bottom left now.
