### ISSUE TITLE
Loosing all data when signing up

### ISSUE THREAD

**Issue by matheusfillipe** [getferdi/ferdi#1292]
This is not a bug, or maybe it is since it is a pretty darn needed and expected feature. (At least to me 😅)

So I first heard about ferdi, was testing without signup for a few hours, added many of my accounts then decided to sign up on ferdi. Suddenly I lost all accounts I had signed in. Well this is a big awkward isn't it? It could keep all the preferences and logins after singning in or up.

**Comment by vraravam** [comment]
@matheusfillipe - please see [this page](https://help.getferdi.com/server/transfer) - about transfering data from the internal server to the hosted ones. You can choose to use it with either a ferdi.com server or franz.com server.

**Comment by vraravam** [comment]
@matheusfillipe - if the above has fixed your issue, could you please close this bug ticket?
