### ISSUE TITLE
Process Manager shows only a white window

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1296]
**Bug description:**
Process Manager opens a window - but, its always a white screen without any content.

**Steps to reproduce:**
1. Go to 'Settings'
2. Click on 'Advanced'
3. Click on the 'Open Process Manager' button
4. See a new window - but, it remains white all the time

**Expected behavior**

**Screenshots**

**Environment:**

- Operating System: macOS BigSur 11.2.3
- Ferdi Version: 5.6.0-nightly.18
- Server: Franz

- Debug information:
{"host":{"platform":"darwin","release":"20.3.0","screens":[{"id":2077748985,"bounds":{"x":0,"y":0,"width":1792,"height":1120},"workArea":{"x":0,"y":25,"width":1792,"height":1095},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":30,"colorSpace":"{primaries:SMPTEST432_1, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":10,"size":{"width":1792,"height":1120},"workAreaSize":{"width":1792,"height":1095},"scaleFactor":2,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.0-nightly.18","electron":"10.4.3","installedRecipes":[{"id":"android-messages","version":"1.3.0"},{"id":"franz-custom-website","version":"1.0.2"},{"id":"github","version":"2.0.0"},{"id":"gitlab","version":"1.0.0"},{"id":"gmail","version":"1.3.5"},{"id":"googlecalendar","version":"1.0.3"},{"id":"hangoutschat","version":"1.4.0"},{"id":"slack","version":"1.0.16"},{"id":"whatsapp","version":"2.0.8"},{"id":"yahoo-mail","version":"1.0.0"},{}],"devRecipes":[],"services":[{"id":"86b5ee3b-35c4-4c86-b626-d5e76000da12","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"5c9efb4f-d247-4214-90d3-4eb035f09721","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"d458ab52-0583-4c18-b048-1e3e804f1d09","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"7c620993-64f1-4ac9-b231-e09d06d433dc","recipe":"hangoutschat","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"114cbe89-cc52-4d3f-a50e-6979a7077e89","recipe":"android-messages","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"c18f7665-171a-4037-9ffe-37e3165b9696","recipe":"googlecalendar","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"24df9179-d524-4a27-be8f-77f93f81e789","recipe":"github","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"5f7fd1d8-8a49-47e4-8344-3eea5dfa2ef9","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"be02b66c-11f4-4a7d-b998-93ca15cb42b9","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"34dbed2e-8879-42b0-99b1-38761d8aa1a0","recipe":"gitlab","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"4ffdd8bd-d79f-4bd9-af6b-21d6e461c5a9","recipe":"yahoo-mail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Failed prop type: The prop `hasAddedTodosAsService` is marked as required in `_class2`, but its value is `null`.\n    in _class2 (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _temp)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _temp)\n    in _temp (created by inject-_temp-with-stores-actions)\n    in inject-_temp-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"log","info":["log","Nair Kadai ☕☕☕",{"tag":"919962455655-1404617054@g.us","renotify":true,"dir":"auto","lang":"en","silent":true,"body":"Manikandan Svce Mech‎: 37 runs in 20th over is going waste‎","icon":"https://web.whatsapp.com/pp?e=https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.24694-24%2F57562845_681728955576436_4409366155110645760_n.jpg%3Fccb%3D11-4%26oh%3Df2187da1af3b635307d338cb6a3d527b%26oe%3D6089ECB4&t=s&u=919962455655-1404617054%40g.us&i=1519883720&n=4jjnVgq%2BHqMLOkNn3lyRZ2Zi68NMpBDN3HIEfWpdXBU%3D"}]}],"workspaces":[{"id":"13db4596-2719-49e0-8b0a-573d67fed719","services":[null,null,null,null]},{"id":"52d7ecc6-19d7-42ee-bb07-f19aa5d2cd38","services":[null,null,null,null,null,null]}],"windowSettings":{"width":800,"height":600,"x":0,"y":25,"isMaximized":true,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1792,"height":1120}},"settings":{"autoLaunchInBackground":false,"runInBackground":false,"reloadAfterResume":true,"enableSystemTray":false,"startMinimized":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"notifyTaskBarOnMessage":true,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"en-US\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"]\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":false,"adaptableDarkMode":true,"accentColor":"#1974fc","serviceRibbonWidth":"45","iconSize":"20","sentry":true,"nightly":true,"navigationBarBehaviour":"always","useVerticalStyle":false,"alwaysShowWorkspaces":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by vraravam** [comment]
Looks like the npm modules are [no longer working](https://github.com/dizer/electron-process-manager) - should we remove this functionality all together? @kytwb @vantezzen

**Comment by vantezzen** [comment]
Yes, this feature was originally added to debug Ferdi's high resource usage but it looks like Station didn't maintain this package any longer since 2019.
The best option is to remove this feature until we find a better way of doing it.

**Comment by vraravam** [comment]
@vantezzen - shall I raise a PR to remove this then? Also - could you please approve a couple of the other PRs that are open? #1309 in particular is helpful for me while debugging.

**Comment by vraravam** [comment]
@kytwb  @vantezzen - i have raised the [above PR](#1313) - please approve/merge

**Comment by vraravam** [comment]
Closing since the PR to remove the Process Manager has been merged into `develop` branch
