### ISSUE TITLE
Ferdi package from AUR is not working

### ISSUE THREAD

**Issue by WitherCubes** [getferdi/ferdi#1298]
I don't know if this is the problem in my laptop or the AUR package, but all the time it shows error.

Here is the error message showing
[error.txt](https://github.com/getferdi/ferdi/files/6372483/error.txt)

This is the debug log. Please help.
[debug.log](https://github.com/getferdi/ferdi/files/6372489/debug.log)

**Comment by Zethson** [comment]
Another AUR user here: You should report this to the AUR package and not here.
