### ISSUE TITLE
Chrome Version 60+ needed

### ISSUE THREAD

**Issue by siltentassasin** [getferdi/ferdi#1299]
If I try to add a whatsapp web account, i get a message, that I need chrome version 60+

**Comment by Gavin152** [comment]
Yeah, same for me. I'm running Manjaro and installed via the AUR. 

In the What'sApp Service it's just saying "WhatsApp works with Google Chrome 60+" and there's an "Update Google Chrome" button beneath. [Here's what it looks like](https://imgur.com/a/sXHTmmm). 

Version: 5.5.0
Electron: 8.5.5
Node.js: v12.13.0

Happy to supply more info, if needed (logs etc)!

**Comment by vraravam** [comment]
Have you checked whether you have the [latest version of the WhatsApp recipe](https://github.com/getferdi/recipes/tree/master/recipes/whatsapp)? Most of the similar issues have been solved by updating either the `index.js` or the `webview.js` manually.

You can also try to use the nightly version (if you are bold enough to try this). YMMV

Please report back if this solved the issue.

If it does, I would request you to upvote the following [feature request](https://github.com/getferdi/ferdi/issues/1302)

**Comment by Gavin152** [comment]
Thanks, updating the ```index.js``` and ```webview.js``` in ```.config/Ferdi/recipes/whatsapp``` and then restarting the app (reloading the service wasn't enough, it seems) did the trick. 

Shame the recipes aren't "gitable". The feature request makes a lot of sense to me ... upvoted!

**Comment by vraravam** [comment]
right - and that's what i was trying to aim for as the feature request - to make it triggerable by the user, but the editing is no longer manual.
btw - Electron still supports only Chromium 59 - not yet v60

Could you also please close this issue?
