### ISSUE TITLE
Ability for the user to upgrade individual recipes

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1302]
**Is your feature request related to a problem? Please describe.**
I have noticed a lot of issues that are logged - where the fix ends up asking for the user to edit the recipe file(s). In some cases when I have faced similar issues, I ended up reviewing the latest code in the `recipes` repo in Github - and discovering that there was a fix contributed by someone, but the fix to the recipe has not made it to the general user's _installed location_ due to the time in between the main application (Ferdi) releases.

**Describe the solution you'd like**
A mechanism where the user has the choice (from within Ferdi) to get notified of a newer version of the recipes that they are using, and then getting upgraded. I guess this already happens to some extent (?) when a new version of Ferdi is installed. If so, what I am suggesting is for this recipe-upgrade-process to be independent of the application-upgrade-process - and be triggerable by the end-user on a per-recipe basis.

**Describe alternatives you've considered**
Manual editing of the recipe files is very techie-oriented and even then it becomes a hit-or-miss scenario.

**Comment by vraravam** [comment]
One more suggestion (if this feature request is implemented): Since the user can independently upgrade recipes, it might be ok to not package the recipes into the deployable app itself - thus making its size smaller. At the time of a fresh installation, as the user adds services, at that time, a network call can be made to fetch the relevant compressed files and expand into the target location on the client machine/laptop.
For pre-existing profiles, an option could be given to check the version of the recipe with the latest on the GH server - and the existing code for each recipe can be upgraded in place by the same above mechanism. This can be done on either app-startup or once per day or some other cadence.

**Comment by manavortex** [comment]
Yes, please - with Facebook constantly changing their web API around, I find myself touching those rather more often than Ferdi's usual update cycle.

**Comment by vraravam** [comment]
This seems like a duplicate of #819 - we can continue any conversation there.
