### ISSUE TITLE
Images not being rendered in Google Chat

### ISSUE THREAD

**Issue by sidcool1234** [getferdi/ferdi#1310]
**Bug description:**

Ferdi is not rendering images that are uploaded to Google chat.  Instead it shows the red placeholder.  

**Steps to reproduce:**

1.  Open a room or chat
2. Upload an inline image (not an attachment)
3. Upload happens successful, but the image is not rendered

**Expected behavior**

1.  After successful upload, the image should be rendered inline

**Screenshots**

<img width="558" alt="Screenshot 2021-04-28 at 3 07 17 PM" src="https://user-images.githubusercontent.com/6894/116382337-6d91c400-a833-11eb-9a87-3a8ac3b029c1.png">

**Environment:**

- Operating System: macOS Catalina
- Ferdi Version: 5.5.0 (The issue existed before updating)
- Server: Using without account

- Debug information:

Debug information seems to have private info

**Comment by vraravam** [comment]
Duplcate of #1283
