### ISSUE TITLE
Fuzzy search for Quick switch feature

### ISSUE THREAD

**Issue by kishaningithub** [getferdi/ferdi#1311]
**Is your feature request related to a problem? Please describe.**
The "Quick Switch" feature is very good, it would be great if the search is fuzzy 

**Describe the solution you'd like**
Example:
Say if the following are my services
- Gmail
- Slack
- Whatsapp
- Work - Gmail
- OSS Slack
If i type "mail" both "Gmail" and "Work - Gmail" should come as a a result

What is currently happening is i don't see anything, 

**Describe alternatives you've considered**
I am thinking it is fine if it is not completely fuzzy
instead of the "startsWith" if we change it to "contains" it would be great :-)

**Comment by vraravam** [comment]
@kishaningithub - I just committed a PR for this: #1326 - if this is what you wanted, please upvote the PR
<img width="584" alt="Screen Shot 2021-05-01 at 8 45 28 AM" src="https://user-images.githubusercontent.com/69629/116769420-97c4cb00-aa59-11eb-99b8-cf92c91cea57.png">

**Comment by vraravam** [comment]
Please note that in javascript, if you want to match with special characters, you will need to [escape](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#escaping) the string. So, to match `gmail` and NOT match `gitter`, the search string needs to be `g\*l`

**Comment by vraravam** [comment]
@kishaningithub - since this is now merged, could you please verify and close the issue?
