### ISSUE TITLE
Maintain service sort order

### ISSUE THREAD

**Issue by ICDeadPpl** [getferdi/ferdi#132]
The icons in the left bar won't keep their sort order after restarting Ferdi.
I usually put the most used services at the top, by dragging the icons in the order I want them.
The next time I start Ferdi, the icons have reordered themselves in no particular order.
They are not sorted by name, neither by date/time added.
It would be nice if Ferdi saved the sort order of the services.

**Comment by vantezzen** [comment]
There was a problem with ferdi-server that threw an error when trying to reorder services.
I just fixed this problem, reordering should work again.

**Comment by VOOM108** [comment]
I have a similar problem in 5.4.0 and 5.4.1b3 - for some workspaces ordering works, for others it does not. In the later case the icon I am currently dragging jumps back to where I grabbed it, while other icons reorder without any particular system.

**Comment by vantezzen** [comment]
@VOOM108 what server are you using?

**Comment by VOOM108** [comment]
Standard ferdi server as it came with the app: https://api.getferdi.com

**Comment by VOOM108** [comment]
Actually I am using no server at all, see other issue of mine. I mixed up the threads.... ;)
