### ISSUE TITLE
Unwanted Connection to api.getferdi.com

### ISSUE THREAD

**Issue by Mavpt** [getferdi/ferdi#1323]
**Bug description:**
When using Ferdi without an account it still establishes a connection to api.getferdi.com.
I understand this might be an intended feature, in which case would it be possible to explain the purpose of the connection?

**Steps to reproduce:**
1. Choose to 'Use Ferdi without an Account'
2. Open a terminal
3. Run `ping api.getferdi.com`
3. Run `ss -anputw | grep ferdi` or `netstat -anputw | grep ferdi`
4. Verify Ferdi establishes a tcp connection with the same IP returned by the ping

**Expected behavior**
Ferdi not to connect to any servers when being used without an account.
**Screenshots**
Don't believe it to be applicable.

**Environment:**
- Operating System: Arch Linux
- Ferdi Version: 5.5.0 (x64)
- Server: Using without an account

- Debug information:
Don't believe it to be applicable.

**Comment by kris7t** [comment]
Ferdi will attempt to check for updates and download the latest versions of recipes even if you're using a local server. (Technically, you can't use Ferdi without a server, but if you chose not to use an online server, it runs a server locally without authentication, that will store your data in `$XDG_CONFIG_HOME/Ferdi/server.sqlite`). In particular, the local server acts as a proxy to download recipe updates.

You can disable checking for updates in the settings, but I don't believe there's a way to disable recipe proxying in the UI. You can set the environmental variable `CONNECT_WITH_FRANZ=false` to disable recipe proxying (but then you'll be limited to the recipes already present locally).

**Comment by Mavpt** [comment]
Thank you for the clarification.

If I can make a suggestion, adding a way to disable recipe proxying in the UI would be useful since it'd make what's happening behind the scenes clearer.
I understand however that this is not a top priority and since the original question has been answered, I'll go ahead and mark the issue as closed.
