### ISSUE TITLE
Set a Notification icon from Service icon 

### ISSUE THREAD

**Issue by rsanjuan87** [getferdi/ferdi#1325]
When it shows a notification its shows a Ferdi icon.
I think it's better if the notification shows a Sercvice icon instead

**Comment by vraravam** [comment]
@rsanjuan87 - could you please specify which version of Ferdi you are running? And which service is it you are referring to?

For eg, I'm running the latest version of ferdi (built from source), and I see the following: 
A notification from the google calendar service from within Ferdi:
<img width="337" alt="Screen Shot 2021-05-14 at 2 47 29 PM" src="https://user-images.githubusercontent.com/69629/118251231-edbb5900-b4c4-11eb-8faa-bea429b38d08.png">

A notification from the google chat service from within Ferdi:
<img width="341" alt="Screen Shot 2021-05-14 at 2 47 38 PM" src="https://user-images.githubusercontent.com/69629/118251234-eeec8600-b4c4-11eb-9190-13846468b86a.png">

**Comment by mhatvan** [comment]
This is highly related to the OS and not related to Ferdi, on Ubuntu for example I see the message content and user image when receiving a message on WhatsApp while macOS seems to behave completely different.
