### ISSUE TITLE
Pushbullet has "Local Storage Unaccessable" or "Cookies Disabled" error on login

### ISSUE THREAD

**Issue by jeremymeyers** [getferdi/ferdi#1331]
**Bug description:**
When logging in to Pushbullet for the first time (via google, if that matters), it responds with a "Local Storage seems to be unaccessible to us" and login fails.  As a note, the Ferdi recipe for PB and the Franz recipe are exactly the same, so it is perhaps something with the new Ferdi code.

**Screenshots**
![Screenshot 2021-05-01 19 14 39](https://user-images.githubusercontent.com/3514095/116797247-b6ef4700-aab1-11eb-9daa-00bffa1b806d.png)

**Environment:**

- Operating System: Win10
- Ferdi Version: 5.5
- Server: Ferdi

**Debug information:**
{"host":{"platform":"win32","release":"10.0.19041","screens":[{"id":2528732444,"bounds":{"x":0,"y":0,"width":1920,"height":1200},"workArea":{"x":0,"y":0,"width":1920,"height":1200},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6600, 0.3320],  [0.3020, 0.6130],  [0.1500, 0.0630]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1200},"workAreaSize":{"width":1920,"height":1200},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"discord","version":"1.1.3"},{"id":"github","version":"2.0.0"},{"id":"instagram","version":"2.0.0"},{"id":"messenger","version":"1.1.0"},{"id":"pushbullet","version":"1.0.0"},{"id":"slack","version":"1.0.15"},{"id":"telegram","version":"3.0.0"},{"id":"todoist","version":"1.1.0"},{"id":"tweetdeck","version":"1.0.2"},{"id":"twitter","version":"1.1.1"},{}],"devRecipes":[],"services":[{"id":"7a8232fe-68ba-42b3-9c11-bad7d6e6a5e0","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"d4b54314-5fa2-486e-87d4-e9d1fedacc3b","recipe":"instagram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"c4fc6b9e-f858-466f-b0c8-602acdb74b51","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"8799fc98-8fef-4d8f-87de-bdd9d2b624f1","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"e78d316c-d7d6-4a64-8cd5-ef78c0571f6c","recipe":"pushbullet","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"e1f95aa3-6dc5-45e3-83e2-16293d444fd1","recipe":"todoist","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"baa12613-253d-4cd1-8cf9-5c316f1f7d41","recipe":"tweetdeck","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"bf125ed5-7465-47fe-bc3d-2b21f5b093b6","recipe":"github","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"a0e0c050-0f4b-4281-add4-0aaadc7d7a49","recipe":"twitter","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"default"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state."]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar.unpacked\\recipes\\discord.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar.unpacked\\recipes\\telegram.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar.unpacked\\recipes\\pushbullet.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar.unpacked\\recipes\\todoist.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar.unpacked\\recipes\\tweetdeck.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar.unpacked\\recipes\\github.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar.unpacked\\recipes\\slack.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","C:\\Users\\softl\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar.unpacked\\recipes\\twitter.tar.gz"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in WithTheme(Jss(_class2)) (created by inject-WithTheme(Jss(_class2))-with-stores)\n    in inject-WithTheme(Jss(_class2))-with-stores (created by _class2)\n    in _class2 (created by WithTheme(_class2))\n    in WithTheme(_class2) (created by Jss(WithTheme(_class2)))\n    in Jss(WithTheme(_class2)) (created by _class2)"]},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in WithTheme(_class2) (created by Jss(WithTheme(_class2)))\n    in Jss(WithTheme(_class2)) (created by _class2)"]},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in WithTheme(ButtonComponent) (created by Jss(WithTheme(ButtonComponent)))\n    in Jss(WithTheme(ButtonComponent)) (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by inject-Jss(_class2)-with-stores)\n    in inject-Jss(_class2)-with-stores (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)"]}],"workspaces":[],"windowSettings":{"width":800,"height":600,"x":614,"y":153,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1920,"height":1200}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":false,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by jeremymeyers** [comment]
Looks like a few other electron apps have had trouble with this.  I believe that PB is trying to set a cookie which may not be working possibly because of chrome site isolation:

Was resolved in RAMBox: https://github.com/ramboxapp/community-edition/issues/185 with a redirect hack: https://github.com/TheGoddessInari/hamsket/commit/ffd27e9b3aae45d8a3ba8d72b33022e740cbab3f

The reason i think it might have to do with site isolation is due to a PB Bug report here: https://www.reddit.com/r/PushBullet/comments/9y5g0t/cant_login_in_firefox_addon/

**Comment by vraravam** [comment]
@jeremymeyers - could you please try with the latest version of the recipe?
The steps to perform are detailed [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help).

**Comment by jeremymeyers** [comment]
still not working :(  (i'm using the release version of ferdi rather than the nightly if that makes a difference)

**Comment by vraravam** [comment]
@jeremymeyers - could you please try with the nightly? The framework around the recipes might have changed between the 5.5 and the nightlies. So, without being on the same versions, (and also not being on windows), I can't help a lot. Please try the nightlies, and then upgrade the recipes based on the previous comment.

**Comment by jeremymeyers** [comment]
Still not working, using the latest nightly (from february)

**Comment by vraravam** [comment]
thanks @jeremymeyers - and AFTER upgrading, did you follow the manual steps for replacing the recipes in your profile folder?

**Comment by jeremymeyers** [comment]
yup, the version in C:\Users\[username]\AppData\Roaming\Ferdi\recipes\pushbullet is 1.0.1 (which i think is the one you just uploaded?)

**Comment by sverhagen** [comment]
FWIW, same behavior on Ubuntu 21.04.

**Comment by vraravam** [comment]
@sverhagen - which version of Ferdi are you using? Can you please try with the latest beta that was uploaded a few hours ago and report the behavior please?

**Comment by sverhagen** [comment]
I did the following:
1. Download `ferdi_5.6.0-beta.6_amd64.deb`
2. `sudo dpkg -i ~/Downloads/ferdi_5.6.0-beta.6_amd64.deb`
3. `rm -rf ~/.config/Ferdi/recipes/pushbullet`
4. Start Ferdi
5. Tried Login to Pushbullet: **same results: "Local Storage seems to be unaccessible to us."**
6. `cat ~/.config/Ferdi/recipes/pushbullet/package.json`:

        {
          "id": "pushbullet",
          "name": "Pushbullet",
          "version": "1.0.1",
          "description": "Pushbullet",
          "main": "index.js",
          "author": "Diego bersanetti <diego.bersanetti@gmail.com>",
          "license": "MIT",
          "config": {
            "serviceURL": "https://www.pushbullet.com/"
          }
        }

**Comment by mylemans** [comment]
Same issue here (I tried the beta)

**Comment by jeremymeyers** [comment]
@vraravam any possibility of reworking this?

**Comment by vraravam** [comment]
Related to #1579 

@jeremymeyers - no, i am starting to look at this now. Grepping the code for some keywords that might provide me a clue as to where to look.

**Comment by jeremymeyers** [comment]
@vraravam cool, happy to help

**Comment by vraravam** [comment]
@kris7t - any ideas where I can start looking for this?

**Comment by jeremymeyers** [comment]
(note that 0.7 beta did not fix this though there is some mention in release notes)

**Comment by vraravam** [comment]
Sorry about that @jeremymeyers - I will correct the release notes right away. This ticket is still open.

**Comment by jeremymeyers** [comment]
Hoping to be able to get this addressed so as to not have to have a whole other client open

**Comment by sverhagen** [comment]
5.6.4, seems resolved now.

**Comment by jeremymeyers** [comment]
@sverhagen Confirmed!  To those for whom it may still be an issue, make sure to refresh (control+R) after re-logging in.
