### ISSUE TITLE
Hangouts Chat Dark Mode Not Working

### ISSUE THREAD

**Issue by 0-SamboNZ-0** [getferdi/ferdi#1353]
I'm a Ferdi noob, so maybe I'm doing something wrong, but I can't get dark mode for Hangouts Chat working.

Universal Dark Mode is enabled (and working fine in other services), and 'Dark Mode' is enabled for Hangouts Chat, but there is no change to the colors in Hangouts Chat.

Ferdi v5.5 (x64)

**Comment by jaddel** [comment]
I'm running into the same issue, is there an update on this?

**Comment by gdevenyi** [comment]
Still a thing on 5.6beta7

**Comment by vraravam** [comment]
Please see the discussion/explanation here: https://github.com/getferdi/ferdi/issues/1604#issuecomment-876885287 - untill google fixes chat to support dark mode natively, we will not be able to give a completely working experience.
