### ISSUE TITLE
Zulip recipe needs update

### ISSUE THREAD

**Issue by timabbott** [getferdi/ferdi#1362]
The Zulip recipe for Franz/Ferdi has an out-of-date selector and thus does not show unread counts correctly and continuously throws exceptions.

The latest Zulip recipe for Franz/Ferdi is this: https://github.com/adambirds/recipe-zulip.

**Comment by vraravam** [comment]
@timabbott - Could you please raise a PR against the getferdi/recipes repo **with the specific changes** that you think are valid/necessary? If I compare the commits in our recipes repo with what you have pointed to - the commits in the former are more recent.
