### ISSUE TITLE
Ferdi force to use English

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#138]
**Describe the bug**
From a few commit dev I tried now I can't change language.

**To Reproduce**

1. Go to File
2. Click on Settings
3. Scroll down to Language
4. Change Language
5. See error (not refreshing and not showing in another language)
6. Reload or restart Ferdi
7. Turn back to english in a second

**Expected behavior**
Before the app was automaticly refresh when choosing a new language but now Ferdi do nothing and when restarting the app I can see (i.e. French) for 1 or 2 second and just after that everything turn into english and the settings too.

**Desktop (please complete the following information):**

- OS: Windows 7, 10
- Version: 5.4.0-beta.2 (Official release)

**More info**
This was when using no account and with account

**Comment by vantezzen** [comment]
The user settings feature wasn't implemented into ferdi-server yet, this resulted in the language not updating. I now implemented this feature into ferdi-server and the internal server and switching languages should now work correctly.
