### ISSUE TITLE
RingCentral recipe no longer works

### ISSUE THREAD

**Issue by michaeldrouin** [getferdi/ferdi#1388]
**Bug description:**

The RingCentral recipe no longer works, as the original site has been depricated. Now when you try to open it, it says "RingCentral Classic is no longer available." They do have a new version of the website that can be used, so the recipe probably just needs to be changed for that instead.

**Screenshots**

![rc](https://user-images.githubusercontent.com/7315656/117711906-85990a00-b188-11eb-9a2f-42d2d098d3b8.png)

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.6.0-beta.5 (x64)
- Server: Ferdi

**Comment by vraravam** [comment]
Can you please provide the new website url? I do not use ringcentral - but, will need that info to be able to try and fix the issue.

btw - I looked through the codebase, and couldn't find any word referring to "ringcentral" - are you sure that this is in Ferdi and not some other similar app? Also, are you sure you haven't set this up as a custom service?

**Comment by michaeldrouin** [comment]
> btw - I looked through the codebase, and couldn't find any word referring to "ringcentral" - are you sure that this is in Ferdi and not some other similar app? Also, are you sure you haven't set this up as a custom service?

yeaaaah, i'm an idiot. closing the issue. sorry about that lol

**Comment by deadmeu** [comment]
FYI @michaeldrouin a RingCentral recipe is now shipped from v5.6.4.
