### ISSUE TITLE
Settings: "You are using the official Ferdi Server for Ferdi" 🙄

### ISSUE THREAD

**Issue by bittner** [getferdi/ferdi#139]
**Describe the bug**
Ferdi settings explain server use is a weird way:

> You are using the official Ferdi Server for Ferdi.

This text is not in the repository, so "Franz" is probably replaced in [EditSettingsForm.json](https://github.com/getferdi/ferdi/blob/master/src/i18n/messages/src/components/settings/settings/EditSettingsForm.json#L56) by "Ferdi" at packaging time. (I'm guessing!)

Also, I'm not sure whether the hint "consider paying for a Ferdi account" is actually true or a mistake.

**To Reproduce**

1. Open Ferdi
2. Click on the gear icon on the lower left to open the settings dialog

**Expected behavior**

This should be worded properly. Maybe the entire paragraph can even be removed. Not sure about the new, local server feature, though. (It's unclear how to activate this, so maybe the explanation should go here instead of the original text.)

**Screenshots**

![Ferdi-settings-server](https://user-images.githubusercontent.com/665072/67162524-1620b700-f365-11e9-955f-9ae57ea440ef.png)

**Desktop (please complete the following information):**

- OS: Ubuntu GNU/Linux Bionic 18.04.3 LTS
- Browser: Chromium, Firefox (does that matter?)
- Version: Ferdi 5.4.0-beta.2

**Comment by Makazzz** [comment]
I think this [file](https://github.com/getferdi/ferdi/blob/develop/src/i18n/apply-branding.js) has to do somthing with this.

**Comment by vantezzen** [comment]
Yes, looks like the apply-branding script has overwritten the string there. Just pushed 048d968 which corrects the string and script.

**Comment by bittner** [comment]
Though it's weird: After logging out to use "no server" the Settings look totally different, and the text from above is not there. I'm confused. :confused:

**Comment by vantezzen** [comment]
The text is only shown when you are using the Franz API (API.franzinfra.com). As you are using the internal server, the text won't get shown.
