### ISSUE TITLE
Zoom doesn't work

### ISSUE THREAD

**Issue by markwalkom** [getferdi/ferdi#143]
**Describe the bug**
Zoom doesn't work

**To Reproduce**

1. In the main app
2. Use command and +/-
3. Or use the View > Zoom in/out
4. Nothing happens

**Expected behavior**
Text size should alter

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 10.14.6 (18G103)
- Browser N/A
- Version 5.4.0-beta.2 (5.4.0-beta.2.690)

**Smartphone (please complete the following information):**

**Additional context**

Maybe related https://github.com/meetfranz/franz/issues/1289

**Comment by vantezzen** [comment]
Could reproduce bug and found issue. I'll implement it upstream.

**Comment by falkenhawk** [comment]
is there any workaround possible in the meantime? e.g. manually setting zoom level for a service in a config file?

**Comment by kytwb** [comment]
@falkenhawk I have cherry-picked @vantezzen commit and pushed it to our develop branch via https://github.com/getferdi/ferdi/commit/a28c993d2045c3bef61a4435737e0c810d380282. It will ship in our next (beta) release.

**Comment by kytwb** [comment]
Available in [v5.4.1-beta.1](https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.1).

**Comment by markwalkom** [comment]
I can zoom out, but I can't zoom in beyond the original 100%. It's not a
big problem for me.

**Comment by kytwb** [comment]
@markwalkom I managed to do both:

<img width="1436" alt="Screen Shot 2019-11-28 at 12 05 10 PM" src="https://user-images.githubusercontent.com/412895/69778599-7d891c80-11d7-11ea-8180-f5a2d3626829.png">
<img width="1436" alt="Screen Shot 2019-11-28 at 12 05 27 PM" src="https://user-images.githubusercontent.com/412895/69778600-7e21b300-11d7-11ea-8663-c988c1dbbd64.png">

Can you give me more details on what prevents you to zoom in beyond 100%?  
Is the menu entry `View > Zoom in` grayed out?

**Comment by markwalkom** [comment]
Sorry, I should have mentioned this is when I use the keyboard shortcuts,
so command and +

**Comment by kytwb** [comment]
You need to press the shift key at the same time to trigger CMD-+, otherwise you are most likely triggering CMD+= (depending on your keyboard layout).

**Comment by markwalkom** [comment]
Doh!
