### ISSUE TITLE
Propietary license: Is the downloadable linux (.deb) version corresponding with this code? 

### ISSUE THREAD

**Issue by digitalTranshumant** [getferdi/ferdi#1435]
Hi, 

Thanks for this amazing project. 

I'm confused with the license used here. I've downloaded the last .deb file (ferdi_5.5.0_amd64.deb), and when I try to install it, the Ubuntu GUI installer says "License: Proprietary".

I would like to avoid building the full repo, but I don't get why the license of the compiled file is proprietary.   Could you clarify this please?

Thanks

**Comment by yann1cks** [comment]
Ferdi is Open Source, if you download and unpack the .deb file, you can see that it is licensed as Apache-2.0.

I have the problem that Ubuntu does not recognise the licences with other software as well. Seems to be a bug: https://bugs.launchpad.net/snap-store-desktop/+bug/1878924

So no need to build the full repo.

**Comment by mhatvan** [comment]
Closing since seems to be bug of snap store. License is specified as Apache-2.0 in package.json
