### ISSUE TITLE
Can you add google translate? 

### ISSUE THREAD

**Issue by thearkadia** [getferdi/ferdi#144]
**Is your feature request related to a problem? Please describe.**
Discord web app doesn't allow for google translate to work like telegram, slack and many others do.
**Describe the solution you'd like**
I would like to be able to translate conversations instantly like how it works if I go to telegram or slack web app in chrome and right click to translate the page.

**Comment by vantezzen** [comment]
I don't think we can implement this into Ferdi: 
The Google Translate API is [commercial](https://cloud.google.com/translate/pricing) but Ferdi tries to stay free for everybody.

If anyone wants to implement this and finds a translation API that we can use for free, PRs are welcome.

**Comment by kytwb** [comment]
This should also be do-able with https://github.com/getferdi/ferdi/issues/113 and the [Google Translate extension](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb?hl=en).
