### ISSUE TITLE
Signing up for a new service (ie adding into the sidebar), causes the new service to always get added at index 2

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1445]
**Bug description:**
Adding a new service (beyond the 2nd service) keeps adding the service only at position number 2.

**Steps to reproduce:**
1. Open Ferdi
2. Make sure that you already have 3 configured services
3. Click `Cmd+N`
4. In the new 'Services' dialog, add any random service
5. Upon clicking 'save' button, the new service is always added as the 3rd service. 

**Expected behavior**
The new service should always be added to the end of the existing list of services.

**Screenshots**

**Environment:**

- Operating System: macOS Big Sur
- Ferdi Version: Latest GIT SHA: `cda77aa3` from the `develop` branch
- Server: Ferdi

- Debug information:

**Comment by kris7t** [comment]
I can reproduce this in production mode. However, it doesn't happen for in debug mode, which is especially infuriating and makes debugging it pretty difficult.
