### ISSUE TITLE
Review 1.1.1.1 requests hack

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#146]
There has been an effort to remove errors/warnings as they appear in the console.

<img width="888" alt="Screen Shot 2019-10-21 at 6 32 29 PM" src="https://user-images.githubusercontent.com/412895/67201895-8563dd00-f431-11e9-916f-007b6d1e98d3.png">

The last chunk is related to the hack implemented here:

https://github.com/getferdi/ferdi/blob/9724d4a3ad849cb688545946edb2e878e4a4efc4/src/api/apiBase.js#L19

I think things can be refactored so we don't have to use this kind of hack.  
WDYT?

**Comment by vantezzen** [comment]
Yes, the apiBase hack is not the prettiest - do you have any ideas on how to refactor it?

One option I thought of is to return a special config key (similar to how `config.LOCAL_SERVER` is used) and implement a check for this into `src/api/server/ServerApi.js` that will wait until the value is loaded (as the functions are async anyway).

**Comment by vantezzen** [comment]
I now added the possible fix I suggested via a0ac009c. It looks to me that the errors are gone and everything works as intended but we'll have to test that.
