### ISSUE TITLE
IS VERY  IMPORTANT HAVE DOCKER HUB IN THE SERVICES

### ISSUE THREAD

**Issue by DevParraneitor** [getferdi/ferdi#1462]
**Bug description:**

**Steps to reproduce:**

**Expected behavior**

**Screenshots**

**Environment:**

- Operating System: 
- Ferdi Version: 
- Server: 

- Debug information:

**Comment by vantezzen** [comment]
I think you want Docker Hub added to the services? Sorry, your issue isn't really very informational about that.

Please read our disclaimer and create service requests in the https://github.com/getferdi/recipes/issues repository and using the template.
