### ISSUE TITLE
Ferdi Debian package uses incorrect path in postinst

### ISSUE THREAD

**Issue by norbusan** [getferdi/ferdi#1469]
The Debian package downloaded from the current release v5.6.0-beta.6 uses `/opt/ferdi` in two places, but the actual files are installed into `/opt/Ferdi`. That means that:
- the link `/usr/bin/ferdi` is dead
- `/opt/Ferdi/chrome-sandbox` is not properly chown-ed

Best

**Comment by vraravam** [comment]
@kris7t - would you be able to take this up asap?

**Comment by k3tan172** [comment]
Just another note on the debian package - every time I log out of my computer and log back in again, there are two ferdi icons in the taskbar. One is irresponsive.
![image](https://user-images.githubusercontent.com/44537874/120169581-736c3200-c243-11eb-9fe6-019bb7d0e2bd.png)

**Comment by kris7t** [comment]
@vraravam @norbusan I'll try to look into this. I might have to change the application name from `Ferdi` to `ferdi`, though.

@k3tan172 Yes, this is a known issue. Unfortunately, fixing it will require a substantial rewrite of our tray icon functionality for Linux. (We use the default Chromium tray icon support, but that's kinda broken and the icon just disappears on screen lock. We fixed it, but now the icon duplicates, which is still more usable compared to just disappearing, but obviously not ideal.)

**Comment by vraravam** [comment]
I was doing a small bit of browsing between work meetings, and came to [this page](https://github.com/electron-userland/electron-builder/pull/2392/commits/8258d33ad913a4704d7ee8fa579255af5bad983f) - it might be helpful in running the `chown`command. Also, [this](https://www.electron.build/configuration/linux#linuxtargetspecificoptions-apk-freebsd-pacman-p5p-and-rpm-options) might be helpful.

For the application name, maybe you can take a look at the `productName` in the `electron-builder.yml` file? [relevant read](https://www.electron.build/configuration/configuration)

**Comment by vraravam** [comment]
@k3tan172 - thanks for testing/logging the bug, but, once the first issue is fixed, we will want to close the issue. If you would like your bug fixed/tracked, I would suggest that you create a new bug card with all relevant details. Thanks in advance.

**Comment by kris7t** [comment]
@vraravam @k3tan172 We're already tracking this at e.g.  #1189

**Comment by kris7t** [comment]
> For the application name, maybe you can take a look at the productName in the electron-builder.yml file?

The problem seems to be that we have `linux.executableName: ferdi` in `electron-builder.yaml`, and I think there's some inconsistency about which directory names come from `linux.executableName` and which directory names come from `"productName"` in `package.json`. Now I'm investigating just setting `linux.executableName: Ferdi` to see what changes in the resulting package.
