### ISSUE TITLE
Links don't open on mouse left click

### ISSUE THREAD

**Issue by dehyde** [getferdi/ferdi#1470]
Links don't open on a regular left mouse click.
Only open on right click -> open link.

**Steps to reproduce:**

1. Go to any service
2. Click on a link

**Expected behavior**

Click opens in default browser

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.60

**Comment by johanvanhelden** [comment]
Same here. `Ctrl`-click does seem to work.

**Comment by vraravam** [comment]
This is now fixed by https://github.com/getferdi/ferdi/pull/1474 - which has just been merged! Please pull and rebuild from source, or wait for tonight's nightly build.
