### ISSUE TITLE
Are there plans to bring Ferdi to FreeBSD?

### ISSUE THREAD

**Issue by KodyVB** [getferdi/ferdi#1473]
There are currently download options for Arch, RPM, Ubuntu, Linux AppImages, Mac, and Windows, but is there any plans to bring it to FreeBSD?

**Comment by kris7t** [comment]
We currently don't have CI set up for FreeBSD builds, but it theoretically seems possible. You can try building and/or running Ferdi from the source code to see whether it works.

**Comment by vraravam** [comment]
According to [this](https://www.electron.build/configuration/linux) - we can include `freebsd` and electron-builder will output an artifact for `freebsd`. @KodyVB - please try and raise a PR?
