### ISSUE TITLE
Nightly updates not working

### ISSUE THREAD

**Issue by alopix** [getferdi/ferdi#1476]
**Bug description:**
When checking for updates with nightlies turned on, no update notification is shown, even though a new nightly is available on GitHub.

**Steps to reproduce:**
1. Install nightly, e.g. 5.6.0-nightly.48
2. Enable "include nightlies" in settings an accept
3. Click check for updates
4. No update, even though 5.6.0-nightly.53 is available

**Expected behavior**
5.6.0-nightly.53 shows as update

**Screenshots**

**Environment:**

- Operating System: macOS Big Sur 11.3.1
- Ferdi Version: 5.6.0-nightly.48
- Server: Ferdi with account

- Debug information:

**Comment by vraravam** [comment]
This has now been fixed in #1479 - but, the _first download_ will still have to be downloaded and installed _manually_ and the auto-updater should get fixed after that point onwards. Please wait for the next nightly release v56) over [here](https://github.com/getferdi/nightlies/releases)
