### ISSUE TITLE
Error in Appveyor and Travis progress build

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#148]
**Describe the bug**
It seem that from some last commit the Appveyor progress build is now failling to remote or just before finishing the script.

I think this commit 405100200dfec9d55f985ffae4bc70f10df44846 did something and maybe another with submodule too.

<details>
<summary>Error almost in the end</summary>
` • packaging       platform=win32 arch=ia32 electron=6.0.10 appOutDir=out\win-ia32-unpacked
  • building        target=nsis file=out\Ferdi Setup 5.4.0-beta.2.exe archs=x64, ia32 oneClick=true perMachine=false
  • building        target=portable file=out\Ferdi 5.4.0-beta.2.exe archs=x64, ia32
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.3.2/nsis-3.0.3.2.7z size=1.4 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.3.2/nsis-3.0.3.2.7z duration=768ms
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z size=731 kB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z duration=710ms
  • building block map  blockMapFile=out\Ferdi Setup 5.4.0-beta.2.exe.blockmap
  ⨯ [object Object]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ferdi@5.4.0-beta.2 build: `npx electron-builder --publish onTag`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ferdi@5.4.0-beta.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2019-10-21T10_00_23_508Z-debug.log
Command exited with code 1`
</details>

<details>
<summary>Error when doing remote the server and service</summary>
`Build started
git clone -q --branch=develop https://github.com/getferdi/ferdi.git C:\projects\ferdi
git checkout -qf 405100200dfec9d55f985ffae4bc70f10df44846
APPVEYOR_CACHE_SKIP_RESTORE is set to 'true' - skipping cache restore
Running Install scripts
git submodule update --init --recursive
Submodule 'recipes' (git@github.com:getferdi/recipes.git) registered for path 'recipes'
Submodule 'src/server' (git@github.com:getferdi/internal-server.git) registered for path 'src/server'
Cloning into 'C:/projects/ferdi/recipes'...
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:getferdi/recipes.git' into submodule path 'C:/projects/ferdi/recipes' failed
Failed to clone 'recipes'. Retry scheduled
Cloning into 'C:/projects/ferdi/src/server'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:getferdi/internal-server.git' into submodule path 'C:/projects/ferdi/src/server' failed
Failed to clone 'src/server'. Retry scheduled
Cloning into 'C:/projects/ferdi/recipes'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:getferdi/recipes.git' into submodule path 'C:/projects/ferdi/recipes' failed
Failed to clone 'recipes' a second time, aborting
Command exited with code 1`
</details>

**Comment by vantezzen** [comment]
Fixed with 07a5228. Have now moved back to HTTPS for submodules.
