### ISSUE TITLE
Left clicking on a link does nothing on Telegram React (newest recipe)

### ISSUE THREAD

**Issue by notNSANE** [getferdi/ferdi#1484]
**Bug description:**
Left clicking on a link does nothing on Telegram React (newest recipe)

**Steps to reproduce:**

1. Add Telegram React
2. Get a URL
3. Left Click it

**Expected behavior**
Link opens in default browser like it happens on all other services.

**Environment:**

- Operating System: Windows 10 x64
- Ferdi Version: 5.6.0-beta.6
- Server: Ferdi

**Comment by notNSANE** [comment]
PS: I don't know what happened but I had to remove thousands of \\\\\\\\\\\\\\\\\\\\\\ characters from the debug code.

**Comment by vraravam** [comment]
@notNSANE - could you please try with the latest nightly? This has been fixed just 24 hrs ago.
https://github.com/getferdi/nightlies/releases/tag/v5.6.0-nightly.56

**Comment by notNSANE** [comment]
Hm, any of those are portable? I only use portable I'm afraid. @vraravam

**Comment by notNSANE** [comment]
OK, I figured it out and it indeed seems to be working correctly now! Thanks!

**Comment by notNSANE** [comment]
sadly this nightly breaks steam #1489 ... seems you guys can't get it right. Rolling back to stable beta.
