### ISSUE TITLE
Boomerang gmail integration?

### ISSUE THREAD

**Issue by jason-mehmel** [getferdi/ferdi#1485]
**Is your feature request related to a problem? Please describe.**
I've found rapid logging of meetings and deadlines in my email to be tricky, and the Boomerang gmail integration takes care of that. Boomerang will detect dates in emails and offer to make events out of them, and the integration will also show if the proposed dates conflict with other bookings.

**Describe the solution you'd like**
Integrating Boomerang into the Ferdi/Gmail instance, which then allows for rapid logging of calendar dates within emails.

**Additional context**
I'm not sure if this is already known, but I believe Boomerang is added as an extension via Chrome and Firefox.

**Comment by kris7t** [comment]
Development for extension support is ongoing in #822, but it is a quite complex task, so it might take some time to be ready.
