### ISSUE TITLE
Service preloader not needed since most services already have a preloader, and it also doesn't respect Dark Mode

### ISSUE THREAD

**Issue by notNSANE** [getferdi/ferdi#1488]
**Bug description:** Not sure why this was implemented, but all services nowadays have a preloader. Why implement a preloader _preloader_? Also, it doesn't respect dark mode and just a big white screen before the services load.

**Steps to reproduce:**

1. Load a service

**Expected behavior**

No preloader preloader.

**Screenshots**

**Environment:**

- Operating System: Windows 10 
- Ferdi Version: 5.6.0 beta 6
- Server: Ferdi

- Debug information:

**Comment by kris7t** [comment]
What do you mean by preloader preloader?

The white screen that is shown when a service is initializing is Chromium (the browser powering Ferdi) loading the service website -- just like when your browser is loading a site when you have entered an URL, but it haven't downloaded the page yet.

What would be interesting is to make the webviews initialize with a dark background when dark mode is activated (but I don't know whether that's possible at all with current Electron API). But even then, a blank page would be visible for a brief moment (until the browser downloads the service website).

**Comment by notNSANE** [comment]
wait, so that's chromium? huh. That wasn't there on beta 5! That's why I was so confused about it.

**Comment by kris7t** [comment]
Beta 5 was on Electron 9 on Chromium 83, beta 6 is on Electron 13 with Chromium 91. The default background for webviews probably changed from transparent to white in the meantime. But I'll look into whether it can be styled.

**Comment by vraravam** [comment]
Closing since this is not something we can control and the 👍 from @notNSANE leads me to believe that they are satisfied with the above explanation.
