### ISSUE TITLE
How to turn off copy (command-c) notifications: "Data copied into Clipboard"?

### ISSUE THREAD

**Issue by ylluminate** [getferdi/ferdi#1491]
Something that has just now become visible for my Ferdi experience is the system notification on macOS when copying URLs. 
I see a `Data copied into Clipboard` notification each time.  How can I turn this specific notification off while keeping other notifications active?

**Comment by kris7t** [comment]
I've been meaning to implement an option for this (https://github.com/getferdi/ferdi/pull/1433/files/bf80833851568de178e5095c80635ae93b7bcf3f#r635437395), but haven't had the time yet.
