### ISSUE TITLE
Update outdated node modules

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1495]

**Comment by mhatvan** [comment]
## Dependencies upgrades that are in progress

- `webpack`, `webpack-cli`, `html-webpack-plugin`, `terser`, `ts-loader` are upgraded in gulp to webpack PR
- `@adonisjs/*` - upgrades are done in https://github.com/getferdi/server

## Dependencies that have to stay locked for now

- `macos-version`, `normalize-url` and `os-name`: new versions only work with ES Modules, no CommonJS. Still a long way to get there.
