### ISSUE TITLE
Ability to override the behavior of opening links/button-actions globally and per-recipe

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1501]
**Is your feature request related to a problem? Please describe.**
Of late, we have seen lots of issues related to the behavior of opening pages (whether they are links or buttons) from within the service/recipe. Some users want the ability to open these urls in the same service's view (for eg clicking on a link to an issue in the Github service should change the current webview's location), some other users want a modal window within Ferdi for the link that's clicked, and some others want the url to be opened in the default browser.

**Describe the solution you'd like**
Such an idea is great - since it will allow the users the ability to choose which option they want - and set one value globally, while also being able to override per-recipe. If the user wants more fine-grained control per type of link (for eg, "anything with a `target=_blank` should behave like so-and-so), then they can use the context menu to perform that specific action for that specific link-type. (so, this final bit is not in scope for this enhancement).

**Describe alternatives you've considered**
A workaround has been implemented [here](https://github.com/getferdi/recipes/pull/546) - but, this is not scaleable - and still doesn't allow the *user* to determine which behavior is best for their interaction.

**Additional context**

**Comment by davidbenucci** [comment]
I moved to Ferdi from Shift. In that application, for each link/button, right-clicking on it I can choose form 3 option:
- open the link in the same windows
- open the link in a new aplication window
- open the link in the default browser
I think this could be a good solution and it could be implemented in Ferdi giving the use rthe control over each link. It could be useful to set a default behaviour for each service in service option page.
This is my opinion. Hope you find it useful.

**Comment by gsantner** [comment]
a simple way is to allow configure regexes (one-per-line) which when matching - opens the link inside ferdi. would be quite good solution to most problems already...like

```
https:\/\/l.facebook.com\/.*
https:\/\/m.facebook.com\/.*
notfications-whatever.reddit.com
```

this per webapp (pre-defined) and user configureable per webapp (user-defined input box)

What I get when clicking literally anything in the facebook ferdi app -> opens in external browser and I have to login again to actually get to the page I clicked to visit `
https://l.facebook.com/l.php?u=https%3A%2F%2F....rest.of?%20the%20link`

![grafik](https://user-images.githubusercontent.com/6735650/146653624-9626ef95-50a4-4ce0-9da8-0940d7e37432.png)

I would expect then that it at least resolved the l-facebook-com link internally at ferdi, which redirects then to and opens in external browser `https://rest.of?%20the`

**Comment by gsantner** [comment]
Wob't fix?

**Comment by gsantner** [comment]
won't fix?

**Comment by gsantner** [comment]
@vraravam  won't fix?

Just curious because you have been closing lots of issues as duplicate to this, just to not fix the issue at the end.
