### ISSUE TITLE
Google stuff keeps logging out too often.

### ISSUE THREAD

**Issue by leoheck** [getferdi/ferdi#1511]
Is it possible to do something or increase this time from our side?
This is pretty annoying it almost makes ferdi useless for Google stuff since I have to keep logging back a bunch of google related services

**Comment by leoheck** [comment]
This may help to fix this issue. Just don't know how.
https://support.google.com/accounts/answer/54490?hl=en

**Comment by Jendker** [comment]
I don't have this issue. You could try reloading the service, maybe that will help.

**Comment by vraravam** [comment]
I dont have this issue - I am running the latest nightly on my machine. (macOS BigSur)

**Comment by leoheck** [comment]
It happens quite often. Running the latest nightly on my machine (Ubuntu 21.04)
How many different Google accounts do you have? I have more than 1, 4 actually.

**Comment by leoheck** [comment]
> I don't have this issue. You could try reloading the service, maybe that will help.
No, it doesn't help.
I have to do the login again every time.

**Comment by kris7t** [comment]
Maybe Google is applying heuristics to log you out if you're logged into multiple Google accounts from the same machine?

**Comment by leoheck** [comment]
I am always logged in on multiples accounts in the same machine in the browser (Google Chrome) with the same profile.

**Comment by Jendker** [comment]
Do you mean that you have multiple browsers and in each one you can see a different account simultaneously? That's essentially what Ferdi does. I believe you are switching between the accounts in browser, that's something different.

**Comment by leoheck** [comment]
I have a single browser, multiples tabs, connected to different Google accounts. Every time I want to access a different account in Gmail, for instance, I just click on my picture. Then I choose another account and then I am in. Without having to put the password again. 

In Ferdy, I am login into an account then after some time, something happens and then I have to type the password again.

**Comment by kris7t** [comment]
Yeah, that means you're logged into a single Google account at a time, and use Google's quick switch functionality (so Google is aware that your accounts belong the same person, and that you're using them on the same machine). In Ferdi, you're logged into multiple Google accounts with different browser profiles ("partitions" in Chromium/Electron parlance), and Google doesn't connect the login with each other (or apparently, it does, and forces logouts). So I guess one way to fix this would be to make Google think you're using the different Google accounts from different browser (say, pretend that there are different Chromium versions for each).

Do you have 2FA enabled for your accounts? That might make Google trust your logins more.

**Comment by leoheck** [comment]
some of them have.

--
Leandro Heck

**Comment by vraravam** [comment]
I have the following services: gMail (official), gMail (personal), gChat (official), gCal (official), gCal (personal), gDrive (official). All of these work consistently without the behavior that has been reported here. I'm on the latest nightly/HEAD of the `develop` branch.

**Comment by leoheck** [comment]
It is been a while (a couple of days) since I didn't notice this, I am using `5.6-nightly.64` so it looks like something has changed. it looks promising. I will keep this open for a couple of days (maybe for a week) then I will close it, cool?

**Comment by keunes** [comment]
@leoheck kind community reminder that more than a week has passed ;)

**Comment by leoheck** [comment]
the community should interfere with personal decisions. but something has changed I am not having to log in pretty often anymore.

**Comment by vraravam** [comment]
Thanks for confirming @leoheck - i'll close this ticket now.

**Comment by keunes** [comment]
@leoheck no intent to 'interfer with personal decisions' - apologies if offence was taken.
