### ISSUE TITLE
Please add service Google Chat

### ISSUE THREAD

**Issue by putuniki** [getferdi/ferdi#1513]
![icon](https://user-images.githubusercontent.com/902237/121672603-94097700-cae2-11eb-9cb8-b3aa4959862c.png)

[package.txt](https://github.com/getferdi/ferdi/files/6637703/package.txt)
[README.txt](https://github.com/getferdi/ferdi/files/6637704/README.txt)
[service.txt](https://github.com/getferdi/ferdi/files/6637705/service.txt)
[webview.txt](https://github.com/getferdi/ferdi/files/6637706/webview.txt)
[gitignore.txt](https://github.com/getferdi/ferdi/files/6637707/gitignore.txt)
[index.txt](https://github.com/getferdi/ferdi/files/6637708/index.txt)

**Comment by vraravam** [comment]
@putuniki - this is already present called `hangoutschat`.
