### ISSUE TITLE
Google Calendars being loaded as in mobile.

### ISSUE THREAD

**Issue by leoheck** [getferdi/ferdi#1514]
The latest beta `5.6.0-beta.6` opens google calendars in mobile mode. How do I change/fix this?

**Comment by vraravam** [comment]
Not sure why - since I don't see this behavior at all (running on macos with the beta and other newer builds).

Most likely, your user-agent is being recognized incorrectly. Please try with the nightly builds from [here](http://github.com/vraravam/nightlies/releases) - this exposes the ability to the user to control the user-agent via the UI as opposed to editing files in the Ferdi profile. Please do be aware of the **unsigned nature** of the builds in this repo - while we work on fixing the issue with signing of our build artifacts.

**Comment by vraravam** [comment]
@leoheck - could you please confirm if the latest nightly (giving the user the capability to override the `user-agent`) fixes the above issue?

**Comment by leoheck** [comment]
Sure! Let me download it and test it.

Is it possible to add something on these nightly images that check and advertises new nightly releases?
The same can be used for stable releases as well.
And many a button to go to the releases page or to automatically update it

**Comment by leoheck** [comment]
This is my current ferdi.
![image](https://user-images.githubusercontent.com/1277920/122575678-6020db00-d027-11eb-8539-fe144ff614b7.png)

Which one is the latest one?
This is the latest I can see.
![image](https://user-images.githubusercontent.com/1277920/122575799-775fc880-d027-11eb-8b9c-964d819ff31f.png)

**Comment by vraravam** [comment]
Actually, such a feature is already present (for nightlies as well) - just that the url that it checks against is hardcoded/baked into the packaged app as `https://github.com/getferdi/nightlies/releases` as opposed to my fork which is `https://github.com/vraravam/nightlies/releases`

Please use my fork while we are still straightening out the code signing process.

**Comment by vraravam** [comment]
@leoheck - the link that I posted is pointing to *my fork* - not the main org/repo

**Comment by leoheck** [comment]
Cool, thanks.

**Comment by leoheck** [comment]
Still the same. I am afraid that I have to remove the service and add it back. I was just skipping doing this since the password process is a pain.
![image](https://user-images.githubusercontent.com/1277920/122579188-0a4e3200-d02b-11eb-813a-b0114ed40fb1.png)

**Comment by leoheck** [comment]
Even after adding a new Google Calender service, it loads the same mobile view.

**Comment by vraravam** [comment]
Please check the `user-agent` that's being sent to google? That is the only reason for the mobile ui to show up as opposed to the desktop-version

**Comment by leoheck** [comment]
Where? How?

**Comment by leoheck** [comment]
I cannot click this field.
![image](https://user-images.githubusercontent.com/1277920/122580331-37e7ab00-d02c-11eb-9b50-c665c0025186.png)

**Comment by leoheck** [comment]
These buttons do not work.
![image](https://user-images.githubusercontent.com/1277920/122580418-4fbf2f00-d02c-11eb-8cfd-61d998c57175.png)

**Comment by vraravam** [comment]
this is the "hint" - the field is a text field - into which you can put the entry/string that is appropriate for your OS

**Comment by leoheck** [comment]
No haha. You have to explain how to do what you need.
![image](https://user-images.githubusercontent.com/1277920/122580727-a75d9a80-d02c-11eb-9f69-e0b296a2674e.png)

**Comment by leoheck** [comment]
How do I do this?

**Comment by vraravam** [comment]
<img width="396" alt="Screen Shot 2021-06-18 at 8 30 58 PM" src="https://user-images.githubusercontent.com/69629/122581470-b49e7780-d074-11eb-9200-4ab62ded6ecd.png">
1. Click on "View > Toggle Service Developer tools"

<img width="739" alt="Screen Shot 2021-06-18 at 8 31 15 PM" src="https://user-images.githubusercontent.com/69629/122581502-bcf6b280-d074-11eb-92a5-649ec1408386.png">

2. Click on the "Network" tab on top
3. Click on any of the links in the main window for the gCal service
4. back on the new window, click on the outgoing request
5. click on the "General" tab on the lower right pane
6. Scroll down to the "Request Headers" - and within this the "user-agent"

**Comment by leoheck** [comment]
Alright. Clicking anything inside GCalendar does not add anything in this list.
Clicking on another service and going back to the GCal service adds things on this list.
However I don't have anything like you have.

This is the name column
![image](https://user-images.githubusercontent.com/1277920/122587246-fa871b80-d033-11eb-82d4-04ab4c86f697.png)

This is one of the Request Headers after clicking on GCal service. I am not sure if I can past the whole content here.
What I am looking for?
![image](https://user-images.githubusercontent.com/1277920/122587270-0246c000-d034-11eb-806b-952dd6f3d437.png)

**Comment by vraravam** [comment]
> Alright. Clicking anything inside GCalendar does not add anything to this list.
> Clicking on another service and going back to the GCal service adds things to this list.
> However, I don't have anything like you have.
> 
> This is the name column
> ![image](https://user-images.githubusercontent.com/1277920/122587246-fa871b80-d033-11eb-82d4-04ab4c86f697.png)

This shows me that you have clicked on "View > Toggle Developer Tools" - not "View > Toggle Service Developer Tools" - pls try the correct one.

**Comment by leoheck** [comment]
oh, sorry.

**Comment by leoheck** [comment]
```user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36```

**Comment by vraravam** [comment]
I have this in my mac: `user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 12_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36` - which seems to be the correct equivlent.

**Comment by vraravam** [comment]
Are you sure that you haven't edited the `index.js` and/or the `webview.js` in the ferdi profile folder for `googlecalendar`?

**Comment by leoheck** [comment]
I updated all recipes together last time you have told me to update recipes.
I will try to remove this one then.

**Comment by leoheck** [comment]
it didnt change anything.

**Comment by vraravam** [comment]
Yes please - the manual update of the recipes was for an older version of ferdi. since then, ie the current nightly, please use the vanilla recipes ie no changes at all.

**Comment by leoheck** [comment]
how do I do that?

**Comment by vraravam** [comment]
1. please stop ferdi
2. open the file explorer, navigate to the folder where the ferdi profile is stored,
3. Delete the whole `recipes` folder.
4. Restart ferdi

**Comment by vraravam** [comment]
if you have been using ferdi with a server (franz or ferdi server) then all your pre-registered services should come back without any other manual steps - this time around with the vanilla recipes code.

**Comment by leoheck** [comment]
Done. Nothing has changed.

**Comment by leoheck** [comment]
Maybe I have to remove the whole ferdi folder or a cache folder

**Comment by leoheck** [comment]
Nothing, still the same even after removing the while ferdi folder and login in with my franz/ferdi account

**Comment by vraravam** [comment]
Sorry - i have run out of ideas. I also use gCalendar - and it works perfectly on my MBP 16"

**Comment by leoheck** [comment]
No problem. Any idea where I can tweak the service URL? Maybe I can workaround it somehow.

**Comment by vraravam** [comment]
It's in the same folder - in the file called `package.json` - look for `serviceURL`

**Comment by leoheck** [comment]
When I was setting everything back. I saw this in the footer of Calendar's page.
It is fixed now. This is annoying as hell. Thank you so much for your help @vraravam 
![image](https://user-images.githubusercontent.com/1277920/122604127-d2a3b200-d04b-11eb-9604-a0b0999ba459.png)

**Comment by vraravam** [comment]
At least this episode showed you the temporary nightlies location - and you can upgrade and use that (its quite stable btw)

**Comment by leoheck** [comment]
This is true. I like to be on the bleeding edge.

**Comment by leoheck** [comment]
I am not a specialist, but I feel that the Ferdi cannot store cookies or something for Google Calendar. Am I right? 

It also keeps changing language as you can see here. My accounts are all in English. 
![image](https://user-images.githubusercontent.com/1277920/122923835-79819a00-d33b-11eb-8bf9-8fe23ba81ff5.png)

**Comment by leoheck** [comment]
I had to reopen this. This calendar thing is pretty annoying. Maybe it is a problem with cookies or something.

**Comment by sowiso** [comment]
I had the same, I also saw a dev mode label under the settings icon. I can temporarily fix it by removing the ~/.config/FerdiDev folder, but after a while I get a message that says "Your services have been updated." with a button "Reload services"

After I click that, Google calendar reloads in mobile mode again, and also the dev mode label is back again

![image](https://user-images.githubusercontent.com/1487955/124237484-dc331c80-db17-11eb-8856-b2882d6d7cb5.png)
![image](https://user-images.githubusercontent.com/1487955/124237514-e228fd80-db17-11eb-94fa-fb9c49824990.png)

**Comment by leoheck** [comment]
Good to know. Unfortunately I don't have anything labeled development. I tried a lot of stuff. Removing the app, removing recipes. Removing local config files. Nothing works. I am almost looking for something different than Franz.

**Comment by vraravam** [comment]
@sowiso @leoheck : (just a guess looking at the code): do you have an env var called `NODE_ENV` set?

According to [this line](https://github.com/getferdi/ferdi/blob/develop/src/environment.js#L53) of code, if such an env var is set, then Ferdi assumes you are running in development mode. This might cause such issues. Please try by removing that variable if its set.

**Comment by vraravam** [comment]
I tried setting the above `NODE_ENV` to `development` on my mac. But, this had no effect when I run Ferdi from the packed version (the orange "DEV MODE" didn't appear across restarts of Ferdi). I had refactored some of the code around this - just yesterday for a different purpose (cleanup/simplification). Once the current in progress v73 nightly build finishes - please try it out and report back? Should be completed in an hour or so.

**Comment by vraravam** [comment]
> I am almost looking for something different than Ferdi

@leoheck - I would love to retain you as a user/contributor and would like to help debug the issue. Is it possible to connect on zoom?

**Comment by leoheck** [comment]
It is late here now. But I will continue using Ferdi. I will try to check what you said tomorrow and then we can try to figure out an alternative solution. I didn't try to go back to the stable version for instance.

**Comment by mhatvan** [comment]
I am also experiencing this issue on Ubuntu 21.04 currently. It happens as soon Google Cal is loading, also when reloading the tab manually.

**Comment by leoheck** [comment]
It looks like I don't have any environment variable refereeing to the node. I also don't have any indication about Ferdi running as in development mode.

I am on Ubuntu 21.04 but I am pretty confident it is not related to the OS version. Maybe the OS but not the version of it.

This is the URL for the desktop version when running in Chrome.
https://calendar.google.com/calendar/r

This is the mobile version of the URL. 
https://calendar.google.com/calendar/m
https://calendar.google.com/calendar/gp

Changing the default `serviceURL` seems to have worked for now. It needs to restart Ferdi to take effect.
![image](https://user-images.githubusercontent.com/1277920/124366830-f4469100-dc28-11eb-9652-a4505bce0995.png)

I would suggest this `serviceURL` field being accessible through this menu for tweaks. The field has to be a text input with the default value there so the user can see and tweak the original URL there. This may be a good idea since I have to do this for a Slack workspace I have too. 
![image](https://user-images.githubusercontent.com/1277920/124366841-14765000-dc29-11eb-80dc-9ec3705ce7f2.png)

**Comment by leoheck** [comment]
@mhatvan could you check if this tweak works for you too?
@vraravam what do you think about changing the default serviceURL? I bet no one is looking for a mobile version of the calendar.

**Comment by vraravam** [comment]
You can add a new entry `hasCustomUrl` (inside `config`) - which will allow you to then have the text entry field in the service settings @leoheck - please try that?

**Comment by mhatvan** [comment]
@leoheck The tweak works for me, thanks ;) Spotted this as well a while ago that its just a url difference to access the mobile version.

**Comment by leoheck** [comment]
> You can add a new entry hasCustomUrl (inside config) - which will allow you to then have the text entry field in the service settings @leoheck - please try that?

Yeap, it works.
![image](https://user-images.githubusercontent.com/1277920/124391745-72a64000-dcc8-11eb-8b16-25befa8e668f.png)

**Comment by sowiso** [comment]
v73 nightly build solved the Dev mode problem for me

The calendar problem was still there, but changing the url in the config also solves that

**Comment by vraravam** [comment]
I just committed the above into the main branch. Will appear in the next nightly(v75) in a couple of hours.
