### ISSUE TITLE
Unable to add new service on Linux

### ISSUE THREAD

**Issue by jinscoe123** [getferdi/ferdi#1517]
**Bug description:**

When attempting to add a new service, nothing happens.

**Steps to reproduce:**

1. Go to "Add new service (Ctrl-N)"
2. Search for a service (e.g. "Outlook").
2. Click on the icon for the particular service.
4. See that nothing happens.

**Expected behavior**

The new service should be added successfully.

**Screenshots**

When trying to add the service, the developer console shows the following error:

![image](https://user-images.githubusercontent.com/3609458/121735138-9059fe00-caaa-11eb-926e-560abbb05c3b.png)

Going to the `/home/jinscoe/.config/Ferdi/recipes/temp/outlook/` directory, there is one file, `recipes.tar.gz`, which is **NOT** a gzipped tar file. It is actually HTML, the contents of which I'll paste here:

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>ferdi-internal-server</title>

  <link rel="stylesheet" href="/css/vanilla.css" />
  <link rel="stylesheet" href="/css/main.css" />
</head>

<body>
<style>
    ol,
    p {
      margin: 0.5rem 0;
    }

  </style>
  <h1>Internal Ferdi Server</h1>
  <p>You are accessing the local server instance of your Ferdi application. This server is used to enable Ferdi's "Use without an Account" feature.</p>
  <p>
    To use Ferdi without an account, log out of your current account (if you are already logged in) and choose "Use Ferdi without an Account".
  </p>
  <p>
    Alternatively, you can <a href="/import">import your account from a remote server</a> or <a href="/transfer">import your data from a ".ferdi-data" file</a> or <a href="/transfer">export your data to a ".ferdi-data" file</a>.
  </p>
</body>

</html>
```

The HTML says to try logging out of my current account and choosing "Use Ferdi without an Account". I don't have a Ferdi account, and am not currently logged into one. I tried clicking "Log in", and then selecting "Use Ferdi without an Account", but it did not fix the issue.

**Environment:**

- Operating System: Linux 5.10.41-1-MANJARO
- Ferdi Version: 5.5.0-13 (installed via `pacman` package manager).
- Server: Using without an account

**Comment by Split7fire** [comment]
Same here on NixOS, ferdi 5.6.b6. The only services I can add is Telegram React and Whatsapp.

**Comment by Split7fire** [comment]
Seems to find workaround: If you sign in to franz (maybe ferdi) everything starts to operate. Previously I always chosed "without account"

**Comment by vraravam** [comment]
@jinscoe123 + @Split7fire : Since you are reporting an issue with a really old version of Ferdi (5.5), can I request you to use the latest nightlies from [here](https://github.com/vraravam/nightlies/releases) - and then report back whether this bug still is observed? Since we have done a lot of work to revamp services, I would like to check if this was some issue that was previously solved as a by-product of other work.

Please note that the code-signing process is currently broken right now and we are trying to get it fixed - but, till then please use the unsigned builds from my fork.
