### ISSUE TITLE
Password removed every time you open setting->privacy

### ISSUE THREAD

**Issue by mccoy88f** [getferdi/ferdi#1518]
**Bug description:**
After successful set a password on Mac Version Bigsur M1 version 11.4 (Ferdi version5.6.0 beta6, but also on previous one)
It works at usual.

If you open setting and go to privacy and then close password it will be set as blank (no password).
So if you restart app (or simple lock it) when ferdi ask for password you can enter only using blank password.

This problem happen just opening settings->privacy (you do not need to click on password setting)
I think is very important to solve thanks!

Thanks for all this great job!

**Comment by mccoy88f** [comment]
Testing Version: 5.6.0-nightly.57 on same device problem seems solved.

**Comment by vraravam** [comment]
@mccoy88f - could you please close the ticket if the issue has been resolved in the latest nightly?

**Comment by mccoy88f** [comment]
Problem solved with latest nightly build. Closed
