### ISSUE TITLE
Cyclical Dependencies in JS modules

### ISSUE THREAD

**Issue by markandan** [getferdi/ferdi#1519]
Found few cyclical dependencies in the source code.

Example: 
`features/announcements/index.js` -> exports `ANNOUNCEMENTS_ROUTES` and also imports `AnnouncementsStore` from `features/announcements/store.js`

`features/announcements/store.js` -> imports `ANNOUNCEMENTS_ROUTES` from `index.js` resulting in cyclical dependency.

There are few more modules where the same issue is present.

**Comment by vraravam** [comment]
Thanks for the contribution @markandan . As you mentioned, for the other instances of the same problem - please go ahead and raise PRs.

**Comment by vraravam** [comment]
Closing this issue - since all the cyclic dependencies are now fixed (as of this point)
