### ISSUE TITLE
Electron 'app.allowRendererProcessReuse' issue causes segfault

### ISSUE THREAD

**Issue by Librechain** [getferdi/ferdi#1523]
> *leaving the support messages for Ferdi up in this issue request to help spread awareness* 

Using an Arch Linux OS ; fairly modern laptop (2019), with 16GB+ RAM & other modern parts + processors (mentioning this to rule out device issues & provide bg info). 

When running the .AppImage, there's a ton of resource used as the app attempts to start - then it eventually seg faults. 

Message given: 

```bash
[user]$ ./Ferdi-5.5.0.AppImage # command ran; below is the output in the terminal
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Segmentation fault (core dumped)
```
I'm not really sure what they're talking about wrt "app.allowRendererProcessReuse" (not familiar w Electron); any guidance would be super appreciated. 

Thank you in advance

**Comment by Librechain** [comment]
**Update** 

Went over to the releases, downloaded the .tar.gz instead, extracted and chmod +x on the 'ferdi' executable and ran it and it worked (_although it produced the same feedback regarding the Electron flag mentioned above_). 

**Here's the Output After Running the Binary From the Terminal**: 

```bash
[user]$ ./ferdi
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:32170) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9. # this warning repeats multiple times in case that's meaningful info 
```

**Comment by kris7t** [comment]
You should try the latest beta: https://github.com/getferdi/ferdi/releases/tag/v5.6.0-beta.6

Unfortunately, at this point, the stable 5.5.0 release is extremely old and is built on an extremely old version of Electron.

Nevertheless, the `allowRendererProcessReuse` warning is probably not connected to the segfault (it's just the last thing Electron manages to print before failing).

**Comment by Librechain** [comment]
> You should try the latest beta: https://github.com/getferdi/ferdi/releases/tag/v5.6.0-beta.6
> 
> Unfortunately, at this point, the stable 5.5.0 release is extremely old and is built on an extremely old version of Electron.
> 
> Nevertheless, the `allowRendererProcessReuse` warning is probably not connected to the segfault (it's just the last thing Electron manages to print before failing).

Wow I'm a moron. 

Sorry about that and thanks man. Closing this issue. Keep up the great work.
