### ISSUE TITLE
No notification badge for WhatsApp

### ISSUE THREAD

**Issue by Jendker** [getferdi/ferdi#1526]
Please fill our form below, this way we can analyse and fix the problem as fast as possible.

Please keep in mind that any text inside "
**Bug description:**
Since updating to 5.6.0-beta6 there are no notification badges for WhatsApp. I have updated to latest nightly and tried downgrading to 5.5.0 but the notification badge still do not appear.

**Steps to reproduce:**
1. Update to 5.6.0-beta6
2. There is no notification badge on WhatsApp.

**Screenshots**
<img width="122" alt="Screen Shot 2021-06-14 at 9 35 33 AM" src="https://user-images.githubusercontent.com/14967831/121927489-f5ecfb00-ccf3-11eb-853f-6a9f45e2d040.png">

**Environment:**

- Operating System: MacOS Big Sur
- Ferdi Version: 5.6.0-beta6, nightlies
- Server: Ferdi

- Debug information:
I press the Accept and Publish but nothing happens.

**Comment by pulver22** [comment]
I must say I tried to follow what written in #1301 but it doesn't work for me on the latest nightly.

**Comment by Jendker** [comment]
It worked for me. I am running Ferdi on Mac and I had to place the webview.js from the linked recipe into /Users/<userID>/Library/Application Support/Ferdi/recipes/whatsapp.

Thanks!
