### ISSUE TITLE
Ability to select icons sizes for services in sidebar

### ISSUE THREAD

**Issue by pztrn** [getferdi/ferdi#153]
It'll be great if I can choose icons size in sidebar to make them smaller to allow more services to be visible.

**Comment by vraravam** [comment]
Yes - on different machines with different screen resolutions - this looks good/bad - and is also a very subjective matter. Could you please make this a user-configurable option?

**Comment by vantezzen** [comment]
Both @kytwb and me are currently pretty busy so we won't be able to implement this anytime soon but PRs are always welcome.

**Comment by vantezzen** [comment]
Added the ability to change the sidebar width via e8a64e25 and the ability to change icon size via 8fe27d40.

**Comment by vraravam** [comment]
Can we get a new beta build with this PR?  I would love to try this out!

**Comment by kytwb** [comment]
@vraravam We will make a release in the coming days as soon as we've merged the other open pull requests and did a review to make sure we don't introduce regressions 🙏 Thanks for your patience!

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.2).
