### ISSUE TITLE
Possibility to login without password when Ferdi is locked 

### ISSUE THREAD

**Issue by eliaszkubala** [getferdi/ferdi#1530]
**Bug description:**
I enabled password lock-in Settings. There is two way to log in without a password. 

**Steps to reproduce:**
First way
1. Enable password lock 
2. Click on notification after app lock
3. You will log in without a password

Second way
1. Enable password lock 
2. Use touch bar to select service
3. You will log in without a password

**Expected behavior**
Do not start without a password 

**Screenshots**

**Environment:**

- Operating System: Big Sur
- Ferdi Version: 5.4.3 
- Server: Using without an account

- Debug information:

**Comment by vraravam** [comment]
Tagging [this discussion](https://github.com/getferdi/ferdi/discussions/1645)
