### ISSUE TITLE
Activating app lock causes application to hang (Win10 - latest ferdi windows)

### ISSUE THREAD

**Issue by Joshndroid** [getferdi/ferdi#1533]
Windows 10 latest
Ferdi (portable or installation no different) windows app latest 5.5.0 (straight off website)
Backend server - self hosted ferdi server

Activate the app lock check box and save.

Application goes purple. Hangs with no ability to function.
Have attempted numerous times over different days.

Requires a full uninstall including the removal of all ferdi residual files to allow a fresh installation and log in to ferdi account.

Due to the app fully locking up and just showing the purple background i cannot get you a debug via the menu...

**Comment by vraravam** [comment]
@Joshndroid - could you please try with the latest nightlies found [here](https://github.com/getferdi/nightlies/releases) - and report this problem if it exists?

**Comment by Joshndroid** [comment]
cheers for the reply.
I activated this and input a secure password.
It now locks me out.
the password does not work and says that it is incorrect (it definitely wasn't incorrect, generated and saved in a password manager)
I have to setup ferdi again... sigh lol

**Comment by vraravam** [comment]
@Joshndroid  - there's an outstanding bug where, on the password screen, press the `Escape` key or the key combination to open the settings / preference pane. this will (unfortunatel) bypass the security and open Ferdi. This is a known bug that has not yet been fixed. If this works, you can unlock Ferdi.

**Comment by Joshndroid** [comment]
I just reset it up again... thankfully it doesnt kill my account or anything as i host it local... its just the setting doesnt work at present and ill have to use another program to atleast secure my instance a bit

**Comment by vraravam** [comment]
Please try with the latest version 5.6.0 and if it still doesn't work, I will take this up over this weekeend or next.

**Comment by vraravam** [comment]
Just released the latest nightly (and the first in the 5.6.1 series): https://github.com/getferdi/nightlies/releases/tag/v5.6.1-nightly.3 - I am running this and do not see this behavior. Please confirm on your machine and close this bug asap.

**Comment by Joshndroid** [comment]
I switched over to the deb version a little while back. But i just installed the nightly and enabled the password lock with no issues apart from the toggle taking a fair while to 'activate' and 'deactivate.' I originally created this based on the stable release, rather than the nightly release. But all in all it appears that the app lock works as required albeit a tad slow to toggle. Cheers
