### ISSUE TITLE
Tutanota is listed as a supported service on the website but is not available in the services in the app

### ISSUE THREAD

**Issue by g4z** [getferdi/ferdi#1534]
hi

Before downloading Ferdi, i checked that it supports Tutanota by searching here: https://getferdi.com/services/

![image](https://user-images.githubusercontent.com/16230360/122375593-a6ad0180-cf63-11eb-8e13-e997591932dc.png)

After downloading the app, seems like Tutanota is not available

![image](https://user-images.githubusercontent.com/16230360/122375243-55047700-cf63-11eb-8401-1ff18a13492d.png)

Am i missing something?

**Comment by vraravam** [comment]
Please download the latest nightly from [here](https://github.com/getferdi/nightlies/releases) - Tutanota is present in the packaged code in here.
