### ISSUE TITLE
Upgrade to latest Electron v13.x instead of v8.x

### ISSUE THREAD

**Issue by instagendleg** [getferdi/ferdi#1538]
**Is your feature request related to a problem? Please describe.**

Hi, as of today, this project is using Electron v8.x. The v13.1.2 is out.

It should be good to include the latest build for security, performance, UI fixes and compatibility improvement.

**Describe the solution you'd like**

Upgrade Electron v8.x. to v13.x.

**Additional context**

* https://www.npmjs.com/package/electron

**Comment by vraravam** [comment]
@instagendleg - please use the latest nightlies that can be found [here](https://github.com/vraravam/nightlies/releases) - we have been on electron v13.x for the past couple of months - but, are unable to release due to the broken code signing process.
