### ISSUE TITLE
Listen to Whatsapp voice messages?

### ISSUE THREAD

**Issue by vedagel** [getferdi/ferdi#1540]
Dear community, so far I have not been able to play WhatsApp voice messages. There is just no sound. But this works via the Whatsapp app. Is that a bug or doesn't it work in Ferdi?

Many Thanks!
vedagel

**Comment by vraravam** [comment]
@vedagel - It would be good to specify which version of Ferdi, which OS, etc that you are using. Without this important info, it would be hard for anyone to try to help.

If you are on Ferdi 5.5.x, I would request you to upgrade to the latest nightlies found [here](https://github.com/vraravam/nightlies/releases). This will also upgrade your registered non-custom services (which I assume Whatsapp to be one of). Please try with this and then report the findings - with some more info please.

**Comment by pigi-spm** [comment]
Hi @vedagel , I had the same problem with Whatsapp (I use the whatsapp services). 
If the **disable audio** option is activeted on the whasapp service than you can not listen the voice messages. 
One test is to **enable the audio** for the whasapp service. 
You find it on: 
`settings -> your serivces -> [ your whasapp service ] -> enable audio`

please let us know

P.s. I use ferdi version 5.6.0 - beta.6 on Windows 10

**Comment by vedagel** [comment]
Hi @pigi-spm this is it. Thanks for your help!! How it works :)
