### ISSUE TITLE
screen share on Ferdi

### ISSUE THREAD

**Issue by thomasplt** [getferdi/ferdi#1541]
I am a mac user, into the mac settings --> "security" --> "screen record" Ferdy is authorized (attached screenshot). Unfortunately, screen sharing is not working on slack when having a call. Any solution?
<img width="764" alt="Capture d’écran 2021-06-21 à 14 39 32" src="https://user-images.githubusercontent.com/82810630/122763540-ba77a100-d29e-11eb-858f-36ce25bdc23d.png">

**Comment by sathishkumar-manogaran** [comment]
Not only Slack, I am facing same issue with Teams also. Due to this every time I am opening actual app / service to do screen share.

**Comment by luisfpg** [comment]
Screen share seems to be broken in general.
I'm using Ferdi on Linux and screen share doesn't work.
Tested in both Skype and Hangouts with Ferdi 5.5 (stable), 5.6 Beta 5 and nightly 81.

**Comment by vraravam** [comment]
I tried to do this with 2 personal logins - but, looks like screensharing is only available for paid accounts on slack. Would anyone be willing to help debug the issue farther? If so, I can try to pair with you. (I assume that if one of the participants is on a paid account, they can screenshare with another participant who is not in any paid plan?)
<img width="900" alt="Screenshot 2021-07-14 at 7 47 42 AM" src="https://user-images.githubusercontent.com/69629/125550698-6c492bda-3ae5-466e-9c4e-d787e05c5d50.png">

**Comment by muhammedabad** [comment]
> Not only Slack, I am facing same issue with Teams also. Due to this every time I am opening actual app / service to do screen share.

Same issue experienced here

**Comment by SolAZDev** [comment]
This is happening to me in all services where I tried to share the screen. Teams, Messenger, Discord, etc.

**Comment by muhammedabad** [comment]
Does anyone know of any workaround for this ?

**Comment by sathishkumar-manogaran** [comment]
Hi @vraravam I got some error logs from the console (MS Teams - Screenshare). This log will print when user clicks on Screenshare button while in the call. (Not sure how much it can you help to debug).

> `2021-07-19T06:00:55.248Z [screenSharing][control] screenSharingControlService: unexpected, cannot find the call, teamsCallId [1]
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:114
(anonymous) @ 3.2-app.min-ef0c71e.js:1
(anonymous) @ 3.2-app.min-ef0c71e.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:246
b @ 0.2-angular-jquery.min-eee9041.js:122
e @ 0.2-angular-jquery.min-eee9041.js:270
$eval @ 0.2-angular-jquery.min-eee9041.js:142
$apply @ 0.2-angular-jquery.min-eee9041.js:142
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:270
dispatch @ 0.2-angular-jquery.min-eee9041.js:1
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:1
0.2-angular-jquery.min-eee9041.js:114 2021-07-19T06:00:55.275Z callingAgents: calling-stack [JS.TsCalling.MediaAgent] ffffffff: MA/DeviceManager/MediaStreamManager could not start media stream: 1, total streams: 2, error: {}
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:114
(anonymous) @ 3.2-app.min-ef0c71e.js:1
(anonymous) @ 3.2-app.min-ef0c71e.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ rt-js-bindings.bundle-db8ace5.js:1
(anonymous) @ rt-js-bindings.bundle-db8ace5.js:1
(anonymous) @ rt-js-bindings.bundle-db8ace5.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
Promise.catch (async)
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
i @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
i @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
i @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
P @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
l @ 3.1-app.min-af47a74.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:246
b @ 0.2-angular-jquery.min-eee9041.js:122
e @ 0.2-angular-jquery.min-eee9041.js:270
$eval @ 0.2-angular-jquery.min-eee9041.js:142
$apply @ 0.2-angular-jquery.min-eee9041.js:142
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:270
dispatch @ 0.2-angular-jquery.min-eee9041.js:1
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:1
Show 20 more frames
0.2-angular-jquery.min-eee9041.js:114 2021-07-19T06:00:55.276Z callingAgents: calling-stack [JS.TsCalling.MediaAgent] ffffffff: MA/DeviceManager getMediaStream() error: TypeError: e.getAudioTracks is not a function
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:114
(anonymous) @ 3.2-app.min-ef0c71e.js:1
(anonymous) @ 3.2-app.min-ef0c71e.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ rt-js-bindings.bundle-db8ace5.js:1
(anonymous) @ rt-js-bindings.bundle-db8ace5.js:1
(anonymous) @ rt-js-bindings.bundle-db8ace5.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
Promise.catch (async)
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
i @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
i @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
i @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
P @ skype-calling-pluginless.bundle-a2629e4.js:1
(anonymous) @ skype-calling-pluginless.bundle-a2629e4.js:1
l @ 3.1-app.min-af47a74.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 3.1-app.min-af47a74.js:1
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:246
b @ 0.2-angular-jquery.min-eee9041.js:122
e @ 0.2-angular-jquery.min-eee9041.js:270
$eval @ 0.2-angular-jquery.min-eee9041.js:142
$apply @ 0.2-angular-jquery.min-eee9041.js:142
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:270
dispatch @ 0.2-angular-jquery.min-eee9041.js:1
(anonymous) @ 0.2-angular-jquery.min-eee9041.js:1
Show 20 more frames
0.2-angular-jquery.min-eee9041.js:114 2021-07-19T06:00:55.280Z CallingScreenSharingMixin: Failed to start screenSharing in call 59ff2102-75c7-4be7-9ba1-a67bf6d0feab, error: {"stack":"TypeError: e.getAudioTracks is not a function\n    at t.applyState (https://statics.teams.cdn.office.net/hashed/skype-calling-pluginless.bundle-a2629e4.js:1:1261921)\n    at t.<anonymous> (https://statics.teams.cdn.office.net/hashed/skype-calling-pluginless.bundle-a2629e4.js:1:1261716)\n    at i (https://statics.teams.cdn.office.net/hashed/skype-calling-pluginless.bundle-a2629e4.js:1:1257549)\n    at Object.next (https://statics.teams.cdn.office.net/hashed/skype-calling-pluginless.bundle-a2629e4.js:1:1256853)\n    at https://statics.teams.cdn.office.net/hashed/skype-calling-pluginless.bundle-a2629e4.js:1:1256762\n    at new Promise (<anonymous>)\n    at https://statics.teams.cdn.office.net/hashed/skype-calling-pluginless.bundle-a2629e4.js:1:1256539\n    at t.handleMediaStreamRequestSuccess (https://statics.teams.cdn.office.net/hashed/skype-calling-pluginless.bundle-a2629e4.js:1:1261123)\n    at https://statics.teams.cdn.office.net/hashed/skype-calling-pluginless.bundle-a2629e4.js:1:1261018","message":"e.getAudioTracks is not a function","name":"TypeError"}`

**Comment by eitchtee** [comment]
Facing the same issue on Discord.

[This polyfill](https://github.com/electron/electron/issues/16513#issuecomment-602070250) seemed to fix it.

---

I added it to the `webview.js` for the Discord recipe, as follows:

```javascript
"use strict";

var _path = _interopRequireDefault(require("path"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

module.exports = Franz => {
  const getMessages = function getMessages() {
    const direct = document.querySelector('[class*="guilds-"]').querySelectorAll('[class^="numberBadge-"]').length;
	
	var indirect = 0;
	var guilds = document.querySelector("[data-ref-id=guildsnav]");
	if(guilds != null) {
		var channelPills = [].slice.call(guilds.querySelectorAll("[class*=item-2hkk8m]"));
		indirect += channelPills.filter(y => y.clientHeight == 8).length;
	
		var activeWindow = channelPills.find(y => y.clientHeight == 40);
		if(activeWindow != null) {
			var unreadChannels = document.querySelector("[class*=modeUnread]");
			
			if(unreadChannels != null)
				indirect++;
		}
	}
	
    Franz.setBadge(direct, indirect);
  };

  Franz.loop(getMessages);
  Franz.injectCSS(_path.default.join(__dirname, 'service.css'));
};

const { desktopCapturer } = require('electron')
window.navigator.mediaDevices.getDisplayMedia = () => {
  return new Promise(async (resolve, reject) => {
    try {
      const sources = await desktopCapturer.getSources({ types: ['screen', 'window'] })

      const selectionElem = document.createElement('div')
      selectionElem.classList = 'desktop-capturer-selection'
      selectionElem.innerHTML = `
        <div class="desktop-capturer-selection__scroller">
          <ul class="desktop-capturer-selection__list">
            ${sources.map(({id, name, thumbnail, display_id, appIcon}) => `
              <li class="desktop-capturer-selection__item">
                <button class="desktop-capturer-selection__btn" data-id="${id}" title="${name}">
                  <img class="desktop-capturer-selection__thumbnail" src="${thumbnail.toDataURL()}" />
                  <span class="desktop-capturer-selection__name">${name}</span>
                </button>
              </li>
            `).join('')}
          </ul>
        </div>
      `
      document.body.appendChild(selectionElem)

      document.querySelectorAll('.desktop-capturer-selection__btn')
        .forEach(button => {
          button.addEventListener('click', async () => {
            try {
              const id = button.getAttribute('data-id')
              const source = sources.find(source => source.id === id)
              if(!source) {
                throw new Error(`Source with id ${id} does not exist`)
              }
              
              const stream = await window.navigator.mediaDevices.getUserMedia({
                audio: false,
                video: {
                  mandatory: {
                    chromeMediaSource: 'desktop',
                    chromeMediaSourceId: source.id
                  }
                }
              })
              resolve(stream)

              selectionElem.remove()
            } catch (err) {
              console.error('Error selecting desktop capture source:', err)
              reject(err)
            }
          })
        })
    } catch (err) {
      console.error('Error displaying desktop capture sources:', err)
      reject(err)
    }
  })
}
```
---

This will replace Discord's native screen share windows tough, but I think it looks good enough.
![image](https://user-images.githubusercontent.com/10510126/126230651-c540c94a-0223-4f34-845f-3ae37a6db362.png)

Hopefully it will work for the other services.

@vraravam I could create a pull request with this change for Discord's recipe, not sure how you'd feel about replacing the native window though.

**Comment by vraravam** [comment]
@eitchtee - great find! If it works, please raise a PR. The other contributors can also comment on it.

imo, as long as it doesn't violate any security principles, then working code in the recipes is always welcome!

**Comment by eitchtee** [comment]
@vraravam done! https://github.com/getferdi/recipes/pull/600

Hopefully the other participants try the same with their services and we can reach a "fix" of sorts, as I don't think we can fix this on Ferdi's code as discussed [here](https://www.reddit.com/r/electronjs/comments/kazhum/hey_electronjs_i_built_meetinone_a_mac_app_for/gfdv4xu/).

**Comment by vraravam** [comment]
Please checkout the [latest nightly](https://github.com/getferdi/nightlies/releases/tag/v5.6.1-nightly.3) that we just released a few minutes ago. This has support for fixing the screensharing on Discord, Teams, etc. Please verify the same and report back. Once we have corroboration that this is indeed working, we can even release a new beta soon! Thanks for all your help.

**Comment by eitchtee** [comment]
But using the last nightly, I can confirm that screen sharing is working on **Discord** without the previously mentioned need to change `webview.js`.

![image](https://user-images.githubusercontent.com/10510126/126856774-93978d50-198b-4664-9205-09e7473a6d45.png)

![image](https://user-images.githubusercontent.com/10510126/126856804-d227f544-fd34-4395-b2f0-652ddb913f35.png)

**Comment by vraravam** [comment]
Closing based on previous comment

**Comment by luisfpg** [comment]
I can confirm that screen share now works in Skype.
However it DOES NOT work in classic hangouts calls.
Of course, calls in meet work, but it runs in browser, not in Ferdi.

**Comment by BrianGilbert** [comment]
No audio or video working in Discord via Ferdi on M1 Mac Mini with latest nightly

**Comment by vraravam** [comment]
@BrianGilbert - It would be good to specify what is "latest".... because there have been instances where the OP said they were on the latest, when in fact they were not. Please specify more details. Also, this ticket is closed, please create a new one - as I said, with more details.
