### ISSUE TITLE
Slack: This browser won’t be supported starting from 1st Sep 2021.

### ISSUE THREAD

**Issue by BackSeat** [getferdi/ferdi#1559]
The attached has started appearing at the bottom of the Slack Ferdi window. Do we need to do anything?
![image](https://user-images.githubusercontent.com/827233/123255782-23058e80-d4e8-11eb-9697-c4ca6407a922.png)

**Comment by vraravam** [comment]
@BackSeat - this has been discussed in the recent couple of days. Duplicate of #1552

**Comment by BackSeat** [comment]
Sorry, I searched on 'slack' but didn't find that issue.

**Comment by vraravam** [comment]
That's because its in the `closed` status. Please follow the thread there and the solution that works for other users.
