### ISSUE TITLE
Crowdin translation now downgraded?

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#156]
When merging Franz into Ferdi, I saw that line that was translated are now delete and because it is from Franz, the bla bla about paying service are back. So is there a way to stop breaking all language file because of the merge?

**Comment by Makazzz** [comment]
(Or this is just mne and everything is fine?)

**Comment by vantezzen** [comment]
Are there any translations that have been lost during the merge? The merge shouldn't have overwritten any Ferdi translations.
The new Franz translations for the new plan selection screen are now in the messages files as they are still part of the code (but the screen is never shown). We can hopefully completely remove that part of the code in the future.

**Comment by Makazzz** [comment]
@vantezzen Sorry I wrote this because I saw all the new translation and I was asking myself if everything was removed or whatever but if it is only merging and add something then its fine. Thanks for the comment.
