### ISSUE TITLE
Suppression of clipboard event notifications is broken

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1564]
**Bug description:**
Toggling of the `Don't show notification for clipboard events` seems to be broken. I have tried toggling on and off - but, when I copy the current page url from the right-click context menu - the notification still appears **always**.

**Steps to reproduce:**

1. Go to any service
2. Right-click anywhere on the page (not a link or image)
3. Choose "Copy Page url"
4. See notification

**Expected behavior**
If the preference setting is turned on/off, the notification should not show/show - respectively.

**Screenshots**

**Environment:**

- Operating System: macOS Monterey (beta)
- Ferdi Version: Latest from the `develop` branch (git SHA: 6fb38f93f708a1)
- Server: Ferdi

- Debug information:

**Comment by fuzzy76** [comment]
Why on earth is this on by default? I've never in my lifetime seen a single application that does this.

**Comment by vraravam** [comment]
@fuzzy76 - i had a need when i implemented this feature. This feature is supposed to allow the user to switch it off as necessary. You are welcome to contribute to the development and implement what you think is best.

**Comment by vraravam** [comment]
This is now fixed and will appear in tonight's nightly build.

**Comment by fuzzy76** [comment]
Implementing very uncommon functionality that no other app has because you have a need is one thing, but leaving it on by default is a weird choice. I am pretty sure most people would not want this.
