### ISSUE TITLE
Ferdi (latest 5.5.0) on Mac Mini m1 with Big Sur > MS Teams settings missing

### ISSUE THREAD

**Issue by SeBr28** [getferdi/ferdi#1566]
**Steps to reproduce**
Add Teams to Ferdi
Accept Microphone / Video change for Ferdi
Make video/audio call

**Expected behavior**
Normally you can change the webcam and/or mic settings. Also you can enable webcam filters (like blurred or diff. background)

**Actual behavior**
There are NO settings (no devices tab) what so ever for cam/mic and thus also no Webcamfilters...
If you open the regular teams app (next to Ferdi.. there you have everything right away..

ENVIRONMENT
Ferdi 5.5.0
Machine: Mac Mini M1 with Big Sur 11.4

WHAT WE SHOULD SEE:
![image](https://user-images.githubusercontent.com/86455299/123372730-61508b80-d584-11eb-9a5f-6b7350081a4b.png)

![image](https://user-images.githubusercontent.com/86455299/123372715-5ac21400-d584-11eb-83bd-62835e0cf08e.png)

IN FERDI:
![image](https://user-images.githubusercontent.com/86455299/123372743-69a8c680-d584-11eb-8b6c-f34112f6acdf.png)

**Comment by vraravam** [comment]
@SeBr28 - Ferdi 5.5 is really old. Please try running the latest nightlies from [here](http://github.com/vraravam/nightlies/releases).

**Comment by SeBr28** [comment]
Thank you for the quick replay.. however.. hmm..
i see in the nightly builds.. Three versions for Mac.. As it is a M1 chip i took the Arm64 - Mac but also the other just for MAC won't open. It says I have no permission to open the App and have to ask for permission..
Sorry if I seem noob..

**Comment by vraravam** [comment]
@SeBr28 - please see the other nightlies where I have linked to a blog post on the security that has been implemented by apple in catalina and newer OSes.
If you are on a Mac M1 - you need the `Mac M1` builds

**Comment by vraravam** [comment]
I have added the link to the article in this release as well.

**Comment by SeBr28** [comment]
It was a bit of a search (pretty new at Apple) but found it, got it working.. and now on the Arm64 version.
The issue remains however for the teams settings...
Also, maybe idiot question.. If I click on Ferdy todo's I get a side bar that says FRANZ todo's?

**Comment by vraravam** [comment]
If the teams settings dont appear - then its a limitation of MS Teams - in how they expose settings for a browser-based usage of their service. Ferdi will not be able to do much in this case im afraid.

The Franz TODOs page is WIP right now to rebrand to Ferdi.

**Comment by SeBr28** [comment]
Thnx for the very quick replies... will see what comes... :) thank you
