### ISSUE TITLE
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by Marietto2008** [getferdi/ferdi#1567]
I'm trying to run ferdi using the docker image on my jetson nano (ubuntu 21.04 / arm64) but it does not work :

root@zi-desktop:~/Desktop/Work/I9/ferdi# docker build -t ferdi-package .

Sending build context to Docker daemon  16.57MB
Step 1/13 : FROM electronuserland/builder:14 as builder
14: Pulling from electronuserland/builder
345e3491a907: Pull complete 
57671312ef6f: Pull complete 
5e9250ddb7d0: Pull complete 
5e45489a94de: Pull complete 
764526a9cbea: Pull complete 
2329f6147f0a: Pull complete 
4cc3a1addc22: Pull complete 
793329d210da: Pull complete 
feb4d6757ee3: Pull complete 
7141b72e1bf9: Pull complete 
5e502a75dfc8: Pull complete 
Digest: sha256:837f5cbec3735ee27eb7105b9646aedd73340bce7d6ea44943a99a105a4dca55
Status: Downloaded newer image for electronuserland/builder:14
 ---> 663ec91caf21
Step 2/13 : WORKDIR /usr/src/ferdi
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 7d100559e0e1
Removing intermediate container 7d100559e0e1
 ---> f4b30665faf0
Step 3/13 : COPY package*.json ./
 ---> 46724b7070e0
Step 4/13 : COPY lerna.json ./
 ---> 82770b973564
Step 5/13 : ENV PREVAL_BUILD_INFO_PLACEHOLDERS=true
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in ccb30b0bb17b
Removing intermediate container ccb30b0bb17b
 ---> de5f5e536725
Step 6/13 : RUN npm i -g node-gyp@8.0.0     && npm config set node_gyp "$(which node-gyp)"     && npx lerna bootstrap
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 0f78b9a03662
standard_init_linux.go:228: exec user process caused: exec format error
The command '/bin/sh -c npm i -g node-gyp@8.0.0     && npm config set node_gyp "$(which node-gyp)"     && npx lerna bootstrap' returned a non-zero code: 1

**Comment by kris7t** [comment]
The Docker image is for amd64 only, so you won't be able to build on arm64 using that.

We currently don't have Linux arm64 builds set up, only macOS arm64 builds are present. So you'll have to try installing and configuring a toolchain yourself to attemp a Linux arm64 build.

If you succeed, pull request would very much welcome! Unfortunately, as far as I know, we don't have Linux arm64 devices to try ourselves.

**Comment by vraravam** [comment]
I am going to  swap my daughter's laptop (M1) with mine (x86) - both macs. I will try to see if I can find a solution for this. But, if its an issue with the base docker image from electronbuilder - then we will have to wait for them to fix.

**Comment by vraravam** [comment]
@Marietto2008 - please converge all the ARM-based issues into a single one?

**Comment by vraravam** [comment]
Closing this since the conversation is continued in #1585
