### ISSUE TITLE
No notification badge for Telegram

### ISSUE THREAD

**Issue by xannasavin** [getferdi/ferdi#1568]
**Bug description:**

The Telegram service does not show a notification badge in the sidebar.

**Steps to reproduce:**

Receive a message in Telegram and don't see an unread counter.
All notifications are enabled.

**Expected behavior**

The icon in the sidebar should show a notification / unread badge

**Environment:**

- Operating System: Win10
- Ferdi Version: 5.6.0-beta6
- Server: Ferdi

- Debug information:

### You should REALLY not output any messages nor ID's in the debug information!

{
  "host": {
    "platform": "win32",
    "release": "10.0.19043",
    "screens": [
      {
        "id": 2528732444,
        "bounds": {
          "x": 0,
          "y": 0,
          "width": 1920,
          "height": 1080
        },
        "workArea": {
          "x": 0,
          "y": 40,
          "width": 1920,
          "height": 1040
        },
        "accelerometerSupport": "unknown",
        "monochrome": false,
        "colorDepth": 24,
        "colorSpace": "{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}",
        "depthPerComponent": 8,
        "size": {
          "width": 1920,
          "height": 1080
        },
        "displayFrequency": 60,
        "workAreaSize": {
          "width": 1920,
          "height": 1040
        },
        "scaleFactor": 1,
        "rotation": 0,
        "internal": false,
        "touchSupport": "unknown"
      },
      {
        "id": 2779098405,
        "bounds": {
          "x": 1920,
          "y": -79,
          "width": 1920,
          "height": 1080
        },
        "workArea": {
          "x": 1920,
          "y": -39,
          "width": 1920,
          "height": 1040
        },
        "accelerometerSupport": "unknown",
        "monochrome": false,
        "colorDepth": 24,
        "colorSpace": "{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}",
        "depthPerComponent": 8,
        "size": {
          "width": 1920,
          "height": 1080
        },
        "displayFrequency": 60,
        "workAreaSize": {
          "width": 1920,
          "height": 1040
        },
        "scaleFactor": 1,
        "rotation": 0,
        "internal": false,
        "touchSupport": "unknown"
      }
    ]
  },
  "ferdi": {
    "version": "5.6.0-beta.6",
    "electron": "13.0.1",
    "installedRecipes": [
      {
        "id": "slack",
        "version": "1.0.16"
      },
      {
        "id": "telegram",
        "version": "3.0.0"
      },
      {
        "id": "whatsapp",
        "version": "3.0.0"
      },
      {}
    ],
    "devRecipes": [],
    "services": [
      {
        "id": "XXX",
        "recipe": "whatsapp",
        "isAttached": true,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": false,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "XXX",
        "recipe": "telegram",
        "isAttached": true,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": false,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "XXX",
        "recipe": "slack",
        "isAttached": true,
        "isActive": true,
        "isEnabled": true,
        "isHibernating": false,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "XXX",
        "recipe": "slack",
        "isAttached": true,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": false,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "XXX",
        "recipe": "slack",
        "isAttached": true,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": false,
        "hasCrashed": false,
        "isDarkModeEnabled": true
      }
    ],
    "messages": [
      {
        "type": "error",
        "request": {
          "result": null,
          "wasExecuted": true,
          "method": "getInfo"
        },
        "error": {},
        "response": {},
        "server": "https://api.getferdi.com"
      },
      {
        "type": "error",
        "request": {
          "result": null,
          "wasExecuted": true,
          "method": "features"
        },
        "error": {},
        "response": {},
        "server": "https://api.getferdi.com"
      },
      {
        "type": "error",
        "request": {
          "result": null,
          "wasExecuted": true,
          "method": "all"
        },
        "error": {},
        "response": {},
        "server": "https://api.getferdi.com"
      },
      {
        "type": "error",
        "info": [
          "error",
          "Warning: You cannot PUSH the same path using hash history"
        ]
      },
            {
        "type": "error",
        "info": [
          "error",
          "Uncaught Error: An object could not be cloned.",
          "\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\@sentry\\browser\\dist\\helpers.js",
          91,
          13,
          {}
        ]
      },
      {
        "type": "
      {
        "type": "error",
        "info": [
          "error",
          "Uncaught Error: An object could not be cloned.",
          "\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\@sentry\\browser\\dist\\helpers.js",
          91,
          13,
          {}
        ]
      }
    ],
    "workspaces": [],
    "windowSettings": {
      "width": 800,
      "height": 600,
      "x": 100,
      "y": 100,
      "isMaximized": true,
      "isFullScreen": false,
      "displayBounds": {
        "x": 1920,
        "y": -79,
        "width": 1920,
        "height": 1080
      }
    },
    "settings": {
      "autoLaunchInBackground": false,
      "runInBackground": false,
      "reloadAfterResume": true,
      "enableSystemTray": true,
      "startMinimized": false,
      "minimizeToSystemTray": false,
      "closeToSystemTray": false,
      "privateNotifications": false,
      "notifyTaskBarOnMessage": true,
      "showDisabledServices": true,
      "showMessageBadgeWhenMuted": true,
      "showDragArea": false,
      "enableSpellchecking": true,
      "spellcheckerLanguage": "de-de",
      "darkMode": false,
      "locale": "de",
      "fallbackLocale": "en-US",
      "beta": true,
      "isAppMuted": false,
      "enableGPUAcceleration": "",
      "serviceLimit": 5,
      "server": "https://api.getferdi.com",
      "predefinedTodoServer": "https://app.franztodos.com",
      "autohideMenuBar": false,
      "lockingFeatureEnabled": false,
      "locked": false,
      "lockedPassword": "******",
      "useTouchIdToUnlock": true,
      "scheduledDNDEnabled": false,
      "scheduledDNDStart": "17:00",
      "scheduledDNDEnd": "09:00",
      "hibernate": false,
      "hibernateOnStartup": true,
      "hibernationStrategy": 300,
      "inactivityLock": 0,
      "automaticUpdates": true,
      "showServiceNavigationBar": false,
      "universalDarkMode": false,
      "adaptableDarkMode": true,
      "accentColor": "#ec6607",
      "serviceRibbonWidth": 68,
      "iconSize": 20,
      "sentry": false,
      "nightly": false,
      "navigationBarBehaviour": "never",
      "searchEngine": "duckDuckGo",
      "useVerticalStyle": false,
      "alwaysShowWorkspaces": false,
      "todoServer": "isUsingCustomTodoService",
      "customTodoServer": ""
    },
    "features": {
      "isSpellcheckerIncludedInCurrentPlan": true,
      "needToWaitToProceed": false,
      "needToWaitToProceedConfig": {
        "delayOffset": 3600000,
        "wait": 10000
      },
      "isServiceProxyEnabled": true,
      "isServiceProxyIncludedInCurrentPlan": true,
      "isAnnouncementsEnabled": true,
      "isWorkspaceIncludedInCurrentPlan": true,
      "isWorkspaceEnabled": true,
      "isCommunityRecipesIncludedInCurrentPlan": true,
      "isSpellcheckerPremiumFeature": false,
      "isServiceProxyPremiumFeature": true,
      "isWorkspacePremiumFeature": false,
      "isSettingsWSEnabled": false,
      "isServiceLimitEnabled": false,
      "serviceLimitCount": 0,
      "isCommunityRecipesPremiumFeature": false,
      "isCustomUrlIncludedInCurrentPlan": true,
      "isMagicBarEnabled": true,
      "isTeamManagementIncludedInCurrentPlan": true,
      "isTodosEnabled": true,
      "isTodosIncludedInCurrentPlan": true,
      "defaultTrialPlan": "franz-pro-yearly",
      "subscribeURL": "https://getferdi.com",
      "planSelectionURL": "https://getferdi.com",
      "hasInlineCheckout": true,
      "isPlanSelectionEnabled": false,
      "isTrialStatusBarEnabled": false,
      "canSkipTrial": true,
      "pricingConfig": {
        "currency": "$",
        "currencyID": "USD",
        "plans": {
          "personal": {
            "monthly": {
              "id": "ferdi-free",
              "price": 0,
              "billed": 0
            },
            "yearly": {
              "id": "ferdi-completely-free",
              "price": 0,
              "billed": 0
            }
          },
          "pro": {
            "monthly": {
              "id": "ferdi-still-free",
              "price": 0,
              "billed": 0
            },
            "yearly": {
              "id": "ferdi-forever-free",
              "price": 0,
              "billed": 0
            }
          }
        }
      }
    },
    "user": "XXX"
  }
}

**Comment by vraravam** [comment]
I use the `Telegram React` recipe, and I see the notification badge.
<img width="50" alt="Screen Shot 2021-06-25 at 5 17 56 PM" src="https://user-images.githubusercontent.com/69629/123420595-5d9b2400-d5d9-11eb-9163-9cb92f5fc969.png">

**Comment by xannasavin** [comment]
thank you @vraravam with the React recipe I do receive the notifications again. 

I am not sure if I should add a new ticket for my note, that the export of the log details must not contain any personal information like ID's or even text messages sent?

**Comment by vraravam** [comment]
Yes - please close this ticket and create a separate one for that. But, I must tell you that it would be a somewhat low priority at this time - since we want to do a lot of catchups/upgrades, etc - and all this AFTER the current release process is fixed. I hope you understand that - but, once again, please do log the bug. If there's a contributor who feels its of high-enough priority, i'm sure they will pick it up asap.
