### ISSUE TITLE
Upgrade mobx-react-router from 3.x to 4.x

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1569]
This seems to be a pre-requisite for building on ARM machines. so, might be considered high priority since more contributors are coming in with ARM-based laptops.

When building on a M1 mac, this is the error that I get (also, this is using node v16.4.0 because node v14.x is not supported on ARM architecture):
```bash
lerna notice cli v4.0.0
lerna info versioning independent
lerna info bootstrap root only
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ferdi@5.6.0-nightly.40
npm ERR! Found: mobx@5.15.0
npm ERR! node_modules/mobx
npm ERR!   mobx@"5.15.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer mobx@"^3.0.0" from mobx-react-router@3.1.2
npm ERR! node_modules/mobx-react-router
npm ERR!   mobx-react-router@"3.1.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by Marietto2008** [comment]
why u say that "node v14.x is not supported on ARM architecture" ? give a look at the image below : there are the versions we need :

![Screenshot_2021-06-26_15-03-18](https://user-images.githubusercontent.com/755339/123513821-aad9cd00-d68f-11eb-9ff0-daf03b707288.png)

**Comment by vraravam** [comment]
@Marietto2008 : According to [this page](https://github.com/nodejs/node/blob/v14.x/BUILDING.md#platform-list) - node v14 is not supported on macos on ARM chipsets.

**Comment by Marietto2008** [comment]
Im not on macOS.

**Comment by Marietto2008** [comment]
Help me to make a choice here :

zi@zi-desktop:~/.cache/yay/yay$ yay -S ferdi
:: There are 4 providers available for ferdi:
:: Repository AUR
    1) ferdi 2) ferdi-bin 3) ferdi-git 4) ferdi-nightly-bin 

Enter a number (default=1):

**Comment by vraravam** [comment]
If you are trying to build from source - then I would recommend `ferdi-git`
IF you are trying to run a pre-built binary, then `ferdi-nightly-bin`

**Comment by Marietto2008** [comment]
-> The following packages are not compatible with your architecture:
  ferdi-nightly-bin

**Comment by Marietto2008** [comment]
==> Updated version: electron-nightly-npm 15.0.0.nightly.20210625-1
==> Sources are ready.
==> Making package: electron-nightly-npm 15.0.0.nightly.20210625-1 (Sat Jun 26 14:09:06 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Entering fakeroot environment...
==> Starting package()...
npm ERR! code EINVAL
npm ERR! syscall lchown
npm ERR! path /home/zi/.npm/_locks
npm ERR! errno -22
npm ERR! EINVAL: invalid argument, lchown '/home/zi/.npm/_locks'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zi/.npm/_logs/2021-06-26T14_09_23_166Z-debug.log
==> ERROR: A failure occurred in package().
    Aborting...
error making: electron-nightly-npm
