### ISSUE TITLE
Cannot login to Ticktick on Todos sidebar with Google authentication

### ISSUE THREAD

**Issue by jimmylad** [getferdi/ferdi#1574]
**Bug description:**
Trying to login to Ticktick on Todos sidebar with Google authentication produces error

**Steps to reproduce:**

1. Open Todos sidebar with Ticktick server
2. Click on Google login
3. Enter email address and click next
4. Error message "Impossible to connect"

**Expected behavior**
Be able to login

**Environment:**

- Operating System: macOS High Sierra
- Ferdi Version: 5.5.0
- Server: Using without an account

**Comment by vraravam** [comment]
@jimmylad  - Ferdi has progresses a lot since v5.5.0 - please use the nightlies from [here](http://github.com/vraravam/nightlies/releases). We are currently grappling with broken signing process - and thus the unsigned builds are being released for general use for now.

**Comment by jimmylad** [comment]
Thanks for coming back quickly. Are you saying the Mac updates are broken?
I'm on the latest release (including betas) according to settings.

**Comment by vraravam** [comment]
Yes - the builds are broken due to the signing cert expiration. We are working on rectifying that.

Till then - please use the nightlies from my fork - they are unsigned.

**Comment by jimmylad** [comment]
Great thanks. Sorted in the latest nightly 👍
