### ISSUE TITLE
Ability to use localStorage for custom services even across restarts of Ferdi

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1579]
Many users configure services via custom services (as opposed to pre-configured services based on recipes). This trend is mainly due to some bug fixes not being available to them till they upgrade their version of Ferdi that is locally installed. Though some of this frustration can be relieved once this enhancement #1302 is implemented, the immediate fix can be to allow for the localStorage to store cookies/session data - including for custom services.

**Describe the solution you'd like**
If I login into Ferdi, configure a custom service, login into that service, and work. At the end of the day, I close Ferdi, and when I reopen Ferdi into that service - I should remain logged in (at least if this is allowed by that service). An example could be StackOverflow.

**Describe alternatives you've considered**
Request a new recipe for the service/url that I use quite often - but which might not be used by others. So, this ultimately pollutes the recipes of Ferdi.

**Comment by kris7t** [comment]
This looks very strange. Custom websites run from the `franz-custom-website` recipe, which doesn't interact with localStorage at all. The only way to clear the storage would be through the `session.clearStorageData` API, but it only gets called if the user clears the cache deliberately or logs out from Ferdi.

The only thing I can think about is the `service.partition` (or `recipe.partition`) being incorrectly initialized for custom websites, which would result in a non-persistent partition for the service, hence the data loss on restart. But creating a custom website service and inspecting its partition ID in `window.ferdi.stores.services.all` shows a `persist:` partition, so I'm stumped.

**Comment by vraravam** [comment]
Could it be that (if more than 1 custom recipe had been configured), then they clobber each other's data and end up with corrupted localStorage? Since the filesystem shows uuid-based folder names within the `Partitions` - I am unable to figure out if such a clash occurs.
