### ISSUE TITLE
Autodownload of upates - not working

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1581]
**Bug description:**
I got notified of a new nightly version of ferdi (please see the screenshot) - but, when I clicked on "What is new" - it showed a blank page. Also, clicking on "Restart & Install update" in the lower blue ribbon had the same effect - it terminated Ferdi, but nothing showed up in my downloads folder or anywhere else. I suspect that this is due to the [apiBase.js](https://github.com/getferdi/ferdi/blob/06920874d7c0761704c8d8b12a448e70c1a6333c/src/api/apiBase.js#L27) not handling the different repo, or somewhere in [autoUpdate.js](https://github.com/getferdi/ferdi/blob/06920874d7c0761704c8d8b12a448e70c1a6333c/src/electron/ipc-api/autoUpdate.js#L21) not working. Please fix asap.

**Steps to reproduce:**

1. Install an older nightly version of Ferdi
2. In settings, ensure that the `nightly` updates is checked
3. Verify in a browser that a newer version of nightlies has been released by the core team
4. After opening Ferdi with the above conditions met , after sometime, a blue ribbon will show (as in the screenshot)
5. Click on the 2 links in the blue ribbon and see the error

**Expected behavior**
If a version exists, then it should be upated by choosing the button in the ribbon.

**Screenshots**
<img width="1680" alt="Screen Shot 2021-06-30 at 12 09 10 PM" src="https://user-images.githubusercontent.com/69629/123913781-3c9d4f00-d99c-11eb-8247-2f34ac938957.png">

**Environment:**

- Operating System: macOS Monterey
- Ferdi Version: nightly v70
- Server: Ferdi

- Debug information:

**Comment by JazzXP** [comment]
Exactly the same issue here too on macOS Catalina and Big Sur.

**Comment by ylluminate** [comment]
Yep, nightlies are not actually downloading and updating when we trigger the "Restart & install update". Also seeing a "Reload services" all the time now on each startup and sometimes in the middle of use.

**Comment by cereum** [comment]
I can confirm this in the arm macbook. I get both random update service notifications and have no ability to auto update

**Comment by vraravam** [comment]
Update: The zip file is in fact downloaded into the cache folder. But, when the restart event happens, I think the Ferdi code is failing silently.

**Comment by mhatvan** [comment]
Might be related: https://github.com/electron-userland/electron-builder/issues/6174

**Comment by avielc** [comment]
This fails on Windows on 5.6.1 beta 3 onwards (probably before too) 
this also include downloading beta version or official release. 
(where is that blue ribbon supposed to be? )

**Comment by vraravam** [comment]
Closing - duplicate of #329
