### ISSUE TITLE
Mailbox.org logo still old version in Service Search

### ISSUE THREAD

**Issue by keunes** [getferdi/ferdi#1583]
**Bug description:** 'Mailbox.org' logo is still the old version when searching for this service

**Steps to reproduce:** click 'add service' search for 'mailbox.org' and notice the old logo. Click to add the service, and notice the correct logo

**Expected behavior**

**Screenshots**

**Environment:**

- Operating System: Ubuntu
- Ferdi Version: 5.6.0 nightly 71
- Server: Using without an account

- Debug information:
I [corrected the recipe logo here](https://github.com/jonhil/recipe-franz-mailbox.org/pull/4) following [the advice here](https://github.com/getferdi/recipes/issues/16).

**Comment by vraravam** [comment]
Fixed in https://github.com/getferdi/recipes/pull/578
