### ISSUE TITLE
GMail logo vertically stretched

### ISSUE THREAD

**Issue by keunes** [getferdi/ferdi#1584]
**Bug description:** The GMail logo is vertically stretched in the vertical 'app bar' on the left.

**Steps to reproduce:** click 'add service' and find 'Gmail' - notice that the logo is correctly shaped. Then proceed to actually add the service, and see that the logo is vertically stretched.

**Expected behavior** Display the same logo version as in the services overview.

**Screenshots**
![Schermafdruk van 2021-07-02 00-27-43](https://user-images.githubusercontent.com/11229646/124196490-d106cf00-dacc-11eb-8772-daeb3fbab1d6.png)

**Environment:**

- Operating System: Ubuntu
- Ferdi Version: 5.6.0 nightly 71
- Server: Using without an account

- Debug information:

**Comment by vraravam** [comment]
Fixed in https://github.com/getferdi/recipes/pull/577
