### ISSUE TITLE
Windows Taskbar Icon is choppy

### ISSUE THREAD

**Issue by Stanzilla** [getferdi/ferdi#159]
**Describe the bug**
On Windows 10, the taskbar icon is *very* fuzzy around the edges 

**To Reproduce**

1. Install Ferdi

**Expected behavior**
Clear circle
**Screenshots**
![image](https://user-images.githubusercontent.com/75278/67580595-dda72180-f746-11e9-863b-552be30fd5ea.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10
- Version [e.g. 22] 5.4.0

**Additional context**

**Comment by Gaboris** [comment]
Yeah, it's the same on Win7 as well.

There was probably some problems while converting the Franz icon or if this is a completely new icon then some settings are mismatched.

**Comment by vantezzen** [comment]
It is a new icon so I exported it wrong. It looks like `build-helpers/images/win-app-icon.ico` is 64x64 in Franz and 32x32 in Ferdi - that may be the issue.
