### ISSUE TITLE
Can't add Mastodon service

### ISSUE THREAD

**Issue by keunes** [getferdi/ferdi#1593]
**Bug description:** I cannot add the Mastodon service because clicking on it doesn't load the 'edit & save' view.

**Steps to reproduce:**

1. Go to 'Add new service'
2. Search for 'Mastodon'
2. Click on 'Mastodon'

**Expected behavior** Open 'Add & Save' screen

Instead, a spinner is shortly displayed, then the search results are displayed again.

**Screenshots**

**Environment:**

- Operating System: Ubuntu
- Ferdi Version: 5.6.0 nightly 71
- Server: Using without an account

**Comment by keunes** [comment]
Just noticed that the same is true for the Element service

**Comment by vraravam** [comment]
There was a bug in the nightly v71/72/73 - which was fixed in v74. Please try any nightly release either 74 or later. This issue should have been resolved. In fact, I was able to add Mastodon and sign into my company's federated service just now.

**Comment by keunes** [comment]
Will give it a try tomorrow

**Comment by keunes** [comment]
Don't think it was a question as much as it was, simply, a bug report. But one that is about a now fixed issue (using nightly 78). Thanks! :)
