### ISSUE TITLE
Unable to add a new service after nightly 72

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1595]
**Bug description:**
When running nightly 72, I am able to search for and add a new service to my registered services. This version corresponds to  [this commit](https://github.com/getferdi/ferdi/commit/6828530f1b7f9f39d43a22b798e8e34d63c658b0). Since nightly v73, this has been erroring out with "Something went wrong".

@mhatvan and @vraravam have made the bulk of changes since then. Will need to review

**Steps to reproduce:**

1. Go to "Add new Service"
2. See error

**Expected behavior**
Able to search for and add new service

**Screenshots**

**Environment:**

- Operating System: macOS Big Sur Monterey
- Ferdi Version: nightly 72/73
- Server: Ferdi

- Debug information:

**Comment by mhatvan** [comment]
I just checked, the "Add new service" workflow works fine in dev which uses 5.6.0-nightly.72

The actual production version of Ferdi that I use is 5.6.0-nightly.73 and is broken.

**Comment by vraravam** [comment]
@mhatvan - if you are buiding from source - (which reports as v72 - because of the hardcoded `version` in `package.json`), its still broken. I am unfortunately unable to start the local dev due to something wrong in `node-gyp`. Please use `git bisesct` to figure out which commit broke it?

The starting commit for this can be: 6828530f1b7f9f39d43a22b798e8e34d63c658b0 - which is where v72 was created from

**Comment by mhatvan** [comment]
I will take a look at it, but not much time right now unfortunately.
Dev works for me even with v73, probably because it is requesting the recipes from localhost rather than `api.getferdi.com`

**Comment by mhatvan** [comment]
Might be related: https://github.com/getferdi/server/issues/52

**Comment by mhatvan** [comment]
Yeah, can confirm that dev breaks the same way when changing the request url for popular recipes.

**Comment by vraravam** [comment]
Found the offending commit - will raise a PR in a few mins after local testing.

**Comment by vraravam** [comment]
Sorry to cause the scare @mhatvan

**Comment by mhatvan** [comment]
That's fine, I like to help out and improve Ferdi ;)
