### ISSUE TITLE
Rocket.Chat tab doesn't display notifications

### ISSUE THREAD

**Issue by mhatvan** [getferdi/ferdi#1599]
**Bug description:**
Rocket.Chat tab doesn't display notifications although there are a lot of channels that have new content.

**Steps to reproduce:**

1. Go to Rocket.Chat tab
2. There are new messages waiting to be read
3. No notification counter on Rocket.Chat tab 

**Expected behavior**
Rocket.Chat tab in Ferdi displays the summed up amount of notifications.

**Screenshots**
![Screenshot from 2021-07-04 11-12-20](https://user-images.githubusercontent.com/16797721/124379718-f1937c80-dcb8-11eb-8f59-a727e0fa88d3.png)

**Environment:**

- Operating System: Ubuntu 21.04
- Ferdi Version: 5.6.0-nightly.73

**Comment by vraravam** [comment]
@mhatvan - could you please raise a PR in the getferdi/recipes repo that fixes this? I don't use rocketChat - and so would not be able to provide a fix. Its basically to do with css selectors and grabbing the numbers that show up in the orange circular callouts.

**Comment by mhatvan** [comment]
Sure Vijay, I will provide a fix when I find time ;)
