### ISSUE TITLE
Update the name and icon of Google Chat (formerly Hangouts Chat)

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [getferdi/ferdi#1615]
As you might have noticed from a number of issues asking for Google Chat to be added ([569](https://github.com/getferdi/recipes/issues/569) [548](https://github.com/getferdi/recipes/issues/548) [534](https://github.com/getferdi/recipes/issues/534)), not everyone knows of the former name or realizes to search for it. This not only creates unnecessary work for you, the maintainers, but also confuses and loses a few users.

If there is a concern that too many users might still refer to it as [Hangouts Chat](https://en.wikipedia.org/wiki/Hangouts_Chat), then see suggestion #1614 

Unimportant trivia:
<details>
Google doesn't make it easy with their rebrandings. When I was looking to add Google Chat to Ferdi I dug through some Wikipedia articles and more to understand the gist of:

- Google Allo
- Google Meet
- Google Voice
- Google Talk
- Google Hangouts
- Google Duo
- Google Chat

...before I learned of the recent rebranding.
</details>

**Comment by vraravam** [comment]
This will be available in the next nightly `v5.6.1-nightly.24`
