### ISSUE TITLE
Could not load services and user information 

### ISSUE THREAD

**Issue by bittner** [getferdi/ferdi#162]
**Describe the bug**
Error message "Could not load services and user information" at the lower end of the Ferdi UI

**To Reproduce**

1. Start Ferdi
2. After a while the message appears
3. Open View > Developer Tools, Network tab
4. See a lot of HTTP 500 status errors going to the following resource
```
/opt/Ferdi/resources/app.asar/api/utils/auth.js:1
```
5. When I click on the Application tab I see the following query:
```
select * from `users` where `id` = 1 limit 1 - SQLITE_ERROR: no such table: users
```
6. In the Console tab there are more details of the error:
```
127.0.0.1:45569/v1/me:1
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```
```
/opt/Ferdi/resources/app.asar/stores/lib/CachedRequest.js:1
Uncaught (in promise)
Response
body:ReadableStream
bodyUsed: true
headers: Headers {}
ok: false
redirected: false
status: 500
statusText: "Internal Server Error"
type: "cors"
url: "http://127.0.0.1:45569/v1/me"
``` 
**Expected behavior**
No Error 500, message should go away.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu GNU/Linux 18.04.3 LTS
- Browser Chromium; Firefox
- Version 5.4.0-beta.4

**Comment by vantezzen** [comment]
Looks like there is a problem with the database of the internal server.
The file is located inside the application userdata folder (`~/.config/server.sqlite` on Linux). Could you please check:
- if the file if readable and writable
- that the file is >=41KB in size (to make sure it isn't empty)

Could you also please try renaming the database file (so the internal server will create a new one) and restart Ferdi? Just to check if the problem is in the database file.

**Comment by tkharo** [comment]
Had the same problem. After update Franz server was replaced with Ferdi server.
@bittner check if you have `https://api.meetfranz.com` or `https://api.getferdi.com` in your settings.

**Comment by bittner** [comment]
The `~/.config/Ferdi/server.sqlite` file is 57344 bytes of size.

The content of that file is:
```python
>>> c.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;").fetchall()
[('adonis_schema',), ('recipes',), ('services',), ('sqlite_sequence',), ('workspaces',)]
```

As for the settings, I had https://api.getferdi.com, I removed that and tried again and now I'm locked out as it seems (I'd have to start over with the accounts). The import at http://localhost:45569/import is also not available. :worried: Setting the value to https://api.meetfranz.com doesn't help.

**Comment by bittner** [comment]
I managed to us the Franz server again by:
1. setting `https://api.meetfranz.com` as Server in the settings
1. log out (restarting alone doesn't help)
1. log in using the Franz server credentials

This may seem logical, but it's not 100% intuitive. -- Well, I'm an idiot: It's even written in the user interface, just below the text field. :roll_eyes: 

Maybe we can help idiots like me by either asking whether to log out immediately (popup?) or by highlighting the hint below the text field after the text field content was changed.

-----

Anyway, the original problem from above still persists (e.g. when I choose "Use Ferdi without an Account" on the login screen).

I noticed, the import is now available [from a public URL](https://api.getferdi.com/import) via a link on the login screen. nice!

**Comment by bittner** [comment]
Somehow the problems I face I somewhat related to workspaces. Or at least that feature is severely affected. I originally added another Slack team and wanted to add that to a specific workspace. That didn't work and the above mentioned messages started coming up (or maybe they were there before, I don't exactly remember). Now I figured the entire Slack team was gone; I added it again and tried to add it to the workspace; result: some error message; then I saw all the workspaces were gone. :face_with_head_bandage:

**Comment by vantezzen** [comment]
I looked through the changes between beta.2 and beta.4 again and I think I found your issue:
In order to implement the user settings feature, we had to add the table `users` to the local database. 
New users would have this table in their database but as you already used the "Use Ferdi without an Account" feature on beta.2, your local database wan't updated. We'll have to look into building a migration assistant for the internal server that will automatically update the local database as needed.

For now, if you know how to execute SQL commands in an SQLite database you should be able to simply run this command to add the missing table:
```SQL
CREATE TABLE `users` (`id` integer not null primary key autoincrement, `settings` text, `created_at` datetime, `updated_at` datetime)
```

**Comment by markwalkom** [comment]
I was on beta2 and upgraded and had this. When I checked there was a `users` table and even after I created one per the above comments, I still get this error.

**Comment by vantezzen** [comment]
@markwalkom Can you try renaming the database file just to make sure the problem is in the database migration and not the code.

**Comment by markwalkom** [comment]
That "worked", but it removed all my accounts :(

**Comment by vantezzen** [comment]
Of course, it was just for testing. 
To you mind sharing your original database with me for testing? The database contains your services but no service content like your messages. Otherwise I'll try to find the error together with you over GitHub.

**Comment by markwalkom** [comment]
Yeah I can do that, I am https://keybase.io/markwalkom if that helps?

**Comment by vantezzen** [comment]
@markwalkom Can you please revert the move of your old database again (so Ferdi is using your original database) and execute this SQL command in the database:
```
INSERT INTO  "users" ("id") VALUES ('1');
```
and see it it works again?

**Comment by markwalkom** [comment]
That worked @vantezzen! :D

**Comment by vantezzen** [comment]
Ferdi is not only expecting the table "users" to be in the database but also a row with the user ID of 1 to be existent - this row will be used to save the settings.
For this update you'll have to run these two commands yourself, for future updates we'll have to create a migration assistant when making changes to the database structure.

**Comment by vantezzen** [comment]
Ferdi internal-server will now ship with a [database migration wizard](https://github.com/getferdi/internal-server/commit/1a3e86a0d7e6d97f22bf80a43f3eaf46c2d83f06) that should prevent this error from happening in future versions.

**Comment by incace** [comment]
Just updated from 5.4.0 to 5.4.1-beta.1 and lost all my services. I've tried logging out, restarting, no dice. If I view my account on https://api.getferdi.com/user/data, all my services are there and intact. So, I'm not quite sure what's going on or how to fix it. Any ideas?
