### ISSUE TITLE
Google Calendar start in mobile mode instead desktop mode

### ISSUE THREAD

**Issue by JPnux** [getferdi/ferdi#1622]
Google Calendar start in mobile mode instead desktop mode.

Can you force the desktop mode at the startup ?

Dark mode doesn't work for Google Calendar.

Ferdi version in use : deb package of  Ferdi-5.6.0-nightly.77

**Comment by vraravam** [comment]
@JPnux - please see the discussion in #1514 - I have exposed the ability to set the `serviceUrl` by the user for this purpose.

**Comment by vraravam** [comment]
Dark mode fix has been checked in just this morning. Will be present in the next nightly.

**Comment by JPnux** [comment]
> @JPnux - please see the discussion in #1514 - I have exposed the ability to set the `serviceUrl` by the user for this purpose.

Thank you it works. I added my user agent in Calendar parameters.

**Comment by vraravam** [comment]
> Thank you it works. I added my user agent in Calendar parameters.

Can you please post a screenshot of what you mean? I don't understand

**Comment by JPnux** [comment]
![image](https://user-images.githubusercontent.com/47024223/124764532-578c3800-df35-11eb-91a3-66661a8613d1.png)
