### ISSUE TITLE
Hibernation Broken Again (beta 7)

### ISSUE THREAD

**Issue by CptDinosaur** [getferdi/ferdi#1624]
**Bug description:**
Updated to 5.6.0-beta.7
"Enable Hibernation" became disabled for all my services
I reenabled it for the ones I want.

However, those services aren't hibernating after the amount of time I have set.
Also, if I enable "Keep services in hibernation on startup", it's hibernating ALL services, not just those with hibernation enabled. But even then, once opened for the first time, they don't re-hibernate after x amount of time

**Steps to reproduce:**
1. Update to 5.6.0-beta.7
2. Enable hibernation for services
3. They don't hibernate
4. Enable keep services in hibernation on startup
5. Restart
6. All services are hibernating, not just those that have it enabled.

**Expected behavior**
Functioned correctly in 5.6.0-beta.5
I notice the "Starting <service>" dialog is changed too, I assume its some change that was implemented at the same time as the useragents change

1. Services, with hibernation enabled, hibernate after the time defined in the hibernation strategy in settings
2. With "Keep services in hibernation on startup" enabled, only those with hibernation enabled are hibernating on startup

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.6.0-beta.7
- Server: w/o Account

**Comment by vraravam** [comment]
Is this related to #1486 ?

**Comment by CptDinosaur** [comment]
Could be, though that pull request is older than this update

**Comment by vraravam** [comment]
Yes - that's becuase the PR was created much earlier, but the author and the other maintainers had some discussion that is not yet resolved.

**Comment by vraravam** [comment]
This should be in the next nightly: `5.6.1-nightly.3`
