### ISSUE TITLE
pop-up blocker

### ISSUE THREAD

**Issue by thdesous** [getferdi/ferdi#1625]
Hi, I'm using ```Ferdi (Version: 5.5.0 (x64), Electron: 8.2.3, Node.js: v12.13.0, Platform: linux)```. When you click on a link from any website, through the Gmail - Tasks service, a poup-up message is displayed:
> Message
 A pop-up blocker may be preventing the app from opening the page. If you have a pop-up blocker, try disabling it to open the window

I currently use the ```Brave browser - Version 1.26.74 Chromium: 91.0.4472.124 (Official version) 64 bits```.

How can I add an exception for Ferdi, is there any site to add to Brave, or extension?

Thanks.

**Comment by vraravam** [comment]
Sorry - we are no longer supporing v5.5 - that is too old, and lots of new changes have taken place.
We just released the latest beta (which I can assure you : is very stable, and we are about to do a public GA release).

Please download the beta from [here](https://github.com/getferdi/ferdi/releases) - and report back.

**Comment by urielsalis** [comment]
I have the same issue in v5.5.0 and v5.6.0-beta.7, any link in gmail results in that message

**Comment by vraravam** [comment]
great! Thanks for the tip @urielsalis - that was the reason for exposing this functionality! 

@thdesous : Can we close the issue after you confirm the same?

**Comment by thdesous** [comment]
@vraravam I updated to the informed version, it is now working. Thank you very much.
