### ISSUE TITLE
Latest beta: Discord - pasted images won't upload

### ISSUE THREAD

**Issue by manavortex** [getferdi/ferdi#1630]
**Bug description:**
Pasted images fail to upload on Discord. This was working on 5.6.0-nightly.76 (same computer)

**Steps to reproduce:**

1. Add a Discord service, go to a server or DM
2. Copy an image file to clipboard
3. Paste the image file (via cmd+V or right-click/paste)

**Expected behavior**
The image should upload automatically and embed in the channel or DM. This used to be the case in 5.6.0-nightly.76, which I updated after our conversation on https://github.com/getferdi/ferdi/issues/1113

**Environment:**
Version: 5.6.0-beta.7
Electron: 13.1.6
Chrome: 91.0.4472.124
Node.js: 14.16.0
Platform: macOS Mojave
Arch: x64
Build date: Wed Jul 07 2021 15:03:58 GMT+0200 (Central European Summer Time)
Git SHA: 60fe1510
Git branch: release

Service: Discord

**Comment by mhatvan** [comment]
Cannot reproduce this with v5.6.3-nightly.3 on Ubuntu.

Pasting a .png image with `Strg+V` opens up an upload image dialog and gives you the option to add a comment. After clicking "Upload" it is then saved in the discord DM.

@manavortex Do you still experience this issue?

**Comment by manavortex** [comment]
Not anymore! Thank you!
