### ISSUE TITLE
View services side by side

### ISSUE THREAD

**Issue by tapia** [getferdi/ferdi#1631]
I recently got a 32" screen, and when I make Ferdi fullscreen there's A LOT of wasted space. It would be awesome if it I could see my services side by side (in columns?), instead of having them in different tabs.

**Comment by niutech** [comment]
Great idea! This is how it looks like in Rambox:

![Rambox tiling](https://rambox.pro/images/img-02.png)

**Comment by vraravam** [comment]
We would really appreciate any help in implementation. At the moment though, we do not have the bandwidth to implement this feature.

**Comment by niebloomj** [comment]
Oh man this is a great idea.

**Comment by vraravam** [comment]
Please remember that we are comparing to a paid application, whereas there are a handful of active voluntary contributors.

**Comment by vantezzen** [comment]
Kind of (?) duplicate of #893 - can we close one issues as they are essentially requesting the same thing?

**Comment by vraravam** [comment]
Yes @vantezzen - lets close this card and track conversations in the previous one.
