### ISSUE TITLE
Time in Service is Incorrect

### ISSUE THREAD

**Issue by Snayff** [getferdi/ferdi#1632]
**Bug description:**
The time shown in the different services is incorrect, perhaps reflecting a different time zone. 

**Steps to reproduce:**
1. Install Ferdi.
2. Add Android Messages and Discord services. 
3. Login to both services. 
4. Send a message in either service. 
5. Note time shown.

**Expected behavior**
Expected the time shown in Ferdi to reflect the time on my device. 

**Screenshots**
Message just sent in Android Messages service. Note the time delivered in the service (1:58 AM) and the actual time (09:58).
![image](https://user-images.githubusercontent.com/23128268/125157880-50764d00-e122-11eb-8589-85c69d081413.png)

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.5.0
- Server: Ferdi

Debug information:
Clicked Copy Debug Information and nothing happened. Clicked Publish Debug Information and a pop up presents but clicking "Accept and publish" doesnt trigger any action and the pop up remains.

**Comment by vraravam** [comment]
@Snayff 
1. Unfortunately, this is not something that is controlled by Ferdi.
2. Since v5.5 of Ferdi is quite old, we are no longer able to support it. Please move to the latest beta found [here](http://github.com/getferdi/ferdi/releases) - and test out the same service/functionality.

We can try to help - if this happens in the new version.

**Comment by Snayff** [comment]
@vraravam thank you for coming back to me. I have updated to 5.6.0-beta.7 and the same issue is present. Any suggestions?

**Comment by vraravam** [comment]
Not a problem - I was just about to type this explanation!

Thanks for trying out Ferdi. We are very close to releasing the next public version 5.6.0 with lots of new features. Exciting times!

**Comment by Snayff** [comment]
Ferdi is much better than the last app I used (Rambox) - excited for the
next release. I am finding that some services are not triggering pop ups,
is that as expected?

**Comment by vraravam** [comment]
No - that should not be the case. Please log a separate bug for that (if its a pattern). If not a pattern, then please log 1 per issue.

**Comment by Snayff** [comment]
Will do, thank you. Should that be on the service/recipe or on the main
ferdi repo?

**Comment by vraravam** [comment]
In the `recipes` repo please.
