### ISSUE TITLE
Shortcut to disable a service

### ISSUE THREAD

**Issue by LiamMoy** [getferdi/ferdi#1636]
**Is your feature request related to a problem? Please describe.**
Keyboard shortcuts for common actions are useful. If an action exists in a context menu then that suggests that it deserves a shortcut.

**Describe the solution you'd like**
A shortcut to disable the currently selected service.

**Describe alternatives you've considered**
This feature already exists via the context menu but a shortcut would be very useful for some users that wrangle huge numbers of services.

Cheers

**Comment by vraravam** [comment]
@LiamMoy - could you please suggest what shortcut would work for you? I can take a stab at this today

**Comment by mhatvan** [comment]
Closed via https://github.com/getferdi/ferdi/pull/2148
