### ISSUE TITLE
Reset password lock

### ISSUE THREAD

**Issue by Jostino** [getferdi/ferdi#1639]
There are any way to reset the password lock?

I've configured the password lock but now it's not recognize from ferdi.

I unistalled many times but doesnt work to reset completely the app.

I'm on manjaro system.

**Comment by Jostino** [comment]
> 1. You can delete the whole Ferdi profile folder (or)
> 2. You can edit the `<ferdiProfile>/config/settings.json` file, and change the value for: `lockingFeatureEnabled` to `false`.
> 
> Either of these will allow you to continue using Ferdi. The first one also wipes out all the data, but the 2nd one is a backdoor to get re-entry (afaik) even if the password is set.

I've follow the method 2. but after that the app still open with the password.
Have I missed something?

**Comment by vraravam** [comment]
hmm - I have been able to successfully bypass the security on my macos with the latest nightly build by following option 2.  I am not logging into any online account for Ferdi - its the "use ferdi without a login" mode.

**Comment by Jostino** [comment]
Using the button unlock without inserting any password worked.

**Comment by vraravam** [comment]
> Using the button unlock without inserting any password worked.

This seems like a different bug ie a password should not be bypassable from the ui.

**Comment by vraravam** [comment]
Closing since the main issue has been fixed with a workaround. Further discussions about the strength of the password can be continued in the discussion topic #1640
