### ISSUE TITLE
Pasting text from clipboard without formatting (via Ctrl+Shift+V) inserts text twice

### ISSUE THREAD

**Issue by MurzNN** [getferdi/ferdi#1644]
**Bug description:**
When I try to paste text from clipboard without formatting (via Ctrl+Shift+V) on Ubuntu Linux, Ferdi inserts text twice, one after another. This happens with all services (GMail, Element, Slack, VK, etc).

In other Electron apps and Chromium browser this hotkey works well, without duplicating pasted text.

**Steps to reproduce:**

1. Copy to clipboard some formatted text, for example "One two three".
2. Paste it on any textfield inside Ferdi service, using "Ctrl+Shift+V" hotkey.
3. You will see the pasted text twice: `One two threeOne two three`

**Expected behavior**
Pasted text should appear one time.

**Environment:**

- Operating System: Ubuntu 20.04 with KDE 5.22
- Ferdi Version: 5.6.0-nightly.68

**Comment by Nikitoring** [comment]
Yes, I have this problem In OS Linux Mint 20.2(Uma)
Ferdi version 5.6.0-beta.6

**Comment by kyle-ds** [comment]
Not sure if this is text specific. Pasting an image to Whatsapp on Windows 20H2 (19042.1083) will also double paste the image.

Ferdi 5.6.0-beta7.

![image](https://user-images.githubusercontent.com/51097593/125997902-3bfdebb3-77c0-45b0-8385-eda954d7c0cd.png)

**Comment by vraravam** [comment]
Not a fix, but a workaround: https://github.com/meetfranz/franz/issues/1466#issuecomment-572035222

**Comment by vraravam** [comment]
I tried this on macos - and I dont experience the same behavior. Tried with both image-data in the clipboard and other formatted text from Word.

**Comment by MurzNN** [comment]
Maybe fix like https://github.com/atom/atom/pull/1983 can fix problem with Ferdi to?

**Comment by vraravam** [comment]
@MurzNN - that is not a definitive fix. It has other consequences as the other posters also claim.

btw - I was also researching whether there are somehow 2 different listeners to `Ctrl+Shift+v`- but since this doesn't seem to happen on a mac, I'm unable to test.

**Comment by stnkl** [comment]
I have the same problem on Windows 20H2 with Ferdi 5.6.0-beta.8 when pasting images into WhatsApp or Telegram using only Ctrl+V.

For text it seems to only happen when the text actually contains formatting (e.g. by copying code from within VSCode).

**Comment by stnkl** [comment]
First of all: It looks like the copy/paste/etc. menu item functionality is broken. Clicking them has no effect for me whatsoever.

Regarding this issue: It appears like the `click` event of a `MenuItem` gets triggered when pressing the accelerator/shortcut ([source](https://www.electronjs.org/docs/api/menu-item#menuitemclick)) which I was able to confirm. So removing the click events entirely fixes the problem but would break the menu item click behavior (which is currently broken anyways as mentioned above). Ideally the click event should distinguish between the keyboard event and click event which I was not able to figure out how to do elegantly.

Another way to fix this is to add `role: 'pasteAndMatchStyle',` [here](https://github.com/getferdi/ferdi/blob/419933f6505caf4c5e685f8436b1ff735185e55a/src/lib/Menu.js#L592) and `role: 'paste',` [here](https://github.com/getferdi/ferdi/blob/419933f6505caf4c5e685f8436b1ff735185e55a/src/lib/Menu.js#L585). This approach would not come with any downsides as far as my testing went.

I could open a PR for the latter fix but in both cases I am not sure about other implications this fix could have so I would rather leave it for discussion here for now.

**Comment by vraravam** [comment]
@stnkl - great find! Please raise the PR!
