### ISSUE TITLE
CRX extensions and UserScripts

### ISSUE THREAD

**Issue by warshell** [getferdi/ferdi#1647]
Hello ! As Ferdi is chrome based, the best would be .CRX extensions, but it would be too much, scripts are cool as they are like extensions. The idea is to implement a userscripts (like greasemonkey, tampermonkey etc )

This would really expand a possibility of software to a new level

**Comment by vraravam** [comment]
Thanks - but, closing this ticket. Please continue all conversations related to extensions support in #113
