### ISSUE TITLE
Enabling Password Lock without an account leads to inoperable software

### ISSUE THREAD

**Issue by fanis** [getferdi/ferdi#1648]
**Bug description:**
Enabling Password Lock when not using an account brings up multiple issues: 
- cannot specify the password because the settings dialog doesn't open
- no guidance of where to go to actually unlock the program

**Steps to reproduce:**

1. Use Ferdi without an account
2. Go to Settings
3. Toggle to enable the "Enable Password Lock"
4. The Settings dialog disappears without letting you define a password.
5. Also there is no indication of where to input a password to unlock it
6. Clicking on Login at the bottom left seems to reload the program and brings up a password field to unlock it
7. When entering the password (I specified it in settings.json), I get the splash screen that asks me to Create a free account or login to one, or use Ferdi without an account.
8. Clicking on "Use Ferdi without an account" loads my enabled services (reloads them)
9. Clicking on Settings shows the dialog is missing/broken and you cannot disable Password Lock.

**Expected behavior**
A new password input field should appear to let you specify a password and then a button to Save your setting.
When locked, the software should have a single centered password input field and a button to Unlock.
When entering the correct password, the software should "unlock" without reloading the services which takes time.

**Screenshots**
Click on Settings
<img width="538" alt="2021-07-15 10_49_02-Ferdi - Messenger" src="https://user-images.githubusercontent.com/562545/125752310-98324c34-3eca-47a5-a16e-59f6628c819a.png">

As soon as you Toggle the Password Lock the dialog disappears:
<img width="538" alt="2021-07-15 10_49_14-Ferdi - Messenger" src="https://user-images.githubusercontent.com/562545/125752358-a08d8e98-02c8-4e23-b90c-4eab569d2821.png">

After entering your password (specified in settings.json) under Login
<img width="538" alt="2021-07-15 11_04_58-Ferdi" src="https://user-images.githubusercontent.com/562545/125752487-13b95637-588d-44aa-87a0-e042aca681a5.png">

It asks you again if you want to create/login to an account or to use without an account
<img width="538" alt="2021-07-15 11_05_03-Ferdi" src="https://user-images.githubusercontent.com/562545/125752533-8cdd7ebe-2d0f-4b60-a9e4-31b29ec2a07b.png">

Clicking "Use without an account" brings up your services (reloaded), but the Settings menu still doesn't work.
<img width="538" alt="2021-07-15 11_05_13-Ferdi - Messenger" src="https://user-images.githubusercontent.com/562545/125752589-52ce99b4-1e30-442f-839c-d84a41863621.png">

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.5.0 (x64)
- Server: Using without an account 

- Debug information:

```
{"host":{"platform":"win32","release":"10.0.19042","screens":[{"id":2528732444,"bounds":{"x":0,"y":0,"width":1920,"height":1080},"workArea":{"x":0,"y":0,"width":1920,"height":1050},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1050},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":2779098405,"bounds":{"x":1920,"y":0,"width":1920,"height":1080},"workArea":{"x":1920,"y":0,"width":1920,"height":1050},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1050},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"discord","version":"1.1.3"},{"id":"mattermost","version":"1.2.1"},{"id":"messenger","version":"1.1.0"},{"id":"skype","version":"1.3.0"},{"id":"whatsapp","version":"2.0.3"},{}],"devRecipes":[],"services":[{"id":"b92ae7b2-cfc3-49ba-9a30-7c0dab84a803","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"54fead88-aa21-4330-b5ac-989edda71a33","recipe":"skype","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"eac3f5d6-d049-459f-ab71-3b3391d47719","recipe":"mattermost","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"fd0e2e17-120e-40eb-812a-3ba05fab593b","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"9a66d6c3-76c1-4b6a-a518-050332708aff","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"85d439ae-562e-48ba-9da6-1a97f42251df","recipe":"messenger","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"}],"workspaces":[],"windowSettings":{"width":1075,"height":912,"x":733,"y":74,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":false,"spellcheckerLanguage":"en-us","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":true,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":false,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":"80","iconSize":"20","sentry":false,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}
```

**Comment by vraravam** [comment]
hi @fanis - thanks for trying out and using Ferdi.

Unfortunately, v5.5 is *quite old*. We are very close to releasing v5.6 and will only be able to support v5.6 at this time.

The latest nightlies (found [here](http://github.com/getferdi/nightlies/releases)) are quite stable and might solve your problem. Please do try the latest nightly for your OS and architecture. And if this is still a problem, please do get back to us. IF we don't hear back from you, I will assume that your issue is solved, and we will close this ticket in a couple of days. Thanks once again for your patronage of Ferdi!

**Comment by fanis** [comment]
Hi @vraravam , thank you for getting back to me so quickly. I will check out the latest nightlies, but please note that I downloaded 5.5 from https://getferdi.com/download assuming it's the current stable version since it's the only one offered there.

Perhaps the messaging on that page should change to reflect that 5.5 is old and unsupported, or hurry up with 5.6 :)

**Comment by vraravam** [comment]
Yes - that is a known issue - since new comers to this app download the old version - and we have to revise their understanding when they log bugs. Or worse still, they get put off by the buggy software and leave Ferdi without getting in contact with us!

I will look to see how this can be accomplished (unfortunately, I just joined the contributors team, and don't have all the knowledge or the permissions to deploy the website code yet).

cc @kytwb - if you can update the website please?

**Comment by fanis** [comment]
Trying the latest nightly 5.6.0-nightly.81, this issue is fixed there so I will close it.
