### ISSUE TITLE
Spell checking preferences not applied

### ISSUE THREAD

**Issue by marcelbrode** [getferdi/ferdi#1651]
**Bug description:**
Spell check is enable by default, ignoring its settings

**Steps to reproduce:**
1. Setup Ferdi to disable spell check
2. Close the Application
3. Restart the Application
4. Use a Service (for example Discord) and type something correct

**Expected behavior**
No Spell check / red lines

**Screenshots**

**Environment:**

- Operating System: Ubuntu 16.04
- Ferdi Version: 5.5.0
- Server: Ferdi, using without account

- Debug information:
Re- and enabling the spell check option do switch it off again, so I guess the preferences aren't loaded correctly

**Comment by vraravam** [comment]
@marcelbrode - Unfortunately, we are not in a position to support v5.5 since its quite old. Please try the latest nightlies (quite stable - we are very close to releasing the public GA release soon) from [here](http://github.com/getferdi/nightlies/releases) - and report back.

**Comment by marcelbrode** [comment]
Ah, I see. So the nightly build is way further :D 

Got the nightly build an d the problem seems to be fixed. Thanks for your support :+1:

**Comment by vraravam** [comment]
Glad to be of help! and Thanks for supporting Ferdi with your testing and logging of bugs - really appreciated!
