### ISSUE TITLE
Facebook/Messenger video and audio call does not work.

### ISSUE THREAD

**Issue by zelop81** [getferdi/ferdi#1652]
**Steps to reproduce**

1. Open up messenger on Ferdi.
2. Try to start a video or audio call.
3. Does not work.

**Expected behavior**

Should open up a window on internet browser for video and audio call.

**Actual behavior**

After clicking, nothing happens on Messenger.

**ENVIRONMENT**

Ferdi: v5.6.0-beta.7
OS: win32
Arch: x64
Windows 10

**Comment by vraravam** [comment]
As a workaround, can you try by right-clicking on the link (to start a video or audio call)?
Once this context menu opens up, please select "open in ferdi" - and then report back what happens.

I am not in FB Messenger - and so will only be able to help by remote debugging and you reporting the exact behavior. else, some other contributor will have to supply a fix/workaround.

**Comment by vraravam** [comment]
Also - please try to override the user-agent for Messenger in the service-specific settings. Use the value that represents the latest Chrome for your OS. Does thiat fix the issue?

**Comment by zelop81** [comment]
The call is already working in version 5.6.0-beta.8.

**Comment by vraravam** [comment]
Thanks for confirming @zelop81 . I'm closing this ticket based on that status. btw - the stable 5.6.0 was released a few weeks ago, and there's a newer version of Ferdi (nightlies) that got released which you might want to try out.
