### ISSUE TITLE
Ferdi is always crashing on second launch

### ISSUE THREAD

**Issue by pztrn** [getferdi/ferdi#166]
I'm on 5.4.0-beta.4 and macos 10.15.

When I start ferdi for first time - everything is okay, I can login to my self-hosted Ferdi server and use synced configuration.

When I stop it and start again - PSoD (purple screen of death :D) with "Something went wrong" label appeared. I cannot use Ferdi anymore until I've remove app's data.

[Logs from devtools](https://github.com/getferdi/ferdi/files/3776112/ferdi-traces.log)

And... third launch was successful! So it is crashing only on second launch. I've successfully reproduced it on my machine with identical logs.

**Comment by vantezzen** [comment]
The only error I can see from your logs is a problem with the announcement. I have now updated the announcement send by the server which may have resolved this issue.

**Comment by pztrn** [comment]
Tried 2 times, yes, it is fixed now :)

**Comment by Rihcus** [comment]
Having this issue on ferdi upon a log out it takes 3 attempts to open the ferdi app image
