### ISSUE TITLE
Whatsapp doesn't work on Ferdi 

### ISSUE THREAD

**Issue by janstieler** [getferdi/ferdi#1661]
**Bug description:**
Whatsapp doesn't work with this version of chrome. It will have chrome version 60+.

**Steps to reproduce:**
Add whatsapp to Ferdi.

**Expected behavior**
Whatsapp opens.

**Screenshots**
![Bildschirmfoto 2021-07-18 um 18 32 29](https://user-images.githubusercontent.com/754880/126075037-28bdb072-1937-44a6-a5c3-0151801fb119.jpg)

**Environment:**

- Operating System: macOS 11.4 (20F71)
- Ferdi Version: 5.5.0 (5.5.0.2116)
- Server: Ferdi

- Debug information:
[Debug Information](https://pastebin.com/xzanVPpn)

**Comment by vraravam** [comment]
Please upgrade to the latest `5.6.0` that just got released a few mins ago. Whatsapp should work.

**Comment by janstieler** [comment]
Thanks!
