### ISSUE TITLE
Shortcut to Toggle main window

### ISSUE THREAD

**Issue by gustavotrott** [getferdi/ferdi#1663]
Hello,
I couldn't find if this options is available already.

I would like some way to create a shortcut to Toggle main window to Show/Hide Ferdi quickly!
I use other Electron apps that I can configure it thought a `keymap.cson`:
```
'global':
  'ctrl-shift-x': 'application:toggle-main-window'
```
It minimizes to tray or restore.
This option would improve a lot the productivity. :smile:

**Comment by tubbadu** [comment]
I use [this script](https://github.com/tubbadu/anyToggle) to toggle ferdi and other applications (Qalculate for example), it could be done better but it works for me!

**Comment by gustavotrott** [comment]
> I use [this script](https://github.com/tubbadu/anyToggle) to toggle ferdi and other applications (Qalculate for example), it could be done better but it works for me!

Thanks @tubbadu 
I installed here and I think it will help! :smile: 
I would like to minimize to tray.. but anyway if I can restore it helps!

**Comment by mhatvan** [comment]
Minimize to tray works in my case with `Ctrl+M` on Ubuntu. 

If you want to be able to restore the window with a shortcut, that functionality would need to be added.

**Comment by vraravam** [comment]
Also, wouldn't that need to hook into the global keyboard shortcuts at the OS-level? To be clearer, if I have minimized Ferdi to the tray and am working on some other app, but then want Ferdi to open up, the shortcut key will need to be configured at the OS-level to be able to then trigger/open Ferdi. Is that not right?

**Comment by tubbadu** [comment]
> Also, wouldn't that need to hook into the global keyboard shortcuts at the OS-level? To be clearer, if I have minimized Ferdi to the tray and am working on some other app, but then want Ferdi to open up, the shortcut key will need to be configured at the OS-level to be able to then trigger/open Ferdi. Is that not right?

yes you're right, but if only there was a ferdi shell command that rises ferdi (someting like `ferdi --rise` for istance) you will only have to assign it to a global shortcut and voilà

**Comment by gustavotrott** [comment]
> Also, wouldn't that need to hook into the global keyboard shortcuts at the OS-level? To be clearer, if I have minimized Ferdi to the tray and am working on some other app, but then want Ferdi to open up, the shortcut key will need to be configured at the OS-level to be able to then trigger/open Ferdi. Is that not right?

You are right, but Electron can register Global Shortcuts!

https://www.electronjs.org/docs/tutorial/keyboard-shortcuts#global-shortcuts
