### ISSUE TITLE
Invalid password after new update

### ISSUE THREAD

**Issue by serenaneo** [getferdi/ferdi#1672]
**Bug description:**
Ferdi was automatically updated to the latest version. Upon launch, I tried to unlock it as usual with my password however it did not work and I was met with a 'Password invalid' message. I have tried looking for methods to bypass this but not a lot of info as I'm on Mac + I'm unfamiliar with tinkering with the backend of things. My workaround was reinstalling version 5.5.0 and the password worked, but would be great if it worked on 5.6.0 as well.

**Steps to reproduce:**

1. Update Ferdi to 5.6.0
2. Launch Ferdi app
3. Enter password
4. Cannot log in, password invalid error message

**Expected behavior**
Unlocks app

**Screenshots**

**Environment:**

- Operating System: macOS Mojave
- Ferdi Version: 5.6.0
- Server: Ferdi / Using without an account (not sure how to answer this)

- Debug information:

**Comment by vraravam** [comment]
@serenaneo - thanks for posting this. There's a workaround that I have described [here](https://github.com/getferdi/ferdi/issues/1639#issuecomment-879120237) on how to get back into ferdi by wiping out the setting where he password is enforced. I have also started a discussion topic on how to block this backdoor. Please try the backdoor for your purposes, and also participate in the discussion if interested.

**Comment by vraravam** [comment]
@serenaneo - as discussed in [this comment](https://github.com/getferdi/ferdi/issues/845#issuecomment-883287095) - looks like the password hashing was turned on - which broke backwards compatibility.

I'm closing this issue since this is a one-time issue (and we wont be changing the hashing algo anytime soon).

**Comment by sad270** [comment]
Try to:

- Rollback to Ferdi 5.5
- Remove your password
- Update to 5.6
- Set back your password

**Comment by serenaneo** [comment]
> @serenaneo - thanks for posting this. There's a workaround that I have described [here](https://github.com/getferdi/ferdi/issues/1639#issuecomment-879120237) on how to get back into ferdi by wiping out the setting where he password is enforced. I have also started a [discussion topic](https://github.com/getferdi/ferdi/discussions/1645) on how to block this backdoor. Please try the backdoor for your purposes, and also participate in the discussion if interested.

Thank you for this, have looked into it but couldn't find the relevant files on my end. What I did was to go to the application, right-click and 'show package contents' but could not find the profile folder/json file. (Sorry to be a pain, I'm not very savvy...)

Have instead tried @sad270 's method which worked, up until today when I experienced a power cut in my building. After starting up the computer and launching Ferdi, the same invalid password issue comes up again. Did the same thing that worked before  — rolled back to 5.5, except password was invalid on that version, and on 5.4.3, as well.

**Comment by vraravam** [comment]
@serenaneo : Since you are on macos, your Ferdi profile folder is: `~/Library/Application\ Support/Ferdi` - and within this folder, there is a file called `config/settings.json`. You should be able to edit that file, remove the key for `lockedPassword` completely, and set `lockingFeatureEnabled` to `false`.

**Comment by serenaneo** [comment]
@vraravam Got it, thank you very much!
