### ISSUE TITLE
Ferdi starts and shuts down.

### ISSUE THREAD

**Issue by dzigner** [getferdi/ferdi#1673]
**Bug description:**

**Everytime I start Ferdi, it opens, shows my accounts, but then shuts down. This has started happening since yesterday, Monday, Jul 19th 2021.**

**Steps to reproduce:**

**1. Start Ferdi
2. It shuts down**

**Expected behavior**

**Screenshots**

**Environment:**

**- Operating System: Windows 10, 21H1, build: 19043.1110
- Ferdi Version: 5.6.0 - I just installed this yesterday, after the previous version first shut down on me.
- Server:  Ferdi, with account.**

- Debug information:

**It does not stay open long enough for me to copy the debug information.**

**Comment by vraravam** [comment]
@dzigner - thanks for trying out Ferdi. I strongly suspect that you Ferdi profile folder is somehow corrupted. the only way to get Ferdi up-and-running is to delete the Ferdi profile folder and restart Ferdi. Could you please try that and report back?

**Comment by dzigner** [comment]
> @dzigner - thanks for trying out Ferdi. I strongly suspect that you Ferdi profile folder is somehow corrupted. the only way to get Ferdi up-and-running is to delete the Ferdi profile folder and restart Ferdi. Could you please try that and report back?

So I ran the compatibility troubleshooter on the pc, and right now, Ferdi is working with compatibility to Windows 8.
If this also does not work, will try what you suggested.

**Comment by mhatvan** [comment]
Ferdi works as expected for me on windows 10 pro.

Seems workaround was found as well.
