### ISSUE TITLE
Ferdi or Franz

### ISSUE THREAD

**Issue by ammarmalhas** [getferdi/ferdi#169]
May I know what the relationship is between Franz and Ferdi? They seem identical but with different colors, even the account I created in Franz is the same in Ferdi!?
Are they from the same developer and why have two identical apps?

**Comment by vantezzen** [comment]
Ferdi and Franz are similar but not the same.

Ferdi is a [fork](https://en.wikipedia.org/wiki/Fork_(software_development)) of Franz. We (@kytwb and me) were unhappy about how Franz is developing - making more and more features locked behind a paywall. Thanks to Franz being open-source, we could ["Fork"](https://en.wikipedia.org/wiki/Fork_(software_development)) Franz and add various improvements to the software, like removing paywalls and adding new features. You can see a full list of changes we made to Franz at <https://github.com/getferdi/ferdi#ferdi-specific-features>.

@kytwb will also publish a blog article explaining Ferdi in the near future.

**Comment by kytwb** [comment]
Exactly, thanks for explaining @vantezzen! 😄 I have been a bit busy with things in real life but the blog post is coming soon.

**Comment by michal-halenka-datasentics** [comment]
Link has changed:
https://github.com/getferdi/ferdi#what-makes-ferdi-different-from-franz
