### ISSUE TITLE
Teams daily relogin

### ISSUE THREAD

**Issue by kitzler-walli** [getferdi/ferdi#1696]
Teams works great in Ferdi but I have to relogin every day - is there a way to avoid this?

**Comment by vraravam** [comment]
I have just joined a new client where they use MS Teams - and I face the same issue. I am not sure if this can be managed/controlled by Ferdi. For eg, each time I quit Ferdi and get back in, I am forced to relogin with okta. The behavior is the same when I use plain old Firefox or chrome as well - so, its not a Ferdi-related bug, but some setting that the MA Teams admins have setup on the server-side.
