### ISSUE TITLE
MacOS spell check does not work globally in the app

### ISSUE THREAD

**Issue by cereum** [getferdi/ferdi#1707]
**Bug description:**

When I use apps in Ferdi the spell check highlighting does not work. This persists despite changing the settings in the Ferdi settings menu. 

**Steps to reproduce:**

In any service type the word 'greem'- there will be no spell check highlighting.

**Expected behavior**

Ideally spell check would kick in to correct 'greem' to 'green', like it does elsewhere. 
**Screenshots**

**Environment:**

- Operating System: macOS Catalina
- Ferdi Version: 5.6.1 nightly 5
- Server:  w/o an account

- Debug information:

https://pastebin.com/ed0E1BDF

**Comment by vraravam** [comment]
<img width="892" alt="Screenshot 2021-07-30 at 7 24 20 AM" src="https://user-images.githubusercontent.com/69629/127588032-2aa210f4-cf85-4026-81d7-be968b8c9f33.png">

Unable to reproduce - the above is a screenshot of this same GH ticket comment, where I can see the red squiggly underline. I'm on macos Big Sur and the latest nightly - in case that sways the behavior.

**Comment by cereum** [comment]
I swear I am not crazy, but it works now.
