### ISSUE TITLE
Ferdi Todo not available in https://api.getferdi.com and local server

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#171]
**Describe the bug**
Ferdi todo in the Todos tabs is not available anymore if I am not in https://api.franzinfra.com

**To Reproduce**

1. Go to Todos
2. See error (the dropdown is blank)

**Expected behavior**
Normally Ferdi/Franz Todos should appears to be opened.

**Desktop (please complete the following information):**

- OS: Windows 7
- Version: 5.4.0-beta.3

**More info**
When I am not in Franz server the setting for changing the todo server dissapear too

**Comment by Makazzz** [comment]
Should this be feature request instead?

**Comment by vantezzen** [comment]
This is a change on Franz's server that we cannot change. The only thing we could do is change the default Todo Server to something else.

**Comment by Makazzz** [comment]
So like a todo.getferdi.com?

**Comment by vantezzen** [comment]
Either that or a more well-known service like Todoist.

**Comment by Makazzz** [comment]
But I cant choose my todo server without being in franzinfra api

**Comment by vantezzen** [comment]
Oh sorry, I only now understood the problem. Franz/Ferdi 5.4.0 seems to be expecting some new options from <https://api.getferdi.com/v1/features>. If you are using Ferdi's API you should now be able to use Ferdi Todos again - can you check that?

**Comment by Makazzz** [comment]
Its is working now! I can use Franz todo app (or todoist. Thanks.

**Comment by vantezzen** [comment]
By "local server mode" you mean using Ferdi without an account? The local server has had the same incomplete feature list that ferdi-server had, but I fixed it via <https://github.com/getferdi/internal-server/commit/8249d625bbd80498ae18257a52e480d0ebb368c0> - things should work again with the next build.

**Comment by Makazzz** [comment]
Ah ok thanks!
