### ISSUE TITLE
Request for Google login

### ISSUE THREAD

**Issue by zgstyle** [getferdi/ferdi#1716]
Lates Ferdi - 5.60
![ksnip_20210801-181518](https://user-images.githubusercontent.com/574192/127776151-c0f81417-a0b5-4c8e-893c-c477f60a107d.png)
Why do I have to login to my Google account to use Ferdi?
I can understand Google keep needs it, but why Rocketchat, Whatsapp or Skype requires it?

**Comment by alindl** [comment]
Looks like this is the login for the Todo sidebar. It has nothing to do with the services you installed on the left sidebar you mentioned.

**Comment by vraravam** [comment]
Yes - same as what @alindl answered. Closing this ticket.
