### ISSUE TITLE
ToDos are completely gone

### ISSUE THREAD

**Issue by alindl** [getferdi/ferdi#1717]
**Bug description:**

The ToDo sidebar is gone, I can't activate it. The menu bar only shows "(empty)" on clicking the "Todos" element. The shortcut doesn't activate it, the entry in the settings is also completely gone.

**Steps to reproduce:**

Update to v5.6.1-nightly.10.

**Expected behavior**

Having my Todo sidebar, specifically Todoist.

**Environment:**
- OS: Linux 5.13 Arch/EndeavourOS
- Ferdi: 5.6.1-nightly.10
- Electron: 13.1.7
- Chrome: 91.0.4472.124
- Node.js: 14.16.0
- Server: Ferdi, using an account

- Debug information:
```
{"host":{"platform":"linux","release":"5.13.6-arch1-1","screens":[{"id":2785062953156691,"bounds":{"x":0,"y":0,"width":1920,"height":1080},"workArea":{"x":0,"y":0,"width":1920,"height":1080},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"displayFrequency":60,"workAreaSize":{"width":1920,"height":1080},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.1-nightly.10","electron":"13.1.7","installedRecipes":[{"id":"discord","version":"1.1.4"},{"id":"element","version":"1.0.4"},{"id":"facebook","version":"1.0.2"},{"id":"franz-custom-website","version":"1.0.4"},{"id":"github","version":"2.0.1"},{"id":"gmail","version":"1.3.9"},{"id":"irccloud","version":"1.0.2"},{"id":"messenger","version":"1.1.2"},{"id":"proton-mail","version":"1.2.2"},{"id":"roundcube","version":"1.0.2"},{"id":"slack","version":"1.0.17"},{"id":"telegram-react","version":"1.1.2"},{"id":"todoist","version":"1.2.1"},{"id":"toggl","version":"1.0.2"},{"id":"trello","version":"1.0.3"},{"id":"tutanota","version":"1.0.1"},{"id":"whatsapp","version":"3.0.2"},{}],"devRecipes":[],"services":[{"id":"ca8b3596-7262-4dba-b12a-573a970660e9","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"e4f3f3e2-6a2b-4886-ac23-7f7bee9640c8","recipe":"todoist","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"b7c97f18-86d4-4c1d-87f9-e7d122be681d","recipe":"telegram-react","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"88fd7382-d5c1-46df-9e61-239d28becf85","recipe":"toggl","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"0569159f-99fb-4d98-beef-9217969ea8f0","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"9166e18f-9aea-4fc5-ac5b-879a355327f1","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"9a777f06-fd13-4fd3-b32a-ee70adc6612e","recipe":"proton-mail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"69747c3c-e2f6-4a16-a708-43bba19098fb","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"1850dd39-df43-4a21-bac4-9b1a3b117581","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"d4b2f0e0-664e-4f4f-a54d-fa9d5f5e2d28","recipe":"franz-custom-website","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"95176632-31ef-40d1-b206-874880cd06aa","recipe":"trello","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"8d7460aa-4135-45e0-82d2-677f48acd074","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"864c1fc3-1f47-4dd1-9e59-db526a187378","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"0f4360c7-3f18-4d20-9b3e-ba3d133987a8","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"771d416b-9cce-4028-854b-ca54456bc026","recipe":"messenger","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"e363b564-7bc0-4019-845f-0d8e16c1aaad","recipe":"tutanota","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"034e0bdf-6413-4fb3-b089-6a33c17ac8f9","recipe":"element","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"e9a4739e-f726-40b6-84eb-96c10dc69088","recipe":"franz-custom-website","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"3194a70a-78d5-4357-9733-68d4dcfcde3f","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"fc9cd6b6-6897-4980-80b9-5e34209f9215","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"bc612d9e-45bd-464c-9845-9fa37ddac7dd","recipe":"roundcube","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"a43bb37f-6433-41b5-a4dc-2b87e935ec80","recipe":"roundcube","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"fe62a943-3531-4f0b-89be-757415fe65b3","recipe":"facebook","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"00b22af4-fa4d-484b-acfe-4e704dc33e37","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"254c8277-00bc-49f9-8be7-0add5c8caac1","recipe":"github","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"2fc601cd-a61f-43e5-913a-cfa6c2c1b546","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"9d09656a-186c-43da-98d0-5f3e9827e45f","recipe":"gmail","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"6a543db9-95b0-4a69-929e-c4add89d5ac7","recipe":"franz-custom-website","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: The prop `stores.app.accentColor` is marked as required in `_class2`, but its value is `undefined`.\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by WithTheme(Jss(_class2)))\n    in WithTheme(Jss(_class2)) (created by inject-WithTheme(Jss(_class2))-with-stores)\n    in inject-WithTheme(Jss(_class2))-with-stores (created by _class2)\n    in _class2 (created by WithTheme(_class2))\n    in WithTheme(_class2) (created by Jss(WithTheme(_class2)))\n    in Jss(WithTheme(_class2)) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in WithTheme(Jss(_class2)) (created by inject-WithTheme(Jss(_class2))-with-stores)\n    in inject-WithTheme(Jss(_class2))-with-stores (created by _class2)\n    in _class2 (created by WithTheme(_class2))\n    in WithTheme(_class2) (created by Jss(WithTheme(_class2)))\n    in Jss(WithTheme(_class2)) (created by _class2)"]},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in WithTheme(_class2) (created by Jss(WithTheme(_class2)))\n    in Jss(WithTheme(_class2)) (created by _class2)"]}],"workspaces":[],"windowSettings":{"width":1894,"height":1005,"x":13,"y":36,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080}},"settings":{"autoLaunchInBackground":false,"runInBackground":false,"reloadAfterResume":true,"enableSystemTray":false,"startMinimized":false,"minimizeToSystemTray":"","closeToSystemTray":"","privateNotifications":false,"clipboardNotifications":false,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"[\"en-US\"]","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"server":"https://api.getferdi.com","predefinedTodoServer":"https://todoist.com/app","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":false,"hibernationStrategy":"3600","wakeUpStrategy":"300","inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#268bd2","serviceRibbonWidth":"68","iconSize":"20","sentry":false,"nightly":false,"navigationBarBehaviour":"never","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"serviceLimit":5,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isServiceProxyEnabled":false,"isAnnouncementsEnabled":true,"isWorkspaceEnabled":false},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}
```

**Comment by mrussolo** [comment]
+1 for this issue. It was present yesterday, but today both the settings, menu options and shortcuts are unavailable:.

OS: Windows 10 Pro - 20H2
Ferdi: 5.6.1-nightly.8
Electron 13.1.7


Chrome: 91.0.4472.124

Node.js: 14.16.0

Debug Info:
``` {"host":{"platform":"win32","release":"10.0.19042","screens":[{"id":2528732444,"bounds":{"x":0,"y":0,"width":2560,"height":1080},"workArea":{"x":0,"y":0,"width":2496,"height":1080},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2560,"height":1080},"displayFrequency":75,"workAreaSize":{"width":2496,"height":1080},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":2779098405,"bounds":{"x":-1920,"y":0,"width":1920,"height":1080},"workArea":{"x":-1920,"y":0,"width":1920,"height":1080},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"displayFrequency":60,"workAreaSize":{"width":1920,"height":1080},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.1-nightly.8","electron":"13.1.7","installedRecipes":[{"id":"discord","version":"1.1.3"},{"id":"franz-custom-website","version":"1.0.2"},{"id":"googlecalendar","version":"1.0.3"},{"id":"slack","version":"1.0.17"},{"id":"telegram","version":"3.0.3"},{"id":"whatsapp","version":"3.0.2"}],"devRecipes":[],"services":[{"id":"91a82626-1b20-4689-9c33-a3586d752b15","recipe":"whatsapp","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"2e5dd5da-1d38-48d3-be53-673ae3bf348d","recipe":"whatsapp","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"642c6048-32e1-409e-8789-4758f3d580d9","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"c9b62d93-a601-4483-89e6-beaef7d4c467","recipe":"telegram","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: The prop `stores.app.accentColor` is marked as required in `_class2`, but its value is `undefined`.\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by WithTheme(Jss(_class2)))\n    in WithTheme(Jss(_class2)) (created by inject-WithTheme(Jss(_class2))-with-stores)\n    in inject-WithTheme(Jss(_class2))-with-stores (created by _class2)\n    in _class2 (created by WithTheme(_class2))\n    in WithTheme(_class2) (created by Jss(WithTheme(_class2)))\n    in Jss(WithTheme(_class2)) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.ui` of type `Object` supplied to `_class`, expected instance of `_class`.\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.app` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _class)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.workspaces` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _class)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.app` of type `Object` supplied to `_class`, expected instance of `_class`.\n    in _class (created by inject-_class-with-actions)\n    in inject-_class-with-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _class)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]}],"workspaces":[],"windowSettings":{"width":1295,"height":1088,"x":-1928,"y":0,"displayBounds":{"x":-1920,"y":0,"width":1920,"height":1080},"isMaximized":false,"isFullScreen":false},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":true,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":true,"showDisabledServices":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://todo.microsoft.com/?app#","autohideMenuBar":true,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":true,"scheduledDNDStart":"22:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":"1800","wakeUpStrategy":"300","inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":false,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":"35","iconSize":"20","sentry":false,"nightly":true,"navigationBarBehaviour":"never","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"serviceLimit":5,"hibernate":true,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isServiceProxyEnabled":false,"isAnnouncementsEnabled":true,"isWorkspaceEnabled":false},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}} ```

**Comment by vraravam** [comment]
I have just triggered a build for `5.6.1-nightly.11` - please update to it in a couple of hours.
