### ISSUE TITLE
Problem with color accent

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#172]
**Describe the bug**
If I change my color with darkmode the color is now in the font of the button and the rectangle is still purple. And now the white text is not showing correctly. Only when I hover with my cursor the button, I can see the text.

**To Reproduce**

1. Go to Settings
3. Scroll down to Accent of color
4. Change to something else like #0ef

**Expected behavior**
Normaly it should act like the purple of Ferdi but with another color.

**Screenshots**
Dark mode:
![before](https://user-images.githubusercontent.com/49844464/67805514-85825f00-fa67-11e9-9b89-42bdccdc65b8.PNG)
![after](https://user-images.githubusercontent.com/49844464/67805526-8a471300-fa67-11e9-9b14-ef3b71783dfe.PNG)
![after1](https://user-images.githubusercontent.com/49844464/67805536-8dda9a00-fa67-11e9-8f64-195de6c7571e.PNG)

Light mode:
![beforelight](https://user-images.githubusercontent.com/49844464/67805878-37219000-fa68-11e9-9637-413e7e07e7ee.PNG)
![afterlight](https://user-images.githubusercontent.com/49844464/67805879-37ba2680-fa68-11e9-81fc-1cbe345a6e5d.PNG)
![afterlight1](https://user-images.githubusercontent.com/49844464/67805876-37219000-fa68-11e9-9ba0-57fcdfdda1e8.PNG)

**Desktop (please complete the following information):**

- OS: Windows 7
- Version: 5.4.0-beta.3

**Comment by vantezzen** [comment]
Should be fixed by the next build.
