### ISSUE TITLE
Persistent _Reload Services_ banner

### ISSUE THREAD

**Issue by mfloresVicomtech** [getferdi/ferdi#1720]
**Bug description:**
Since updating to latest v5.6.0 Ferdi is always displaying "Your services have been updated. [Reload Services]" banner at botom of the window. This keeps appearing even after clicking various times and letting Ferdi reload.

**Steps to reproduce:**

1. Update to v5.6.0
2. Click on _Reload Services_ button at the banner.
3. Wait for Ferdi to reload
4. Banner will show again

**Expected behavior**
I would not expect any new banner after services have been reloaded.

**Environment:**

- Operating System: Windows 10 Pro
Version	21H1
OS build	19043.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0

- Ferdi Version: 5.6.0
- Server: Ferdi

<details>
<summary>Debug information:</summary>

> ``` json
> {
> 	"host": {
> 		"platform": "win32",
> 		"release": "10.0.19043",
> 		"screens": [
> 			{
> 				"id": 2528732444,
> 				"bounds": {
> 					"x": 0,
> 					"y": 0,
> 					"width": 1280,
> 					"height": 720
> 				},
> 				"workArea": {
> 					"x": 0,
> 					"y": 0,
> 					"width": 1280,
> 					"height": 680
> 				},
> 				"accelerometerSupport": "unknown",
> 				"monochrome": false,
> 				"colorDepth": 24,
> 				"colorSpace": "{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}",
> 				"depthPerComponent": 8,
> 				"size": {
> 					"width": 1280,
> 					"height": 720
> 				},
> 				"displayFrequency": 60,
> 				"workAreaSize": {
> 					"width": 1280,
> 					"height": 680
> 				},
> 				"scaleFactor": 1.5,
> 				"rotation": 0,
> 				"internal": true,
> 				"touchSupport": "unknown"
> 			},
> 			{
> 				"id": 2779098405,
> 				"bounds": {
> 					"x": 1280,
> 					"y": -360,
> 					"width": 1920,
> 					"height": 1080
> 				},
> 				"workArea": {
> 					"x": 1280,
> 					"y": -360,
> 					"width": 1920,
> 					"height": 1040
> 				},
> 				"accelerometerSupport": "unknown",
> 				"monochrome": false,
> 				"colorDepth": 24,
> 				"colorSpace": "{primaries_d50_referred: [[0.6520, 0.3360],  [0.3210, 0.6100],  [0.1530, 0.0610]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}",
> 				"depthPerComponent": 8,
> 				"size": {
> 					"width": 1920,
> 					"height": 1080
> 				},
> 				"displayFrequency": 59,
> 				"workAreaSize": {
> 					"width": 1920,
> 					"height": 1040
> 				},
> 				"scaleFactor": 1,
> 				"rotation": 0,
> 				"internal": false,
> 				"touchSupport": "unknown"
> 			}
> 		]
> 	},
> 	"ferdi": {
> 		"version": "5.6.0",
> 		"electron": "13.1.7",
> 		"installedRecipes": [
> 			{
> 				"id": "discord",
> 				"version": "1.1.4"
> 			},
> 			{
> 				"id": "feedly",
> 				"version": "1.0.0"
> 			},
> 			{
> 				"id": "gmail",
> 				"version": "1.3.9"
> 			},
> 			{
> 				"id": "hangouts",
> 				"version": "1.1.1"
> 			},
> 			{
> 				"id": "msteams",
> 				"version": "2.0.1"
> 			},
> 			{
> 				"id": "reddit",
> 				"version": "1.0.1"
> 			},
> 			{
> 				"id": "telegram",
> 				"version": "3.0.3"
> 			},
> 			{
> 				"id": "trello",
> 				"version": "1.0.3"
> 			},
> 			{
> 				"id": "whatsapp",
> 				"version": "3.0.2"
> 			},
> 			{
> 				"id": "feedly",
> 				"version": "1.0.0"
> 			}
> 		],
> 		"devRecipes": [
> 			{
> 				"id": "feedly",
> 				"version": "1.0.0"
> 			}
> 		],
> 		"services": [
> 			{
> 				"id": "cb5c18a5-7760-43ae-a2ed-17dcf920e714",
> 				"recipe": "telegram",
> 				"isAttached": true,
> 				"isActive": false,
> 				"isEnabled": true,
> 				"isHibernating": false,
> 				"hasCrashed": false,
> 				"isDarkModeEnabled": true
> 			},
> 			{
> 				"id": "2777bfee-256b-4baa-9e33-5b953a7fd5b4",
> 				"recipe": "discord",
> 				"isAttached": false,
> 				"isActive": false,
> 				"isEnabled": true,
> 				"isHibernating": true,
> 				"hasCrashed": false,
> 				"isDarkModeEnabled": true
> 			},
> 			{
> 				"id": "a8745180-1f44-4d8a-b35a-5949984bee90",
> 				"recipe": "gmail",
> 				"isAttached": true,
> 				"isActive": true,
> 				"isEnabled": true,
> 				"isHibernating": false,
> 				"hasCrashed": false,
> 				"isDarkModeEnabled": true
> 			},
> 			{
> 				"id": "a11df158-c22a-42c4-a771-804a519e8f0f",
> 				"recipe": "msteams",
> 				"isAttached": false,
> 				"isActive": false,
> 				"isEnabled": false,
> 				"isHibernating": true,
> 				"hasCrashed": false,
> 				"isDarkModeEnabled": false
> 			},
> 			{
> 				"id": "229348b8-86d3-4752-9d8b-bcdd6669eef6",
> 				"recipe": "trello",
> 				"isAttached": false,
> 				"isActive": false,
> 				"isEnabled": true,
> 				"isHibernating": true,
> 				"hasCrashed": false,
> 				"isDarkModeEnabled": true
> 			},
> 			{
> 				"id": "0ef2aaac-f877-42ba-b943-b65ffaaea00b",
> 				"recipe": "whatsapp",
> 				"isAttached": false,
> 				"isActive": false,
> 				"isEnabled": true,
> 				"isHibernating": true,
> 				"hasCrashed": false,
> 				"isDarkModeEnabled": true
> 			},
> 			{
> 				"id": "b32f4c9b-8c6c-4e18-85f9-fc95e1fde539",
> 				"recipe": "reddit",
> 				"isAttached": false,
> 				"isActive": false,
> 				"isEnabled": true,
> 				"isHibernating": true,
> 				"hasCrashed": false,
> 				"isDarkModeEnabled": true
> 			},
> 			{
> 				"id": "112c7d15-71f3-4439-abd9-b4c943b0dccf",
> 				"recipe": "hangouts",
> 				"isAttached": true,
> 				"isActive": false,
> 				"isEnabled": true,
> 				"isHibernating": false,
> 				"hasCrashed": false,
> 				"isDarkModeEnabled": true
> 			},
> 			{
> 				"id": "7d5ed351-cb1b-4920-bac4-7de9cb774e16",
> 				"recipe": "feedly",
> 				"isAttached": false,
> 				"isActive": false,
> 				"isEnabled": true,
> 				"isHibernating": true,
> 				"hasCrashed": false,
> 				"isDarkModeEnabled": true
> 			}
> 		],
> 		"workspaces": [
> 			{
> 				"id": "94734c0a-349e-4f72-a1c1-242f9b21897d",
> 				"services": [
> 					"0ef2aaac-f877-42ba-b943-b65ffaaea00b",
> 					"cb5c18a5-7760-43ae-a2ed-17dcf920e714",
> 					"b32f4c9b-8c6c-4e18-85f9-fc95e1fde539",
> 					"2777bfee-256b-4baa-9e33-5b953a7fd5b4",
> 					"7d5ed351-cb1b-4920-bac4-7de9cb774e16"
> 				]
> 			},
> 			{
> 				"id": "3f44c6d1-e2cd-4ee8-818e-3f5ace854d08",
> 				"services": [
> 					"cb5c18a5-7760-43ae-a2ed-17dcf920e714",
> 					"112c7d15-71f3-4439-abd9-b4c943b0dccf",
> 					"a11df158-c22a-42c4-a771-804a519e8f0f",
> 					"229348b8-86d3-4752-9d8b-bcdd6669eef6",
> 					"a8745180-1f44-4d8a-b35a-5949984bee90",
> 					"b32f4c9b-8c6c-4e18-85f9-fc95e1fde539",
> 					"7d5ed351-cb1b-4920-bac4-7de9cb774e16"
> 				]
> 			}
> 		],
> 		"windowSettings": {
> 			"width": 800,
> 			"height": 600,
> 			"x": 0,
> 			"y": 0,
> 			"displayBounds": {
> 				"x": 0,
> 				"y": 0,
> 				"width": 1280,
> 				"height": 720
> 			}
> 		},
> 		"settings": {
> 			"runInBackground": true,
> 			"reloadAfterResume": true,
> 			"enableSystemTray": true,
> 			"startMinimized": true,
> 			"minimizeToSystemTray": true,
> 			"closeToSystemTray": false,
> 			"privateNotifications": false,
> 			"clipboardNotifications": true,
> 			"notifyTaskBarOnMessage": true,
> 			"showDisabledServices": "",
> 			"showMessageBadgeWhenMuted": "",
> 			"showDragArea": false,
> 			"enableSpellchecking": "",
> 			"spellcheckerLanguage": "en-us",
> 			"darkMode": false,
> 			"locale": "en-US",
> 			"fallbackLocale": "en-US",
> 			"beta": true,
> 			"isAppMuted": false,
> 			"enableGPUAcceleration": "",
> 			"serviceLimit": 5,
> 			"server": "https://api.getferdi.com",
> 			"predefinedTodoServer": "https://app.franztodos.com",
> 			"autohideMenuBar": false,
> 			"lockingFeatureEnabled": false,
> 			"locked": false,
> 			"lockedPassword": "******",
> 			"useTouchIdToUnlock": true,
> 			"scheduledDNDEnabled": false,
> 			"scheduledDNDStart": "17:00",
> 			"scheduledDNDEnd": "09:00",
> 			"hibernate": true,
> 			"hibernateOnStartup": true,
> 			"hibernationStrategy": 300,
> 			"inactivityLock": 0,
> 			"automaticUpdates": true,
> 			"showServiceNavigationBar": false,
> 			"universalDarkMode": true,
> 			"userAgentPref": "",
> 			"adaptableDarkMode": true,
> 			"accentColor": "#7367f0",
> 			"serviceRibbonWidth": 68,
> 			"iconSize": 20,
> 			"sentry": false,
> 			"nightly": false,
> 			"navigationBarBehaviour": "never",
> 			"searchEngine": "duckDuckGo",
> 			"useVerticalStyle": false,
> 			"alwaysShowWorkspaces": false,
> 			"todoServer": "isUsingCustomTodoService",
> 			"customTodoServer": ""
> 		},
> 		"features": {
> 			"isSpellcheckerIncludedInCurrentPlan": true,
> 			"needToWaitToProceed": false,
> 			"needToWaitToProceedConfig": {
> 				"delayOffset": 3600000,
> 				"wait": 10000
> 			},
> 			"isServiceProxyEnabled": true,
> 			"isServiceProxyIncludedInCurrentPlan": true,
> 			"isAnnouncementsEnabled": true,
> 			"isWorkspaceIncludedInCurrentPlan": true,
> 			"isWorkspaceEnabled": true,
> 			"isCommunityRecipesIncludedInCurrentPlan": true,
> 			"isSpellcheckerPremiumFeature": false,
> 			"isServiceProxyPremiumFeature": true,
> 			"isWorkspacePremiumFeature": false,
> 			"isSettingsWSEnabled": false,
> 			"isServiceLimitEnabled": false,
> 			"serviceLimitCount": 0,
> 			"isCommunityRecipesPremiumFeature": false,
> 			"isCustomUrlIncludedInCurrentPlan": true,
> 			"isMagicBarEnabled": true,
> 			"isTeamManagementIncludedInCurrentPlan": true,
> 			"isTodosEnabled": true,
> 			"isTodosIncludedInCurrentPlan": true,
> 			"defaultTrialPlan": "franz-pro-yearly",
> 			"subscribeURL": "https://getferdi.com",
> 			"planSelectionURL": "https://getferdi.com",
> 			"hasInlineCheckout": true,
> 			"isPlanSelectionEnabled": false,
> 			"isTrialStatusBarEnabled": false,
> 			"canSkipTrial": true,
> 			"pricingConfig": {
> 				"currency": "$",
> 				"currencyID": "USD",
> 				"plans": {
> 					"personal": {
> 						"monthly": {
> 							"id": "ferdi-free",
> 							"price": 0,
> 							"billed": 0
> 						},
> 						"yearly": {
> 							"id": "ferdi-completely-free",
> 							"price": 0,
> 							"billed": 0
> 						}
> 					},
> 					"pro": {
> 						"monthly": {
> 							"id": "ferdi-still-free",
> 							"price": 0,
> 							"billed": 0
> 						},
> 						"yearly": {
> 							"id": "ferdi-forever-free",
> 							"price": 0,
> 							"billed": 0
> 						}
> 					}
> 				}
> 			}
> 		},
> 		"user": "82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"
> 	}
> }
> ```
</details>

**Comment by vraravam** [comment]
This is an issue on certain users' machines. The guaranteed mechanism to fix this is to go into the ferfi profile folder,  and delete the `recipes` subfolder. Please do this when Ferdi is not running, and then restart Ferdi.

**Comment by mfloresVicomtech** [comment]
> 
> 
> The guaranteed mechanism to fix this is to go into the ferfi profile folder, and delete the `recipes` subfolder.

This worked! Thank you.
