### ISSUE TITLE
Remove White Flash

### ISSUE THREAD

**Issue by monkeylove** [getferdi/ferdi#1733]
**Is your feature request related to a problem? Please describe.**
I'm currently using dark mode. When I switch to another service, I get a white flash before the page loads. Is there a way to stop this?

**Describe the solution you'd like**
When I switch from one service to another, I get a white flash.

**Describe alternatives you've considered**
I can't think of an alternative to this.

**Additional context**
I'm currently using dark mode.

**Comment by vraravam** [comment]
@monkeylove - please specify other details like Ferdi version, OS version, etc.

Also, I am using the latest nightly on a mac, with dark mode, and I dont see this issue at all.

**Comment by monkeylove** [comment]
Sorry, I just checked now, and it only happens while the page is being loaded for the first time, either after starting the program or when waking from hibernation.

I'm currently using ver. 5.60 on Win 10 Home x64, latest build. I'll try beta or nightly.

**Comment by vraravam** [comment]
Yes - when the service is loading the page, there is bound to be some time where the contents are downloaded over the internet. Not sure if this can be fixed or not.

**Comment by monkeylove** [comment]
Similar took place for Firefox (a white flash whenever pages are opened), and was dealt with a one-line command in a CSS file or configuration to change the background color.

https://www.reddit.com/r/firefox/comments/8clww9/changing_background_color_while_loading_webpages/?depth=4

I wonder if something similar can be done for Ferdi.

**Comment by vraravam** [comment]
@monkeylove - thanks for the link. But, this cannot be done at the global level. Each service that you observe this behavior, you can create the css and paste the content in - for that specific service in Ferdi.

**Comment by mhatvan** [comment]
Don't see a viable solution for this except changing the color of the flash which doesn't solve the fact that ferdi simply has to download content.
