### ISSUE TITLE
Clear cache button should not log out of services

### ISSUE THREAD

**Issue by mhatvan** [getferdi/ferdi#1734]
**Is your feature request related to a problem? Please describe.**

The way I understand, clearing cache should be unrelated to cookies/credential state.

Currently it logs out of all services and it is tedious to re-login.

**Describe the solution you'd like**
Only clear cache, stay logged in.

**Describe alternatives you've considered**
Not ever clear cache.

**Comment by vraravam** [comment]
imo - the change will ultimately be here: https://github.com/vraravam/ferdi/blob/develop/src/api/server/LocalApi.js#L49

**Comment by mhatvan** [comment]
Very cool Vijay, I will take a look when I find time, should be easy to do. (Famous last words)
