### ISSUE TITLE
Follow OS' reduced motion setting, or offer a reduced motion option

### ISSUE THREAD

**Issue by Arteneko** [getferdi/ferdi#1735]
**Is your feature request related to a problem? Please describe.**

Right now, the software doesn't respect the OS' reduced motion settings, and doesn't offer any tick to enable this.
For a person impaired with heavy motion sickness, this poses a huge problem.

**Describe the solution you'd like**

Ideally, I would imagine having a select providing three choices:

__Reduced Motion__

- Follow OS settings
- Enabled
- Disabled

**Comment by Arteneko** [comment]
A quick scan through the `src/styles` folder shows that most files creates animations.

All those selectors should be wrapped by a `@media not screen and (prefers-reduced-motion: reduce)` as ideal fix, and override could be done for custom user settings.

```
:: ferdi/src/styles 2 » grep -r 'transition' .
./welcome.scss:    transition: .5s filter, .5s opacity;
./type.scss:    transition: background .5s, color .5s;
./toggle.scss:      transition: all 0.5s;
./tabs.scss:  transition: background $theme-transition-time;
./slider.scss:      -webkit-transition: .2s;
./slider.scss:      transition: opacity .2s;
./settings.scss:    transition: background $theme-transition-time;
./settings.scss:    transition: background $theme-transition-time, color $theme-transition-time;
./settings.scss:    transition: background $theme-transition-time, color $theme-transition-time;
./recipes.scss:  transition: background $theme-transition-time;
./radio.scss:    transition: background $theme-transition-time;
./layout.scss:  transition: opacity .5s ease;
./image-upload.scss:    transition: opacity .5s;
./content-tabs.scss:      transition: background $theme-transition-time;
./colors.scss:$theme-transition-time:      .5s;
./button.scss:  transition: background .5s;
./button.scss:    transition: none;
./button.scss:    transition: background .5s, color .5s;
./animations.scss:  transition: opacity .5s ease-out;
./animations.scss:  transition: opacity .5s ease-out;
./animations.scss:  transition: opacity 300ms ease-in;
./animations.scss:  transition: opacity .25s ease-out;
./animations.scss:  transition: opacity .25s ease-out;
./animations.scss:  transition: opacity .25s ease-in;
./animations.scss:  transition: max-height .5s ease-out;
./animations.scss:  transition: max-height .5s ease-out;
./animations.scss:  transition: all .3s ease-out;
./animations.scss:  transition: all .3s ease-out;
./animations.scss:  transition: opacity 300ms ease-in;
:: ferdi/src/styles » grep -r 'animation' .
./main.scss:@import './animations.scss';
./layout.scss:        animation-name: pulse-danger;
./layout.scss:        animation-duration: 0.75s;
```

**Comment by vraravam** [comment]
thanks @Arteneko - this is a very comprehensive ticket - and the idenfitied code should allow ease of fixes. Would you want to make the changes and raise a PR for the same?

**Comment by Arteneko** [comment]
I'm sadly not in a state to work on this code right now, sorry. If no one picks it up anytime soon and I come around it again, I'll try to do it.

**Comment by Arteneko** [comment]
Testing reduced motion is all about going in your OS' settings and enabling/disabling them, so it depends on your OS.

If you take care of it and make a PR, I can test it for you, too.

**Comment by mhatvan** [comment]
Hey @Arteneko, I prepared a PR which respects motion settings of the OS. 

Please review and test this if it is how you imagined it to be ;)

**Comment by vraravam** [comment]
This should appear in the next nightly v22

**Comment by vraravam** [comment]
Actually, we just discovered an issue in nightly 22, please wait for nightly 23 (in another 12 hrs or so) to get the updated working version.
