### ISSUE TITLE
spellcheck not working - does not show suggestions in v5.6

### ISSUE THREAD

**Issue by dkhokhlov** [getferdi/ferdi#1743]
Spellcheck not working - does not show suggestions in v5.6.
It was working in v5.5.

**Steps:**
1. type text with typo
2. text gets underlined with red
3. right mouse click on text

**Expected:**
- suggestions

**Observed:**
- nothing shows up 

**Environment:**
- Windows 7

**Comment by vraravam** [comment]
This seems to be platform specific. I am able to see the red squiggly lines and the context menu shows up the suggestions on macos.

**Comment by mhatvan** [comment]
Unfortunately there is barely any information about the SpellChecker from Electron: https://www.electronjs.org/docs/tutorial/spellchecker

**Comment by vraravam** [comment]
@mhatvan - looks like [this](https://www.electronjs.org/docs/tutorial/spellchecker#how-to-enable-the-spellchecker) is not how our Ferdi code behaves. I am specifically looking at how `BrowserWindow` is initiated [here](https://github.com/getferdi/ferdi/blob/develop/src/index.js#L183). 

Based on the above, this is my suggestion (to add the following in that initialization struct:
```javascript
spellcheck: settings.get('enableSpellchecking'),
```

Follow on question: How will this behave if a user toggles it in the preferences? Maybe we should warn the user that this is only going to take effect when they restart Ferdi?

**Comment by vraravam** [comment]
If the above suggestion of the addition of the key is right, then we might also need to set the chosen spellChecker language: https://www.electronjs.org/docs/tutorial/spellchecker#how-to-set-the-languages-the-spellchecker-uses

**Comment by vraravam** [comment]
@dkhokhlov - would you be able to test the PR that I just raised? Since I'm on a mac, I am unable to test this myself.

**Comment by dkhokhlov** [comment]
> @dkhokhlov - would you be able to test the PR that I just raised? Since I'm on a mac, I am unable to test this myself.

I can test it. Instructions?

**Comment by vraravam** [comment]
@dkhokhlov - I have merged the PR. If you have the codebase setup to be able to build from the source, please go ahead and create a package from the latest `develop` branch. If not, please wait for the next nightly.

**Comment by mhatvan** [comment]
Can confirm that it works as expected on Linux/Ubuntu with spellchecking on and off now.

**Comment by dkhokhlov** [comment]
How to install zip/tgz from nightly build for testing?

**Comment by vraravam** [comment]
@dkhokhlov - why do you need to bother with zips? There's an msi , and an exe windows installer for ferdi.

**Comment by dkhokhlov** [comment]
link to msi? 
do not see it here: https://github.com/getferdi/ferdi/releases/tag/v5.6.1-nightly.21

**Comment by vraravam** [comment]
The nightlies are in a different repo: https://github.com/getferdi/nightlies/releases/tag/v5.6.1-nightly.21

**Comment by dkhokhlov** [comment]
tested - works.
