### ISSUE TITLE
Google Calendar loads mobile version since update to 5.6

### ISSUE THREAD

**Issue by huang-jy** [getferdi/ferdi#1771]
**Bug description:**
I updated to 5.6.0 and let it reload the services and now each time it loads up, Google Calendar loads the mobile version of the page and I have to click on "Desktop" to get it to switch to the desktop version. I did not change any of the settings between the upgrade.

**Steps to reproduce:**

1. Install 5.5 on Linux
2. Add Google Calendar
3. Login and verify everything works
4. Quit Ferdi
5. Update to 5.6
6. Reload and allow Ferdi to reload services when prompted
7. Google Calendar will load in mobile view.
8. Click "Desktop" to load into desktop view.
9. Reload the service
10. It will display in mobile view again

**Expected behavior**
Persistent desktop view as previous version of Ferdi

**Screenshots**

![image](https://user-images.githubusercontent.com/2756283/129147487-f69e7e30-6f6c-45bc-8d72-d86ed428a8c8.png)

**Environment:**

- Operating System: Linux
- Ferdi Version: 5.6.0
- Server: Ferdi
![image](https://user-images.githubusercontent.com/2756283/129147593-11d346a9-de01-4336-9a53-b10c85b7dcba.png)

- Debug information:

**Comment by vraravam** [comment]
@huang-jy - this has been fixed in #1514 - please upgrade to that or a newer version.
