### ISSUE TITLE
Still getting in-app news from Franz

### ISSUE THREAD

**Issue by MichaelBui** [getferdi/ferdi#178]
![image](https://user-images.githubusercontent.com/1146708/67917449-08282d00-fbd4-11e9-8b1c-d59bbaaf8465.png)
Just want to understand our direction

**Comment by kytwb** [comment]
@MichaelBui This is an announcement from Franz, not Ferdi. We have fixed the issue to make sure Ferdi only gets announcements coming from Ferdi with https://github.com/getferdi/ferdi/commit/73ecb428bb699a2dfb27f88e3d9b803c71d881b7. Sorry for the inconvenience.

**Comment by kytwb** [comment]
To further answer your question, Ferdi will forever be free. We have decided to let the community fund the development if they will/can using [Open Collective](https://opencollective.com/getferdi). No freemium model, purely donation based.

**Comment by MichaelBui** [comment]
Thanks for being free 👍
Anyway, I'm using v5.4.0-beta.4 😅

**Comment by kytwb** [comment]
Thank you for specifying your version. I looked at it a bit more and realized we haven't changed `getLatestNews` to fetch news only from Ferdi. It was still fetching it based on the server/API you use:

https://github.com/getferdi/ferdi/blob/a0ac009c44b210df4d79ffedbdd892fe7302d22e/src/api/server/ServerApi.js#L461

**Comment by kytwb** [comment]
Fixed in d0afab6 and will ship in the next release.  
Thank you for reporting!
