### ISSUE TITLE
Google services not loading properly

### ISSUE THREAD

**Issue by 0x5c4r3** [getferdi/ferdi#1782]
**Bug description:**
Gmail and Google calendar do not load properly. Seems like they load some kind of old design and I did not find any way to get them back as they was. This issue is recent, all was perfectly working with 5.6.0.

**Steps to reproduce:**
Just open up ferdi and browse to the services.

**Screenshots**
GMAIL
![image](https://user-images.githubusercontent.com/16732213/129338008-32df001a-8b75-4cf9-9160-aedc7d247b13.png)
CALENDAR
![image](https://user-images.githubusercontent.com/16732213/129338138-4a243783-4fb2-447a-b328-9d8c0368958f.png)

**Environment:**

- Operating System: arch 5.13.7
- Ferdi Version: 5.6.1-nightly.0 (installed as `ferdi` from AUR using yay)
- Server: Ferdi

**Comment by psyonara** [comment]
I can confirm this. Gmail in particular complains that the browser is not a supported browser, that's why it is defaulting to the HTML version of Gmail.

**Comment by vraravam** [comment]
Lets please have conversations in the same single ticket: #1779
