### ISSUE TITLE
Configurable inactivity lock

### ISSUE THREAD

**Issue by MichaelBui** [getferdi/ferdi#179]
I'm in love with our current Password Lock and it will be great if we can have inactivity lock:
* The app lost focus for a X minutes 
* X is configurable - `0` means disable inactivity lock 
* Should be able to have service notifications with hidden content while being locked

**Comment by kytwb** [comment]
Suggested by @ammarmalhas as well, taking over.

**Comment by ammarmalhas** [comment]
Any news on this? :)

**Comment by kytwb** [comment]
@ammarmalhas I have been really busy lately, will update as soon as I get to work on it 🙏

**Comment by ammarmalhas** [comment]
No worry. I appreciate your efforts and great help. Bless you.

**Comment by vantezzen** [comment]
Added via 5.4.3.

**Comment by ammarmalhas** [comment]
THANK YOU it is working
