### ISSUE TITLE
Announcements not working

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1800]
**Bug description:**
Taking this from the developer tools network tab: The app is somehow invoking: `https://api.github.com/repos/${GITHUB_ORG_NAME}/${ferdiRepoName}/releases/tags/v${version}` - but, such an API is not currently present/supported by Github. Need to investigate and fix. This also affects the `Help > Whats New?` menu

**Steps to reproduce:**

1. Start Ferdi
2. Open the "View Developer Tools"
3. Switch to the Network tab

**Expected behavior**
The `Whats New?` menu works correctly. The announcements from the server are available to the user.

**Screenshots**

**Environment:**

- Operating System: macOS Big Sur
- Ferdi Version: latest nightly 5.6.1-nightly.28
- Server: Using without an account

- Debug information:

**Comment by vantezzen** [comment]
> but, such an API is not currently present/supported by Github

Ferdi is using GitHub's [release info API](https://docs.github.com/en/rest/reference/repos#get-a-release-by-tag-name) which seems to work for the releases, see https://api.github.com/repos/getferdi/ferdi/releases/tags/v5.6.1-beta.1 and includes the correct release `body`. Or am I missing something there?

This might just be a problem with nightly releases like your 5.6.1-nightly.28 as they are only released as tags, not full releases - at least according to https://github.com/getferdi/ferdi/releases.

**Comment by vraravam** [comment]
Thanks for responding @vantezzen .

But, I do see: https://api.github.com/repos/getferdi/nightlies/releases/tags/v5.6.1-nightly.28 - which is released as a full pre-release.

**Comment by vraravam** [comment]
Not sure what changed (maybe that the nightly.14 - which was causing other problems - was deleted), but, now the `Whats new` works fine - but, exposed a different usability bug. I will close this one, and create another for that specific usecase.
