### ISSUE TITLE
'?' > 'Support' link is not working (404 error)

### ISSUE THREAD

**Issue by Tsakatac** [getferdi/ferdi#1806]
**Bug description:**

After clicking on ? > Support in menu bar, we are redirected to [a 404 error page](https://getferdi.com/contact "a 404 error page").

**Steps to reproduce:**

1. Go to menu bar
2. Click on help menu '?'
3. Click 'Support'
4. See 404 error in browser

**Expected behavior**

I think we have to modify the link and point it elsewhere (maybe GitHub).

**Screenshots**
![image](https://user-images.githubusercontent.com/89021195/129589203-ba5c4f86-7c84-4385-a449-8f536f3dc1f4.png)

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.6.0

![image](https://user-images.githubusercontent.com/89021195/129590685-68cfd038-2eb1-402b-a70e-ae60fb5f4d77.png)

**Comment by kytwb** [comment]
https://getferdi.com/contact/

**Comment by kytwb** [comment]
@all-contributors please add Tsakatac for bug
