### ISSUE TITLE
Upgrade button not working

### ISSUE THREAD

**Issue by ammarmalhas** [getferdi/ferdi#181]
**Describe the bug**
Today I got a note that there is a %50 off on upgrade for "Halloween". Pressing the button does nothing!
How do I take advantage of this offer?

**Comment by vantezzen** [comment]
This is an issue we have fixed and will be published via the next update. Ferdi is currently displaying offers that Franz is offering.
As Ferdi doesn't have any premium plans and you won't have to pay for it, this deal doesn't exist for Ferdi.

**Comment by kytwb** [comment]
First part is related to https://github.com/getferdi/ferdi/issues/178.

**Comment by ammarmalhas** [comment]
OK, thank you for clearing this, I thought it was Ferdi selling "Upgrades"!
I await the updated version.
Thanks for all your great work.
