### ISSUE TITLE
Huddle Slack's feature

### ISSUE THREAD

**Issue by pscamino** [getferdi/ferdi#1810]
Hello everyone! It's my first time reporting something here, so I hope to do it well!

Recently, I have added the Slack service to my Ferdi account, and I realized that the new function of Slack "Huddle" is not working correctly. When you are in a huddle and someone shares its screen, you can't open the screen in full screen and you can't see the full screen, it keeps a small square in the left corner of the bottom of Ferdi's screen. Maybe in future updates, you can fix it, because now, when it happens, I have to open the Slack app and left my Ferdi app and it's boring to be running two applications at the same time.

Thank you so much!!!

**Comment by vraravam** [comment]
hi @pscamino - thanks for trying out Ferdi. Unfortunately, there's already a ticket logged for this: #1709 - thus, I'm closing this one. Please follow the other ticket for updates.
