### ISSUE TITLE
Ferdi Account log out after upgrade to 5.6.1-nightly.29 30 or 32

### ISSUE THREAD

**Issue by sad270** [getferdi/ferdi#1811]
**Bug description:**
When i upgrade `5.6.1-nightly.28` to `5.6.1-nightly.29` or `5.6.1-nightly.30` or `5.6.1-nightly.32`
* my Ferdi account is not logged in
* In settings Services, Workspaces and Account panel is disabled (Screenshot)
* I can't log in, when i try to login i have purple screen, i reload Ferdi, he show me the login screen and when try to log with my email and password it fail.

I rollback to `5.6.1-nightly.28` and the log in works good with same email and password. (And i rollback to `5.6.1-nightly.27` because 28 have regression)

**Steps to reproduce:**
1. Install `5.6.1-nightly.28` and log you to a Ferdi account
2. Upgrade `5.6.1-nightly.28` to `5.6.1-nightly.29`
3. Try to log in your Ferdi account

**Expected behavior**
Upgrade should not log out my Ferdi Account

**Screenshots**

<img width="977" alt="Screenshot 2021-08-18 at 12 33 05" src="https://user-images.githubusercontent.com/5607440/129884363-6c6aa524-141b-42f0-beea-6c60f5f908fc.png">

**Environment:**
```
Version: 5.6.1-nightly.29
Electron: 13.1.9
Chrome: 91.0.4472.164
Node.js: 14.16.0
Platform: macOS Big Sur
Arch: x64
Build date: Tue Aug 17 2021 03:30:24 GMT+0200 (Central European Summer Time)
Git SHA: 6ad52a6
Git branch: nightly
```
- Server: Ferdi

- Debug information:
  - After the upgrade : [debug_after_upgrade.txt](https://github.com/getferdi/ferdi/files/7006729/debug_after_upgrade.txt)
  - When i try to login after the upgrade: [debug_after_try_login.txt](https://github.com/getferdi/ferdi/files/7006730/debug_after_try_login.txt)

**Comment by vraravam** [comment]
Thanks for logging this @sad270 . We suspect this [PR](#1804) to be the culprit - and I am reverting that at this time. Please downgrade to v27, and then upgrade to the next nightly (v33). Sorry for the inconvenience.

**Comment by vraravam** [comment]
@sad270 - I just released v33 - please try it out and confirm if the issue has been fixed.

**Comment by mhatvan** [comment]
I also experienced this, v33 works again fine. Sorry for the broken version!

**Comment by sad270** [comment]
@vraravam i upgrade v33 and it's works goof for me too :)
Thank you.
And @mhatvan no problem it's nightly version, not beta or stable so it can have some issues don't worry :)

**Comment by sad270** [comment]
@vraravam you can remove the regression message on `5.6.1-nightly.28` in nightly releases page. The v28 haven't this issue, it's start from v29 to v32
