### ISSUE TITLE
Login to service using CAS with a popup window fails in Ferdi

### ISSUE THREAD

**Issue by swcurran** [getferdi/ferdi#1816]
**Bug description:**
Unable to log in to a CAS authenticated service (Rocketchat) that uses a popup on a Mac M1 and Windows.   When I try to log in, I get to the popup authentication page (requesting userId and password) and successfully provide my credentials, but on return to Ferdi, the login process stops.  In the developer service console, the error is:

```
989a0e5……s_resource=true:424 Uncaught TypeError: Cannot read property 'focus' of null
    at i (989a0e5……s_resource=true:424)
    at Object.o.loginWithCas (989a0e5……s_resource=true:424)
    at Object.click .external-login (989a0e5……s_resource=true:424)
    at 989a0e5……s_resource=true:219
    at Function.t._withTemplateInstanceFunc (989a0e5……s_resource=true:219)
    at h.View.<anonymous> (989a0e5……s_resource=true:219)
    at 989a0e5……s_resource=true:219
    at Object.h._withCurrentView (989a0e5……s_resource=true:219)
    at h._DOMRange.<anonymous> (989a0e5……s_resource=true:219)
    at HTMLButtonElement.delegatedHandler (989a0e5……s_resource=true:219)
```

Tried on Mac and Windows Ferdi.  The process works in Brave outside of Ferdi on both Mac and Windows, and had previously worked in Ferdi.

I can log into the same kind of Ferdi service (RocketChat) protected by a GitHub OAuth successfully.

**Steps to reproduce:**

1. Add service "RocketChat", self-hosted, using URL https://chat.hyperledger.org
2. Use the service -- it opens to the unprotected section
3. Click to login, and on resulting screen "Click to Login", which opens a popup requesting credentials.
4. Enter Linux Foundation ID (if you really want to try this -- you can get a free Linux Foundation ID)
5. Returns to the "resulting screen" (3) and stops.
6. Open up the Developer Service Console to see the error.

**Expected behavior**
It would be super cool if I could log in and use the service.

**Screenshots**

**Environment:**

- Operating System: MacOS 11.5.2 Big Sur ARM 64 (M1), Windows 10 Pro 19043.1165
- Ferdi Version: 5.6.0
- Server: Self-Hosted Ferdi Server

- Debug information:
Let me know if this is needed -- it's a lot of data!

**Comment by swcurran** [comment]
If needed I can get more information on the SSO service that Linux Foundation is using.  The URL for the authentication service is https://identity.linuxfoundation.org/

**Comment by swcurran** [comment]
Updated the title and description to note that it is also failing on Windows 10, so it is not a Mac or Mac M1 issue as I had previously thought.  This had worked in the past -- the last time I logged into this service.  Likely a few months ago.

**Comment by swcurran** [comment]
Determined that the error occurs on both 5.5 and 5.6 on Windows.

**Comment by xi-ao** [comment]
Same thing on Linux.

**Comment by swcurran** [comment]
Following up with some others on this and it looks like a general problem with the Hyperledger Foundation's authentication flow. The same issue is happening with the RocketChat desktop app. 

Closing this issue as not specific to Ferdi.
