### ISSUE TITLE
"What's new" opens a modal dialog without a close button

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1822]
**Bug description:**
Clicking on `Help > Whats new` opens a modal dialog that covers the full webview of Ferdi (see screenshot). This also disables shortcut keys to switch out (for eg I would like if this can be hidden by pressing the `Esc` key).

**Steps to reproduce:**

1. Go to 'Help'
2. Click on 'Whats new'
3. See error

**Expected behavior**
Some way to close the modal - in addition to a close 'X' button, preferably the `Esc` key can close the modal.

**Screenshots**
<img width="1792" alt="Screenshot 2021-08-22 at 9 01 11 AM" src="https://user-images.githubusercontent.com/69629/130341032-94a435d7-fc46-4268-abb9-d16136a9f172.png">

**Environment:**

- Operating System: macOS Big Sur
- Ferdi Version: 5.6.1-nightly.35
- Server: Using without an account

- Debug information:

**Comment by vraravam** [comment]
The other thought could also be that since the markdown is anyways not exported by the GH API, the content doesn't have the link etc.

From an operational perspective, the `CHANGELOG.md` file is more useful in tracking changes across both nightlies, betas and public releases. (Granularity is different across each of these categories).

With the above being said, it might be a good idea to just remove the `What's new` page/link/functionality - and just keep the link to the `Changelog` that was introduced a few weeks ago.

**Comment by mhatvan** [comment]
> With the above being said, it might be a good idea to just remove the `What's new` page/link/functionality - and just keep the link to the `Changelog` that was introduced a few weeks ago.

Yes, I was thinking the same yesterday, when I was checking the Help menu entries!
