### ISSUE TITLE
gmail link and block pop-up

### ISSUE THREAD

**Issue by Nickyg001** [getferdi/ferdi#1831]
when I click on a link in an email I get the message that "probably a pop-up blocking function prevents the link from being opened" but I don't have any pop-up blockers inside ferdi. if I right click and "open link" the link opens in the browser.
Where is the problem and how can I solve it thanks.

PS: I use on windows 10 version 5.6.1 Nightly 37.
But hadn't this problem already been solved ??

**Comment by vraravam** [comment]
Related to #842

**Comment by vraravam** [comment]
Duplicate of #1153
