### ISSUE TITLE
Reorganization of tab icons not working in vertical style - goes to start or end only

### ISSUE THREAD

**Issue by ylluminate** [getferdi/ferdi#1833]
Running on macOS 11.5.1, nightly Ferdi updates, this issue has presented since the last release and I moved back to nightlies in hopes it would resolve:

When I am using the sidebar "normally" (non "User vertical style") I can reorganize the icons in the sidebar correctly, but when I change to "vertical style" (at top) when I move an icon it shoots over to the end or beginning of all icons without fine grained control.

Settings: 

![image](https://p153.p0.n0.cdn.getcloudapp.com/items/mXuK5n1j/4f2415a8-526d-4bb9-89d1-f5c25262303c.jpg?v=42aa41cd842aa8952c3c6bf5cd8a1a06)

**Comment by technowhizz** [comment]
I was just about to report this myself +1

**Comment by technowhizz** [comment]
@vraravam do you have any insight on how to fix this? Thank you!

**Comment by technowhizz** [comment]
could it possibly have anything to do with this: https://github.com/getferdi/ferdi/blob/59e503fdc61802bd9f9fac2c030c2192bd95c4ce/src/components/services/tabs/Tabbar.js#L107

**Comment by technowhizz** [comment]
can someone who has their machine configured for development test this by changing y to x and seeing if it works? :)

@vraravam possibly or @mhatvan :)

Thank you

**Comment by vraravam** [comment]
@technowhizz - i can try it out in some time (I'm at work right now). If it fixes, I will commit and push it for tonight's nightly.

**Comment by technowhizz** [comment]
Thank you!

Also now that I think of it it will probably be something like if(use.vertical.style) then x else y

**Comment by vraravam** [comment]
yes - that's why I wanted some time to get that logic correct :)

**Comment by vraravam** [comment]
@technowhizz - thanks for the pointer about the hardcoded line. That was indeed the issue, and I have committed a fix in #1834 - this should appear in the next nightly.

**Comment by technowhizz** [comment]
Thank You!!!

**Comment by technowhizz** [comment]
Also This is a bigger task as the variables have now been used everywhere but @vraravam do you think it should be called horizontal style as vertical is the default posisition?

**Comment by vraravam** [comment]
> Also This is a bigger task as the variables have now been used everywhere but @vraravam do you think it should be called horizontal style as vertical is the default position?

yes, unfortunately, that would also need for us to introspect the users' installed location settings, and invert the meaning - so that the migration is seamless when a user upgrades. I'm pretty sure that that is a much more involved process, as opposed to just finding text in the code and replacing it. Since, this is "internal" atm, I would just leave it "as is" for now.
