### ISSUE TITLE
Voice recording in Whatsapp/Telegram services does not work

### ISSUE THREAD

**Issue by ammarmalhas** [getferdi/ferdi#184]
**Describe the bug**
Trying to send a recorded voice message in the WhatsApp and Telegram services but the messages goes out empty.
Either Ferdi is not getting microphone permission on the MAC OS system or something else is wrong.

**To Reproduce**
1. Go to either service inn Ferdi, select to send a message to a recipient (one of your accounts would be easier to check),
2. Click on microphone icon and start recording,
3. Send the message when done,
4. Listen to it on your phone! Nothing recorded!

**Expected behavior**
I expect the record button in these services to actually record my voice.

**Desktop (please complete the following information):**
- MAC OS: 10.14.6
- Ferdi Version 5.4.0 beta 4

**Comment by vantezzen** [comment]
May be related to #154

**Comment by ammarmalhas** [comment]
> May be related to #154

It is. The issue seems to be Ferdi not obtaining Mic/Camera permission from MAC OS.

**Comment by kytwb** [comment]
Closing in favor of https://github.com/getferdi/ferdi/issues/154.
