### ISSUE TITLE
In app Tiling please!

### ISSUE THREAD

**Issue by 3d73a4a412** [getferdi/ferdi#1847]
**Is your feature request related to a problem? Please describe.**
Screen real estate is pretty limited on my notebook computer so maximizing the space would really be useful; actually this would be useful on large monitors as well, so being able to say see email and chat windows at the same time for some workflows is easier than switching back and forth.

**Describe the solution you'd like**
In short, in app window tiling.

**Describe alternatives you've considered**
I have used vivaldi's excellent screen split feature to show multiple tabs, tiled, on one screen.

**Additional context**
If ferdi could show multiple tabs at once, say like one for my email and another for a chat that would be SUPER useful! 

Regardless, thanks for all the great work!

**Comment by vraravam** [comment]
Duplicaet of #893 - please continue conversations there.
