### ISSUE TITLE
Provide RPM package

### ISSUE THREAD

**Issue by mthomos** [getferdi/ferdi#185]
**Is your feature request related to a problem? Please describe.**
Not exactly, just provide rpm package for supported systems

**Comment by vantezzen** [comment]
We won't provide an RPM package ourselves but anyone is free to create and maintain one - similar to how the [AUR package](https://aur.archlinux.org/packages/ferdi/) is maintained.
If anyone does package Ferdi to an RPM package I would be happy to add it to the readme.

**Comment by kytwb** [comment]
@vantezzen Couldn't we just add the `rpm` target so the rpm package automatically gets delivered with the assets? It's natively supported by [electron-builder](https://www.electron.build/configuration/linux).

**Comment by vantezzen** [comment]
Oh sorry, I didn't knew that - sounds good.

**Comment by kytwb** [comment]
Next release will ship with the `rpm` asset 👍

**Comment by kytwb** [comment]
@mthomos https://github.com/getferdi/ferdi/releases/tag/v5.4.0 comes with a RPM package listed in the assets.
