### ISSUE TITLE
Zoom In/Zoom out works only for last LOADED ON STARTUP webview

### ISSUE THREAD

**Issue by pztrn** [getferdi/ferdi#1867]
**Bug description:**
When trying to play with zoom only last LOADED service is affected. Dragging service in the sidebar's bottom doesn't make it work.

**Steps to reproduce:**
1. Open Ferdi with 2 or more services.
2. Try to zoom out on first.
3. See it isn't worked.
4. Switch to last LOADED ON START service and realize that your hundreds of zoom outs happened here.

_(actually, reloading service isn't working, it will be last loaded on startup)_

**Expected behavior**
Zoom out (or zoom in, or actual size) works on currently active service.

**Environment:**

- Operating System: macOS 11.5.2
- Ferdi Version: 5.6.1-nightly.48
- Server: no server.

- Debug information:
<img width="863" alt="изображение" src="https://user-images.githubusercontent.com/869402/132105211-5a944823-dd96-49ce-92a3-b5f8c5a3b608.png">
¯\_(ツ)_/¯

**Comment by vraravam** [comment]
@sad270 - could you please try to debug this? I made some changes and committed, which worked in dev mode, but in the packaged mode, it again stopped working

**Comment by sad270** [comment]
Ok, i gonna look tomorow

**Comment by vraravam** [comment]
I can confirm that this is now working perfectly in `5.6.1-nightly.52`
