### ISSUE TITLE
"Updates" tab not in sync with actual used release version

### ISSUE THREAD

**Issue by mhatvan** [getferdi/ferdi#1870]
**Bug description:**
When downloading a nightly version for the first time and opening Ferdi, the "Include nightly versions" toggle is off, even though the user is using nightly.

**Steps to reproduce:**

1. Go to 'Settings'
2. Click on 'Updates'
3. Nightly version toggle is off, even though using nightly

**Expected behavior**
Version toggles are in sync with user preferences AND downloaded version

**Environment:**

- Operating System: Ubuntu 21.04
- Ferdi Version: v5.6.1-nightly.47
- Server: Ferdi

**Comment by vraravam** [comment]
Sorry - but, I don't agree with this coupling. I would much rather give the choice to the user to jump to a nightly for testing purposes, but then choose not to upgrade to the next nightly and so on. They can then choose to (independently) upgrade to a beta or directly to a public version.

**Comment by mhatvan** [comment]
Ah interesting! Actually it makes sense, I agree.
