### ISSUE TITLE
Removing zh-Hant.json duplicate

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#188]
Remove [this file zh-Hant.json](https://github.com/getferdi/ferdi/blob/develop/src/i18n/locales/zh-Hant.json) because it is buggy on windows and it is a duplicate of the same file.

PS: Maybe checking first what FerdiBot update which file first before deleting one of them.

**Comment by kytwb** [comment]
I remember doing it a while back but it must have been reintroduced by FerdiBot yeah. Related: [Git is case-sensitive and your filesystem may not be - Weird folder merging on Windows](https://www.hanselman.com/blog/GitIsCasesensitiveAndYourFilesystemMayNotBeWeirdFolderMergingOnWindows.aspx)

**Comment by vantezzen** [comment]
I now changed CrowdIn to using "zh-HANT" instead of "zh-Hant" (as seen in #192) and deleted "zh-Hant.json"
