### ISSUE TITLE
Can't connect to Ferdi online services

### ISSUE THREAD

**Issue by Cyruz143** [getferdi/ferdi#1888]
Just popped up, I logged out and restarted the application, now I can't login. Is this a backend issue, I can login to my account on https://api.getferdi.com/user/account without issue. Can't see any DNS being blocked in relation to it either.

**Comment by EgoDogg** [comment]
I also got randomly booted and can't login (same error). I was on the latest beta and tried re-installing as well as the newest nightly. No luck.

**Comment by tcastelli** [comment]
same issue here

**Comment by Wolfensteijn** [comment]
Developer tools show 503 errors on api.getferdi.com, visiting the API using a webbrowser works fine. Changing the server to Franz also works fine.

![image](https://user-images.githubusercontent.com/1969576/132539922-08e21a89-8162-4b56-bb00-ce4c49f67267.png)

**Comment by LordBoos** [comment]
I have the same issue. I cannot login to application and all my services dissappeared.

**Comment by M0UL** [comment]
i have same problem.

**Comment by LordBoos** [comment]
Looks like the issue is with CloudFlare.
![image](https://user-images.githubusercontent.com/939813/132540201-e0ffe75c-9509-4845-8adc-b7d0f89acb83.png)

**Comment by hagerf** [comment]
The same for me, services gone, cannot login. 😢

**Comment by M0UL** [comment]
it works again for me

**Comment by LordBoos** [comment]
Yep, looks like it was just a temporary outage.

**Comment by tcastelli** [comment]
working again 👍

**Comment by Cyruz143** [comment]
Alright, pack it up people, time to go back to not working.
