### ISSUE TITLE
Problems settings up Ferdi with Docker Server

### ISSUE THREAD

**Issue by kmplngj** [getferdi/ferdi#189]
Hello,

I'm new to Ferdi. I also did not used Franz before.

I installed Ferdi on macOS 10.15 (via homebrew) and I installed the server in my CentOS Docker Stack (running behind Traefik Reverse Proxy).

In Ferdi I changed the server URL to my server. I created an account. But now I could not add any of the services to Ferdi. I click on any of the services and nothings happens.

But I could be some browser errors in Ferdi.

![Bildschirmfoto 2019-11-03 um 16 56 32](https://user-images.githubusercontent.com/562965/68087974-fd32fe00-fe5a-11e9-927f-d31193151444.png)
![Bildschirmfoto 2019-11-03 um 16 56 39](https://user-images.githubusercontent.com/562965/68087975-fd32fe00-fe5a-11e9-89c3-e06d757061bc.png)

How could I find out that the problem is?

Thanks a lot for the help
Jan

**Comment by kmplngj** [comment]
I think my server installation could be the problem. But how could I debug it?

**Comment by vantezzen** [comment]
In the Developer Tools under "Network" you can view the responses sent by your server. This response normally contains an error message - can you check that?

**Comment by kmplngj** [comment]
I think that is: E_INVALID_JWT_TOKEN: invalid signature

I added a screenshot of the server startup messages.

![Bildschirmfoto 2019-11-04 um 11 37 18](https://user-images.githubusercontent.com/562965/68115141-fc03de80-fef7-11e9-8150-e19e0b8df0cd.png)

**Comment by vantezzen** [comment]
Can you please log out and back in inside Ferdi?

**Comment by kmplngj** [comment]
![Bildschirmfoto 2019-11-04 um 12 46 39](https://user-images.githubusercontent.com/562965/68118807-358d1780-ff01-11e9-9083-f4eff7801176.png)

Not possible now :(

**Comment by vantezzen** [comment]
You can click „Abmelden“ in the bottom left instead

**Comment by kmplngj** [comment]
I tried it with a fresh install on another mac. Same problem.

**Comment by kmplngj** [comment]
Could anybody help? Thx!

**Comment by vantezzen** [comment]
Logging out didn't help?
Can you validate your JWT token manually please:
- In Ferdi's Developer Console run `localStorage.getItem('authToken')`. You will get back your current auth token
- Insert your token into <https://jwt.io/#debugger-io> and validate if its a valid JWT token
