### ISSUE TITLE
App always requests a default-url-handler-scheme change

### ISSUE THREAD

**Issue by csandwith** [getferdi/ferdi#1898]
**Bug description:**

Ubuntu 20.04 Desktop. Whenever I start the Snap Ferdi, I am prompted for a default-url-handler-scheme change. Regardless of my selection, if I close the app and reopen it, I am prompted again

**Steps to reproduce:**

1. Snap Install Ferdi on Ubuntu 20.04
2. Launch Ferdi
3. A dialog is presented: 
Allow settings change?

Allow snap "ferdi" to change "default-url-scheme-handler" subproperty "ferdi" to "ferdi_ferdi.desktop" ?
4. Select "Yes" or "No"
5. Close Ferdi
6. Launch Ferdi

**Expected behavior**

Expected: Ferdi launches with no extra prompt
Actual: I am prompted again with the "Allow settings change" dialog

**Screenshots**

![2021-09-09_08-53](https://user-images.githubusercontent.com/11035407/132720064-6cf0bbe7-e320-4ec1-b62b-b7bcd156fd7c.png)
**Environment:**

- Operating System:  Ubuntu 20.04 Desktop
- Ferdi Version:  5.6.1-beta.1
- Server:  ?? I'm not sure that it matters

- Debug information:

`
{"host":{"platform":"linux","release":"5.11.0-27-generic","screens":[{"id":1707290301651283,"bounds":{"x":1920,"y":0,"width":1920,"height":1200},"workArea":{"x":1920,"y":27,"width":1920,"height":1121},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6477, 0.3327],  [0.3086, 0.6012],  [0.1511, 0.0729]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1200},"displayFrequency":59,"workAreaSize":{"width":1920,"height":1121},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":1707290301651284,"bounds":{"x":3840,"y":0,"width":1920,"height":1200},"workArea":{"x":3840,"y":0,"width":1920,"height":1200},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1200},"displayFrequency":59,"workAreaSize":{"width":1920,"height":1200},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":1707290301651285,"bounds":{"x":0,"y":0,"width":1920,"height":1200},"workArea":{"x":0,"y":0,"width":1920,"height":1200},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1200},"displayFrequency":59,"workAreaSize":{"width":1920,"height":1200},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.1-beta.1","electron":"13.1.9","installedRecipes":[{"id":"messenger","version":"1.2.0"},{}],"devRecipes":[],"services":[{"id":"b4ade2e4-ddba-4324-bf8f-3f5fc356ec8a","recipe":"messenger","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: The prop `stores.app.accentColor` is marked as required in `_class2`, but its value is `undefined`.\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by WithTheme(Jss(_class2)))\n    in WithTheme(Jss(_class2)) (created by inject-WithTheme(Jss(_class2))-with-stores)\n    in inject-WithTheme(Jss(_class2))-with-stores (created by _class2)\n    in _class2 (created by WithTheme(_class2))\n    in WithTheme(_class2) (created by Jss(WithTheme(_class2)))\n    in Jss(WithTheme(_class2)) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You are using Ferdi without a server"}],"workspaces":[],"windowSettings":{"width":800,"height":600,"x":0,"y":37,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1920,"height":1200}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":"300","wakeUpStrategy":"300","inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"never","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isServiceProxyEnabled":false,"isAnnouncementsEnabled":true,"isWorkspaceEnabled":false,"isTodosEnabled":true},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}`

As a final aside, another FOSS Snap experienced the same bug, and seems to have resolved the issue. It might be valuable/worthwhile/whatever to take a look at what they did to resolve it: https://github.com/ytmdesktop/ytmdesktop/issues/630

**Comment by vraravam** [comment]
This has already been fixed in 5.6.1-beta.2 - please upgrade and check it out.

**Comment by csandwith** [comment]
Confirmed. I had to switch to the beta track in order to get it (`snap refresh ferdi --channel=latest/beta`) but the issue is no longer reproducible in 5.6.1-beta.3

Thank you for the quick response!

**Comment by redno2** [comment]
I'm still affected with this bug on the latest version ferdi 5.6.3
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

$ snap info ferdi
name:      ferdi
summary:   All your messaging services in one place
publisher: Ferdi (getferdi)
store-url: https://snapcraft.io/ferdi
contact:   hello@getferdi.com
license:   unset
description: |
  Ferdi is a messaging browser that allows you to combine your favorite messaging services
  into one application.
commands:
  - ferdi
snap-id:      c9FsJPOVsNaH3lLn0KtmU76g0CKm1N6R
tracking:     latest/stable
refresh-date: today at 10:20 CET
channels:
  latest/stable:    5.6.3            2021-11-07 (113) 122MB -
  latest/candidate: ↑                                       
  latest/beta:      5.6.3-beta.4     2021-11-07 (111) 122MB -
  latest/edge:      5.6.3-nightly.54 2021-11-07 (110) 122MB -

```
![image](https://user-images.githubusercontent.com/3406132/140721286-05a3ebc1-3886-41fc-b5ed-c215cb46dc01.png)
![image](https://user-images.githubusercontent.com/3406132/140721307-baaa71e8-342c-494e-ba10-9d4ba1f388b9.png)
