### ISSUE TITLE
Ferdi dosn't close properly (1 process is still open)

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#190]
**Describe the bug**
When closing Ferdi, there is still one and only process that is not shuting down and cause to maybe break something after or blocking ejection of the drive etc. And the process "go outside of the warpper (FerdiPortable)".

**To Reproduce**

1. Go to Settings
2. Click on Quit
3. Go to Task Manager of Windows
4. See the process still up

**Expected behavior**
Normally when Ferdi is asking to be closed it is terminating everything.

**Screenshots**
![dsada](https://user-images.githubusercontent.com/49844464/68090227-483f1800-fe3f-11e9-839b-d272396a07dd.PNG)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 5.4.0-beta.5 4cb24eb

**Additional context**
This is when using FERDI_APPDATA_DIR with my PortableApps Format (like a wrapper). FranzPortable has not this problem though.

This is the command line of the process that is causing problem:
`"C:\PortableApps\FerdiPortable\App\ferdi\Ferdi.exe" --type=renderer --field-trial-handle=2024,16648864906732012307,7597258420868579733,131072 --disable-features=LayoutNG,SpareRendererForSitePerProcess --lang=fr --app-user-model-id=com.kytwb.ferdi --app-path="C:\PortableApps\FerdiPortable\App\ferdi\resources\app.asar" --no-sandbox --no-zygote --preload="C:\\PortableApps\\FerdiPortable\\App\\ferdi\\resources\\app.asar\\webview\\recipe.js" --background-color=#fff --guest-instance-id=11 --enable-blink-features --disable-blink-features --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=17486244775156609310 --renderer-client-id=24 --no-v8-untrusted-code-mitigations --mojo-platform-channel-handle=3652 /prefetch:1
`

**Comment by vantezzen** [comment]
Do you have "keep Ferdi running in Background" enabled in the settings?

**Comment by Makazzz** [comment]
> 
> 
> Do you have "keep Ferdi running in Background" enabled in the settings?

No

**Comment by Makazzz** [comment]
It seem to not always do that (but I am on another PC right now..) I will have to do more check about this.

**Comment by Makazzz** [comment]
I will close this issue because the bug has stopped at the moment (tested 3 Windows PC) and I am only one to report something like this too.
