### ISSUE TITLE
Ferdi nightly freezes upon launching

### ISSUE THREAD

**Issue by mll0** [getferdi/ferdi#1901]
**Bug description:**

Upon launching Ferdi portable, I get a purple rectangle only :
![image](https://user-images.githubusercontent.com/1040535/132808137-f1dc8f4f-aeea-4e96-a404-8c53f6664c2a.png)
Then, Ferdi wouldn't quit, and I need to kill the processes from the task manager.

If launched for the first time, we get the purple rectangle, then after a few secs, the screen to offer to connect.
![image](https://user-images.githubusercontent.com/1040535/132808394-02d3804b-2dff-495f-af6a-ea92578944d4.png)
Then, when I click "Use Ferdi without an account", we get the same behaviour as above.

This problem does not happen with 5.6.1-nightly.46. This does happen with 5.6.1-nightly.53 (and 5.6.1-nightly.54, and 5.6.1-nightly.55), so the bugs must have been introduced between 47 and 53 (inclusive)

**Environment:**

- Operating System: Windows 10 21H1
- Ferdi Version: see above
- Server: Using without an account

- Debug information:
Menu not available AFAICS

**Comment by alexdevero** [comment]
This happens to me with latest v5.6.1, on Windows 10. Ferdi launches and I get only the purple rectangle. In order to quit I have to kill Ferdi process.

**Comment by sebastianarnold** [comment]
I have the same issue with Ferdi 5.6.1 running on Linux Mint 20.2 x86-64 (installed from deb package). I tried to reset configuration by deleting ~/.config/Ferdi/ but it still shows the purple rectangle after clicking "use ferdi without an account".

**Comment by Nikitoring** [comment]
I have the same problem in Ferdi 5.6.1 on Linux Ubuntu 21.04

**Comment by janhohner** [comment]
Same problem on Ubuntu 20.04 LTS

**Comment by janhohner** [comment]
Seems to be fixed in 5.6.2 🙂

**Comment by jaimiewashere** [comment]
> Seems to be fixed in 5.6.2 slightly_smiling_face

I can confirm this!

**Comment by vraravam** [comment]
Closing this ticket - Thanks @janhohner , @jaimiewashere
