### ISSUE TITLE
[Feature Request] Spotify support

### ISSUE THREAD

**Issue by ShrirajHegde** [getferdi/ferdi#1909]
Support for Spotify would be a great use.

There's a Franz recipe - https://github.com/NickMorozov/franz-recipe-spotify

but Ferdi browser doesn't support DRM

![image](https://user-images.githubusercontent.com/66936172/132952017-2affb599-2124-4d1b-8fd9-081df972d75b.png)

**Comment by vraravam** [comment]
As described in #671 , the DRM content requires the widevine player to be installed, which is currently not possible in Ferdi. Closing this ticket since the other one is tracking the support for extensions.
