### ISSUE TITLE
Windows 10 need --vs2015 for building

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#191]
In the readme it is asking to use this command line for windows;

```bash
$ npm install --global windows-build-tools // Windows 10
$ npm install --global windows-build-tools --vs2015 // Windows 7
```

but I just did a build of Ferdi with this commit 4cb24eb and I was getting error when using this line;

npm run rebuild

So I used the command line for windows 7 (in my windows 10 machine) and after re-using rebuild and build.. everything worked.

So my suggestion is to do
this
```bash
$ npm install --global windows-build-tools // Windows 10
$ npm install --global windows-build-tools --vs2015 // Windows 7
```

to this
```bash
$ npm install --global windows-build-tools --vs2015
```

**Comment by kytwb** [comment]
Addressed via https://github.com/getferdi/ferdi/commit/33a1daa4dc0a01a8d2fd68300ddd63503aab8d41. Thank you for testing on Windows 10 and reporting.

**Comment by Makazzz** [comment]
For more information in the error log it was saying that the build was needing Visual Studio v140 (so VS2015) and not 2017 for windows 10
