### ISSUE TITLE
Bug | no top menu at all (can't invoke it either)

### ISSUE THREAD

**Issue by avielc** [getferdi/ferdi#1911]
**Bug description:**
on 5.6.1 (not beta) the menu disappeared completely, pressing Alt doesn't invoke it either. 

**Steps to reproduce:**
Just installed 5.6.1

**Expected behavior**
Expected to see the top menu and be able to remove it if wanted by the View -> Auto hide menu

**Screenshots**
![image](https://user-images.githubusercontent.com/13572969/132955409-c5b45868-73b6-45eb-86c1-d3b3e1a5629c.png)

**Environment:**

- Operating System: Windows 10 Pro
- Ferdi Version: 5.6.1
- Server: with or without
- 
- Debug information:
Can't click help

**Comment by vraravam** [comment]
This might even warrant a priority hot-fix release. Unfortunately, I don't have a windows machine available. @kytwb / @mhatvan - can either of you take this up please?

**Comment by vraravam** [comment]
@avielc , in your ferdi profile folder (for windows: `%appdata%/Ferdi`), please open this file in a text editor: `config/settings.json`).

Within it, search for `autohideMenuBar` and set it to `false` (without quotes). - or you can simply delete that line alone. Please do this after killing Ferdi. Then restart Ferdi - does the menubar come back up?

**Comment by avielc** [comment]
@vraravam - tried it, nothing changed. 
I'm using the standalone version. and it seems to be ignoring that config file. (or the command) 
on 5.6.1-beta-3 it always displays the menu bar, on 5.6.1 it always doesn't. 
on top of that, on windows when loading it up i see a constant 15% cpu usage, and the app refuses to close gracefully, I have to force shut it down.

**Comment by bittner** [comment]
Likely related: On Linux (e.g. Ubuntu) the menu is available, but – compared to earlier versions of Ferdi – a lot of items seem to be missing. The Help menu, for example, is entirely empty:

![Ferdi-Help-menu-empty](https://user-images.githubusercontent.com/665072/132989779-24a6ca27-0174-41a4-afaa-a7d67cb112a0.png)

**Comment by vraravam** [comment]
I strongly suspect the refactorings done to the [Menu.js](https://github.com/getferdi/ferdi/commits/develop/src/lib/Menu.js) file has caused these issues. But, everything is fine on macos (which is what I use to build and test).

is anyone willing to test one of the nightlies? If so, I can revert the refactorings and create new builds.

**Comment by avielc** [comment]
@vraravam - i'd be happy to test, my only issue is how to turn a nightly into an actual app. (since the updater is also broken as you've mentioned previously - I can't just click it and let it download the nightly and deploy it) 

Thanks

**Comment by mhatvan** [comment]
I just released a fix for the broken menu, which will land in 5.6.2-nightly.2, please let me know if it solves the issue at hand.

We will probably also change to a faster stable release cadence to avoid broken functionality for extended period of time.

**Comment by avielc** [comment]
@mhatvan - can you tell me how to implement the new nightly into the existing installation? (running on windows) 
a guide\set of instructions would be great. thank you!

**Comment by mhatvan** [comment]
You will find the new one appearing here: https://github.com/getferdi/nightlies/releases

I agree, we should have the nightlies within Ferdi or easier discoverable in the readme.

**Comment by avielc** [comment]
Thank you very much! 
unfortunately as mentioned in another ticket #329  (I think) isn't fully working, it downloads the update but isn't able to apply it.
I'll test it out in a few minutes

**Comment by avielc** [comment]
@vraravam @mhatvan - unfortunately it seems to be the same 
![image](https://user-images.githubusercontent.com/13572969/133000329-2a0104af-ad64-4bd4-b20d-0831a0676dd9.png)

the configuration was changed to false for autohide,
removed completely (I'm using the portable version) 
What I do notice is this extra space under the apps icons (as if where the menu could've been. 

Also, can't close the app gracefully - must shut down by force through task manager

**Comment by avielc** [comment]
worth mentioning for the quit issue - 
quitting from the systray icon isn't working
but if I choose to press the X it'll quit it no issue. (if that helps)

**Comment by mhatvan** [comment]
Sorry for the confusion, the nightly (6.6.1-nightly.2) I am talking about is not released yet.

**Comment by avielc** [comment]
Gotcha, when it does come out, can you please have it built for Windows (at the very least) so I can test it? 
Thanks!

**Comment by vraravam** [comment]
@avielc @bittner - I just released the [latest nightly](https://github.com/getferdi/nightlies/releases/tag/v5.6.2-nightly.2) - please try if this works for this bug. IF all the critical bugs are fixed, I plan to release a hot fix later today. Thanks in advance

**Comment by avielc** [comment]
@vraravam - how do i run it? 
Is there a build process or set of instructions I can follow up to create an exe file? (at the very least)?
as mentioned before, (I think you are on that ticket too) the update function inside Fredi isn't working at all, I think you mentioned it downloads the update but isn't able to process it(?)
Looking forward to your answer

**Comment by vraravam** [comment]
@avielc - the link that I had sent in my previous comment - in there are present downloads of executables for different operating systems and chip architectures. Did you not see that?

**Comment by avielc** [comment]
@vraravam  - I went to the releases page manually and all I saw there was the source zip\tar.gz 
I guess it took it a little while to get updated? 
Anyways, downloading it now and will let you know
Thanks!

**Comment by vraravam** [comment]
No - the zip/tar.gz will only be the compressed sources. Are you going to the correct link? You might be going to the one for *ferdi* - which is incorrect. The link I have sent in this comment: https://github.com/getferdi/ferdi/issues/1911#issuecomment-917783866 - also refers to the *nightiles* repo - please check once more.

**Comment by vraravam** [comment]
this is the nightlies repo: https://github.com/getferdi/nightlies

this is the main repo: https://github.com/getferdi/ferdi

The FIRST ONE is the one that I had linked to up above

**Comment by avielc** [comment]
Ah! Thanks for clarifying!
I was sure I was being redirected to the regular fredi page. 
took me a second to figure what I missed. 

Thanks again, downloading and installing now

**Comment by vraravam** [comment]
@kytwb - please update the Downloads page in the website to make the nightlies more prominent

**Comment by avielc** [comment]
so few items
first for good news: 
I can close Fredi either with Ctrl+Q, close when the setting is set to: do not close to systray, or by right clicking and quitting from systray. 
Next up: 
1. Fredi starts with a huge cpu load at the begining: (reached 80% load) 
![image](https://user-images.githubusercontent.com/13572969/133041158-41c9bbd2-6688-40c0-9cad-8ceb834f282b.png)
it calms down after that intial burst to about 2% cpu usage. 
2. the UI icons seemed to me as mega sized on "normal icon bar"
![image](https://user-images.githubusercontent.com/13572969/133041453-bb645dd9-2e4e-49db-99e0-68a1e81e1847.png)
3. related to the previous point - when in Horizontal mode - there's some extra line space under the service icons:
![image](https://user-images.githubusercontent.com/13572969/133041623-8e49ff1e-b081-4879-96c8-dd25cf5aba6f.png)
4. Auto hide isn't working still (checked or unchecked) 

I can come up with one or more styles that could be corrected or changed, but it's mostly cosmetics, so it's really low priority for now. 

let me know if you want me to break it down into issues 
Thanks again!
I think this is definitely a hotfix for the critical issue of no-menu\no-quit bugs

**Comment by vraravam** [comment]
thanks - please log separate tickets for the above cosmetic issues. I will close this ticket so that I can do a hotfix release in the next hour or so

**Comment by bittner** [comment]
I confirm the menu bar is populated properly on Linux now (e.g. Help menu has a lot of items again).

There are some more issues, though. See #1928 and #1929.
