### ISSUE TITLE
Unable to quit from system tray

### ISSUE THREAD

**Issue by Dominiquini** [getferdi/ferdi#1913]
**Bug description:**
I was unable to quit Ferdi using the system tray icon!

**Steps to reproduce:**

1. Start Ferdi
2. Enable the options "Keep Ferdi in the background" and "Show Ferdi on system tray"
3. Close the windows
4. Click on "Quit Ferdi" on system tray
5. The application remains working (the system tray remains and the applications is still running).

**Expected behavior**
The application is finished and the system tray disapear

**Environment:**

- Operating System: Windows 10 x64
- Ferdi Version: 5.6.1
- Server: ---

**Comment by mbledkowski** [comment]
Same issue
OS: Manjaro Gnome
Ferdi Version: 5.6.1

**Comment by vraravam** [comment]
@Dominiquini @mbledkowski - I just released the [latest nightly](https://github.com/getferdi/nightlies/releases/tag/v5.6.2-nightly.2) - please try if this works for this bug. IF all the critical bugs are fixed, I plan to release a hot fix later today. Thanks in advance

**Comment by Dominiquini** [comment]
This nightly build appears to be working ok!

Thanks.
