### ISSUE TITLE
CTRL+1, CTRL+2, etc no longer working

### ISSUE THREAD

**Issue by k3tan172** [getferdi/ferdi#1916]
CTRL+1, CTRL+2, etc to switch between services doesn't seem to work anymore. It stopped working since Ferdi 5.6.1-beta3 or beta4 and doesn't work in v5.6.1. On linux, using .deb package.

**Comment by beningodfrey4** [comment]
Can confirm. Seems to affect Ctrl+<NUM> and Ctrl+Alt+<NUM> shortcuts only. Ones for zoom, reload and others in the menubar still work. Ferdi v5.6.1, electron13 with the AUR package(ferdi).

**Comment by vraravam** [comment]
@k3tan172 @beningodfrey4 - I just released the [latest nightly](https://github.com/getferdi/nightlies/releases/tag/v5.6.2-nightly.2) - please try if this works for this bug. IF all the critical bugs are fixed, I plan to release a hot fix later today. Thanks in advance

**Comment by k3tan172** [comment]
It's working for me now. Thanks, appreciate it.

**Comment by beningodfrey4** [comment]
Yep, works for me too.

**Comment by Upgreydd** [comment]
@vraravam Hey mate, I'm facing the issue still in Arch Linux:
I've tried:
- AUR ferdi 5.6.2
- AUR ferdi-bin 5.6.2
- snapd version 5.6.2
Any option to help you debug the issue?

**Comment by vraravam** [comment]
@Upgreydd - would you be willing to test this out in the latest nightlies? I'm sorry, I dont use linux, and so won't be able to debug the issue.
