### ISSUE TITLE
Ferdi crashes multiple times on starting (win10)

### ISSUE THREAD

**Issue by micker** [getferdi/ferdi#1921]
hello i have many many crash on strating in WIN 10 windows start and clash ..... in loop
any idea ?
regards

**Comment by vdurante** [comment]
@micker I have similar issue, Ferdi is starting but no gui shows up.

**Comment by mhatvan** [comment]
Please provide more information about used Ferdi version, error logs, etc.

Using 5.6.3-nightly.4 on Windows 10 and it works as expected.
