### ISSUE TITLE
Ferdi cannot connect to online services

### ISSUE THREAD

**Issue by alexdevero** [getferdi/ferdi#1922]
**Bug description:**

Ferdi can't connect to online services and load account information.

**Steps to reproduce:**

1. Start Ferdi

**Expected behavior**

Ferdi will start and connect to online services and load account information.

**Screenshots**

![ff](https://user-images.githubusercontent.com/4237724/133077480-f0427c10-3227-4fd6-a370-fbd2cc2d1d0f.PNG)

**Environment:**

- Operating System: Windows 10 21H1
- Ferdi Version: 5.6.2
- Server: Ferdi

- Debug information:

**Comment by mhatvan** [comment]
I cannot reproduce this. @alexdevero Is this issue still relevant?

**Comment by alexdevero** [comment]
@mhatvan Connection to online services is working now.

**Comment by mhatvan** [comment]
Great, happy to hear!

Let us know in case this happens again.
