### ISSUE TITLE
About box only partially modal (Linux)

### ISSUE THREAD

**Issue by bittner** [getferdi/ferdi#1928]
**Bug description:**
On Linux, the About box is only partially modal.

Specifically, when the About box dialog is open Ferdi's main application window can be activated , potentially hiding the About box dialog window behind it.

It's possible to interact with the main window where the focus currently is (e.g. enter text when the cursor blinks in a message input field), but most interactions with the main window are blocked.

**Steps to reproduce:**

Given you're on a Linux distribution (e.g. Ubuntu Linux).

1. Go to menu bar > Help > About Ferdi ➜ (the About box dialog opens)
2. Click on the main window behind the About box ➜ (the About box loses the focus)
3. Type text on the keyboard ➜ (the input field having the focus types the text)
4. Try to press the <kbd>Alt</kbd> key to show the menu ➜ (no reaction)
5. Try to click on the menu (if visible) or somewhere on the main window ➜ (no reaction)

**Expected behavior**

The About box dialog should stay in front of the main window at all times, until it is disposed.

_Likely source of the problem: The reference of the parent window is not passed to the About dialog constructor (or similar)._

**Screenshots**

![ferdi-about-box-partially-modal-and-image-missing](https://user-images.githubusercontent.com/665072/133123037-8a41a858-9794-4988-a12f-de62284fe507.png)

**Environment:**

- Operating System: Ubuntu GNU/Linux 18.04.5 LTS
- Ferdi Version: 5.6.2
- Server: (local)

**Comment by vraravam** [comment]
This is the base electron behavior. We switched from custom code to using the electron API - and this resulted in this behavior. Please log a bug against electron for this chage.

**Comment by vraravam** [comment]
Update: I have reverted back to the custom code - since there were other issues as well related to the same base electron API. This should now be fixed in the next nightly.
