### ISSUE TITLE
Ferdi logo image broken in About box

### ISSUE THREAD

**Issue by bittner** [getferdi/ferdi#1929]
**Bug description:**
On Linux, the About box shows a placeholder for an image, just if the image reference was broken or the image was unavailable.

Both, the DEB package and the Snap are affected.

**Steps to reproduce:**

Given you're on a Linux distribution (e.g. Ubuntu Linux).

1. Go to menu bar > Help > About Ferdi ➜ (the About box dialog opens)
2. The About box shows a placeholder icon for when an image is not available (see screenshot below)

**Expected behavior**

The About box dialog should show the Ferdi logo nicely.

_Side note: Shouldn't the text also say something like "Franz Ferdinand"? It was like that in the past._

**Screenshots**

![ferdi-about-box-partially-modal-and-image-missing](https://user-images.githubusercontent.com/665072/133123037-8a41a858-9794-4988-a12f-de62284fe507.png)

**Environment:**

- Operating System: Ubuntu GNU/Linux 18.04.5 LTS
- Ferdi Version: 5.6.2
- Server: (local)

**Comment by vraravam** [comment]
I am reverting the change to reuse the core electron API to show the `About` dialog, which should go back to using custom code and this issue can be re-verified in the next nightly.

**Comment by vraravam** [comment]
@bittner - could you please confirm if this is still an issue? I had reverted the use of the in-built code and went back to the original custom implementation.

**Comment by bittner** [comment]
This looks fine with the latest nightly. Thanks for asking!

![image](https://user-images.githubusercontent.com/665072/133530450-6808f968-2ea3-48e1-9e20-b3ad4b69e407.png)

**Comment by bittner** [comment]
Just noticed that the problem is not fixed for the Ferdi _snap_ package. But that's most likely for a different reason (snap permission issues).
