### ISSUE TITLE
Highlights added to native Slack UI

### ISSUE THREAD

**Issue by SDVII** [getferdi/ferdi#1932]
**Bug description:**
Slack integration seems to be having a visual bug where weird highlights are added to certain elements and inputs.
At first I thought it was a new slack update, but the browser version doesn't have the same appearance.

**Steps to reproduce:**

1. Install Slack's integration
2. Enable dark mode via Slack preferences 
3. Added highlights are visible

**Expected behavior**
For the Slack integration UI to match the one that appears on a normal browser

**Screenshots**
![image](https://user-images.githubusercontent.com/10416702/133204204-adfb6ff0-8ade-48af-8aa8-991ee5f26d4c.png)
![image](https://user-images.githubusercontent.com/10416702/133204246-7cec1cc8-b654-4e04-bcf5-1a0853022edf.png)
![image](https://user-images.githubusercontent.com/10416702/133204261-885267b0-659c-4669-bd57-b804af76a4d2.png)
![image](https://user-images.githubusercontent.com/10416702/133204278-a2a409d1-4c77-48fc-a9af-e8388f3dd4cb.png)

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.6.2
- Server: Ferdi

**Comment by SDVII** [comment]
A small update, it seems that the issue is also visible in light mode and I am **not** using the `Universal Dark Mode` feature.

**Comment by laur89** [comment]
Same on linux.
Chat text is barely readable:
![image](https://user-images.githubusercontent.com/4551018/133237898-15a7192c-a62b-47c3-84d2-81c70f4bec0b.png)

**Comment by SimenB** [comment]
I had to disable dark mode in Ferdi's settings, but enable it within slack itself. Then it looks correct to me (i.e. same as in Chrome)

![image](https://user-images.githubusercontent.com/1404810/142849031-ee8ffee8-1c33-480e-bba1-f8255ce53b5f.png)

**Comment by SDVII** [comment]
I've just tired to 

> I had to disable dark mode in Ferdi's settings, but enable it within slack itself. Then it looks correct to me (i.e. same as in Chrome)
> 
> ![image](https://user-images.githubusercontent.com/1404810/142849031-ee8ffee8-1c33-480e-bba1-f8255ce53b5f.png)

Just tried the fix. Still having the same issue

**Comment by SDVII** [comment]
Seems to be suddenly working out of the blue. Will close this.
