### ISSUE TITLE
Workspace switching shortcut not working

### ISSUE THREAD

**Issue by mattydebie** [getferdi/ferdi#194]
**Describe the bug**
Normally you should be able to use <kbd>ctrl+alt+[0-9]</kbd> to switch between workspaces. Right now only the 0 (all services) works.

**To Reproduce**

1. Add workspaces
2. press <kbd>ctrl+alt+1</kbd>

**Expected behavior**
When using the shortcut, you should switch between workspaces.

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version 5.3.3

**Comment by vantezzen** [comment]
Can't reproduce on macOS Catalina and Ferdi 5.4.3. Do you still face this issue?

**Comment by mhatvan** [comment]
Cannot reproduce this either on Ubuntu with the latest nightly, closing.
