### ISSUE TITLE
[Internal] Fix slow macOS CI pipeline

### ISSUE THREAD

**Issue by mhatvan** [getferdi/ferdi#1942]
With a typical pipeline run:
- macOS takes 36m
- ubuntu takes 23m
- windows takes 16m

We probably should speed up all three of them, but macOS seems to be the slowest.

**Comment by vraravam** [comment]
my suspicion is the install of the specific version of xcode. Maybe we should try it with the default version and check?

**Comment by vraravam** [comment]
we can run the change in a fork - to see if that gets a green build

**Comment by vraravam** [comment]
> my suspicion is the install of the specific version of xcode. Maybe we should try it with the default version and check?

this is not the case - based on the timings from the logs.

**Comment by mhatvan** [comment]
I read somewhere, maybe on electron-builder that people have issues with long build pipelines due to code-signing.

**Comment by mhatvan** [comment]
This doesn't seem to be an issue anymore. Linux builds are now taking the longest time, but that is to be expected since we build for a large variety of packaging formats.
