### ISSUE TITLE
[Internal] Naming conventions of files/folders/components

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1944]
Some files use camel case, some use pascal case, still others use hyphenation for word separation.

We need to adhere to a standard - and enforce it with [lint rules](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/filename-case.md)

**Comment by mhatvan** [comment]
Although I agree that this is helpful to be consistent, I would say it's low priority since we have many open issue tickets.

**Comment by vraravam** [comment]
agreed - which is why I haven't marked it as "high priority"
