### ISSUE TITLE
Allow user to disable recipe automatic updates

### ISSUE THREAD

**Issue by briankendall** [getferdi/ferdi#1949]
**Is your feature request related to a problem? Please describe.**
Recently a change to the Discord recipe introduced a bug. I tried reinstalling previous versions of Ferdi only to find that it didn't resolve the issue. I've found that Ferdi is now automatically updating recipes separately from Ferdi itself, and there's no way to turn it off.

**Describe the solution you'd like**
Given that new recipes may introduce bugs, and that rolling back to previous Ferdi versions does not restore previous recipes, there should be a way to disable updates to recipes, perhaps on a per-service basis, so that users can use older recipe versions if they want, and decide for themselves when they want to update.

(Users very much hate it when they open up an app that was working yesterday only to find it's broken today, even though they did nothing to change it!)

Even better, I'd suggest adding something to the UI that allows rolling back to a previous recipe version and staying fixed on it, until the user disables it.

**Describe alternatives you've considered**
I managed to work around this by manually copying in the older working recipe and changing its version number in `package.json` to something very high, but that's not something we can expect non-programmer users to figure out on their own. At least an option in the UI makes it easily discoverable.

**Comment by vraravam** [comment]
@briankendall - afaik, the auto-update of recipes has been there in Ferdi since when I was just a user (not a contributor).

Though your idea is good, im not sure if this is needed as built-in functionality.

The steps to rollback are quite simple. My suggestion would be to include this in the wiki as a series of manual steps (3-4) that the user can do if/when this rare scenario occurs.

**Comment by kytwb** [comment]
Disabling updates disables recipe automatic updates in https://github.com/getferdi/ferdi/commit/7bffdc7f81dd365858003764beb3a921e6e043e7.
