### ISSUE TITLE
Ferdi suddenly started forcing the use of actual Slack App

### ISSUE THREAD

**Issue by Jixal** [getferdi/ferdi#1951]
Hi,

I've been using Slack within Ferdi for the past 11 months and its been great. However today I received a notification in Ferdi saying that Slack is no longer supported, and now it always forces the app to try and open. Even if its not installed I'll get a locate program dialogue. 

![SlackApp_Locator](https://user-images.githubusercontent.com/59186468/133527582-311b3eda-1ae9-4935-8c1e-f0b07e28135c.jpg)
![SlackFerdi_Broken](https://user-images.githubusercontent.com/59186468/133527585-35d6460a-6621-4c7b-9adf-746acf2f563c.jpg)

Has anybody else encountered this problem or know of a fix?

Cheers,
J

**Comment by vraravam** [comment]
@Jixal - which version of Ferdi do you use? Which version of the slack recipe? Is this behavior evident when you click on a link within slack? Please specify more information.

**Comment by oitray** [comment]
This has been occurring with me as well for about a week. Ferdi 5.5.0
Slack gives a popup that the browser is no longer supported. There is no option other than to use the Slack app. Reloading brings you back to the same window. 

![image](https://user-images.githubusercontent.com/24635338/133615229-8016edd4-f391-4e6d-84a1-f2201e8242a9.png)

If you delete the service and re-add you get the usual window to open slack or use in your browser. But if you click the link to use in the browser it just refreshes back to the same popup. You cannot get past it

**Comment by vraravam** [comment]
@oitray : thanks for the info. I would strongly suggest that you upgrade to the latest version of Ferdi. (5.6.2 as of this point)

As can be seen, this is not something that Ferdi can control. The only solution that I would be able to suggest is to use the service-specific preferences to override the user-agent for this specific service. Ferdi also shows you a couple of websites that you can use for this.

**Comment by Jixal** [comment]
@vraravam I was using 5.5.0 now I'm using 5.6.2, still the same issue.
Slack is 4.19.3
Not sure what you mean about _"Is this behaviour evident when you click on a link within slack?"_
I can't access Slack at all via Ferdi. 
Links within the standalone Slack app or web app work fine.

**Comment by vraravam** [comment]
@Jixal - The version that I wanted to know was the version of slack service/recipe within Ferdi. For eg, the version I am running is `1.3.1`. To find this info, please right click on the Slack service, choose `Edit service`, scroll down and at the bottom, you'll find the version of the recipe.

This is weird - since I also use Slack via okta-oauth setup, and I dont have any of these issues. Can you please confirm if this behavior is present when using a regular browser and accessing slack via the browser? If this works fine, then I would suggest that you override the `user-agent` for the slack service based on your default browser's value. Ferdi allows you to override this setting at a global (within Ferdi) level or at individual services-levels.

**Comment by Jixal** [comment]
@vraravam The current Slack recipe inside my Ferdi is 1.3.0
When using choosing to use Slack via browser, it asks to open the app, which works. I can also choose the option to use it within the browser.
I'm not a developer, so not familiar with user-agent overrides or how to use them properly. I'll just use the default Slack App, hopefully an update will fix this problem in the future for casual users like myself ^_^.

**Comment by vraravam** [comment]
fyi: The `user-agent` can be overridden via the preferences screen in Ferdi: 
<img width="658" alt="Screenshot 2021-09-20 at 8 01 09 AM" src="https://user-images.githubusercontent.com/69629/133952118-fbe37d9d-f96c-407a-b460-b3d6d8854fc2.png">

The above screenshot is for the global override. Service-specific overrides are also possible. The italicized help text tells you which website(s) to use to determine the string for your OS/hardware-architecture/browser combos.
