### ISSUE TITLE
Ferdi no longer working with Slack as it was  

### ISSUE THREAD

**Issue by AndySymons** [getferdi/ferdi#1956]
Not exactly a bug but ... today, suddenly, Slack does not open in the Ferdi window any more. You get a message saying you can open the app or open it in your browser. Is this due to a change of policy at Slack??   

Can anything be done?

**Comment by vraravam** [comment]
Duplicate of #1951

**Comment by vraravam** [comment]
Please see the suggested workaround in this comment: https://github.com/getferdi/ferdi/issues/1951#issuecomment-920878302
