### ISSUE TITLE
Requesting Chrome Update on launching Ferdi with WhatsApp

### ISSUE THREAD

**Issue by ammarmalhas** [getferdi/ferdi#196]
**Describe the bug**
When I launch Ferdi with WhatsApp service, I get a popup saying "WhatsApp needs Chrome version 49+, Update Chrome" which disappears quickly! I do have Chrome v78 but WhatsApp in Ferdi has nothing to do with my installed Chrome version

**To Reproduce**
Launch Ferdi

**Expected behavior**
No such popup should appear and Chrome version warning must not appear in WhatsApp service inside Ferdi.

**Desktop (please complete the following information):**

- OS Mojave 10.14.6
- Browser Firefox v70 and Chrome v78
- Ferdi v5.4.0 beta 4

**Comment by vantezzen** [comment]
Thank you for reporting this bug. This is a known issue in Franz/Ferdi: [franz#1185](https://github.com/meetfranz/franz/issues/1185)

**Comment by ammarmalhas** [comment]
Sorry, I should have searched before reporting :-(
