### ISSUE TITLE
Reopen: Unable to import my franz account #927 - Not Resolved

### ISSUE THREAD

**Issue by joshjacobson** [getferdi/ferdi#1960]
[#927](https://github.com/getferdi/ferdi/issues/927) has been closed, but it does not appear to be resolved across multiple tests. I am unable to reopen that issue directly, so I am opening this here.

**Comment by vraravam** [comment]
@joshjacobson - please provide the exported data file for us to test locally. You can verify that it does not contain any person info in any text editor. Also, which version of Ferdi are you trying to import into?

**Comment by mhatvan** [comment]
Closing this issue as duplicate and reopening https://github.com/getferdi/ferdi/issues/927
