### ISSUE TITLE
Problem with Launching Telegram in Ferdi

### ISSUE THREAD

**Issue by AayeSharky** [getferdi/ferdi#197]
Well, when i try to run the telegram in Ferdi it shows me some type of problems. It depends on difference between connection. Via proxy or Vpn but nothing of it works...
The errors like:
ERR_TIMED_OUT
ERR_CONNECTION_TIMED_OUT
ERR_TUNNEL_CONNECTION_FAILED
And maybe smt else

**To Reproduce**
1. Launch Ferdi
2. Open Telegram
3. Wait till the error shows up.
4. (Have tryed to put the proxy exactly in Ferdi(which in Beta tho) but it didn't help.

![ssd](https://user-images.githubusercontent.com/42211222/68517797-10e6c600-029a-11ea-955f-ae11cdfd7d5a.png)

**Desktop (please complete the following information):**

- OS: Win7
- Browser Chrome 78.0.3904.97 
- Version x64

**Comment by vantezzen** [comment]
Cannot reproduce on Mac, everything is working fine.
Are you able to use Telegram normally in your browser?

**Comment by AayeSharky** [comment]
Nah, it's blocked in our contry, That's why we use proxyes and vpn...

**Comment by vantezzen** [comment]
Ok, I just tried the Proxy functionality and tried using a VPN with Ferdi and it seems to work, [www.whatismyip.com](https://www.whatismyip.com/) reports another IP

**Comment by AayeSharky** [comment]
Well, I have no idea btw, Just waiting for some of engineers response or at least seo...

**Comment by vantezzen** [comment]
I am one of the engineers of Ferdi.
What server are you using for Ferdi?

**Comment by AayeSharky** [comment]
(This&) https://api.franzinfra.com

**Comment by AayeSharky** [comment]
thanks! Waiting for update.

**Comment by kytwb** [comment]
Available since [v5.4.0](https://github.com/getferdi/ferdi/releases/tag/v5.4.0). Let's re-open if something isn't working as expected 🙏
