### ISSUE TITLE
Ferdi 5.6.0 (macOS) not updating after 'new update' notification

### ISSUE THREAD

**Issue by j7e** [getferdi/ferdi#1973]
**Bug description:**
An available update for Ferdi isn't installed when given the option to do so.

**Steps to reproduce:**
1. On startup in version 5.6.0 on macOS, Ferdi presents a notification message saying "A new update for Ferdi is available".
2. Click on the "Restart & install update" button. This Ferdi but doesn't show any subsequent activity.
3. Manually re-open Ferdi.
4. The notification message re-appears until dismissed. In Ferdi's menu bar, go to Ferdi > About Ferdi to confirm the version hasn't changed;

**Expected behavior**
When clicking the 'Restart & install update' button, Ferdi should install the latest update, which can be verified by checking the version number and the update notification bar no longer being shown.

**Environment:**

- Operating System: macOS 10.14.6
- Ferdi Version: 5.6.0
- Server: Ferdi

- Debug information:
When attempting to publish debug information, the following error was given: "There was an error while trying to publish the debug information. Please try again later or view the console for more information."

**Comment by j7e** [comment]
In the meantime, am I able to manually update Ferdi by manually downloading the latest version and copying it into the Application folder to replace the current version?

**Comment by vraravam** [comment]
Yes - in-app updater is broken. (Tracked in #329 )

> In the meantime, am I able to manually update Ferdi by manually downloading the latest version and copying it into the Application folder to replace the current version?

Yes - please update manually by the steps you mentioned.
