### ISSUE TITLE
Per service wake up setting

### ISSUE THREAD

**Issue by shvchk** [getferdi/ferdi#1974]
Service hibernation can be enabled / disabled per service, but auto wake up can only be set globally. Some services need it (e.g. mail, messengers), while others do not (e.g. services for notes, documents, passwords, etc.). Would be nice to have an option to enable / disable auto wake up per service.

**Comment by vraravam** [comment]
I like the idea, and I had thought of this when I implemented the "wake up service" behavior. But, I don't have time to work on this atm. Will wait for any contributor for the same.

That being said, the darkMode setting is the pattern that can be followed (there's a global setting, that can be overridden by the service-specific setting). Please also check the `android-messages` recipe for related changes in the recipe.
