### ISSUE TITLE
Does ferdi allow whatsapp to work without phone being connected?

### ISSUE THREAD

**Issue by horia-m** [getferdi/ferdi#1978]
I'd like to use whatsapp in windows without having to be permanently connected to whatsapp via a phone. Is this by chance working in Ferdi, or it's the same like using whatsapp for windows (so I need to have whatsapp previously online, on a phone, so that the client on the PC can be online too) ?
This would be a great feature... For example Signal works fine like this, but whatsapp - no (with its standard windows app).

**Comment by vraravam** [comment]
This is a limitation imposed by Whatsapp/Facebook. The phone has to have WA installed, and to have an internet connection so that the logged-in user session is validated. If this ping is not successful, the desktop and web clients are immediately invalidated and cannot be used.

**Comment by horia-m** [comment]
@vraravam 
thank you so much for this exact answer! This helps me a lot!
