### ISSUE TITLE
Whatsapp service "Update Available"

### ISSUE THREAD

**Issue by ammarmalhas** [getferdi/ferdi#198]
**Describe the bug**
Upon restarting Ferdi, and after the disappearing Chrome 49+ message the Whatsapp service comes on and shows a message "Update Available ... Click to update WhatsApp".

**To Reproduce**
Restart Ferdi

**Expected behavior**
i expect if there is a real WhatsApp update for it to be installed and done with.

**Screenshots**
<img width="1023" alt="Screen Shot 2019-11-10 at 10 32 14 PM" src="https://user-images.githubusercontent.com/57057209/68550334-f552fb00-0412-11ea-8c23-03e5c8dc8708.png">

**Desktop (please complete the following information):**

- MAC OS: 10.14.6
- Browser Chrome 78
- Ferdi Version 5.4.0 Beta 4

**Comment by ammarmalhas** [comment]
If I may ask, how do I search the site for reported bugs or issues? I want to do so before I file a Bug Report. thanks

**Comment by vantezzen** [comment]
What happens when you click on it? This is a normal behaviour of WhatsApp Web.

**Comment by MichaelBui** [comment]
Actually I've got the same annoy issues. It keeps informing me with new updates and warning my with low Chrome version. Exactly like what @ammarmalhas described above!

**Comment by ammarmalhas** [comment]
It looks like it reloads WhatsApp and continues normally for that session.
The problem is it is doing almost every launch of Ferdi! Even happens if I keep Ferdi open and it goes into a lock screen after a while, entering the passcode then WhatsApp asked to update (but not always)!
I doubt very much that they are producing updates three or four times daily every day for a week!
You have a beautiful software in Ferdi and problems will surely arise from services that you do not really control.
More power to you.
Ammar

> On Nov 11, 2019, at 5:40 PM, Bennett <notifications@github.com> wrote:
> 

﻿
What happens when you click on it? This is a normal behaviour of WhatsApp Web.

**Comment by Ansem93** [comment]
I have similar issue with Rambox, I doubt Whatsapp will update the web version every 1/2 days. Not sure if more often. I usually never "update" it since I barely use whatsapp

**Comment by userferdi** [comment]
Acabei de realizar a atualização do ferro para versão 5.4.0-beta.4. 

E estou com o mesmo problema.

**Comment by ammarmalhas** [comment]
It is still happening with Version 5.4.4-beta.1 (5.4.4-beta.1.1023). When I start I get the Chrome needs updating and it disappears a few seconds later (on its own), then the WhatsApp shows it needs updating, clicking update apparently does nothing and the session continues normally till next start.

**Comment by vraravam** [comment]
@ammarmalhas - is this still an issues? I am running the latest nightlies of Ferdi - and don't see this behavior. Please close if you no longer see this issue.

**Comment by rgpublic** [comment]
This still happens for me. It also happens with similar apps like RamBox etc. But it doesn't happen if you use WhatsApp Web in  a browser. The message in itself is a normal WhatsApp Web message which can also appear in a browser from time to time. Problem is that with Electron apps the message appears way to often (I'd say everyday). You can click it and it reloads, but the next day it's there again. I suspect that the reason is that Electron does sth. differently than a normal browser would do. IMHO, though, it would be nice if Ferdi included proprietary JS code to automatically remove this message. See the comments here: https://github.com/ramboxapp/community-edition/issues/2217 on how to do that.

**Comment by vraravam** [comment]
@rgpublic - In Ferdi, when you edit the preferences for the service, scrolling down, you will notice 3 buttons - the `user.css` can be used to apply that style from the comment that you linked. (The comment is javascript, which is in turn trying to inject css btw).
