### ISSUE TITLE
Images in chats now opens in external browser instead in chat

### ISSUE THREAD

**Issue by propiro** [getferdi/ferdi#1984]
After updating from 5.6.0 to 5.6.2 yesterday, i've noticed VERY ANNOYING behaviour on for example discord service -  when clicking on thumbnail of a picture, it now try to open it in separate browser, instead just opening it on top of the chat - so now whole operation takes 15 seconds instead of .1 secon (my pc is usually busy doing other work, so i dont have browser windows opened, neither want to have anything open in them, thats why I use ferdi - to contain all the instant messaging stuff inside it.)

I dont know if it was deliberate change or its an issue with new version, but at least please give an option to keep opening pictures in ferdi window.

Steps to reproduce:
click on any thumbnailed picture send on discord service

Result:
ferdi opens image in browser window

Expected result:
ferdi opens image on top of chat, like in previous version.

Such desired behaviour is still present in discord web run in rambox or even an browser (it doesnt open new tab/window, just overlays image over the chat, which takes .1 second), so it suggest this is ferdi issue not discord service issue.

**Comment by vraravam** [comment]
This has already been fixed in https://github.com/getferdi/recipes/pull/712 - and was present in a nightly just after 5.6.2

Please upgrade to the latest nightly (they are quite stable) to get this fix.
