### ISSUE TITLE
Slack - Service URL format not quite right for me and I cannot make it work

### ISSUE THREAD

**Issue by leoheck** [getferdi/ferdi#1999]
I cannot set an alternative Team URL for Slack even in the `package.json`
It asks for a service url in the following format
```
"serviceURL": "https://{teamId}.slack.com"
"urlInputSuffix": ".slack.com" <-- this looks duplicated
```

But  my team uses the following url
```
"serviceURL": "https://app.slack.com/client/{teamId}/"
```

I cannot make this work. Still getting `Error: ERR_NAME_NOT_RESOLVED`

I could not find the older thread. But there is a thread where people were discussing this, here.

I am using 

```
Version: 5.6.2
Electron: 13.3.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
Platform: Linux 5.11
Arch: x64
Build date: Mon Sep 13 2021 05:17:08 GMT-0300 (Brasilia Standard Time)
Git SHA: 40a3d0b
Git branch: release
```

**Comment by vraravam** [comment]
@leoheck : Did you try with the `urlInputPrefix`? These 2 strings are used to enable parsing the `serviceUrl` and still match the `teamId` (so they are not duplicated).

**Comment by leoheck** [comment]
What should I do with `urInputPrefix`?

I just kept it as it is as in:
```
"urlInputSuffix": ".slack.com" <-- this looks duplicated
```

I also tried to use it empty.

**Comment by leoheck** [comment]
If the service URL is like this, `https://app.slack.com/client/{teamId}/` then I am assuming from what you have said that the `urlInputPrefix` should be empty or with `/` maybe

**Comment by leoheck** [comment]
And what if we have a field called `teamId` would not be easier?

**Comment by leoheck** [comment]
Well, tried a bunch of things. But since I don't know much how it works, I could not make it work yet. I appreciate any other idea.

**Comment by vraravam** [comment]
please change the `package.json` to use:
```
"serviceURL": "https://app.slack.com/client/{teamId}/",
"urlPrefix": "https://app.slack.com/client/",
"urlSuffix": "",
```

Please get back if this works. The explanations for these can be found [here](https://github.com/vraravam/recipes/blob/master/docs/configuration.md#config-flags)

**Comment by leoheck** [comment]
Oh, I did not know it has a prefix too. Cool!

Alright, this is what is happening now.
Following your instructions, with Ferdi openned, Slack does not work, still.

This is what I put (xxxxxxxxx was replaced by my teamId, of course)
```json
{
  "id": "slack",
  "name": "Slack",
  "version": "1.3.0",
  "license": "MIT",
  "config": {
    "serviceURL": "https://app.slack.com/client/xxxxxxxxx",
    "hasNotificationSound": true,
    "hasIndirectMessages": true,
    "hasTeamId": true,
    "urlInputPrefix": "https://app.slack.com/client/",
    "urlSuffix": "",
  }
}
```

Then if I close and open Ferdi again, I see nothing. There is no services anymore.

Then login out and in again reloads all of my services which is good but Slack is still not working.

If I check the `preferences.json` of Slack service it was reverted back to the original again. This one: 
```json
{
  "id": "slack",
  "name": "Slack",
  "version": "1.3.0",
  "license": "MIT",
  "config": {
    "serviceURL": "https://{teamId}.slack.com",
    "hasNotificationSound": true,
    "hasIndirectMessages": true,
    "hasTeamId": true,
    "urlInputSuffix": ".slack.com"
  }
}
```

**Comment by vraravam** [comment]
Each time you make a change in the recipe, you will need to bump up the version so that the one that was packaged into ferdi does not override it. Please try with my original suggested values - but also bump the `version` to be semantically higher than the version `1.3.0` - so, at least `1.3.1` for eg

**Comment by leoheck** [comment]
@vraravam everytime I edit the package json, it does not load any service. I am pretty sure I am not adding anything that breaks the syntax.

Also, I tried updating the version as you are saying. It did not work. I still have to logout and login back, and it also resets the contents of the package.json. I tried with 1.3.1 as you said, and also with 1.3.0.1.

**Comment by leoheck** [comment]
Should I enable this?  "hasCustomUrl"

**Comment by leoheck** [comment]
I think Ferdi has a bug that it resets the recipie when it sees that it was manually changed. Is this possible?

**Comment by vraravam** [comment]
> I think Ferdi has a bug that it resets the recipie when it sees that it was manually changed. Is this possible?

nope - as a contributor to ferdi, I edit recipes all the time while testing different things during development. I have never had this happen.

I hope that each time you edit the recipe, you are doing it after exiting/quitting ferdi?

**Comment by vraravam** [comment]
> Should I enable this? "hasCustomUrl"

I have not followed the logic in the code if this is enabled alongside the one pertaining to the `teamId`. Please try and see whether that allows you to move forward.

**Comment by leoheck** [comment]
It didn't make any difference. But I think it is not even trying to update the recipe. Since it doesn't load services when the recipe is edited in the first place.

Should I close the app before editing the recipe or it doesn't matter? Should I close it check if editing has worked?

**Comment by vraravam** [comment]
@leoheck - as I said before: YEs ,you will need to close/quit Ferdi BEFORE editing. And each time that you edit, the version number of the recipe should be bumped up. To verify that the new version "has been picked up", you can start Ferdi, go to "Edit Service", scroll down, and see the version on the bottom of the page

**Comment by leoheck** [comment]
I see. I have tried that. Just wanted to make sure I was following the right (known/recommend) way of doing it. But I am doing exactly what you are saying.

**Comment by vraravam** [comment]
did you try the other config options that are listed in the [configuration doc](https://github.com/vraravam/recipes/blob/master/docs/configuration.md#config-flags).

Without at least the full url of what you are trying to configure and connect to, I wont be able to debug much more

**Comment by leoheck** [comment]
So, I was able to update the service since I saw, my new version being loaded. Finally. Ferdi does not need to be closed, but it has to be restarted to reload the edited recipe.

Now, going back to the issue. This `"hasCustomUrl": true` is promising since  my service has this URL

```
"serviceURL": "https://app.slack.com/client/{teamId}",
```

Now, how it works? Where should I put this custom URL? The documentation states this:

> A boolean field

![Screenshot-20210930110509-890x105](https://user-images.githubusercontent.com/1277920/135471247-84334cf9-05d7-4248-8749-8342febbd9a4.png)

> And here it says this field has nothing to do with custom URLs

![Screenshot-20210930110959-889x195](https://user-images.githubusercontent.com/1277920/135471308-1db52022-73ec-45a1-bae0-0fd61500b0b3.png)

**Comment by leoheck** [comment]
If I use this:

```
"urlInputPrefix": "https://app.slack.com/client/",
```

Then the GUI shows this value duplicated.

![image](https://user-images.githubusercontent.com/1277920/135474557-2b3dc46f-f382-4aca-8c74-7b0105ff5670.png)

**Comment by leoheck** [comment]
If I remove serviceURL keeping the prefix, the recipes won't load.

**Comment by leoheck** [comment]
If I put the teamId only in the serviceURL, then it loads the recipe but the fields remain duplicated
serviceURL

![image](https://user-images.githubusercontent.com/1277920/135475059-fe3f251b-1da8-456e-aadb-92be4f30bae5.png)

**Comment by vraravam** [comment]
you can always remove the `hasTeamId`, and set the `hasCustomUrl` - that will give you the most customizable option

**Comment by vraravam** [comment]
> I expect that the GUI, if there is no bug, shows me something like this `https://app.slack.com/client/` `xxxxxxxxx`

This should be possible with the `urlInputSuffix` option

**Comment by leoheck** [comment]
Alright, this is what I have now. Maybe something is not needed but I will keep it like this for now since I was able to make it work. 

```json
{
  "id": "slack",
  "name": "Slack",
  "version": "1.3.2",
  "license": "MIT",
  "config": {
    "serviceURL": "https://app.slack.com/client/",
    "urlInputPrefix": "TEAM_ID_HERE", # <= change this
    "urlInputSuffix": "https://app.slack.com/client/", # <== This is wrong but it is being ignored I think.
    "hasTeamId": true,
    "hasNotificationSound": true,
    "hasIndirectMessages": true,
    "hasCustomUrl": true # <=== it cannot have a comma here.
  }
}
```

And then, I had to login with my slack account and authenticate the service again.

Any possible issue with the recipe syntax makes all recipes fail. It would be good if Ferdi could to validate the json before loading it, to at least be able to drop it to have at least some services working. _Just a thought actually._

**Comment by vraravam** [comment]
1) The presence of a comma for the last line in a struct in javascript will cause failure - that's a language feature.
2) Great that you finally got it working. But, i would suggest that you try out removing those keys whose values are the default as described in the documentation. This will shield you from new pain due to unnecessary code as the underlying code evolves in the future.

**Comment by leoheck** [comment]
Nice. I will try to remove, sure. Thanks for the help and the patience @vraravam ! You always help me a lot.
