### ISSUE TITLE
Navigation shortcuts/actions and/or context menu

### ISSUE THREAD

**Issue by RJVB** [getferdi/ferdi#2017]
**Is your feature request related to a problem? Please describe.**
Certain services are more in the form of a generic web page than others. For instance, the Instagram service is really just the IG desktop version in a rather basic browser. It may load in the DM view, but the other views are just as readily accessible as they are in a full-blown browser. The FB Messenger service also gives access to other Facebook views (e.g. profiles) though a little less easily.
What's missing here is a possibility to navigate back to a previous page. In Instagram you can always click on the Home or DM icons, but even that is a bit cumbersome as you don't necessarily always want to go that far.

**Describe the solution you'd like**
I'd like the usual "Go back" "Go forward" navigation options, with a keyboard shortcut and possibly the corresponding menu items/actions. Enabling the webview context menu could be useful too in this context.

**Describe alternatives you've considered**
I presume that activating the context menu and/or defining keyboard shortcuts for common navigation actions *might* be possible via `user.js` injection ... but I have no idea how. I'd be interested to experiment though.

**Comment by vraravam** [comment]
hi @RJVB : Thanks for trying out Ferdi.

All of these options (shortcut keys, title-bar menu options and context menu options) are available already to navigate back and forward similar to a normal browser - without the need for any hacks in the `user.js`.

**Comment by RJVB** [comment]
My bad, I don't understand why they didn't show up for me yesterday when I realised I missed them! But since you mention hacking: is there a way to edit the keyboard shortcuts (I'm used to Alt+Left and Alt+Right for history navigation)?

**Comment by vraravam** [comment]
Yes - unfortunately, these are "baked into" the code, ie not configurable from a properties file or anything
