### ISSUE TITLE
Encountering error when trying to register new account

### ISSUE THREAD

**Issue by flora-fischbacher** [getferdi/ferdi#2039]
**Bug description:**

Unfortunately I was not able to complete the sign up process without quitting the application and restarting it. 
After filling out my name, email etc. and clicking "_create account_" I was redirected to the "_Let's get started_" page. Here I selected the relevant services. 

After clicking "_Let's go_" I saw the spinning wheel animation but was not redirected to the main application window. After clicking a few more times I quit the application and restarted it which finally lead me to the main application window. Unfortunately the services I had selected in the "_Let's get started_" section were now being displayed more than once, I presume this is because I pressed the "_Let's go_" button more than once.

**Steps to reproduce:**

1. Go to 'Create a free account'
2. Click on 'Create account'
3. Select services
4. Click on 'Let's go'
5. See errors in dev tools

**Expected behavior**

After clicking on "Let's go" I would expect to be directed to the main application menu where the previously selected services are displayed only once, not the amount of times I clicked on the "Lets go" button.

**Screenshots**

<img width="660" alt="Screenshot 2021-10-08 at 13 41 13" src="https://user-images.githubusercontent.com/56727520/136553304-422f9ad0-4a55-4a85-9d3a-c9c974fc9ce9.png">

<img width="827" alt="Screenshot_2021-10-08_at_13_41_22" src="https://user-images.githubusercontent.com/56727520/136553386-aaa02db4-f1c3-4f51-a89b-10651279c051.png">

<img width="623" alt="Screenshot_2021-10-08_at_13_42_01" src="https://user-images.githubusercontent.com/56727520/136553509-6660f015-a64b-4dbc-acdb-b845364c86ce.png">

**Environment:**

- Operating System: macOS Catalina
- Ferdi Version: 5.6.3-nightly.27
- Server: Ferdi

- Debug information:

**Comment by kytwb** [comment]
I ran into this issue locally.

**Comment by kytwb** [comment]
<img width="1552" alt="Screen Shot 2021-12-11 at 7 16 30 PM" src="https://user-images.githubusercontent.com/412895/145687578-1e5312c2-89a0-4bfd-928c-d6180eeadfa0.png">
