### ISSUE TITLE
Upgrade `react-router` since this is a pre-requisite for upgrading `mobx`

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#2040]
Prerequisite for #1543 

related reading: https://github.com/remix-run/react-router/blob/main/packages/react-router/docs/guides/migrating.md

**Comment by SarveshLimaye** [comment]
Yeah would try to complete pr by 10-10-2021.  Would try my best to do it at earliest.  I should upgrade it react-router v4 right?

**Comment by SarveshLimaye** [comment]
@vraravam I have upgraded react-router but the code is breaking a lot. I have resolved almost all the errors but I am getting this error constantly.

![image](https://user-images.githubusercontent.com/74766567/136681458-5023e3ef-c8c5-459e-9f0e-af8c381f570c.png)


Could you pls help me with this

**Comment by vraravam** [comment]
@SarveshLimaye - if you have raised a PR - I can try to download your fork and try to fix. Without it, its going to be impossible to guess based on the screenshot (its quite blurred as well)

**Comment by SarveshLimaye** [comment]
Yeah sure
