### ISSUE TITLE
Running Ferdi in a browser - e.g. off your website?

### ISSUE THREAD

**Issue by RJVB** [getferdi/ferdi#2044]
Ferdi runs in Electron, which is essentially a web browser, right? I've been wondering this about Franz before too: could the code be built in such a way that it can be run in a generic web browser?

The point: you could then host this build yourself, giving people the possibility to connect to their account from any computer with a sufficient browser (probably even from any mobile device).

**Comment by vraravam** [comment]
This is actually how Station pivoted. But, this level of pivoting would require a dedicated team of folks. which is not possible at this point in time.

**Comment by RJVB** [comment]
>So looking at it like this is like asking if you could run Firefox within Chrome

No?! Parts of Firefox probably could run within Chrome, but certainly not everything, AFAIK.

> but most of us have a preference to having these in a dedicated app.

If we disregard (the) dedicated ("official") apps on mobile devices, to what extent do you think people prefer to use a multi-chat app because it's 1) a standalone app or 2) just something that combines your various chat accounts in a single window? I was a big fan of Adium back in the day when dedicated apps had the advantage of being much more lightweight than a webbrowser, but these days where those non-web APIs have almost completely gone I'd guess it's mostly point (2) (and maybe point (1) from those who still believe that multi-chat apps like Franz/Ferdi are still leaner than running a browser).
>
>BTW this idea would work if Ferdi was a custom client that connected to these services through open APIs

Are you telling me that Ferdi doesn't just present the Messenger/Whatsapp/Hangouts/Skype/etc. web pages just like a browser would?

> This is actually how Station pivoted. But, this level of pivoting

Pivoting?

**Comment by RJVB** [comment]
>Ferdi/Franz (and possibly the other electron-based apps) are deeply intertwined with the electron APIs so much so that what you are suggesting would mean a complete, ground-up rewrite. This is what Station did. Afterwards, they open sourced their desktop app.

Got it. Or Electron would have to provide a glue library that maps their APIs to what's available in standard browsers, I presume.
