### ISSUE TITLE
Telegram React notification with no sound

### ISSUE THREAD

**Issue by Naviol** [getferdi/ferdi#2060]
I'm using version 5.6.2 on Windows 10 pro and MacOS Big Sur.
Telegram React notification no sound
![image](https://user-images.githubusercontent.com/30588505/137090053-a7dcec79-1b1c-41ee-ac00-5aa8382c5816.png)

**Comment by mhatvan** [comment]
Verified again that the sound on incoming notifications works as expected, tested with WebK version 0.9.1

It might not be enabled by default, you can do that by going to "Settings" > "Notifications and Sounds" > "Notification Sound" and toggle it to be enabled.
