### ISSUE TITLE
do not add service if not logged in

### ISSUE THREAD

**Issue by userferdi** [getferdi/ferdi#208]
Guys, find out ferdi this week. and did all installation on my notebook (Windows 10 Original). I read all the content on the site (getferdi.com) but realized that in this stable version available on the site. There are some bugs. First, I would like to know how do I access ferdi without registering? because according to information from the site, informs that it is possible to use without signing in. But that's not true. because when trying to add any service it goes into loop and does not load the service. but if you are logged in to the account. Everything works, remembering that the api remains the same, nothing has changed, just installed the ferdi and opened it. Another thing that the staff reported, was that the login problem was due to permission of the folder ferdi (read) but changed the permission and still does not work without login. ferdi version 5.3.3

**Comment by vantezzen** [comment]
Thank you for trying out Ferdi! Using Ferdi without an account is currently only possible with the latest beta version, not the stable version yet. Please update to the beta or download the latest beta on the releases tab on GitHub

**Comment by userferdi** [comment]
@vantezzen ok. I will do that. I wanted to help with the translation, is it possible? how should I proceed? I am from Brazil and I do not speak English. and the available translation is not completely ready. I wanted to help anyway. if you can help, in my language and in spanish. let me know and explain how I do it. OK big hug to you and the whole team. Sorry if my words are not so explanatory, I am using Google translator.

**Comment by Makazzz** [comment]
@userferdi You can translate in your language with [Crowdin]¸(https://crowdin.com/project/getferdi) and after creating an account on this website you will have access to the translation.
