### ISSUE TITLE
Build fails probably due to spellchecker

### ISSUE THREAD

**Issue by AGCaesar** [getferdi/ferdi#209]
Building latest Ferdi git fails:

make: *** [spellchecker.target.mk:121: Release/obj.target/spellchecker/src/main.o] Fehler 1
make: Verzeichnis „/tmp/yaytmp-1000/ferdi-git/src/ferdi/node_modules/@felixrieseberg/spellchecker/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.3.11-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/yaytmp-1000/ferdi-git/src/ferdi/node_modules/@felixrieseberg/spellchecker
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @felixrieseberg/spellchecker@4.0.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @felixrieseberg/spellchecker@4.0.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/caesar/.npm/_logs/2019-11-14T21_02_49_746Z-debug.log
==> FEHLER: Ein Fehler geschah in prepare().
    Breche ab...

Arch Linux, latest Kernel etc...
Not sure what the problem is...

**Comment by vantezzen** [comment]
This looks to be a problem in `electron-spellchecker`: https://github.com/electron-userland/electron-spellchecker/issues/165

**Comment by AGCaesar** [comment]
Any easy way to disable spell checker plugin on build to temporarily fix this?

**Comment by kytwb** [comment]
We can temporarily fix by using a hardcoded version `electron-spellchecker` (the last known working release) instead of letting semantic versioning pick up the faulty version.

**Comment by AGCaesar** [comment]
If you give me a hint where to look I can try writing a small patch for the arch installer only

**Comment by kytwb** [comment]
I just took a look and it's coming from a dependency of dependency, so we can't fix it the way I mentioned previously. I have mentionned the author of the dependency's dependency in [this comment](https://github.com/electron-userland/electron-spellchecker/issues/165#issuecomment-555481892) as we can't open issues on the faulty dependency repository.

**Comment by kytwb** [comment]
Not sure what happened there (semver mishap?) but this doesn't seem to be an issue anymore.
