### ISSUE TITLE
Sidebar on the bottom of the window

### ISSUE THREAD

**Issue by ThomasWeber** [getferdi/ferdi#2090]
I like love the sidebar horizontal option, but I it would be great if there were an additional option to have the horizontal sidebar at the bottom of the window instead of the top.

Thanks!

**Comment by vraravam** [comment]
I can see some users liking this placement - but, this needs some contributions from outside the current core team of 2. Happy to review any PRs that get raised.

**Comment by niutech** [comment]
It should be easily done in CSS:
 - in `.sidebar` replace `top: 0;` with `bottom: 0;`
 - in `.app .app__content` replace `padding-top: 97px;` with `padding-bottom: 97px;`
 - in `.tab-item.is-active` replace `border-top-width: 4px; border-top-style: solid;` with `border-bottom-width: 4px; border-bottom-style: solid;`

**Comment by vraravam** [comment]
@Jinal2711 - i had assigned this to you 28 days ago. Still waiting for a PR

**Comment by Jinal2711** [comment]
Hi Getferdi/Ferdi,

I will complete this Today. But I have one query.
Should I create 2 check box for use top horizontal style and use bottom
horizontal style??

Thanks,
Jinal Vaghasiya

**Comment by vraravam** [comment]
@Jinal2711 - yes that would be something that I would like to see in the preferences screen. Without it, I dont think the user would be able to change it in a non-tech-savvy manner

**Comment by niutech** [comment]
A `<select>` field with {top, bottom, left} instead of two checkboxes would be more appropriate in my opinion.

**Comment by kytwb** [comment]
Closing in favour of https://github.com/getferdi/ferdi/issues/2379.
