### ISSUE TITLE
[bug] Trying to add Outlook accounts doesn't work

### ISSUE THREAD

**Issue by AmodeusR** [getferdi/ferdi#2093]
**Bug description**

 Trying adding an Outlook service doesn't work. When I click to add it, it doesn't do anything other than reproducing a mouse loading animation for half a second.

 I added other services and it worked fine.

**Steps to reproduce**

I think you just need to try adding an outlook service, that was what I did and it didn't work.

**Expected behavior**

Load config page tab for configuring the outlook service.

**Environment**

- Operating System: Windows 10, 64 Bits
- Ferdi Version: 5.6.2
- Server: Using without an account

- Debug information: https://pastebin.com/hS681n54

**Comment by AmodeusR** [comment]
I checked the recipes on https://github.com/getferdi/recipes/tree/master/recipes, and it seems Outlook recipe doesn't exist there actually, which probably is the reason it's not working.

**Comment by mhatvan** [comment]
I also receive two results when I search for "outlook". Verified that I don't have any local ferdi recipes called outlook. Maybe it is also related to the server need to be redeployed?

**Comment by vraravam** [comment]
@kytwb @vantezzen - could you please redeploy the hosted server? so that this issue can be closed?
