### ISSUE TITLE
Ferdi fails to start with ICU 65

### ISSUE THREAD

**Issue by AGCaesar** [getferdi/ferdi#210]
I got an update to ICU 65 http://site.icu-project.org/home and ferdi fails to start. Downgrading to ICU 64 fixes the problem. Might be related to #209 
Arch Linux, latest updates.

**Comment by vantezzen** [comment]
Does Franz have the same problem?

**Comment by AGCaesar** [comment]
Franz 5.3.3 does work

**Comment by kytwb** [comment]
Is this still relevant?

**Comment by AGCaesar** [comment]
Sorry, I was away on holiday. Everything works now, thanks!
