### ISSUE TITLE
Service CMD+num shortcut not working

### ISSUE THREAD

**Issue by ClaireBookworm** [getferdi/ferdi#212]
The `cmd+num` command doesn't work--can't switch services. When mouse hovers over service names, there is a `cmd+3` (or whatever number) prompt but it never works. This might be a just be a problem with my computer, but if it's not, this feels like quite a core feature...

**Specs**
- OS: macOS Catalina
- Version 5.3.3

**Comment by vantezzen** [comment]
Is this a duplicate of #204?

**Comment by ClaireBookworm** [comment]
No, this persists even after immediately adding a service...

**Comment by kytwb** [comment]
I haven't been able to reproduce.  
@ClaireBookworm do you still experience the issue with the latest update?

**Comment by kytwb** [comment]
Closing for now, please let us know if that is still an issue.
