### ISSUE TITLE
Window title should also reflect the current application's title

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#213]
**Is your feature request related to a problem? Please describe.**
I use KeepassXC for my password manager. In it, I have setup a global shortcut to be able to auto-type my username and password when I am on a login page for some services that are configured within ferdi (for eg my github page). When I try the shortcut, the event is sent to the password manager with a title of only "Ferdi". Without the specific app-service that I am trying to use it for, the password manager then doesn't return any matches.

**Describe the solution you'd like**
Could you please include the page name (for eg, "Ferdi - Github login" or something similar) in the window title? As I navigate between different services configured within Ferdi, the window title should refect that change.

**Describe alternatives you've considered**
None - other than copy-pasting my username/password from the password manager and pasting it into Ferdi.

**Additional context**
<img width="420" alt="Screenshot 2019-11-19 at 8 51 00 AM" src="https://user-images.githubusercontent.com/69629/69113700-c3443780-0aa9-11ea-8a5c-1a5ea2d38062.png">

**Comment by gmarec** [comment]
Hi 

I have just done a quick fix for this, need to use keeWeb also ;-) 
https://github.com/gmarec/ferdi/commit/191e0bdf1aa4f6ff615edfeae98329da2e1a463c
 
Thanks

**Comment by kytwb** [comment]
@gmarec Awesome, can you please submit a pull request? 🙏 
Thank you!

**Comment by gmarec** [comment]
> @gmarec Awesome, can you please submit a pull request? 🙏
> Thank you!

done ;-)

**Comment by frankhommers** [comment]
Just what I needed! (I was entering a new feature request for this when this issue showed up as similar). When you've released the binaries I will test this!

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.3).

**Comment by frankhommers** [comment]
Confirmed it's working in Windows
![image](https://user-images.githubusercontent.com/7355878/76636593-9f6d9b80-6549-11ea-914d-03f10e118f94.png)

**Comment by frankhommers** [comment]
Confirmed (by using a piece of applescript) it's working on macOS as well
