### ISSUE TITLE
Preferences overlay doesn't paint properly on macOS Catalina

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#214]
**Describe the bug**
Please see the screenshot. The settings window doesn't "paint" completely/properly.

**To Reproduce**

1. Go to Preferences option
2. See error

**Expected behavior**
The preferences window/overlay is shown completely so that I can set/unset options and click on "Save"

**Screenshots**
<img width="1193" alt="Screenshot 2019-11-19 at 9 01 00 AM" src="https://user-images.githubusercontent.com/69629/69114470-7d886e80-0aab-11ea-9b08-0efd7f9df052.png">

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser Ferdi
- Version 5.4.0-beta.4 (5.4.0-beta.4.779)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kytwb** [comment]
Is this a recurrent thing? Have you tried toggling (restart for changes to take effect) GPU Acceleration in the settings? What about with the latest beta? We have upgraded to Electron 7 since, maybe that helps?

**Comment by vraravam** [comment]
I am now on the latest beta (5.4.4-beta.1.1023) - and this issue has not recurred.

**Comment by kytwb** [comment]
@vraravam thank you for following up! 🙏
