### ISSUE TITLE
Multiple/Duplicate services(recipes) available to choose from.

### ISSUE THREAD

**Issue by razkif** [getferdi/ferdi#2152]
**Bug description:**
Duplicate services are being shown, unsure which is the latest service.

**Steps to reproduce:**

Add new service
Search for "drive"
two services show instead of one.
search for "voice"
two services show instead of one.
search for "glowing"
two services show instead of one.

**Expected behavior**
Expected to see only one service 

**Screenshots**

![image](https://user-images.githubusercontent.com/19786399/139022781-1f6889ee-8680-4ce2-9ea3-970102c8d0e2.png)

![image](https://user-images.githubusercontent.com/19786399/139022689-b8fe86c4-80e1-4fac-bba1-7ca0475ab4d2.png)

![image](https://user-images.githubusercontent.com/19786399/139024087-e57ba5e9-bd00-4a89-8095-62a40c3e0093.png)

- Operating System: 
Windows 11
Version: 5.6.2
Electron: 13.3.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
Arch: x64
Git SHA: 40a3d0b
Git branch: release

- Server: No account

- Debug information:

**Comment by kytwb** [comment]
Fixed via getferdi/server@e4a7fcb.

![Screen Shot 2021-12-31 at 2 51 04 PM](https://user-images.githubusercontent.com/412895/147826650-878c84e3-35b7-4e97-9580-336972c9d539.png)
![Screen Shot 2021-12-31 at 2 50 10 PM](https://user-images.githubusercontent.com/412895/147826605-2b7dee89-ff2c-439e-b1ed-3d7de8080598.png)
![Screen Shot 2021-12-31 at 2 50 20 PM](https://user-images.githubusercontent.com/412895/147826610-59acfd67-34c2-4767-88b2-0f953001a829.png)
