### ISSUE TITLE
Custom service greyed out, unable to add and/or use

### ISSUE THREAD

**Issue by Rawh** [getferdi/ferdi#217]
**Describe the bug**
When adding custom services, there's a colored square around the service which says Premium is required. When you go to the account details page, it says you already have premium Ferdi service enabled.

**To Reproduce**
1. Add a custom service to your %appdata% directory.
2. Reload Ferdi
3. Add a new service
4. Select the Custom Tab
5. The custom service is greyed out

**Expected behavior**
The ability to add and use the custom service

**Screenshots**
![image](https://user-images.githubusercontent.com/10486655/69453305-f285cd80-0d63-11ea-97aa-c56df800e3b8.png)

![image](https://user-images.githubusercontent.com/10486655/69453465-40023a80-0d64-11ea-8831-5a42425bd23e.png)

**Desktop**

- OS: Windows 10 1903 (build 18362.476)
- Ferdi.Setup.5.3.3

**Comment by vantezzen** [comment]
Which server are you using?

**Comment by Rawh** [comment]
My own personal, running in a docker container

**Comment by mhatvan** [comment]
Hey @Rawh, this issue is really old! Do you still experience this behavior with the newest release?

**Comment by Rawh** [comment]
No all is fine, ill close thee issue!
