### ISSUE TITLE
Shortcut and context menu action to enable/disable current service

### ISSUE THREAD

**Issue by MrChocolatine** [getferdi/ferdi#2171]
**Is your feature request related to a problem? Please describe.**

My request is not related to a problem, it is a suggestion to facilitate the usage of Ferdi.

**Describe the solution you'd like**

I would like to have a keyboard shortcut, and a context menu action, to disable/enable the current service I am using.

As an example, you already provide the shortcut `Disable notifications & audio` (binding <kbd>Shift</kbd> + <kbd>Command</kbd> + <kbd>M</kbd> on macOS).

**Describe alternatives you've considered**

None.

But this action can already be done when right clicking on a service and choosing the option `Disable/Enable service`.

**Additional context**

Request very similar to #1638 , but here the suggestion aims only the service currently used.

**Comment by vraravam** [comment]
#2148 was merged just a few hours ago - please see that ticket for screenshots.

This will appear in the next nightly.

**Comment by MrChocolatine** [comment]
Perfect, thank you and sorry @vraravam I missed that PR.
