### ISSUE TITLE
Can I add Google Docs as a standalone service?

### ISSUE THREAD

**Issue by rssowmiyan** [getferdi/ferdi#2177]
Newbie here
I couldn't find google docs in the available services. 
So I was just wondering if I could add it😅

**Comment by vraravam** [comment]
@rssowmiyan - sure, if you think its valuable, please go ahead. btw, there's already google drive - from which one can create docs, spreadsheets, etc

**Comment by vraravam** [comment]
Closing the ticket - since the recipe needs to be added in the [http://github.com/getferdi/recipes](recipes) repository.
