### ISSUE TITLE
Services not the same over multiple devices (same account)

### ISSUE THREAD

**Issue by Rawh** [getferdi/ferdi#218]
**Describe the bug**
Services seen on screen are empty on laptop, while they are filled on the pc. Is this proxy related?

**To Reproduce**

1. Login to pc at home
2. Screen is loaded with services.
3. Login with laptop at work
3. Nothing is shown.

Adding new services results in nothing. 

When looking with "view" -> "Development tools", I get the following error
![image](https://user-images.githubusercontent.com/10486655/69523282-ccc71700-0f63-11ea-82d9-663ac3bcff3e.png)

**Expected behavior**
See my services and continue with them.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win 10 1903 18362.418
- Browser n/a
- Version
![image](https://user-images.githubusercontent.com/10486655/69522735-6c83a580-0f62-11ea-8742-f78f2fc82e6a.png)

**Additional context**

**Comment by vantezzen** [comment]
It looks like Ferdi isn't able to install new recipes on your system. Could you please try to update to v5.4.0?

**Comment by Rawh** [comment]
Update fixed it
