### ISSUE TITLE
Javascript error on Ferdi-Setup-5.6.3-nightly.52

### ISSUE THREAD

**Issue by AGonLen** [getferdi/ferdi#2181]
I got the below error after installing Ferdi-Setup-5.6.3-nightly.52.   Reverting to Ferdi-Setup-5.6.3-nightly.50 worked, but there's a bug on nightly-52.

**Environment:**
- Operating System: Windows 11
- Ferdi Version: Ferdi-Setup-5.6.3-nightly.52

![image](https://user-images.githubusercontent.com/24992203/140479970-7000321b-7aaf-4c75-b720-89e947925052.png)

**Comment by MagicLike** [comment]
Similar error on Windows 10 21H1 when updating from 5.6.3-nightly.50 to 5.6.3-beta.4.

![Ferdi_QHPgw3tsMi](https://user-images.githubusercontent.com/82117109/140642717-30674268-ce16-4f4c-a79a-042a51c0693c.png)

**Comment by MagicLike** [comment]
@AGonLen It works again for me, when updating to 5.6.4-nightly.1 and future versions

**Comment by vraravam** [comment]
Yes, I had fixed this in #2195 - please use one of the latest nightlies for overcoming this issue.
