### ISSUE TITLE
Zimbra logo not working

### ISSUE THREAD

**Issue by AGonLen** [getferdi/ferdi#2188]
The Zimbra logo is not working and not displaying in the services

**Environment:**
- Operating System: Windows 11 Pro
- Ferdi Version: 5.6.3-nightly.54

![image](https://user-images.githubusercontent.com/24992203/140662184-bae62df2-cab5-4662-adf1-1241787051b4.png)

**Comment by kytwb** [comment]
Fixed via https://github.com/getferdi/recipes/commit/32de5dc57afe1ee878122fa50f33e381e54655ac.

<img width="381" alt="Screen Shot 2021-12-23 at 3 08 12 PM" src="https://user-images.githubusercontent.com/412895/147251554-504f0226-7379-4b88-95a5-0c84e89f80f2.png">
