### ISSUE TITLE
Update logged me out of everything

### ISSUE THREAD

**Issue by Stanzilla** [getferdi/ferdi#219]
I just updated from -beta4 to final 5.4.0 and it logged me out of my Ferdi account and every service. is that normal?

**Comment by vantezzen** [comment]
Were you using a Franz account to log into Ferdi? Ferdi 5.4.0 switched to using the Ferdi API instead.
Other than that, are you able to log back in and use Ferdi normally?

**Comment by Stanzilla** [comment]
I used a Franz account but "converted" it to a Ferdi account when I first started using it. And I used that same account to log in today as well, yea. It does work normally after I go through every service and login again

**Comment by Stanzilla** [comment]
Oh darkmode.css no longer work, they used to work in the beta unlike here https://github.com/getferdi/ferdi/issues/158

**Comment by kytwb** [comment]
@Stanzilla are you on Windows?

**Comment by Stanzilla** [comment]
@kytwb yup, 10 1909

**Comment by kytwb** [comment]
@vantezzen could it be https://github.com/getferdi/ferdi/pull/167 that is responsible for the issues with Windows? Also permission error?

**Comment by Stanzilla** [comment]
Could be, I see no migration in that PR

**Comment by Stanzilla** [comment]
Is it safe to upgrade now?

**Comment by vantezzen** [comment]
Did these errors reoccur on any of the later updates, especially the 5.4.3 update?
Otherwise I think this issue we could close this issue if it was really just the jump to 5.4.0.

**Comment by Stanzilla** [comment]
I haven't tested 5.4.0-beta4 to 5.4.3 finals but it did not happen from any later releases to 5.4.x
