### ISSUE TITLE
MS Teams left click on links not working

### ISSUE THREAD

**Issue by karolkpl** [getferdi/ferdi#2193]
Left click on links posted in "Teams/Rooms" conversations is doing nothing (it should open the link in system browser). Right click + Open link works.
Left click is working in "Chat" conversations.

Tested on version 5.6.2 and 5.6.3 under linux.

**Comment by vraravam** [comment]
As a workaround, please use the right-click to choose "open link in Ferdi" or "open link".

We have been contemplating revamping the link/url handler code to be more amenable to expose this behavior as preferences that the user can control - but, with other priorities, this hasn't made it into the list till date. We will be very glad to accept code contributions to help implement the same.

**Comment by vraravam** [comment]
Duplicate of #1501
