### ISSUE TITLE
Linux Libinput Scroll Coasting/ kinetic scrolling/ inertia scrolling

### ISSUE THREAD

**Issue by youssefahmedsamy** [getferdi/ferdi#2194]
My request is just as simple as implementing coasting, otherwise known as kinetic scrolling, for the touchpads using the libinput driver. This is done by a lot of GTK apps, including firefox, so I'm wondering if you would be fine putting this on any sort of future plan? Thank you.

(Brief description of feature: you scroll fast with the touchpad and lift your hands and it continues scrolling for a short while, kinda like on mobile phones).

**Comment by vraravam** [comment]
This needs to be supported by electron. Please check if they support this feature.
