### ISSUE TITLE
Ferdi not opening from tray after last update

### ISSUE THREAD

**Issue by pjom** [getferdi/ferdi#2197]
Hi, guys.

I've just updated Ferdi to the latest version and since then I don't seem to make the window show when double clicking the tray icon, nor selecting the "Show Ferdi" option from the tray menu.
In order to open the window, I have to use the application's shortcut.

Windows 10 - 64 bits

Paulo

**Comment by geofausto** [comment]
Same here. Linux Mint 20.2 Cinnamon.

**Comment by vraravam** [comment]
Duplicate of #2147
