### ISSUE TITLE
Telegram service doesn't work

### ISSUE THREAD

**Issue by rssowmiyan** [getferdi/ferdi#2198]
- I get this error after adding the telegram service
--------------------------------
![image](https://user-images.githubusercontent.com/51026146/140924589-002d7c6a-d5b5-449c-be63-3e9f75c22503.png)
--------------------------------------------------
-  Pardon, Am I doing something wrong here?

Operation system : Windows 10
Version                  : 5.6.3

**Comment by vraravam** [comment]
Please edit the `package.json` in the recipes folder for telegram to:
`"serviceURL": "https://webk.telegram.org",`

please note the `webk` instead of `web` - this seems to fix the issue for users in India.
