### ISSUE TITLE
Uncaught Exception at startup after an update. Stable release on MS Windows 8.1.

### ISSUE THREAD

**Issue by crazed-translator** [getferdi/ferdi#2211]
**Bug description:**

When starting the app from either the taskbar or the desktop shortcut, the app crashes displaying the window in the attachment.

**Steps to reproduce:**

1) Have the app update itself to the lastest version
2) Open the app
3) See the error

**Expected behavior**

App starting up normally

**Screenshots**

![image](https://user-images.githubusercontent.com/32799935/141260200-bb3b47d8-27dc-44f0-a591-dc38838d6be6.png)

**Environment:**

- Operating System: Windows 8.1 x86 
- Ferdi Version: Lastest stable (update downloaded and installed automatically) 
- Server: Using without an account 

- Debug information:

Cannot paste the debug info because the error window won't let me copy the contents

**Comment by crazed-translator** [comment]
Uninstalling the app and installing version 5.6.3 also causes the crash.
[https://github.com/getferdi/ferdi/releases/download/v5.6.4-nightly.2/Ferdi-5.6.4-nightly.2-ia32.msi](url) works fine.

**Comment by MagicLike** [comment]
Duplicate of #2181, only the error message is kinda different.

**Comment by crazed-translator** [comment]
also #2078 but yeah, error message is different

**Comment by crazed-translator** [comment]
As an update, the current stable release doesn't seem to have the same problem. Closing the issue for now...
