### ISSUE TITLE
[ Feature Request ] Update Zoho Mail Default URL

### ISSUE THREAD

**Issue by 8227846265** [getferdi/ferdi#2215]
**Is your feature request related to a problem? Please describe.**

- When you added Zoho Mail and logged in, and you reload Zoho Mail. This is the first thing you will see every time.
![image](https://user-images.githubusercontent.com/66582769/141387282-2a6becf1-f0e4-44ba-b86f-74697b11e59f.png)

You have to click "Access Zoho Mail" every single time just to see your Inbox!

**Describe the solution you'd like**
Change the default URL to https://mail.zoho.com/zm/

This will load the Inbox immediately every fresh instance.

**Describe alternatives you've considered**
Creating Custom App for Zoho Mail but the setup on creating custom service is different what I usually do on Rambox.

**Comment by 8227846265** [comment]
Wait never mind. It seems there's a Custom Website service available to use. I'll just use that instead to replace Zoho Mail service.

**Comment by vraravam** [comment]
@8227846265 - the last segment `/zm/` is some kind of bucketization that zoho does (maybe by geography, im not sure). For eg, when I login into my zoho mail, i get a different path.
Moreover, if your login session expires, then you will be automatically taken to the login page, from where you will still land on this page (at least, that's how it behaves for me)
