### ISSUE TITLE
Auto update check doesn't work

### ISSUE THREAD

**Issue by ihatemicrosoft-was-already-taken** [getferdi/ferdi#2218]
**Bug description:**
Auto update check doesn't work. I never get notified about new updates. When I click on the "Check for updates" button in Settings > Updates, it just turns to "is searching for update" and nothing else happens.

**Steps to reproduce:**
1. Install Ferdi from .deb on Ubuntu 21.10
2. Go to Settings > Updates
3. Click "Check for updates"

**Expected behavior**
It should successfully check for an update and either report the update or report that no updates are available.

**Screenshots**
![image](https://user-images.githubusercontent.com/44801995/141454235-248aee3a-ffce-4b1e-972f-6cd53aa1d33a.png)

**Environment:**

- Operating System: Ubuntu 21.10 impish Linux 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Ferdi Version: 5.6.3
- Server: Using without an account

- Debug information: [debug_information.txt](https://github.com/getferdi/ferdi/files/7526943/debug_information.txt)

**Comment by vraravam** [comment]
@ihatemicrosoft-was-already-taken - you are on the latest version. As seen in your screenshot, you have only opted for betas (not nightlies).  `5.6.3` is the latest public stable version, and beyond that, there are only nightlies that have been released for wider testing purposes.

For the issue about the in-app updater not working properly, I am closing this ticket in favor of #329
