### ISSUE TITLE
"Show Ferdi" on task bar icon not working

### ISSUE THREAD

**Issue by davidbenucci** [getferdi/ferdi#2220]
I've just updated Ferdi at 5.6.3 version. I have enabled option "Minimized Ferdi to system tray" and "Close Ferdi to system tray" but when I double click on Ferdi icon in the tray, nothing happens; the same if I right click eand select "show Ferdi". In order to see Ferdi windows, I have to relaunch it.
I'm using Windows 10.

**Comment by vraravam** [comment]
Duplicate of #2147
