### ISSUE TITLE
Can't log in after importing account to api.getferdi.com

### ISSUE THREAD

**Issue by fleity** [getferdi/ferdi#223]
Imported my franz account using https://api.getferdi.com/import
Changed server to https://api.getferdi.com
Login screen says wrong mail / password, so does https://api.getferdi.com/user/login since clearing browsing data (before it said invalid CSRF token)

A second attempt at importing my account tells me that my mail adress already exists in the database therefore I believe the account should exist. Additionally, there is no option to reset the password for a ferdi account? 

my email adress contains a +franz@gmail and I suspect it might not got parsed correctly

**Comment by vantezzen** [comment]
The `+` in your email shouldn't be a problem. I suspect that the importer didn't save your password in the correct format and thus locking you out of the account.
We'll be working on a password reset mechanism in the future (https://github.com/getferdi/server/issues/16) but if you want to you can send a mail to hello@getferdi.com with your account's e-mail address and we can reset the password manually on the server side.

**Comment by vantezzen** [comment]
This error has now been resolved via email:
The account has been imported without the "+franz" part
