### ISSUE TITLE
Service shows browser address bar

### ISSUE THREAD

**Issue by grmon** [getferdi/ferdi#224]
**Describe the bug**
Every service tab shows a usable browser bar.

**To Reproduce**

1. Open Ferdi
2. Unlock
3. Chose any tab
4. See usable browser bar

**Expected behavior**
Browser bar neither visible nor usable.

**Screenshots**
<img width="599" alt="Screenshot 2019-11-26 at 13 49 36" src="https://user-images.githubusercontent.com/500813/69635021-c44e0980-1053-11ea-8b12-8bbd6d8609d6.png">

**Desktop (please complete the following information):**

- OS: macOS 10.14.6

**Additional context**

**Comment by vantezzen** [comment]
Ferdi 5.4.0 has a new setting “Always show service navigation bar” - do you have that enabled?

**Comment by grmon** [comment]
(-_Q)
