### ISSUE TITLE
Trello External Link Freeze

### ISSUE THREAD

**Issue by kovacskrisztian1** [getferdi/ferdi#2240]
Hey,

When I try to open external links by clicking on them from the Trello service it freezes. If I right click the link and click on "Open link" it does not freeze. What can I do about it? I'm on Windows 10.

Thank you!

**Comment by vraravam** [comment]
The link behavior is a known issue. Its not that Ferdi freezes - more that the link click handler consumes the event, but does nothing with it.

**Comment by kovacskrisztian1** [comment]
Sorry didn't found it. Is there any workaround?

**Comment by vraravam** [comment]
The right-click context menu and choose "open in ferdi" or "open link"

**Comment by vraravam** [comment]
Duplicate of #1501
