### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by KikoCosmetics** [getferdi/ferdi#2248]
Really?

And what's this strange blue bar at the bottom of Ferdi?

<a href="https://ibb.co/HCpTfT7"><img src="https://i.ibb.co/VxpYcYV/ferdi-update.png" alt="ferdi-update" border="0"></a>

**Comment by vraravam** [comment]
@KikoCosmetics - please do NOT create issue tickets randomly. Please continue this conversation in the previous card.

To answer your question, that is not a *reboot* ,that is a restart. (I dont know what language that is - and if the language meaning is "reboot" - that is a translation issue)
