### ISSUE TITLE
[Bug]: Ferdi minimized in the traybar does not open.

### ISSUE THREAD

**Issue by Nickyg001** [getferdi/ferdi#2251]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

windows 10 19043 

### What arch are you using?

x64

### Last Known working version of Ferdi

5.6.1

### Steps to reproduce

run

### Expected Behavior

Ferdi is open, minimized in the traybar at the bottom right.
Clicking on the icon in the traybar Ferdi does not open.
Notifications are working, so Ferdi is running correctly.
By clicking on the start icon (the one that is placed on the desktop or in the start bar) the program starts. Once minimized to the tray it no longer opens.

### Actual Behavior

 Once minimized to the tray it no longer opens.

**Comment by vraravam** [comment]
Please see #2234 - this has been fixed and available in the latest nightlies.
