### ISSUE TITLE
Custom icon drag-and-drop does not work

### ISSUE THREAD

**Issue by probablykasper** [getferdi/ferdi#226]
Drag-and-drop to add icons in services does not work:
https://youtu.be/ivIUlYKbxcw

macOS 10.14.6
Ferdi 5.4.0

**Comment by vantezzen** [comment]
What server are you using?

**Comment by probablykasper** [comment]
@vantezzen https://api.getferdi.com

**Comment by vantezzen** [comment]
Hmm, custom icons should have been implemented via [server#
26bff86](https://github.com/getferdi/server/commit/26bff86fee36e2bedeee19c750634860e59ed3ec). Can you open the Developer Console and see if there are any errors related?

**Comment by kytwb** [comment]
@vantezzen the issue is in the drag'n'drop itself, we can't drop the image as he tried in the video.

**Comment by probablykasper** [comment]
@kytwb Yeah true, doing it manually works after all. Tried again now, and it doesn't work now, very weird.

**Comment by gustavoggs** [comment]
I am not able to add icons in any way to it. Not only using drag & drop. Any clue what can be the problem or is part of this bug?

**Comment by chrismayer** [comment]
> I am not able to add icons in any way to it. Not only using drag & drop.

Same for me. The custom icons are stored in `~/.config/Ferdi/icons/` but are not shown in the UI. The `src`, which is used within the `img` tag, points to `http://127.0.0.1:45569/v1/icon/<SOME-UUID>`. This responds with an HTTP status code 302.

I am using the following version:
![image](https://user-images.githubusercontent.com/1185547/100216010-0da89180-2f12-11eb-82fd-44ccbd1e1ebb.png)

**Comment by real-or-random** [comment]
> > I am not able to add icons in any way to it. Not only using drag & drop.
> 
> Same for me. The custom icons are stored in `~/.config/Ferdi/icons/` but are not shown in the UI. The `src`, which is used within the `img` tag, points to `http://127.0.0.1:45569/v1/icon/<SOME-UUID>`. This responds with an HTTP status code 302.
> 
> I am using the following version:
> ![image](https://user-images.githubusercontent.com/1185547/100216010-0da89180-2f12-11eb-82fd-44ccbd1e1ebb.png)

I can confirm that adding icons does not work. I can confirm that they're stored in `~/.config/Ferdi/icons` but not shown. (I haven't checked HTTP status codes.)

**Comment by mhatvan** [comment]
Verified that this works with the latest nightly, closing.

Please note that there is an open issue regarding deleting custom icons though: https://github.com/getferdi/ferdi/issues/1787
