### ISSUE TITLE
[Bug]: "This browser or app may not be secure."

### ISSUE THREAD

**Issue by dehyde** [getferdi/ferdi#2261]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 11

### What arch are you using?

x64

### Steps to reproduce

1. Add new service
2. try to log in using google
3. opens google sign in on an external windows
4. enter google username

### Expected Behavior

Sign in using google account

### Actual Behavior

See error "couldn't sign you in 
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in."

### Screenshots

![image](https://user-images.githubusercontent.com/32676977/142698431-73fcf665-23e9-4f29-8793-9b002bfde1a3.png)

**Comment by vraravam** [comment]
@dehyde : This happens from time to time when google changes their browser-detection algorithm. Without any change on Ferdi's code, this has resolved itself (in past instances).

The best workaround for this is to play around with the `user-agent` setting. There is a global one, as well as a recipe-specific one. Both are available in the Preferences/Settings dialog of Ferdi.
