### ISSUE TITLE
[Bug]: Whatsapp notification counter broken

### ISSUE THREAD

**Issue by manavortex** [getferdi/ferdi#2263]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

macOS

### Server

Ferdi

### Operating System Version

10.14.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known working version of Ferdi

-

### Steps to reproduce

1. Receive a private Whatsapp (direct) message in a not-disabled chat  

### Expected Behavior

The notification counter displays reliably and always.

### Actual Behavior

The notification counter shows only occasionally

Unfortunately, I can't pinpoint what works and what doesn't, since I rarely use the service (due to the fact that I'm not getting notifications reliably 😏 But I also don't like it much) 

### Additional Information

As per the last ticket about this issue, I added the following to the recipe:

```
    if (0 === count) {
      count = document.querySelectorAll('._38M1B').length;
    }
```
... and now I'm getting notifications again.

**Comment by vraravam** [comment]
Please raise the bug against the https://github.com/getferdi/recipes repo. This is not the right repo for such a bug
