### ISSUE TITLE
[Bug]: Unable to restore Ferdi upon minimizing to system tray

### ISSUE THREAD

**Issue by SimKaiLong** [getferdi/ferdi#2267]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 10 Pro, Version 21H2

### What arch are you using?

x64

### Last Known working version of Ferdi

Previous version prior to updating

### Steps to reproduce

1. Open up Ferdi
2.  Minimize the app either via Minimize or Close (Close to Tray setting enabled)
3.  Try to re-open Ferdi via double clicking on the Ferdi icon in system tray.

Note: Ferdi "launches" and opens the window if I start it again from a desktop shortcut or from the Windows Start Menu.

### Expected Behavior

1. Open up Ferdi
2. Minimize the app either via Minimize or Close (Close to Tray setting enabled)
3. Try to re-open Ferdi via double clicking on the Ferdi icon in system tray.
4. Ferdi opens up

### Actual Behavior

Ferdi does not respond to open.

### Debug information

{"host":{"platform":"win32","release":"10.0.19044","screens":[{"id":2528732444,"bounds":{"x":0,"y":0,"width":2752,"height":1152},"workArea":{"x":0,"y":0,"width":2752,"height":1112},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6783, 0.3220],  [0.2995, 0.6358],  [0.1554, 0.0838]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2752,"height":1152},"displayFrequency":50,"workAreaSize":{"width":2752,"height":1112},"scaleFactor":1.25,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.3","electron":"15.3.0","installedRecipes":[{"id":"android-messages","version":"2.2.4"},{"id":"hangouts","version":"1.2.0"},{"id":"hangoutschat","version":"1.5.1"},{"id":"messenger","version":"1.3.3"},{"id":"whatsapp","version":"3.3.6"},{}],"devRecipes":[],"services":[{"id":"be197142-4a06-4a6d-a1c3-b3f9a45aa87f","recipe":"whatsapp","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"daf357cd-2ead-49e4-ab03-62a5a2a2a38c","recipe":"hangoutschat","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"f0672a70-bf02-41a5-a626-c1d51e443c0d","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"5743a24d-8314-40e1-b410-498e3dc81a0e","recipe":"android-messages","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\Sidebar.js:1:2094)\n    at Injector (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at injectIntl(inject-_class2-with-stores-actions)\n    at div\n    at div\n    at _class2 (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class`, expected instance of `_class`.","\n    at _class (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\features\\nightlyBuilds\\Component.js:1:2135)\n    at Injector (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Jss (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(inject-_class-with-stores-actions))\n    at div\n    at div\n    at div\n    at _class2 (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\Aftershock\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","info":["error","Warning: You cannot PUSH the same path using hash history"]}],"workspaces":[],"windowSettings":{"width":1408,"height":824,"x":612,"y":104,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":2752,"height":1152}},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":true,"closeToSystemTray":true,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"splitMode":false,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":300,"inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"never","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"locale":"en-US","showServiceNavigationBar":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by michaelhays** [comment]
Fixed in #2234

**Comment by SimKaiLong** [comment]
Oh! Somehow did not see that when I was searching through the existing bug list.
