### ISSUE TITLE
[Bug]: Outlook 365 clicking on menu icons opens new browser window

### ISSUE THREAD

**Issue by warber** [getferdi/ferdi#2268]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Ubuntu

### Server

Using without an account

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Last Known working version of Ferdi

5.6.3

### Steps to reproduce

1. Open Outlook 365 service
2. Try to switch to the calendar view by clicking the Calendar icon inside Outlook 365 on the left

### Expected Behavior

Schuld be able to see the Calendar view inside the Ferdi Service

### Actual Behavior

 Calendar is opened as a new tab in your Browser

### Screenshots

I am not able to use the Outlook 365 integration with Ferdi properly anymore as whenever I switch to another Outlook 365 view (e.g. switching from mail to calendar) my Webbrowser (in this case Firefox) is opened with a new tab for that view.

It was never a problem and stopped working a couple of days ago, maybe due to an update of Outlook 356 (the icons look a bit differnt now...)

**Comment by vraravam** [comment]
I'm on the latest nightly, and I dont see this behavior with Outlook365

**Comment by warber** [comment]
Just tried it with `5.6.4-nightly.12` with no lock
Recipe version: `1.5.0`

**Comment by warber** [comment]
Seems like this is at the moment just the default behavior of the Outlook365 Web App as it also opens new tabs when I am just using Outlooke365 with my Web Browser :/

**Comment by gianlucapisati** [comment]
Yep, I'm having the same issue :(

**Comment by rayvermey** [comment]
> Yep, I'm having the same issue :(
> 
> At the moment I've solved adding a new service dedicated to the calendar with this url (choosing self-hosted) https://outlook.office.com/calendar/view/workweek

Thanks! Good tip!

**Comment by warber** [comment]
FYI, seems like Microsoft fixed this behavior :raised_hands: -  working again :)

**Comment by vraravam** [comment]
Closing the ticket since it was fixed on the server-side.
