### ISSUE TITLE
Possible to give us access to chrome/chromium flags ?

### ISSUE THREAD

**Issue by SolidTerre** [getferdi/ferdi#2269]
I have an issue with my HDR settings being applied on all apps/websites.
While some websites support it, a lot of chat apps and other don't which over-brightens the screen/window a lot when doing some actions.

The workaround is to change the chrome://flags/#force-color-profile value to sRGB for people who make use of HDR.

Any way to do that in Ferdi, or to give us a way to access the flags of the Chromium/Electron version you're using ?

**Comment by vraravam** [comment]
This is not possible. Please log a feature request against Electron - and if they implement this, we can discuss the need and how it gets implemented.
