### ISSUE TITLE
Context menu item for opening a link in the current service

### ISSUE THREAD

**Issue by probablykasper** [getferdi/ferdi#227]
Right-clicking a link would give you a context menu item for opening a link in the current service.

I'm not sure if this is something that should really be added because it's not really how services should work, but it's an idea that would at least help mitigate [the issue where you can't login to Gmail](https://github.com/getferdi/ferdi/issues/110).

I assume pressing reload, View > Back and the back shortcut lets you go back.

**Comment by kytwb** [comment]
Implemented (**Open Link in Ferdi**), will ship in the next release:

<img width="471" alt="Screen Shot 2020-03-03 at 3 15 25 AM" src="https://user-images.githubusercontent.com/412895/75739565-7bb68400-5d05-11ea-9150-66be4d416ea0.png">

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.3).
