### ISSUE TITLE
Make "autoLaunchInBackground" setting work instead of just using app settings

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#228]
**Describe the bug**
When using a pre-created settings.json my autoLaunchInBackground option is not disabled like other option and I need to disabled manually.
```
{
  "autoLaunchInBackground": false,
  "runInBackground": false,
  "enableSystemTray": false,
  "minimizeToSystemTray": false,
  "privateNotifications": false,
  "showDisabledServices": true,
  "showMessageBadgeWhenMuted": true,
  "enableSpellchecking": true,
  "spellcheckerLanguage": "en-us",
  "darkMode": false,
  "locale": "en-US",
  "fallbackLocale": "en-US",
  "beta": false,
  "isAppMuted": false,
  "enableGPUAcceleration": true,
  "serviceLimit": 5,
  "server": "https://api.getferdi.com",
  "todoServer": "https://app.franztodos.com",
  "autohideMenuBar": false,
  "lockingFeatureEnabled": false,
  "locked": false,
  "lockedPassword": "",
  "scheduledDNDEnabled": false,
  "scheduledDNDStart": "17:00",
  "scheduledDNDEnd": "09:00",
  "hibernate": false,
  "hibernationStrategy": 300,
  "noUpdates": true,
  "showServiceNavigationBar": false,
  "universalDarkMode": true,
  "accentColor": "#7367f0",
  "adaptableDarkMode": ""
}
```

**To Reproduce**

1. Use a Ferdi without data created
2. Put a settings.json in _DataFolder_/Ferdi/config
3. Go to settings
4. See _Launch Ferdi on start_ is still enabled with a pre-created option not to do that

**Expected behavior**
Normally with a option put to false is supposed to desactivated the option when using the app for the first time or more.

**Screenshots**
![launch-on-start](https://user-images.githubusercontent.com/49844464/69651383-fce2e880-103d-11ea-878e-997d322c3234.PNG)

**Desktop (please complete the following information):**

- OS: Windows 10 x64 1903
- Version: 5.4.0

**Additional context**
This is for my future release of PortableApps Format and because of this I need to created a box in the first run telling to everyone to disabled this option when using ferdi. If not when windows is power on Ferdi.exe directly will be launch and not FerdiPortable.exe.

PS: This is the same on Franz.

**Comment by vantezzen** [comment]
Ferdi doesn't use the settings.json setting to set this option. Instead, it updates Electron's `launchOnStartup` setting when updating the settings through the settings modal:

https://github.com/getferdi/ferdi/blob/fd7710a395bcf3d3fc5f9760a48ded335e591ad9/src/containers/settings/EditSettingsScreen.js#L162-L165

It actually never reads the `autoLaunchInBackground` setting from settings.json but uses the information from Electron directly:

https://github.com/getferdi/ferdi/blob/fd7710a395bcf3d3fc5f9760a48ded335e591ad9/src/containers/settings/EditSettingsScreen.js#L255

You would need to add new code to Ferdi that would add this functionality.

**Comment by Makazzz** [comment]
Oh okay.. I can see it now. But because I can't add new code (I don't have enough knowledge for this) is there a way to put this option `false` by default instead? And make this `autoLaunchInBackground` work for real in the future?

**Comment by mhatvan** [comment]
Seems this was already solved in https://github.com/getferdi/ferdi/pull/331
