### ISSUE TITLE
[Bug]: I set it to start minimized to tray and I cannot show the window at all

### ISSUE THREAD

**Issue by NULUSIOS** [getferdi/ferdi#2285]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 11

### What arch are you using?

x64

### Steps to reproduce

After many other issues (that need separate reports), I set it to minimize to tray, close to tray, start minimized.
I minimized it (to tray) and when I click or double-click it doesn't show any window.
I can right click the icon to quit it, but if I start again, it starts minimized (as I configured it), but again, I cannot make it show its window at all.

Windows 11 dual monitor.

Right now my only option is to somehow delete all the settings (how?) so that I can "reset" it to default behavior.

### Expected Behavior

To pop-up its own window when I click (or double-click) its tray icon.

### Actual Behavior

Just stays minimized.  I can right click to quit it.

**Comment by vraravam** [comment]
fixed in #2234 . Please use one of the latest nightlies for the fix
