### ISSUE TITLE
[Bug]: systray icon menu "Show Ferdi" and "Disable Notifications & Audio" do nothing

### ISSUE THREAD

**Issue by 3b-fly** [getferdi/ferdi#2286]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Other Linux

### Server

Using without an account

### Operating System Version

Linux Mint 20.2 Cinnamon

### What arch are you using?

x64

### Steps to reproduce

click on items in icon menu

### Expected Behavior

to do action

### Actual Behavior

does nothing

### Debug information

no error logs

**Comment by vraravam** [comment]
the show/hide is fixed by #2234 and already available in the nightlies
