### ISSUE TITLE
[Feature Request]: Toggle default Slack icons

### ISSUE THREAD

**Issue by TJonCooper** [getferdi/ferdi#2289]
### Preflight Checklist
- [x]  I have read the Contributing Guidelines for this project.
- [x]  I agree to follow the Code of Conduct that this project adheres to.
- [x]  I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Description
Would it be possible to prevent Slack services from loading the server's icon? i.e. use the default, Ferdi Slack icon.

So instead of:

![Screenshot-20211130074158-72x202](https://user-images.githubusercontent.com/15924377/143992266-9648ede0-9538-44d6-b62d-d7e6b6366600.png)

We can toggle to:

![Screenshot-20211130074211-77x200](https://user-images.githubusercontent.com/15924377/143992277-e1e1d297-6152-4d47-a109-3f15747c283d.png)

**Comment by vraravam** [comment]
Sorry - this has been the preferred ask from multiple folks - and thus been implemented as such. If you want to be able to toggle this off, it should be a implemented as a user preference (the default being the current behavior).

Also - such a request is very specific to slack and will need to be logged/implemented in the https://github.com/getferdi/recipes repo. Closing in this repo.
