### ISSUE TITLE
Ferdi client not allowed to login in Gmail

### ISSUE THREAD

**Issue by silvadev** [getferdi/ferdi#229]
Google doesn't allow logging in to gmail for reporting Ferdi as insecure.
Performed the procedure to delete files from gmail recipe and Ferdi services before posting this issue.

Ferdi: 5.4.0
OS: Manjaro Linux Budgie x64

![Captura de tela de 2019-11-26 16-40-51](https://user-images.githubusercontent.com/457433/69667425-c2dd0b00-106c-11ea-83ba-4eb0e33fc964.png)

**Comment by kytwb** [comment]
Similar to https://github.com/meetfranz/franz/issues/1573 https://github.com/meetfranz/franz/issues/1573.

**Comment by kytwb** [comment]
Also similar to https://github.com/ramboxapp/community-edition/issues/2385.

**Comment by kytwb** [comment]
Possible fix shipped with [v5.4.1-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.2).

> Regarding the Gmail service issues, your Gmail service(s) will need to be re-created as we can't remotely update services for now using the Ferdi API (pending getferdi/server#14).

Feedback welcome!

**Comment by ylluminate** [comment]
Good to see this is finally being addressed.

**Comment by packermann76** [comment]
Couldn't get gmail running with the beta.2, same error as initially posted. Re-installed stable and seen gmail-recipe was was extended with user-agent override. However this also didn't solve it for me. Copied the recipe to my dev-folder and changed user-agent to what is used with my current firefox-installation. This solved it for me, gmail is working for me.
System: MacOSX 10.15.2
Firefox: v71.0

user-agent-override provided with built-in recipe:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36`

user-agent-override working at least for me:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0`

**Comment by kytwb** [comment]
Closing in favor of https://github.com/getferdi/ferdi/issues/264.

**Comment by kytwb** [comment]
In the meantime, please refer to https://github.com/getferdi/ferdi/issues/264#issuecomment-567138371.

**Comment by MikeDabrowski** [comment]
This worked for me
https://gist.github.com/HarderBetterFasterStronger/ae9e853d739b856a367592f0a105a8f8#gistcomment-3130820
