### ISSUE TITLE
Ferdi doesn't log in automatically anymore

### ISSUE THREAD

**Issue by NLatuny** [getferdi/ferdi#2293]
Usually when I close Ferdi and open it again it automatically logs in. Now it doesn't giving the following error:

`There were errors while trying to perform an authentication request. Please try logging out and back in if this error persists.`

I can confirm I have tried logging out and back in again, but it doesn't help the issue. I also uninstalled and reinstalled Ferdi, but that also doesn't help the issue. 

Also (not sure if it's related), but when I manually log back in again I can't log back into Whatsapp. Just a loading screen saying "organization messages" forever. While it works fine when I try in my browser.

**Comment by vraravam** [comment]
@NLatuny - please provide more details: what version of Ferdi, what specific service, what version of said recipe, etc would be welcome for starters.

If its specific to Whatsapp, and the new multi-device beta, there's already a few bugs - please close this one if so

**Comment by NLatuny** [comment]
@vraravam I'm using Ferdi v5.6.3. Not sure what service matters here as I mean the Ferdi login.

The thing about whatsapp was a separate thing, but you can scratch that for now.

**Comment by vraravam** [comment]
ok - so which server are you trying to connect to (for Ferdi login) - is it the Franz server, (hosted) Ferdi server or some other?

**Comment by NLatuny** [comment]
I use the Ferdi server.

**Comment by vraravam** [comment]
ok - unfortunately, as a user, I moved away from the Ferdi server due to such flakiness.

I do not have visibility into the current state of the deployed version, and so cannot comment on this.

@vantezzen @kytwb - maybe you can help debug?

**Comment by Bananaman** [comment]
I tried Ferdi's latest flatpak. Logged into discord. Every time I restart Ferdi I'm logged out again.

I am using Ferdi without an account (at the startup screen). Surely the app doesn't force us to store login cookies online just to use it? I'm uninstalling Ferdi now and going back to Discord's own app...

**Comment by Bananaman** [comment]
@vraravam I decided to try Ferdi again. Latest flatpak version 5.6.5. The login is kept between Ferdi restarts now, with local-server credentials. Good! :)

Ferdi uses more RAM than Discord (500mb vs 300mb) but it's more flexible so I think I'll switch to Ferdi.

**Comment by Bananaman** [comment]
@NLatuny @vraravam Wellllll damn, I'm logged out again after restarting Ferdi flatpak. Hrm...
