### ISSUE TITLE
Ferdi is not advertising a new version/release

### ISSUE THREAD

**Issue by leoheck** [getferdi/ferdi#2294]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.2

### What operating system are you using?

Ubuntu

### Server

Other server (please specify in the steps to reproduce)

### Operating System Version

120.21

### What arch are you using?

x64

### Steps to reproduce

n/a

### Expected Behavior

n/a

### Actual Behavior

n/a

### Additional Information

Oh god.. now we are seeing the same issue wall with a bunch of required fields to even start a conversation. This is so bad. Seriously. I am about to leave the issue report page. I just want to acknowledge to you that this is happening... 

Server = IDK

Ferdi is not issuing a new version. As it was said before. Seriously

**Comment by leoheck** [comment]
It is ok @vraravam. The other issue is from 2020. How do I help to make this happen?

**Comment by vraravam** [comment]
Unfortunately, there's no way to debug this without the signing key. @kytwb is the only one who has that, and thus the in-app updater is blocked.
