### ISSUE TITLE
[Bug]: Custom Website fails to load when using custom ssl cert

### ISSUE THREAD

**Issue by Kuuchuu** [getferdi/ferdi#2296]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Other Linux

### Server

Ferdi

### Operating System Version

Linux solus 5.14.16-205.current #1 SMP PREEMPT Sat Nov 6 09:14:32 UTC 2021 x86_64 GNU/Linux

### What arch are you using?

x64

### Steps to reproduce

1. Add website as custom service, website uses its own generated self-signed certs, local website only.
2. Attempt to open the service, you receive an error.

### Expected Behavior

Custom service loads

### Actual Behavior

Error: ERR_CERT_AUTHORITY_INVALID
Webpage never loads.

### Additional Information

Here is an issue for this that was never resolved and eventually marked as stale on Franz's github:
[https://github.com/meetfranz/franz/issues/1479](https://github.com/meetfranz/franz/issues/1479)

**Comment by briankendall** [comment]
I just ran into this issue myself. Would be great to have a way for it to accept self-signed certificates.

**Comment by kytwb** [comment]
Closing in favour of https://github.com/getferdi/ferdi/issues/2296.
