### ISSUE TITLE
[Bug]: letters of words in services menu show with squares.

### ISSUE THREAD

**Issue by anvaari** [getferdi/ferdi#2305]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Ubuntu

### Server

Ferdi

### Operating System Version

Ubuntu 20.04 LTS

### What arch are you using?

x64

### Steps to reproduce

1. Go to service (like Whatsapp)
2. Click on attach icon to attach file to message
3. All words on menu show with squares instead of letters

When go to help menu --> about fredi, same thing happend.

### Expected Behavior

Words in menu should show with letters.

### Actual Behavior

It seems, any menu which open file manager behave like this.

### Screenshots

![Bug](https://user-images.githubusercontent.com/39170783/144735615-c40b88a5-a7cb-471d-bb6a-bd2c3f5eb6ae.png)

**Comment by vraravam** [comment]
@anvaari - this looks like fonts are messed up on your OS. I'm not sure how I can help proceed to debug this.

**Comment by anvaari** [comment]
Oh, thanks. If it's a missing font, Does is solve if i install font?
Can you give me a font name?

**Comment by anvaari** [comment]
@noraj Yes, I install ferdi with snap. Ok I will use deb package.

**Comment by anvaari** [comment]
It fixex, After reinstall with deb package. Thanks a lot.
