### ISSUE TITLE
[Bug]: Ferdi Icon on system tray but not doing anything when I press on "Show/Hide".

### ISSUE THREAD

**Issue by shiftokay** [getferdi/ferdi#2306]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 10 Pro 21H2

### What arch are you using?

x64

### Last Known working version of Ferdi

5.6.3

### Steps to reproduce

1. Go to Ferdi
2. Minimize the app
3. Check the system tray 
4. Right/Left Click on Ferdi Icon
5. Click the Show/Hide button

--- Not doing anything ---

### Expected Behavior

I expect ferdi to show up or pop up when i click on the show/hide button or option.

### Actual Behavior

Nothings happening when I click on the show/hide button on the system tray of ferdi.

**Comment by vraravam** [comment]
Please do not create duplicate bugs! This has been reported in #2285  #2267 #2262 - and the fix is already available for the past few nightlies.

**Comment by shiftokay** [comment]
> Please do not create duplicate bugs! This has been reported in #2285 #2267 #2262 - and the fix is already available in the past few nightlies.

Greetings, so I tried using nightflies or the ferdi 5.6.4 and it says that a new update is available, when I click on "update" the show/hide is not working again. But other than that it's fixed now. Thank you very much!

**Comment by vraravam** [comment]
That is yet another bug #329

sent using an itty-bitty keyboard that assumes it can think
