### ISSUE TITLE
Lock password default behavior

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#232]
I just noticed in the source code that if the password input for the lock feature is empty in the settings, the password default to `ferdi`. This is not documented afaik and could lead to confusion. I propose we just let an empty lock password be a possibility instead of defaulting to this default password. WDYT?

**Comment by Makazzz** [comment]
For me an empty password if you put nothing in the option seem logic to me.

**Comment by kytwb** [comment]
Available in [v5.4.1-beta.1](https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.1).
