### ISSUE TITLE
[Compliment!]: Ferdi updated automatically from 5.6.3

### ISSUE THREAD

**Issue by avielc** [getferdi/ferdi#2330]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3-5.6.4

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

W11

### What arch are you using?

x64

### Last Known working version of Ferdi

5.6.3

### Steps to reproduce

Hi evereyone
This is just a note on congratulating you on doing such a great work!
Ferdi just notified me about an update available and did an actual installation of the app! 

So, thank you for all the hard work, and congratz on reaching the point that didn't happen for quite a few versions. 
this is great! 

### Expected Behavior

Expected to work like this!

### Actual Behavior

it worked!

### Additional Information

you can close this "bug" :)

**Comment by mhatvan** [comment]
Hey @avielc, that is great to hear!

So I guess auto updating works as expected for Windows (confirmed by you), and Linux AppImage (confirmed by me)

Now we only need to get macOS autoupdating working again, but I fear it's an issue with `electron-builder`

Happy holidays! ;)
