### ISSUE TITLE
[Bug]: WhatsApp forcing logout and re-login every couple days

### ISSUE THREAD

**Issue by jeff4157** [getferdi/ferdi#2333]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

macOS

### Server

Ferdi

### Operating System Version

12.1

### What arch are you using?

arm64 (including Apple Silicon)

### Steps to reproduce

Just been using WhatsApp as usual on a M1 mac.  I was logged in for months before but now every couple days need to redo. 

### Expected Behavior

Stay logged in

### Actual Behavior

Forced logout

**Comment by ruifchaves** [comment]
I've been having the same issue. For me, it's more frequent than every couple of days, It's almost everyday. I have to logout and relink the service. I've recently activated Multi-device beta feature, so it might be related to that but I'm not sure. Have you activated it?
![image](https://user-images.githubusercontent.com/59342151/147488249-3899ea2c-6e6f-490a-a103-615a8d6318cb.png)

**Comment by kytwb** [comment]
Duplicate of https://github.com/getferdi/ferdi/issues/1745.
