### ISSUE TITLE
Service disabled upon restart

### ISSUE THREAD

**Issue by ammarmalhas** [getferdi/ferdi#234]
**Describe the bug**
In the latest beta version 5.4.1 beta1 if i quit the app and relaunch it my Telegram service launches disabled and i need to enable it again.
When I enable the service I get a message in RED at the bottom of the app saying that the "There was an error while trying to perform and authentication request ....", it goes off after a few seconds.

**Screenshots**

**Desktop (please complete the following information):**
- iOS 10.14.6
- Ferdi 5.4.1. beta1
<img width="1160" alt="Screen Shot 2019-11-28 at 08 45 24" src="https://user-images.githubusercontent.com/57057209/69783189-08f8b280-11c4-11ea-9c63-44dfc8e58d26.png">

**Additional context**

**Comment by kytwb** [comment]
I have experienced the same and created a ticket in https://github.com/getferdi/server/issues/13. @vantezzen any ideas?

**Comment by vantezzen** [comment]
Hmm, can you look at the developer tools network tab to see what queries are getting send and what errors there are?

**Comment by kytwb** [comment]
```
{"message":"Invalid POST arguments","messages":[{"message":"required validation failed on name","field":"name","validation":"required"}],"status":401}
```

Sending `{isEnabled: false}` if I remember correctly.

**Comment by kytwb** [comment]
It's being worked on at the API level, closing this ticket in favour of https://github.com/getferdi/server/issues/13.  
Thanks for reporting @ammarmalhas, I will come back to report in here once it's fixed.

**Comment by kytwb** [comment]
@ammarmalhas this should be fixed now.

**Comment by ammarmalhas** [comment]
Great, but what do I do? Do I download the app again?

**Comment by kytwb** [comment]
Nothing needed. When you enable the service now, you shouldn't have the red error message you saw earlier and things should be working as expected. Let us know if it is not 😄

**Comment by ammarmalhas** [comment]
I just use beta 1 as I have it downloaded this morning?

**Comment by kytwb** [comment]
Yes 😄 The error was on the API side, and it has been fixed and deployed (see https://github.com/getferdi/server/issues/13).  
No changes required in the client.

**Comment by ammarmalhas** [comment]
I tried it, it seems to be working well. I will give it a few more restarts and see. On another note, when will the password (lock) kick-in? Is there a time value after which the app locks itself?

**Comment by kytwb** [comment]
I have created an issue for this improvement (see https://github.com/getferdi/ferdi/issues/240). Please subscribe to the issue (bottom right corner of the screenshot below) to be kept in the loop on progress.


![Screen Shot 2019-11-28 at 10 46 40 PM](https://user-images.githubusercontent.com/412895/69819221-0d0ee980-1231-11ea-8cd3-7f89d45bae77.png)
