### ISSUE TITLE
[Bug]: Keeps asking to update

### ISSUE THREAD

**Issue by pappymu** [getferdi/ferdi#2340]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

macOS

### Server

Ferdi

### Operating System Version

Catalina

### What arch are you using?

x64

### Steps to reproduce

Every time I open Ferdi, it keeps asking me to restart and install updates. The red circle on the settings button appears but nothing different appears in settings.

### Expected Behavior

It should probably stop asking me to update, since the latest update was a while back

### Actual Behavior

The purple bar at the bottom keeps asking me to update
<img width="927" alt="Screenshot 2021-12-19 at 10 30 05 AM" src="https://user-images.githubusercontent.com/86952621/146661467-2c0053b3-036d-4cbc-b433-0b6652204831.png">

### Debug information

{"host":{"platform":"darwin","release":"19.6.0","screens":[{"id":69733382,"bounds":{"x":0,"y":0,"width":1680,"height":1050},"workArea":{"x":0,"y":23,"width":1680,"height":1027},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":30,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1_HDR, matrix:RGB, range:FULL}","depthPerComponent":10,"size":{"width":1680,"height":1050},"displayFrequency":60,"workAreaSize":{"width":1680,"height":1027},"scaleFactor":2,"rotation":0,"internal":true,"touchSupport":"unknown"},{"id":1086996487,"bounds":{"x":1680,"y":0,"width":2560,"height":1080},"workArea":{"x":1680,"y":23,"width":2560,"height":1057},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2560,"height":1080},"displayFrequency":59,"workAreaSize":{"width":2560,"height":1057},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.3","electron":"15.3.0","installedRecipes":[{"id":"messenger","version":"1.3.3"},{"id":"slack","version":"1.3.3"},{"id":"telegram","version":"3.2.4"},{"id":"whatsapp","version":"3.3.6"},{}],"devRecipes":[],"services":[{"id":"4429a34a-931a-44c8-89f3-61c693346c30","recipe":"whatsapp","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"6711b396-ce90-465c-a3da-33c35d1fb8a1","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"6e5153c1-2aff-4b42-9743-f3d45bbbec4e","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"3bb0cdfc-b89b-44d7-a2df-9653097c0da0","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2781)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:842)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/layout/Sidebar.js:1:2094)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at injectIntl(inject-_class2-with-stores-actions)\n    at div\n    at div\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:1023)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/layout/AppLayout.js:1:2715)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/theming/dist/cjs/create-theme-provider.js:66:7)\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2781)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:842)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class`, expected instance of `_class`.","\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/features/nightlyBuilds/Component.js:1:2135)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(inject-_class-with-stores-actions))\n    at div\n    at div\n    at div\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:1023)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/components/layout/AppLayout.js:1:2715)\n    at Jss (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/theming/dist/cjs/create-theme-provider.js:66:7)\n    at _class2 (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2781)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at _class (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:842)\n    at Injector (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:1328:7)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","info":["error",{}]},{"type":"log","info":["log","+65 9366 1907",{"tag":"6593661907@c.us","renotify":true,"dir":"auto","lang":"en","silent":true,"body":"WhatsApp group invite‎‏ - ‪10:29 am‬","icon":"https://web.whatsapp.com/pp?e=https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.24694-24%2F70912311_727530114377055_4678274280851505152_n.jpg%3Fccb%3D11-4%26oh%3D9400472e328ecce2bcd69910389ccff8%26oe%3D61C30310&t=s&u=6593661907%40c.us&i=1569511252&n=mWFpJm5DYxcJq45XYcJxLM6KYi%2BXl5Zg%2B4naoeYNq1I%3D"}]}],"workspaces":[],"windowSettings":{"width":943,"height":718,"x":345,"y":93,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1680,"height":1050}},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"splitMode":false,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":"300","wakeUpStrategy":"300","inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"custom","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"locale":"en-US"},"features":{},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by vraravam** [comment]
The in-app updater is broken and is a known issue being tracked in #329
