### ISSUE TITLE
Review contributors template

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#236]
I suggest we display only the contributors profile pictures in the README, in a circle shape similar to the bakers. We can add details on the images alt/title attributes. This way we will be able to display more contributors as there is a growing number of people helping with bug reports, code and testing/feedback.

![Screen Shot 2019-11-28 at 7 28 22 PM](https://user-images.githubusercontent.com/412895/69806366-45083380-1215-11ea-90ea-24ab0c3a490d.png)

Related: [all-contributors configuration](https://allcontributors.org/docs/en/bot/configuration).

**Comment by vantezzen** [comment]
Personally, I like the way all-contributors displays items and I've also seen repos with more contributors [use this way of displaying people](https://github.com/starship/starship#contributors).

**Comment by kytwb** [comment]
The idea was to have something similar to [Dark Reader](https://github.com/darkreader/darkreader) to give the focus on the community/people:

![Screen Shot 2019-11-30 at 1 30 24 AM](https://user-images.githubusercontent.com/412895/69885737-2f783400-1311-11ea-89c9-dde808a1527b.png)

I'm afraid a bigger/more complex template doesn't scale nicely with this amount of contributors. We could take the opportunity to update the list of contributors as well as it is far from exhaustive at the moment (if we include everybody that has given a feedback, reported a bug, etc.).

**Comment by kytwb** [comment]
@vantezzen What do you think about highlighting the core contributors before the all-contributors block, and adopt Dark Reader template for the latter?

**Comment by vantezzen** [comment]
I would not highlight the core contributors seperately but adopting the DarkReader template sounds good,

**Comment by kytwb** [comment]
Quick update on this one: Dark Reader use one SVG to list all the contributors based on the GitHub contributions graph (via Open Collective). Our image would be:

![Contributors](https://opencollective.com/getferdi/contributors.svg?width=890&button=false)

Unfortunately, this is not what we want as we also want to list contributors who spend time to help investigating issues, give feedback and such (which GitHub doesn't account for). I have opened a draft pull request where to propose some updates to the contributors template and add a contributors count badge. I will add whomever is missing from the contributors list once we agree'd on the template to use.

**Comment by kytwb** [comment]
We also can't apply `border-radius` to the avatars:

<img width="929" alt="Screen Shot 2019-12-19 at 4 32 31 PM" src="https://user-images.githubusercontent.com/412895/71186290-427d8480-227d-11ea-95f1-31e453b235f5.png">

You can see the current status of the proposed changes [here](https://github.com/getferdi/ferdi/blob/contributors/README.md#contributors-).

**Comment by yourcontact** [comment]
I was browsing through "Good first issue" to find one to take on; @kytwb @vantezzen do we still want to display the contributers' pictures (only) in round avatars?

>Personally, I like the way all-contributors displays items and I've also seen repos with more contributors use this way of displaying people. I do however think that round icons would look better.

Removing names only would also be a way to make some space while keeping (round) avatars and items (e.g. 🐛 )

**Comment by mhatvan** [comment]
After reading the initial description as well as the comments, I think that this issue can be closed.

This is how it looks ilike currently:

![Screenshot from 2021-12-17 20-16-45](https://user-images.githubusercontent.com/16797721/146596796-5a0d5dea-f8f6-438d-bbd5-71b035c8aae9.png)
