### ISSUE TITLE
URL in whatsapp chat does not "auto-load" during or after sending message

### ISSUE THREAD

**Issue by stormy1777** [getferdi/ferdi#2368]
In older Ferdi, e.g 5.6.0-* placing a URL, any URL in a whatsapp chat, auto-loaded it few seconds after pressing SPACE bar when finishing to type or copy/paste the URL.  This allowed for a nice "thumbnail" to be loaded on the URL that is about to be sent.

This function stopped working after upgrading to 5.6.2, also now updated to 5.6.5, same thing, it does not auto-load/expand the url, instead message contrins JUST the url, no text or thumbnail if it had auto-loaded as before...

right now using: 
`Version: 5.6.5
Electron: 15.3.4
Chrome: 94.0.4606.81
Node.js: 16.5.0
Platform: Windows 10
Arch: x64
Build date: Tue Dec 21 2021 22:11:36 GMT+0200 (Israel Standard Time)
Git SHA: 242293b
Git branch: release`

The PC has full internet/network access, no firewall.. how does one debug such a thing?

**Comment by otaviof** [comment]
I noticed the same behavior, the so called "link preview" was not working using the new WhatsApp beta. If you go back to the "stable" version of the service, the preview links are working again.

I'm not sure how Ferdi could contribute to this scenario, I haven't troubleshoot further than that yet.

**Comment by stormy1777** [comment]
Wow, thanks for that tip.. On Phone, i think i need to retain the beta, any way to run the non-beta on Ferdi? how does one rollback to non-beta on Ferdi? also, how to further debug, I'll be glad to run any tests if instructions are given.
Thanks.
Stormy.

**Comment by otaviof** [comment]
> Wow, thanks for that tip..

Sure! No problem. 👍 

> On Phone, i think i need to retain the beta, any way to run the non-beta on Ferdi? how does one rollback to non-beta on Ferdi?

As far as I understand, you need to join or leave the WhatsApp beta program ([help-center information](https://github.com/getferdi/ferdi/issues/2368#issuecomment-1007751132)). So, I'm afraid that will take effect to all devices.

> also, how to further debug, I'll be glad to run any tests if instructions are given. Thanks. Stormy.

I'm interested on how to further troubleshoot this too, will be great to pin-point whats going on.

**Comment by stormy1777** [comment]
Sharing from Phone (with beta), and the preview (thumbnail) WORKS, thought it's a Ferdi issue, however, even from Chrome, web, does not seem to work, can anyone else confirm?  maybe need to report to whatsapp directly? :)
