### ISSUE TITLE
Saving password

### ISSUE THREAD

**Issue by charlie-s-la** [getferdi/ferdi#237]
Hi Guys,
I was just wondering if it is possible to save passwords or use an integrated password manager such as 1Password for built-in and custom services?
One of the site we use keeps logging us out and it is very inconvenient to log back in.
Thank you

**Comment by kytwb** [comment]
Sorry to hear about the inconvenience. Out of curiosity, which service keeps logging you out? We are planning to add support for browser extensions with #113. Once it is implemented, you should be able to add the browser extension of your favourite password manager as usual. Closing in favour of #113.
