### ISSUE TITLE
[Bug]: Not allowed to add Outlook Service

### ISSUE THREAD

**Issue by crscaballero** [getferdi/ferdi#2371]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.5

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 11 Pro version 21H2

### What arch are you using?

x64

### Steps to reproduce

1. Go to "Add New Srvice"
2. Search for "Outlook"
3. Click on "Outlook" (Not "Office 365 - Outlook")

and then you won't be able to add it, nothing it's going to happen once you click on "Outlook"

### Expected Behavior

Once I select "Outlook" to be added I expected that that service be added

### Actual Behavior

Not adding Outlook once it's selected

**Comment by kytwb** [comment]
Related to https://github.com/getferdi/recipes/issues/612, https://github.com/getferdi/recipes/issues/143, https://github.com/getferdi/ferdi/issues/2152.

Fixed via https://github.com/getferdi/server/commit/e4a7fcbde65f399bc09065890cad750e40d1568e.

@all-contributors please add @crscaballero for bug
