### ISSUE TITLE
Non-dismissable error

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#239]
When receiving the following error:

> There were errors while trying to perform an authenticated request [TRY AGAIN]

We can't dismiss the error and the `[TRY AGAIN]` button doesn't seem to do anything.

**Comment by kytwb** [comment]
The button was not doing anything because of an issue spotted in Sentry and fixed via https://github.com/getferdi/ferdi/commit/f9bf37e13d53b4f9847af9d3398505e500f81b2e.

**Comment by keunes** [comment]
I just downloaded the Deb for Ubuntu (Ferdi 5.4.0) and seem to have this issue. Any idea as to when the fix might reach me? :)
