### ISSUE TITLE
[Bug]: Scroll sidebar in horizontal style

### ISSUE THREAD

**Issue by schousda** [getferdi/ferdi#2398]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.9

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 11

### What arch are you using?

x64

### Steps to reproduce

I added a lot of services to Ferdi. If i don't use fullscreen mode and use my prefered horizontal style for the sidebar, i can't scroll to the services outside the visible area.

1. Enable horizontal style for sidebar
2. Try to scroll to a service outside the visible area

### Expected Behavior

In vertical style i can use my scroll wheel to scroll the sidebar.
In horizontal style this is not working.
I also would expect arrow icons to click on to scroll.

### Actual Behavior

There is no chance to go to a service outside the visible area of the sidebar in horizontal style.

**Comment by kytwb** [comment]
Let's address this in https://github.com/getferdi/ferdi/issues/2379.
