### ISSUE TITLE
[Bug]: ferdie  keeps updating to v5.6.8

### ISSUE THREAD

**Issue by M0UL** [getferdi/ferdi#2403]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.8

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

windows 10 19044

### What arch are you using?

x64

### Steps to reproduce

1. try to update fredie with build in updater.

### Expected Behavior

install the newest version

### Actual Behavior

keeps installing the same version (5.6.8) again. even if the version  that is installed is newer. changing it pre-release does not matter.

**Comment by kytwb** [comment]
Please install the latest version manually https://getferdi.com/download/.
Maybe related to https://github.com/getferdi/ferdi/issues/2380.

**Comment by M0UL** [comment]
that does not fix the problem. fredie still keeps  updating again.

**Comment by kytwb** [comment]
When that happens, go to **Help** > **Publish Debug Information** and share that with us, thanks.

**Comment by M0UL** [comment]
https://debug.getferdi.com/76b15827-98b4-46f3-a942-7766f00a30e9

**Comment by kytwb** [comment]
<img width="776" alt="Screen Shot 2022-01-10 at 11 25 32 AM" src="https://user-images.githubusercontent.com/412895/148750829-6d324f13-7c7b-4410-84cf-b06f8db8919e.png">

**Comment by M0UL** [comment]
uninstalling and than installing fixed the problem
