### ISSUE TITLE
Issue recieving pop-up notifications from Messenger 

### ISSUE THREAD

**Issue by jacobmoron** [getferdi/ferdi#2404]
Hi - for some reason I have an issue receiving pop-up notifications from the Facebook Messenger service. I have this turned on both in the app and on the messenger website. While I hear a noise when I'm sent a new message, no pop-up appears. Interestingly, I also had this issue with Franz, before I moved to Ferdi. Would really appreciate any help. Thanks

**Comment by kytwb** [comment]
Duplicate of https://github.com/getferdi/ferdi/issues/2274.
