### ISSUE TITLE
[Bug]: Ferdi not launching

### ISSUE THREAD

**Issue by Falciform** [getferdi/ferdi#2405]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.9

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 10 Enterprise version 20H2

### What arch are you using?

x64

### Last Known working version of Ferdi

5.6.9

### Steps to reproduce

This is what i did. No clue if this can be reproduced...

1. Install Ferdi
2. use Ferdi
2. Remove Ferdi for stupid reasons
3. Install Ferdi again
4. Launch Ferdi

### Expected Behavior

that Ferdi would open up

### Actual Behavior

Nothing happens.
The processes seem to be running in task manager but no Ferdi window opens (in the taskbar neither).

### Additional Information

So installed Ferdi and removed it.
Ever since i tried installing Ferdi again but without succes. I also feels as if the installer stops to soon. No error appears however so this could be just me.
The desktop icon is in place. When launching, nothing happens.

Ferdi is however visible in taskmanager. Ending those processes and launching Ferdi again puts me in exactly the same spot again.

I tried installing Ferdi 5.6.5 but it's the exact some thing.

I also tried removing all folders and registry entries but nothing seems to be able to fix this issue.

**Comment by kytwb** [comment]
Similar to https://github.com/getferdi/ferdi/issues/2345.
