### ISSUE TITLE
Showcase Ferdi on Producthunt

### ISSUE THREAD

**Issue by vantezzen** [getferdi/ferdi#243]
Now that Ferdi 5.4.0 is released we could think about showcasing Ferdi on <https://www.producthunt.com/> - just like [Franz did it](https://www.producthunt.com/posts/franz-5).

@kytwb WDYT?

**Comment by kytwb** [comment]
Good idea. I think we want to finish addressing the pending bugs and Sentry errors to reach a more stable release for now. Let's target for 5.5?

**Comment by vantezzen** [comment]
Depending on when Franz is releasing 5.5 - it looks like they havn't even started working on it.
I think we should just target when we adressed urgent bugs and sentry errors.

**Comment by kytwb** [comment]
We've been hunted 3 months ago apparently 😅 
https://www.producthunt.com/posts/ferdi

**Comment by vantezzen** [comment]
Interesting, but it looks like it didn't gain too much attention. Maybe we could create a separate post for Ferdi 5.5.0?
