### ISSUE TITLE
Order the workspaces using drag and drop

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#245]
**Is your feature request related to a problem? Please describe.**
I had added workspaces and also associated services that I want in each workspace. Then I realized that I wanted to change the order of the workspaces. This doesnt seem possible from the preferences overlay.

**Describe the solution you'd like**
In the screen when I select "workspaces", and I see the workspaces that I have configured, I would like the ability to drag and reorder them.

**Describe alternatives you've considered**
Delete all workspaces and recreate them would be a very painful option.

**Additional context**
Running on macOS Catalina, Ferdi version: 5.4.1-beta.2

**Comment by vantezzen** [comment]
Might be related to https://github.com/meetfranz/franz/issues/1620

**Comment by sampathBlam** [comment]
@vantezzen : Can I work on this ?

**Comment by vantezzen** [comment]
Yes, please do!

**Comment by vraravam** [comment]
pinging for removing staleness

**Comment by Inspirementt** [comment]
New user and this was something I noticed within a few minutes of using the app. Luckily I managed to add them in the right order pretty much when I set it up on my primary computer so didn't see it as too much of an issue, but when I logged in and got my settings and apps imported to my secondary computer, the workspaces were in a different order. So I'd like to rearrange them into the order I prefer.

**Comment by jaronschulz** [comment]
+1

**Comment by jurgenhaas** [comment]
Even on a single instance it appears that after restarting Ferdi, the workspaces are in a different order. As if it was random.

**Comment by PublicBenemy** [comment]
pinging for removing staleness

**Comment by vraravam** [comment]
remove staleness

**Comment by CoinAxe** [comment]
We need this please remove staleness

**Comment by LiamMoy** [comment]
I would also like the ability to customise the order of workspaces.

A workaround in the short term would be a feature to duplicate workspaces to the end of the list, as then the desired order could be achieved by duplicating and deleting the relevant workspaces.

**Comment by lnhrdt** [comment]
@vraravam I saw you recently closed this issue. Has a feature to order workspaces been released? Or is there another place to track this feature request? I'm unable to sort workspaces using v5.6.5.
