### ISSUE TITLE
Google Voice: Dark Mode not working

### ISSUE THREAD

**Issue by ylluminate** [getferdi/ferdi#249]
I'm finding that Dark Mode does not work at all on the Google Voice service.

**Comment by vantezzen** [comment]
What do you mean with "does not work at all"? Does it not get dark? Then it might be related to #158. Do the dark mode style look weird? Then it is probably a bug in DarkReader, not Ferdi.

**Comment by ylluminate** [comment]
You are correct, DarkReader is not activating currently in the stable release for Google Voice.

**Comment by kytwb** [comment]
Closing in favor of https://github.com/getferdi/ferdi/issues/158.
