### ISSUE TITLE
ProtonMail shows 1000 unread messages

### ISSUE THREAD

**Issue by MuffinGamedev** [getferdi/ferdi#250]
I'm using the ProtonMail service through Ferdi 5.3.3 on MacOS, and each time I get a new email, the number of notifications on Ferdi's icon increases not by 1, but by 1000. It seems to me like this might be an intentional decision to separate the notifications from that service from those of others, but I can't seem to find any way to disable it. None of my other services behave in this manner. The badge next to the ProtonMail icon within Ferdi displays the correct number of notifications; it is the Ferdi icon on the dock that displays the incorrect number.

<img width="68" alt="image" src="https://user-images.githubusercontent.com/33110037/70383515-17ba3480-193d-11ea-8a36-c98f3c40541b.png"><img width="90" alt="image" src="https://user-images.githubusercontent.com/33110037/70383519-24d72380-193d-11ea-9f44-e469d6d096cd.png">
<img width="69" alt="image" src="https://user-images.githubusercontent.com/33110037/70383560-c9596580-193d-11ea-9bef-18ab0d95204f.png"><img width="91" alt="image" src="https://user-images.githubusercontent.com/33110037/70383563-d5452780-193d-11ea-9ca6-d58be81279d2.png">

Expected behavior: upon receiving one email to my ProtonMail email address, with no other notifications present from other services, the red circle near Ferdi's icon on the dock and the red circle near ProtonMail's icon in Ferdi will both display "1" and increment by 1 each time a new email is received such that ProtonMail's badge displays the sum total of current notifications from its service and Ferdi's badge displays the sum total of current notifications from all services.

Actual behavior: upon receiving one email to my ProtonMail email address, with no other notifications present from other services, the red circle near ProtonMail's icon in Ferdi displays "1" and increments by 1 each time a new email is received, but the red circle near Ferdi's icon on the dock displays "1000" and increments by 1000 each time a new email is received.

**Comment by vantezzen** [comment]
The behaviour you described is not an intentional decision as you speculated - this is simply a bug in the ProtonMail recipe. I actually fixed this bug in the original repository several months ago (https://github.com/lukas-reineke/franz-recipe-proton-mail/pull/1) but it looks like Ferdi's recipe repository hasn't got the new version yet - that is something we'll have to do.

In short, the reason why this is happening is that the ProtonMail recipe returns the unread messages count as a string instead of a number. When Ferdi is now adding up all unread messages, it will execute `"1" + 0 + 0 + 0`, which - in JavaScript - will concatenate the string to `1000` instead of adding the numbers to `1`.

**Comment by vantezzen** [comment]
Just updated the ProtonMail recipe in the recipe repository - this change will be shipped with the next release of Ferdi.
Please keep in mind that the local recipe repository doesn't have auto-update functionality yet so you'll have to manually force Ferdi to update:
On Windows:
- Press `Windows Key + R` to open the "Run" dialog
- Type `%appdata%` and hit `Enter` to open your appdata folder
- Continue below

On Linux:
- Navigate to `~/.config`
- Continue below

On Mac:
- In the Finder menu bar, click on Go > Library
- Navigate to `Application Support`
- Continue below

Continue:
- Navigate to `Ferdi/recipes`
- Delete the "proton-mail" folder inside this folder
- Restart Ferdi
