### ISSUE TITLE
Cannot save Riot as service without changing default settings

### ISSUE THREAD

**Issue by keunes** [getferdi/ferdi#251]
**Describe the bug**
I can't save Riot without changing default service settings as 'Save service' button is greyed out.

**To Reproduce**
Install the app anew, click 'Get started' > 'Discover services' > 'Riot'. The 'Save service' is not enabled, but changing any setting (e.g. enabling dark mode) enables the button. I tried only Gmail, and there this doesn't seem to happen.

**Expected behavior**
'Save service' button is enabled, even with default settings.

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.3
- Ferdi version: 5.4.0

**Comment by vantezzen** [comment]
Might be related to https://github.com/getferdi/recipes/issues/5. Have you entered the URL?

**Comment by keunes** [comment]
Thanks for replying. Nope - I don't need a custom server, so I left the field empty.

**Comment by vantezzen** [comment]
As far as I know, the recipe was made so that if you don't use a custom server you should still input the default Riot URL (https://riot.im/app). Does the recipe work after you saved it without entering a URL?

**Comment by keunes** [comment]
> Does the recipe work after you saved it without entering a URL?

No, I can't save the server without entering a custom URL. From your message that's as it's intended?

> As far as I know, the recipe was made so that if you don't use a custom server you should still input the default Riot URL (https://riot.im/app).

As a user I'd expect it to work without entering a URL, as the screen specifically gives the option for a _custom_ url, and informs me of the default url. This makes me think that it will connect to the default server when no custom url is entered, and informs me of this as a simple FYI.

I guess an update to the recipe would be necessary to change current behaviour, so that it takes the default url if no custom url is entered by the user. Should this report be moved to the [recipy repository](https://github.com/getferdi/recipes) actually?

**Comment by vantezzen** [comment]
As far as I can see, there is currently no way to implement a recipe like you described into Ferdi, so this would need to be implemented into Ferdi or Franz first.

**Comment by keunes** [comment]
Ok, thanks. Will create a new ticket for that specific feature. In the meantime, I think the wording in the UI should be updated. I think removing 'custom' would help already.

**Comment by kytwb** [comment]
Closing in favor of https://github.com/getferdi/ferdi/issues/260. Thank you for contributing @keunes 🙏

**Comment by kytwb** [comment]
@keunes reviewed the copy from `Custom server` to `Service URL` with 57eed412 as you suggested.

**Comment by keunes** [comment]
Thanks @kytwb!
