### ISSUE TITLE
Cannot disable adaptable dark mode

### ISSUE THREAD

**Issue by FWDekker** [getferdi/ferdi#256]
**Describe the bug**
After enabling adaptable dark mode, it is not possible to disable it again.

**To reproduce**

1. Open the settings.
2. Enable "Join the Dark Side".
3. Enable "Enable adaptable Dark Mode".
4. Disable "Enable adaptable Dark Mode".

**Expected behavior**
Adaptable Dark Mode should be disabled.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Ubuntu 18.04
- Browser [e.g. chrome, safari]: Electron 6.0.10
- Version [e.g. 22]: 5.4.0

**Comment by kytwb** [comment]
There has been some enhancement shipped via https://github.com/getferdi/ferdi/commit/eff719b87c60097342d393922048662c32255d88 on this matter (available in [5.4.1-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.2)). But I recommend waiting for the next release before updating as the current betas have known issues.

**Comment by kytwb** [comment]
Closing in favor of https://github.com/getferdi/ferdi/issues/158.
