### ISSUE TITLE
Dark mode setting being read incorrectly

### ISSUE THREAD

**Issue by deadmeu** [getferdi/ferdi#258]
Enabling dark mode in the settings is not being reflected in the services.

**To Reproduce**

1. Join dark mode in the settings (also enabling adaptive & universal dark mode)
2. Open/Reload a service
3. Open the dev tools for the service and read the console
4. You will see that the light theme is being set

![image](https://user-images.githubusercontent.com/12111013/70844232-f059ef00-1e89-11ea-8d0c-763ff320f81e.png)

**Ferdi Version**: 5.4.0
**Electron**: 6.0.10
**Node.js Version**: 12.4.0
**Platform**: Linux

**Comment by kytwb** [comment]
There has been some enhancement shipped via https://github.com/getferdi/ferdi/commit/eff719b87c60097342d393922048662c32255d88 on this matter (available in [5.4.1-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.2)). But I recommend waiting for the next release before updating as the current betas have known issues.

**Comment by kytwb** [comment]
Closing in favor of https://github.com/getferdi/ferdi/issues/158.
