### ISSUE TITLE
Not able to reset password

### ISSUE THREAD

**Issue by p5hema2** [getferdi/ferdi#259]
As mentioned in the title i am not able to reset my password.
Upon clicking the password reset button i dont receive an email.

My registered email ist "martin.hess85@gmail.com" on api.getferdi.com

**Comment by martin-hess-arithnea** [comment]
Request URL: https://api.getferdi.com/v1/auth/password
Request Method: POST
Status Code: 404 
Remote Address: 104.31.81.187:443
Referrer Policy: no-referrer-when-downgrade
access-control-allow-origin: false
cf-cache-status: DYNAMIC
cf-ray: 5468de1c4b67bed8-FRA
content-encoding: br
content-type: text/plain; charset=utf-8
date: Tue, 17 Dec 2019 12:23:19 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
status: 404
Provisional headers are shown
Content-Type: application/json
Origin: file://
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Ferdi/5.4.0 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36
X-Franz-platform: win32
X-Franz-Source: desktop
X-Franz-System-Locale: de
X-Franz-Timezone-Offset: -60
X-Franz-Version: 5.4.0
Request Paylod: {"email":"martin.hess85@gmail.com"}

**Comment by vantezzen** [comment]
Looks like the Mail configuration on our server is incorrect. I just reset your password manually and send it to you via email.

**Comment by TimBaltic** [comment]
Hi there, also I need to reset password. How is this working? Thank you.

**Comment by kytwb** [comment]
Pending getferdi/server#16.
