### ISSUE TITLE
Virus warning with Avast when installing this Ferdi-Setup-5.4.0.exe

### ISSUE THREAD

**Issue by AlpineViper** [getferdi/ferdi#261]
**Describe the bug**
Attempting to run the installer Ferdi-Setup-5.4.0.exe, Avast detects a threat
First attempt - Threat identifieds as IDP.Alexa.51
Second attempts - Threat identified as IDP.Generic

**To Reproduce**
Attempt to run windows installer on a windows machine with avast free antivirus installed

**Screenshots**

![image](https://user-images.githubusercontent.com/28502863/71051905-d24c0180-219d-11ea-8bc7-69f169952e16.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Pro

**Smartphone (please complete the following information):**

**Additional context**
I'm basically just looking for reassurance the installer is not, in fact, infected with anything.

**Comment by kytwb** [comment]
After looking up the name of the threats you encountered, I believe those are false positives.  
Here is a [VirusTotal scan result](https://www.virustotal.com/gui/url/a2595f424319ca9227e5b3740f1a8db40a7a45048146025de79ff52fc3e08675/detection) of the binary you mentioned (Ferdi-Setup-5.4.0.exe).
