### ISSUE TITLE
Google Services Failure

### ISSUE THREAD

**Issue by ylluminate** [getferdi/ferdi#263]
I'm having the following same issue that Franz is having in Ferdi:
https://github.com/meetfranz/franz/issues/1720

Both in Gmail for some accounts AND for Google Voice:
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/P8uYbGOp/test.png)

**Comment by ylluminate** [comment]
It appears that changing the user agent may be the solution:
https://github.com/meetfranz/franz/issues/1720#issuecomment-566460763

Oddly enough, I believe that this could be readily tied to this:
https://github.com/getferdi/ferdi/issues/83#issuecomment-567107331

Basically if we had a way to define a custom Agent string we could also use this to insert custom JS. We could have both a global definition and individual service override.

**Comment by kytwb** [comment]
Related to https://github.com/getferdi/ferdi/issues/229. I agree that we should be able to override user agents in the service settings to fix that issue once and for all as we can't remotely update recipes to users for now.  

Opening a dedicated issue as an enhancement and writing up an explanation on how-to fix.

**Comment by kytwb** [comment]
Closed in favor of https://github.com/getferdi/ferdi/issues/264.

**Comment by kytwb** [comment]
In the meantime, please refer to https://github.com/getferdi/ferdi/issues/264#issuecomment-567138371.
