### ISSUE TITLE
Excessive CPU while Ferdi is inactive

### ISSUE THREAD

**Issue by probablykasper** [getferdi/ferdi#265]
I just noticed each of my 6 Ferdi renderer processes taking up 3% CPU (And that's an i7 7700K). All of those are Gmail services.

When opening Ferdi, each of these went down to 0.1%. I don't have the hibernation setting enabled, but when i opened it, the window was completely gray for a second, as if it was hibernating in some way.

- OS: macOS
- Version: 5.4.0

**Comment by kytwb** [comment]
Thank you for reporting this and giving us additional details. Closing in favor of https://github.com/getferdi/ferdi/issues/62.
