### ISSUE TITLE
Auto-focus password field when locked

### ISSUE THREAD

**Issue by keunes** [getferdi/ferdi#269]
**Is your feature request related to a problem? Please describe.**
Ferdi auto-launches on startup, but locked. With the screen open, I always have to click on the password field to activate it.

**Describe the solution you'd like**
Auto-focus on the password field whenever Ferdi is locked, so I can start typing immediately.

**Comment by kytwb** [comment]
Done with https://github.com/getferdi/ferdi/commit/22d76adbe613fd474eb9671cf283edda7f723b76, will ship in the next release.
Thank you for the enhancement suggestion! 🙏

**Comment by keunes** [comment]
Great, thanks!

**Comment by kytwb** [comment]
Shipped in [v5.4.1-beta.4](https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.4).
