### ISSUE TITLE
Option to hide navigation bar in Custom Website recipe

### ISSUE THREAD

**Issue by keunes** [getferdi/ferdi#270]
No particular problem, but it would be nice to have an option to hide the navigation bar in the Custom Website recipe.

**Comment by ericse** [comment]
An option to show/hide the navigation bar on any service would be even more generic and very nice

**Comment by keunes** [comment]
> show/hide the navigation bar on any service

IIRC the bar is not displayed on any/most services(?) - at leastnoyt on the ones I use.

**Comment by vantezzen** [comment]
Yes, the bar should normally not be displayed on any other service. Maybe you have the option "Show navigation bar for all services" enabled in settings?

**Comment by vantezzen** [comment]
Adding this via #270

**Comment by keunes** [comment]
You probably mean #403 ;)
Thanks!

**Comment by vantezzen** [comment]
Oh yes, has the wrong number in the clipboard 😅

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.2).
