### ISSUE TITLE
Allow svg as filetype for custom icon

### ISSUE THREAD

**Issue by keunes** [getferdi/ferdi#271]
**Is your feature request related to a problem? Please describe.**
The [only high-quality image](https://app.monicahq.com/img/monica.svg) of a custom service (Monica) is in the svg file format. I can't add this image as custom icon.

**Describe the solution you'd like**
Allow me to add svg as file type for custom icons.

**Comment by vantezzen** [comment]
Transferred this to the main repo. For now you can use something like <https://convertio.co/svg-png/> to convert you SVG to PNG.

**Comment by kytwb** [comment]
Allowed SVG with 4e01c44, will ship in the next release.  
Thank you for the enhancement suggestion! 🙏

**Comment by keunes** [comment]
Thanks again :pray:

**Comment by kytwb** [comment]
Shipped in [v5.4.1-beta.4](https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.4).

**Comment by greghab** [comment]
Hmm. Running 5.6.0-beta.5 on NixOS. SVG's show up in custom icon edit screen after upload, but when I click save, it's black on the left hand side panel. Had to use a png.
