### ISSUE TITLE
Enhance app icon on scaled Windows

### ISSUE THREAD

**Issue by VOOM108** [getferdi/ferdi#272]
**Is your feature request related to a problem? Please describe.**
The main app icon has very pixelated edges on Win 10. This applies to the taskbar as well as to the tray. Given the modern and polished appearance of the GUI itself that looks very unfitting 

**Describe the solution you'd like**
Include a high quality scalable app icon

**Comment by vantezzen** [comment]
Is this similar to #159?

**Comment by VOOM108** [comment]
Probably the same

**Comment by vantezzen** [comment]
What version are you using?

**Comment by VOOM108** [comment]
5.4.0

**Comment by vantezzen** [comment]
Hmm ok, the issue I linked should have fixed this in 5.4.0 but it looks like it didn't - reopening the issue

**Comment by VOOM108** [comment]
I have windows scaled to 110% but all other icons look sharp without exception
![task](https://user-images.githubusercontent.com/16562946/71324294-866ec480-24dd-11ea-9728-b15eb24bb705.png)
![tray](https://user-images.githubusercontent.com/16562946/71324295-866ec480-24dd-11ea-8c4e-4655e612a39c.png)

**Comment by VOOM108** [comment]
I think the point ist to include a multisize-ico in the exe file, not just a single size. From the looks of it you inluded a singel size icon, and windows does not scale that down nicely. So I took the largest icon-PNG from the repo and converted it to a multisize-ico with all sizes from 32 to 256px. With resource hacker I replaced the icon in ferdi.exe with the multisize-version - viola! :) 

![ferdi-multi-icon](https://user-images.githubusercontent.com/16562946/71327447-db740000-2508-11ea-9df4-73fcc4f177e5.png)

**Comment by kytwb** [comment]
I am not sure what to change here and I'm missing a Windows install to give it a try; nonetheless, I see we are already referencing an 256px [icon](https://github.com/getferdi/ferdi/blob/22d76adbe613fd474eb9671cf283edda7f723b76/electron-builder.yml#L29) in the electron-builder file, but maybe we need to include more size for Windows to resolve the relevant one and show the scaled version correctly?

> Please note — build resources is not packed into the app. If you need to use some files, e.g. as tray icon, please include required files explicitly: "files": ["**/*", "build/icon.*"]

Via https://www.electron.build/configuration/configuration#MetadataDirectories-buildResources
Will have to give it a try by specifically adding `builder-helper/images/icons` files to the `win` section?

**Comment by VOOM108** [comment]
I don't know how this is built on your side, but Resource Hacker excepts an .ico file. And just like for favicon.ico files that file can be multisize / multilayer - containing different sizes from 16px up to 256px (usually, I don't think there is a limit, though). If windows does the scaling down from 256px, it looks rugged. With the exe providing different sizes Windows will use the appropriate one. 

![rh-ferdi-multisize-ico](https://user-images.githubusercontent.com/16562946/71372886-d91baf80-25b5-11ea-81e4-12536354eaa1.png)

btw which file contains the tray icon?

**Comment by kytwb** [comment]
I think it's the file referenced [here](https://github.com/getferdi/ferdi/blob/22d76adbe613fd474eb9671cf283edda7f723b76/electron-builder.yml#L29) for now. Maybe we can try to replace the current (not-multisize) .ico file with the (multisize) .ico you generated?

**Comment by VOOM108** [comment]
I used the icon-ferdi-seamless.png and sent it through a converter like this: https://icoconvert.com/

In Step 4 select custom multisize and the sizes required (I selected all from 16 to 256), then "Convert ICO"

I would paste it here, but the Editor does not take .ico files

**Comment by kytwb** [comment]
Roger that, giving it a try now.

**Comment by kytwb** [comment]
Shipped in [v5.4.1-beta.4](https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.4).  
@VOOM108 Can you confirm that fixed it?

**Comment by VOOM108** [comment]
Yes, that fixed it, looks good :)
