### ISSUE TITLE
Two Slack workspaces, only one loads

### ISSUE THREAD

**Issue by VOOM108** [getferdi/ferdi#273]
**Describe the bug**
In 5.4.0 on Windows 10 I added two Slack workspaces. The second always shows "ERR_NAME_NOT RESOLVED". I could put the workspace-url into the address bar and open the workspace manually, but as soon as I switch to a different service and go back to that workspace the error is back. 

**To Reproduce**
Add two slack workspaces via add services

**Expected behavior**
Both workspaces load successfully the same way

**Screenshots**

![ferdi-slack](https://user-images.githubusercontent.com/16562946/71323675-085aef80-24d6-11ea-9a65-5c3d27074299.png)

**Comment by VOOM108** [comment]
This happens every time I close Ferdi - after reopening I need to log in newly for messenger, and manually go to the second slack workspace. Gmail loads fine, but keeps stating that: "Gmail has authentication problems. Please login to solve the problem" - while it looks fine otherwise and everything works.

**Comment by VOOM108** [comment]
Removed the second slack service and re-added. Now it seems to work. Other two problems remain.

**Comment by VOOM108** [comment]
Facebook: in Dark Mode the switch for "Stay logged in" was invisible. Switched to light mode for first login, enabled that and now facebook remains logged in. 

Gmail not being fully authenticated remains - whatever that means

**Comment by kytwb** [comment]
Thanks for reporting the different issues you've encountered. 

I think the `ERR_NAME_NOT_RESOLVED` error is out of our scope for now as related to your connection, or a temporary DNS issue afaik. We could enhance the user experience on this point by implementing a retry strategy I guess. 

Regarding the Dark Mode issue, I think this is related to [Dark Reader](https://github.com/darkreader/darkreader/issues?utf8=%E2%9C%93&q=facebook) and should be fixed/enhanced there directly; in the meantime, you should be able to bring your own edits to the Dark Mode of that particular service by editing `darkmode.css` via the service settings.

<img width="304" alt="Screen Shot 2019-12-23 at 2 31 22 PM" src="https://user-images.githubusercontent.com/412895/71360681-ea05fa00-2590-11ea-9583-a0673cdba03d.png">

Regarding the Google service issue, I'll refer you to https://github.com/getferdi/ferdi/issues/264 where this is being discussed.
