### ISSUE TITLE
Gmail: authentication error message

### ISSUE THREAD

**Issue by VOOM108** [getferdi/ferdi#274]
**Describe the bug**
Gmail account seems to work, but error message remains (authentication problems, try to login)

**To Reproduce**
Log into Gmail account in Ferdi Gmail service
Red error message on top remains

**Screenshots**

![ferdi-gmail](https://user-images.githubusercontent.com/16562946/71324118-49093780-24db-11ea-9f64-33b499cbbd71.png)

**Comment by kytwb** [comment]
Closing in favor of https://github.com/getferdi/ferdi/issues/264
