### ISSUE TITLE
Messenger: unread messages badge shows wrong and not removable count

### ISSUE THREAD

**Issue by VOOM108** [getferdi/ferdi#275]
**Describe the bug**
While everything is read and messenger in the browser does not show any unread notifications, in Ferdi the Messenger service badge remains at "2". I find no way to remove this wrong notification count... 

**Screenshots**
![ferdi-messenger-badge](https://user-images.githubusercontent.com/16562946/71324159-c7fe7000-24db-11ea-9ce2-ba3a4651316c.png)

**Comment by VOOM108** [comment]
It seems the way messenger itself counts and discards notifications and how Ferdi counts is different. I found some very old group chat messages that were unread and that solved it.

**Comment by vantezzen** [comment]
This looks to be a problem with the messenger recipe (https://github.com/meetfranz/recipe-messenger) and not Ferdi. Please report your issue there instead
