### ISSUE TITLE
Cannot close About window

### ISSUE THREAD

**Issue by keunes** [getferdi/ferdi#277]
**Describe the bug**
I opened the 'about' window via the menu in the top of the window. I can't seem to close it - except I just discovered pressing Escape does the trick.

**Expected behavior**
Have a 'close' icon or close the window when clicking on/opening Ferdi's main window.

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04.3
- Version: 5.4.0

**Comment by kytwb** [comment]
Can't you close it with the title bar buttons?  
On macOS I close it with the red button (or the ESC key as you specified).

<img width="321" alt="Screen Shot 2019-12-23 at 2 35 13 PM" src="https://user-images.githubusercontent.com/412895/71360856-72849a80-2591-11ea-87c6-05c71d797cac.png">

**Comment by keunes** [comment]
Nope, I don't have these title bar windows - let alone a title bar at all :)
Using Ubuntu 18.04.3 LTS. I'm using the [Unite GNOME Shell Extension](https://extensions.gnome.org/extension/1287/unite/) which moves my window buttons from the window to the top bar, but disabling this Shell Extension has no effect.
![Screenshot from 2019-12-23 22-30-25](https://user-images.githubusercontent.com/11229646/71381662-b947b400-25d4-11ea-9dd4-0baa22ae7a84.png)
You see here no window buttons anywhere - when I close the About window they appear again (for Ferdi's main window).

On a related note: the window name of this thing is "Franz Ferdinand" - this should probably be just "Ferdi" to avoid confusion.

**Comment by mhatvan** [comment]
This is how the About window looks with 5.6.1.-nightly.18, there is an OK button to close it again.

![Screenshot from 2021-08-08 23-38-03](https://user-images.githubusercontent.com/16797721/128646471-f2aee19e-6e3b-44d2-8cbd-e3cda58edb50.png)

Can you check if you have a way of closing the window now too?

**Comment by keunes** [comment]
Yes, thanks. I can close the window now :)

**Comment by bittner** [comment]
Regression or, at least, a similar issue: #1929
