### ISSUE TITLE
Allow to disable hibernation for individual services

### ISSUE THREAD

**Issue by ylluminate** [getferdi/ferdi#280]
One thing I've noticed, which is really troublesome for me in comparison to Rambox, is that services seem to be shut down (presumably to save memory) after a certain amount of time. I'm not sure what this timeout limit is, but it would be good if we could define this limit to even include "never". I have some services that simply need to be open always in order to be able to respond more quickly to some customers vs having the service load back up.

**Comment by kytwb** [comment]
This is the hibernate (see https://github.com/getferdi/ferdi/issues/75). We could implement the feature and timer config at the global and service level as an enhancement.

**Comment by vantezzen** [comment]
You should be able to completely disable hibernation using the toggle above the habit time selection.

**Comment by TheKevJames** [comment]
A semi-related feature request in case anyone is considering picking this issue up:

It would be useful to be able to set individual hibernation timers (or at least toggle hibernation individually); eg. I want all my services to hibernate except for one or two high-priority ones (or perhaps I want the high-prio services to hibernate slower).

**Comment by vantezzen** [comment]
Closing this as hibernation can already be turned off

**Comment by ylluminate** [comment]
But not on a per app / service basis. Global timing is not sufficient. 

If you want to have hibernation, just move it to a per app function instead of being global. That's what's needed here.

**Comment by vantezzen** [comment]
Oh I'm sorry, I misunderstood the title there. Clearing up the title and reopening the request - is that title right?

**Comment by TheKevJames** [comment]
As per discussion, I might think to modify the title to "Allow toggling or configuring hibernation for individual services", although that could just-as-easily be two different feature requests.

**Comment by ylluminate** [comment]
Hmmm. I guess I'm just biased to how I phrased it, but I suppose you're welcome to rephrase this however you wish.  I think the issue's understood at this point.

**Comment by teras** [comment]
Is it just me, or after restart the application the preference to stop a specific application from entering hibernate state is always disabled?

**Comment by alisterburt** [comment]
+1 to teras', individual app hibernation settings don't seem to be staying for me either
