### ISSUE TITLE
Cannot login Google Calendar (unsafe warning)

### ISSUE THREAD

**Issue by l4jos** [getferdi/ferdi#286]
**Describe the bug**
Google blocks logging in to Calendar services in Ferdi. Can you bypass this?

**To Reproduce**

1. Go to "services" in top menu bar
2. Click on "add new service"
3. Search for Google Calendar
4. Login with your account
5. See screenshot

![Screenshot_2019-12-30_11-03-59](https://user-images.githubusercontent.com/52865939/71577508-b711b800-2af4-11ea-816d-aaf3bf31c22a.png)

**Expected behavior**
Would like to view my Calendar in Ferdi. Not a big deal if I can't, but apparently there is no acknowledgement yet between Ferdi and Google.

**Desktop**
- OS: 5.3.18-1-MANJARO
- Browser: Firefox
- Version: 5.4.0

**Smartphone**

- Device: Galaxy S7 Edge
- OS: LineageOS 16 (Android 9)
- Browser: Firefox

**Additional context**
My Google account has 2FA on, don't know if this makes sense, just saying.

**Comment by kytwb** [comment]
Have you tried what is recommended in https://github.com/getferdi/ferdi/issues/264#issuecomment-567138371?

**Comment by l4jos** [comment]
Yes, that works. Thanks.
