### ISSUE TITLE
Sign Up doesn't work

### ISSUE THREAD

**Issue by paulwaldmann** [getferdi/ferdi#287]
**Describe the bug**
Sign up doesn't work. No error is shown and no effect when clicking 'Create account'

**To Reproduce**

1. Go to 'Sign Up Form'
2. Fill out Form 
3. Press 'Create account'

**Expected behavior**
Execute Sign Up process

**Screenshots**
![ferdi](https://user-images.githubusercontent.com/32001342/71584663-a0984a80-2b4e-11ea-9ea8-aed7ed7481bc.png)

**Desktop (please complete the following information):**

- OS: Manjaro Linux
- Browser: Brave
- Version 1.1.23

**Additional context**
The screenshot is from Developer Tools inside Ferdi

**Comment by vantezzen** [comment]
Looks like Ferdi couldn't load any server configuration. Could you please execute the following command in the console and post its output here:
```javascript
console.log("Stores:", window.ferdi.stores, "Settings:", window.ferdi.stores.settings, "All settings:", window.ferdi.stores.settings.all, "Server:", window.ferdi.stores.settings.all.app.server);
```

**Comment by paulwaldmann** [comment]
```Stores: {router: RouterStore, app: _temp, user: _temp, features: _temp, settings: _temp, …} Settings: _temp {stores: {…}, api: {…}, actions: {…}, _reactions: Array(0), fileSystemSettingsTypes: Array(2), …} All settings: {app: Proxy, proxy: Proxy, service: {…}, stats: {…}, migration: {…}} Server: You are using Ferdi without a server```

**Comment by vantezzen** [comment]
Hmm ok, would have been interesting what it was before selecting the option as that overwrote whatever has been there.

When changing the server you will have to log out as Ferdi's current Auth token won't be valid on the new server - so the error you are getting is expected.

**Comment by paulwaldmann** [comment]
Okay, edited my previous reply tho. How to proceed? If you want I can reinstall Ferdi and follow a step by step guide to help you reproduce the error. Alternatively, you can join my desktop via AnyDesk or such and take a look for yourself. Ready to help!

**Comment by vantezzen** [comment]
Have you changed any settings before you tried creating an account? Can you please open Ferdi's settings, in the bottom left corner click on "Login" or "Logout" (depending on what button you have there) and try signing up again?

**Comment by paulwaldmann** [comment]
Got a "Login" button there, upon clicking it, Ferdi reloads saying "logging you out" and loads the "Sign in" page. I clicked "Create a free account", filled out the form and clicked "Create account". Problem persists.

And no, I've not made any changes whatsoever to Ferdi, Just downloaded it from AUR using pamac and went straight for the sign up.

**Comment by paulwaldmann** [comment]
Okay, so I reinstalled Ferdi and it loaded as expected the default startup screen (Login, Sign up, etc.) but also encountered the `There were errors while trying to perform an authenticated request. Please try logging out and back in if this error persists.` error right after launching the app.

**Comment by vantezzen** [comment]
Could you try deleting Ferdi's config folder in `~/.config/ferdi`?

**Comment by paulwaldmann** [comment]
Now, nothing works any more lulz

![Screenshot_20191231_010725](https://user-images.githubusercontent.com/32001342/71592119-f0d0d600-2b69-11ea-8a95-90d901aa1c77.png)

**Comment by paulwaldmann** [comment]
I went on Logout and tried to sign up again, error persists.

**Comment by eyriewow** [comment]
I am encountering the same issue on Windows 10 and Ferdi 5.4.0.
![LalL5E](https://user-images.githubusercontent.com/20689060/71618725-366cbd80-2bc1-11ea-8f50-c63d475a7252.png)

**Comment by smt** [comment]
I'm encountering the same issue as @eyriewow on MacOS 10.14.6 and Ferdi 5.4.0

**Comment by juanjotoronja** [comment]
same for me Windows 7 x64  and Ferdi 5.4.0

**Comment by eyriewow** [comment]
> UPDATE: Uninstalled version 5.4.0 and installed 5.3.3 and it let me create an account and login, then after update was autmomatically downloaded by the app everything is working as it should.

Can confirm this also worked for me.

**Comment by VOOM108** [comment]
Win 10 x64, 5.4.1-beta.4 had this problem since 5.4.0 with a fresh first install

**Comment by vantezzen** [comment]
It looks like the bug was that Franz/Ferdi 5.4.0 is using a different URL to fetch its feature list and is also expecting some new config parameters. I just updated the server via https://github.com/getferdi/server/commit/5aff6ab34a2f0d60d8cccdfe244e62e3256dbc15 - you should now be able to sign up and sign in to Ferdi 5.4.0 (no client update needed)

**Comment by VOOM108** [comment]
This worked... But my services I created locally are not reflected when logged in. Any easy way to synchronize?

**Comment by vantezzen** [comment]
What do you mean with "that you created locally"? Have you created them while using Ferdi without an account? In this case there is currently no way to synchronize them - they are seperate accounts (maybe a feature we'll implement in the future).
Your services are however not deleted when you logged into your account on Ferdi's server. You can simply logout again and choose to use Ferdi without an account and your services should still be present.

**Comment by VOOM108** [comment]
Ok I see.... I created a complex setup with 13 services, partly with custom darkmode.css and had hoped there was an easy way to transfer these to the online account....

**Comment by vantezzen** [comment]
Sorry, but the Ferdi server currently only supports importing from Franz's server. Your custom `darkmode.css` should however still be present and not need to be "transferred" in any way as they are stored locally and not on the server.

**Comment by vantezzen** [comment]
@VOOM108 I just implemented the account transfer for the internal server via https://github.com/getferdi/internal-server/commit/f534147e00fc889769845b9207572ce63ef3cad7 - this option will be available in the next release of Ferdi.

**Comment by VOOM108** [comment]
Cool, I am sure that will be widely appreciated! I just finished the manual transfer, took 30 minutes all in all...

**Comment by vantezzen** [comment]
Details on how to transfer data between servers is now also available at https://github.com/getferdi/ferdi/wiki/Transferring-data-between-servers
