### ISSUE TITLE
Start minimized in tray on startup

### ISSUE THREAD

**Issue by juanjotoronja** [getferdi/ferdi#288]
Minimize and Show Ferdi in system tray are checked in settings but still main window show up on launch.

OS: Windows 7 x64
Version: 5.4.0

**Comment by kytwb** [comment]
Marking as enhancement request to add a **Start minimized in tray** in there:

<img width="457" alt="Screen Shot 2020-01-22 at 7 51 03 PM" src="https://user-images.githubusercontent.com/412895/72924078-8b2ece80-3d50-11ea-8f8e-0376aa1e1641.png">

**Comment by kytwb** [comment]
Shipped in [5.4.4-beta.1](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.1).
