### ISSUE TITLE
Addons

### ISSUE THREAD

**Issue by Philipp0205** [getferdi/ferdi#293]
**Is your feature request related to a problem? Please describe.**
I like using keyboard shortcuts for most things I am doing. For browsers there are addons like Surfingskeys  which allow the user to navigate trought the web and webapps without using the mouse.

**Describe the solution you'd like**
It would be nice to have the ability to install browser addons in Ferdi. I guess Ferdi is based on Chromium but I have no idea if this can be implemented easily.

**Additional context**
I am using Ferdi on Ubuntu 19.10.

**Comment by vantezzen** [comment]
Duplicate of #113
