### ISSUE TITLE
Can't remove workspace

### ISSUE THREAD

**Issue by Celtiore** [getferdi/ferdi#294]
**Describe the bug**
I can't remove workspaces

ferdi 5,4,1 beta4

**To Reproduce**

simply click : remove workspace"

![Capture d’écran 2020-01-04 à 12 07 53](https://user-images.githubusercontent.com/38855912/71764699-67176480-2eeb-11ea-91da-5928935ff8cd.png)

**Comment by vraravam** [comment]
I am also facing the same issue. Running the latest beta version: 5.4.1-beta.3 (5.4.1-beta.3.923)

**Comment by vantezzen** [comment]
There was a problem in how the server validated the input data when deleting a workspace.
The problem has now been fixed. If you are using Ferdi's API you can now delete workspaces, if you use Ferdi without an account this fix will be shipped with the next update.

**Comment by vraravam** [comment]
Is there a beta release with this fix?

sent using an itty-bitty keyboard that assumes it can think

**Comment by vantezzen** [comment]
Not yet, we will release one in the next days.

**Comment by vantezzen** [comment]
I just started the build for 5.4.1-beta.6 - it should be available in a few minutes.
