### ISSUE TITLE
Context menu does not work in Telegram

### ISSUE THREAD

**Issue by IngwiePhoenix** [getferdi/ferdi#300]
**Describe the bug**
Right-clicking conversations in Telegram does not work and opens the "default" context menu, containing navigation buttons.

**To Reproduce**
Add the Telegram service and log in. Optionally, I use the dark Mode - while this should not be an interference, I thought I'd mention it anyway. If you now try to right-click a conversation, you won't see the options to delete chats or alike at all.

**Expected behavior**
A context menu to delete/archive chats and alike.

**Desktop (please complete the following information):**

- OS: Windows 10 (1909)
- Browser Windows Desktop App (Electron/Chromium)
- Version Latest, downloaded today.

**Comment by kytwb** [comment]
The current [Telegram web](https://web.telegram.org/) application doesn't have a custom context menu when right-clicking conversations (see [thread](https://www.reddit.com/r/Telegram/comments/d71574/how_do_i_archive_chats_on_the_telegram_web/) and screenshot):

<img width="572" alt="Screen Shot 2020-03-03 at 3 00 03 AM" src="https://user-images.githubusercontent.com/412895/75735567-4016bc80-5cfb-11ea-8df8-b32584cdc0b6.png">

There is a new Telegram web application being developed [here](https://evgeny-nadymov.github.io/telegram-react/).  
It has a custom context menu to administrate conversations:

<img width="590" alt="Screen Shot 2020-03-03 at 3 03 19 AM" src="https://user-images.githubusercontent.com/412895/75735715-9dab0900-5cfb-11ea-9a18-365c6665f1e2.png">

**Comment by kytwb** [comment]
Closing in favour of https://github.com/getferdi/recipes/issues/56.  
You can use the new client URL in a Custom Website service in the meantime.
