### ISSUE TITLE
No Dark-Mode for Github?

### ISSUE THREAD

**Issue by IngwiePhoenix** [getferdi/ferdi#302]
**Describe the bug**
Enabling dark-mode for the Github service does not do anything - the `darkmode.css` is literally blank.

**To Reproduce**
Enable Dark-Mode on the Github service.

**Expected behavior**
Well...I expected Github to be dark. o.o

**Screenshots**
None needed.

**Desktop (please complete the following information):**

- OS: Windows 10 (1909)
- Browser Windows Desktop App (Electron/Chromium)
- Version Latest

**Comment by vantezzen** [comment]
The `darkmode.css` is mostly meant to be used with your own styles - so it is expected that this file will be blank, only very few recipes ship with their own darkmode styles. If you want to use Ferdi's universal darkmode you can delete your `darkmode.css` and make sure you've enabled universal dark mode in Ferdi's settings.
