### ISSUE TITLE
Make custom window draggable optional

### ISSUE THREAD

**Issue by probablykasper** [getferdi/ferdi#304]
I often find the title bar's draggable area to be annoying. When I try to select text in Gmail, this can happen:
![screenrecording](https://user-images.githubusercontent.com/11315492/72433475-a66e6c80-3799-11ea-8f68-ddcfa87c0d18.gif)

I can avoid this by selecting text a little bit further down. As you can see here, the `.window-draggable` element covers half of the search bar:
![image converted](https://user-images.githubusercontent.com/11315492/72435075-804acb80-379d-11ea-8aa8-0241adf472b8.jpg)

One thing to note is that the Ferdi's draggable area is taller than a usual macOS title bar. VSCode's div-implemented title bar has a height of 22px, while Ferdi's `window-draggable` has a height of 35px.

### Solution
The only sensible solution I see is to add a title bar to the top of the window. Should be implemented through a div for backwards-compatibility beyond macOS Mojave. Assuming there's no setting for this title bar, it should be hidden when the navigation bar is visible.

#### Navigation bar solution
This issue still happens if you try to select text in the navigation bar. From inspecting Discord, I'm pretty sure the solution to that is to remove the `window-draggable` element and add `-webkit-app-region: drag` to the navigation bar element. Then, add `-webkit-app-region: no-drag` to any child elements the user can interact with (search bar, buttons etc).

### Versions
Ferdi 5.4.0
macOS 10.14.6
Note: I'm just talking about macOS, no idea how this works for Windows and Linux.

**Comment by thegoldgoat** [comment]
I find it rather annoying too on Telegram, and I see that Franz has the same problem. (see [this](https://github.com/meetfranz/franz/issues/1308) for example)

## Stupid solution

Don't use Client Side Decoration and let the MacOS compositor render a standard titlebar, this sacrifices a few pixels space

## Alternative solution

Maybe the titlebar should propagate the mouse events only if it is not dragging the window, so that the mouse events propagates only for mouse clicks ( I don't know if this could be implemented at all )

**Comment by probablykasper** [comment]
@thegoldgoat Your alternative solution sounds like what currently happens. Like you can see in the GIF, clicks are propagated and click-and-drag moves the window. The problem is, that the latter interferes with text selection (double-click to maximize window also would)

**Comment by thegoldgoat** [comment]
@probablykasper what I meant is that when you are click-and-dragging the mouse event should _not_ be propagated to the web page: this is what is happening in your gif; I actually misunderstood that your problem was text selection, sorry.

Now, considering text selection, I don’t see any easy and practical solution other than a dedicated title bar

**Comment by kytwb** [comment]
> VSCode's div-implemented title bar has a height of 22px, while Ferdi's window-draggable has a height of 35px.

I think reducing the height of the draggable area is the easiest solution for now. Implementing double click handling for macOS has been [done before](https://github.com/electron/fiddle/pull/156/files); we would need to add the onDoubleClick handler on: 

https://github.com/getferdi/ferdi/blob/7cc26c9b84191e9ecff0866a7b5d5248bb4207b1/src/index.html#L10

**Comment by kytwb** [comment]
TIL I'm not very good at text selection, but reducing the height of the window-draggable does help a bit:

![Kapture 2020-03-03 at 21 36 38](https://user-images.githubusercontent.com/412895/75817415-4eb2b180-5d97-11ea-98b2-288ea4741d22.gif)

**Comment by probablykasper** [comment]
@kytwb I believe you can add window-draggable to the URL bar when it's visible, and disable the window-draggable div.

I'd still prefer to have an actual title bar though

**Comment by thegoldgoat** [comment]
The reduced height seems better for text selection, but it won’t ever be perfect in my opinion.

An actual title bar is the best easy solution, considering it takes just a few pixels but really improves the UX.

**Comment by kytwb** [comment]
Let's reduce the height first to improve the title bar draggable area and the issue exposed in the original message?

Then we could propose to add an option to toggle the frameless window effect on/off? Ferdi window being frameless is one of the app visual characteristic; I could see it bothering some users if the default changed from one update to another, thus I think it would be more appropriate to offer it as an option.

WDYT?

**Comment by thegoldgoat** [comment]
@kytwb 
Seems like a good starting point.

You are also right, changing defaults is always risky.

However, reducing the height does not impact the visual at all, seems reasonable.

**Comment by kytwb** [comment]
Submitted a pull request to align the height to VSCode's as originally mentioned by @probablykasper. Updated the ticket accordingly to reflect what was previously discussed.

**Comment by kytwb** [comment]
📦 Shipped in [v5.5.0-gm](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm).
