### ISSUE TITLE
System tray icon default action

### ISSUE THREAD

**Issue by flinguin** [getferdi/ferdi#307]
on macOS the system tray icon opens a droptdown with two options (show/quit ferdi)
it would be nice if a single click on the tray icon would show ferdi - now you need to click twice to show the app every time.

the desired behavior can for example be examined with the telegram desktop app on mac where a single click opens the app and a second click opens the menu. left and right clicks would also be fine :)

**Comment by squatto** [comment]
This would be a great change! I'd suggest that a single primary/left click opens the app, and a secondary/right click opens the menu.

**Comment by kytwb** [comment]
Thank you for the suggestion @flinguin 🙏

**Comment by kytwb** [comment]
As suggested per @m-vlad, we could also:

> Make the click on the tray icon minimize the app back.

So I suggest a simple click on the tray icon toggle the tray minimization, and right click shows the menu.

**Comment by kytwb** [comment]
Quick update:

> a simple click on the tray icon toggle the tray minimization, and right click shows the menu

![Kapture 2020-02-21 at 16 08 54](https://user-images.githubusercontent.com/412895/75048939-a57fd780-54c9-11ea-9e11-083e32f2d75c.gif)

Also moved the Windows-specific setting next to the other tray-related settings:

<img width="400" alt="Screen Shot 2020-02-21 at 4 52 22 PM" src="https://user-images.githubusercontent.com/412895/75049505-98afb380-54ca-11ea-93a0-a323ff47a117.png">

Will come up with a pull request by tomorrow!

**Comment by kytwb** [comment]
Pull request reviewed by @vantezzen and merged; it will ship in the next release! 🎉 Thank you @flinguin @squatto and @m-vlad for the feedback!

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.2).

**Comment by Mic92** [comment]
It seems on Linux/X11 using this beta makes the systray icon be hidden for me. Can anyone confirm that?

**Comment by kytwb** [comment]
@Mic92 Confirmed via https://github.com/getferdi/ferdi/issues/437.
