### ISSUE TITLE
.dmg is missing in releases/5.4.1-beta.5

### ISSUE THREAD

**Issue by frankhommers** [getferdi/ferdi#309]
The .dmg is missing in releases/5.4.1-beta.5 so I can't try ferdi without an account....

**Comment by kytwb** [comment]
Adressed vi https://github.com/getferdi/ferdi/commit/9d04827adca0ff4542d281b1d950524ab761529f, re-releasing.

**Comment by kytwb** [comment]
Fixed in [v5.4.1-beta.5](https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.5).
