### ISSUE TITLE
security locked password

### ISSUE THREAD

**Issue by garffi** [getferdi/ferdi#311]
**Describe the bug**
Clear display of the ferdi delocking password

**To Reproduce**
cat  $HOME/.config/Ferdi/config/settings.json |grep lockedPassword 

version 5.4

**Comment by vantezzen** [comment]
Duplicate of #230

**Comment by ammarmalhas** [comment]
I am not sure this is where I need to report what I am seeing. I started using Ferdi v 5.5 again a week ago. The password lock (automatic after x minutes) is not working! I also notices that when I click on a notification of received WhatsApp or Telegram or SMS messages on my Mac OS Catalina, Ferdi windows gets focus (opens) and is unlocked without entering a password! I think thing were better in the version before this one, not sure what version number.

**Comment by ammarmalhas** [comment]
Furthermore, when unlocking Ferdi, WhatsApp and Telegram take a long time to load the messages (maybe I have many), it takes 10-20! Should the messages not be already loaded, or is Ferdi un-encrypting the messages and taking time to do so?

**Comment by ammarmalhas** [comment]
A third note, launching Ferdi stops "Typinator", I do not believe this should be!

**Comment by ammarmalhas** [comment]
If I need to report these as new bugs, please remind me of how to do so? many thanks.
