### ISSUE TITLE
Work-spaces not working as expected.

### ISSUE THREAD

**Issue by ashutoshpw** [getferdi/ferdi#312]
Workspaces were supposed to have different sessions in the application but when I added service (Custom Website) in two workspaces and logged in into the service from Workspace 1, it automatically logged in into Workspace 2. 

### Expected Behavior
When I logged in into "SERVICE" in Workspace 1, I should be able to login to another account in Workspace 2. 

### Current Behavior
When I logged in into a particular service in Workspace 1, it automatically login the service with the same account in Workspace 2. 

### Possible Solution
No Idea

### Steps to Reproduce (for bugs)
1. Login into getferdi
2. Create workspace  as "Workspace1"
3. Create another Workspace as "Workspace2"
4. Add a service, say "Custom Website" to Workspace1 and Workspace2
5. Open the service from Workspace1 and login into the account (related to service)
6. Switch Workspaces. (to Workspace2) 
7. You are still logged in

### Context
When I switched the Workspaces, a new Instance of the service should be opened where I should be able to login to another account of the same service. I tested this on *Whatsapp Web* and *mail.zoho.com*

### Your Environment
* Ferdi Version used:  5.4.0 (x64)
* Platform: win32
* Operating System and version: Windows 10 Professional

**Comment by vantezzen** [comment]
This is not how workspaces work. If you want to be able to use different sessions on the same site you'll have to add the service multiple times.
Workspaces are simply a way to organise your services and only show those you are currently using: For example when you are at work you want to show different services from when you are at home.

**Comment by ashutoshpw** [comment]
Is there any service that works in the way that I expect?
I have tried Franz, Ferdi, gestation, Rambox, etc.

But none of them worked.
Although Rambox worked that is high memory intensive and there is no hibernation.

**Comment by vantezzen** [comment]
If you want to use Ferdi in this way, simple add the same service multiple times and add different instances of the service to different workspaces. I think all other messaging browsers handle workspaces in this way.

**Comment by ashutoshpw** [comment]
I haven't found the concept of Workspaces in several other apps. I was looking for a solution where I could create workspaces as "Home" and "Work". In one I will check personal email and in another, I will only check work-related emails. 

Well, I am closing this issue now as I misunderstood the concept of workspaces. I thought it will work in that way as when I switched workspaces, I saw a toast with the message "Switching Workspaces"

If anyone is reading this and want the desired results as of mine, please do upvote this comment. I will try to fork this and make this feature available in the fork.
