### ISSUE TITLE
Fullscreen mode issue when watching videos

### ISSUE THREAD

**Issue by 4ifi** [getferdi/ferdi#314]
F11 fullscreen mode terribly works! So it's impossible to watch youtube videos in fullscreen.
OS: windows 10 ltsc 1809
Love your app :)
Thank you for your work!

**Comment by catarino** [comment]
Not sure if applicable here but:

As of 5.5.0, fullscreen is not working on startup. 

Now everytime you startup, the app goes back to default window screen size. Not fullscreen as expected if you had last time you closed the app.

It worked as expected in 5.4.3

**Comment by kytwb** [comment]
@catarino issue should be fixed thanks to @dannyqiu via #733 🙏 Keeping open as the original issue seems to be regarding fullscreen mode when watching videos.

**Comment by catarino** [comment]
@kytwb Great thx!

**Comment by mhatvan** [comment]
Verified that F11 full screen mode is retained after restarting the application.
