### ISSUE TITLE
Quick switch does not get focus

### ISSUE THREAD

**Issue by dansdantas** [getferdi/ferdi#322]
**Describe the bug**
After opening quick switch window, does not get focus on input.

**To Reproduce**

1. Activate quick switch CTRL+S
2. See error

**Expected behavior**
Input field should get focus, so can change service by typing and hitting enter.

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version: 5.4.0(x64)
- Electron: 6.0.0
- Node.js: v12.4.0

**Additional context**
Installed from aur `ferdi-bin`. I use a window manager `i3-gaps`.

**Comment by vantezzen** [comment]
This is a known bug which we unfortunately cannot fix: Electron does not allow Ferdi to focus the box if the focus is currently inside a webview.

Related:
https://github.com/getferdi/ferdi/issues/68#issuecomment-534146281
https://github.com/getferdi/ferdi/blob/1fea645b0b94e52a31158d47d0ad921110dfa95e/src/features/quickSwitch/Component.js#L232-L235
