### ISSUE TITLE
Ferdi distribution as flatpak on flathub

### ISSUE THREAD

**Issue by lhw** [getferdi/ferdi#323]
**Is your feature request related to a problem? Please describe.**
Distributing Ferdi as flatpak on the official flathub in addition to the current versions.

**Describe the solution you'd like**
I already have it up and running and would submit the pull request from https://github.com/lhw/flathub/tree/ferdi but I wanted your input first in case its already on your agenda.

**Comment by vantezzen** [comment]
Sound great - it wasn't on our agenda yet.
But it looks like your "com.getferdi.Ferdi.appdata.xml" isn't completely up-to-date yet: Could you please update the author to the "Ferdi Team" and update the description to the one on GitHub? Other than that, thank you for putting work into Ferdi!

Is there anything that we'll have to do on our side?

**Comment by vantezzen** [comment]
@all-contributors please add lhw for platform

**Comment by lhw** [comment]
@vantezzen Thats pretty much it actually. Maintaining the flatpak ist relatively simple. Do you have a link for a screenshot somewhere I could embed? I currently still link the [Franz](https://meetfranz.com/static/images/franz-screenshot.png) one. Looks something like this: https://flathub.org/apps/details/com.meetfranz.Franz

**Comment by vantezzen** [comment]
As a screenshot I would use "https://raw.githubusercontent.com/getferdi/ferdi/develop/branding/screenshots/hero.png" or any other screenshot inside Ferdi's [screenshot folder](https://github.com/getferdi/ferdi/tree/develop/branding/screenshots).

**Comment by lhw** [comment]
The merge into flathub is now tracked here: https://github.com/flathub/flathub/pull/1346

**Comment by lhw** [comment]
One of the suggestions from flathub was that the metainfo/appdata.xml ([this file](https://github.com/flathub/flathub/blob/4b01b872869db237d9b86a9444e643be624a961f/com.getferdi.Ferdi.metainfo.xml)) is integrated with the upstream project. It should be distributed in the path `/usr/share/metainfo/com.getferdi.Ferdi.metainfo.xml`.

I generally don't know how this project is build for distribution otherwise I would simply open a pull request. If you can give me an inkling I could do the PR.

**Comment by vantezzen** [comment]
What should Ferdi do with this file? Should it copy it there during installation?

**Comment by lhw** [comment]
Yes. Ferdi just needs to supply the file at the path after installation. You can read more about it here https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
But basically its just a small file with metadata file for desktop applications. Standard freedesktop stuff.

**Comment by vantezzen** [comment]
Ferdi uses electron and [electron-builder](https://github.com/electron-userland/electron-builder) to build its application. It looks like electron-builder doesn't have this feature build-in (https://github.com/electron-userland/electron-builder/issues/1993) but you may be able to add this via the [extraFiles](https://www.electron.build/configuration/contents.html#extrafiles) option. Ferdi's build config is inside [electron-builder.yml](https://github.com/getferdi/ferdi/blob/develop/electron-builder.yml)

**Comment by lhw** [comment]
Alright i'll check it out and get back to you.

**Comment by lhw** [comment]
I did check on it and the doubled changelog is annoying. I think we can skip this part and I'll just include it in the flatpak distribution until the electron support is available.

**Comment by lhw** [comment]
I think you were also mentioned on the merge request but just in case https://flathub.org/apps/details/com.getferdi.Ferdi and https://github.com/flathub/com.getferdi.Ferdi @vantezzen

**Comment by vantezzen** [comment]
Thanks, already saw the message in the PR. Do you know what we'll have to do when Ferdi updates? Simply update the info in the repo you linked?

**Comment by lhw** [comment]
So basically for now, unless we want to change to a source build, we just have to update the deb file link and sha256sum and as soon as it is checked in it will update for everyone after the build server run. But that should be done via PR into the repo that automatically creates a test build we can try out beforehand.
