### ISSUE TITLE
white edges on dropdown menus

### ISSUE THREAD

**Issue by Stanzilla** [getferdi/ferdi#325]
**Describe the bug**
Dropdown menus have a white edge on the bottom left

**To Reproduce**
1. Open a menu

**Expected behavior**
Dark border edge

**Screenshots**

https://i.imgur.com/jRgzUtE.png

![image](https://user-images.githubusercontent.com/75278/55431056-d7c1d700-558f-11e9-91b2-1fdfc4e091cd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Franz/Ferdi: 5.4.1-beta4

**Comment by Stanzilla** [comment]
Still an issue

**Comment by Stanzilla** [comment]
Still an issue

**Comment by Stanzilla** [comment]
Still an issue

**Comment by Stanzilla** [comment]
Still an issue

**Comment by Stanzilla** [comment]
still relevant

**Comment by mhatvan** [comment]
Cannot reproduce this with v5.6.1-nightly.48 in either dark or light mode on any dropdown menu in Ferdi.

This was probably fixed upstream in newer versions of electron in the mean time.

**Comment by Stanzilla** [comment]
> Cannot reproduce this with v5.6.1-nightly.48 in either dark or light mode on any dropdown menu in Ferdi.
> 
> This was probably fixed upstream in newer versions of electron in the mean time.

Can confirm fixed in 5.6.1-beta3 as well.
