### ISSUE TITLE
macOS: Window preview is blank in macOS Control

### ISSUE THREAD

**Issue by briankendall** [getferdi/ferdi#333]
**Describe the bug**
When entering Mission Control in macOS 10.14.6 or later, the preview of Ferdi will be blank if it is on a different desktop.

**To Reproduce**

1. Run Ferdi 5.4.3 in macOS 10.14.6 or later
2. Click the green 'zoom' button in the upper left corner of Ferdi's window to make it full screen
3. Enter Mission Control
4. Note the preview of Ferdi in Mission Control is totally blank

**Expected behavior**
The preview of Ferdi would not be blank and contain an up-to-date view of the window

**Additional context**
[This is apparently a bug with Electron 7.](https://github.com/electron/electron/issues/19430) That bug report goes into more detail with the issue and includes screenshots.

I doubt there's anything that can be done on Ferdi's end of things until Electron fixes the bug, at which point hopefully updating Electron will fix it.

edit: I plan to stick with Ferdi 5.4.0 for the time being until the bug is fixed, since it's built using Electron 6 and doesn't have this issue.

**Comment by vantezzen** [comment]
I can reproduce this bug but as you said yourself this is nothing we can fix ourselves.

**Comment by kytwb** [comment]
This fixed itself when we upgraded to Electron 8 in [v5.4.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.2):

<img width="380" alt="Screen Shot 2020-03-02 at 6 50 21 PM" src="https://user-images.githubusercontent.com/412895/75702938-bfce6800-5cb6-11ea-8003-8e50708ebaaa.png">

**Comment by briankendall** [comment]
I can confirm it's fixed in v5.4.4-beta 2.
