### ISSUE TITLE
recipes/dev folder not created automatically upon first launch

### ISSUE THREAD

**Issue by reischlfranz** [getferdi/ferdi#339]
**Describe the bug**
Settings -> Available Services -> Custom Services -> Custom 3rd Party Recipes, Open Folder:
(Sub-)Folder "dev" is the path listed in the text field automatically, but clicking on "Open Folder" leads to an error since the folder does not exist.

**To Reproduce**
* Delete or rename the Ferdi/recipes/dev folder and click on above mentioned button

**Expected behavior**
Folder is opened in file manager/Explorer; If not exist, the folder should be created

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Win10 Pro x64
- Version 5.4.3

**Additional context**
N/A

**Comment by vantezzen** [comment]
Can reproduce this bug. I just added your described functionality - this will be fixed with Ferdi 5.3.4-beta.2
