### ISSUE TITLE
Add feature: Signal app

### ISSUE THREAD

**Issue by fcojgodoy** [getferdi/ferdi#342]
https://signal.org/

**Comment by vantezzen** [comment]
Signal cannot be added as it does not have a web client.

Related:
getferdi/recipes#26
getferdi/recipes#22
getferdi/recipes#21
getferdi/recipes#18
meetfranz/franz#1702
meetfranz/franz#767
meetfranz/franz#655

**Comment by dutscher** [comment]
but there is a signal chrome extension which is written in js.
https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk?hl=de

**Comment by vantezzen** [comment]
> but see https://github.com/signalapp/Signal-Desktop

The Signal Desktop app implements a lot of additional logic and is not a normal website that we can add to Ferdi. We would have to write our own Signal service in order for it to work with Ferdi's APIs and capabilities.
