### ISSUE TITLE
Can not enable Dark Mode in Ferdi v5.4.4-beta.1 on Windows 10

### ISSUE THREAD

**Issue by awunder** [getferdi/ferdi#347]
complete new w10 and ferdi installation and i can not enable dark mode.. the button is just disabled..

i can however toggle the universal dark mode though that doesnt seem to do anything

### Your Environment

* Ferdi Version used: 5.4.4 B1
* Operating System and version: W10

**Comment by kytwb** [comment]
Regression introduced via https://github.com/getferdi/ferdi/commit/eefda6c7b3e9f0e9b0cfc056efbf59d04a54be85 at https://github.com/getferdi/ferdi/blob/dcc05d2e9e066ce0a64425b9b2c7772bf2add3aa/src/components/settings/settings/EditSettingsForm.js#L453

**Comment by vantezzen** [comment]
Removed the `disabled={isAdaptableDarkModeEnabled}` via 374b5219 which should fix this issue but not change the behaviour on macOS.

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.2).
