### ISSUE TITLE
Signing and notarisation on Mac

### ISSUE THREAD

**Issue by vantezzen** [getferdi/ferdi#35]
Currently, when first opening a Ferdi build on MacOS, you'll get this error:
![Screenshot](https://user-images.githubusercontent.com/10333196/64905835-fe0ea580-d6dd-11e9-969e-1941274f12af.png)
This is because Ferdi is not signed using an Apple Developer ID. The only way to open Ferdi is to use `ctrl`-click > "Open".

From MacOS Catalina onwards, you'll also get this error because Ferdi isn't notarised either:
![Screenshot](https://kilianvalkhof.com/wp-content/uploads/58382976-69b6f080-7fd1-11e9-845e-5587dd500702.png)

These two warnings will probably scare off new users switching from Franz, as they might think Ferdi is a virus.

The problem is, that we would need an Apple Developer ID to sign and notarise Ferdi, costing 100$ per year.

Are there any suggestions on how one could solve this problem? Any Developer IDs we could use?

**Comment by kytwb** [comment]
I don't have a Developer ID at the moment, but I could sort that out.

**Comment by shenwalter** [comment]
Hi, to circumvent that issue you want to right click on Ferdi, and then in the menu click run.
![image](https://user-images.githubusercontent.com/24768371/64933597-0537cf80-d814-11e9-8a31-81b96d49292a.png)
That should solve the issue!

**Comment by vantezzen** [comment]
@shenwalter Thank you for your comment. I also mentioned this "trick" in my original comment, but I don't think this will work as a permanent solution:

This will work for all experienced users, but unexperienced users will not know this "trick" - especially because Franz is signed, meaning they don't need to use the trick there - and also probably won't search for this trick as they will think Ferdi (not having a button to open by default) might be a virus or could harm their computer.

**Comment by kytwb** [comment]
I have the Apple Developer Program membership sorted; will take a look at the next steps soon.

**Comment by kytwb** [comment]
Related: https://github.com/kytwb/ferdi/blob/f5b266719d90639b673c0e0344144f8c443f7378/gulpfile.babel.js#L181

**Comment by kytwb** [comment]
Related: https://www.jviotti.com/2016/03/16/how-to-code-sign-os-x-electron-apps-in-travis-ci.html

**Comment by kytwb** [comment]
Will follow https://github.com/electron/electron-osx-sign/wiki/1.-Getting-Started#create-your-certificates to generate certificates; then refer to https://www.electron.build/code-signing as we use `electron-builder` for the build command.

Still waiting on the membership to activate to be able to generate the certificates:

> Your purchase may take up to 48 hours to process.

**Comment by vantezzen** [comment]
Also related: https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

**Comment by kytwb** [comment]
```
  • electron-builder version=20.43.0
  • loaded configuration file=/Users/kytwb/Downloads/Side Projects/ferdi/electron-builder.yml
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config file=out/builder-effective-config.yaml
  • installing production dependencies platform=darwin arch=x64 appDir=/Users/kytwb/Downloads/Side Projects/ferdi/build
  • packaging       platform=darwin arch=x64 electron=4.2.4 appOutDir=out/mac
  • signing         file=out/mac/Ferdi.app identityName=Developer ID Application: Amine Mouafik (B6J9X9DWFL) identityHash=0DB37648852C073A6B47DE14AD8B9F686D840B4D provisioningProfile=none
  • building        target=macOS zip arch=x64 file=out/Ferdi-5.3.3-mac.zip
  • building        target=DMG arch=x64 file=out/Ferdi-5.3.3.dmg
(node:45614) Warning: a promise was created in a handler at /Users/kytwb/Downloads/Side Projects/ferdi/node_modules/app-builder-lib/src/macPackager.ts:91:26 but was not returned from it, see http://goo.gl/rRqMUw
    at /Users/kytwb/Downloads/Side Projects/ferdi/node_modules/bluebird/js/release/generators.js:197:21
  • building block map blockMapFile=out/Ferdi-5.3.3.dmg.blockmap
  • building embedded block map file=out/Ferdi-5.3.3-mac.zip
```

Looking at making signing work in Travis next.

**Comment by kytwb** [comment]
Added to https://travis-ci.org/kytwb/ferdi/settings

![Screen Shot 2019-09-19 at 12 41 45 PM](https://user-images.githubusercontent.com/412895/65217199-8bd30200-dadd-11e9-8752-148e92ec52e9.png)

As per https://www.electron.build/code-signing#travis-appveyor-and-other-ci-servers.

**Comment by kytwb** [comment]
Also added the env variables used in `build-helpers/notarize.js` (see https://github.com/kytwb/ferdi/pull/52/commits/96bf053ac6cb90a8bfb87fd89ffe866e9cbf015f):

![Screen Shot 2019-09-19 at 1 21 40 PM](https://user-images.githubusercontent.com/412895/65218451-af4b7c00-dae0-11e9-912c-538ef0067280.png)

**Comment by kytwb** [comment]
Email received after https://travis-ci.org/kytwb/ferdi/jobs/586865267 succeeded:

![Screen Shot 2019-09-19 at 2 02 30 PM](https://user-images.githubusercontent.com/412895/65221112-7f9f7280-dae6-11e9-9a28-5114f8b9f371.png)

**Comment by kytwb** [comment]
@all-contributors add @vantezzen for example

**Comment by vantezzen** [comment]
@kytwb Could you also remove meetfranz.com as the project URL from GitHub?
![Screenshot](https://user-images.githubusercontent.com/10333196/65230646-815d3c00-dace-11e9-8405-f767ec5c5f00.png)
I think it is not fitting to link the fork origin project as the project URL, I would just keep it blank.

**Comment by kytwb** [comment]
@vantezzen done 👍

**Comment by vantezzen** [comment]
> Still waiting on the membership to activate to be able to generate the certificates:
> 
> > Your purchase may take up to 48 hours to process.

@kytwb Can you add this expense to opencollective?

**Comment by kytwb** [comment]
@vantezzen done.
