### ISSUE TITLE
U2F Support

### ISSUE THREAD

**Issue by Hakujou** [getferdi/ferdi#351]
**Is your feature request related to a problem? Please describe.**
Ferdi doesn't seem to handle U2F authentication devices. It can cause issues, eg. when using Gmail in strict security mode, which requires U2F as a second factor (and doesn't allow any other 2FA method).

**Describe the solution you'd like**
U2F support in Ferdi.

Please let me know if you need more information.

**Comment by vantezzen** [comment]
Do you mean USB U2F authentication? Ferdi should handle this just fine - I just verified this again.
What OS and Ferdi version are you on?

**Comment by Hakujou** [comment]
Hello,

Thanks for your fast answer!
yes I mean USB U2F token (from Feitian).

I'm using Ferdi v5.4.3.994 on MacOS 10.15.2. To be honest, I only assumed U2F was broken because it was a little while ago on Franz, and I'm now receiving a message when trying to login on Gmail:
"This browser or this application might not be secure.
Try to use an other browser. If you use a compatible browser, you can try to refresh and try to login again" (this is a very rough translation, as this error is actually in French since it's my mother tongue).

It might not be related to U2F after all, maybe Gmail is enforcing some browser checks when using strict security mode ?

**Comment by vantezzen** [comment]
Yes, that is a problem with new checks by Google - you'll have to update to 5.4.4-beta.1 where this problem is already fixed

**Comment by Hakujou** [comment]
Just tried 5.4.4-beta1, the message is still there.
