### ISSUE TITLE
Login with GMAIL doesn't work

### ISSUE THREAD

**Issue by ragusa87** [getferdi/ferdi#352]
**Describe the bug**
I try to login into the Gmail service, but the browser is not supported
**To Reproduce**

1. Go to 'Add a new Service'
2. Click on 'Gmail'
2. I Click on "Save service"
3. I Click on "X" to close the setting window
4. I Click on the "Gmail" service
3. I enter my Google Account email
4. I click on "Next"
5. I enter my password
6. I click on "Next"
7. I See an error message with the Title "Couldn't sign you in"

**Expected behavior**
I expect to see the main Gmail interface instead of the unsupported browser page.

**Screenshots**
![Screenshot from 2020-02-05 18-05-22](https://user-images.githubusercontent.com/1695207/73864589-3e63f100-4842-11ea-987d-c6ec9a4797fa.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.4 LTS // Linux 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Gmail plugin version: 1.2.1
- Version: Ferdi 5.4.3 (x64), Electron 7.1.6, Node.js v12.8.1, on linux

**Additional context**
The page seems to be : https://support.google.com/accounts/answer/7675428?hl=en

I was able to login with my professional account (2 factor auth is on).
I added the Gmail service one more time for my private account, the private one doesn't work (2 factor auth is on).

**Comment by ragusa87** [comment]
Please note that I am using Ferdi without an account, and that after clearing Ferdi's cache and starting over, the problem is still here.

**Comment by vantezzen** [comment]
Please update to the newest Beta version of Ferdi - this problem should already be fixed there.
