### ISSUE TITLE
Disable disk cache

### ISSUE THREAD

**Issue by eadmaster** [getferdi/ferdi#353]
Is there an  option to disable the browser disk cache? ( like `--disk-cache-dir=/dev/null --disk-cache-size=1 --disable-gpu-shader-disk-cache` for chrome)

I'd like to move or disable the cache for use with an SSD.

**Comment by vantezzen** [comment]
Packaged Electron applications (as far as I can tell) don't support changing cache behaviour. The only way you could disable caching is by [running Ferdi from source](https://github.com/getferdi/ferdi#development) and starting it via `npm start --disable-http-cache` or any other Electron argument you want to use.
