### ISSUE TITLE
Are you thinking of integrating Asana? 

### ISSUE THREAD

**Issue by KrisBataican** [getferdi/ferdi#355]
Hey just got here, and i'm really happy that you have integrated Instagram, been waiting for it for so long time on franz, but it never happend.  

Just wondering if you have any plans on integrating Asana? I can see that Trello is there like in Franz, but would be great if Asana could be integrated as well. 

My Best Regards Krisbataican.

**Comment by vantezzen** [comment]
Please request new services at https://github.com/getferdi/recipes/issues/new?assignees=&labels=recipe+request&template=recipe_request.md&title=%5BRecipe+Request%5D+SERVICE

**Comment by kytwb** [comment]
@KrisBataican you could try using a Custom Website service:

<img width="671" alt="Screen Shot 2020-02-11 at 1 58 15 AM" src="https://user-images.githubusercontent.com/412895/74204079-090c3880-4c72-11ea-985b-9becd7fd1b3f.png">

Or make a recipe request as suggested by @vantezzen 🙏
