### ISSUE TITLE
Google Voice flickering with Dark Mode

### ISSUE THREAD

**Issue by ylluminate** [getferdi/ferdi#358]
Just wanted to call this out since it may be easier to track and test this way, please see: 
https://github.com/getferdi/ferdi/issues/158#issuecomment-582581458

![example](https://camo.githubusercontent.com/b95138900bdb883b83dbf4c305105dc6dad32278/68747470733a2f2f703135332e70302e6e302e63646e2e676574636c6f75646170702e636f6d2f6974656d732f503875594c375a472f646973617070656172696e675f676f6f676c655f766f6963652e676966)

**Comment by kytwb** [comment]
Maybe related to https://github.com/darkreader/darkreader/issues/790.

**Comment by ylluminate** [comment]
This flickering seems to be resolved in the most recent release.

**Comment by ylluminate** [comment]
I spoke too soon, it doesn't seem as serious, but it is still happening.  When I load a voice message it starts up again, but in an unreliable fashion.

There are also some other problems here with this that probably should be incorporated under a general Dark Mode problem with Google Voice:

• When I load voice messages, they go invisible: 
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/12u1ogkZ/example.png)

• Search text is black:
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/X6uz9EXp/black.png)

• On a 2nd Google Voice service I have, it won't even load messages, even after I "Reload" the service (**Reload simply doesn't seem to function**):
[gif screencast](https://p153.p0.n0.cdn.getcloudapp.com/items/v1urNg89/Screen+Recording+2020-03-05+at+11.36+AM.gif?v=590027f74433623d6392a1246f2a2393)
