### ISSUE TITLE
Touch ID support in lock feature

### ISSUE THREAD

**Issue by aleksabobic** [getferdi/ferdi#367]
**Is your feature request related to a problem? Please describe.**
As someone who values there privacy I would like Ferdi to support touch ID.

**Describe the solution you'd like**
When setting a password for Ferdi I would like to have an option to unlock with touch ID and not just a password. This option should  appear or be enabled on Mac systems.

**Comment by vantezzen** [comment]
Adding this feature via #423.
Unfortunately, I do not have access to a Mac with Touch ID so I can't really test this.
Would you be able to run Ferdi from source to test this feature with actual TouchID? MacOS seems to prompt for the normal user password on Macs without TouchID so the feature should already be mostly tested.

**Comment by vraravam** [comment]
I'm very excited about this feature - but, i don't know how to run ferdi from the source. I have a MBP with touch bar - so if someone could please point me to instructions on how I can run from the source - I can try to verify this PR.

**Comment by kytwb** [comment]
@vraravam You should be able to run Ferdi from the sources by following the development setup instructions in the README file.

**Comment by vantezzen** [comment]
> You should be able to run Ferdi from the sources by following the development setup instructions in the README file

Also, we'll release a new beta in the few days so unless you want it before then, there is no real need to run form source.

**Comment by kytwb** [comment]
I'll be for @vraravam to give it a try still if he is keen 😄 We can't have enough people with the development setup running and ready to contribute. The next beta should be released by my end of day (11am here).

**Comment by vraravam** [comment]
I agree with @kytwb 's last comment. Let me try to get it setup tonight (its around 6 pm here in India right now). If successful, at least it'll let me test in the future without having to wait for beta releases ;)

No guarantees - since I'm not a node/js dev.

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.3).
