### ISSUE TITLE
Electron 8 build not working

### ISSUE THREAD

**Issue by AGCaesar** [getferdi/ferdi#369]
Electron got updated to version 8 and the bulid is broken again :/

**Comment by vantezzen** [comment]
What error messages are you getting?

**Comment by AGCaesar** [comment]
It starts fine, but then shows nothing.
The developer tools say:
![20200213154558_window](https://user-images.githubusercontent.com/7844066/74446362-0f6c0180-4e78-11ea-9cbc-da3ac880a6ff.png)

**Comment by sergiughf** [comment]
Same thing happening for me too. :cry:

**Comment by dpeukert** [comment]
@AGCaesar This can be fixed by patching the `package.json` with the system electron version in the PKGBUILD like the official Electron packages in the repos do: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/signal-desktop#n42

**Comment by AGCaesar** [comment]
@dpeukert tanks for adopting the packages. I really do not understand this electron packaging and it gave me headaches...

**Comment by dpeukert** [comment]
@AGCaesar No worries, electron packaging is a bit of a mess. I've gone through the packages so everything should be working now.

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.2).
