### ISSUE TITLE
emoji shortcut / copy pasting / other shortcuts  not working on mac

### ISSUE THREAD

**Issue by aleksabobic** [getferdi/ferdi#377]
**Describe the bug**
When pressing "control + command + space" or "command + v" I do not get the emoji popup or paste data which I copied before. Additionally pressing "command + a" does not select all my text.

**To Reproduce**
Pressing "control + command + space" -> nothing happens. 
Copy text from somewhere else. Press "command + v" -> nothing happens. 
Write some text in input field. Press "control + a" -> nothing happens.

**Expected behavior**
When pressing "control + command + space" I expect the standard emoji popup as seen on Franz. 
When pressing "command + v" I expect my data to be pasted into the chat window as in Franz. 
Pressing "control + a" should result in my text in the input field being selected. 

**Desktop (please complete the following information):**

- OS: macOS Catalina 
- Ferdi Version 5.4.3
- Server Used: https://api.getferdi.com

**Comment by kytwb** [comment]
Thanks for reporting the issue @aleksabobic, we will look into it via https://github.com/getferdi/ferdi/issues/377. Feel free to subscribe to that issue to receive updates!

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.2).

**Comment by fuzzy76** [comment]
Emoji pallette doesn't work in v5.5.0? control-command-space does nothing.

**Comment by fuzzy76** [comment]
Created a new issue for the missing functionality -> #1178
