### ISSUE TITLE
Can't add any service after install on Windows, CORS error

### ISSUE THREAD

**Issue by luckydonald** [getferdi/ferdi#381]
**Describe the bug**

**To Reproduce**

1. Download app
2. Run installer
3. Say no server
4. choose any service
5. click add service with or without entering details.
```
Response {type: "cors", url: "http://127.0.0.1:45569/v1/service", redirected: false, status: 500, ok: false, …}
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2737108/74595564-59551300-5043-11ea-9e76-237534b2716c.png)

**Desktop (please complete the following information):**

- OS: Windows 10 etc.
- Ferdi Version 5.4.3 and 5.4.4-beta1

- Server Used: without

**Additional context**

**Comment by luckydonald** [comment]
Mac version runs fine though

**Comment by dhuffer** [comment]
I ran into the same error.
After an uninstall and a wipe of the user folder C:\Users\%username%\AppData\Roaming\Ferdi\ and a second install it works. During the install a red alert appeared, but I was'nt able to read it properly before it disappeared again. Ferdi is still working though.

**Comment by luckydonald** [comment]
Couldn't make it to work that way. Stable 5.4.3 @dhuffer?

**Comment by dhuffer** [comment]
5.4.4-beta1

**Comment by luckydonald** [comment]
Oh my indeed the beta works

**Comment by dhuffer** [comment]
Today it stopped working again. All services are gone and I can't add any 😢

**Comment by kytwb** [comment]
@luckydonald @dhuffer thank you for reporting the issue; it seems to be a duplicate of https://github.com/getferdi/ferdi/issues/253, which origins in the internal server used for using Ferdi without an account. It's being worked on at https://github.com/getferdi/internal-server/issues/2. In the meantime, please try using Ferdi with an account. Thanks for bearing with us! 🙏

**Comment by luckydonald** [comment]
@kytwb workaround above does the job without server!

**Comment by pczora** [comment]
Another workaround: Right click on `server.sqlite` in `C:\Users\$USER_NAME\AppData\Roaming\Ferdi`, click 'Properties', uncheck 'Read-only', restart Ferdi. Done.
