### ISSUE TITLE
Ensure all native modules are NAPI or Context Aware

### ISSUE THREAD

**Issue by dpeukert** [getferdi/ferdi#385]
By Electron 11.x, all native modules will have to be NAPI or Context Aware (more info [here](https://github.com/electron/electron/issues/18397)). Every incompatible module has to be updated or replaced with a compatible alternative. Below is the list of native modules we use:

- [ ] [@felixrieseberg/spellchecker](https://github.com/felixrieseberg/node-spellchecker)
    - state - open PR - felixrieseberg/node-spellchecker#4
    - reason - dependency of [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker) (which might not be required if we switch to the native spellchecker implementation in Electron 8)
- [ ] [sqlite3](https://github.com/mapbox/node-sqlite3)
    - state - merged - mapbox/node-sqlite3@34d6283, [released](https://github.com/mapbox/node-sqlite3/releases/tag/v5.0.0)
    - reason - direct dependency
- [ ] [windows-notification-state](https://github.com/felixrieseberg/windows-notification-state)
    - state - unknown
    - reason - dependency of [@meetfranz/electron-notification-state](https://github.com/felixrieseberg/electron-notification-state)
- [ ] [windows-quiet-hours](https://github.com/felixrieseberg/windows-quiet-hours)
    - state - merged - felixrieseberg/windows-quiet-hours@400a5f4, defined dependency version in [@meetfranz/electron-notification-state](https://github.com/felixrieseberg/electron-notification-state) **DOES NOT MATCH** the compatible version
    - reason - dependency of [@meetfranz/electron-notification-state](https://github.com/felixrieseberg/electron-notification-state)
- [x] [macos-notification-state](https://github.com/felixrieseberg/macos-notification-state)
    - state - merged - felixrieseberg/macos-notification-state#6, defined dependency version in [@meetfranz/electron-notification-state](https://github.com/felixrieseberg/electron-notification-state) matches the compatible version
    - reason - dependency of [@meetfranz/electron-notification-state](https://github.com/felixrieseberg/electron-notification-state)
- [x] [cld](https://github.com/dachev/node-cld)
    - state - merged - dachev/node-cld#60, defined dependency version in [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker) matches the compatible version
    - reason - dependency of [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker)
- [x] [keyboard-layout](https://github.com/atom/keyboard-layout)
    - state - merged - atom/keyboard-layout#51, defined dependency version in [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker) matches the compatible version
    - reason - dependency of [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker)

**Comment by vantezzen** [comment]
Do you know what we have to do to make modules context aware? Is this something we have to do on our side or something the package creator has to do?

**Comment by dpeukert** [comment]
AFAIK it is something the package creator has to do.
