### ISSUE TITLE
Minimise on tray icon click

### ISSUE THREAD

**Issue by m-vlad** [getferdi/ferdi#388]
**Is your feature request related to a problem? Please describe.**
I'm currently using Mailspring and it's so nice when I can minimise it to tray by just clicking the icon tray. It saves me the time to click minimize/exit from the title bar or the taskbar.

**Describe the solution you'd like**
Make the click on the tray icon minimize the app back.

**Describe alternatives you've considered**
> It saves me the time to click minimize/exit from the title bar or the taskbar.

**Comment by kytwb** [comment]
Closing in favor of https://github.com/getferdi/ferdi/issues/307 and adding your suggestion there 🙏 Thank you!
