### ISSUE TITLE
Use of password managers inside Ferdi

### ISSUE THREAD

**Issue by teamtmedia** [getferdi/ferdi#394]
Loving Ferdi.  Only gripe I have is not being able to use a password manager in Ferdi.  I have a number of encrypted email accounts that I would like to use in Ferdi.  It is a pain having to launch my password manager (Dashlane, in this instance) and copy/paste my password in every time I open up Ferdi.  Naturally encrypted email accounts do not, as a security measure, allow pervasive logins.

Dashlane, as an example, provides addons for most browsers.  Is there a way to slip them into the browser instance in the recipes via index.js?  If not what are the other methods we could use?

**Comment by vantezzen** [comment]
Feature requested in #113.

There is currently no way to use password managers or other browser extensions in Ferdi. You can however edit the recipe `webview.js` (location of the recipes varies per OS, `%appdata$/Ferdi/recipes` on Windows, `~/Library/Application Support/Ferdi/recipes` on macOS and `~/.config/Ferdi/recipes` on Linux) and add a script that inserts your credentials. Please note that the `webview.js` will get executed before the DOM is fully loaded so you'll have to add a listener for that.

**Comment by kytwb** [comment]
@teamtmedia Thanks for your feedback!
As @vantezzen mentioned, we already have a feature request regarding extension support (for case like yours and others). We will close this ticket for now and keep the other ticket updated when anybody starts to work on it.

**Comment by teamtmedia** [comment]
Thanks guys.  Shall follow the other thread.
