### ISSUE TITLE
Can't Connect To Ferdi Online Services

### ISSUE THREAD

**Issue by agamerj** [getferdi/ferdi#396]
**Describe the bug**

**To Reproduce**

1. Start Ferdi (with or without Administrator Permissions)
2. Login
3. Create Free Account

**Expected behavior**

It will show the error: Can't Connect To Ferdi Online Services

**Screenshots**

![sx-22-February-20-3080](https://user-images.githubusercontent.com/9323342/75092683-404ae580-55a0-11ea-8516-ffb68a17842a.png)

**Desktop:**

- OS: Windows 8.1
- Ferdi Version: 5.4.3

- Server Used: https://api.getferdi.com

Debug information: https://pastebin.com/raw/fN78tLSn

**Additional context**

**Comment by agamerj** [comment]
It seems like something is wrong with the current version itself and I downloaded the 5.3.3 version after uninstalling the latest one and it's working.

**Comment by vantezzen** [comment]
As you already mentioned this is a problem with Ferdi 5.4.x on Windows. We now changed the download link to 5.3.3 for Windows on https://getferdi.com so new users shouldn't experience this problem any longer for now.

**Comment by agamerj** [comment]
I think this software should adopt BETA now. What I mean to say is that, new releases should pass the BETA first and then go to the live-build.

Because, right now seeing that "Update" button all the time is kind of annoying.

**Comment by vantezzen** [comment]
Ferdi already uses betas and only releases a new version every 1-2 months (see releases at https://github.com/getferdi/ferdi/releases). You are probably experiencing a bug in Ferdi's updater, could you send a screenshot of the message you are getting?

**Comment by dbogdanov** [comment]
Same issue for me on 5.6.0-beta.2.

**Comment by mnaufalhilmym** [comment]
Same issue on ferdi 5.5.0 (installed from flatpak) on my openSUSE Tumbleweed. I tested it on my VM with another OS and works fine. On `flatpak run com.getferdi.Ferdi`, it shows:
```
info: serving app on http://localhost.localdomain:45569
Error: listen EADDRNOTAVAIL: address not available 36.86.63.182:45569
    at Server.setupListenHandle [as _listen2] (net.js:1283:19)
    at listenInCluster (net.js:1348:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1487:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10) {
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '36.86.63.182',
  port: 45569
}
```
How to resolve this issue? Thanks.

**Comment by vraravam** [comment]
@mnaufalhilmym - could you please try with the latest nightlies found [here](https://github.com/getferdi/nightlies/releases)? IF this is still a bug, we can investigate a fix.

**Comment by mnaufalhilmym** [comment]
@vraravam Thanks for your reply. I just fixed it by changing my computer's static hostname in /etc/hostname and /etc/hosts.

**Comment by bundyo** [comment]
Seems localhost in /etc/hosts is the problem. If specified like this:

```
127.0.0.1     localhost
```

Ferdi refuses to connect. If static hostname is also added:

```
127.0.0.1     localhost hostname
```

Ferdi works. Not a problem with any other software with this, looks like a bug to me.

**Comment by vraravam** [comment]
Just putting this here for reference: #1744 should have fixed this issue - which was merged and released in a nightly a long time ago. As of earlier this morning, we just released the latest beta.
