### ISSUE TITLE
Reduce Width of the Sidebar & Telegram Issue

### ISSUE THREAD

**Issue by agamerj** [getferdi/ferdi#397]
Note: I have removed the default text so that I could mention my feature request as this is not a bug. (I have shared two issues in this thread)

**1. How to reduce the width of the Sidebar?**

Because, it is taking a lot of space in the side.

![sx-22-February-20-3082](https://user-images.githubusercontent.com/9323342/75093126-10eaa780-55a5-11ea-879e-d622948c1f9c.png)

**2. Telegram is not aligned as it should be.**

This is how it comes in the Ferdi or Franz.

![sx-22-February-20-3083](https://user-images.githubusercontent.com/9323342/75093142-3e375580-55a5-11ea-9a7a-b9d2b8487978.png)

This is how it comes in other alternative (tryshift) or Chrome Browser itself.

![sx-22-February-20-3084](https://user-images.githubusercontent.com/9323342/75093154-560ed980-55a5-11ea-97f5-c3b4e16253f8.png)

The reason, I am saying this is because we need more space for the reading message and not to see the preview.

If both the issues / features are something which cannot be applied for everyone, please if you could guide me how can I do it for myself (I am not tech or coder). I will be really thankful.

Thanks.

Tech Details:

Version: 5.3.3
OS: Windows 8.1

**Comment by vantezzen** [comment]
1. is a feature requested in #153
2. looks to be due to the custom `service.css` of Telegram. To remove it, open the file at `%appdata%/Ferdi/recipes/telegram/service.css` and remove its contents. Please don't delete the file itself as that will cause issues.

**Comment by agamerj** [comment]
Hello, Thanks for the reply.

There is no FERDI in the Local App Data Folder. Please help me with it. @vantezzen

**Comment by vantezzen** [comment]
Oh sorry, its acutually in`%appdata%/Ferdi/recipes`
