### ISSUE TITLE
Turned spell checking off, now it spell checks for English instead of not at all

### ISSUE THREAD

**Issue by VOOM108** [getferdi/ferdi#400]
I turned spell checking off, in search for the source for the "losing focus to input field" bug, now it spell checks for English instead of not at all. Usually it spell checks for German, turned on it spell checks German, turning it off all German words are marked wrong because it is checked for English. Now that works even less of course. 

(Win10, Ferdi 5.4.4-beta1)

**Comment by kytwb** [comment]
I think we need to get rid of electron-spellchecker and use Chrome's built-in spellchecker introduced with the upgrade to Electron 8.

**Comment by ZeroCool940711** [comment]
Im having this problem since version 5.4.0, I can't upgrade to a newer version since the red lines under everything is pretty annoying, I write with people in multiple languages (Spanish, English, Japanese, German and Italian) and the spell check is making it impossible to use a new version since everything not written in English will be marked as if its written incorrectly.

**Comment by mimavox** [comment]
Will this ever be fixed?? The app is totally useless as it stands now.. really can't stand these squiggly lines. As all idiotic spellcheck systems, you really cannot use them if you're multi lingual. I, for example, mix English and Swedish all the time (as well as use abbrevations and technical jargon) which makes it impossible to use a spell check system that only recognizes proper words for one language at the time. Feels like some developers really don't understand this use case :(

**Comment by ZeroCool940711** [comment]
@mimavox I recommend using an older version, I haven't updated ferdi in a while just because of the stupid spell checking. It looks like it will never be fixed so, you should downgrade to version 5.4.0 or older and disable updates on ferdi so it doesnt update itself.

**Comment by vantezzen** [comment]
@mimavox I appreciate your feedback and I am having the same problems as you, constantly switching between German and English.
We definitely want to improve Ferdi's spellchecker by switching to the more native solution provided by ElectronJS in the near future (hopefully even with 5.4.4 if we can manage) but for now we are working on other essential features and fixes like getting "Use without an Account" to not crash on Windows (see #253) and getting all frequently-used services (like Google) to fully work.
For the time being, Ferdi is being maintained by mostly @kytwb and me in our free time so some features and fixes (like this one) may take some time until one of us two has the time and motivation to realise them.
We are always happy to see other members of Ferdi's community taking action and providing us with PRs themselves to make Ferdi better though - so if you want feel like you want and could help fix this issue yourself we would very thankfully accept PRs.

**Comment by ZeroCool940711** [comment]
Any news on when this will be fixed? I tried later version and it still has this problem, its been quite some time since the spell checker cant be disabled, since version 5.4.0 the spell checker is broken if you disable it as it turns on English spell checking and for those of us who speak other languages its the same as been broken.

**Comment by mimavox** [comment]
We are now at 5.5.0 and still no fix. Sorry, but I just cannot use this software anymore. Have to look for alternatives.

**Comment by ZeroCool940711** [comment]
@mimavox Im using version 5.4.0 since it was released, anything above that version won't work, I tried looking for alternatives but there arent any good alternatives, if you can find something that can do what ferdi does please let me know, I would also like to use something else unless this problem is fixed.

**Comment by vantezzen** [comment]
I'm sorry to hear that. We are currently working on Ferdi 5.6.0 where we will be switching to the spellchecker build-in to the OS. This way we can provide functionality to check for multiple languages and hopefully also fix the error that spellcheck can't be completely disabled.

**Comment by mimavox** [comment]
> @mimavox Im using version 5.4.0 since it was released, anything above that version won't work, I tried looking for alternatives but there arent any good alternatives, if you can find something that can do what ferdi does please let me know, I would also like to use something else unless this problem is fixed.

I recently tried Wavebox, and that seems to be a good alternative. However, for the time being, I've reverted back to Chrome as a dedicated browser for the site/apps I need (I'm using Firefox as my default browser otherwise).

**Comment by ZeroCool940711** [comment]
@mimavox after checking Wavebox I found [Hamsket](https://github.com/TheGoddessInari/hamsket) which is a fork of Rambox just like Ferdi is a fork of Franz, its pretty good, I will test it and tell you if its a good alternative.

**Comment by leandroprz** [comment]
I'm experiencing the exact same issue as well. I'm using v5.5.0
Here's my debug log: https://pastebin.pl/view/642f326e

**Comment by fernandofig** [comment]
It persists on v5.6.0 beta 5, Windows 10 x64

**Comment by pieniacy** [comment]
I think I found a workaround!

Edit `~/.config/Ferdi/config/settings.json`, find `spellcheckerLanguage` and change the line to :
```
  "spellcheckerLanguage": "PLEASE_FIX_DISABLING",
```

I use Arch btw and my Ferdi version is 5.5.0

**Comment by vraravam** [comment]
Closing - the fix is in the upcoming nightly.

**Comment by pieniacy** [comment]
Can confirm, [ferdi-git from AUR](https://aur.archlinux.org/packages/ferdi-git/) works great! Thanks a lot!
