### ISSUE TITLE
Can't login on Google Calendar, says that web browser isn't safe

### ISSUE THREAD

**Issue by nsrosenqvist** [getferdi/ferdi#407]
**Describe the bug**
Can't login on Google Calendar, says that web browser isn't safe and links to [this page](https://support.google.com/accounts/answer/7675428) for more information.

**To Reproduce**
Add Google Calendar as a service and attempt to login.

**Expected behavior**
One should be able to log in.

**Desktop:**

- OS: Windows 10
- Ferdi Version: 5.4.3
- Server Used: https://api.getferdi.com

**Comment by kytwb** [comment]
Closing as this has been discussed in https://github.com/getferdi/ferdi/issues/264.  
You can try the script shared via https://github.com/getferdi/ferdi/issues/264#issuecomment-584837303 in the meantime to update the user agent of your Google services 🙏

**Comment by nsrosenqvist** [comment]
Thanks! Great to know it's already being worked on 🙂
