### ISSUE TITLE
Camera laptop not recognized by Skype with flatpack package

### ISSUE THREAD

**Issue by Nokia808** [getferdi/ferdi#411]
**Describe the bug**

Skype currently do not detect my laptop camera, though it detect my laptop mic !
**To Reproduce**

login to Skype account & try to launch camera. You will see "no device detected". The camera icon is inactive. This also happening if you try to test camera. Please look at my mouse pointer within attached screenshot bellow.

**Expected behavior**

It should detect camera.
**Screenshots**

![no-camera](https://user-images.githubusercontent.com/25375330/75538856-35190f00-5a11-11ea-901e-ff594dd014c6.png)

**Desktop:**

- OS: [Fedora Linux X64 bit, version 30, Cinnamon edition]
- Ferdi Version [e.g. 5.4.3 X64 bit]

- Server Used: [I'm using Ferdi without Ferdi account]

Debug information: https://debug.getferdi.com/...

**Additional context**

I'm installing Ferdi as a flatpak package from FlatHub.

**Comment by duduche59** [comment]
Same problem.
Desktop

- OS : LinuxMint 19 Cinnamon

- Ferdi 5.4.3

-  Server Used: [I'm using Ferdi without Ferdi account]

I'm installing Ferdi as a flatpak package from FlatHub.

**Comment by duduche59** [comment]
Same with WhatsApp

**Comment by kytwb** [comment]
@lhw could it be related to https://docs.flatpak.org/en/latest/sandbox-permissions.html#device-access?

**Comment by lhw** [comment]
Yes I already noticed this too. Will fix it asap

**Comment by lhw** [comment]
Had time to test it. Works with the version that will be up in a few minutes to hours. Depending on how fast the build servers are.

**Comment by kytwb** [comment]
@lhw Thank you! 🙏

**Comment by Nokia808** [comment]
@lhw 
Thank you very much!
Only one thing: does this fix will make camera available on other services like WhatsApp & ICQ ?
In Skype there is already icon for video call. But with WhatsApp & ICQ there is no such icon ?

**Comment by lhw** [comment]
What I noticed is that some webapps require the chrome built-in "allow access to webcam" to function. I tried with Discord and it just auto accepted it in the background. But I am not sure how WhatsApp handles this. Maybe @kytwb knows more about this. The camera is now generally available to all applications in Ferdi so that is not the blocker.

**Comment by kytwb** [comment]
@Nokia808 are you missing the video call icons in the latest flatpak version?

**Comment by Nokia808** [comment]
@kytwb 
@lhw 
Hi all. I just received new update few minutes ago.
1) It is very perfect regarding Skype, so this issue is fixed really.

2) but other services like: WhatsApp, Telegram, & ICQ, the only change is that before this fix I was unable to use camera to take a picture by it & send this picture as attachment through the service like WhatsApp, but after this update now I can use my laptop camera through WhatsApp JUST to take picture then send it as attachment. BUT:

3) I can not make audio / video calls through WhatsApp, Telegram, ICQ. The question is that: is this a bug or the matter is just that the web applications of these services do not support audio / video calls & they infact support audio / video message as attachment ?? When I use Telegram official application as flatpak, there is icon for audio calls, but when I open Telegram from Ferdi there are only option (icon) to send audio messages (recording) & other for sending a media (as attachment) audio or video file (not recorded from within Telegram).
If this (point 3) is a bug, then inform me to open a new bug.

**Comment by kytwb** [comment]
@Nokia808 awesome! Regarding the rest, I think it's the latter; I also can't do video calls in the web version of WhatsApp. Regarding Telegram, I suspect the same as the current web app used is very limited; we are thinking of changing it for a web app with more features via https://github.com/getferdi/recipes/issues/56. Not sure for ICQ.

**Comment by mbnoimi** [comment]
I've a similar issue with snap version (Ferdi 5.6.3) although I give the package a full permissions as shown below:
```
$ snap connections ferdi
Interface                 Plug                   Slot                             Notes
audio-playback            ferdi:audio-playback   :audio-playback                  -
browser-support           ferdi:browser-support  :browser-support                 -
content[gnome-3-28-1804]  ferdi:gnome-3-28-1804  gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     ferdi:gtk-3-themes     gtk-common-themes:gtk-3-themes   -
content[icon-themes]      ferdi:icon-themes      gtk-common-themes:icon-themes    -
content[sound-themes]     ferdi:sound-themes     gtk-common-themes:sound-themes   -
desktop                   ferdi:desktop          :desktop                         -
desktop-legacy            ferdi:desktop-legacy   :desktop-legacy                  -
gsettings                 ferdi:gsettings        :gsettings                       -
home                      ferdi:home             :home                            -
network                   ferdi:network          :network                         -
opengl                    ferdi:opengl           :opengl                          -
pulseaudio                ferdi:pulseaudio       :pulseaudio                      manual
unity7                    ferdi:unity7           :unity7                          -
wayland                   ferdi:wayland          :wayland                         -
x11                       ferdi:x11              :x11                             -
$ 
```
![image](https://user-images.githubusercontent.com/284547/142875267-1a63596f-a4c6-4fdf-ae25-061f188641d0.png)

**Comment by mbnoimi** [comment]
It seems this issue occurs in `snap` disrto while it doesn't occur in `appimage` distro
