### ISSUE TITLE
Does Ferdi save passwords in secure way?

### ISSUE THREAD

**Issue by Nokia808** [getferdi/ferdi#412]
Sorry for that, but I have no other way to ask this question.
I was using Rambox. But Rambox currently has very weak point: it store credentials (passwords) using MD5 hash to encrypt them, which is bad algorithm.

I would like to ask about Ferdi: does it store passwords in secure way or in plan text ? If it store passwords in encrypted way, then which algorithm (or way) it using for this ?

Many thanks for your efforts to build & maintain this nice application.

**Comment by vantezzen** [comment]
Ferdi does not store your service credentials.

The password for your Ferdi Account is hashed via sha256 before sending it to our servers who then again hash the password before storing them in our database.

**Comment by kytwb** [comment]
In addition to what @vantezzen said, I wanted to mention there is one password that is currently stored in an unsafe manner in Ferdi, which is the password used for the Lock feature. It will be addressed via https://github.com/getferdi/ferdi/issues/230.

**Comment by Nokia808** [comment]
Thank you all for your replies !

I asked specifically about passwords saved to login for services like Skype, Haugout, Google, .......
@vantezzen said "Ferdi does not store your service credentials." ! So, if not store them, then how can remember them on next sessions ??

Can you kindly explained more about this point: passwords to login to services like Skype, Google, .....

**Comment by kytwb** [comment]
@vantezzen answered:

> Ferdi stores your service sessions locally using Chrome partition files.

We don't store the passwords used to login in your services, only the sessions.

**Comment by kytwb** [comment]
More on sessions in the [Electron documentation](https://www.electronjs.org/docs/api/session) and [relevant code](https://github.com/getferdi/ferdi/search?l=JavaScript&q=session).
