### ISSUE TITLE
Setup Windows development machine in the cloud

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#415]
I propose we setup a Windows development machine in the cloud so both @vantezzen and I can connect to it remotely and debug/test things on Windows before releasing as we both don't have access to Windows afaik. 

That would unlock https://github.com/getferdi/ferdi/issues/253 (via https://github.com/getferdi/internal-server/issues/2) as a fix has been submitted but not tested yet. It would also help prevent introducing platform-specific regressions further down the road. 

The development machine would incur some costs that could be passed onto the collective. At the moment Ferdi runs almost for free using the free tier of AWS (monthly bill under $1):

<img width="853" alt="Screen Shot 2020-02-28 at 4 14 22 PM" src="https://user-images.githubusercontent.com/412895/75562218-842e6680-5a48-11ea-9ce1-c5bd343b1a87.png">

We could take a look at the [EC2 On-Demand Pricing](https://aws.amazon.com/ec2/pricing/on-demand/) for Windows and establish which kind of instance we would need; Windows instances comes with EBS only for storage, so we should take that in the cost consideration as well (we can run the EC2 instance on-demand (start it when we're working and stop it when we're done) but the storage will be persistent and paid for).

WDYT?

**Comment by kytwb** [comment]
Alternatively I wanted to take a look at Visual Studio Online but [I'm stuck at login](https://twitter.com/kytwb/status/1233407038472048645).

**Comment by vantezzen** [comment]
This sounds like a good idea. Do you know how much this would approximately cost?

**Comment by rndthoughts** [comment]
I use Azure DevOps (VS Online) quite extensively and Azure - can i assist in anyway?

**Comment by kytwb** [comment]
I have been stuck with VS Online trying to setup my account:

<img width="426" alt="Screen Shot 2020-03-17 at 5 55 56 PM" src="https://user-images.githubusercontent.com/412895/77020036-b31e6500-6982-11ea-9b5c-3335153d3b8d.png">

I have already created the free Azure account but the menu above doesn't get updated. I will give it another try or go with AWS.

**Comment by rndthoughts** [comment]
If you've already created a free Azure account, did you create the subscription in the Azure Portal?

**Comment by kytwb** [comment]
@rndthoughts yes it is created; I have followed-up with Azure support on Twitter (with a video of the issue) and they suggested I create a new support ticket.

**Comment by rndthoughts** [comment]
That's bizarre, I've just tried it myself and got the following.   It's nothing to do with any ad-blocker or failed CORS requests is it?  I noticed the new Edge because extremely picky about CORS requests recently.

![image](https://user-images.githubusercontent.com/4190823/77154286-4f379180-6a93-11ea-8e9e-d0747a1ef182.png)

**Comment by kytwb** [comment]
The request to go fetch my subscriptions is done, but the returned array is empty. I have tried in Brave, Chrome (making sure there's no script bocker). Safari isn't supported. Installing Edge and giving it another try later today.

**Comment by kytwb** [comment]
<img width="1115" alt="Screen Shot 2020-03-21 at 4 54 19 PM" src="https://user-images.githubusercontent.com/412895/77230468-ad986900-6b94-11ea-8c5e-9d559af052a1.png">

**Comment by vantezzen** [comment]
What I currently don't understand about VS Online is can it run the ElectronJS app? Looking into the service, it looks like you can only run server applications but we cannot test Ferdi itself - is that right?

**Comment by rndthoughts** [comment]
Yes it's pretty much a shared development environment - you can access VSCode in a browser rather than an Electron app.  If you want to actually run the app, you'd have to spin up a ubuntu/mac/windows vm on Azure anyway but you could automate this process with DevOps.

**Comment by kytwb** [comment]
Ah my bad for the confusion; @vantezzen I'll just setup a Windows instance we can Remote Desktop Connect to in AWS next to the already existing instance that runs the server 🙏 Following this: ["Remote Desktop uses the Remote Desktop Protocol (RDP) and enables you to connect to and use your instance in the same way you use a computer sitting in front of you."](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/connecting_to_windows_instance.html)

**Comment by kytwb** [comment]
Instance created and succesfully connected using [Microsoft Remote Desktop 10](https://apps.apple.com/app/microsoft-remote-desktop/id1295203466?mt=12) for macOS.  
Setting up the development environment.

**Comment by kytwb** [comment]
Well, that's embarrassing. I think that was a false lead as well; I could only start a Windows Server instance and I just realized that's completely different from a normal Windows (7, 8, 10). I couldn't install VSCode on it. I guess we will have to try to get a Windows VM to run locally, but that would be nothing that can be shared and licences managed at your own discretion.

Feedback appreciated 🙏

**Comment by kytwb** [comment]
@vantezzen I terminated the instance to avoid incurring costs.

**Comment by kytwb** [comment]
I just ran into the following: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/.
Downloading and giving it a try with VirtualBox for macOS.

**Comment by kytwb** [comment]
Experiencing with [Amazon WorkSpaces](https://aws.amazon.com/workspaces/features/) 👀

**Comment by kytwb** [comment]
Looks like it's the same issue:

> AWS Workspaces does not give you a Windows client install. AWS will only provide server installs.
>
>"All Amazon WorkSpaces bundles include a Microsoft Windows 7 or Windows 10 desktop experience, powered by Windows Server 2008 R2 and Windows Server 2016 respectively...".

https://stackoverflow.com/a/50650682/926721

**Comment by kytwb** [comment]
@vantezzen added the credentials to the Amazon WorkSpaces account to the secure note.

**Comment by kytwb** [comment]
<img width="1150" alt="Screen Shot 2020-03-26 at 2 48 55 AM" src="https://user-images.githubusercontent.com/412895/77602398-af07bf80-6f0d-11ea-803a-0dce59a32628.png">
<img width="1150" alt="Screen Shot 2020-03-26 at 2 58 24 AM" src="https://user-images.githubusercontent.com/412895/77602405-b29b4680-6f0d-11ea-9a0a-e3cd31b59e64.png">

**Comment by kytwb** [comment]
Details on pricing available at https://aws.amazon.com/workspaces/pricing/

**Comment by kytwb** [comment]
@vantezzen Given upcoming monthly billing, I just wanted to bring that back to attention and re-evaluate with you if we should keep the workspace or not? We have new contributors since who are working on Windows, so maybe we could consider including them in the release testing process?

**Comment by vantezzen** [comment]
Yes, I think that the little use we get out of the workspace can justify the monthly cost. It was good to solve the Windows issues but not really needed anymore.

**Comment by kytwb** [comment]
Done 👍 Current billing status FYI:

<img width="437" alt="Screen Shot 2020-04-16 at 1 38 04 PM" src="https://user-images.githubusercontent.com/412895/79457096-8a23db00-7fe7-11ea-9059-45aafa531f5c.png">

**Comment by kytwb** [comment]
By the way, Microsoft is sharing a Windows development environment for free via https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

**Comment by kytwb** [comment]
I recommend going with Parallels Desktop on macOS if ever needed. VirtualBox was not working.


<img width="1440" alt="Screen Shot 2020-04-24 at 8 23 23 AM" src="https://user-images.githubusercontent.com/412895/80192011-121c6d00-8606-11ea-84c6-e4b8b201b00b.png">


<img width="959" alt="Screen Shot 2020-04-24 at 7 15 24 AM" src="https://user-images.githubusercontent.com/412895/80192005-10eb4000-8606-11ea-9886-6d140f03f303.png">

**Comment by kytwb** [comment]
If you're a contributor or thinking of contributing to Ferdi and are using macOS, let us know, we have some licences for [Parallels Desktop](https://www.parallels.com/) to share with you so you can properly contribute and test your changes on Windows (using the free development Windows VM shared above) 🥳 

<img width="1281" alt="Screen Shot 2020-04-30 at 11 59 21 AM" src="https://user-images.githubusercontent.com/412895/80707862-34b4f700-8ada-11ea-8d90-6acb9203566f.png">

**Comment by kytwb** [comment]
I will be adding Parallels logo to the README:

![parallels-logo-png-transparent](https://user-images.githubusercontent.com/412895/87706297-3025e380-c797-11ea-94c4-bf8414b0b5ab.png)
