### ISSUE TITLE
Gmail service not working

### ISSUE THREAD

**Issue by pelonchasva** [getferdi/ferdi#417]
**Describe the bug**

When adding the Gmail service, and try to log in with my gmail account, it says it cannot be accessed because the browser is not supported.

**To Reproduce**

1. Add the Gmail service
2. Try to login using a valid gmail account
3. See error

**Expected behavior**

The service should provide a valid browser engine to work according to google's restrictions.

**Screenshots**

![gmail_service](https://user-images.githubusercontent.com/4713147/75599278-fc0c8900-5a68-11ea-8396-ea4d5177071c.PNG)

**Desktop:**

- OS: Windows 10 Pro - v10.0.18362 - Build 18362
- Ferdi Version: 5.4.3

- Server Used: https://api.franzinfra.com

**Additional context**

* Tried reloading the service but it isn't working.
* Restarted the app and the issue remains.

**Comment by kytwb** [comment]
Closing as this has been discussed in https://github.com/getferdi/ferdi/issues/264.  
You can try the script shared via https://github.com/getferdi/ferdi/issues/264#issuecomment-584837303 in the meantime to update the user agent of your Google services 🙏
