### ISSUE TITLE
Add predefined select options to Ferdi Todo setting

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#418]
The idea is for this issue to be picked up by new people wanting to contribute to Ferdi's development. The goal is to outline what is expected clearly so the new contributor can practice submitting a pull request while taking care of and focusing on a contained enhancement to get started.

**Task:** Enhance current Todo Server setting so users can select from a pre-defined list of Todo services. Rename Todo Server to Todo Service by the way. Example of Todo services: [Todoist](https://todoist.com/app), [Microsoft To Do](https://todo.microsoft.com/tasks/), [Franz Todos](http://app.franztodos.com/), ... Last select option should say _Custom service URL_ and show the existing input to let the user freely configure a custom URL as it currently works.

**Edit:** did a pairing session with @yourcontact to introduce him to the task.

**Comment by yourcontact** [comment]
@kytwb shall we close this issue now that we are working #477 ?

**Comment by kytwb** [comment]
@yourcontact There is some merge conflicts in the pull request now, could you take a look at how-to fix them please? I can jump in a quick call to help fix if needed but please give it a go yourself first, there should be instructions on how-to merge the conflicts:

You will probably need to run `npm run prepare-code` after fixing the conflicts for the `json` files to be regenerated with the right line count.

**Comment by yourcontact** [comment]
> @yourcontact There is some merge conflicts in the pull request now, could you take a look at how-to fix them please?

@kytwb I took a look at the conficts. I resolved some, not all. I posted a question in the PR: https://github.com/getferdi/ferdi/pull/477#issuecomment-606514031

**Comment by kytwb** [comment]
@yourcontact Thank you for your contribution and perseverance!  
💪 Welcome onboard!

**Comment by kytwb** [comment]
📦 Shipped in [v5.5.0-gm](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm).
