### ISSUE TITLE
Unable to use SOCKS proxy type in Ferdi per service proxy setting

### ISSUE THREAD

**Issue by MurzNN** [getferdi/ferdi#421]
**Describe the bug**
I need to user local tor instance as proxy for some services. It work as SOCKS5 proxy at localhost:9050.
But in Ferdi I can't set proxy type in service settings, filling only port&host not help. Seems by default Ferdi try to use it as HTTP proxy?

**To Reproduce**

1. Start local tor instance
2. In Ferdi configure proxy for some service with filling host "localhost" and port "9050"
3. Restart Ferdy
4. You will see error when loading service

**Expected behavior**
Ferdi must provide selector for proxy type for allow use SOCKS proxy

**Desktop:**

- OS: Linux
- Ferdi Version 5.4.3

**Comment by vantezzen** [comment]
Have you tried using `socks5://localhost` as your Proxy Host?

**Comment by MurzNN** [comment]
Thanks, filling `socks5://localhost` works well! Will be good to add description to field with examples of setting proxy protocol.
