### ISSUE TITLE
Invalid translations for Portuguese Brazilian

### ISSUE THREAD

**Issue by leandrogehlen** [getferdi/ferdi#424]
Currently there is mistake with translations. The file `pt.js` contains **Portuguese Brazilian** translations but should be **Portuguese Portugal**.

**Expected behavior**
It's necessary to move file content from ` pt.js` to `pt-BR.js` and fix Crowdin integration

**Screenshots**
![image](https://user-images.githubusercontent.com/1750751/75676380-d7323480-5c67-11ea-9dde-bf6844bad3fa.png)

**Comment by vantezzen** [comment]
Thank you for the report. This problem should be fixed via #420
