### ISSUE TITLE
Find feature in navigation bar

### ISSUE THREAD

**Issue by leandrogehlen** [getferdi/ferdi#432]
I think is necessary adds find feature on navigation bar.

![image](https://user-images.githubusercontent.com/1750751/75770518-d1e7ef00-5d26-11ea-902d-afdb7f89823b.png)

**Comment by kytwb** [comment]
Closing in favour of https://github.com/getferdi/ferdi/issues/67 but taking your feedback in consideration to prioritize tickets accordingly.
Thank you!

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.3).

**Comment by bittner** [comment]
The "Find in Page" <kbd>Ctrl</kbd>+<kbd>F</kbd> option is now available from the "View" menu.

While I understand the reasoning behind this ("it's all read-only"), I believe the appropriate place would still be the "Edit" menu. That's where people are used to look for it.

Would you accept a PR for that change?
