### ISSUE TITLE
Small issue with 5.4.4 beta-x: rendering of websites

### ISSUE THREAD

**Issue by VOOM108** [getferdi/ferdi#434]
Since 5.4.4 a website I added as a service does not render correctly. There is a tiled background that should fill the whole window. Now it has white borders left and right and does not display the background much further down than the content leaving a large whitespace. This does not happen in any browser displaying the same page. I wrote the HTML and CSS myself, so I know there is nothing wrong on that side and I could fix it myself if there was. 

It is surely not a big issue, but a little annoying. 

The URL is: https://orakel-spiel.de/neo/

I suppose this will happen to other pages, too, but just in case there is sth I can fix in the page I thought I'd provide it for testing...

**Comment by kytwb** [comment]
Could you please share a screenshot? Which platform are you?  
I don't think I can reproduce:

<img width="1083" alt="Screen Shot 2020-03-04 at 1 37 01 AM" src="https://user-images.githubusercontent.com/412895/75833230-b0374800-5db8-11ea-9ab0-284b202c5627.png">

We have introduced `user.js` and `user.css` in services in 5.4.4, could you double-check yours?

<img width="332" alt="Screen Shot 2020-03-04 at 1 38 40 AM" src="https://user-images.githubusercontent.com/412895/75833301-eb397b80-5db8-11ea-91c8-b495c98b2b97.png">

**Comment by VOOM108** [comment]
user.css ist empty and user.js has nothing addional in it. 
![whitespace](https://user-images.githubusercontent.com/16562946/75833616-dc06fd80-5db9-11ea-9d05-ddc8c413fa4f.png)

**Comment by kytwb** [comment]
<img width="342" alt="Screen Shot 2020-03-04 at 3 51 06 AM" src="https://user-images.githubusercontent.com/412895/75840454-88051480-5dcb-11ea-83ec-0d8634373946.png">

You would need to handle overriding user agent styles in your website:

```css
html, body { 
  margin: 0;
}
```

More on this: [body margin user agent](https://duckduckgo.com/?q=body+margin+user+agent&t=brave&ia=web).

**Comment by VOOM108** [comment]
Thanks!

This is strange; I also had to set the height of body and margin to 100% in order to remove the large bottom whitespace. Never saw this happen before, and with Ferdi it appeared only with the latest betas.
