### ISSUE TITLE
Translations error

### ISSUE THREAD

**Issue by leandrogehlen** [getferdi/ferdi#438]
Some translations are not working:

![image](https://user-images.githubusercontent.com/1750751/75887814-219ee700-5e09-11ea-9127-cbfb93dd5053.png)

![image](https://user-images.githubusercontent.com/1750751/75887857-324f5d00-5e09-11ea-8e4b-7ac68f1f419c.png)

**Comment by kytwb** [comment]
That must have slipped through during the review 😄 
Thanks for reporting, we will address!

**Comment by kytwb** [comment]
<img width="600" alt="Screen Shot 2020-03-11 at 4 54 40 AM" src="https://user-images.githubusercontent.com/412895/76381130-ed6d7e00-6354-11ea-9ab3-5d019c4f78fb.png">
