### ISSUE TITLE
Get Ferdi notification status through applescript

### ISSUE THREAD

**Issue by dfrigon** [getferdi/ferdi#439]
Hi,

is there anyone who know how we could extract every service notification status (the red dot on the app icon) so I could integrate it in third party apps?

Thanks!

**Comment by vantezzen** [comment]
I don't think that there is currently a way to integrate this information into third-party apps - at least not that I know of.

**Comment by mhatvan** [comment]
Duplicate of https://github.com/getferdi/ferdi/issues/967
