### ISSUE TITLE
Update your download page!

### ISSUE THREAD

**Issue by dutscher** [getferdi/ferdi#440]
Hy there, i found this on your download page.
It shows "Download Ferdi 5.4.3" but the link is "https://github.com/getferdi/ferdi/releases/download/v5.3.3/Ferdi.Setup.5.3.3.exe"

![image](https://user-images.githubusercontent.com/14682/75981081-05bc4380-5ee4-11ea-8560-28a191c66a02.png)

cheers

**Comment by vantezzen** [comment]
We are intentionally still shipping v5.3.3 for Windows due to #253 - all other platforms are up-to-date. We will get back to shipping the newest update once that problem is fixed.
