### ISSUE TITLE
Add Signal

### ISSUE THREAD

**Issue by Prajwal-Koirala** [getferdi/ferdi#444]
Hello,
Can we please add signal.
https://signal.org/
- prajwal

**Comment by vantezzen** [comment]
Duplicate of:
getferdi/ferdi#342
getferdi/recipes#26
getferdi/recipes#22
getferdi/recipes#21
getferdi/recipes#18
meetfranz/franz#1702
meetfranz/franz#767
meetfranz/franz#655

Signal cannot be added as it does not have a web client.
