### ISSUE TITLE
Ferdi is not opening in Debian 10

### ISSUE THREAD

**Issue by anacvignola** [getferdi/ferdi#450]
Ferdi is not opening in Debian 10.

SO: Debian 10(Buster) GNOME: 3.30.2

Test: Ferdi 5.4.0 and Ferdi 5.4.3

**Comment by marchingon12** [comment]
Try out the latest beta package (v.5.4.4), it's working at my end. v5.4.3 and v5.4.0 won't open at all.

**Comment by kytwb** [comment]
@marchingon12 thanks for the feedback! 🙏
@anacvignola please try with a more recent version, will re-open if the issue persists.
