### ISSUE TITLE
Right click not working

### ISSUE THREAD

**Issue by halcyon101** [getferdi/ferdi#452]
it opens the right-click menu then closes it immediately how to fix this issue?

**Comment by kytwb** [comment]
Duplicate of https://github.com/getferdi/ferdi/issues/357; we will be publishing a new beta release with the fix (https://github.com/getferdi/ferdi/pull/419) today.

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.3).
