### ISSUE TITLE
Discord not staying logged in

### ISSUE THREAD

**Issue by StephenDini** [getferdi/ferdi#455]
**Describe the bug**

Logging into Discord via the Scan QR code and with User/Pass w/ 2FA does not save the credentials. 
This may be related to #177 

**To Reproduce**

1. Add Discord as a service
2. Log in with User/Pass w/ 2FA or QR login
3. Close Ferdi 
4. IT will now be logged out. 

**Expected behavior**

I expected to not log in each time. 

**Desktop:**

- OS: Windows 10
- Ferdi Version 5.4.3 and 5.4.40-beta.2

- Server Used: https://api.franzinfra.com [e.g. https://api.getferdi.com]

Debug information: https://debug.getferdi.com/eb8eee08-7d55-4abd-81f5-e6ea36101f68

**Additional context**

This might be somewhat related to Issue #177

**Comment by wedens** [comment]
Still a problem with a fairly recent 48e25d8 revision. I've logged in with username/password in a freshly installed ferdi, restarted ferdi and I wasn't logged in. Then I logged in using a QR code, so far it survived a couple of restarts.

**Comment by MisterShifty** [comment]
Still happening for me on Linux -- though oddly, my Discord stays logged in on the Windows (both Linux and Windows running Ferdi 5.6.0).  I do have 2FA enabled on Discord.

**Comment by mhatvan** [comment]
Closing as duplicate of https://github.com/getferdi/ferdi/issues/1198 

Please continue the conversation there.
