### ISSUE TITLE
Uninstaller

### ISSUE THREAD

**Issue by Prajwal-Koirala** [getferdi/ferdi#461]
Hey,
Just uninstalling this was the hardest thing i did today and took almost 45 mins, can we please make a uninstaller.
- Prajwal

**Comment by vantezzen** [comment]
Uninstalling should only require you to delete the `*.exe/*.app/...` and the "Ferdi" folder in the user data - or are there any other files Ferdi saves permanently?

**Comment by Prajwal-Koirala** [comment]
`Windows Registry`
`if you update, it will install twice`
`%temp%`
