### ISSUE TITLE
Screen sharing does not work

### ISSUE THREAD

**Issue by Esokrates** [getferdi/ferdi#463]
**Describe the bug**

Using Skype in the latest Flatpak version screensharing does not work, clicking screensharing does nothing.

**Desktop:**

- OS: Ubuntu 20.04 (Gnome session, using X11)
- Ferdi Version 5.4.3

**Comment by Zackhardtoname** [comment]
Not working for Discord neither.
Laptop:

OS: Ubuntu 18.04
Ferdi Version 5.4.3

**Comment by kytwb** [comment]
Related to https://github.com/electron/electron/issues/4432.

**Comment by MurzNN** [comment]
Maybe this workaround https://github.com/electron/electron/issues/16513#issuecomment-602070250 can help with implementing custom screen sharing picker?

**Comment by gautamsi** [comment]
@MurzNN I came across this issue after opening a PR - https://github.com/getferdi/recipes/pull/116

It worked for Teams so should also work for skype.

**Comment by Esokrates** [comment]
@gautamsi Would you mind implementing this for Skype too?

**Comment by gautamsi** [comment]
@Esokrates I have added a PR for this which is exactly like Teams.

**Comment by MurzNN** [comment]
@gautamsi Great thanks! Screen sharing in Skype with your patches works well! Waiting merge this PR with master!

**Comment by Esokrates** [comment]
@gautamsi Thanks very much!
@kytwb Actually this bug should remain open as there are still other services that don't have screensharing, e.g. Discord?

**Comment by MurzNN** [comment]
Maybe exists some way to integrate this feature globally in Ferdi, to work for all services? If Ferdi use iframe, here is way to pass `getDisplayMedia()` from iframe: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture#Security_2

**Comment by gautamsi** [comment]
I will try over weekend to see if can integrate as umbrella solution for all.

**Comment by tubbynl** [comment]
this will be awesome, thank you guys for your effort :)
