### ISSUE TITLE
Remote\Reverse Proxy

### ISSUE THREAD

**Issue by endiz** [getferdi/ferdi#465]
Ability to run ferdie as a reverse proxy webserver so you can connect from any browser. 

### Feature Description

ferdie.personaldomain.com brings up the ferdie interface in any browser.

Additional functionality could also be added to the ferdie client to connect to this reverse proxy to create a vpn-like connection in an un-trusted environment.

### Motivation and Context
* Why is this change required?
	- Allow you to use ferdie remotely without installing it
* How is this improving the Franz experience?
	- Remote connectivity
* What problem does it solve?
	- No installation
	- Secure connectivity in hostile environments

**Comment by vantezzen** [comment]
This doesn't look like a feature that would be viable to implement into Ferdi.

It is very complex to implement yet it would only be used by very few people. As far as I can tell, there are no libraries that easily allow remote operations for Electron and most people that want to use Ferdi can install the application, and if not that they can at least use the portable edition of it.

 I suggest you to use software like TeamViewer or [Chrome Remote Desktop](https://remotedesktop.google.com/) instead.
