### ISSUE TITLE
Custom service icons isn't working with custom Ferdi sync server

### ISSUE THREAD

**Issue by pztrn** [getferdi/ferdi#470]
**Describe the bug**

Custom service icons isn't working with self-hosted Ferdi server - looks like I'm able to assign one, but it is invisible in interface (sidebar and service editing page). Right after assigning I saw:

<img width="159" alt="изображение" src="https://user-images.githubusercontent.com/869402/76705543-a4c21600-6702-11ea-9f94-2ddcb51dddc9.png">

See that gray dot in left lower corner? Is that **icon**? :)))

**To Reproduce**

1. Assign custom icon to custom service.
2. Click "Save".
3. Say "WTF where is my icon?" :) And see no icon in services sidebar.

**Expected behavior**

Icon is saved and shown in sidebar and services list in settings.

**Desktop:**

- OS: macOS 10.14.6
- Ferdi Version 5.4.4-beta.3 (5.4.4-beta.3.1426)
- Server Used: up-to-date self-hosted

Debug information: https://debug.getferdi.com/016604e2-a7d2-4ae5-8c86-16a2df5c2e52

(btw, why my ferdi server URL is publicly available at debug.getferdi.com? I do not want everyone to register there!)

**Comment by jeroenpraat** [comment]
I can also confirm this when not using Ferdi without an account (using the Internal Ferdi Server). Same behavior as described as above. If you delete the custom icon the default icon comes back, but after restarting Ferdi it's blank again.

Using the developer tool, I can see what the location should be:

`http://127.0.0.1:45569/v1/icon/31be7c65-5272-4008-b370-21f3829e02d7d60d58dc-c67c-4585-a1cc-44371757cf5d`

Loading this into Firefox redirects me to http://127.0.0.1:45569/

This file actually exist in `~/.config/Ferdi/icons/31be7c65-5272-4008-b370-21f3829e02d7d60d58dc-c67c-4585-a1cc-44371757cf5d`

_I'm on Ubuntu 20.04_

**Comment by anotherjames** [comment]
Once I had restarted Ferdi, saving and displaying the icons for services worked fine.

**Comment by ragusa87** [comment]
This issue is related to https://github.com/getferdi/ferdi/issues/780

**Comment by mhatvan** [comment]
Cannot reproduce this, seems it was fixed by the PR linked above.

Custom .svg icon shows correctly on both macOS and Ubuntu, also after restarting Ferdi.
