### ISSUE TITLE
Blank unlock screen

### ISSUE THREAD

**Issue by justus-saul** [getferdi/ferdi#471]
OS: Ubunu 18.04.4
Ferdi Version: 5.4.4-beta.3

After the upgrade to 5.4.4-beta.3 I get a blank unlock screen with the purple background and cannot login.

Going back to beta 4 solved the issue for me.

**Comment by kytwb** [comment]
Seems similar to what I commented in https://github.com/getferdi/ferdi/issues/467#issuecomment-599551019.  
Thanks for reporting 🙏

**Comment by vantezzen** [comment]
Can you please add a screenshot of where you are stuck? From your description this might not be the login screen but the general startup screen, so the error might be even before opening the lock screen.

Also, are you able to open the DevTools somehow? If so, it would be useful to see any console output that occured.

**Comment by ghanisch** [comment]
Same here with 5.5.0, my ferdi-screen was locked with a blank screen right after enabling password. See gif.
No reinstall or nightly version worked for me.
This worked though: 
Installed 5.4.3 - then i was able to unlock per password (which was empty!)
after deactivating password-lock i was able to re-install 5.5.0  - normal startup without a password needed.
![ferdi 5 5 0 password bug_small](https://user-images.githubusercontent.com/40340058/84122635-08758a00-aa39-11ea-84e0-edb70f57a592.gif)

**Comment by joseadrian** [comment]
I also got the same problem with version 5.5.0 on windows. After downloading it, I went to settings and enabled password lock. Right after I was asked to do a restart. Then a blank screen wouldn't let me in. 

Tried uninstalling and installing a 5.6.0-beta.2 which no longer showed a blank screen but it was locked. I guess this was already fixed, though an empty password didn't work. Uninstalling wasn't enough, had to search for ferdi files and remove manually everything that was left. After that I was able to use Ferdi.

**Comment by Ansem93** [comment]
I had the same issue with windows. 
Selected "enable password lock", than I had a black screen and I couldn't do anything.
Installed ferdi 5.6.0 b2 but now it ask for a password than I never inserted.

**Comment by misleadingrhino** [comment]
The instructions in [this(596)](https://github.com/getferdi/ferdi/issues/596#issuecomment-639146765) comment got this working again for me. 

> Hi, instead of reverting back to an older version to deactivate the Password lock, you can also go to C:\Users\Username\AppData\Roaming\Ferdi\config, then open settings.json & then set "lockingFeatureEnabled" to false.
> 
> I had the same issue, but after changing the value & reopening Ferdi, everything was working again :)

**Comment by Pedro12909** [comment]
> The instructions in [this(596)](https://github.com/getferdi/ferdi/issues/596#issuecomment-639146765) comment got this working again for me.
> 
> > Hi, instead of reverting back to an older version to deactivate the Password lock, you can also go to C:\Users\Username\AppData\Roaming\Ferdi\config, then open settings.json & then set "lockingFeatureEnabled" to false.
> > I had the same issue, but after changing the value & reopening Ferdi, everything was working again :)

Isn't this a security flaw? The password prompt can be bypassed by changing a flag in a settings file

**Comment by j1ngles** [comment]
upgraded to 5.5.0 today, this is still an issue for me.

**Comment by dalaeance** [comment]
Having the same problem on Fedora 34. And I'm pretty sure I had it on Windows 10 a few days ago, but got around it by uninstalling, restarting, and re-installing.

**Comment by mhatvan** [comment]
Seems to be an older issues, can't reproduce with latest nightly from: https://github.com/getferdi/nightlies/releases

Please file a new issue in case this still occurs.
