### ISSUE TITLE
Gmail with SAML providers redirects to login page

### ISSUE THREAD

**Issue by Hakujou** [getferdi/ferdi#473]
**Describe the bug**
My company uses Google Apps for Work with SAML login.
After typing my company email in "login" prompt, it redirects me to SAML login page (expected). Once I'm logged in the SAML page, it tells me it will redirect me to Gmail, but it redirects me to Google login page instead.
If I retry to connect by entering my email on Google, my SAML providers tells me my session is still valid (so cookies are working fine) and if I'm redirected back to Google login page once again.

**To Reproduce**
Add Gmail service with a SAML enabled account and try to login.

**Expected behavior**
The redirect from the SAML should occur to Gmail.

**Desktop:**
- OS: MacOS 10.15.3
- Ferdi Version 5.4.4 beta 1
- Server Used: https://api.getferdi.com

**Comment by tpopela** [comment]
Can confirm this as well.

OS: Fedora 31
Ferdi Version 5.4.4-beta.3 (inside Flatpak)
Server Used: https://api.getferdi.com

**Comment by tpopela** [comment]
I think that the problem will be in https://github.com/getferdi/recipes/blob/master/uncompressed/gmail/webview.js#L6 the " if (location.hostname == 'www.google.com') " is probably too general. I will try to build ferdi and see whether I can do it a little bit stricter.

**Comment by vantezzen** [comment]
Thank you for investigating this.

To change recipe files you won't have to build Ferdi from source! The recipe files are stored inside `~/.config/Ferdi/recipes` and can be edited from there.

**Comment by tpopela** [comment]
Yes, I found it :) so the first location is:

https://www.google.com/intl/cs/gmail/about/# ('cs' states there from Czech Republic)

and after SAML is finished, then it loads with:

https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&service=mail&sacu=1&rip=1

So there are two solutions. Only redirect if we find "gmail/about/" in the location, or redirect always unless find 'https://accounts.google.com/ServiceLogin'. I have locally the first solution and it works and the other one will work as well I expect. So decide what you like more and I will create a PR in getferdi/recipes.

**Comment by vantezzen** [comment]
Great! I think the first solution sounds like the better one.

**Comment by vraravam** [comment]
I am also facing the same issue - unable to login into work email. Can anyone please help?

**Comment by vantezzen** [comment]
> Can anyone please help?

This will be fixed via the next update of Ferdi, we've already merged the changes.
If you know how, you can already update the recipe locally yourself using the files at https://github.com/getferdi/recipes/tree/master/uncompressed/gmail - otherwise the recipe will be automatically updated when Ferdi 5.4.4 is released.
