### ISSUE TITLE
Hangouts will not load

### ISSUE THREAD

**Issue by kyds3k** [getferdi/ferdi#474]
**Describe the bug**

When trying to log in to Hangouts, I get a screen that says "Couldn't sign you in - this browser or app may not be secure."

**To Reproduce**

1. Add Hangouts as a service
2. Click on the Hangouts icon
3. Follow the login instructions

**Expected behavior**

Expect to be logged into Hangouts!

**Screenshots**

![image](https://user-images.githubusercontent.com/1071985/76882281-7de31b80-688b-11ea-9600-a3e9de8d6d1c.png)

**Desktop:**
- OS: Windows 10
- Ferdi Version 5.4.3

- Server Used: https://api.getferdi.com

**Comment by vantezzen** [comment]
Thank you for your report.

This issue is already being discuddes in #264
