### ISSUE TITLE
Right click not working properly in Telegram

### ISSUE THREAD

**Issue by FreeMeWat** [getferdi/ferdi#478]
Hi, love the app. I manage a lot of social media accounts and am very active on all platforms. This app is an amazing idea! However, one glaring problem that I cannot seem to figure out:

Using Telegram via Ferdi, when I have my list of chats, if I right click a chat, the "right click" options dont pop up, in the chat list or the actual messages themselves, so I cannot:

delete chats
delete messages
pin messages
mute or ban
promote to admin
or any other option that right clicking would give me. 

This is so important, could you perhaps find a fix for this? Thank you

Windows 10 - most recent update of Ferdi

**Comment by kytwb** [comment]
@FreeMeWat Thanks for your report! Could you please try with [v5.4.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.3)?  
We believe this has been fixed in this release via https://github.com/getferdi/ferdi/pull/419.

**Comment by FreeMeWat** [comment]
Hi, thank you for the reply. I downloaded the beta, and right click does
work now, but not for the correct purpose. Where right-click should open
options to delete and manage telegram chats/messages, it pops up with a
"windows style" right click option menu, only allowing me to "Copy, Inspect
Element, and Paste as Plain Text"

[image: image.png]

**Comment by kytwb** [comment]
Ah my bad, I had forgotten this is similar to https://github.com/getferdi/ferdi/issues/300 and not related to the context menu. This will be addressed via https://github.com/getferdi/recipes/issues/56.
