### ISSUE TITLE
Empty Todos causes 1px purple border line

### ISSUE THREAD

**Issue by deadmeu** [getferdi/ferdi#48]
**Description**
When the todos feature is enabled, empty, and collapsed, a thin vertical purple line is drawn on the right-hand edge of the window.

**To Reproduce**
1. Open the app
2. Enable Todos
3. Collapse Todos
4. See purple line on right edge of the window

**Expected behavior**
No purple line should be shown, as occurs when Todos are disabled.

**Screenshots**
The line may be hidden using the developer tools, as shown in this gif:
![Ferdi purple line](https://user-images.githubusercontent.com/12111013/65150888-55a76b00-da68-11e9-8064-ff6bf97db39c.gif)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: latest master branch as of bug report, 5.3.3 indicated in the app

**Comment by vantezzen** [comment]
I think this behaviour can also be found inside Franz (but with a blue line). It should indicate that "there is something" on the right side. When hovering near the line, the button for opening Ferdi Todos will appear.

Thus making it not a bug but a feature request to change Ferdi's behaviour. I actually don't mind the line but I am also not a fan of it so I wouldn't care if we remove it.

What do other people think? Keep it or remove it?

**Comment by kytwb** [comment]
> It should indicate that "there is something" on the right side. When hovering near the line, the button for opening Ferdi Todos will appear.

I'm for keeping it as it.
