### ISSUE TITLE
Slack dark mode not working

### ISSUE THREAD

**Issue by Xerus2000** [getferdi/ferdi#483]
**Describe the bug**

When I go to the service settings for Slack and click on enable dark mode, the slider turns on. But as soon as I hit save, the slider turns back off. Nothing changes.

**Desktop:**

- OS: KDE Neon (based on Ubuntu)
- Ferdi Version: 5.4.4-beta.3

- Server Used: https://api.getferdi.com

Debug information: I clicked on publish, but it doesn't respond - the button remains in clicked state and there's no link.

**Additional context**

**Comment by vantezzen** [comment]
That sound more like a server or network problem to be honest as publishing debug log doesn't work either.

Can you please open the console by going to "View" > "Open Developer Tools" and screenshot any errors that may appear while you are trying to save.

**Comment by Xerus2000** [comment]
Yeah, it was a bit buggy overall, seems it's smoother now. I'll reopen if I get more details :)

**Comment by vantezzen** [comment]
Our server seemed to have some small problems which now look to be resolved. Closing this issue for now
