### ISSUE TITLE
Question: Limited info about portable version

### ISSUE THREAD

**Issue by acicovic** [getferdi/ferdi#489]
Hello everyone,

I would like to test Ferdi so I wanted to get the portable version. In the readme.md there is a mention of Ferdi portable for Windows but I couldn't find any other information on how to get it.

Is there a pointer or document with more info?

Thanks!

**Comment by vantezzen** [comment]
You can always find all release files of the latest Ferdi version at https://github.com/getferdi/ferdi/releases/latest when scrolling past the changelog.
"Ferdi-5.4.3.exe" is the Windows Portable version while "Ferdi-Setup-5.4.3.exe" is the normal Windows version.

**Comment by acicovic** [comment]
Thanks for the info @vantezzen. Perhaps it would make sense to rename the file to something like Ferdi-Portable-5.4.3.exe? I think that this would make things a bit clearer for potential portable users.

Thanks again!
