### ISSUE TITLE
Start Ferdi minimized (not in tray)

### ISSUE THREAD

**Issue by Jendker** [getferdi/ferdi#490]
**Is your feature request related to a problem? Please describe.**
In beta there is a new feature of starting Ferdi minimized in tray, thank you for it!  https://github.com/getferdi/ferdi/issues/288 Some may not use the tray icon though but still would like to start Ferdi minimized. Would it be possible to extend the current option to non-tray behaviour?

**Describe the solution you'd like**
Change the option "Start minimized in tray" to "Start minimized". This option would always be visible, not only when "Show Ferdi in system tray" is active. 

**Describe alternatives you've considered**
Not sure what the alternative could be.

**Comment by kytwb** [comment]
@Jendker thank you for the suggestion Jendker! 🙏

**Comment by kytwb** [comment]
Referencing to upstream https://github.com/meetfranz/franz/issues/365.

**Comment by kytwb** [comment]
📦 Shipped in [v5.5.0-gm](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm).
