### ISSUE TITLE
Segfault on Linux

### ISSUE THREAD

**Issue by ragusa87** [getferdi/ferdi#491]
**Describe the bug**
After a crash the application doesn't open anymore.
A segfault occur every time you launch the app. A reboot is needed to fix it.

**To Reproduce**
Well, I don't know how to reproduce it. 
Yesterday while using slack, I clicked on a channel and Ferdi crashed.
Then I was not able to open it (Seg fault) until I restarted my computer.
Today, I have the same behaviour, the app doesn't open anymore due to a seg. fault so I am reporting it.

**Expected behavior**
The app should open

**Screenshots**
> ./messages/current.AppImage --help
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:16087) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:16087) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:16087) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:16087) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
Starting local server on port 45569
info: serving app on http://127.0.0.1:45569
(electron) 'setAudioMuted function' is deprecated and will be removed. Please use 'audioMuted property' instead.
[1]    16087 segmentation fault  ./messages/current.AppImage --help

strace ./Ferdi-5.4.4-beta.3.AppImage
+++ killed by SIGSEGV +++
[1]    19054 segmentation fault  strace ./Ferdi-5.4.4-beta.3.AppImage
[trace.log](https://github.com/getferdi/ferdi/files/4371165/trace.log)

**Desktop:**

- OS: 
> ➜ uname -r
4.15.0-91-generic
> ➜ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

Ferdi Version:
> Ferdi-5.4.4-beta.3.AppImage

**Comment by abmantis** [comment]
Also experiencing this. Any logs that could help?

**Comment by igorguida** [comment]
Hi all, it's still relevant, it's just happend to me, after an improper shutdown (electricity down), the app is unable to restart giving me this error:
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Errore di segmentazione

**Comment by numkem** [comment]
I'm getting the same thing, OS is NixOS, franz works just fine.

**Comment by MarvinMep** [comment]
Same issue here.
Debian 10.6
ferdi_5.5.0_amd64.deb

uninstalled, cleaned cache, config, etc., installed again, added `"enableSystemTray": false` to .config/Ferdi/config/settings.json (https://github.com/getferdi/ferdi/issues/677#issuecomment-624834036) ...

Nothing seems to make it work. 

> ~$ ferdi
> (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
> (node:6249) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
> (node:6249) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
> (node:6249) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
> (node:6249) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
> Segmentation fault

**Comment by diraol** [comment]
Just happened here.

These are the logs while trying to restat it:

```
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:28212) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:28212) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:28212) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:28212) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(electron) 'setUserAgent function' is deprecated and will be removed. Please use 'userAgent property' instead.
[1]    28212 segmentation fault  ferdi
```

Let me know if I can help gathering more info.
System: Debian bullseye/sid
Using Sway (Wayland)
ferdi_5.5.0_amd64.deb

**Comment by diraol** [comment]
Updating here:

I've completely removed and cleaned up Ferdi from my computer and then reinstalled. Same thing.

I'm using a personal server, and I've started using Ferdi today (I was just doing my first client setup).

At the moment when Ferdi started throwing segfault, I had just added my 15th service (and 3 workspaces).

The last three applications I've added were, in this order, `Instagram`, `Jitsi` and `Linkedin`.

After removing them (and all relationships between workspaces and services) directly on the database I was able to start my Ferdi client again.

**Comment by d4hines** [comment]
Same thing, also on NixOS.

**Comment by mtoohey31** [comment]
I was also experiencing the same issue after a completely fresh install (on Wayland), and the same issue ocurred with the current appimage release, but the 5.6.0-beta.2 appimage does not give me any errors, so I'm using that for now until 5.6 is officially released and goes through the nixpkgs pipeline.
