### ISSUE TITLE
Teams don't work

### ISSUE THREAD

**Issue by SVSwift** [getferdi/ferdi#496]
**Describe the bug**
Managing teams doesn't work when using franz's servers (default install).

**To Reproduce**

1. Go to Settings -> Manage Team
2. Click on Manage your Team on getferdi.com
3. See error 404: Not found

**Expected behavior**

I would expect to be able to add new team members. When this isn't possible because franz won't allow it when using their servers I would expect to see a notice that it will work when setting up an own ferdi-server. 
BTW: Does ferdi-server support teams? If so: Why isn't it stated in the README?

**Screenshots**

![Ferdi1](https://user-images.githubusercontent.com/56492577/77530131-2ba88880-6e91-11ea-8c0b-ab12fe218224.png)
![Ferdi2](https://user-images.githubusercontent.com/56492577/77530133-2c411f00-6e91-11ea-8791-501b33e0ab0d.png)

**Desktop:**

- OS: Windows 10
- Ferdi Version 5.4.3 (latest)

- Server Used: https://api.franzinfra.com

**Additional context**

The same happens when you try Settings -> Account ->Edit account

**Comment by vantezzen** [comment]
Ferdi doesn't officially support Franz Teams and there is no support for Teams on custom Ferdi servers.
The reason for this is that Ferdi doesn't offer any "premium" subscriptions, thus making Franz's Team management useless as that is only used to manage subscriptions for multiple users.
We may remove the "Teams" page in the future to make this more clear.

For now, if you need to manage your Franz team subscription simply replace the "getferdi.com" with "meetfranz.com" in the URL opened to manage teams.

**Comment by vantezzen** [comment]
We'll improve the information about Teams and Premium subscriptions in general via #497. This will also fix the "Manage your Team" link to work again.
