### ISSUE TITLE
Add "Don't Keep Loaded" option to services

### ISSUE THREAD

**Issue by CptDinosaur** [getferdi/ferdi#499]
**Is your feature request related to a problem? Please describe.**
Currently, all services in the active workspace are kept loaded at all times. This is resource intensive, especially memory intensive for people with many services.

**Describe the solution you'd like**
My proposed solution is to add a "Don't Keep Loaded" option to each service's settings, setting it so it is only loaded when it's the active tab, then unloaded when in the background. This could also be linked into disabling notifications.

I'm aware this would mean getting no notifications from them, but I don't actually need notifications for all my services anyway.

**Describe alternatives you've considered**
I could make an individual workspace for each service, but this is impractical.

(Thanks, nice work on the fork, by the way, I've been manually editing Franz updates until now to remove things that annoy me. Side question to save me from looking through code, what data is sent to your API when I'm not using a server? I saw it is connecting, but not sure what for. Update checks? It's periodic)

**Comment by vantezzen** [comment]
Thank you for your feature request but Ferdi already has such a feature: You can enable "Service Hibernation" in Ferdi's settings and can additionally set up how long services should be kept active before being hibernated.

Network requests sent to our server when you are not using an account is an update check and a check for new announcements.
