### ISSUE TITLE
Whatapp complains about the need of google chrome 49+

### ISSUE THREAD

**Issue by israelio** [getferdi/ferdi#502]
I am using Chrome Version 80.0.3987.149 (Official Build) (64-bit) (latest) on a mac, whatsapp web is working perfectly but when i try to use whatapp inside Fredi whatsapp complains:
"WhatsApp works with Google Chrome 49+"

Tested even on the latest Fredi v5.4.4-beta.3 build 1426

if you are using chromium to host the service there is probably a need to upgrade it.
![Screen Shot 2020-03-27 at 14 30 57](https://user-images.githubusercontent.com/2522999/77751911-9e536880-7037-11ea-9d2a-99681a452d86.png)

**Comment by kytwb** [comment]
Can you try a right click on the WhatsApp icon and "Reload"?

**Comment by kytwb** [comment]
That happened to me earlier today and Reload did the trick. Please let us know if that doesn't work for you and we will re-open. Thank you! 🙏

**Comment by israelio** [comment]
At the moment complete reinstall solved it... (reload didnt work earlier...) so if it will happen again i will reopen the issue.

**Comment by ICDeadPpl** [comment]
Updated to 5.5.0-gm on Windows 10, and the "WhatsApp works with Google Chrome 49+" message keeps reloading the page. 
Reload doesn't help, neither removing the service and adding it again.
Total uninstall of Ferdi and then installing it again didn't help.

**Comment by kytwb** [comment]
@ICDeadPpl We are addressing this regression in https://github.com/getferdi/ferdi/issues/536 🙏 Thanks for bearing with us! We prioritized publishing v5.5.0-gm as a pre-release as to release the long awaited fix for https://github.com/getferdi/ferdi/issues/264. Addressing it and shipping a fix with v5.5.0.
