### ISSUE TITLE
Missing settings when using without account

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#509]
**Describe the bug**

Some settings are missing when using the app without account. This affects the workspace and todo features. We can also notice the rulers (`<Hr/>`) are displayed even if the settings are not displayed.

**Expected behavior**

Display workspace and todo related settings. We should also include the rulers in the appropriate display conditions (if we keep any).

**Screenshots**

<img width="790" alt="Screen Shot 2020-03-28 at 3 12 39 PM" src="https://user-images.githubusercontent.com/412895/77829381-fa92b700-7121-11ea-98de-224edcf58748.png">

**Desktop:**

- OS: macOS
- Ferdi Version: 5.4.4-beta.3
- Server Used: none

Debug information: https://debug.getferdi.com/b26a35b2-c2dd-422b-bc91-374e0a24e021

**Comment by yourcontact** [comment]
I would like to work on that bug.
First, I am trying to check if I see that bug in the Ferdi app on my laptop but I am on version 5.4.3.
I toggled  `Include beta versions` on and clicked `Check for updates` button but I am stuck on 5.4.3.
<img width="244" alt="Screen Shot 2020-03-31 at 11 59 30 AM" src="https://user-images.githubusercontent.com/46404814/78013674-1a56f480-7347-11ea-8344-da7042057402.png">

How can I download Ferdi version 5.4.4-beta.3?

**Comment by kytwb** [comment]
Maybe related to the fact that I logged in to Franz server before.

**Comment by yourcontact** [comment]
I can't reproduce @kytwb 
I downloaded [Ferdi Version: 5.4.4-beta.3](https://github.com/getferdi/ferdi/issues/509). 
I am using Ferdi with no account. No server.
This is what I see:
<img width="619" alt="Screen Shot 2020-03-31 at 12 53 19 PM" src="https://user-images.githubusercontent.com/46404814/78018805-d2d46680-734e-11ea-876d-a1b674b168a5.png">
Screenshot of Ferdi version:
<img width="326" alt="Screen Shot 2020-03-31 at 12 55 26 PM" src="https://user-images.githubusercontent.com/46404814/78018849-e8e22700-734e-11ea-87c9-a0dcf6a6319f.png">

@kytwb I will let you decide what next step is with this issue.

**Comment by mhatvan** [comment]
Cannot reproduce this with the latest nightly, closing.
