### ISSUE TITLE
Some UI elements are wrongfully using Dark Mode styling

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#511]
**Describe the bug**

Noticed when reviewing https://github.com/getferdi/ferdi/pull/497 that some elements of the UI are using their Dark Mode styling when they should not, making some texts unreadable and some inputs stand out. Noticed on the "Your workspaces" input, "Account" titles, and workspaces drawer background (see gif below).

**To Reproduce**

![ezgif com-resize](https://user-images.githubusercontent.com/412895/77830174-0339bc00-7127-11ea-8c9f-945012f762aa.gif)

**Desktop:**

- OS: macOS
- Ferdi Version: 5.4.4-beta.3
- Server Used: N/A

**Comment by mhatvan** [comment]
Cannot reproduce this anymore with macOS Big Sur running v5.6.3-nightly.3
