### ISSUE TITLE
Hide 'Update' section from Flatpak (& Deb?) version

### ISSUE THREAD

**Issue by keunes** [getferdi/ferdi#512]
**Is your feature request related to a problem? Please describe.**
Currently the "Update" section in the settings don't do anything, when Ferdi is installed as Flatpak. It might be confusing for not so experienced users, and the button's don't do anything anyway. Not sure how updating works with the Deb package version (does installing the Deb add a repository)?

**Describe the solution you'd like**
Maybe remove the section all-together, or just display the current version. Potentially, it could also be displayed whether a new version is available, plus a note that Ferdi is installed as a Deb/via Flatpak, and that it will (need to) be updated via the system.

Ping @lhw, as you seem to have been involved in the Flatpak packaging and thus probably know a thing or two about Flatpak updating :)

**Comment by kytwb** [comment]
Adding as a note, the [list of auto-updatable targets](https://www.electron.build/auto-update#auto-updatable-targets).

**Comment by lhw** [comment]
Currently the version used in the flatpak is actually the debian package version. Which is basically just unpacked and linked in the correct places. Deactivating the update section is probably a good idea to not confuse users. Right now I assume that most people installing Ferdi via flatpak are enthusiasts but you never know the future.

Maybe add a conditional to the build process that allows deactivating the update page altogether?

**Comment by keunes** [comment]
> Currently the version used in the flatpak is actually the debian package version.
> Maybe add a conditional to the build process that allows deactivating the update page altogether?

Would it work to add the conditional to just for the debian package, then?

**Comment by lhw** [comment]
Yes. Absolutely. Until I get around to doing a from-source build for flatpak its just the debian package unpacked in a flatpak environment.

**Comment by keunes** [comment]
@lhw Could this be something for Hacktoberfest?

**Comment by lhw** [comment]
I have never worked with electron/js but I'm guessing this could be considered a small change. Add a build environment variable and set a small "can't update like this" page if founds. Sounds reasonable.

**Comment by keunes** [comment]
@kytwb @vantezzen What d'you think about labelling this for Hacktoberfest?

**Comment by keunes** [comment]
Thanks @kytwb!
