### ISSUE TITLE
Windows 10: Dragging titlebar from the very top doesn't work while maximized

### ISSUE THREAD

**Issue by thegoldgoat** [getferdi/ferdi#519]
1. Open maximized Ferdi
2. Drag from the very top of the title bar
3. Nothing happens

**Expected behavior**

You should be able to move the window around

**Screenshots**

![Ferdi-2020-03-29-17-41-23](https://user-images.githubusercontent.com/25644731/77853573-04c9b980-71e5-11ea-8184-7315afeee4a0.gif)

**Desktop:**

- OS: Windows 10
- Ferdi Version: 5.4.3
- Server Used: https://api.getferdi.com

**Comment by douglaswhitaker** [comment]
Wanted to report that this is still a problem - I found this bug report via Google when searching for a solution. Exactly what @thegoldgoat describes matches the behaviour I'm seeing, and this is the only application that I use that has this problematic behaviour. 

Version: 5.5.0 (x64)
Electron: 8.2.3
Node.js: v12.13.0
Platform: win31

**Comment by thegoldgoat** [comment]
Yeah, but I guess this is a problem of electron itself, unfortunately I have no knowledge about it so can't test it

**Comment by mhatvan** [comment]
Partially reproduced this with v5.6.1-nightly.48

Grabbing the topmost end of the title bar doesn't work. 
If you grab it at the middle or lower end of the title bar, it works as expected.

Anyhow, I assume this is indeed electron specific.
