### ISSUE TITLE
No mouse actions while downloading file in Whatsapp

### ISSUE THREAD

**Issue by jocuen** [getferdi/ferdi#523]
Hello. When I try to download a file from a Whatsapp chat, the folder navigator appears but I can't select items clicking with the mouse: they can be modified only using the keyboard. 
This problem does not exist in the inverse way, when I send (upload) a file to a chat.   

* Ferdi Version used: 5.4.3
* Operating System and version: Debian testing amd64, Gnome desktop 3.34.2

**Comment by jocuen** [comment]
Maybe it is related to the libwayland in the gnome-shell. I will check in more detail.

**Comment by mhatvan** [comment]
Strange issue, but I can't reproduce it anymore with 5.6.3-nightly.3

Running Ubuntu 21.04 with GNOME 3.38.5

Is this still an issue for you @jocuen?
