### ISSUE TITLE
Ctrl + tab to switch services

### ISSUE THREAD

**Issue by lukefisklennon** [getferdi/ferdi#529]
**Describe the solution you'd like**
Would like to be able to use control + tab to switch services (like in chrome) and control + shift + tab to go the other way.

**Additional context**
Switched away from franz due to this (issue open there has been ignored). Hoping this repo is more active.

**Comment by mahadevans87** [comment]
@vantezzen @lukefisklennon Can I work on this?

**Comment by vantezzen** [comment]
Of course! I'll assign the issue to you so others can see that you are already working on it.
If you have any questions, don't hesitate to ask here.

**Comment by mahadevans87** [comment]
Sure. Please go ahead and link this with #301 and close this issue.

**Comment by kytwb** [comment]
Closing in favor of https://github.com/getferdi/ferdi/issues/301.
@lukefisklennon thanks for feedback! We will address the issue in #301, you can subscribe to notifications in the right sidebar:

<img width="323" alt="Screen Shot 2020-04-05 at 1 48 47 PM" src="https://user-images.githubusercontent.com/412895/78498792-4a860500-7744-11ea-839b-661f847b9d7d.png">

**Comment by lukefisklennon** [comment]
@kytwb thanks!
