### ISSUE TITLE
Add Dark Mode hot-key / toggle shortcut

### ISSUE THREAD

**Issue by lukefisklennon** [getferdi/ferdi#530]
**Describe the solution you'd like**
Shortcut key for switching between light and dark theme (if one doesn't already exist). And the ability to customise this shortcut if possible.

**Comment by vantezzen** [comment]
Sure, go ahead

**Comment by kytwb** [comment]
📦 Shipped in [v5.5.0-gm](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm).
