### ISSUE TITLE
Expose DarkReader settings to users

### ISSUE THREAD

**Issue by lukefisklennon** [getferdi/ferdi#531]
**Describe the solution you'd like**
Allow users of ferdi to access darkreader settings. In particular, the brightness setting which makes dark themes more readable for me. Also, the shortcut key setting would be useful.

(Sorry for submitting so many issues lol)

**Comment by mahadevans87** [comment]
@kytwb  Can I take this up?

**Comment by vantezzen** [comment]
Not @kytwb but yes you can take this

**Comment by kytwb** [comment]
@mahadevans87 Please do! Feel free to pick up whichever open issue you feel like working on if nobody explicitly said they're working on it and the issue is not assigned 🙏

**Comment by nordurljosahvida** [comment]
this would be amazing thanks!

**Comment by kytwb** [comment]
📦 Shipped in [v5.5.0-gm](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm). A minor fix will be shipped in v5.5.0 via https://github.com/getferdi/ferdi/pull/593.
