### ISSUE TITLE
Any 'first good issue' I could work on?

### ISSUE THREAD

**Issue by yourcontact** [getferdi/ferdi#533]
@kytwb, are there any '[good first issue](https://github.com/getferdi/ferdi/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)' I could work on?

EDIT: added `good first issue` url

**Comment by Krzyku** [comment]
https://github.com/getferdi/ferdi/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by vantezzen** [comment]
https://github.com/getferdi/ferdi/issues/529 may be interesting to implement. You'll need to add a new item to the menubar to allow the usage of shortcuts and then you toggle between services using that.

**Comment by yourcontact** [comment]
Thanks, @vantezzen. I will look at #513.
I am closing this issue for now.
