### ISSUE TITLE
Caches aren't being cleared

### ISSUE THREAD

**Issue by PashaKagan** [getferdi/ferdi#541]
**Describe the bug**

Caches doesn't get cleared.
Currently I have 4.5GB worth of caches, which are not being removed when the button is clicked.
I know that I can remove it manually, but I feel like the button should work.
Exiting the settings and returning to them doesn't help, the button stays clicked until Ferdi is restarted.

**To Reproduce**

1. Go to settings
2. Scroll down to the clear cache button
3. Click the button
4. The button becomes "pressed", the spinner spins indefinitely
5. It doesn't change overnight, so it's not a "wait" thing

**Expected behavior**

The caches should clear, the size should be reduced, the folders should be cleaned.

**Desktop:**

- OS: Windows 10
- Ferdi Version 5.4.4-beta.3

**Comment by kytwb** [comment]
📦 Shipped in [v5.5.0-gm](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm). Will be enhanced via https://github.com/getferdi/ferdi/issues/557.
