### ISSUE TITLE
Mic not allowed in Discord

### ISSUE THREAD

**Issue by tristanplouz** [getferdi/ferdi#545]
**Describe the bug**

The microphone is not allowed to be used, the windows to allow it doesn't pop.
**To Reproduce**

Go into Discord service
Try to unmute your mic
The Discord website try to pop the allow windows

**Expected behavior**

The allow windows must pop or the mic has to be allowed
**Screenshots**

![Capture d’écran du 2020-04-07 15-07-12](https://user-images.githubusercontent.com/6893466/78672872-886c6000-78e1-11ea-8a5f-cf04b3ce0db1.png)
![Capture d’écran du 2020-04-07 15-37-12](https://user-images.githubusercontent.com/6893466/78675746-c8354680-78e5-11ea-9318-07807fe60351.png)

**Desktop:**

- OS: Debian Testing
- Ferdi Version 5.4.4-beta.3

- Server Used: [e.g. https://api.getferdi.com]

Debug information: https://debug.getferdi.com/...

**Additional context**

It doesn't work since the last discord update.
Works fine on Chromium and Firefox when the mic is allowed to be used
Sorry for my English Speaking

**Comment by deadmeu** [comment]
I experienced this issue yesterday, but now it seems to have gone away. Could you test this again to see if it is still present?

**Comment by tristanplouz** [comment]
Unfortunately, the issue is still present... The mic still not allowed when I try to activate it

**Comment by mhatvan** [comment]
I cannot reproduce this. 

It is probably an outdated issue that was fixed with updates in the meantime.
