### ISSUE TITLE
Hide menu bar

### ISSUE THREAD

**Issue by mahdzu** [getferdi/ferdi#546]
Hi...
Testing the menu bar I found a option like "Hide menu bar" (I do not remember exactly) in the menu Show. I clicked on it.

Now the menu bar is hidden and I do not know how to restore it.

![1](https://user-images.githubusercontent.com/58485218/78732259-65e93f80-78ff-11ea-814a-b32c5276386c.png)

**Desktop:**

- OS: [Linux 5.4.28-1-MANJARO (x86_64) ]
- Desktop environment: [Gnome-Shell 3.36.0] 
- Ferdi Version [ 5.4.3] I use self-host and use Ferdi without an account

So, how can I restore the menu bar?

Rgds.

**Comment by tristanplouz** [comment]
Hello,
You can temporarily show the menubar by pressing "alt" touch on your keyboard. And then deactivate the hide option.

**Comment by vantezzen** [comment]
Closing this question as the question has been answered.

**Comment by mahdzu** [comment]
I tried the "alt" tip and did not work for me but after a reboot of the computer I got the menu bar again.

Thanks
