### ISSUE TITLE
Specify a unique User-Agent

### ISSUE THREAD

**Issue by timabbott** [getferdi/ferdi#551]
It appears that Ferdi sends the following User-Agent to servers:

```
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.130 Safari/537.36
```

It'd be nice if there were something here that indicated that the connection is from Ferdi, not from Chrome, ideally containing the Ferdi version.  (E.g. due to #547, Ferdi/Franz recipes for Zulip throw exceptions every time a new message arrives in Zulip, and it'd be nice to be able to filter those)

**Comment by vantezzen** [comment]
Thank you for this feature request. We originally removed all information about Ferdi and ElectronJS as it would cause issues with Google, but as we'll now use a better method for fixing Google services we can go back to including information about Ferdi.

I'll add that information via #549, the new UserAgent looks like this:
```

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.141 Safari/537.36 Ferdi/5.4.4-beta.3 (Electron 8.1.1)
```
