### ISSUE TITLE
Allow user to install Tampermonkey plugin and run scripts within ferdi

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#553]
**Is your feature request related to a problem? Please describe.**
We use google chat for messaging - and gChat has some features that are not present. One of my colleagues had created a tampermonkey script - but, i don't find how I can install the plugin and register the script within ferdi

**Describe the solution you'd like**
Allow plugins like chrome/firefox within ferdi.

**Describe alternatives you've considered**
I will have to move away from ferdi for my comms.

**Additional context**

**Comment by vantezzen** [comment]
Ferdi >= 5.4.4-beta.2 allows you to use a custom `user.js` script to run inside services - you should be able to easily convert your Tampermonkey script to plain JavaScript (if its not already compatible). 
Otherwise there is already a feature request over at #113 to add support for Chrome Extensions.

**Comment by hcientist** [comment]
> Ferdi >= 5.4.4-beta.2 allows you to use a custom `user.js` script to run inside services - you should be able to easily convert your Tampermonkey script to plain JavaScript (if its not already compatible).
> Otherwise there is already a feature request over at #113 to add support for Chrome Extensions.

@vantezzen where?/how?

**Comment by hcientist** [comment]
How can I add global (or at least service-global) key listeners? tried the following in the discord console:

```
let betterListener = (ev) => {
    console.log('ev', ev);
}
```

1. `window.addEventListener('keyup',betterListener, true)`
1. `window.addEventListener('keydown',betterListener, true)`
1. `document.addEventListener('keyup',betterListener, true)`
1. `document.addEventListener('keydown',betterListener, true)`
