### ISSUE TITLE
Right-clicking on Discord messages brings up no context menu

### ISSUE THREAD

**Issue by diceroll123** [getferdi/ferdi#554]
**Describe the bug**
Right-clicking to bring up a context menu on a Discord message does nothing

**To Reproduce**

1. Go to any text channel in discord
2. Right-click on any message
3. See nothing happen

**Expected behavior**
A context menu should appear.

**Desktop:**

- OS: Win 10
- Ferdi Version 5.4.4-beta.3

**Additional info:**
No errors in the console.

**Comment by bartier** [comment]
@diceroll123 Is this happening on other services too? (Gmail, Slack, for example).

**Comment by diceroll123** [comment]
I don't know if Slack has custom context menus like Discord, but:

Gmail - context menu works when right-clicking an email in inbox
Slack - right clicking a message opens the windows context menu with Copy/Inspect Element

To clarify on Discord, it ONLY doesn't work for messages. It works for users in the sidebar and in chat, servers in the left sidebar, channels in the left sidebar.

Peculiar.

**Comment by diceroll123** [comment]
Sorry for the false alarm, folks. Turns out it's this way on the web client in my browser as well. (which I only used to look into this some more myself)

Googling this, it looks like it was an issue + was resolved 4 months ago.

In any case, doesn't seem to be Ferdi's bug. Closing!
