### ISSUE TITLE
Windows 10 Notification auto dismiss

### ISSUE THREAD

**Issue by danialasghar** [getferdi/ferdi#560]
**Describe the bug**

For windows 10 notifications the banner pops on the display but after its time out the notification dismisses instead of showing up in the action center. 
**To Reproduce**

1. Enable service
2. Receive notification
3. Wait for it to time out (3 or 5 seconds etc)
4. Check action center there will be no notification that you can check after

**Expected behavior**

**Screenshots**

**Desktop:**

- OS: Windows 10 build 1909
- Ferdi Version Latest 5.4.4 beta 3 

- Server Used: [e.g. https://api.getferdi.com]

Debug information: https://debug.getferdi.com/...

**Additional context**

Possible solution mentioned here: https://github.com/electron/electron/issues/3916#issuecomment-567860009

**Comment by tbasallo** [comment]
This is still an issue with electron v10.1.1

Is there anything out there discussing this bug?

**Comment by mhatvan** [comment]
Cannot reproduce this problem on Windows 10 Pro with the latest nightly.

The notification stays in the notification center also after marking the e.g. WhatsApp message as read.
It only gets dismissed when doing so manually through the notification center dialog.

Please reply in case this still occurs so I reopen this.
