### ISSUE TITLE
Ferdi's menu bar doesn't work (macOS)

### ISSUE THREAD

**Issue by 71vl17** [getferdi/ferdi#562]
<img width="363" alt="Снимок экрана 2020-04-11 в 15 36 11" src="https://user-images.githubusercontent.com/56300682/79044608-c5e92a00-7c0e-11ea-98ab-a2136b7d63c3.png">

I can't press "Ferdi" button and there's no other elements in menu bar when app launched and is active, so I can't edit text conveniently. Also hotkeys like "cmd+Q" don't work (maybe #550 is related), see video below:
https://drive.google.com/open?id=1KICgaSFpmUyeYNDu--qp2H6QCRtVrC3I

Elements appear for a short time on app's launch and then become gone:
<img width="484" alt="Снимок экрана 2020-04-11 в 15 54 22" src="https://user-images.githubusercontent.com/56300682/79044627-d5687300-7c0e-11ea-87a6-435d3443e412.png">

Mac:
macOS Catalina 10.15.3 (19D76)
<img width="135" alt="Снимок экрана 2020-04-11 в 15 54 13" src="https://user-images.githubusercontent.com/56300682/79044631-dc8f8100-7c0e-11ea-9c12-f4fb65f29732.png"> (can't even cmd+C)
Default https://api.getferdi.com

**Comment by kytwb** [comment]
This issue has been addressed via https://github.com/getferdi/ferdi/pull/393. You should be able to get the fixes by upgrading to https://github.com/getferdi/ferdi/releases/download/v5.4.4-beta.3/Ferdi-5.4.4-beta.3.dmg directly. Sorry for the inconvenience 🙏

**Comment by 71vl17** [comment]
Thanks

**Comment by Just-Insane** [comment]
There seems to be a regression/similar issue with 5.5.0, where the menu bar does not work and loads the system default options.

**Comment by jbredenfeldt** [comment]
I too have this issue, the "File" menu is not present, and there's no way to close the Ferdi window from the keyboard, the common ”Command-W” does nothing in macOS 10.15.5 (19F96). On a side note; it would be nice™ to be able to open the main Ferdi if you have closed it using the mouse, there's no command to re-open the main window, but that's not present in Franz either. Only way I've found to re-open the window is to click the app in the dock.

But it's still a much better love stor... I mean app than <arhem> ”others”.
