### ISSUE TITLE
Mobile optimized Viewport for KaiOS

### ISSUE THREAD

**Issue by tomwwabo** [getferdi/ferdi#566]
**Unfortunately there is no mobile version of Ferdi**
A lot of Messaging Apps - for example Telegram - do not support the feature-phone OS [KaiOS](https://www.kaiostech.com/)  which has gained a big userbase in developing countries.

**solution**
It would require a responsive slimmed down version of the Viewport, maybe a PWA would suffice.
See [KaiOS Devoper FAQ](https://www.kaiostech.com/developer-faq/) 

Maybe this could be helpful: 
https://whatwebcando.today/
And for a PWA https://quasar.dev/

Also while researching this issue I found
A rival for kaiOS: https://www.puffin.com/index.php

https://appsbuilders.org/guides/review-puffin-os-new-mobile-os-to-rival-android-go-kaios/

**Comment by kytwb** [comment]
I think we should be able to make Ferdi responsive / small viewport friendly to start with, but porting to KaiOS would need something like https://github.com/mozilla/positron, which has been [discontinued](https://mykzilla.org/2017/03/08/positron-discontinued/).

**Comment by vantezzen** [comment]
Sounds like a very interesting idea.
Ferdi relies heavily on Electron-specific features (webview, IPC messages etc.) though, which KaiOS can't provide. As Positron is long discontinued and doesn't implement many features Ferdi requires, we also can't go that route.

Supporting a platform like KaiOS would require us to fork Ferdi and perform major rewrites of large parts of the app.

I don't think this is a realistic target as this would essentially be a different project than what Ferdi is.

**Comment by vraravam** [comment]
Closing this - since it doesn't seem feasible.
