### ISSUE TITLE
Home button is not working as expected

### ISSUE THREAD

**Issue by leandrogehlen** [getferdi/ferdi#571]
The home button in navigation bar is loading the current url instead of home url.

**Desktop**
- OS: Windows 10
- Ferdi version:  5.4.4-beta.3 (x64)

![home-button](https://user-images.githubusercontent.com/1750751/79218297-914fbb00-7e26-11ea-82f6-7a338b126af7.gif)

**Comment by sampathBlam** [comment]
@leandrogehlen : I am curious how the address bar and the controls (home, back, etc ) are visible to you. Is there an option to make it visible/invisible in ferdi?

**Comment by vantezzen** [comment]
You can select whether you want to see the navigation bar in Ferdi's settings under "Navigation bar behavior"

**Comment by vantezzen** [comment]
Closing this as #573 is merged

**Comment by kytwb** [comment]
📦 Shipped in [v5.5.0-gm](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm).
