### ISSUE TITLE
Keep services in hibernation at startup

### ISSUE THREAD

**Issue by Octogonapus** [getferdi/ferdi#577]
**Is your feature request related to a problem? Please describe.**
When I start Ferdi, all my services (of which I have a lot relative to the "power" of my computer) start loading in parallel. I have service hibernation enabled so that most of them will hibernate because I only need to use a few of them regularly.

**Describe the solution you'd like**
When Ferdi opens, I would like all my services, except the service I had selected when Ferdi was closed, to start in the hibernated state. This way, I only have to load the service I was using last.

This feature would have no effect on the services of users that don't have hibernation enabled.

**Describe alternatives you've considered**
I'm not sure there are any alternatives. This feature just seems to be missing.

**Comment by kytwb** [comment]
Available in [v5.5.0-gm.2](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm.2).
