### ISSUE TITLE
Ferdi organization on GitHub

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#58]
As we are many contributors to this repository, I'm proposing to create a Ferdi organization on GitHub and transferring this repository and affiliated (https://github.com/vantezzen/ferdi-server, https://github.com/vantezzen/ferdi-slim-server) to that one organization. WDYT @vantezzen?

**Comment by kytwb** [comment]
If you're ok with it, we need to come up with an org name as `ferdi` is taken. Should we go with `meetferdi` or? Suggestions welcome! Mine: `getferdi/desktop`, `getferdi/server`, `getferdi/slim-server`.

**Comment by Gaboris** [comment]
I'd say using "meet" would be just too direct. If Ferdi really wants to detach itself from Franz then I'd say the "get" versions would be a better alternative.

**Comment by vantezzen** [comment]
Yes, great idea. I am for getferdi. Meetferdi also just looks too similar.

**Comment by kytwb** [comment]
@Gaboris thanks for the feedback!
@vantezzen roger that!

https://github.com/getferdi created, transferring the repository!

**Comment by kytwb** [comment]
✅ https://github.com/getferdi/ferdi

🎉😃

**Comment by kytwb** [comment]
@all-contributors please add @Gaboris for his feedback
