### ISSUE TITLE
Different tray icon notification indicator

### ISSUE THREAD

**Issue by FeikoJoosten** [getferdi/ferdi#583]
Currently it's unclear to me what kind of notification I've received by looking at the taskbar icon. You have a direct notification and an indirect notification.

I think it would be a great addition to have a similar solution as to what Slack does. When you have an indirect notification, the badge on the taskbar icon turns blue. and when you have a direct notification, the badge on the taskbar icon turns red.

**Comment by kytwb** [comment]
@FeikoJoosten Thank you for the feedback!

**Comment by mahadevans87** [comment]
What is the difference between a direct v/s indirect notification?

**Comment by FeikoJoosten** [comment]
direct: for example, on Discord/Slack a mention.
indirect: for example, on Discord/Slack an unread message in a channel without being mentioned.

**Comment by mahadevans87** [comment]
@FeikoJoosten What OS are you running Ferdi on?

**Comment by FeikoJoosten** [comment]
Currently Windows, but I'm certain that this feature isn't in any version of Ferdi?

**Comment by mahadevans87** [comment]
Ah yes. It's straightforward to implement this feature in Windows compared to OS/X and Linux. So wanted to confirm that before I take this up :)

**Comment by FeikoJoosten** [comment]
did some research (3 minutes of Googling). Slack does a similar thing as the Windows version of Ferdi currently does in the side bar (not the notification tray). https://images.fastcompany.net/image/upload/w_596,c_limit,q_auto:best,f_auto/fc/3068379-inline-zapier-7.png

I have no clue about Linux

**Comment by kytwb** [comment]
The Slack recipe used to support this afaik; indirect notifications would show just a red dot, and direct notifications would show a red dot with count, see: https://github.com/getferdi/recipes/blob/master/uncompressed/slack/webview.js#L46. Isn't it how we should continue to implement it?

**Comment by kytwb** [comment]
📦 Shipped in [v5.5.0-gm.2](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm.2).
Thank you everyone for your collaboration on this!
