### ISSUE TITLE
FB MESSENGER

### ISSUE THREAD

**Issue by nacho1978** [getferdi/ferdi#589]
**no funciona las videos llamadas de facebook messenger en getferdi. tengo instalado ferdi en ubuntu 18lts. aguardo 

aguardo solucion**

**Comment by nacho1978** [comment]
** facebook messenger video calls in getferdi does not work. I have ferdi installed on ubuntu 18lts. I await

I await solution **

**Comment by vantezzen** [comment]
Duplicate of #373
