### ISSUE TITLE
Replace leftover Franz references

### ISSUE THREAD

**Issue by AGCaesar** [getferdi/ferdi#59]
I found a few more Franz references....
In the settings Menue we have "show franz in info area" and "Activate franz todos"
Seen here: https://i.imgur.com/T5UmPfI.png
In the Menu under "?" -> "lean more" it still links to the franz homepage, 
Changelog  links to the franz changelog, 
"Support" links to https://meetfranz.com/support ,
"Terms of service" links to Franz,
"Privacy Statement" also links to franz

Maybe some are intentional or required, especially the privacy statement because we use their servers? Not sure, but the rest should probably be changed.

**Comment by kytwb** [comment]
Good catch, thanks for reporting!

> it still links to the franz homepage

I just got [getferdi.com](getferdi.com), so I think we can start referencing to (https://)getferdi.com when needed!

**Comment by vantezzen** [comment]
Thanks. 
I have now finally added a new `npm run apply-branding` script that replaces the Franz branding with the Ferdi branding in all locales. This should now mean that the only time we get leftover Franz references is, when they are hard-coded and not stored in the translation files.

**Comment by AGCaesar** [comment]
Is the "npm run apply-branding" performed automatically during build or do I have to change the Arch Linux package build do fix this? Sorry I am a total electron/npm noob.

**Comment by vantezzen** [comment]
> Is the "npm run apply-branding" performed automatically during build or do I have to change the Arch Linux package build do fix this? Sorry I am a total electron/npm noob.

You don't have to change anything in your package. The script will automatically be applied when pushing to GitHub, so the translations on GitHub are already fixed.
Additionally, one can manually run `npm run prepare-code` or `npm run apply-branding` to manually apply the branding before pushing it to GitHub.

**Comment by vantezzen** [comment]
> @kytwb : I just got getferdi.com, so I think we can start referencing to (https://)getferdi.com when needed!

I see that getferdi.com is currently parked. Can you redirect it to this repo?
And server.getferdi.com and slim-server.getferdi.com to their repos?

**Comment by kytwb** [comment]
![Screen Shot 2019-09-19 at 8 14 42 PM](https://user-images.githubusercontent.com/412895/65247198-281afa00-db1a-11e9-8676-ee41fb49cd74.png)
