### ISSUE TITLE
Add "Mailvelope" add-on to allow encryption of email services using OpenPGP

### ISSUE THREAD

**Issue by Nokia808** [getferdi/ferdi#591]
Hi. I have an idea if you apply it, your application will be elevated to the sky in comparison with other similar application like Franz & Rambox.

Look for this:
https://www.mailvelope.com/en
https://github.com/mailvelope/mailvelope

this is an add-on for both Firefox & Chrome - see:
https://github.com/mailvelope/mailvelope/releases

If you make this add-on included in Ferdi, so that users can use it to utilize OpenPGP to encrypt & decrypt heir/his emails over Internet then Ferdi will jump into sky & will be the 1st browser messenger that give users such security option ....... This will add big credential for your work .....

The question in my mind is the way to implement this:
1) as easy as such is just to include Mailvelope within Ferdi. In this case you will be in great responsibility to update Ferdi as soon as new version of Mailvelope released. At each new release of Mailvelope, you must push new release of Ferdi containing new release of Mailvelope .......
2) 2nd way, is add an installation point within Ferdi, allowing users to install Mail Mailvelope from official add-on so that it will updated automatically & by this you excuse yourself from additional packaging work ..... This way if implemented should bee only limited to Mailvelope add-on (not other add-on) so no need to visit add-on in usual way, but just one click process within Ferdi & it will bring it from official add-on page (AFTER VERIFYING IT AS USUAL) 

Other notes: 
1) this add-on when added, should only be active & accesable when user open an email service. If user open non-email service, like google drive or chat or messenger service, then this add-on should not be active or visible on UI of such non-email services because it is useless ......
2) usage of this add-on should be optional to the user: user can select to use it or not (to activate it or to deactivate it as she/he like).

Please look to this suggestion & consider it seriously ....... Really it will elevate Ferdi to the sky .......

By the way, this suggestion not to my benefit but to benefit of other users. I'm already using Thunderbird+enigmail & will never such new option instead of Thunderbird+enigmail.

Also, you should notify the users that Mailvelope on Firefox/Chrome is less secure than Thunderbird+enigmail BUT IT IS BETTER THAN NO ENCRYPTION AT ALL.

Many thanks.

**Comment by vantezzen** [comment]
We already have a feature request to support chrome extensions over at #113. When we implement that, users who are interested in Mailvelope can install it themselves.
Additionally, we won't make any assumptions about how users like to use their services - this is why we will never pre-enable any extension by default.

> Really it will elevate Ferdi to the sky

Personally, I think that such a feature will not attract many users. Users who are already privacy conscious will already use a service like ProtonMail or use a setup like yours.
As you already said yourself: You "will never [use] such new option" - so if even you as the requester of this feature won't use it, then the amount of users who will is tiny and won't justify the amount of work it takes to implement such a feature.

Looking at the Firefox page, Mailvelope currently only has 65k users which is very little compared to actually popular extensions like UBlock Origin with almost 6 Mio. users. I don't say that there are absolutely no users who will use this feature, but I'd guess that only 10-50 users of our 3.000-8.000 users will ever use this.

> you should notify the users that Mailvelope on Firefox/Chrome is less secure

Of course this is personal opinion and not the scope of this issue, but I don't see Ferdi being responsible to inform users about protecting their privacy, just as I don't see Browsers being responsible. Ferdi is simply a productivity tool that displays services. We don't make assumptions about how users want to use their services and don't want to influence them in their doing.
Of course, protecting your own privacy is important but most users today simply are not interested in doing so.

**Comment by Nokia808** [comment]
@vantezzen 
issue113
Really excellent ! Thank you too much ! This will be more useful & of much broader scope ! Really amazing work !

**Comment by Nokia808** [comment]
@vantezzen 
Only one concern about this future feature: is it will be possible on flatpak version also ? 
Currently some functions not possible on flatpak like "autostart" due to sandbox limitation .....
I see, on FlatHub, applications like "Thunderbird" & "LibreOffice" unable for that unless by packaging a specific add-ons as flatpak packages & offering them as extensions for their targeted program, a process that not recommended due to being time & resources consuming ..... However, I see other flatpak applications, on FlatHub, able to enter to it's official add-ons page & install from them without such limitation, the most dramatic example is Firefox OFFICIAL package on FlatHub - see:

https://www.flathub.org/apps/details/org.mozilla.firefox
https://github.com/flathub/org.mozilla.Firefox.BaseApp

Please see this discussion:
https://github.com/flathub/org.mozilla.Firefox.BaseApp/pull/13
