### ISSUE TITLE
Loosing focus while typing in Ferdi >= 5.5.0-gm

### ISSUE THREAD

**Issue by PashaKagan** [getferdi/ferdi#597]
**Describe the bug**
When typing in multiple services, the window loses focus.
It happens on all screens - when logging in, when chatting on multiple services, when looking for emoji...
Happened first since upgrading 5.5.0-gm.

**To Reproduce**
Just typing, anywhere.

**Expected behavior**
The window shouldn't be losing focus.

**Desktop:**

- OS: Windows 10 64bit
- Ferdi Version 5.5.0-gm

**Comment by vantezzen** [comment]
Thank you for reporting this.
We are already discussing this issue over at #343

**Comment by PashaKagan** [comment]
@vantezzen I don't think it's a duplicate, to be honest. 
It started happening now, after upgrading to 5.5.0-gm, never happened before. 
Also, don't use Teams, don't have it installed, Logged in into the same Ferdi account, use the same services. Only change I made was to upgrade.

**Comment by basalphenaar** [comment]
I have this exact same issue after upgrading to 5.5.0-gm on macOS 10.15.4. Unfortunately the whole application is completely unusable for me at the moment.

**Comment by basalphenaar** [comment]
Just reverted back to 5.4.4-beta3, this fixed the issue for me.

**Comment by vantezzen** [comment]
Sorry, looks like this bug has the same symptoms with probably a different cause. Renaming this issue to make this more clear

**Comment by azorpax** [comment]
happening too in ubuntu 19.10

**Comment by kytwb** [comment]
Possibly fixed via https://github.com/getferdi/ferdi/pull/610, shipping in the next release 🙏

**Comment by kytwb** [comment]
Is this still the case in [v5.5.0-gm.2](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm.2)?

**Comment by basalphenaar** [comment]
This seems to have been fixed for me in v5.5.0-gm.2, thanks!

**Comment by simonghrt** [comment]
Hi, is it normal that I still encounter this issue with Ferdi 5.5.0 on macOS Catalina (v10.15.7)?
