### ISSUE TITLE
WhatsApp does not load in 5.5.0-gm

### ISSUE THREAD

**Issue by Jendker** [getferdi/ferdi#598]
**Describe the bug**
WhatsApp service only blinks "WhatsApp works only with Google Chrome 49+" in endless loop. With 5.4.3 there is no such issue.

**To Reproduce**

1. Install 5.5.0-gm on MacOS
2. Run Ferdi
3. Open WhatsApp service

**Expected behavior**
WhatsApp loads properly like in 5.4.3.

**Screenshots**

https://youtu.be/LdUtIxV9i_I

**Desktop:**

- OS: MacOS 10.15.4
- Ferdi Version 5.5.0-gm

- Server Used: https://api.getferdi.com

Debug information: https://debug.getferdi.com/35dd02af-1e79-4c25-b2ac-a8d0277aecea

**Comment by mokipedia** [comment]
Seems to be (again) a user agent problem.
find .../Ferdi/recipes/whatsapp/index.js and replace like this:
`
"use strict";

module.exports = Franz => class Messenger extends Franz {
  overrideUserAgent() {
    //return window.navigator.userAgent.replace(/(Franz|Electron)([^\s]+\s)/g, '');
    return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36";
  }

};
`

not a perfect fix but hotfixed it for me.
restart ferdi to see effect

**Comment by hiddenman** [comment]
Confirm that. After simple upgrade from previous version both Whatsapp services stopped working.

**Comment by kytwb** [comment]
@mokipedia We have identified the issue, working on it (see https://github.com/getferdi/ferdi/issues/536#issuecomment-616093384)! 🙏 
Thank you for your patience.
