### ISSUE TITLE
Teams in 5.5.0-gm do not load with default user agent

### ISSUE THREAD

**Issue by otichy** [getferdi/ferdi#599]
Opening Teams in this version loads a blank screen (even after deleting/adding service) on Win10 64bit. This worked fine in the previous version.

Changing the user agent the same way WhatsApp now requires solves the issue: https://github.com/getferdi/ferdi/issues/598

**Comment by kytwb** [comment]
Thank you for the report! 🙏 We will address this regression via https://github.com/getferdi/ferdi/issues/536.
