### ISSUE TITLE
Keep repository in sync with meetfranz/franz

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#60]
I just saw that Ferdi is with is own organization wich is great but I have a question: Will Ferdi still get merge with Franz update and be even with Franz even if it is not a "fork" in the GitHub repo?

I just wanted to know, thanks.

**Comment by kytwb** [comment]
Good point! I think we need to configure Pull properly to indicate the upstream manually now that we detached from the original repository.

**Comment by Makazzz** [comment]
Good to know!
Thanks for your work and your team.

**Comment by kytwb** [comment]
See https://github.com/wei/pull#advanced-setup-with-config

**Comment by kytwb** [comment]
Oops, went a bit too fast:

> Prerequisites
Upstream must be in the same fork network.

**Comment by Makazzz** [comment]
I just saw this but I don't know if it will work https://github.com/marketplace/actions/git-sync-action

**Comment by vantezzen** [comment]
We'll just have to make sure it only creates a PR and not force-pushes directly to the repo - that could break quite some things.

**Comment by Makazzz** [comment]
Your right that what it is saying in [GitHub Repo Sync](https://github.com/marketplace/actions/github-repo-sync#advanced-usage-sync-all-branches)

> This will force sync ALL branches to match source repo. Branches that are created only in the destination repo will not be affected but all the other branches will be hard reset to match source repo. ⚠️ This does mean if upstream ever creates a branch that shares the name, your changes will be gone.

**Comment by vantezzen** [comment]
That is to sync all branches, we only need to sync the master branch.

**Comment by Makazzz** [comment]
Oh ok good to hear.

**Comment by vantezzen** [comment]
I think we might have to fork <https://github.com/repo-sync/github-sync> and modify it so it only create a PR instead of directly merging.
@kytwb will you look into this?

**Comment by kytwb** [comment]
What about https://github.com/repo-sync/repo-sync?

**Comment by kytwb** [comment]
@vantezzen I will take a look at it tomorrow yep, signing off for today 😃 Nice going everyone!

**Comment by vantezzen** [comment]
> What about https://github.com/repo-sync/repo-sync?

Yes, doesn't work for this case but I think its best to fork this and go from there as this project already has the PR creation process right.

'till tomorrow.

**Comment by Makazzz** [comment]
Why is this removed from the To do Roadmap?

**Comment by kytwb** [comment]
@Makazzz I just followed-up in the Reddit comments of this thread sharing the link to the roadmap and thought it would be better to keep development operations outside of the roadmap for it to show only incoming enhancements. WDYT?

**Comment by Makazzz** [comment]
If it help the developpment of Ferdi it is good for me. But what is the reddit link?

**Comment by kytwb** [comment]
Edited with the missing link: https://www.reddit.com/r/opensource/comments/d6r8ma/franz_messenger_has_been_hardforked_by_the/

**Comment by kytwb** [comment]
@vantezzen I went with setting up repo-sync between getferdi/ferdi and kytwb/franz; my fork of Franz still use the pull bot to stay in sync with the upstream. WDYT?

**Comment by vantezzen** [comment]
Good idea.

**Comment by kytwb** [comment]
Moved the fork to the org instead, so repo-sync is between getferdi/franz and getferdi/ferdi now.
