### ISSUE TITLE
5.5.0: WhatsApp wants "up to date Chrome"

### ISSUE THREAD

**Issue by VOOM108** [getferdi/ferdi#601]
WhatsApp does not load, message: "please update Chrome"

### Your Environment

* Ferdi Version used: 5.5.0-gm portable
* Operating System and version: Win10, up to date

**Comment by kytwb** [comment]
@VOOM108 Thank you for the report and sorry for the inconvenience. We noticed this regression via https://github.com/getferdi/ferdi/issues/536 and are addressing it as quick as possible 🙏 Thanks for bearing with us!
