### ISSUE TITLE
Searching for a user doesnt work in Google Chat

### ISSUE THREAD

**Issue by mahadevans87** [getferdi/ferdi#621]
**Describe the bug**

Searching for a user doesn't work in Google chat  
Search for a user who is not in the cached list of Google Chat. 
**To Reproduce**

1. Go to Google Chat and search for a user using the search bar on the top left panel
2. Type in a few words and observe that no results are returned

**Expected behavior**

Matching users should be listed in the dropdown.

**Screenshots**
Look for the autocomplete requests failing in the console

![image](https://user-images.githubusercontent.com/1255523/79877346-c00ef800-8409-11ea-9340-ebd387a5b2ee.png)

Here is a response of the autocomplete request:
`{
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
`
**Desktop:**

- OS: [Windows 10]
- Ferdi Version [e.g. 5.4.3]
- Server Used: [e.g. https://api.getferdi.com]

**Comment by kytwb** [comment]
@mahadevans87 is it still happening in 5.5.0-gm?

**Comment by mahadevans87** [comment]
> 
> 
> @mahadevans87 is it still happening in 5.5.0-gm?

I can confirm this works in the latest 5.5.0-gm as well as building from the develop branch

**Comment by mahadevans87** [comment]
Have made some progress on this. Hopefully the fix should resolve all of the Google related issues

**Comment by sampathBlam** [comment]
@kytwb : Created a PR each in both ferdi as well as the recipe repo. Please review the same.
