### ISSUE TITLE
Issue with Telegram service in Ferdi 5.5.0-gm

### ISSUE THREAD

**Issue by ste7enm** [getferdi/ferdi#623]
**Describe the bug**

An update to the Telegram service was introduced in Ferdi 5.5.0-gm. With it came a totally new approach to the viewport (no longer simply replicating the web.telegram.org experience). Amongst the aesthetic differences is a forced Chat Background image. Unfortunately, the chat background that's selected does not persist through a service refresh, so unless you select Dark Mode from within the service itself (not in the service's settings, but in Telegram's settings), you get the daisy background for all of your chats every time you start the service.

**To Reproduce**

In Telegram:

- Click the menu,
- Click Settings,
- Click General Settings,
- Click Chat Background,
- Select any background, and
- Refresh your service.

Once you refresh, the background image will have reverted.

**Expected behavior**

The background image persists through reloads and app launches.

As a personal tangent, I hate that there's no theme support in whatever version this is ("Telegram Web 0.0.635, TDLib 1.6.0," according to active sessions log, compared to the previous "Telegram Web 0.7.0") but that it forces one of their backgrounds into your chats. I preferred the cleanliness of the web version.

**Desktop:**

- OS: macOS Mojave 10.14.6
- Ferdi Version Ferdi 5.5.0-gm (5.5.0-gm.1893)

**Additional context**

As mentioned in my tangent, this version of the service appears to run "Telegram Web 0.0.635, TDLib 1.6.0," compared to the previous instance, which used "Telegram Web 0.7.0."

Edit: Other elements that are similar in the app, such as the Appearance setting, where you choose light or dark theme and the accent colour, do persist on refresh.

**Comment by kytwb** [comment]
We are reverting the default Telegram client to the original one via https://github.com/getferdi/recipes/issues/128 for v5.5.0-gm.2. We will propose this new React client as Telegram React. If there is an issue with the client itself, please forward to its repository https://github.com/evgeny-nadymov/telegram-react/ 🙏 Thank you for taking the time to report.

**Comment by ste7enm** [comment]
Thanks, @kytwb – appreciate it.
