### ISSUE TITLE
Instagram desktop browser interface

### ISSUE THREAD

**Issue by misterhh** [getferdi/ferdi#624]
**Is your feature request related to a problem? Please describe.**
The current mobile-web version of instagram, especially the DMs is clunky and annoying. My main issue is that you need to click the "send" button instead of pressing enter.

**Describe the solution you'd like**
Luckily, Instagram's desktop web-app now supports DMs! The layout is a little more preferable and I can send messages with the enter key like a regular human. Seems like it's only natural to transition from the mobile-web version to the desktop version.

Love the project, thanks for all your hard work.

**Comment by kytwb** [comment]
@misterhh Thank for your feedback! We have already updated Instagram to use the official web client, so you don't have the issue with the Enter key anymore (see https://github.com/getferdi/recipes/issues/86). This is available in the [latest pre-release](https://github.com/getferdi/ferdi/releases) already and will land in the next stable one 🙏 Thank you for your patience!
