### ISSUE TITLE
`tsconfig.tsbuildinfo` files show as untracked

### ISSUE THREAD

**Issue by yourcontact** [getferdi/ferdi#626]
### Expected Behavior

Should `tsconfig.tsbuildinfo` files _not_ show as untracked (I am working on #569)? I read in another repository that is a bug (see https://github.com/aws/aws-sdk-js-v3/issues/750)

### Current Behavior

`tsconfig.tsbuildinfo` files show as untracked. 

### Screenshots (if appropriate):

<img width="540" alt="Screenshot 2020-04-22 at 14 45 02" src="https://user-images.githubusercontent.com/46404814/79986267-10d72d00-84ac-11ea-9904-791845a84ca5.png">

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Context

I am working on PR #569 and want to clear untracked files.

### Your Environment

* Ferdi Version used:
* Operating System and version:

**Comment by jeremieP** [comment]
seems already fixed ?

**Comment by yourcontact** [comment]
> seems already fixed ?

I have not worked on another PR since https://github.com/getferdi/ferdi/pull/569 unfortunately, so I don't know if that issue would replicate.

**Comment by mhatvan** [comment]
Verified that files are gitignored properly.
