### ISSUE TITLE
Launch on start registering Electron binary, not Ferdi's

### ISSUE THREAD

**Issue by deadmeu** [getferdi/ferdi#63]
**Describe the bug**
On Linux, when "Launch Ferdi on start" is enabled in the General settings, an autostart entry is added pointing to electron4, not Ferdi. Disabling the setting removes the electron4 autostart entry.

**To Reproduce**
1. Enable Launch Ferdi on start in the General Settings
2. Check your autostart entries for the addition of electron4

**Expected behavior**
An entry for Ferdi should be present, not electron4

**Screenshots**
Here is the autostart entry added, pointing to electron4:
![image](https://user-images.githubusercontent.com/12111013/65365780-a339f880-dc5f-11e9-8c52-c94b630510c5.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 5.3.4-beta.1

**Additional context**
Running KDE on Manjaro Linux.

**Comment by vantezzen** [comment]
We could see if switching from [Franz's custom package](https://github.com/meetfranz/node-auto-launch) to the [official node-auto-launch](https://github.com/Teamwork/node-auto-launch) fixes this bug.

**Comment by deadmeu** [comment]
May be related, but when hovering over the Ferdi icon in my taskbar, the dialog box lists Ferdi as being named "electron4", instead of "Ferdi". Should I raise this as a separate issue?
![image](https://user-images.githubusercontent.com/12111013/65810645-3343e900-e1f0-11e9-9c61-05c2707341a6.png)

**Comment by vantezzen** [comment]
No I think this is related. Did you installed Ferdi through the official [release packages](https://github.com/getferdi/ferdi/releases) or through something like the AUR package?

**Comment by deadmeu** [comment]
> No I think this is related. Did you installed Ferdi through the official [release packages](https://github.com/getferdi/ferdi/releases) or through something like the AUR package?

AUR package, do you think it might be the packaging? Maybe @AGCaesar can help?

**Comment by vantezzen** [comment]
Maybe. The AUR packages gets build separately from how we package Ferdi.

@AGCaesar I don't quite know what it does, but [this line in your PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ferdi-git#n42) looks like it may be causing this issue?
```
sed -i "s|\(\s\+\"electron4\":\).*,|\1 \"$electron_version\",|" package.json
```

**Comment by AGCaesar** [comment]
@deadmeu @vantezzen I created the AUR package mainly for myself to update ferdi easily... I have basically no Idea what I am doing, I copied the franz build and changed a few things... (Just to dampen expectations)
But maybe we can work out something together....
The sed command just changes the "electron" occurrences to "electron4" bevause the native electron package in arch is electron 6...

Ferdi is started using the ferdi.sh file shipped with the package and the command
"electron4 /usr/lib/ferdi/resources/app.asar "$@""  seen here:https://aur.archlinux.org/cgit/aur.git/tree/ferdi.sh?h=ferdi
 maybe the autostart function fails on this? But I am not sure how to improve this....

**Comment by vantezzen** [comment]
Oh that could be the problem: In your package, Ferdi is not really build to an application, it is only started using Electron - this is the same I do during development. When doing this, Ferdi can't properly add its branding to the application:
![Screenshot](https://user-images.githubusercontent.com/10333196/65815043-51a6e600-e1ea-11e9-9f8a-f2891a38f302.png)

It makes sense that `usr/lib/electron4` gets added as a startup item, as Ferdi is currently running over that application and simply add its current path to the startup list.
As far as I can tell, the only way to fix this is to actually build Ferdi inside the AUR package as suggested in https://wiki.archlinux.org/index.php/Electron_package_guidelines#Using_electron-builder_with_system_electron. @AGCaesar could you try to implement this that way? Maybe using https://aur.archlinux.org/packages/rocketchat-desktop/ as a template?

**Comment by AGCaesar** [comment]
I will give it a try, give me some time :) Thanks for the hints!

**Comment by AGCaesar** [comment]
I tried a lot (and actually this way I found the bug in #77 but I did not manage to create a working auto start shortcut... All examples I looked at start it similar to this: https://aur.archlinux.org/cgit/aur.git/tree/rocketchat-desktop?h=rocketchat-desktop

**Comment by kytwb** [comment]
Related: https://github.com/Teamwork/node-auto-launch/issues/48

**Comment by kytwb** [comment]
@AGCaesar can you try converting one of the DEB package into an Arch Linux package with debtap and see if that fixes the issue? (see https://github.com/helixarch/debtap)

**Comment by kytwb** [comment]
Actually, I've just added `pacman` to the list of targets for Linux builds, that might build the deliverable you need for the AUR package? Giving it a try now.

**Comment by AGCaesar** [comment]
I will wait what happens :) But I think using a deb file is possible too.

**Comment by kytwb** [comment]
Not sure why the [build](https://travis-ci.org/getferdi/ferdi/jobs/591974223#L501) is failing; please try with the deb file, for now, it should be better. Would having a `.pacman` in the releases assets help you to build the AUR package?

**Comment by kytwb** [comment]
From what I understand, the AUR package is built from the Linux unpacked version of the app and ran using the system electron; which is nice if you want to optimize things and use one electron to run all your electron apps, but then it shows the system's Electron details where you mentioned it. Need to use a packaged version of Ferdi (so it comes with its own electron) for it to be standalone and properly show Ferdi info where it should. Some of the things I just said might be inaccurate but that's my understanding of it. I also just noticed we use a hack for `isDevMode` in the `build()` of the PKGBUILD, which should not be needed and should hint us that we're doing something wrong. I have to sign off for now, but I'm happy to help at a later stage. I would be happy to pair with you on this @AGCaesar if you're keen — please reach out to amine@mouafik.fr for us to arrange the details of the pairing session.

**Comment by AGCaesar** [comment]
The dev mode hack is copied from the Franz version and is definitely still needed with ferdi. Just build it without it and it started in dev mode... I will try building a package from the deb file and report back :)

**Comment by AGCaesar** [comment]
@deadmeu I Created https://aur.archlinux.org/packages/ferdi-bin/
Now with working autostart! Please try it out and see if it works :)

**Comment by kytwb** [comment]
@AGCaesar Well done! 👍 

Regarding the previous way, I'm still confused as I see the hack as not being needed: `isDevMode` should be true in development mode, but false when we are packaging and delivering the app for production use by users. I am not sure what are all the differences between dev/prod mode in Electron internals, but building an app in dev mode then overwriting the `isDevMode` in our codebase should not be enough to get a production-ready app. If `isDevMode` is true, we should figure why and make so the build we ship to non-developers/users has `isDevMode` set to false (without us overwriting it).

**Comment by kytwb** [comment]
@AGCaesar I think ferdi-bin should be working properly now that it's based on the debian. Do you think we should deprecated ferdi-git/ferdi and redirect them to ferdi-bin? Or remove them and rename ferdi-bin to just ferdi?

**Comment by AGCaesar** [comment]
I will investigate further on the differences in build mechanism after the weekend. I think we should leave the arch packages the way they are as they follow the AUR standards. It is quite common to have different versions of a program. Maany arch users like to use the system electron package because it is more lightweigt. Also, ferdi packages are the same:
https://aur.archlinux.org/packages/?O=0&SeB=nd&K=franz&outdated=&SB=n&SO=a&PP=50&do_Search=Los

**Comment by kytwb** [comment]
@AGCaesar LGTM, did not know that was AUR standards, but now I know 😃 Thank you again for the work you're doing on maintaining the AUR packages! 🙏
