### ISSUE TITLE
Teams/Outlook - Can't log in with SAML SSO

### ISSUE THREAD

**Issue by bkhl** [getferdi/ferdi#631]
**Describe the bug**

I've added Teams and Outlook 365 as services, and for each, put in my company email to log in. This redirects to the company SAML SSO service, which is a URL something like

https://saml03.mycompany.com/adfs/ls/wia?client-request-id=081df3db-63cb-4287-9396-cd4f61100836&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAeNiNdQz0LPUYjb0M7RSMU01Tk41SzbQNUoyTNM1MbIw1b1IMUnSNTdNTTW3AEJjE7MiIS9B259lOU4ntztNnnbWP1GAw2wWI8MqRrmMk8KCYit9_ZLUxNxivdzM5KL84vy0Er3k_Fz99PwdjIxBlfMDKuYlJJMjQ1sTQ0NtBNNTRM0TVJS0nSTUq1MNY1STFMTDEwTjWzMDW7xcTv71hakmEEIvKLMqtSZzGrGBqnmRsZWiTrGiaZJ-uamBkl6VoamyfpphhZGCYaJpoYpyQmb2JmA9qYm593g5nxETNvUl6OQ1lmVRHYHRdYGF-x8HAwCjBxcCowaLAb8P1gYVzECvTSzAmb1OesmOe2INI0I7dejuEUq36QiWdAYJhzWmJUXoSbj2FuRJ5nsKtZYpKrUViyW1ZYlb5LUlCxV7qveZmjramV4QQ2tlNsTF7FH9gYO9gZdnESCI9bXCJGBkYGugYmukbqCgamVsaWVoYWUQA1&cbcxt=&username=myusername%40mycompany.com&mkt=&lc=

(I've replaced the company name with "mycompany" and my username with "myusername", and replaced some characters in the tokens. It's probably not sensitive but I thought it best to mask it as I'm not sure.)

**To Reproduce**

1. Go to "Add new service"
2. Add a Teams or Outlook 365 service (I get the exact same issue with both)
3. Open the service and put in email
4. Click "Next"

-> The web site says "Taking you to your organization's sign-in page", but then nothing happens.

Looking in the service developers tools window, there is a request to the signon URL (similar to the example above).

The request says "0b" and "pending", and nothing more happens.

**Expected behavior**

Redirection to the SAML SSH service where I can log in.

**Desktop:**

- OS: Fedora 31
- Ferdi Version: 5.4.3 (from Flathub)
- Server Used: None

**Additional context**

I would expect I need to add this URL as an allowed one for the service somehow. Apart from a full fix, pointers to where I might be able to put in an exception would be nice. I was not able to find anything like that in the settings for the services.

**Comment by kytwb** [comment]
@bkhl Thank you for the report! 🙏 Could you please share the relevant requests headers as they happen in Ferdi and in your normal browser? The goal being to find the differences like with https://github.com/getferdi/ferdi/issues/359#issuecomment-619546342

**Comment by bkhl** [comment]
Sure, here is this particular request in Chrome:

```
Request URL: https://saml03.mycompany.com/adfs/ls/wia?client-request-id=dc0756fd-ee4f-4d54-be51-fc977656c0d8&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAdNiNtQztFIxgAAjXRCpa5CWZqibnApiIYEiIS6Bv2Hsd_zfhfjuC_wzvSzswI1VjPIZJSUFxVb6-vmlJTn5-dl6-Wlpmcmpesn5ufr55Yn6OxgZLzAyrmIyNzM2NzI2NTczMbM0MjSzNDUw0UuyNEsySrRI1DU1tTTWNQGydS0NTEx1E82TkpNSjU00fcwNbjHx-zuWlmQYgYj8osyq1E9MnGn5RbnxBfnFJbOYY1wii01d850cnX2dIj2idF1SjV28ki2cK0rKQsxDM4NDvNINHC1zPYuMMjOdvFOyM33DIwz9UsJyLLxyS0tTPb3dPNyci7Ij03ycMsNTqkyyky1z8i2DzC3jE33iVzETFTKbmNmA3s3NzzvFzJZfkJqXmfKImTcpL8ehLLOqqAQUFBdYGF-xMBnw_WBhXMQKDMeQKQeb_x71d2iXzlsQIp3DcIpVPznJzzDSsyIwzSLDO82s3D-11LfQMtC01Fffy9BFO6zSzzg1v8BF2y3HMdTWwMpwAhvjBDa2F2yMH9gYO9gZdnESiohbXCJGBkZAh5voGpkrGFhaGVlYmZhHAQA1&cbcxt=&username=myusername%40mycompany.com&mkt=&lc=
Request Method: GET
Referrer Policy: strict-origin-when-cross-origin
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Host: saml03.mycompany.com
Referer: https://login.microsoftonline.com/
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: cross-site
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
```

Meanwhile, in Ferdi:

```
Request URL: https://saml03.mycompany.com/adfs/ls/wia?client-request-id=bb5bad67-84aa-4b15-a5c9-43c1484a61e7&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAdNiNtQztFIxgAAjXRCpa5CWZqibnApiIYEiIS6B9LXRu1e1iHovPel80MMr8fkqRqWMkpKCYit9_fzSkpz8_Gy9_LS0zORUYzNTveT8XP388kT9HYyMFxgZVzGZmxmbGxmbmhoYW5gYGViaGZob6BknpaUZJacm6VqmpJrrmpiYpegmGVsm6RpaGFommhkZmJinmX4i43d3LC3JMAIR-UWZVamfmDjT8oty4wvyi0tmMSe4JJc4ueU7pjs7OgUVpaRUBDsGhvpHmmUn5ZQYxYdVWRiFGvh6RlUlFYdGJDuHFURlhpY4JWV75fsFl6Wau5cF-VYYFoc4hgf5F7tEeXj4-BhmlmaYOWdUlBmmmJWZmuquYiYqgDYxswG9nJufd4qZLb8gNS8z5REzb1JejkNZZlVRCSg4LrAwvmJhMuD7wcK4iBUYnBsDWxQmeD1xm3rIZsbp-H8Mp1j1w8LStCs9IwNczIu1ywwygksr8gKd_UODjVzSKtyccn083KKyMh2dAyNNym3NrAwnsDFOYGN7wcb4gY2xg51hFycR8XGLS8TIwAjodhNdI3MFA0srYxMgigIA0&cbcxt=&username=myusername%40mycompany.com&mkt=&lc=
Request Method: GET
Referrer Policy: strict-origin-when-cross-origin
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
Connection: keep-alive
Host: saml03.mycompany.com
Referer: https://login.microsoftonline.com/
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: cross-site
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.130 Safari/537.36
```

Let me know if you want more extensive HAR logs or something like that?

**Comment by kytwb** [comment]
Via https://www.diffchecker.com/

<img width="1247" alt="Screen Shot 2020-04-27 at 10 07 19 AM" src="https://user-images.githubusercontent.com/412895/80360448-e3ed9600-886e-11ea-8a0d-4d44af5adb68.png">

I think we need to properly set `Sec-Fetch-Dest` and maybe `Sec-Fetch-User` using `modifyRequestHeaders` as it was done via https://github.com/getferdi/recipes/pull/137 for Google Hangouts.

**Comment by bkhl** [comment]
Just noticed now that Yammer also has the same issue (also a Microsoft service using the same login method).

**Comment by bkhl** [comment]
I tried this out witht this diff, running the dev version as per the README file.

```
diff --git a/uncompressed/msteams/index.js b/uncompressed/msteams/index.js
index 918b7b3..dfb1d58 100644
--- a/uncompressed/msteams/index.js
+++ b/uncompressed/msteams/index.js
@@ -1,7 +1,15 @@
 "use strict";
 
 module.exports = Franz => class MicrosoftTeams extends Franz {
+  modifyRequestHeaders() {
+      return [{
+          headers: {
+              "Sec-Fetch-Dest": "document",
+              "Sec-Fetch-User": "?1"
+          }
+      }]
+  }
   overrideUserAgent() {
     return window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \([^)]+\)/g, '');
   }
-};
\ No newline at end of file
+};
```

I can see now that it includes the added headers:

```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
Connection: keep-alive
Host: saml03.vizrt.com
Referer: https://login.microsoftonline.com/
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: cross-site
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
```

So I guess it's more complicated than just hardcoding them at least.

**Comment by kytwb** [comment]
@bkhl Thank you for giving it a try! Can you please try again removing the `overrideUserAgent` and override the user agent [like this](https://github.com/Room4O4/recipes/blob/7aba7c061da97ebc25eb1e0d6c0a80da43073541/uncompressed/whatsapp/index.js#L9) in `modifyRequestHeaders`?

**Comment by bkhl** [comment]
Tried with this content of `index.js`:

```javascript
"use strict";

module.exports = Franz => class MicrosoftTeams extends Franz {
  modifyRequestHeaders() {
      return [{
          headers: {
              "Sec-Fetch-Dest": "document",
              "Sec-Fetch-User": "?1",
              "User-Agent": window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \([^)]+\)/g,"").trim()
          }
      }]
  }
};
```

The request headers look like:

```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
Connection: keep-alive
Host: saml03.vizrt.com
Referer: https://login.microsoftonline.com/
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: cross-site
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
```

Sorry to say that gives the same behaviour.

**Comment by bkhl** [comment]
I tried it again with the most recent version of Ferdi from Flathub (5.5.0), and still see the same issue.

**Comment by jumpingmushroom** [comment]
I can confirm that this issue still exists in Ferdi 5.6.0-beta.2. Seems to be a simple window popup issue for the organizational login site.

**Comment by Catalin-Ionut** [comment]
I can confirm this issue still exists for microsoft teams. Any news on this?

**Comment by vraravam** [comment]
I have been using "Office 365 Outlook Web App" for the past week. I have also deleted the duplicate service recipes. Please upgrade to the latest nightly (in another 12 hours) or upgrade your recipe manually (can be done now itself if you know how / follow the instructions in the website).

This particular issue isn't happening for me.

**Comment by jorneilander** [comment]
> [...] Please upgrade to the latest nightly [...]

Unfortunately, no joy 😞 

![image](https://user-images.githubusercontent.com/22998183/131311850-0fa251a6-f662-44e5-9438-c10e2292b169.png)

**Comment by vraravam** [comment]
@jorneilander - I am running the following versions of the recipes (without any kind of edits):
Teams: 3.1.0
Office 365 Outlook Web App: 1.4.1

You can edit the service configuration in the GUI, scroll down, and you will find the "Recipe version" at the bottom of the page.

**Comment by jorneilander** [comment]
I'm running `1.4.1` as well according to the recipe.

**Comment by jorneilander** [comment]
Interestingly, if I add `https://outlook.office.om` inside a `Custom Website` service, it does actually allow me to sign in...

**Comment by vraravam** [comment]
Unable to reproduce on macos, with the latest ferdi nightly version. Closing the ticket.
