### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by keunes** [getferdi/ferdi#64]
The project description has https://getferdi.com listed as the website, but that site doesn't seem to work. Maybe it's only used for sync server? Would be nice to have a website, too, even if a simple one.

**Comment by vantezzen** [comment]
Thank you for your feedback. getferdi.com should normally redirect you to this. It was down for me yesterday too but works fine now. Do you still have problems?

Additionally, I am currently working on a simple landing page for getferdi.com that should showcase  this project a little better.

**Comment by Makazzz** [comment]
getferdi.com never worked for me just infinite loading page.

**Comment by vantezzen** [comment]
It looks like my Chrome still had some cache. I have now restarted and neither Chrome nor Safari can load getferdi.com. [downforeveryoneorjustme.com also says that its down](https://downforeveryoneorjustme.com/getferdi.com).

@kytwb have you changed some settings? Also, could you take a look at <https://github.com/getferdi/website>?

**Comment by kytwb** [comment]
Removed it from the description for now until we finish setting things up properly. Currently moving from Namecheap's to Cloudflare's DNS to manage the entries from there. Will close the issue once everything point back to the GitHub repositories.

**Comment by kytwb** [comment]
@vantezzen LGTM! 👍 https://getferdi.com should be back up with the actual website instead of the previous redirect to the main GitHub repository.

![Ferdi  All your services in one place   Ferdi](https://user-images.githubusercontent.com/412895/65428963-8825df00-de3f-11e9-945f-f0039d240a16.png)
