### ISSUE TITLE
Slack channel token revoked -- general question

### ISSUE THREAD

**Issue by fishcymbal** [getferdi/ferdi#642]
Didn't want to post a general question in the wrong place but couldn't be sure where was best. Tried the link to the slack channel to Franz but the token has been revoked.

Brand new to the product; had a question about service authentication before diving in -- is all messaging sent through each service's communication channel or is it routed through a 3rd party server? Is login through oauth for the most part? I understand I can set up my own account server or use the Ferdi account server, but I imagine that's more for login synchronization. Is slack communication going straight through slack, FB messenger through FB, etc? Or is it routed centrally and then forwarded? Sorry for the noob q's but trying to be safe before signing into a bunch of accounts with a new (to me) app.

TIA

**Comment by kytwb** [comment]
@fishcymbal Welcome, and thank you for asking! 🙏 

> is all messaging sent through each service's communication channel

Yes

> or is it routed through a 3rd party server? 

No

> Is login through oauth for the most part? 

I am not sure I understand this part.

> I understand I can set up my own account server or use the Ferdi account server, but I imagine that's more for login synchronization. 

An account is mainly useful if you use Ferdi on mutiple devices; it keeps your Ferdi services/settings in sync.

> Is slack communication going straight through slack, FB messenger through FB, etc? Or is it routed centrally and then forwarded? 

Yes, the _same way_ as if you were using your normal browser (Ferdi loads https://messenger.com/ for you in the [Messenger recipe](https://github.com/getferdi/recipes/blob/b7e866909a1c96be5965c57289af551869dce2aa/uncompressed/messenger/package.json#L10)).

I hope that helps! 🙌
