### ISSUE TITLE
Pasting text from clipboard into hangouts prepends it to the already existing message

### ISSUE THREAD

**Issue by BinaryShrub** [getferdi/ferdi#643]
1. Type message in hangouts
2. Paste something from your clipboard
3. See problem (text is prefixed instead of put in the correct spot)
4. Test on hangouts.google.com to see the issue does not happen there

**Screenshots**
![image](https://user-images.githubusercontent.com/10691501/80256660-ff209180-8633-11ea-8bb1-13fd81ad758a.png)
![image](https://user-images.githubusercontent.com/10691501/80256687-0f387100-8634-11ea-8192-d8be8c8e0e29.png)

**Desktop:**

- OS: macOS
- Ferdi Version Version 5.5.0-gm.2 (5.5.0-gm.2.2067)
- Server Used: none

**Comment by mahadevans87** [comment]
Have opened a PR here - https://github.com/getferdi/recipes/pull/142

![ferdi_643_fix](https://user-images.githubusercontent.com/1255523/80393597-56419300-88ce-11ea-89e7-1aa9dd1b6a14.gif)

@kytwb please review.
