### ISSUE TITLE
Dark Reader settings do not follow the accent color

### ISSUE THREAD

**Issue by Sauceee** [getferdi/ferdi#644]
**Describe the bug**

Darkreader settings do not follow the accent color.

**To Reproduce**

1. Go to Settings and set a accent color
2. Edit a service and enable dark mode
3. The dark mode settings color is not changed

**Screenshots**

![image](https://user-images.githubusercontent.com/17987941/80277547-01482600-86f0-11ea-9280-051859cd75e3.png)

**Desktop:**

- OS: Windows 10
- Ferdi Version: 5.5.0-gm.2

**Comment by sampathBlam** [comment]
@kytwb I can take this up.
