### ISSUE TITLE
Ferdi system tray icon doesn't have a name in the tooltip

### ISSUE THREAD

**Issue by baduhai** [getferdi/ferdi#647]
**Describe the bug**

Ferdi does not have a name in the system tray icon tooltip, instead shows the name "electron6"

**To Reproduce**

1. Open Ferdi.
2. Hover system tray icon.
3. See "electron6" beside Ferdi icon.

**Expected behavior**

The Ferdi name should show up.

**Screenshots**

![image](https://user-images.githubusercontent.com/31864305/80287553-4db05780-872a-11ea-82bf-c1225289507f.png)

**Desktop:**

- OS: Arch Linux (Ferdi installed with ferdi-git from AUR)
- Ferdi Version 5.5.0
- Server Used: None

**Additional context**

Using Plasma 5.18.4

**Comment by sampathBlam** [comment]
@vantezzen : Can I take this up ?
