### ISSUE TITLE
Character "&" before text in tabs

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#65]
**Describe the bug**
When installing Ferdi and launching it I can see some "&" before some text.

**To Reproduce**
1. Install Ferdi
2. Open Ferdi
3. Sign / Create account
4. See error in the top of Ferdi

**Expected behavior**
It supposed to be only File, Edit, View and not &File &Edit &View

**Screenshots**
![errorontop](https://user-images.githubusercontent.com/49844464/65427689-dce63d00-dde0-11e9-92ca-e0dd13d5cd27.PNG)
(screenshot taken in beta)

**Desktop:**
 - OS: Windows 10
 - Version: 5.3.3 and 5.3.4-beta.1

**Additional context**
The Todo tabs and windows tabs don't have this problem.

**Comment by vantezzen** [comment]
This issue got introduced through #27. The `&` [should only get used internally](https://electronjs.org/docs/api/menu#static-methods) and not get shown. Will have to see why the `&` get shown.

**Comment by Makazzz** [comment]
Thanks for the info.

**Comment by kytwb** [comment]
@rseitbekov @vantezzen found a comment stating the accelerator is different based on the platform: https://github.com/electron/electron/issues/9584#issuecomment-304050674

**Comment by vantezzen** [comment]
Hmm, but it states that `&` is the right accelerator for windows - which this issue is referencing, so it still doesn't explain it.
If we can't find a solution we can also declare the accelerator separately.

**Comment by kytwb** [comment]
Ah my bad, I don't know why I thought it was related to Ubuntu somehow 😅

**Comment by kytwb** [comment]
Not sure if related: https://github.com/meetfranz/franz/pull/1323#issuecomment-482507454

**Comment by g-ravity** [comment]
@vantezzen can i take up this issue? I would like to fix this bug for my first contribution

**Comment by vantezzen** [comment]
@g-ravity Yes, its still up for grabs.

**Comment by vantezzen** [comment]
@g-ravity Are you woking on this?

**Comment by g-ravity** [comment]
Yes, I'm working on it. I was stuck at work this week, so I wasn't able to send the PR this week. But I'll surely send a PR within next week

**Comment by vantezzen** [comment]
Ok, no problem. I just didn't want this issue to go stale.

**Comment by g-ravity** [comment]
The project is not working properly. I don't why but suddenly many errors came up when I tried to start the project. I thought I'll be able to fix the issues and work on the bug, but it took me whole day and still I couldn't figure out why the project wasn't starting. I guess I'll leave this issue for someone else, as I don't have much time to work on this now

**Comment by Makazzz** [comment]
Is even the feature of doing #27   Alt + (First letter of the tabs) is even working? If not maybe the best will be to revert the pull request that caused this and then find another way to do it this time.

**Comment by vantezzen** [comment]
> Is even the feature (#27 ) of doing Alt + (First letter of the tabs) is even working? If not maybe the best will be to revert the pull request that caused this and then find another way to do it this time.

@rseitbekov?

**Comment by Makazzz** [comment]
Ok I tested on Xubuntu 19.10 x64 and ALT+F or W etc is working and does not show "&". I think the bug happen only in Windows (and macOS X ??)

**Comment by vantezzen** [comment]
Doesn't show "&" on macOS either, just Windows.
