### ISSUE TITLE
Refactoring of Support Ferdi screen

### ISSUE THREAD

**Issue by yourcontact** [getferdi/ferdi#651]
@kytwb and I had a quick chat and thought we could do a refactoring of Support Ferdi screen. 

The screen:

<img width="1130" alt="Screenshot 2020-04-26 at 22 19 10" src="https://user-images.githubusercontent.com/46404814/80318801-e8816280-880c-11ea-8f21-2eaa1d7e783f.png">

The idea would be to improve the screen so we make it more inviting for users to support Ferdi by:
- staring the repo on GitHub;
- sharing Ferdi with friends;
- make donations via Open Collective 

@kytwb suggested we could also add thumbnails of contributors to that screen.

Let me know what you think.
I can take this as my next PR.

**Comment by yourcontact** [comment]
This is on pause. I will focus on https://github.com/getferdi/ferdi/issues/663 for now.

**Comment by yourcontact** [comment]
I am adding a requirement to this refactoring:
- implement button with a link to user-research surveys. When a user click on the button, a Ferdi-native custom window should pop-up. The window should minimize margins around the survey itself (i.e. question + answers field.)

**Comment by yourcontact** [comment]
> The idea would be to improve the screen so we make it more inviting for users to support Ferdi 

I've been thinking about how we could improve that screen. At the moment, the screen does not say much Ferdi, its ethos, its community.

There are only 2 calls to action with no explanation. 

I assume that lots of users coming to that screen know little about open source, its contributors, GitHub starts or open collective. 

I suggest we tell users a bit more about what Ferdi is about on that screen, or maybe that screen isn't the right place and this content should live in a blog post. Let me know what you think. Below is a first draft of what we could add to "Support Ferdi" to give more context to users before we _ask_ for a GitHub star, a referral, or a donation.

-----

Ferdi is an open-source and a community-lead application.

The development and maintenance of the app are done by volunteers. People who use the app like you; they maintain, fix, and improve the app in their spare time.

You can see their work on Ferdi's repository.

Support is always welcomed. You don't necessarily need to be a web developer to contribute. We also need translators, designers, and other specialties. You are also welcome to give your feedback by opening an issue on our repository; that is where the community discusses the development and maintenance of the app. You are welcome to join the conversation.

Another way to support the work of contributors and say thanks is to "star the repo." 

[GitHub star embed]

Last but not least - while most of the work is done by volunteers, there are some costs to develop, maintain, and run the app; Ferdi's main expenses are: 
- Running servers (Amazon Web Services)
- Apple certificates
- Building and testing the infrastructure

As a community, we are fully transparent on funds we collect and spend. You can see our accounts on Open Collective.

If you feel like supporting Ferdi with a donation, you can do so. It will be greatly appreciated.

[Open Collectif donation embed] or link

----

The text might be a bit long if we are to embed it on support Ferdi screen. I can always cut bits here and there. Let's iterate.

**Comment by mhatvan** [comment]
Already implemented via https://github.com/getferdi/ferdi/pull/722
