### ISSUE TITLE
The URL Linux Deb Download not working

### ISSUE THREAD

**Issue by soycamiloypunto** [getferdi/ferdi#654]
**Describe the bug**
https://github.com/getferdi/ferdi/releases/download/v5.5.0 this link not working in webpage home https://getferdi.com/

**To Reproduce**

1. Open WebPage: https://getferdi.com/
2. Click Ubuntu Deb 
3. Error no working download.

**Expected behavior**

**Screenshots**

**Desktop:**

- OS: [e.g. macOS, Windows 10 etc.]
- Ferdi Version [e.g. 5.4.3]

- Server Used: [e.g. https://api.getferdi.com]

Debug information: https://debug.getferdi.com/...

**Additional context**

**Comment by kytwb** [comment]
@soycamiloypunto We experienced some issue during the release process, this should have been fixed now 🙏 Thank you!

**Comment by kytwb** [comment]
We will consolidate and automate the release process via https://github.com/getferdi/ferdi/issues/652 to reduce mistakes in the future.

**Comment by kytwb** [comment]
@soycamiloypunto Is it working now? If not, can you share a screenshot please?

**Comment by kytwb** [comment]
Closing as @soycamiloypunto probably tried to download while the release was getting re-published.

**Comment by soycamiloypunto** [comment]
Working download deb :) thanks
