### ISSUE TITLE
Keyboard shortcut for Settings not working in 5.5.0 in Windows 10

### ISSUE THREAD

**Issue by sampathBlam** [getferdi/ferdi#655]
**Describe the bug**

The keyboard short for Settings screen `Ctrl+,` does not seem to be working.

**To Reproduce**

1. Open Ferdi
2. Press `Ctrl + ,`
3. Settings screen does not open

**Expected behavior**

Settings screen has to open on pressing `Ctrl + ,`

**Screenshots**

![image](https://user-images.githubusercontent.com/17728976/80333044-66278b80-886a-11ea-87a4-f70a2d63bbfa.png)

**Desktop:**

- OS: Windows 10
- Ferdi Version 5.5.0

- Server Used: https://api.getferdi.com

**Comment by sampathBlam** [comment]
If someone can verify if it is a bug, I can take this up.

**Comment by mahadevans87** [comment]
Yeah I can verify that it doesn't work.
