### ISSUE TITLE
Opening Settings via shortcut bypasses lock screen

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#661]
**Describe the bug**
When I saw the release of ferdi 5.5.0, it was super exciting. But, in that overlay, there was a button to click and open the settings overlay. When this was clicked, it bypassed the lock screen and opened all my services - even though I had a master password set earlier.

**To Reproduce**

1. Set a master password in ferdi
2. Close/Quit ferdi and reopen
3. While in the lock screen, without entering your password, open the settings overlay - in mac its "Cmd + ,"
4. See all the services opened without the password.

**Expected behavior**

Opening settings should NOT open all the services.

**Screenshots**

**Desktop:**

- OS: macOS
- Ferdi Version 5.5.0

- Server Used: [e.g. https://api.getferdi.com]

Debug information: https://debug.getferdi.com/...

**Additional context**

**Comment by kytwb** [comment]
@vraravam thanks for reporting, can you please share a screenshot?

**Comment by vraravam** [comment]
I tried to make a gif - but, couldn't do so. Here's the screenshot.
<img width="1792" alt="Screenshot 2020-04-28 at 6 55 02 AM" src="https://user-images.githubusercontent.com/69629/80436736-72205580-891d-11ea-80b0-908f7a0b6846.png">

This screenshot is immediately after pressing `Cmd+,` on my mac - when I am on the lock screen. As you can notice,  the services on the left nav bar (which were previously not present), are now present. one more behavior that I noticed is that, after opening with this mode, the menu bar is not longer "complete", there are missing menus - for eg the keyboard shortcuts dont work. Pressing `Cmd+Shift+L` once again, will prompt the macOS Catalina dialog to authenticate with the fingerprint reader.

**Comment by kytwb** [comment]
Thank you for the additional info, I was able to reproduce.

**Comment by kytwb** [comment]
Did the following announcement screen also bypass your lock feature? As in it showed without you having to unlock Ferdi?

<img width="1552" alt="Screen Shot 2020-04-30 at 6 31 14 PM" src="https://user-images.githubusercontent.com/412895/80747507-161f2200-8b13-11ea-9daa-ed0bd6010e8d.png">

In the screenshot above, I think Ferdi is in a locked state but somehow not showing the locked screen (Menu is showing entries as per locked state).

**Comment by vraravam** [comment]
@kytwb - I have ferdi running 100% of the time, so, I didn't notice whether this announcement-related issue came or not. Sorry.

**Comment by vraravam** [comment]
thanks @vantezzen - could you please release a new beta? I can then test the fix.

**Comment by kytwb** [comment]
@vraravam we have been working on nightly releases via https://github.com/getferdi/ferdi/issues/611. You can find them at https://github.com/getferdi/nightlies/releases 🙏
