### ISSUE TITLE
Right click seems broken 

### ISSUE THREAD

**Issue by ArthurG** [getferdi/ferdi#664]
**Describe the bug**

When I right-click in Ferdi. the menu shows up and quickly disappears. 

**To Reproduce**

1. Download latest version for Ubuntu
2. Link either Facebook Messenger or Discord Messaging service 
3. Right click on something in the Facebook Messenger WebView. 
4. Notice that the right click menu shows up and immediately disappears. 

**Expected behavior**

Should be able to see and interact w/ right click menu 

**Screenshots**
N/A 

**Desktop:**
- OS: [e.g. macOS, Windows 10 etc.]
Ubuntu 18.04
- Ferdi Version [e.g. 5.4.3]
Ferdi 5.4.3 

- Server Used: [e.g. https://api.getferdi.com]

Debug information: https://debug.getferdi.com/...

**Additional context**

**Comment by kytwb** [comment]
You indicated being on v5.4.3, can you please update to v5.5.0 and try again? We have fixed some things around the right-click context menu in the latest releases.

**Comment by ArthurG** [comment]
The update fixed the issue. Thanks!!
