### ISSUE TITLE
Enable opening links in browser instead of internal browser

### ISSUE THREAD

**Issue by nsrosenqvist** [getferdi/ferdi#666]
**Is your feature request related to a problem? Please describe.**
Now when I click links in Google Keep they always open in an internal browser which is useless since I don't have access to saved accounts and other features I use within my regular browser. Instead I'm forced to copy the link URL and paste it in the browser.

**Describe the solution you'd like**
Either an easy to find setting or open in browser by default

**Additional context**
I'm sure I've just missed a setting somewhere, but I wasn't able to find it in the settings window so either I'm just blind or it's not discoverable enough.

**Comment by kari1358** [comment]
Quote:
mundo03 commented on Apr 28, 2020
workaround: Control + click (or whatever equivalent is on osX) will open the link in a browser with no issues.

https://github.com/getferdi/ferdi/issues/321
