### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by beppe9000** [getferdi/ferdi#669]
This process using lots of ram for messenger and whatsapp... windows 10 x64

![image](https://user-images.githubusercontent.com/6625123/80471038-1ff22b00-8943-11ea-954a-f1623f3ffabf.png)

```
"C:\Users\Administrator\AppData\Local\Programs\ferdi\Ferdi.exe" --type=gpu-process --field-trial-handle=1436,16238204240825743630,1749530962674224545,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --gpu-preferences=KAAAAAAAAADgAAAwAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAACgAAAAEAAAAIAAAAAAAAAAoAAAAAAAAADAAAAAAAAAAOAAAAAAAAAAQAAAAAAAAAAAAAAAFAAAAEAAAAAAAAAAAAAAABgAAABAAAAAAAAAAAQAAAAUAAAAQAAAAAAAAAAEAAAAGAAAA --mojo-platform-channel-handle=1484 --ignored=" --type=renderer " /prefetch:2
```

**Comment by vantezzen** [comment]
Thank you for reporting this. This is a known issue that mostly lies in us using ElectronJS for Ferdi, which is known to be resource-hungry. We are still exploring new ways we can reduce RAM usage from our side over at #62

**Comment by beppe9000** [comment]
does franz also have this bug ?

**Comment by vantezzen** [comment]
This is not really a "bug". Ferdi is based on chromium, which itself is known for being resource-hungy - Franz, Rambox etc. all have to deal with the same problem.

**Comment by beppe9000** [comment]
wow I didn't know it was like that...
