### ISSUE TITLE
Add search in service feature

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#67]
https://github.com/meetfranz/franz/issues/193

**Comment by probablykasper** [comment]
@kytwb Is there any ETA for this? Has any work started on it?

**Comment by kytwb** [comment]
@probablykasper no ETA, hasn't been picked up by anyone at the moment. I will try to allocate more time to work on Ferdi in the coming days.

**Comment by vantezzen** [comment]
I would suggest using a package like <https://github.com/rhysd/electron-in-page-search>.

**Comment by vantezzen** [comment]
Added via #446 and will be shipped with the next version of Ferdi.

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.3).

**Comment by bittner** [comment]
I :heart: this feature!! :kissing_closed_eyes: :kissing_heart: 

You guys are so awesome!! :trophy:
