### ISSUE TITLE
Add Widevine DRM support

### ISSUE THREAD

**Issue by vantezzen** [getferdi/ferdi#671]
This feature request is based on a discussion over at https://github.com/meetfranz/plugins/issues/359 with @FeikoJoosten

Widevine DRM is a right management system by Google that is used by websites like Spotify or Netflix. By default, ElectronJS apps have no Widevine support and thus cannot play music on Spotify or Movies on Netflix.

Adding Widevine support isn't too easy as Google seems to be _very_ slow when it comes to distributing the production licenses needed to make the app Widevine-compatible.

There are Electron forks that have build-in Widevine support (see [CastLab DRM](https://github.com/castlabs/electron-releases)), but they do not work without such a license from Google.

Until recently, it looked like there was no chance in getting such a license but a month ago [one ElectronJS app got their license granted](https://github.com/electron/electron/issues/12427#issuecomment-603764098) and seems to be fully compatible with Widevine DRM now.

The path to getting a Widevine license/certificate is though their [Partner program](https://www.widevine.com/training).

We'll have to evaluate if the gain in functionality is worth the effort it takes to get such a certificate. That is why I created this feature request.

**Comment by FeikoJoosten** [comment]
A possible alternative would be to create a native Spotify app. But that would require a lot of work. Spotify does provide API for this.

**Comment by mitelg** [comment]
I would also love to see this :slightly_smiling_face: :+1:

**Comment by vraravam** [comment]
Please see comments in #1909
