### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by SalahAdDin** [getferdi/ferdi#677]
**Describe the bug**
After the last update, Ferdi does not open by itself at the beginning session; then, I try to open it by the terminal and I got that bug:
```
❯ ferdi
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[1]    2135 segmentation fault (core dumped)  ferdi
```
After trying it three times, Ferdi finally opens.

**To Reproduce**

1. Begin session in Manjaro Linux
2. Wait.
3. As Ferdi didn't open, open by yourself clicking in the button.
4. See how Ferdi tries to open but it closes itself immediately.
5. Go to the terminal an try to open Ferdi.
6. Get the error.
7. Try to open it some times more.
8. Finally, it will open.

I updated it by `yay`, I installed it by `yay` too.

Thanks.

**Expected behavior**

**Screenshots**

**Desktop:**

- OS: [e.g. macOS, Windows 10 etc.]
- Ferdi Version [e.g. 5.4.3]

- Server Used: [e.g. https://api.getferdi.com]

Debug information: https://debug.getferdi.com/...

**Additional context**

**Comment by danieltomasz** [comment]
I also similar error - core dump, when trying to login to Franz account
- After several times, Ferdi stopped crashing and now I can use it

**Comment by adigitoleo** [comment]
Related: #667 
Try installing the binary package `ferdi-bin`, from AUR.

**Comment by obvionaoe** [comment]
The binary package worked for me for a few hours, but after I rebooted it stopped working again

**Comment by obvionaoe** [comment]
Installing the ferdi package (not the binary but the 5.5.0-2 package) from the AUR seems to have fixed it for now, let's see if it is consistent

**Comment by obvionaoe** [comment]
It isn't, after a reboot it started crashing again

**Comment by adigitoleo** [comment]
@obvionaoe 
> The binary package worked for me for a few hours, but after I rebooted it stopped working again

Strange, for me the binary is still stable. Rebooted a couple timies to be sure. I think you were on a slightly higher Manjaro kernel, but other that that idk:

<details>
  <summary>Output of inxi -Sx</summary>
  
```
System:    Host: dell-laptop Kernel: 5.4.35-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.3.0 
           Desktop: KDE Plasma 5.18.4 Distro: Manjaro Linux 
```
</details>

**Comment by SalahAdDin** [comment]
Mine here:
```
System:    Host: joselito-asus-rog Kernel: 5.4.35-1-MANJARO x86_64 bits: 64 compiler: gcc 
           v: 9.3.0 Desktop: Deepin 15.10.1 Distro: Manjaro Linux 
```

**Comment by ChanceNCounter** [comment]
Same experience here, different kernel and DE:

```
Host: ChanceBox Kernel: 5.5.18-3-MANJARO x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: KDE Plasma 5.18.4 
           Distro: Manjaro Linux 

If I remember, I'll try it later with an older kernel and see what happens.

**Comment by Moitaeel** [comment]
Disabling systray seems to get ferdi not to segfault.

Going to ```.config/Ferdi/config/settings.json```, then changing ```enableSystemTray``` to ```false``` made Ferdi open at least.

**Comment by LuisAlaguna** [comment]
So, it seems like the problem is with the `SystemTray`.

**Comment by dpeukert** [comment]
These electron issues look like they might be related to this: https://github.com/electron/electron/issues/22137, https://github.com/electron/electron/issues/22215

**Comment by laurinneff** [comment]
I get the same issue:
```
$ inxi -Sx
System:    Host: laurin-pc Kernel: 5.6.11-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: KDE Plasma 5.18.5 
           Distro: Manjaro Linux
$ ferdi
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[1]    5198 segmentation fault (core dumped)  ferdi
```
and, like others, it works when disabling systray

**Comment by kris7t** [comment]
For me, the `ferdi 5.5.0-4` and `ferdi-git` AUR packages exit with segmentation fault, but the `ferdi-bin 5.5.0-1` package (based on the Fedora RPM) works fine. So maybe the culprit is the `electron 8.2.5-2` from Arch vs whatever Electron version is currently used for building the RPM.

**Comment by kytwb** [comment]
Would it be sensible to revert the upgrade from Electron 8.1.1 to 8.2.3 done via https://github.com/getferdi/ferdi/pull/625?

**Comment by kris7t** [comment]
@kytwb I don't think that's the correct course of action, because using an older version of Electron potentially introduces security vulnerabilities. Even then, the AUR packages are building Ferdi with the Electron installed on the system, which would likely be the latest version.

Probably it's better to work around the issue until it's fixed in upstream Electron. I gather from the Zulip commit that that the crash is caused by creating a `Tray` icon without setting its context menu immediately, although as of now I understand neither the Zulip or the Ferdi codebases well enough to grok why that's the case.

**Comment by kris7t** [comment]
This can probably be closed, right?

**Comment by adigitoleo** [comment]
My system now runs Electron v9.1.0 and I reinstalled the AUR ferdi (5.5.0-7), I have not experienced any crashes/segfaults.

**Comment by Moitaeel** [comment]
I rebuilted ferdi modifying the AUR PKGBUILD to go back to native electron (9.1.0) and it seems the segfault problem is indeed solved. 

Unrelated but as a piece of information, you might want to save some time and apply the patch by @schinfo for the [stuck loading screen](https://github.com/getferdi/ferdi/issues/786#issue-627837591) bug that still affects electron9, no noticeable problems after that.

**Comment by worldpe** [comment]
I am having this issue on NixOS.

**Comment by ChanceNCounter** [comment]
What Electron version are you guys running?

**Comment by facundoq** [comment]
I'm using the official 5.5.0 AppImage which has Electron 8.2.3, Node 12.13.0

**Comment by ChanceNCounter** [comment]
Yeap. I think you wanna file a new issue, asking for a new release. In the meantime, choose a different package. It was Electron's fault, and is resolved by running a newer version of Electron (see earlier comments)
