### ISSUE TITLE
How to setup Outlook Exchange Account?

### ISSUE THREAD

**Issue by danieltomasz** [getferdi/ferdi#679]
**Describe the bug**

After login using my organisation authorisation, I am getting the following error (not only on ferdi but on other apps too)
```
:-(
Something went wrong
We couldn't find a mailbox for this recipient. Either they don't have a mailbox or don't have a license assigned.
X-ClientId: 23497C928EB9438A88AA295F6AA59474
request-id 2ec06511-1cd1-4d2c-bfc6-0f7c37613829
X-OWA-Error Microsoft.Exchange.Clients.Owa2.Server.Core.OwaUserHasNoMailboxAndNoLicenseAssignedException
X-OWA-Version 15.20.2937.23
X-FEServer DB6PR07CA0076
X-BEServer DB6PR0902MB2072
Date:4/28/2020 11:12:20 PM
Fewer details...
 Refresh the page
```

I use owa service (Outlook Web Mail) to login into mail work mail
 https://owa.ugent.be 

(I don't even need notification, for me enough would be to log into the page)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop:**

- OS: [e.g. macOS, Windows 10 etc.]
- Ferdi Version [e.g. 5.4.3]

- Server Used: [e.g. https://api.getferdi.com]

Debug information: https://debug.getferdi.com/...

**Additional context**

**Comment by vraravam** [comment]
@danieltomasz - as you say that this is also happening in other apps other than Ferdi, I am not sure how much I can help.

But some basic troubleshooting checks:
1) Please ensure that you are using the latest service recipe. As of an hour ago, I have deleted the duplicate recipes, and the only one supported for outlook is "Office 365 Outlook Web app". If you set this one up, please ensure that you are using the latest version of the recipe from the github repo.
2) Please verify that the service in Ferdi is configured with the correct service URL.

If you do not want to mess around with manually copy-pasting the code, please upgrade to the latest nightly (another 12 hours or so), and then delete the service, and re-add the one that I specified).
Please report back as to whether this is working for you.

**Comment by vraravam** [comment]
Closing this ticket, since there's no response for the latest comment. Feel free to reopen if you have new information that can help debug. Also, please try out the latest nightlies before reopening the ticket.
