### ISSUE TITLE
Add quick switcher feature

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#68]
https://rambox.pro/#feature-details/quick_switcher

**Comment by vantezzen** [comment]
Overall functionality is implemented. The only problem is, that I cannot get the focus back to the search field when focus is inside a webview ([This is a known issue](https://github.com/electron/electron/issues/17882)).

**Comment by kytwb** [comment]
Shipped in [v5.3.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.3.4-beta.2)
