### ISSUE TITLE
CTRL+F search in service

### ISSUE THREAD

**Issue by matthieujoossen** [getferdi/ferdi#680]
Produce with Slack
**This is note the same as #432**

### Expected Behavior
Use of ctrl+f open Slack search (https://slack.com/help/articles/202528808-Search-in-Slack)

### Current Behavior
ctrl+f serach on window

### Your Environment
Ferdi version: 5.5.0 (x64)
Electron: 8.2.3
Node.js: v12.13.0
OS: Ubuntu 19.10

**Comment by kytwb** [comment]
https://github.com/getferdi/ferdi/issues/558
