### ISSUE TITLE
Tray Icon context menu missing

### ISSUE THREAD

**Issue by obvionaoe** [getferdi/ferdi#681]
**Describe the bug**
As of version 5.5.0 the tray icon context menu is missing! If you right-click the tray icon, nothing happens! Left-click to show/hide works like a charm though

**To Reproduce**
Right-click the tray icon

**Expected behavior**
When right-clicking the tray icon, a context menu should appear

**Desktop:**

- OS: Manjaro Linux kernel 5.5.19-1
- Ferdi Version 5.5.0-1 (ferdi-bin from AUR)

- Server Used: self-hosted

Debug information: can't access this because of #667

**Comment by kytwb** [comment]
Closing in favour of https://github.com/getferdi/ferdi/issues/484 🙏 
Thank you for taking the time to report your issue!
