### ISSUE TITLE
Send a message to FOSS Matchmakers 

### ISSUE THREAD

**Issue by yourcontact** [getferdi/ferdi#686]
This is a todo reminder for @yourcontact to draft a message to FOSS Matchmakers re Ferdi's volunteer needs.

https://fossresponders.discourse.group/t/foss-matchmakers-a-place-to-place-to-find-help-and-volunteer-assistance/62

<img width="721" alt="Screenshot 2020-04-29 at 21 40 38" src="https://user-images.githubusercontent.com/46404814/80639294-17dcdd00-8a62-11ea-9e33-119835d9e472.png">

cc @kytwb

**Comment by yourcontact** [comment]
@kytwb, quick follow up on our chat yesterday. I can send the info to FOSS, and coordinate. Although I need some info on the description, requirements and duration about what we need.

**Comment by vraravam** [comment]
Yes - lets please close this issue.
