### ISSUE TITLE
Cannot disable service on Mac

### ISSUE THREAD

**Issue by danieltomasz** [getferdi/ferdi#687]
**Describe the bug**

After installing latest ferdi on latest Catalina I cannot disable services (for example Trello)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop:**

- OS: [e.g. macOS, Windows 10 etc.]
- Ferdi Version [e.g. 5.4.3]

- Server Used: [e.g. https://api.getferdi.com]

Debug information: https://debug.getferdi.com/...

**Additional context**

**Comment by eleightondick** [comment]
This also seems to apply to Windows. I'm seeing the same behavior on both platforms.

**Comment by mhatvan** [comment]
I cannot reproduce this on macOS Big Sur with v5.6.1-nightly.35

Please try with: https://github.com/getferdi/nightlies/releases
