### ISSUE TITLE
Restore "Delete Service" in the sidebar services context menus

### ISSUE THREAD

**Issue by sampathBlam** [getferdi/ferdi#688]
**Is your feature request related to a problem? Please describe.**
Whenever I wish to delete a service, the first place I go to is the sidebar. I right click on the corresponding service icon on the side bar and look for the Delete Service option and get disappointed that it is not there. As a developer I have more need for deleting services and re-adding them to debug issues. I understand that only because of this, it is available in dev mode. ([commit](https://github.com/getferdi/ferdi/commit/3a5c3f016bfa20cb2b0c7108aa19350cdaec6085)). 
But it also makes sense even for a normal user of Ferdi to expect the option in the sidebar against each service. Can we please bring it back? 

@kytwb @vantezzen : I would appreciate your thoughts on this. Is there any other reason behind not enabling it for end users? 

**Describe the solution you'd like**
Enable Delete Service in Sidebar for each service.

**Comment by kytwb** [comment]
@sampathBlam I agree 👍 I don't know the reason behind https://github.com/getferdi/ferdi/commit/3a5c3f016bfa20cb2b0c7108aa19350cdaec6085.

**Comment by sampathBlam** [comment]
Okay. I can revert that change and see if it works as expected. If so, I will raise a PR.
