### ISSUE TITLE
Add adblock feature

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#69]
https://rambox.pro/#feature-details/ad_block

**Comment by vantezzen** [comment]
Good issue for Hacktoberfest if you are familiar with Electron and React.

What to do?
- Add an adblocker to the Webview that gets created inside `src/components/services/contents/ServicesWebview.js`

**Comment by vantezzen** [comment]
May be unnecessary when implementing #113

**Comment by kytwb** [comment]
Closing in favour of #113.
