### ISSUE TITLE
TodoIst failure login in Ferdi Todos

### ISSUE THREAD

**Issue by adriasole** [getferdi/ferdi#691]
![image](https://user-images.githubusercontent.com/51081289/80712664-92553d80-8af2-11ea-9adc-19350ccbc506.png)
 
When I try to acces my TodoIst account (not as a service) as the slidebar for the Ferdi Todos I can't

**Comment by kytwb** [comment]
@adriasole Sorry for the inconvenience; in the meantime, could you try logging in with your password instead of with your Google account?
