### ISSUE TITLE
Disabling hibernation does not persist after restart

### ISSUE THREAD

**Issue by dorukkarinca** [getferdi/ferdi#702]
**Describe the bug**
When you toggle "Disable hibernation" for a service, it is not persisted after you restart Ferdi.

**To Reproduce**

1. Right click on a service on the left bar and click "Edit".
2. Toggle on "Disable hibernation" and then "Save service".
3. Quit and reopen Ferdi.
4. Right click on the same service on the left bar and click "Edit".
5. Notice "Disable hibernation" is toggled off.

**Expected behavior**

It should stay toggled.

**Screenshots**

**Desktop:**

- OS: Windows 10
- Ferdi Version: 5.5.0

- Server Used: [e.g. https://api.getferdi.com]

Debug information: https://debug.getferdi.com/a96d7b6a-6db4-47f3-8a30-e0fc811fd837

**Additional context**

None.

**Comment by vantezzen** [comment]
It looks like you are using Franz's servers? Disabling hibernation for individual services is only available on Ferdi servers as Franz doesn't allow us to save additional setting

**Comment by dorukkarinca** [comment]
I thought this setting would be cached locally the same way other settings are.

**Comment by vantezzen** [comment]
No, only the global Ferdi settings are stored locally, all other settings are only stored on the server. Unfortunately the Franz servers are filtering out all settings Franz itself doesn't support, so all custom settings in Ferdi can only be saved on Ferdi servers
