### ISSUE TITLE
Custom todoist URL doesn't work after update

### ISSUE THREAD

**Issue by jbirnick** [getferdi/ferdi#703]
**Describe the bug**

For the Ferdi Todo server I have always used a custom Todoist URL, like https://todoist.com/app/#agenda%2FToday , which displays only the todos for the current day. ("Today" view) Now since I have updated yesterday, this doesn't work anymore. I can choose the Todoist-Option from the list, and this works. (but does't show the "Today" view) I can also choose "Other service" and type the general Todoist URL https://todoist.com/ and it works. (but doesn't show the "Today" view) But the custom Todo server URL https://todoist.com/app/#agenda%2FToday doesn't work in Ferdi. (But it works in a normal browser, and it show the "Today" view. And it also works in a normal Todoist Service buffer in Ferdi when you enable the navigation bar and type it in there.)

**To Reproduce**

Steps to reproduce the behavior: (you will need a Todoist-Account!)

1. Go to 'Settings' -> 'General'.
2. Click on 'Enable Ferdi Todos'.
3. Choose Todo Server 'Other service' and type in the server field: https://todoist.com/app/#agenda%2FToday
4. See that it doesn't show up.
(5. See that the same URL works in a normal browser and in a normal Ferdi Todoist-Service buffer.)

**Expected behavior**

The Todoist "Today" view should show up.

**Desktop:**

- OS: Linux (Arch)
- Ferdi Version [e.g. 5.5.0]

- Server Used: no account

Debug information: https://debug.getferdi.com/...

**Additional context**

**Comment by kytwb** [comment]
Thank you for taking the time to bring your use case to our attention 🙏 
We will look into it!

**Comment by dannyqiu** [comment]
I think the url validation logic fix in https://github.com/getferdi/ferdi/pull/695 will address this.

**Comment by jbirnick** [comment]
Thanks, I will try it out in the next release! (i am using the AUR repo)

**Comment by mhatvan** [comment]
Hey @jbirnick, is this still relevant? There were a lot of code improvements in the meantime.

**Comment by jbirnick** [comment]
I don't know, I don't use Ferdi anymore.

**Comment by mhatvan** [comment]
That's too bad, I hope you can give it another try at some point.

Closing since it was reported as fixed with https://github.com/getferdi/ferdi/pull/695
