### ISSUE TITLE
Replacing the "Change server" input with a select

### ISSUE THREAD

**Issue by saruwman** [getferdi/ferdi#706]
Replace this input with a select, where the user can choose (default) Ferdi server, Franz server or Custom server; and if Custom server is selected, then we let the user input a custom server URL. To avoid messing with the default URL.
![issue](https://user-images.githubusercontent.com/41330038/80919428-596ad200-8d59-11ea-868a-84c4461aee22.jpg)

**Comment by kytwb** [comment]
If Franz server is selected, maybe we can add a notice that not every settings offered by Ferdi will be saved (see https://github.com/getferdi/ferdi/issues/715 and #702).
