### ISSUE TITLE
Announcement screen shows on every restart

### ISSUE THREAD

**Issue by leoheck** [getferdi/ferdi#707]
One time is enough, right? Or even better, zero time. Since Ferdi is not auto upgrading and the user has to upgrade it from himself so he is aware of the new features. Using Ubuntu 20.04 
The version is 5.5.0 as you can see.

![image](https://user-images.githubusercontent.com/1277920/80926558-71991c00-8d6e-11ea-9202-127a8d78b5ac.png)

**Comment by obvionaoe** [comment]
I agree, if the auto-updater was working it would make sense! But even then I think it should only appear on the first start up

**Comment by vantezzen** [comment]
This looks to be a bug as the screen should only appear the first time after re-starting Ferdi after the upgrade

**Comment by leoheck** [comment]
I am not seeing this anymore.
