### ISSUE TITLE
Add universal dark-mode

### ISSUE THREAD

**Issue by vantezzen** [getferdi/ferdi#71]
As suggested in https://www.reddit.com/r/opensource/comments/d6r8ma/franz_messenger_has_been_hardforked_by_the/f183uw0?utm_source=share&utm_medium=web2x.

Ferdi currently relies on recipe creators to create a custom `darkmode.css` file for each service to provide a dark mode.

We could add the functionality behind the "dark reader" extension to services that don't have a `darkmode.css`.

**Comment by Gaboris** [comment]
That or if full automation isn't possible or glitchy just add a method to manage the darkmode.css within Ferdi.

Basically if it's missing allow users to create one and if there is one then display its content in an editor so that we wouldn't have to navigate the Ferdi folders and try to figure out if we messed up or if Ferdi just doesn't find it by default.

**Comment by vantezzen** [comment]
I have now implemented darkreader into Ferdi via 1eb148d. Looks good to me but needs testing via the next beta build.

**Comment by Gaboris** [comment]
Wow, that was crazy fast. :D
Was it just some kinda "plug and play" type module?

**Comment by vantezzen** [comment]
Yes, DarkReader fortunately has an [npm package](https://github.com/darkreader/darkreader#using-for-a-website) that can simply be imported in the services webview to enable Darkmode.

**Comment by AGCaesar** [comment]
I just tried it out and the new dark mode messes with the discord service. The server icons are... darker than they should be, like an additional gray overlay. See here:https://i.imgur.com/HpAZ1AP.png
Top: Ferdi Dark mode
Bottom: Normal ferdi with discord dark mode
Should be the same
Whatsapp FB and telegram look fine on first glance

**Comment by vantezzen** [comment]
@AGCaesar Thank you for your feedback. I have now created a list of websites that it should not add DarkReader to and added Discord (b3a9cf4).

**Comment by AGCaesar** [comment]
Worked perfectly! Thanks!

**Comment by kytwb** [comment]
Shipped in [v5.3.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.3.4-beta.2)

**Comment by JordyScript** [comment]
DarkReader doesn't seem to be working on Google Calendar on my installation, neither does adding content to the darkmode.css for Google Calendar help. 

Ferdi 5.4.0-beta.2
Windows 10

Should i open an issue, or is there a simple explanation?
