### ISSUE TITLE
Pop-up blocker dialog error when attempting to open links in Gmail

### ISSUE THREAD

**Issue by tnaseem** [getferdi/ferdi#721]
**Describe the bug**
Clicking on a link within an email will give the following error dialog:

> Grrr! A pop-up blocker may be preventing the application fro opening the page. If you have a pop-up blocker, try disabling it to open the window.

However, right-clicking the link and selecting 'Open Link' from the menu works fine. This has only started shipping with the latest 5.5.0 version.

**To Reproduce**

1. Open an email.
2. Click any link within the email.
4. See error.

**Expected behavior**

It should just open the link in the default browser.

**Desktop:**

- OS: Windows 10
- Ferdi Version 5.5.0 (x64)

**Screenshot**

![Snag_644753](https://user-images.githubusercontent.com/1317345/81241833-8d970900-905f-11ea-9649-6d0adbe42460.png)

**Comment by vantezzen** [comment]
Thank you for reporting this. We are already discussing this over at #321

**Comment by m-lamarre** [comment]
Any resolution on this?
Still getting this error. Not sure how I can authorize it to open links in my browser?
![Screenshot 2021-02-21 at 10 38 44 PM](https://user-images.githubusercontent.com/18417244/108637949-998c7400-7495-11eb-945e-e8bfbe3d43f4.PNG)
