### ISSUE TITLE
Question: is there a way to define an exact URL as a starting point for an app?

### ISSUE THREAD

**Issue by kapooostin** [getferdi/ferdi#723]
Given I'd like to load a Trello instance with a specific board, could I achieve it within Ferdi settings?

ATM I did it with a custom recipe, but keeping it up to date is rather awkward.

**Comment by vantezzen** [comment]
You could achieve this via a custom userscript - something like:

```JavaScript
if (window.location.pathname === "/initial/path") {
    window.location.pathname = "/new/path"
}
```

**Comment by kapooostin** [comment]
For now I changed `config.serviceURL` in `package.json`. The first time it redirects to a sign-in page and then always opens the board I need.

Do you mean `user.js`? As I can see it is the same for all instances of a service. Meantime, I want to have Trello in different workspaces with different starting boards respectively.

**Comment by vantezzen** [comment]
Yes, I mean `user.js`. You can use the `config` option there to switch to different workspaces on different service instances (see https://github.com/getferdi/ferdi/wiki/Using-user.css-and-user.js#userjs)

**Comment by kapooostin** [comment]
Sorry, but I can't find anything on workspaces on the page you linked.
These two options look interesting `hasCustomUrl` and `hasPredefinedUrl` though. I guess I'll need to check Franz docs for that.

**Comment by vantezzen** [comment]
Oh sorry, I misunderstood you there. You can only detect different instances of Trello using the `config.id`. In that case, I'd suggest creating multiple Trello instances and putting them on different Workspaces.

**Comment by kapooostin** [comment]
`hasCustomUrl` mostly solves my issue. Now I can define different url for each instance using the same recipe.

**Comment by kapooostin** [comment]
Where could I find information on `hasPredefinedUrl` option? It looks like it is defined in [src/models/Recipe.js](https://github.com/getferdi/ferdi/blob/3239172af9fb68226e1e11392b16f833b726ad72/src/models/Recipe.js#L74) but never actually used in the app.

**Comment by vantezzen** [comment]
No, its never used in the app - it's may have been an old option used in Franz 4 plugins.

**Comment by kapooostin** [comment]
ОК, @vantezzen thank you for helping me with this!

**Comment by Wiggyboy** [comment]
I need the exact same thing. Why isn't this a feature for trello boards? Or... better yet. Make every service "pick up" where last left off.

**Comment by vraravam** [comment]
`hasCustomUrl` in the recipes' `package.json` will allow the user to do this. I haven't come across examples where trello has this sub-domain-based urls (like slack has the `{teamId}.slack.com`. IF there are evidence of such a pattern being used, we can gladly turn on this feature in the main repo.
