### ISSUE TITLE
Spellckecker not working in 5.5.0

### ISSUE THREAD

**Issue by Ruffus2000** [getferdi/ferdi#726]
Spellckecker not working in 5.5.0 in any service. 

Uncaught Error: document.body is null, if you're calling this in a preload script you need to wrap it in a setTimeout
    at SpellCheckHandler.attachToInput (C:\Users\Test\AppData\Local\Programs\ferdi\resources\app.asar\node_modules\electron-spellchecker\src\spell-check-handler.js:214)
    at C:\Users\Test\AppData\Local\Programs\ferdi\resources\app.asar\webview\spellchecker.js:1

- OS:  Windows 10
- Ferdi Version [e.g. 5.5.0]
I'm using Ferdi without a server

**Comment by kytwb** [comment]
Thank you for reporting this! 🙏

**Comment by melltuga** [comment]
Any chance to toggle Spellchecker off as long as it's not working?

**Comment by mahadevans87** [comment]
@Ruffus2000 Does it happen for all services? Can you provide info on what service where you using and how to reproduce this error?

**Comment by Ruffus2000** [comment]
@mahadevans87 
That is strange, it looks like the bug is gone. I noticed the bug right after the 5.5.0 Update.  Sorry

**Comment by mahadevans87** [comment]
no problem. Let us know if this occurs again and we can reopen this issue.
