### ISSUE TITLE
A problem with the APP on Linux

### ISSUE THREAD

**Issue by felipesuri** [getferdi/ferdi#727]
For a few minutes, I have been trying to solve a problem with the application view. However, I had no return. What could be done?

![A bug](http://i.imgur.com/MGOrfx8.png)

**Comment by kytwb** [comment]
Hi @felipesuri 🙏 Thank you for taking the time to report your issue and sorry for the inconvenience. This looks like a duplicate of https://github.com/getferdi/ferdi/issues/543 so I recommend you take a look at the discussion there. Thank you!
