### ISSUE TITLE
can't reload Office 365 Outlook Web App after auto-logout, need to restart Ferdi to log back in

### ISSUE THREAD

**Issue by lebedov** [getferdi/ferdi#728]
**Describe the bug**

When reloading the Office 365 Outlook Web App after auto-logout, the service displays a web page with the following message:
```
Sorry, but we’re having trouble signing you in.
AADSTS50061: Unable to complete signout. The request was invalid.
```
I have to shutdown and restart Ferdi in order to log back in.

**To Reproduce**

1. Add Office 365 Outlook Web App as a service.
2. Login and leave Ferdi running for 24 hours.
3. One should eventually see a screen indicating that one has been logged out of Office 365.
4. Try to reload the service.

**Expected behavior**

Reloading the service should display service's login screen.

**Screenshots**

**Desktop:**

- OS: Ubuntu 18.04.4
- Ferdi Version 5.5.0 (x64)
- Server Used: I use Ferdi without an account

Debug information: https://debug.getferdi.com/b8c4835a-10ad-4610-89e6-7d1339b30ecb

**Additional context**

I haven't observed this problem when I do the equivalent of reloading the Office 365 service after auto-logout with other messaging browsers such as Rambox (0.7.5-180).

**Comment by lebedov** [comment]
This still is an issue as of today.

**Comment by michal-krasowski-red** [comment]
Again, this still is an issue as of today.

**Comment by vraravam** [comment]
I have been using outlook in the latest nightly "Office 365 Outlook Web App" **for the past week** (the others have been deleted just a couple of hours ago since they were essentially duplicates). I have not had this issue. I have just also fixed the unread message badge/count - please upgrade to the latest nightly (or at least upgrade your service recipe) and report back if this is still broken.

**Comment by vraravam** [comment]
@lebedov - have you tried with the latest nightly, and the newest version of the recipe? Closing the ticket for now, but if you can confirm that this is still happening with the latest nightly, please feel free to reopen the ticket. Please also post the versions of the recipes that you are using while doing so.
