### ISSUE TITLE
Auto-assign pull requests reviewers

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#731]
Inspired by https://github.com/apps/auto-assign; we can auto-assign pull requests to maintainers with write access so the maintainer that is available the soonest can review the pull request. It should also help with external contributors not being able to request/assign reviews.

**Comment by vantezzen** [comment]
I don't know about this one: Does that really enhance the contribution flow?

Also, I don't quite understand: Does it add people randomly or just everyone?

If it adds random contributors with write access, it could be that those are currently not available while other maintainers might be. If it just adds everyone, I don't really see the point as everyone will just get spammed with review requests and those you'll actually review can also just add themselves instead.

We already get a notification when PRs are opened and can review them if we want to. It might also stress some people that we add reviewers right after they create a PR (e.g. they might still be in progress - dot many people seem to use draft PRs for this).

**Comment by kytwb** [comment]
@vantezzen The idea was to add everyone, but the rest of your comment has convinced me this is not a good idea 🙏 Thank you for stepping in!
