### ISSUE TITLE
Iteration on boilerplates: name, titles, one-liners, and descriptions

### ISSUE THREAD

**Issue by deprecated-github-account** [getferdi/ferdi#734]
@kytwb and I had a chat about the product's [boilerplates](https://www.urbandictionary.com/define.php?term=boilerplate.)

While we are currently working on a user research campaign to improve the positioning and messaging of the product, we feel we could do a first iteration on boilerplates:

- name;
- title;
- one-liner;
- description.

I suggest we focus on trimming what no longer makes sense in the name, title, one-liner, and description for the first iteration. That means, **cutting out words** that no longer represent what the product is. As written in #663:

[<img width="672" alt="Screenshot 2020-05-11 at 08 45 38" src="https://user-images.githubusercontent.com/46404814/81531897-cf77c600-9363-11ea-94fa-4c25920cf0d2.png">](https://github.com/getferdi/ferdi/issues/663#issue-607680536)

To clarify, this is not a duplicate issue of #663.

- issue #663 now tracks the product-market-fit-indicator and jobs-to-be-done user research campaign;
- this is a first iteration on on boilerplates: name, title, one-liner, and description.

We will close this issue when we have made a first cutting-words-out iteration on boilerplates.

Items we might have to update with new boilerplates:

- [repository](https://github.com/getferdi/);
- [Twitter account](https://twitter.com/getferdi);
- [website](https://getferdi.com/);
- anywhere else?

### Name

As @kytwb mentioned, it seems that the community already adopted "Ferdi" as a name and replaced "Ferdi Messenger". As @kytwb mentioned, there are only 2 "Ferdi Messenger"  left in the codebase.

The repo, Twitter account, and website already call the product "Ferdi" (no longer "Ferdi messenger".)

### Title

Current title: "All your messaging services in one place" [website](https://getferdi.com/)

~_work in progress_~
EDIT: I made a suggestion in https://github.com/getferdi/ferdi/issues/734#issuecomment-626683948

### One-liner

Current one-liners found:
1. "Ferdi is a messaging browser that allows you to combine your favorite messaging services into one application." [website](https://getferdi.com/)
2. "Community edition of @meetfranz. Ferdi is a free messaging app for WhatsApp, Facebook Messenger, Telegram, Slack and 100+ more" [Twitter account](https://twitter.com/getferdi) and [repository](https://github.com/getferdi/).

@kytwb and I picked #1 to iterate. @kytwb suggested we can call Ferdi "a new kind of browser" - see later iterations below.

Aforementioned, I suggested the first iteration is a cutting-word-out iteration. I suggest we delete both "messaging" words from the one-liner:

- "Ferdi is a ~messaging~ browser that allows you to combine your favorite ~messaging~ services into one application."

I also feel "allows you to" is superfluous:

- "Ferdi is a browser that ~allows you to~ combine**s** your favorite services into one application."

We are going a bit further than the cutting-word-out iteration, but while we are at it, below are a few more suggestions.

Adding @kytwb's suggestion:

- "Ferdi is a _new kind of_ browser that combines your favorite services into one application."

@kytwb and I agree that "service(s)" is more of technical terms use by devs; we believe people use "apps" more commonly. Hence we suggest replacing "services" by "apps."
- "Ferdi is a new of kind browser that combines your favorite _apps_ into one application."

We now have "apps" and "application" in the same sentence, a suggestoin would be to emphasize the second by adding "single": 

- "**Ferdi is a new kind of browser that combines your favorite _apps_ into one _single_  application.**"

That is what our first iteration of our one-liner _could be_.

### Description

I am not sure we have this somewhere, that could be a longer description of what Ferdi is, one paragraph. I will work on this in the next iterations (that is for me.)  "Community edition of @meetfranz" could belong to the description.

---------------------------

That is a long description for an issue but I believe we would like to be transparent and inclusive in the development of the app by embracing asynchronous communication.

Let me know if you have suggestions on whether we should name boilerplates such as name, title, one-liner, description something else. Otherwise, suggestions welcome on all of the above.

**Comment by yourcontact** [comment]
I update the [description](https://github.com/getferdi/ferdi/issues/734#issue-615669475) with a suggestion for the title (i.e. "All your apps in one place")

**Comment by vantezzen** [comment]
I don know if "Ferdi is a new kind of browser that combines your favorite apps into one single application" now really explains the benefits of Ferdi to new users:
As a new user I might think "Yeah, but my normal browser can do that too" or I would think that Ferdi does more than it actually does in that it will combine all chats I have into a single list (we already has an E-Mail asking for that once).

I think we might also want to also add that "productivity" aspect.

Just for inspiration, here are the boilerplates from some other similar products:
Station:
"One app to rule them all" - "Station is the first smart browser for busy people. A single place for all of your web applications."
Franz:
"Get back on top of your messaging." - "Franz is your messaging app for WhatsApp, Facebook Messenger, Slack, Telegram and many many more."
Rambox:
"Boost your productivity" - "The best way to organize your workspace"
Shift:
"The workstation for productive people." - "Shift is the desktop app for streamlining your accounts, apps, and workflows"

**Comment by mahadevans87** [comment]
If I do a google search for "Single messaging app with multiple accounts" - I get the following list - 

![image](https://user-images.githubusercontent.com/1255523/81568391-52783b00-93bb-11ea-9a21-b39d494957b4.png)

Franz is 4th in the list.

OT: @vantezzen Is the getferdi website SEO optimized?

**Comment by vantezzen** [comment]
> Is the getferdi website SEO optimized?

Not really as I'm not too experienced with SEO-optimizing websites
