### ISSUE TITLE
No 'Enable Dark Mode' option appearing under Settings>Appearance

### ISSUE THREAD

**Issue by WolfonFerdi** [getferdi/ferdi#735]
Hi, new Ferdi user here. Just finished setting up with just one hiccup. I can't seem to enable a dark mode for Ferdi itself. I only have the 'Synchronize....' and '...universal dark mode' options.

![FerdiNoDark](https://user-images.githubusercontent.com/65162653/81548801-71bd9b00-93b0-11ea-9a26-4f5a3b1b4779.PNG)

I've tried running both the portable version and installation with the same options appearing.

Running Windows 10 Pro ver10.0.18363 build 18363
With Ferdi 5.5.0 (x64)

Thanks and this is by far the best software of its kind that I've tried and I've checked out quite a few by now. Hoping to help out soon when I am able. :)

**Comment by vantezzen** [comment]
Welcome to Ferdi! Can you please try disabling "Syhcronize dark mode..." first?

**Comment by sampathBlam** [comment]
@WolfonFerdi : We really appreciate your kind words.

**Enable dark mode** won't be available if **Synchronize dark mode with my OS's dark mode setting** is turned on. When **Sync..." is on, users do not need to manually enable dark mode and whatever is configured in the PC shall be synced with ferdi.

**Comment by WolfonFerdi** [comment]
@vantezzen @sampathBlam 
Oh wow. Now I feel stupid. Haha. Never even thought of disabling that one out. Thanks a lot for that! Cheers. :)
