### ISSUE TITLE
Updating doesn't appear to be working

### ISSUE THREAD

**Issue by lukefisklennon** [getferdi/ferdi#746]
**Bug description:**
Updating doesn't appear to be working. According to the [releases page](https://github.com/getferdi/ferdi/releases), the latest version is 5.5.0. I'm on 5.4.3.

**Steps to reproduce:**

1. Go to settings
2. Click "Check for updates"
3. Says "Update available downloading..." for a moment before returning back to the "Check for updates" button

**Expected behavior**
Should download and install the update, or indicate why it isn't working.

**Screenshots**

![ferdi](https://user-images.githubusercontent.com/43358885/81833158-b8fb8580-9582-11ea-904b-6d7fbcd875e2.gif)

**Environment:**

- Operating System: Windows 10 Home
- Ferdi Version: 5.4.3
- Server: Franz

**Comment by vantezzen** [comment]
Thank you for reporting this. This is an issue we already have for a longer time but can't seem to fix.
We are already discussing this issue over at #329
