### ISSUE TITLE
Unusually high data-usage

### ISSUE THREAD

**Issue by om-hb** [getferdi/ferdi#747]
**Issue description:**

I use the program GlassWire to monitor the network activities of my computer. There I noticed that Ferdi (in my case) uses _really_ high amounts of data, specifically it has a lot of incoming data. Over the course of the last month, Ferdi used a total of 40.7 GB of incoming data with usually 1.2 to 3.7 GB per day. I have just four services enabled, all of them are mainly used for texting (no video/voice calls, attachments, or similar), therefore I would not expect Ferdi to have that much incoming data.

**Screenshots**

![ferdi_data_usage](https://user-images.githubusercontent.com/49337083/81958340-2274a600-960e-11ea-9648-5d915a683fcd.png)

**Environment:**
- Operating System: Windows 10 Pro (64bit)
- Ferdi Version: 5.4.3 (x64)
- Server: https://api.franzinfra.com

**Comment by vantezzen** [comment]
Yes, you are right, that shouldn't happen!
My guess it that this is connected to the broken updater (#329). Each entry is around 155MB or 310MB (~2 * 155) which is exactly the size of the updater package. I haven't seen it downloading _this much_ data before though - normally it will stop after about 3 tries.
Can you please try disabling automatic updates in Ferdi's settings and see if that reduces the data usage?

**Comment by om-hb** [comment]
Hi @vantezzen, thank you for your fast reply! I will try that and keep you updated!

**Comment by om-hb** [comment]
Short update: Disabling automatic updates did the trick! I also discovered that the unusual behavior started the day Ferdi 5.5.0 was released. Also, as described in #329 my Ferdi can't find that update. 
I guess the easiest fix will be to simply reinstall Ferdi.

**Comment by kytwb** [comment]
@om-hb Thank you for investigating @om-hb 🙏 
Closing for now, will be addressed via https://github.com/getferdi/ferdi/issues/329.
