### ISSUE TITLE
Add hibernate feature

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#75]
https://rambox.pro/#feature-details/hibernation

**Comment by vantezzen** [comment]
I have now implemented this feature in 666ec21. The hibernation can be enabled in the settings and will kick in after 5 minutes - we need to see it this is too short.

**Comment by probablykasper** [comment]
@vantezzen Notifications still work in hibernation?

**Comment by vantezzen** [comment]
No - during hibernation the service won't be loaded and thus won't be able to send you notifications.
