### ISSUE TITLE
Drag and drop attachments to Gmail doesn't work anymore

### ISSUE THREAD

**Issue by daformat** [getferdi/ferdi#751]
**Bug description:**

Dragging attachements to gmail compose window doesn't work anymore since I upgraded to 5.5.0. The only way I can add attachments now is by clicking the 'attach' icon and navigate to the file(s) I want to attach

**Steps to reproduce:**

1. Go to Gmail
2. Click on 'Compose'
3. Try to drag attachments inside the new message from your finder / desktop
4. Impossible to correctly drop the attachment

**Expected behavior**
In previous version, you could drag and drop attachments in mails from finder / desktop without using the 'attach' icon.

**Environment:**

- Operating System: macOS Catalina
- Ferdi Version: 5.5.0.2116
- Server: Using without an account

**Comment by AlbyGNinja** [comment]
I confirm this bug presence also in windows.
Video:
[https://imgur.com/DDJtxII](https://imgur.com/DDJtxII)
[Log info here](https://debug.getferdi.com/e5570c38-2fc8-48ba-b67d-9b9451da9d6c)

**Comment by dannyqiu** [comment]
I think this is caused by using the Firefox user agent as set here: https://github.com/getferdi/ferdi/issues/264#issuecomment-567138371

I can get drag and drop to work when I remove the override in `~/Library/Application Support/FerdiDev/recipes/gmail/index.js`:

```javascript
var os = require('os')

module.exports = Franz =>
  class Gmail extends Franz {
  };
```

**Comment by daformat** [comment]
I can confirm that removing the override restores normal drag and drop behavior, it also prevents clicking on links in Gmail from trigering the 'Grrr, seems a pop-up blocker prevents...' message and  allows clicking the links to open them instead of having to right-click

**Comment by wizzor** [comment]
This issue is still present on Ferdi 5.5.0.2116 on Mac.

**Comment by sbglasius** [comment]
Also present on Ferdi 5.5.0 (x64) on Linux

**Comment by laryn** [comment]
I can confirm that https://github.com/getferdi/ferdi/issues/751#issuecomment-632972319 fixes two issues at once:

1. The drag and drop attachments to an email (and dragging images into the body of an email) as well as 
2. the left click on a link in a gmail message opening correctly in the browser instead of the popup error (eg. https://github.com/getferdi/ferdi/issues/1153 https://github.com/getferdi/ferdi/issues/1138 https://github.com/getferdi/ferdi/issues/1127 https://github.com/getferdi/ferdi/issues/1102 https://github.com/getferdi/ferdi/issues/1071 )

**Comment by nonobio** [comment]
Hi,

I have this issue since i use Ferdi. I'm actually with 5.5.0 version.

Thanks

**Comment by vraravam** [comment]
@nonobio - I use the latest version of the Ferdi nightly, and this is working without a problem.

From my `About` dialog:
Version: 5.6.0-nightly.40
Electron: 13.0.1
Chrome: 91.0.4472.69
Node.js: 14.16.0
Platform: macOS Big Sur
Arch: x64
Build date: Thu Jun 03 2021 08:22:11 GMT+0530 (India Standard Time)
Git SHA: 4cacab45

**Comment by nonobio** [comment]
Thanks :) .

Do you know when the stable release will be available ?

**Comment by vraravam** [comment]
we are racing towards that @nonobio - the remaining work is being tracked here: #1017
