### ISSUE TITLE
Threema Log-in doesn't work

### ISSUE THREAD

**Issue by Traumfaengerin** [getferdi/ferdi#752]
Dear Ferdi-Team,
I am so happy about your app, because all other all-in-one-messenger had one big bug that made the usage very annoying, and I tried A LOT. Just when I thought yours is perfect I unfortunately stumbled across the following:

**Bug description:**

When I want to login to Threema on my laptop, open threema-web on the mobile phone, the QR-Code shown in Ferdi cannot be scanned. There is no error statement or something, just nothing "happens". If I do the same procedure with other all-in-one-apps there was no problem using the same QR-Code.

**Steps to reproduce:**

1. Open Ferdi on Laptop, add Threema as Service, wait for shown QR-Code
2. Open Threema properties on mobile device, go to "Threema-web", pick small camera icon on top right
3. The camera to scan the QR-code opens, but nothing happens if you keep focussing the QR Code (but the camera/mobile phone can't be the problem, as it worked with QR Codes of other threema-web-applications, as stated above)

**Expected behavior**

It should just log in to Threema web

**Screenshots**

**Environment:**

- Operating System: Mac OS Catalina (iPhone SE and MacBook Pro Late 2013)
- Ferdi Version: Version 5.5.0 (5.5.0.2116)
- Server: Using without an Account

- Debug information:
 (if I press the publish debug information button, nothing happens)

All the best,
Laura

![photo5339457816190103144](https://user-images.githubusercontent.com/49274871/82232763-56620b00-992f-11ea-8757-08d9bf1cad14.jpg)

**Comment by vantezzen** [comment]
Hello Laura,
can you please try disabling Ferdi's dark mode and retry scanning the code? You can disable dark mode in Ferdi's settings and in the service settings.

**Comment by Traumfaengerin** [comment]
Thanks for you fast reply! yaaaay, indeed, with the bright mode it scans the code without any problems :) thank you <3
