### ISSUE TITLE
Connect Ferdi Todos to Nextcloud Notes

### ISSUE THREAD

**Issue by RoiArthurB** [getferdi/ferdi#758]
**Is your feature request related to a problem? Please describe.**
I want to connect Ferdi Todos with [Nextcloud Notes](https://apps.nextcloud.com/apps/notes) on my private instance

**Describe the solution you'd like**
Add an entry here (see screenshot) or (if it's already possible) add an explanation of the setup on Ferdi's wiki :)
![image](https://user-images.githubusercontent.com/16764085/82522546-f7c9a680-9b53-11ea-9020-63db3c0123f0.png)

**Comment by vantezzen** [comment]
You should be able to add it by choosing "Other service".

I don't think we'd add "Nextcloud Notes" to the list as you need to enter your own URL anyways - which would be the same behaviour as the "Other service" option. Or am I missing something here?

**Comment by RoiArthurB** [comment]
Oh, that feature is, technically, "just" an iframe on the side ? If yes, effectively a simple custom URL is enough :)

**Comment by vantezzen** [comment]
Yes, technically Ferdi is just a chromium-based browser. You can choose "Other service" which should add a text box below in which you can type your URL.

**Comment by RoiArthurB** [comment]
Perfectly working, thanks a lot ! 🙏
