### ISSUE TITLE
Universal Dark mode is not applied, errors out on all services

### ISSUE THREAD

**Issue by poisonborz** [getferdi/ferdi#759]
**Bug description:**
Universal Dark mode is not applied, error is shown

**Steps to reproduce:**
Ferdi 5.5, Windows
Enable dark model, load any service

```
Warning: Failed prop type: Invalid prop `isAdaptableDarkModeEnabled` of type `string` supplied to `_class2`, expected `boolean`.
```
![image](https://user-images.githubusercontent.com/1070611/82546594-9eb04180-9b58-11ea-9280-353c8c40106d.png)

### Update

While trying to recover from this, I found out that the above might not be connected (I have some installations where dark mode works). This error alone is enough for dark mode to not work 
![image](https://user-images.githubusercontent.com/1070611/82572486-aede1600-9b84-11ea-9779-56f142c5642b.png)

**Comment by mahadevans87** [comment]
Can you provide more info like what OS you were using?

**Comment by poisonborz** [comment]
Windows v1909
Both normal and portable installation
Adding darkmode.css works of course, DarkReader doesn't.
Any way I can debug this further?

**Comment by mahadevans87** [comment]
Can you provide your debug info? You can get this information here - 

![image](https://user-images.githubusercontent.com/1255523/82733974-4b471a80-9d35-11ea-9902-d9baee2414af.png)

**Comment by poisonborz** [comment]
Up until now I used the (unofficial/unsupported) PAF portable version of Ferdi. I think the issue had to do with that - although I could replicate this with normal install, after a reinstall now I can no longer. Will reopen if I see a related issue again.
