### ISSUE TITLE
Default zoom level is small and increments are huge

### ISSUE THREAD

**Issue by MatMaul** [getferdi/ferdi#760]
I am using Ferdi with Riot.
Compared to using it in a browser or in the default desktop app, the default zoom is quite smaller and barely readable.
Doing a `Zoom in` makes it huge on the contrary. The zoom step seems huge, the text is ~2 times bigger with only one increment.

This is on Fedora 32, with the Flatpak bundle, version 5.5.0.

Thanks.

**Comment by MatMaul** [comment]
I just tried with the AppImage instead, same behavior.

**Comment by vantezzen** [comment]
Weird, it should be a similar behaviour to how it is in Chrome and I havn't experiences this thus far. Do you have any special monitor configuration, e.g. a display with very high PPI or some custom setting?

**Comment by MatMaul** [comment]
Hum actually sorry you are right, I re-tested with a browser and it's the same size, just not the same as Riot Desktop, they are probably doing something there. However the increment correspond to something like 133% in the browser, and it goes from really small to huge. Any chance we get smaller increment ?

**Comment by vantezzen** [comment]
Zooming is implemented in https://github.com/getferdi/ferdi/blob/6999476b9eb71880e16b413f27a7df5bf458cd47/src/lib/Menu.js#L427-L453. We are currently using Electron's build-in zoom levels but we could switch to using custom zoom factors instead instead to change the step size (see https://www.electronjs.org/docs/api/web-frame#webframesetzoomfactorfactor).

**Comment by prediscover** [comment]
Do y'all know if there is a way to increase the text size only? and not the Page zoom size? In Facebook messenger, the button elements are HUGE but the text for me is too small. Zooming in just makes the screen too crowded. I just want bigger text.

**Comment by mhatvan** [comment]
@prediscover There is no setting exposed from the electron API to change the text size unfortunately.

Apart from that, I can take a look at modifying the default zoom factor, so we have smaller increments: https://www.electronjs.org/docs/latest/api/web-frame/#webframesetzoomfactorfactor

**Comment by pztrn** [comment]
Going to +1 this issue as separate message (apart with +1 to OP) because on my M1 MBP with screen's default resolution it's too huge and just zooming out for one level makes text painfully small to read. Using scaled resolution isn't an option due to Apple's Notes list view bug which eats constantly 60-65% of CPU (until I use default resolution or switch to gallery mode which is awful).
