### ISSUE TITLE
feature_request(ads): block advertising, prevent tracking

### ISSUE THREAD

**Issue by Kristinita** [getferdi/ferdi#764]
### 1. Summary

It would be nice, if Ferdi will block ads and prevent tracking.

### 2. Argumentation

Ad and tracking is bad. See example article:

+ [**Ads are bad, and also terrible**](https://techcrunch.com/2016/08/20/ads-are-bad-and-also-terrible/)

> People hate ads; it's just a matter of degree. We hate commercial breaks. We hate display ads. We hate billboards. We live with them, because we have no alternative, but we hate them — and ad blockers have taught us that online, we do have an alternative. We don't have to see them at all. Replacing “bad ads” with “not so bad ads” does not make the fundamental concept of advertising any more palatable.

### 3. Expected behavior

It would be nice, if Ferdi will support [**browser extensions**](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1-Extensions#small_orange_diamond-extensions-in-no-particular-order) as uBlock Origin, Privacy Badger, uMatrix and/or Decentraleyes.

### 4. Related issues

For Franz:

1. [**Ads in Outlook**](https://github.com/meetfranz/franz/issues/1356)
1. [**Feature for blocking email tracking**](https://github.com/meetfranz/franz/issues/545)

Thanks.

**Comment by Nokia808** [comment]
This - if my understanding to this issue to be request for allowing add-on - this will be available when upgrading to electron version 9 & above - see:
https://github.com/getferdi/ferdi/issues/591

**Comment by vantezzen** [comment]
We're planning on adding Chrome extension support in the future (#113). You will be able to load an adblocker extension then.
