### ISSUE TITLE
Missing Window Sizes

### ISSUE THREAD

**Issue by cihanisma** [getferdi/ferdi#766]
**Bug description:**
Ferdi is not starting with last window sizes

**Steps to reproduce:**

1. Open Ferdi
2. Maximize window
3. Quit Ferdi
4. Open again
5. Window is not maximized

**Expected behavior**
Ferdi window size and position are being remembered from last session

**Environment:**

- Operating System: Linux Mint Cinnamon
- Ferdi Version: 5.5.0
- Server: Franz

**Comment by vantezzen** [comment]
This has already been fixed via #733 and will be released in the next release of Ferdi.
