### ISSUE TITLE
Ferdi does not show services after latest commits

### ISSUE THREAD

**Issue by AGCaesar** [getferdi/ferdi#77]
Ferdi just shows a purple screen after the last I think 3 patches. I updated yesterday and it worked, today i rebuild from git and it is broken, not sure which commit could be at fault. Other users have the same Problem, see latest comment with screenshot here: https://aur.archlinux.org/packages/ferdi-git/

**Comment by AGCaesar** [comment]
I created a package for the stable releases of ferdi so users will not break their software with each risky commit :)
https://aur.archlinux.org/packages/ferdi/
At the moment  I am to lazy to also create a ferdi-beta package, maybe later :)

**Comment by vantezzen** [comment]
Can you open the developer console? If yes, could you please post a screenshot of any errors it reports?

**Comment by AGCaesar** [comment]
![20190925190653_window](https://user-images.githubusercontent.com/7844066/65623286-bb937580-dfc7-11e9-9a2b-ae8621a9a095.png)
Does this help? :)

**Comment by vantezzen** [comment]
So the commits that could have caused this issue could be 64ab923 or 666ec21.

I don't think 666ec21 adds anything that could cause this error so I suspect 64ab923.
How exactly did you rebuild the app from git? Did you only pull to an existing clone and `npm run build` or did you clone into an empty directory?
If its the first then I would suggest trying `npm rebuild` or deleting node_modules and `npm install` (https://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register).
Otherwise we'll have to see where this error comes from.

**Comment by AGCaesar** [comment]
I build it using the Arch AUR packagebuild:  https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ferdi-git
To be honest I do not really understand what happens there... but I rebuild it after leaning out all cached stuff and it still fails

**Comment by kytwb** [comment]
@AGCaesar 

> I updated yesterday and it worked, today i rebuild from git and it is broken

Even though the master branch should always be working in theory, I recommend shipping only tagged commits as they are confirmed to be working and used to generate the releases for the other platforms as you can see in the [Releases](https://github.com/getferdi/ferdi/releases) tab.

If I understand, you manually update the package for now? Do you think it's possible to automate the building/distributing process for the Arch AUR package as well?

**Comment by AGCaesar** [comment]
@kytwb  As mentioned above I created a Arch Package that only ships ferdi release versions, that should me much safer.

I do nor manually update the packe.. the way aur works is this: For the stable package I have to change the version each time it is updated, but that is easy. The git package automatically fetches the latest git version.
Each time you perform an update (yay -Syu for example, equivalent to apt-get update) the instlled version is checked and if it is outdated the new version is downloaded and build automatically after the script linked above. It is just one single command to perform for the user. Really easy :)

**Comment by kytwb** [comment]
Understood, thanks for the explanation and for maintaining the Arch Package! 😃🙏 Should we consider this issue closed now you created the stable release?

**Comment by kytwb** [comment]
Added a quick note to the README on how-to properly clone the git repository for a development build purpose (so the recipes are not missing) via https://github.com/getferdi/ferdi/commit/061d5edab7b0d330f52c3dd0dbb473e4cfa0d203. Also related to https://github.com/getferdi/ferdi/issues/70.

**Comment by AGCaesar** [comment]
I tried including git submodule update --init --recursive into the arch build but it somehow fails. I could not figure out why until now, the files get downloaded but are not included in the build it seems...
Is it easyer for you to ship the recepies in a submodule and nut just put them directly in the ferdi repo?

**Comment by kytwb** [comment]
I'm ok with @vantezzen decision of having the recipes in a submodule. Could you share some reproduction steps/logs so we can try to help troubleshoot the issue?

**Comment by AGCaesar** [comment]
is there a discord/irc server to discuss this? this might be easier to explain :)

**Comment by vantezzen** [comment]
> Is it easyer for you to ship the recepies in a submodule and nut just put them directly in the ferdi repo?

Splitting recipes into a separate repository allows Ferdi's codebase to stay cleaner and adds a better visual overview than constantly having 70+ .tar.gz files in your file tree . It also allows new recipe PRs to be directed to getferdi/recipes, keeping the PR, issue and commit list of this repository limited to the actual codebase of Ferdi - not its plugins.

**Comment by kytwb** [comment]
We don't have a Discord/IRC channel just yet; I'm happy to help in the open (here) so if other people run into the same issue, this thread can be helpful to them as well. Otherwise, if you prefer, feel free to reach out directly in private at amine@mouafik.fr and we can take it from there. Thank you! 🙏

**Comment by AGCaesar** [comment]
Ok, lets see if I can show something helpful. Not sure if you use Linux/arch
This is the install instruction used by the build script:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ferdi-git
I mainly cloned it from the franz instructions as I understand very little about any npm stuff.
Here is the output of the console while building:
https://pastebin.com/MrPbQD9h
Please excuse my horrible build folder "/home/caesar/Dokumente/Arch/aur/ferdi/ferdi-git"
I think it is worth mentioning that ferdi-git/src/ferdi/recipes is populated with the tar.gz files, buit I suspect they are somehow ignored during build? The developer console error is still the same as in the screenshot above.

**Comment by kytwb** [comment]
Maybe related to https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git_Submodules?  
They recommand:

```
  cd ferdi
  git submodule init
  git config submodule.mysubmodule.url $srcdir/mysubmodule
  git submodule update
```

Instead of:

```
  # Small patching
  cd ferdi
  git submodule update --init --recursive

```

**Comment by AGCaesar** [comment]
I tried both methods, both clone the recipes directory into src/ferdi/recipes but I still have the impression that the folder or the files inside are ignored during build

**Comment by vantezzen** [comment]
Can you try to clone the recipes repository into `src/ferdi/build/recipes`?

**Comment by AGCaesar** [comment]
Not sure how, but the recipes are also in this folder.

**Comment by vantezzen** [comment]
Yes the gulpfile copies them there.
I just thought they might not get copied there but it seems like they do.

**Comment by AGCaesar** [comment]
I now suspect the change from electron4 to electron6 in commit 742a8264f1b01137d1f23eb6876b20b8c27748b7 is the cause, not the recipes. not sure how to handle that atm...

**Comment by vantezzen** [comment]
That change originates from [PR #52](https://github.com/getferdi/ferdi/pull/52/files?file-filters%5B%5D=.json&file-filters%5B%5D=.plist#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R127), didn't even know we updated to Electron 6.

**Comment by AGCaesar** [comment]
ok, after i fixed the electron 6 compilation i get a real error with the modules I guess. Any hints what went wrong?
![20190928161108_window](https://user-images.githubusercontent.com/7844066/65817702-e4f01380-e20a-11e9-961d-f2245f8e53f9.png)

**Comment by vantezzen** [comment]
I just pushed 7040eae which should fix this problem. Can you update and try again?

**Comment by AGCaesar** [comment]
This works! Thank you :) you can close this

**Comment by vantezzen** [comment]
@AGCaesar I'd like to add your AUR package to the readme - Which package and command should I add? Which package works best?

**Comment by AGCaesar** [comment]
@vantezzen If possivle you can add the git and the binarye package.
https://aur.archlinux.org/packages/ferdi-git/  and https://aur.archlinux.org/packages/ferdi-bin/
Git uses system electron version, bin uses your debian build and extracts it to arch.
You could write something like:
"To install ferdi in Archlinux use the AUR package ferdi-git or ferdi-bin. If you use a AUR Helper e.g. yay, simply install it via 'yay -S ferdi-bin' "

Note: Ferdi-git is brocken at the moment due to the electron7 update (unless you use the old e6 version which needs some manual interverntion).

**Comment by AGCaesar** [comment]
Thanks! Mybe a littel change:

    ferdi-build: Uses a prebuild ferdi version and included electron build
    ferdi-git: Uses system preinstalled electron version
