### ISSUE TITLE
Please provide a branch in flathub for nightlies

### ISSUE THREAD

**Issue by nodens** [getferdi/ferdi#778]
I'm hit by #555, and I'd like to test the fix from #748 but I'm using the flatpak.
Any chance to make nightlies available as flatpak via a "nightly" "dev" or whatever branch on flathub ?

Thanks!

**Comment by nodens** [comment]
Hi,

@lhw maybe you could take care of this since you provide the stable via flathub ?

Or just close this if you won't. I'll live :)

Thanks !

**Comment by lhw** [comment]
Flathub only supports stable and beta builds. Nightlies are not on my list currently. I would need to implement from-source compiles first.

**Comment by nodens** [comment]
Right, thanks!
Closing, then.
