### ISSUE TITLE
Zoom doesn't work on Mac for Slack Services

### ISSUE THREAD

**Issue by dpkonofa** [getferdi/ferdi#781]
**Bug description:**
Prior to the 5.5 update, I could resize the content in Slack services using either the shortcut keys or the "Zoom In" and "Zoom Out" options in the View menu. Neither currently works.

**Steps to reproduce:**

1. Go to any Slack service
2. Place cursor in window or highlight any text
3. Go to the View menu and choose "Zoom In" or "Zoom Out"
4. The service doesn't change in any way

**Expected behavior**
Expect to be able to change the size of fonts and the general zoom level of the channel to allow it to be usable on smaller window sizes.

**Environment:**

- Operating System: macOS Catalina 10.15.4
- Ferdi Version: 5.5.0.2116
- Server: Ferdi

- Debug information:
{"host":{"platform":"darwin","release":"19.4.0","screens":[{"id":722475797,"bounds":{"x":0,"y":0,"width":1920,"height":1080},"workArea":{"x":0,"y":23,"width":1920,"height":1005},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6479, 0.3310],  [0.3200, 0.5983],  [0.1563, 0.0654]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1005},"scaleFactor":2,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":69733446,"bounds":{"x":1920,"y":0,"width":1680,"height":1050},"workArea":{"x":1920,"y":23,"width":1680,"height":1027},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6821, 0.3194],  [0.2888, 0.6710],  [0.1580, 0.0569]], transfer:0.0777*x + 0.0000 if x < 0.0450 else (0.9495*x + 0.0495)**2.3955 + 0.0003, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1680,"height":1050},"workAreaSize":{"width":1680,"height":1027},"scaleFactor":2,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"msteams","version":"1.3.2"},{"id":"slack","version":"1.0.15"},{}],"devRecipes":[],"services":[{"id":"e6b0feec-03aa-48c6-ae1e-6208e2e7d82a","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":79791209,"wasExecuted":true,"method":"getAppCacheSize"},"error":{"errno":-2,"code":"ENOENT","syscall":"lstat","path":"/Users/derekk/Library/Application Support/Ferdi/Partitions/service-e6b0feec-03aa-48c6-ae1e-6208e2e7d82a/Cache/7b09dd6c87944533_0"},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","info":["error","Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state."]},{"type":"error","info":["error","Uncaught TypeError: Cannot read property 'webview' of undefined","/Applications/Ferdi.app/Contents/Resources/app.asar/lib/Menu.js",1,7220,{}]},{"type":"error","info":["error","Uncaught TypeError: Cannot read property 'webview' of undefined","/Applications/Ferdi.app/Contents/Resources/app.asar/lib/Menu.js",1,7220,{}]}],"workspaces":[],"windowSettings":{"width":915,"height":600,"x":568,"y":237,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":true,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":"45","iconSize":"30","sentry":true,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by dpkonofa** [comment]
Two notes:

1.  I have this issue in Ferdi but not in Franz.

2.  I looked at some of the closed bugs and someone else posted this for the 5.4.1 release and it got fixed in a beta. Could it be a regression?

**Comment by dpkonofa** [comment]
This is weirding me out. If I minimize the window and then click the Ferdi icon to bring it back in focus, I can adjust the Zoom level for a few quick seconds before it stops responding to the Cmd+/-.  I can't do it quickly enough to check if the menu items work during this time period.

**Comment by mhatvan** [comment]
This was fixed in https://github.com/getferdi/ferdi/pull/1875 

I can confirm that it works as expected now since v5.6.1-nightly.52
