### ISSUE TITLE
User.js on windows not called - using version 5.5.0

### ISSUE THREAD

**Issue by tszaniszlo** [getferdi/ferdi#784]
I have addedd user.js to  service and added the first console log ,message but that is not displayed on console at all.
This is the content of my user.js

module.exports = (config, Ferdi) => {
  // Write your scripts here
  console.log("Ferdi:", Ferdi);
  Ferdi.onNotify(notification => {
	if (notification.title.includes("London"))
      notification.title = "LFX?";
    }

    return notification;

  });
}

**Comment by vantezzen** [comment]
Are you looking at the service developer console? Userscript messages will only appear there and not Ferdi's normal console.

**Comment by tszaniszlo** [comment]
you are right, this is called on startup
