### ISSUE TITLE
Frozen splash screen, unable to do anything after activating password Lock

### ISSUE THREAD

**Issue by nvuillam** [getferdi/ferdi#785]
**Bug description:**

Frozen splash screen, unable to do anything after activating password Lock

**Steps to reproduce:**

I installed Ferdi, add services ( 2 Gmails, GCalendar, LinkedIn, Slack, Workplace, Teams) then I went to settings
I activated Hibernation mode, then activated "Lock with password" option
At this point, the program started to get crazy (settings window half displayed ) so I closed the reoponed Ferdi, tu hav such result : 

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/17500430/83322453-23d1df80-a258-11ea-9168-952534e9fc70.png)

**Environment:**

- Operating System:  Windows 10
- Ferdi Version: Latest downloaded this morning (2020-05-30)
- Server:  Default

- Debug information:

**Comment by vantezzen** [comment]
Thank you for reporting this, we are sorry you're experiencing this.

This is has already been reported at #596 and you can find a temporary fix for this there.

**Comment by nvuillam** [comment]
thanks :)
