### ISSUE TITLE
whatsapp does not work with ferdi Version 5.5.1-nightly.16 (5.5.1-nightly.16.2298)

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#788]
**Bug description:**
Upgraded to Ferdi Version 5.5.1-nightly.16 (5.5.1-nightly.16.2298) - and Whatsapp stopped working.

**Steps to reproduce:**
1. Add Whatsapp as a service into a fresh install of Ferdi
2. Upgrade ferdi to the above version
3. Try to access the new WhatsApp service

**Expected behavior**
WhatsApp should work

**Screenshots**
<img width="1660" alt="Screenshot 2020-06-01 at 7 49 41 AM" src="https://user-images.githubusercontent.com/69629/83370256-789e6300-a3dc-11ea-936c-9087be2191e9.png">

**Environment:**

- Operating System: macOS Catalina 10.15.5
- Ferdi Version: Version 5.5.1-nightly.16 (5.5.1-nightly.16.2298)
- Server: Franz

- Debug information:
https://debug.getferdi.com/f5628ad8-d3dd-4d59-83ad-403b2e5c3888

**Comment by vraravam** [comment]
Did the user-agent setting change between nightlies 15 and 16? Coz v15 works flawlessly for me.

**Comment by SolarAquarion** [comment]
https://github.com/getferdi/ferdi/commit/6999476b9eb71880e16b413f27a7df5bf458cd47

**Comment by janhohner** [comment]
This is still broken for me in 5.6.0-beta.2 on pop!os 20.04 (based on Ubuntu 20.04)

**Comment by vraravam** [comment]
Same here - had to revert back to nightly 15 on mac os catalina since Whatsapp still doesn't work with 5.6.0-beta.2

**Comment by spi43984** [comment]
whatsapp web doesn't work anymore for me too with version 5.6.0-beta.2 on Ubuntu 18.04. Version 5.5.0 did work.

**Comment by vraravam** [comment]
Its been 2 months since the last nightly, and this has a workaround in that nightly, can we please get a new nightly build that fixes the issue? Or a stable build please?

**Comment by the-nic** [comment]
The default regex rule is simply broken. Obviously nobody bothered to test the regex before implementing it.

Here is a regex that is actually working:
```js
"use strict";

module.exports = (Franz) =>
  class Messenger extends Franz {
    modifyRequestHeaders() {
      return [
        {
          headers: {
            'user-agent': window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+\s*/g, "").trim(),
          },
          requestFilters: {
            urls: ['*://*/*'],
          }
        }
      ]
    }
  };
```
