### ISSUE TITLE
Sync settings (except password) with the server

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#789]
**Is your feature request related to a problem? Please describe.**
When I had to setup Ferdi on a new machine, I ended up re-configuring Ferdi by trying to remember what settings I had on the old machine that had crashed. Getting it setup just right took a few minutes and a few retries. Instead, can we move all settings (like appearance, etc - basically everything except the encrypted password) into the server-side?

**Describe the solution you'd like**
As soon as I login into my Franz account, the ferdi settings should be downloaded from the server and "applied" to the Ferdi application running locally.

**Describe alternatives you've considered**

**Additional context**

**Comment by vantezzen** [comment]
I've renamed the issue to sync the settings, not move them. It is not possible to move the settings to the server as the settings file gets used in very low layers of Ferdi and early startup stages, where a server connection isn't possible/viable yet.

**Comment by iliyang** [comment]
Thanks fro considering this! In the mean time, for keeping settings in sync manually, can you point to the relevant file(s)?

On my Mac I found the `~/Library/Application Support/Ferdi/config/` directory, but it doesn't seem to include service settings (e.g. Messenger, WhatsApp, Slack, etc.)?

**Comment by vantezzen** [comment]
@iliyang Are you using Ferdi with or without an Account?
If you use Ferdi with an account, your service settings will be stored on the server you are using. If you don't use an account, your settings will be saved in `~/Library/Application Support/Ferdi/server.sqlite`.
In eather case your service sessions and Cookies are stored inside `~/Library/Application Support/Ferdi/partitions/`

**Comment by iliyang** [comment]
Thanks @vantezzen, this helps!

So when not using an account and migrating to a new machine, do you think it's safe to just copy over the `server.sqlite` file and the `config/` directory and expect all settings to be preserved (apart from having to log into each account again, of course)?

**Comment by vantezzen** [comment]
Yes, that should be possible. I should even be able to copy your whole `Ferdi` folder, which also copies files like your service recipes and sessions over to the other machine.

**Comment by vraravam** [comment]
pinging to remove staleness
