### ISSUE TITLE
Go back and go forward still not implemented

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#79]
**Describe the bug**
The feature from [this issue](https://github.com/getferdi/ferdi/issues/39) is still not implemented in Ferdi. Not even working when using CTRL+LEFT or RIGHT and the menu "View" doesn't show the options either.

**To Reproduce**

1. Open Ferdi
2. Click on View
3. Nothing is showing about Back and Forward
4. Do CMD or CTRL+LEFT or Right while navigating in a service
5. Nothing happen

**Expected behavior**
The go back or forward feature should be doing what is this saying.

**Screenshots**
![gobackgoforward](https://user-images.githubusercontent.com/49844464/65823709-6eaed980-e229-11e9-879a-bd4d8854ef52.png)

**Desktop:**

- OS: Windows 7, 10
- Version: 5.3.4-beta.4

**Comment by vantezzen** [comment]
Oh yes, I see the problem: The buttons are currently only implemented into the Mac menu.

Should be fixed with 1168ef1.

**Comment by appel** [comment]
Sorry to reopen this closed issue, but I was wondering if there could be a way to customize these shortcuts? My brain is hardwired to use ALT+arrowkeys as that's how it works in Chrome.

**Comment by vantezzen** [comment]
@appel Not currently, but hopefully in the future: With #301 we want to make all shortcuts Ferdi uses customizable

**Comment by appel** [comment]
Excellent, thanks so much @vantezzen!
