### ISSUE TITLE
No notifications on Mac [Any Service]

### ISSUE THREAD

**Issue by wynstep** [getferdi/ferdi#791]
**Bug description:**
Cannot receive any banner with notification on Mac

**Steps to reproduce:**
Keep Ferdi running
Receive an email
Cannot see any banner appearing or Notification Center
Counter of unread messages is working JUST for gmail (no teams or outlook)
Banner is not working for ANY service

**Expected behavior**
A banner with email notification appearing

**Environment:**

- Operating System: Mac OSX Catalina 10.15.5
- Ferdi Version: 5.5.0
- Server: Ferdi

- Debug information:
[debugInfo.txt](https://github.com/getferdi/ferdi/files/4718706/debugInfo.txt)

**Comment by vantezzen** [comment]
Closing in favor of #796
