### ISSUE TITLE
Focus on quick switch

### ISSUE THREAD

**Issue by leandrogehlen** [getferdi/ferdi#799]
Is necessary move focus to search box on open quick switch.

**Comment by leandrogehlen** [comment]
I found it, maybe can solve the problem

https://github.com/electron/electron/issues/14474#issuecomment-425794480

**Comment by vantezzen** [comment]
The issue you linked doesn't cover the same problem we are experiencing here as it talk about now seeing the cursor **inside** the Webview.

This is the issue describing this the problem: https://github.com/electron/electron/issues/17882

**Comment by leandrogehlen** [comment]
@vantezzen, i don't have knownlogde about electron but some solution exists currently because 
https://getstation.com/ does it.

https://www.youtube.com/watch?v=QMXx5bDbxK8
