### ISSUE TITLE
Still need to replace leftover Franz references

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#80]
**Describe the bug**
The leftover about Franz is still in Ferdi. And [it was discussed 9 days ago](https://github.com/getferdi/ferdi/issues/59) but the build are still not changing the branding.

> "Learn more" links to https://meetfranz.com/ and not https://getferdi.com,
"Changelog" links to https://github.com/meetfranz/franz/blob/master/CHANGELOG.md and not https://github.com/getferdi/ferdi/blob/master/CHANGELOG.md,
"Support" links to https://meetfranz.com/support and not https://getferdi.com/contact,
"Terms of service" links to https://meetfranz.com/terms and not https://getferdi.com/terms,
"Privacy Statement" links to https://meetfranz.com/privacy and not https://getferdi.com/privacy.

**To Reproduce**

1. Go to "?"
2. Click on Learn more, Changelog, Support...
3. See the result in your default browser

**Expected behavior**
Its is supposed to redirecting in the Ferdi branding

**Desktop:**

- OS: Windows 7, 10
- Version: 5.3.4-beta.4

**Comment by Makazzz** [comment]
[pull request](https://github.com/getferdi/ferdi/pull/82)

**Comment by vantezzen** [comment]
Thank you for your feedback and PR.

The "Terms of service" and "Privacy Statement" should however not link to getferdi.com (these documents are only meant for the website itself, not the app), but rather be changed dynamically based on the current server you choose (as that is the terms and privacy policy you operate in). The code for this can be found in [`src/components/auth/signup.js, Line 120`](https://github.com/getferdi/ferdi/blob/7040eaeacc295b8c1b19a32ce802060279a378da/src/components/auth/Signup.js#L120), [`Line 168`](https://github.com/getferdi/ferdi/blob/7040eaeacc295b8c1b19a32ce802060279a378da/src/components/auth/Signup.js#L168) and [`Line 176`](https://github.com/getferdi/ferdi/blob/7040eaeacc295b8c1b19a32ce802060279a378da/src/components/auth/Signup.js#L176). Could you add this functionality to your PR, the I can merge.

(Also, we didn't correct the other links last time as there was no getferdi.com yet, so thank you for replacing it).

**Comment by vantezzen** [comment]
@all-contributors Please add @Makazzz for bug, code
