### ISSUE TITLE
No dark mode at all

### ISSUE THREAD

**Issue by zeeh1975** [getferdi/ferdi#801]
Recently I reinstalled Ferdi, now I've not dark mode at all whatsapp, telegram, etc. they were dark before, now activating dark mode does nothing, any idea on how to fix this or why was working before?

Ferdi ver 5.5.0 (x64)
Platform win32

**Comment by zeeh1975** [comment]
Reinstalled ver 5.5.0 and now got dark mode on Telegram, Messenger, and Skype, still no dark mode on whatsapp, reinstalled whatsapp service without any change

**Comment by zeeh1975** [comment]
Status page on whatsapp is shown in dark mode

**Comment by markgaze** [comment]
Did you fix this? I'm having the same issue after install

**Comment by zeeh1975** [comment]
Sorry still not working for me, whatsapp and telegram not respond to dark mode setting. I closed the issue because got no response and thought that I was the only one with this problem.

**Comment by markgaze** [comment]
I don't get dark mode in WhatsApp or Telegram either. Just noticed that I get dark mode in GitHub Notifications but not when I load an issue (like this one) so it's definitely intermittent!

**Comment by mahadevans87** [comment]
I shall take this issue up and investigate.

**Comment by mahadevans87** [comment]
@zeeh1975 Can you try deleting your darkmode.css file in your recipe folder in-case you haven't done that already @markgaze ? I just tried to reproduce this and I get the dark mode theme 100% of the time.

**Comment by markgaze** [comment]
Will give it a go @mahadevans87 and let you know 🙂

**Comment by markgaze** [comment]
I removed the `darkmode.css` from the `whatsapp` recipe folder and it made no difference 😕 

My Facebook Messenger and Google Calendar directories don't have `darkmode.css` in so can't do it in there unfortunately.

**Comment by markgaze** [comment]
Interestingly, I just repeatedly toggled Dark Mode on and off in the services and managed to get them to switch to dark mode... So the workaround for this might be to toggle off and back on Dark Mode in the _service_ edit menu. Would be interesting to see if this fixes it for @zeeh1975 too

**Comment by mahadevans87** [comment]
Yes. I think we shouldn't consider a darkmode.css file which is of 0 bytes. Will see if I can put up a fix for that.

**Comment by zeeh1975** [comment]
Removing the 0 bytes darkmode.css and disabling and re-enabling dark mode fix the problem on both whatsapp and telegram.

**Comment by FWDekker** [comment]
I don't have a `darkmode.css` in `%APPDATA%/Ferdi/recipes/*` and disabling and re-enabling dark mode in either the services or globally doesn't fix the issue. This issue occurs on a fresh install of Ferdi.

**Comment by markgaze** [comment]
I have a similar issue with Google Calendar still but if I disable and re-enable then right-click on the service and Reload, then it eventually switches to dark mode.

**Comment by zeeh1975** [comment]
> I don't have a `darkmode.css` in `%APPDATA%/Ferdi/recipes/*` and disabling and re-enabling dark mode in either the services or globally doesn't fix the issue. This issue occurs on a fresh install of Ferdi.

What I do was, going to configure service, on bottom has a button that says "Open darkmode.css" that opens a explorer window on service profile, there I deleted darkmode.css, then back to Ferdi, disabled dark mode and then re-enabled again.

**Comment by FWDekker** [comment]
I've completely reinstalled Ferdi and now I have a 0-byte `darkmode.css`. I've deleted it and followed @zeeh1975's steps, but Whatsapp is still not in dark mode, even after reloading the service, reloading the whole of Ferdi, restarting Ferdi, or rebooting my PC.

**Comment by patrickrushton** [comment]
New Ferdi user here, so I have a fresh install on macOS Mojave. I can't get any of the services to switch to dark mode.... Gmail, Slack, WhatsApp , Messenger, JIRA, Google Calendar - all display in the default (white bg).

**Comment by lepperm** [comment]
New Ferdi 5.5.0 user here as well, also no dark mode on any services with a fresh install. I've tried removing and re-adding services but the issue persists. No `darkmode.css` is created when toggling dark mode on or off in a service, and when "Open darkmode.css" is clicked, it creates an empty file.

**Comment by jfredsilva** [comment]
I have this issue as well. Tried every tip but nothing worked.

**Comment by jpanaro** [comment]
I fresh installed a few minutes ago for the first time and have this issue with facebook messenger. None of the tips work either

**Comment by bzsimon** [comment]
Hello for three days, the dark mode doesn't enable in two services: Slack and Telegram .. strange, tryed to reload many times without success, is there a way to force it? Thanks a lot

**Comment by bzsimon** [comment]
Ok, dark mode problem only in Telegram, I've activated the dark mode under visual menu (CTRL+ALT+D) but Telegram remains white, no dark mode... strange.

**Comment by dylan-k** [comment]
On a fresh install of 5.5. (x64), I also have a 0 byte darkmode.css file. Going to try to manually enter any defaults I might find in the repo, as a workaround. This is probably the cause of issue #158 ?

**Comment by bzsimon** [comment]
I've workaround the problem installing another telegram service: Telegram React, this one goes with daakmode without any problem.

**Comment by dylan-k** [comment]
Good to know, for telegram. A fix is still needed for this issue with several other services.

**Comment by dalekirkwood** [comment]
Hi All.

I just found this and although it is a little late to reply, if anyone is having this issue I have maybe found a fix.

OneNote wasn't working for me in dark mode, so I copied the darkmode.css from Google Calendar to OneNote then reloaded OneNote and boom!

Might work for others as well, definitely worth a try!
