### ISSUE TITLE
Regression – Google: Couldn't sign you in

### ISSUE THREAD

**Issue by BinaryShrub** [getferdi/ferdi#808]
**Screenshots**
![image](https://user-images.githubusercontent.com/10691501/84301310-6b822200-ab08-11ea-8c28-2f90517188f0.png)

**Environment:**

- Operating System: macOS Mojave
- Ferdi Version: 5.5.0
- Server: Using without an account

**Comment by mahadevans87** [comment]
@BinaryShrub can you share your Google Recipe's index.js file? It shoud look something like below
```
var os = require("os");

module.exports = (Franz) =>
  class Gmail extends Franz {
    modifyRequestHeaders() {
      return [
        {
          headers: {
            "user-agent": window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \([^)]+\)/g, "").trim(),
          },
          requestFilters: {
            urls: ["*://*/*"],
          },
        },
      ];
    }
  };

```

**Comment by CptDinosaur** [comment]
Same issue, with the above index.js file @mahadevans87 
I remember this being fixed with a change to index.js, which then had to be switched to this to fix the popup issue. Now I can't log in.

**Comment by CptDinosaur** [comment]
To log in I had to:

1. Change index.js to ```
module.exports = Franz =>
  class Gmail extends Franz {
    overrideUserAgent() {
      return "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0";
    }
  };
```
2. Delete service
3. Re-add service
4. Log in
5. Change index.js back to ```
var os = require("os");

module.exports = (Franz) =>
  class Gmail extends Franz {
    modifyRequestHeaders() {
      return [
        {
          headers: {
            "user-agent": window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \([^)]+\)/g, "").trim(),
          },
          requestFilters: {
            urls: ["*://*/*"],
          },
        },
      ];
    }
  };
``` to fix popup blocker

**Comment by mahadevans87** [comment]
@CptDinosaur what google recipe is this? Gmail?

**Comment by CptDinosaur** [comment]
Yes, gmail

**Comment by mahadevans87** [comment]
Can you help me reproduce this? For some reason, I cannot reproduce this in 5.6.0-beta.1

**Comment by CptDinosaur** [comment]
Occurs on a fresh install of 5.6.0-beta.2 with appdata/roaming/ferdi deleted when getting gmail service.
Happens after typing in email.

I'm on Windows 10 x64 build 2004

![Video](https://user-images.githubusercontent.com/26852749/85421137-fb45b880-b56b-11ea-9808-8812766723de.gif)

**Comment by mahadevans87** [comment]
Awesome. will take a look later today.

**Comment by Shankar1598** [comment]
Am still having this issue on the "Fredi Todo" section. Am not able to use Google login for any for the provided Todo services.

**Comment by therealgorgan** [comment]
This still seems to be an issue hehe I just had it happen, had to edit the recipe to resolve

**Comment by vraravam** [comment]
@therealgorgan - if you are on macos, can you please try the latest builds [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)?

IF not, please try to follow the steps [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) to upgrade the recipes alone - please respond back once you do this - and indicate whether its still recurring or not.

**Comment by therealgorgan** [comment]
I just uninstalled Ferdi and then cleared my %appdata%/Ferdi folder. Then I reinstalled, logged into my Ferdi account, and signed into all of my services again with no issue. I think I really needed to clear the Ferdi data as many uninstalls/reinstalls/change-versions did not help me but this finally did

**Comment by vraravam** [comment]
Please try with the nightly builds from [here](http://github.com/vraravam/nightlies/releases) - this exposes the ability to the user to control the user-agent via the UI as opposed to editing files in the Ferdi profile. Please do be aware of the **unsigned nature** of the builds in this repo - while we work on fixing the issue with signing of our build artifacts.

**Comment by mhatvan** [comment]
Cannot reproduce this with latest nightly, please report back if this still occurs.
