### ISSUE TITLE
I've a Yahoo Mail account. No Yahoo Mail Feature in Ferdi. How to add Yahoo mail Feature to Ferdi?

### ISSUE THREAD

**Issue by Myalternativea** [getferdi/ferdi#810]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by valentinistrate** [comment]
I would like this feature too

**Comment by vantezzen** [comment]
Yahoo mail is already implemented into Ferdi, this will be released in the next update.
