### ISSUE TITLE
Ferdi starts up blank.

### ISSUE THREAD

**Issue by gaitonde-bhau** [getferdi/ferdi#812]
**Bug description:**

When installed on Kubuntu 20.04 the installer installs it fine with one error which doesn't seem to be very serious (line 6) in log.

Installation log : - 

```
sudo dpkg -i ferdi_5.5.0_amd64.deb
(Reading database ... 251142 files and directories currently installed.)
Preparing to unpack ferdi_5.5.0_amd64.deb ...
Unpacking ferdi (5.5.0-2116) over (5.5.0-2116) ...
Setting up ferdi (5.5.0-2116) ...
Error in file "/usr/share/applications/org.kde.kdeconnect_open.desktop": "*/*" is an invalid MIME type ("*" is an unregistered media type)
Processing triggers for desktop-file-utils (0.24-1ubuntu2) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
```

**Steps to reproduce:**

1. Install Ferdi with `sudo dpkg -i ferdi_5.5.0_amd64.deb` on Kubuntu 20.04
2. Start Ferdi (preferably with terminal)
3. Ferdi starts except its completely blank. (See screenshot below)
4. See log
  ```
  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
  (node:1604376) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript  objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
  (node:1604376) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript  objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
  (node:1604376) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript  objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
  (node:1604376) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript  objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
  Starting local server on port 45569
  info: serving app on http://127.0.0.1:45569
  ```

**Expected behavior**

Ferdi should have installed and the initial screen should have popped.

**Screenshots**

![](https://i.imgur.com/CllupFa.jpg)

**Environment:**

- Operating System : 
  ```
  Distributor ID: Ubuntu
  Description:    Ubuntu 20.04 LTS
  Release:        20.04
  Codename:       focal
  ```
- Ferdi : 5.5.0
- Server : Without an account

- Debug information:

  I cannot see an option for Help > Copy/Publish Debug Information. 

  ![](https://i.imgur.com/YRzwC1x.jpg)

**Comment by gaitonde-bhau** [comment]
Removing `$HOME/.config/Ferdi` and restarting Ferdi seems to have fixed the issue. So I am closing this issue.

**Comment by chrischarles2002** [comment]
**Environment**:

Operating System :

Distributor ID: Windows
Description:    Windows 10 64-bit
Ferdi : 5.5.0

Server : With an account

Debug information:

I cannot see an option for Help > Copy/Publish Debug Information.


**_Same behavior, after enabling "Password Lock" feature.
Uninstalled app, and re-installed = behavior persists and is now unusable.
No menus accessible, even by Keyboard-shortcut, just a purple screen_**

![image](https://user-images.githubusercontent.com/16194116/86255690-6a7f6600-bb85-11ea-99db-37742f71ca48.png)
