### ISSUE TITLE
Notifications shows no content preview

### ISSUE THREAD

**Issue by zeeh1975** [getferdi/ferdi#814]
Previous notifications shows a preview of message content in whatsapp notifications, now just show the message "Notification from whatsapp"

![499RIBrG9w](https://user-images.githubusercontent.com/1238547/84398588-858a3600-abd6-11ea-858a-adebd55209a4.png)

**Comment by vantezzen** [comment]
It looks like you might have enabled "Don't show message content in notifications" in Ferdi's settings. Can you please make sure to disable that option to show message content.

**Comment by zeeh1975** [comment]
Sorry, my bad.
Didn't saw that setting, thank you
