### ISSUE TITLE
Crashing when enable password in Ferdi !

### ISSUE THREAD

**Issue by ah332m** [getferdi/ferdi#817]
**Bug description:**
< when i enable Passwords lock in ferdi it crashed and didn't work anymore  -->

**Expected behavior**
< to add password lock. >

**Environment:**

- Operating System: <windows 10 enterprise 64x -->
- Ferdi Version: <5.5.0>
- Server: < Using without an account >

- Debug information:
<
the app crashing 
>

**Comment by vantezzen** [comment]
Duplicate of #750
