### ISSUE TITLE
[MacOS] Screensaver doesn't start when Ferdi is launch

### ISSUE THREAD

**Issue by Salamafet** [getferdi/ferdi#821]
When Ferdi is launch, screensaver doesn't start. I've try to activate hibernate option with different timing in settings but nothing to do.

**Environment:**

- Operating System: **macOS Catalina 10.15.5**
- Ferdi Version: **5.5.0**
- Server: **Using without an account**

**Comment by vantezzen** [comment]
This could be a duplicate of #776 - are you using Threema?

**Comment by Salamafet** [comment]
I don't use Threema.

After many test, screensaver seems to be working sometimes. 
I watch the activity monitor. Ferdi is marked as preventing sleeping mode. I have set the hibernate of the app after 1 minute. Sometimes is works, sometimes not.

**Comment by Salamafet** [comment]
I have again disable the hibernate mode of Ferdi and now the screensaver of the mac appear correctly. I don't understand how the preventing sleeping mode of Ferdi works.

**Comment by Salamafet** [comment]
Screensaver seems to be working correctly since few days.

**Comment by Dudematters** [comment]
Have the same problem, latest MacOS, latest Ferdi. MacMini M1 does not enter sleep mode.
