### ISSUE TITLE
windows silent install possible..?

### ISSUE THREAD

**Issue by kkplein** [getferdi/ferdi#828]
Hi,

We just discovered this great piece of software! Thanks!

This is not an issue, but a question...:

Is there a silent installation switch for distribution through AD software deployment policies?

I tried /help or --help but it simply starts installing with the gui :-)

**Comment by kkplein** [comment]
Right! Works for installing!
Tried also /uninstall but it did not work.
Is there some place with docs I could check..? I feel stupid for asking these kinds of basic questions, as this is something I usually want to rtfm for :-)

**Comment by vantezzen** [comment]
Ferdi uses electron-builder to create its installer. For the answer I sent you above I Google for "electron-builder silent install" - I don't really know what other options there are.

**Comment by kkplein** [comment]
:-) Thanks anyway! Your replies here were appreciated, and making Ferdi available even more! Thanks!
