### ISSUE TITLE
Searching for repositories on GitHub clogs notifications

### ISSUE THREAD

**Issue by kittywhiskers** [getferdi/ferdi#830]
**Bug description:**

Attempting to search for repositories site-wide on GitHub results in false-positive notification detection. This remains persistent even when moving away from that page.

**Steps to reproduce:**

* Go to GitHub's "search or jump to" and type in any phrase and then search for it as *All GitHub*
* Watch the notification count reach triple digits or more

**Expected behavior**

* Notifications should not be triggered at all

**Screenshots**

![False-positive notification detection](https://user-images.githubusercontent.com/63189531/85008507-b50ee480-b17a-11ea-99fa-c845bf0eea6e.png)

![Persistence after moving to another page](https://user-images.githubusercontent.com/63189531/85008596-ceb02c00-b17a-11ea-89f4-999a0507a827.png)

**Environment:**

- Operating System: macOS Catalina 10.15.5
- Ferdi Version: Version 5.5.0 (5.5.0.2116)

**Comment by kittywhiskers** [comment]
@vantezzen, should I close the PR?

**Comment by mhatvan** [comment]
Can confirm that this still occurs with the latest release.
