### ISSUE TITLE
Skype screen sharing doesn't work

### ISSUE THREAD

**Issue by wangxpert** [getferdi/ferdi#831]
**Bug description:**
During a skype call, I can't share my screen.

**Steps to reproduce:**
Make a skype phone call first, Simply press `Share Screen` button.

**Expected behavior**
I expected it works

**Screenshots**
https://recordit.co/8DBC0MBWPK

**Environment:**

- Operating System: MacOS Catalina
- Ferdi Version: Version 5.5.0 (5.5.0.2116)
- Server: Ferdi

- Debug information:

**Comment by martinszy** [comment]
This happens in jitsi screen sharing too. It's related to how electron apps are sandboxed, but I hope it can be fixed. Probably a duplicate of #463

**Comment by tux255** [comment]
I am having same issue on MacOS Catalina. 

Ferdi can not share screen in Skype and Slack.

**Comment by gvannoye** [comment]
Hi, I'm having the same issue on archlinux. Does anyone have an idea what I could look into in order to try and fix it?

**Comment by kris7t** [comment]
You should try running the latest beta, which should have fixed screensharing.

**Comment by gvannoye** [comment]
Thank you, it is indeed working on the 5.6.0-nightly.
