### ISSUE TITLE
Hi! Amazing work and highly appreciated! I even translated some code for your app in Italian :)

### ISSUE THREAD

**Issue by Ziomike98** [getferdi/ferdi#835]
Hi! Amazing work and highly appreciated! I even translated some code for your app in Italian :) 

Here are a few suggestions:

- Telegram is really bad looking right now, I can't even take a photo with my PC camera nor view the photos, links or documents sent in a chat.
- Add the respond option from the notifications, otherwise I have to switch to the app continuously 

- Google Drive will give me an error when logging in, not permitting me to use it.

Again, amazing work, keep it up and add more features without crunch time, give yourself a pat as it's really good!

If I can I will donate some money :)

**Comment by Ziomike98** [comment]
Found some other Telegram features that are a MUST for this great app:

- Pin message;
- Pin message and alert others.

**Comment by vraravam** [comment]
@Ziomike98 - while reviewing the tickets, I came across your ticket.

Is this still a valid issue? 
btw - we recommend using the `telegram-react` service recipe as opposed to the `telegram` one. We seem to find too many issues that are outside of our control and thus have come to this decision.

**Comment by mhatvan** [comment]
I think most of the listed issues are either fixed or outside our control. 

Please file a separate issue with a single actionable item in case there are more bug fixes / feature requests to do.
