### ISSUE TITLE
Custom Service for E-commerce seller center

### ISSUE THREAD

**Issue by YuHengKit** [getferdi/ferdi#836]
We are running e-commerce on Lazada, Shopee and so on.
Appreciate if can add this feature so we can centralize our customer service in one platform.
Trying to add "Custom Service" but the website (https://sellercenter.lazada.com.my/) detect Ferdi as a robot and cannot bypass the CAPTCHA.
Thank you.

**Comment by vantezzen** [comment]
Sorry, but there is nothing we can so when your Service detects Ferdi as a bot. Ferdi is a normal chromium-based Browser.
If you have Problems with a Service falsely flagging Ferdi, please contact the Service's Support.
