### ISSUE TITLE
Google Meet not working

### ISSUE THREAD

**Issue by yann-soubeyrand** [getferdi/ferdi#837]
**Bug description:**

When trying to join a new meeting in Google Meet, I get an error saying that the video cannot be started due to an error.

**Steps to reproduce:**

1. Add a Google Meet service.
2. Login with your Google account.
3. Click on the button to join a meeting, leave the room name empty and click on continue.
4. See the error.

**Expected behavior**

A meeting room should be joined.

**Screenshots**

![Capture d’écran de 2020-06-20 21-18-27](https://user-images.githubusercontent.com/8511577/85209880-c521f200-b33b-11ea-8965-2260dfde1edc.png)

**Environment:**

- Operating System: Fedora 32
- Ferdi Version: 5.5.0
- Server: Ferdi

- Debug information:

https://debug.getferdi.com/65461606-d5eb-4223-bb3d-2832377498f9

**Comment by mahadevans87** [comment]
@yann-soubeyrand - A fix has been put up in the recipes for this issue. Until then open your Google Meet recipe's index.js and replace it with the following piece of code and restart Ferdi
```
var os = require("os");

module.exports = (Franz) =>
  class Gmail extends Franz {
    modifyRequestHeaders() {
      return [
        {
          headers: {
            "user-agent": window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \([^)]+\)/g, "").trim(),
          },
          requestFilters: {
            urls: ["*://*/*"],
          },
        },
      ];
    }
  };

```

**Comment by yann-soubeyrand** [comment]
Hi @mahadevans87, thanks for your answer. However it doesn't work for me, but adding `.replace(/Ubuntu/, "Fedora")` before `.trim()` (I'm on Fedora) does the trick.

**Comment by kris7t** [comment]
@mahadevans87 Btw, what is the difference between using `modifyRequestHeaders` this way vs `overrideUserAgent`?

**Comment by mahadevans87** [comment]
@kris7t  overrideUserAgent is called on a webview when the window initially loads up. But modifyRequestHeaders will send the user-agent to each and every request that we specify in the requestFilters

**Comment by yann-soubeyrand** [comment]
@mahadevans87 the following is working for me (not sure which is better between overrideUserAgent and modifyRequestHeaders but based on what you said, I guess the former doesn't imply modifying each request and is thus better)
```
var os = require('os')

module.exports = Franz =>
  class Gmail extends Franz {
    overrideUserAgent() {
        return window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \([^)]+\)/g, "").replace(/Ubuntu/, "Fedora").trim();
    }
  };
```

**Comment by saimonefcs** [comment]
Also on **Ubuntu 20.04 LTS** is not working with the same behavior.

**Comment by hebinzin** [comment]
Hi there. I have the same here and the recipe solution didn't work. I'm running the appimage release of Ferdi 5.5.0 on Arch Linux.

**Comment by philwronski** [comment]
> Hi there. I have the same here and the recipe solution didn't work. I'm running the appimage release of Ferdi 5.5.0 on Arch Linux.

1. Add an `alert(window.navigator.userAgent)` before return in `overrideUserAgent` methode.
2. Replace ubunthu with your OS. (use `return window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \([^)]+\)/g, "").replace(/Ubuntu/, <your Os here>).trim();`
3. Restart Ferdi

Work for me, i'm on Manjaro (Arch Linux base)

**Comment by hebinzin** [comment]
@philwronski Thank you, but I couldn't make it work yet. My index.js is a little different than the examples here so I couldn't figure exactly where to put those. I tried replacing the content with your accretions over what's been posted by @yann-soubeyrand and @mahadevans87 but didn't work neither. Here's how my index.js looks like originally:
```
var os = require('os')

module.exports = Franz =>
  class Gmail extends Franz {
    overrideUserAgent() {
      if (os.platform() == 'linux')
        return "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
      else
        return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0";
    }
  };
```
Anyway, thanks for helping!

**Comment by philwronski** [comment]
> @philwronski Thank you, but I couldn't make it work yet. My index.js is a little different than the examples here so I couldn't figure out if I was putting those exactly where they should be. I tried replacing the content with your accretions over what's been posted by @yann-soubeyrand and @mahadevans87 but didn't work neither. Here's how my index.js looks like originally:
> 
> ```
> var os = require('os')
> 
> module.exports = Franz =>
>   class Gmail extends Franz {
>     overrideUserAgent() {
>       if (os.platform() == 'linux')
>         return "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
>       else
>         return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0";
>     }
>   };
> ```
> 
> Anyway, thanks for helping!

replace return in if.

**Comment by akira28** [comment]
I'm having the same issue on macOS 10.15.5. How do I edit a recipe?

**Comment by hebinzin** [comment]
Thank you, @philwronski it finally worked for me!

@akira28 
> How do I edit a recipe?

At Ferdi, go to "available services" and them to the "custom services" tab. You'll see a field with the recipes directory, where you'll see the `googlemeet` folder and the `index.js` file inside it. This is the one you'll edit.

You may want to copy that folder inside the dev folder, so your modified Google Meet will be treated as a custom service (separate from the "original").

**Comment by saimonefcs** [comment]
Still happening

**Comment by aagarw33** [comment]
This is what I did for MacOS to make it work on 5.6.0-beta2

```
var os = require('os')

module.exports = Franz =>
  class Gmail extends Franz {
    overrideUserAgent() {
    	return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36";
    }
 };
```

**Comment by m-lamarre** [comment]
> @yann-soubeyrand - A fix has been put up in the recipes for this issue. Until then open your Google Meet recipe's index.js and replace it with the following piece of code and restart Ferdi

Thank you.
This worked for me. 👍🏻

**Comment by vraravam** [comment]
Please try with the nightly builds from [here](http://github.com/vraravam/nightlies/releases) - this exposes the ability to the user to control the user-agent via the UI as opposed to editing files in the Ferdi profile. Please do be aware of the **unsigned nature** of the builds in this repo - while we work on fixing the issue with signing of our build artifacts.

**Comment by mhatvan** [comment]
It seems this issue is fixed by using custom user-agent strings.

**Comment by duonggiakhanhb** [comment]
I try change user-agent in index.js but it don't work.
`module.exports = Ferdi =>
  class GoogleMeet extends Ferdi {
    overrideUserAgent() {
      return "Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36.0 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36.0";
    }
  };
`
or `return window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \([^)]+\)/g, "").trim(); `
