### ISSUE TITLE
5.6 beta not showing up

### ISSUE THREAD

**Issue by rctneil** [getferdi/ferdi#839]
I've noticed the new 5.6 beta is not showing up when i check for updates with betas enabled.

How can I update to the 5.6 beta?

**Comment by vantezzen** [comment]
We haven't released any 5.6.0 betas yet. We are currently in the process of releasing beta 1 but we have some problems with the build process.

**Comment by rctneil** [comment]
Ah! I just saw the Commit and it stated about releasing the beta.  Ah well.  Apologies!
