### ISSUE TITLE
Whatsapp and Microsoft Teams not working with latest Beta 2

### ISSUE THREAD

**Issue by wynstep** [getferdi/ferdi#844]
**Bug description:**
Microsoft Teams and Whatsapp are not loading correctly when I use the latest beta version (5.6.0 beta2). 
**Steps to reproduce:**
1. Go to 'Add service'
2. Click on 'Microsoft Teams'
3. Login with username and password
4. No screen appearing

**Expected behavior**
In the stable version (5.5.0) teams was working correctly

**Screenshots**
<img width="1483" alt="Screenshot 2020-06-24 at 10 57 46" src="https://user-images.githubusercontent.com/7643476/85534859-980a6380-b609-11ea-8066-49091365cc0c.png">
<img width="1484" alt="Screenshot 2020-06-24 at 10 57 55" src="https://user-images.githubusercontent.com/7643476/85534868-9b055400-b609-11ea-91ed-84fc07fc0ea3.png">

**Environment:**

- Operating System: Mac OS Catalina
- Ferdi Version: 5.6.0 beta2
- Server: Both with Franz server and no account

- Debug information:
https://debug.getferdi.com/98f160dd-6b78-4708-a964-325881e5d889

**Comment by frankhommers** [comment]
I have got the same problem on Windows.

**Comment by wynstep** [comment]
> I have got the same problem on Windows.

This is actually a problem that was already present in nightly versions after 5.5.0

**Comment by vossmedien** [comment]
same here!

**Comment by zkhcohen** [comment]
+1

**Comment by wynstep** [comment]
> +1
> 
> Workaround: #603

I can confirm the workaround suggested by @zkhcohen works for both Whatsapp and Teams. Should it be integrated in the beta3?

**Comment by vossmedien** [comment]
@wynstep doesnt work for me.

**Comment by frankhommers** [comment]
> > +1
> > Workaround: #603
> 
> I can confirm the workaround suggested by @zkhcohen works for both Whatsapp and Teams. Should it be integrated in the beta3?

That workaround works for me for WhatsApp as well. I would include it in beta3.

@vossmedien you might need to fully close Ferdi first before it works.

**Comment by dpkonofa** [comment]
Work around doesn't work for me either. :(

**Comment by wynstep** [comment]
> Work around doesn't work for me either. :(

Did you try carefully all the steps and have you closed Ferdi before?

**Comment by vossmedien** [comment]
I had to delete the Service, close the App, make the changes, Restart the App, create the Service. Then it finally worked!

**Comment by idonthaveanametoday** [comment]
The workaround [https://github.com/getferdi/ferdi/issues/603](url) worked at first but after several days I'm still getting the same issues

**Comment by wynstep** [comment]
Mmm this sounds weird for me, after applying the fix everything was correctly sorted and I did not have any other problem on that side. Are you sure you did not revert the changes in the files and/or tried to uninstall the app from the system? Maybe the custom script for the services has been wrongly deleted...

**Comment by idonthaveanametoday** [comment]
Hmm I didn’t change anything at all

**Comment by wynstep** [comment]
> Hmm I didn’t change anything at all
> On Jul 1, 2020, 8:45 AM -0400, Stefano Pirrò <notifications@github.com>, wrote:
> > Mmm this sounds weird for me, after applying the fix everything was correctly sorted and I did not have any other problem on that side. Are you sure you did not revert the changes in the files and/or tried to uninstall the app from the system? Maybe the custom script for the services has been wrongly deleted...
> >
> > On 1 Jul 2020, 13:22 +0100, idonthaveanametoday <notifications@github.com>, wrote:
> > > The workaround https://github.com/getferdi/ferdi/issues/603 worked at first but after several days I'm still getting the same issues
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub, or unsubscribe.
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

are you syncing your services using the server or a local profile?

**Comment by idonthaveanametoday** [comment]
Hmm I’m not sure. I just use WhatsApp and click the QR code

**Comment by RalphBurger** [comment]
same problem here on windows. workaround works for WhatsApp but Microsoft teams is not working at all.

**Comment by wynstep** [comment]
> Hmm I’m not sure. I just use WhatsApp and click the QR code
> […](#)
> On Jul 1, 2020, 2:55 PM -0400, Stefano Pirrò ***@***.***>, wrote: > Hmm I didn’t change anything at all > On Jul 1, 2020, 8:45 AM -0400, Stefano Pirrò ***@***.***, wrote: > > Mmm this sounds weird for me, after applying the fix everything was correctly sorted and I did not have any other problem on that side. Are you sure you did not revert the changes in the files and/or tried to uninstall the app from the system? Maybe the custom script for the services has been wrongly deleted... > > On 1 Jul 2020, 13:22 +0100, idonthaveanametoday ***@***.***, wrote: > > > The workaround #603 worked at first but after several days I'm still getting the same issues > > > — > > > You are receiving this because you were mentioned. > > > Reply to this email directly, view it on GitHub, or unsubscribe. > > > — > > > You are receiving this because you commented. > > > Reply to this email directly, view it on GitHub, or unsubscribe. are you syncing your services using the server or a local profile? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I did have the same problem this morning. There is a very easy fix to this. I just clicked on the Whatsapp Icon -> Reload and that's it!

**Comment by wynstep** [comment]
> same problem here on windows. workaround works for WhatsApp but Microsoft teams is not working at all.

I am on Mac and Linux, so sorry I don't know if there is a custom agent string specific for windows OS

**Comment by dpkonofa** [comment]
I am also on a Mac and changing the user agent string in the index.js file didn't fix my Teams issues at all, even with a restart and then a re-install, re-edit on the file.

**Comment by dpkonofa** [comment]
Microsoft Teams suddenly started working for me this morning after an outage that was restored by Microsoft. Not sure if they're related but I can now use Teams within Ferdi without any issues so far.

**Comment by idonthaveanametoday** [comment]
Oh nice my WhatsApp finally started working again

**Comment by dpkonofa** [comment]
So... what changed on Ferdi's end?

**Comment by thekiefs** [comment]
On a Mac latest Beta the workaround https://github.com/getferdi/ferdi/issues/603 did not work for me :(

**Comment by GuillaumeSorel** [comment]
> I had to delete the Service, close the App, make the changes, Restart the App, create the Service. Then it finally worked!

this worked for me on version 5.6.0-beta.2 on Ubuntu. Thanks

**Comment by Guite** [comment]
#603 worked fine here for fixing Teams on Kubuntu :+1:

**Comment by kkplein** [comment]
Let's hope this will be integrated before a final 5.6 launch. The issue is still open... And also here #603 fixed it.

**Comment by vraravam** [comment]
Please try with the nightly builds from [here](http://github.com/vraravam/nightlies/releases) - this exposes the ability to the user to control the user-agent via the UI as opposed to editing files in the Ferdi profile. Please do be aware of the **unsigned nature** of the builds in this repo - while we work on fixing the issue with signing of our build artifacts.

**Comment by mhatvan** [comment]
Anyone still running into issues with WhatsApp or Microsoft Teams here with the latest releases? 

Otherwise, I would close the issue.

**Comment by kkplein** [comment]
No issues anymore, it has been working for me! :-)

**Comment by mhatvan** [comment]
Great to hear!
