### ISSUE TITLE
Add Process Manager UI for Ferdi Electron app to analyse per-service memory usage

### ISSUE THREAD

**Issue by MurzNN** [getferdi/ferdi#848]
Ferdi ofte eats too much RAM, source of this problem seems one of enabled services. But I can't find the way to get per-service memory report, together with service names. I have found https://github.com/getstation/electron-process-manager that will show sub-processes memory usage - can you integrate it (or similar feature) in Ferdi?

**Comment by vantezzen** [comment]
Ferdi already comes with the process manager you linked. You can open it in Ferdi's settings
