### ISSUE TITLE
Quick Switch shortcut conflict

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#85]
**Describe the bug**
In the File there is "Settings" with the description "CTRL+P" but it appear that the [Quick switch feature (see commit)](https://github.com/getferdi/ferdi/commit/1d41b849cb7840a1611d34f20bfe636fc8b903dc) is using this shortcut instead. And when putting the mouse over the cog in the bottom left corner: we can see a bubble saying "Settings (CTRL+,)" with no other key to show what to press on and using the shortcut.

Maybe we can use CTRL+S instead?

**To Reproduce**

1. Open Ferdi
2. Use CMDorCTRL+P
3. See the Quick Switch appears instead of the settings

**Expected behavior**
The CTRL+P is supposed to be for the settings. (I think?)

**Screenshots**
![wrongshortcut](https://user-images.githubusercontent.com/49844464/65839600-901ccd80-e2dc-11e9-9cf4-67c6276e708a.png)
**Desktop:**

- OS: Windows 7, 10
- Version: 5.3.4-beta.4 (from my last pull request)

**Comment by kytwb** [comment]
Will ship in the next release. Thanks @Makazzz!
