### ISSUE TITLE
Shortcut to switch between services

### ISSUE THREAD

**Issue by leoheck** [getferdi/ferdi#850]
Hi,

I would like to ask to add the `Ctrl+Tab` shortcut to switch between services on a workspace.
Also, `Ctrl+Shift+Tab` to go back.

Since Ferdi is just a browser, having the `Ctrl+Tab` to change between services as a browser does is a good thing to have. I don't understand why it doesn't have this feature so far. 

`Ctrl+1`, `Ctrl+2`, `Ctrl+3`, `Ctrl+4` suck because we have to memorize/remember more things. But of course, these can coexist.

I am currently using Ferdi `5.5.0`

Edit: Added a comment about `Ctrl+Shift+Tab`

**Comment by hyuuki** [comment]
Also upvote for CTRL+TAB/CTRL+SHIFT+TAB, shortcut for Activate next/previous service (CTRL+ALT+RIGHT/LEFT) also won't work since I'm using it globally for playing next/previous track in MusicBee or Spotify using Toastify.

**Comment by martinszy** [comment]
It's ctrl+s, have you tried?

**Comment by leoheck** [comment]
Of course not, because `Ctrl+S` is the universal shortcut to save something. 

Testing now... it also opens a window to change tabs, this sucks even more (takes time to change a tab/service. 

Ferdi is just web browser for message services. Why not just to have the same (universal) shortcut to change tabs/services and change tabs in the same way by just moving.

This issue is not asking for a workaround. I am asking for an improvement.

**Comment by hyuuki** [comment]
@leoh

> Of course not, because `Ctrl+S` is the universal shortcut to save something.
> 
> Testing now... it also opens a window to change tabs, this sucks even more (takes time to change a tab/service.
> 
> Ferdi is just web browser for message services. Why not just to have the same (universal) shortcut to change tabs/services and change tabs in the same way by just moving.
> 
> This issue is not asking for a workaround. I am asking for an improvement.

I totally agree. CTRL+S is the universal shortcut for saving, while CTRL+TAB/CTRL+SHIFT+TAB for switching tab without needing to click or move away from keyboard to mouse. I'm a man of keyboard thus using keyboard more and use mouse less.

**Comment by CombeeMike** [comment]
I totally agree with @leoheck! Also I'd like to add that the current shortcuts `Ctrl+Alt+Left/Right` don't always work for me. I wasn't able to find reproduction steps but sometimes they simply don't do anything. I could imagine that some services also use those shortcuts and somehow "steal" them from the main app but that's just a wild guess...

**Comment by leoheck** [comment]
The one adding these Github tags looks like a real asshole for sure, haha! 
But of course, this is something that Ferdi owners don't know how to do because in the end, it is just a fork of the Franz. 
Which is ok, we can understand.

**Comment by leoheck** [comment]
Bump

**Comment by ilopmar** [comment]
The default `Alt+Ctrl+Right/Left` shortcuts are not the best option because some Linux desktop, like Linux Mint with Cinnamon and many others, use that shortcut to switch between virtual desktops.
