### ISSUE TITLE
Window menu is the same as the Todo menu?

### ISSUE THREAD

**Issue by joshuak94** [getferdi/ferdi#852]
**Bug description:** The window menu shows the same options as the Todo menu.

**Steps to reproduce:**

1. Go to the Todo menu
2. Click on the Window menu
4. Compare the two contents

**Expected behavior:** Not sure what the window menu should contain, but I guess it shouldn't be identical to the Todo menu.

**Screenshots**

**Environment:**

- Operating System: Ubuntu 18.04.4 
- Ferdi Version: 5.5.0
- Server: Franz 

- Debug information:

**Comment by emanuelst** [comment]
This issue is probably related to #550 and #469

**Comment by emanuelst** [comment]
This issue is also in Ferdi Version 5.6.0-beta.2 (5.6.0-beta.2.2329)

**Comment by emanuelst** [comment]
I'd argue that this issue is still relevant as it still exists in the latest beta.

**Comment by emanuelst** [comment]
I'd argue that this issue is still relevant as it still exists in the latest beta.

**Comment by mhatvan** [comment]
I cannot reproduce this with the newest releases on Ubuntu 21.04

"Todos" menu contains "Open/Close Todos drawer" functionality while "Window" menu has entries for "Minimize" and "Close" of the application.
