### ISSUE TITLE
Noticed a considerably slow or lag

### ISSUE THREAD

**Issue by hyuuki** [getferdi/ferdi#859]
Hi, I just found out that Ferdi is a hard-fork of Franz, I was once using Franz and then moved to Rambox. Frankly, Ferdi is beautiful with awesome features. However, comparing to Rambox I noticed a considerably slow or lag while using Ferdi, like its a really heavy program. I'm using Windows 10 2004 with Intel Core i7 8565, 16GB RAM, 512 SSD. Tried using GPU (I have integrated graphic card/Intel HD and Nvidia MX150) but still feel the lag. I don't notice any lag on any programs except Ferdi. I wonder how everyone feeling about it, since I'm feeling quite disturbed with the lag on my workflow that need quick switching, typing, clicking/tapping (mine is convertible laptop).

I'm using 8 services, 2 Gmails, 2 Whatsapps, 2 Slacks, 1 Google Calendar, 1 Google Classroom.

Is there any workaround or settings that any one can suggest to me to omit the lag?

**Comment by martinszy** [comment]
What I do is I configure the auto hibernation feature. In some services you still get notifications, but the webpage is unloaded and this frees up memory. Also in my experience forcing dark mode is considerably slower.

**Comment by vantezzen** [comment]
We are already investigating methods to make Ferdi run more smoothly over at #62. You can look into that thread to see which ones we already implemented, too.

**Comment by hyuuki** [comment]
Hope it will goes well and settled for good. Currently, I'm switching back for now to Rambox even Ferdi is still really tempting for its appearance.
