### ISSUE TITLE
Release beta version in flathub beta

### ISSUE THREAD

**Issue by guilhem** [getferdi/ferdi#862]
It's now possible to release beta versions in flathub
It would be awesome ;)

https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/

**Comment by vantezzen** [comment]
Flathub packages are not officially distributed by us but are managed by @lhw. You can create a PR to https://github.com/flathub/com.getferdi.Ferdi to implement beta versions if you want to.

**Comment by lhw** [comment]
Yes. Flatpaks are completly independent from this repository. Please open flatpak related bugs in the repo vantezzen linked. I'll check on what I need to do to make beta builds available via flathub.

**Comment by lhw** [comment]
Actually nevermind. It was a really easy addition. 5.6.0-b2 is now available in flathub-beta repos. Well. As soon as the index updates. Build is already done https://flathub.org/builds/#/builders/39/builds/2777

**Comment by guilhem** [comment]
thank you @rherwig
