### ISSUE TITLE
Custom Service Icon is not rendered since 5.5.0

### ISSUE THREAD

**Issue by vstyler96** [getferdi/ferdi#863]
**Bug description:**

**Steps to reproduce:**

1. Go to Ferdi New Service
2. Click on Any new Service and choose a custom icon
3. Finish the new service

**Expected behavior**
The Custom PNG ICon must be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/46312870/86820102-39ec7000-c04e-11ea-9c03-9f4894d5345a.png)
![image](https://user-images.githubusercontent.com/46312870/86820033-19bcb100-c04e-11ea-964d-eb3e925c962b.png)

**Environment:**

- Operating System: Arch Linux x64 (Manjaro 20.0.3)=
- Ferdi Version: 5.5.0 x64 (Electron 8.3.4) 
- Server: Using without an account 

- Debug information:
```
{"host":{"platform":"linux","release":"5.7.0-3-MANJARO","screens":[{"id":13761487533244482,"bounds":{"x":0,"y":0,"width":1366,"height":768},"workArea":{"x":0,"y":40,"width":1366,"height":728},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:INVALID, transfer:INVALID, matrix:INVALID, range:INVALID}","depthPerComponent":8,"size":{"width":1366,"height":768},"workAreaSize":{"width":1366,"height":728},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.3.4","installedRecipes":[{"id":"slack","version":"1.0.15"},{"id":"whatsapp","version":"2.0.3"},{}],"devRecipes":[],"services":[{"id":"6e71ea02-8802-438f-afa4-64638ef913d8","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"911947ce-86f4-49a1-9dea-d62cb6b30db4","recipe":"whatsapp","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Using internal recipe file"]},{"type":"log","info":["log","/usr/lib/ferdi/app.asar.unpacked/recipes/whatsapp.tar.gz"]}],"workspaces":[],"windowSettings":{"width":800,"height":600,"x":381,"y":168,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1366,"height":768}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"navigationBarBehaviour":"never","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}
```

**Comment by gfsoftpl** [comment]
I have same issue on windows 10.

Version: 5.5.0 (x64)
Electron: 8.2.3
Node.js: v12.13.0

Server: Using without an account

**Comment by gearboxscott** [comment]
Same issue on OSX Catalina

Version: 5.5.0 (5.5.0.2116)
Node: 13.12.0
No account

**Comment by maddin79** [comment]
Issue also on Ubunut 20.04 installed with .deb (5.5.0)

**Comment by Swandog** [comment]
Same on POP OS! 20.04, installed from a flatpak

Debug info:
`{"host":{"platform":"linux","release":"5.4.0-7626-generic","screens":[{"id":1241946083112412,"bounds":{"x":2953,"y":0,"width":2953,"height":1661},"workArea":{"x":2953,"y":0,"width":2955,"height":1662},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:INVALID, transfer:INVALID, matrix:INVALID, range:INVALID}","depthPerComponent":8,"size":{"width":2953,"height":1661},"workAreaSize":{"width":2955,"height":1662},"scaleFactor":1.2999999523162842,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":4693658129386205,"bounds":{"x":0,"y":0,"width":2953,"height":1661},"workArea":{"x":0,"y":26,"width":2954,"height":1636},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6479, 0.3310],  [0.3200, 0.5983],  [0.1563, 0.0654]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2953,"height":1661},"workAreaSize":{"width":2954,"height":1636},"scaleFactor":1.2999999523162842,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"gmail","version":"1.3.1"},{"id":"googlecalendar","version":"1.0.3"},{"id":"trello","version":"1.0.2"},{}],"devRecipes":[],"services":[{"id":"27af5e14-33a1-4aa6-a739-22199975e920","recipe":"trello","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"76229dcc-936c-4c1d-bb5c-9da3fff66e71","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"aba682b5-2f20-4e2d-b2ff-d14f737ef16c","recipe":"googlecalendar","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"b8d76821-1cc9-41d9-a48d-1f200cc36b93","recipe":"googlecalendar","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `showMessageBadgeWhenMutedSetting` of type `string` supplied to `_class2`, expected `boolean`.\n    in _class2 (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","info":["error","Reaction doesn't converge to a stable state after 100 iterations. Probably there is a cycle in the reactive function: Reaction[bound _build]"]},{"type":"error","info":["error","Warning: You cannot PUSH the same path using hash history"]},{"type":"error","info":["error","Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state."]}],"workspaces":[],"windowSettings":{"width":800,"height":600},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":"","privateNotifications":false,"showDisabledServices":"","showMessageBadgeWhenMuted":"","showDragArea":false,"enableSpellchecking":"","spellcheckerLanguage":"en-us","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":"","serviceLimit":5,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}`

Version: 5.5.0
Electron 8.2.3
used without an account

I just installed Ferdi yesterday, and FWIW I noticed there's no `~/.config/Ferdi` folder

**Comment by c-wagner** [comment]
Same Issue for me too. (Windows 10)

Version: 5.5.0 
No account

**Comment by ragusa87** [comment]
This issue probably duplicates https://github.com/getferdi/ferdi/issues/780
