### ISSUE TITLE
Web browser

### ISSUE THREAD

**Issue by gfsoftpl** [getferdi/ferdi#864]
First of all, I really like your project.
I appreciate your hard work you did.

A wonderful improvement that I miss would be a regular web browser.

**Describe the solution you'd like**
Opening several websites tabs.
Bookmark system.
Cards at the top of the program.

**Describe alternatives you've considered**
All connected services use a web browser. 
Allowing free browsing on the next service would do the trick.

**Additional context**
Similar software with that feature: https://tryshift.com/

**Comment by vantezzen** [comment]
We don't want Ferdi to become a normal web browser so we won't be implementing features a normal web browser might have. If you want to have a tab that has an experience more similar to a normal browser, you can use the "Custom Website" service and activate the navigation bar in Ferdi's settings.
