### ISSUE TITLE
Add "Hibernate service" action to right-click menu on Service icon

### ISSUE THREAD

**Issue by MurzNN** [getferdi/ferdi#865]
Will be good to have "Hibernate service" action in right-click menu on service icon, for force hibernating of service, without waiting for timeout happens.

Also this will be useful for manually one-time hibernating services, that does not enable auto-hibernation feature.

**Comment by MurzNN** [comment]
bump! Feature is very needed!

**Comment by Coderdude112** [comment]
+1 Feature is definitely needed. Would love to see this.

**Comment by MurzNN** [comment]
bump, yopta!

**Comment by Coderdude112** [comment]
Bump! Would still love this feature!!
To people who read this: Have an amazing day -An internet stranger

**Comment by vraravam** [comment]
I am taking this up today. Will raise a PR soon.

**Comment by mhatvan** [comment]
Looks like the functionality is there, can this be closed @vraravam ?
