### ISSUE TITLE
Update Dark Reader to latest version

### ISSUE THREAD

**Issue by deadmeu** [getferdi/ferdi#866]
Version 4.9.9 of Dark Reader claims to include a [variety of performance improvements](https://darkreader.org/blog/v4-9/). Upgrading the `darkreader` package (latest version is [4.9.14](https://www.npmjs.com/package/darkreader)) may be a free performance improvement (also may provide more accurate filtering - I have noticed my browser with the Dark Reader extension does a better job on some websites compared to Ferdi). 

I would open a pull request for this change but I am having issues building the current version of the app under Linux.

**Comment by vraravam** [comment]
I would concur. If its just a question of `npm update darkreader` (without any breaking changes) - then someone should just just do that. Unfortunately, I haven't had much luck getting the dev env up and running (and I only dabble in nodejs).

**Comment by vraravam** [comment]
pinging to remove staleness

**Comment by vraravam** [comment]
ping to make unstale
