### ISSUE TITLE
Opening link when in fullscreen is impossible to close

### ISSUE THREAD

**Issue by rctneil** [getferdi/ferdi#867]
**Bug description:**
On MacOS, when clicking a link, it opens as part of Ferdi but in a separate fullscreen mode window which is impossible to close.

I personally think links should open in the default browser. Or at least provide an option in settings to allow the user to decide.

**Steps to reproduce:**
Use MacOS
Ensure Ferdi is in Fullscreen Mode
Click a link
Try to close fullscreen linked window

**Expected behavior**
External linked fullscreen window would close
**Screenshots**

**Environment:**

- Operating System: MacOS Cataline
- Ferdi Version: 5.6 beta 2

- Debug information:

{"host":{"platform":"darwin","release":"19.5.0","screens":[{"id":69733568,"bounds":{"x":0,"y":0,"width":1440,"height":900},"workArea":{"x":0,"y":0,"width":1440,"height":900},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6818, 0.3196],  [0.2846, 0.6747],  [0.1576, 0.0542]], transfer:0.0777*x + 0.0000 if x < 0.0450 else (0.9495*x + 0.0495)**2.3955 + 0.0003, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1440,"height":900},"workAreaSize":{"width":1440,"height":900},"scaleFactor":2,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.0-beta.2","electron":"8.2.3","installedRecipes":[{"id":"airtable","version":"1.0.1"},{"id":"discord","version":"1.1.1"},{"id":"franz-custom-website","version":"1.0.2"},{"id":"github","version":"2.0.0"},{"id":"hackmd","version":"1.0.0"},{"id":"messenger","version":"1.1.0"},{"id":"pocket","version":"1.0.0"},{"id":"skype","version":"1.2.0"},{"id":"slack","version":"1.0.15"},{"id":"telegram","version":"3.0.0"},{"id":"telegram-react","version":"1.0.0"},{"id":"trello","version":"1.0.2"},{"id":"whatsapp","version":"2.0.5"},{"id":"1password","version":"1.0.1"},{"id":"iCloud","version":"1.0.0"},{"id":"netatmo-energy","version":"1.0.1"},{"id":"unraid","version":"1.0.1"}],"devRecipes":[{"id":"1password","version":"1.0.1"},{"id":"iCloud","version":"1.0.0"},{"id":"netatmo-energy","version":"1.0.1"},{"id":"unraid","version":"1.0.1"}],"services":[{"id":"c3a30643-7ef6-4386-bc5e-f04a2dd533f7","recipe":"telegram-react","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"71a2f921-3cd1-43fa-b533-ae8004bbeb6d","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":""},{"id":"147f7d23-42d9-47de-a5a3-c054922ecd90","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"1471be2d-0082-4e7b-a519-1170f72a0e0c","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"1dac40a4-304a-4dfe-a994-60d225d64e45","recipe":"airtable","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"68ab1a66-677b-4f79-a7b1-0b223ab51061","recipe":"trello","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":""},{"id":"2fcd8a71-e6b8-4d00-9b8d-5b8c8a58fb39","recipe":"pocket","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":""},{"id":"6a67e72c-33bb-4fc4-93f2-86871a660eda","recipe":"github","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"8c90cf28-4984-46fa-a49f-f85ed69c4a6f","recipe":"unraid","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"36c2d892-1833-4026-acfe-faac6ea57f30","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"1c6048cd-23fb-425a-8fb1-72e7cc0cb7e3","recipe":"netatmo-energy","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":""},{"id":"c1dcc9c1-74ca-40ce-a0e6-3d6b47b55ad8","recipe":"1password","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":""},{"id":"153acd20-2f3a-484f-8085-c22ff3701707","recipe":"telegram","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"}],"workspaces":[{"id":"35b10379-c1dc-46a2-858a-0fc94c24a4c9","services":["a23a9a25-0d45-4d09-ba3f-3b0e348c0702","68ab1a66-677b-4f79-a7b1-0b223ab51061"]}],"windowSettings":{"width":1146,"height":745,"x":120,"y":91,"isMaximized":true,"isFullScreen":true,"displayBounds":{"x":0,"y":0,"width":1440,"height":900}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":true,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-gb","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":"55","iconSize":"20","sentry":false,"navigationBarBehaviour":"always","customTodoServer":"","noUpdates":false,"todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by fdoerschner** [comment]
This is unfortunately still an error, currently having it searching for an answer.
Opened a link via rightclick and "Open in Ferdi".
