### ISSUE TITLE
Display a "Back to Service" button/banner after selecting "Open link in Ferdi"

### ISSUE THREAD

**Issue by Falcz** [getferdi/ferdi#868]
When you select "Open link in Ferdi" it opens up the link in the Service's view, as expected, but there isn't currently an intuitive way to navigate the view back to the Service page.

As an example, I've used "Open link in Ferdi" on a Netflix link from the Gmail Service:
![image](https://user-images.githubusercontent.com/1457826/86943526-ef85f480-c11c-11ea-8b0f-05dba46588b9.png)

There isn't a clear way of getting back to Gmail - the view will continue to display the Netflix homepage regardless of whether I:
- Click on the Gmail icon
- Reload the Service

Which is probably the correct behavior - I wouldn't want to lose state in either of those operations (it's nice not losing where you are in the service in both cases).

The only way to get the view back to the Service page seems to be either:
- Using the "Back" option under "View" until you are back where you want to be
- Reloading (or restarting) Ferdi

It would be nice to have an overlay Button or Banner that's displayed in the view after opening a link in Ferdi, which when clicked, navigates the view back to the page where the link was initially clicked.

**Comment by vraravam** [comment]
This is easily overcome by using the "Cmd/Ctrl + left arrow" key combo that is the universal default of "going back" in any browser. Or else, with the latest beta (released approx 24 hours ago), you can right-click and use the context menu option to do the same.
