### ISSUE TITLE
Portable apps and in-app updates tweaks

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#87]
**Is your feature request related to a problem? Please describe.**
For the next release I will create Ferdi in PortableApps format (Already done for Franz and I will do it for Ferdi too) and It will be very great If a switch could be added so the app will not rewriting by himself and maybe asking for admin write.

**Describe the solution you'd like**
Like adding a button/swith for desactivate update under accepting beta version so it is in the same area.

**Comment by vantezzen** [comment]
I just published 098c46e which should _implement_ this feature. Unfortunately, this is something I can't really test so we'll have to test it over the next updates.

**Comment by kytwb** [comment]
@Makazzz from what I understand, the portable apps should not update at all, rather than have an option not-to-update, is that right?

**Comment by Makazzz** [comment]
@kytwb normally when a portable apps is created we use a pre-created config file from the app (like settings/config.json) and change some value <code>update: false</code> so like that in the first run the user is not having an application that break himself by trying to update and/or asking admin right. OR we can block the update by renaming/changing some file so the app dosn't know where to find information about doing update. There is a few app that can be auto-updating without setup or admin right: JDownloader, Discord, etc... I will have to test if ferdi can be updated without a prompt for update or if Ferdi is pre-downloading the packaging in the Appdata folder (like Bitwarden do). And it is usual to desactivate the update option when bulding portableapps (with config file or a trick).

**Comment by kytwb** [comment]
I see electron-builder support the [portable](https://www.electron.build/configuration/nsis#portable) target for Windows; we should give it a try and see how the auto-update behave then. Maybe something is already handled in the portable build regarding in-app updates?

**Comment by kytwb** [comment]
@Makazzz you can find the portable version built by electron-builder in [here](https://ci.appveyor.com/project/kytwb/ferdi/builds/27869773/artifacts) (the executable without _Setup_ in the filename).

**Comment by Makazzz** [comment]
@kytwb thanks for this I will use this .exe for extract the app-32.7z and portabilize without using temps files. And it is possible to create an environment variable like [Bitwarden did](https://github.com/bitwarden/desktop/commit/aa515cb36945437e826c4a2a70717d8d154bc964) (an electron app too writen in TypeScript) for helping the portableapps format to work?  Because the laucher of portableapps can use environement variable for the user and use relative path for beign sure the data go to a folder choosen Like FERDI_APPDATA_DIR.

**Comment by kytwb** [comment]
Possible, on it 👍

**Comment by Makazzz** [comment]
Thank you

**Comment by kytwb** [comment]
@vantezzen I guess if needed we can use `PORTABLE_EXECUTABLE_DIR` to make the define if it's a portable app and disable updates by default?

**Comment by Makazzz** [comment]
Thanks a lot I will finish my repo of FerdiPortable and the build tomorrow. Thanks for your work.

**Comment by kytwb** [comment]
@Makazzz Welcome!
@vantezzen In the doc they say we also have access to:

> PORTABLE_EXECUTABLE_APP_FILENAME - sanitized app name to use in file [paths](https://github.com/electron-userland/electron-builder/issues/3186#issue-345489962).

Following the links on _paths_:

> I want to toggle shortcut and startup, which will need dir and app name

Do we need to use `PORTABLE_EXECUTABLE_APP_FILENAME` somewhere for that purpose/to make things compatible with portable apps?

**Comment by Makazzz** [comment]
@kytwb I tested my Ferdi portable apps and with the FERDI_USERDATA_DIR variable and the config file for settings.json and proxy.json inside the config folder still stay in the appdata dir but all the rest of the data go to where I say so (so in a portable folder).

**Comment by kytwb** [comment]
@Makazzz understood; I think I need to set `app.setPath('appData', ...)` instead of `app.setPath('userData', ...)`. Will come up with a fix soon.

**Comment by kytwb** [comment]
@Makazzz last commit should do the trick; please use `FERDI_APPDATA_DIR` instead of `FERDI_USERDATA_DIR`.

**Comment by Makazzz** [comment]
Thanks, I will wait to AppVeyor to increase your maximum storage and test the next builded Ferdi.

**Comment by kytwb** [comment]
Alternatively, you could build the project locally on your Windows. You should get the .exe in the `out` folder as explained in the README. If you don't manage to, I will follow-up once AppVeyor has.

**Comment by Makazzz** [comment]
I will wait because at the moment I am not home but thanks for the info.

**Comment by Makazzz** [comment]
Finally I will wait because I have to many error (like cb() never called) with Node.js 10.16.3 and nothing work for building

**Comment by Makazzz** [comment]
@kytwb I have a problem... the FERDI_APPDATA_DIR don't do anything now and I don't know why.

**Comment by Makazzz** [comment]
> 
> 
> @kytwb I have a problem... the FERDI_APPDATA_DIR don't do anything now and I don't know why.

@vantezzen Can you check about this please?

**Comment by vantezzen** [comment]
I think we need to roll back to using `FERDI_USERDATA_DIR` instead of `FERDI_APPDATA_DIR `. It looks like [`appData` only gets used to generate the `userData` folder during dev builds](https://github.com/getferdi/ferdi/blob/develop/src/index.js#L12-L20).

I think we need to fix settings.json and proxy.json in another way. These are the only files that get updated through calls to the [local API](https://github.com/getferdi/ferdi/blob/develop/src/api/server/LocalApi.js), so the problem needs to be somewhere in there.
I'll look into this the next days or @kytwb may find the bug.

**Comment by Makazzz** [comment]
Ok thanks for the answer

**Comment by kytwb** [comment]
> It looks like appData only gets used to generate the userData folder during dev builds.

In our code yes, but I think it's also used by Electron's internals afterward.  
What got me confused is:

> the config file for settings.json and proxy.json inside the config folder still stay in the appdata dir but all the rest of the data go to where I say so

But the `SETTINGS_PATH` is set to:

```
export const SETTINGS_PATH = path.join(app.getPath('userData'), 'config');
```

So not sure how the `settings.json` inside the `config` folder was in the appdata dir instead of the set userdata dir.  

Giving another try to `FERDI_APPDATA_DIR` with the next commit I'll push as I noticed I userData wasn't explicitly set on that iteration.

**Comment by Makazzz** [comment]
Still not working :/ . And now Ferdi is forcing me to have english has locale language.

**Comment by kytwb** [comment]
What's happening now if you don't set `FERDI_APPDATA_DIR`? Does it fallback properly to `PORTABLE_EXECUTABLE_DIR`? If it's not working, I guess I'll revert the changes to `FERDI_USERDATA_DIR` and investigate why the two files you previously mentioned are not where they're expected to based on @vantezzen suggestion.

**Comment by Makazzz** [comment]
@kytwb If I remove the variable Ferdi just act like a normal install (use %AppData%)

**Comment by kytwb** [comment]
@Makazzz roger that, I'll spend some more time checking over the weekend 🙏

**Comment by Makazzz** [comment]
I found this when doing research. https://github.com/electron/electron/issues/1404#issuecomment-194391247 I don't know if it help.

**Comment by kytwb** [comment]
@Makazzz Did you ever managed to build the project locally on your Windows? I'd be happy to pair with you to make it work, I think it would really help if we have a contributor that can test things that are Windows-specific to avoid back and forth as we experienced on this issue. WDYT?

I will push the snippet as it:

```
if (process.platform == "win32") {
  app.setPath("appData", process.env.LOCALAPPDATA);
  app.setPath("userData", path.join(process.env.LOCALAPPDATA, app.getName()));
}
```

But I don't understand why that would work and not the previous commits.

**Comment by Makazzz** [comment]
@kytwb I did not managed to make a working build but I want to do it and it will be really helpfull if we pair to make it work. And I was thinking to make an section in the wiki for windows build with steps etc.

**Comment by kytwb** [comment]
@Makazzz awesome, let's do this! You can use this [link](https://calendly.com/kytwb/call) to pick a date/time at your convenience!

**Comment by Makazzz** [comment]
@kytwb Sure but I am not so confident about doing a call/video but more feeling into text/messaging. And my english speaking is not the best (sorry in advance).

**Comment by kytwb** [comment]
No worries, we can do what you're more comfortable with. Received your calendly invite, talk to you in the morning, signing off here!
PS: I speak French as well 😉

**Comment by kytwb** [comment]
I think the last bit to be taken care of here is to disable in-app updates for Portable apps? Or is that not relevant anymore?

**Comment by Makazzz** [comment]
Normally vantezzen did it with this commit 098c46e.
