### ISSUE TITLE
Ferdi on ARM (Mac M1 and Microsoft Surface X)

### ISSUE THREAD

**Issue by inteus707** [getferdi/ferdi#875]
Ferdi won't install and run on Microsoft Surface Pro X which is ARM architecture. Are there plans to include ARM in the future?

**Comment by vantezzen** [comment]
Do other Electron-based apps (like VS Code, Spotify, Discord, etc.) work on ARM? If so, we'll probably just have to change something in our build configuration, otherwise this will be a problem with Electron.

**Comment by inteus707** [comment]
I do use Discord on ARM.

**Comment by fdelucchijr** [comment]
Any news with this? I really wanna start using Ferdi with my m1 mba!

**Comment by vraravam** [comment]
Performance on the ARM is quite bad. Can we get a new version that runs natively please?

**Comment by arioki1** [comment]
slack already native m1 but discord not yet native, electron 11 already native m1 https://www.electronjs.org/blog/electron-11-0 @vantezzen

**Comment by vantezzen** [comment]
Ok, so we'll just have to upgrade Ferdi's electron version and we should be able to add ARM to [the build config](https://github.com/getferdi/ferdi/blob/develop/electron-builder.yml). As far as I can tell, there _should_ be no breaking features that cause problems in Ferdi.

It looks like electron-builder (our build tool) also supports ARM builds now (https://github.com/electron-userland/electron-builder/issues/5392#issuecomment-754239349).

I don't have access to an ARM computer - would anyone be interested in implementing this feature and testing this on an M1?

**Comment by vraravam** [comment]
I have an M1 - and can volunteer for testing. But, I am not a nodejs dev,
so, can't make the code changes. If someone can do them, and ping me the
branch, I will try to follow the `README.md` and run the scripts.

Vijay

**Comment by arioki1** [comment]
i've tried electron and electron-builder upgrade but when npm install always get this error, 
```
npm WARN registry Using stale data from https://registry.npmjs.org/ because the host is inaccessible -- are you offline?
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     undefined,
npm WARN cleanup     AssertionError [ERR_ASSERTION]: rimraf: missing path
npm WARN cleanup         at rimraf (/opt/homebrew/lib/node_modules/npm/node_modules/rimraf/rimraf.js:54:3)
npm WARN cleanup         at node:internal/util:325:7
npm WARN cleanup         at new Promise (<anonymous>)
npm WARN cleanup         at rimraf (node:internal/util:311:12)
npm WARN cleanup         at /opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:446:20
npm WARN cleanup         at Array.map (<anonymous>)
npm WARN cleanup         at Arborist.[rollbackCreateSparseTree] (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:446:8)
npm WARN cleanup         at Arborist.[reifyPackages] (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:211:31)
npm WARN cleanup         at async Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
npm WARN cleanup         at async Install.install (/opt/homebrew/lib/node_modules/npm/lib/install.js:137:5) {
npm WARN cleanup       generatedMessage: false,
npm WARN cleanup       code: 'ERR_ASSERTION',
npm WARN cleanup       actual: undefined,
npm WARN cleanup       expected: true,
npm WARN cleanup       operator: '=='
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /opt/homebrew/Cellar/node/15.13.0/bin/node /opt/homebrew/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/yogasetiawan/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! npm WARN deprecated har-validator@5.0.3: this library is no longer supported
npm ERR! npm WARN deprecated eslint-loader@2.1.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm ERR! npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! npm WARN deprecated debug@4.1.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! npm WARN deprecated debug@4.1.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! npm WARN deprecated typescript-estree@2.1.0: This package was moved to @typescript-eslint/typescript-estree, please install the latest version from there instead
npm ERR! npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! npm WARN deprecated request@2.87.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated eslint-plugin-typescript@0.12.0: Deprecated: Use @typescript-eslint/eslint-plugin instead
npm ERR! npm WARN deprecated webdriverio@4.13.2: outdated version, please use @next
npm ERR! npm WARN deprecated core-js@2.5.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/yogasetiawan/.npm/_cacache/tmp/git-clone-cc030301/node_modules/electron-chromedriver
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node ./download-chromedriver.js
npm ERR! npm ERR! /Users/yogasetiawan/.npm/_cacache/tmp/git-clone-cc030301/node_modules/electron-chromedriver/download-chromedriver.js:30
npm ERR! npm ERR!   if (err != null) throw err
npm ERR! npm ERR!                    ^
npm ERR! npm ERR!
npm ERR! npm ERR! Error: Failed to find Electron v2.0.0 for darwin-arm64 at https://github.com/electron/electron/releases/download/v2.0.0/chromedriver-v2.0.0-darwin-arm64.zip
npm ERR! npm ERR!     at Request.<anonymous> (/Users/yogasetiawan/.npm/_cacache/tmp/git-clone-cc030301/node_modules/nugget/index.js:169:61)
npm ERR! npm ERR!     at Request.emit (node:events:369:20)
npm ERR! npm ERR!     at Request.onRequestResponse (/Users/yogasetiawan/.npm/_cacache/tmp/git-clone-cc030301/node_modules/request/request.js:1062:10)
npm ERR! npm ERR!     at ClientRequest.emit (node:events:369:20)
npm ERR! npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:643:27)
npm ERR! npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
npm ERR! npm ERR!     at TLSSocket.socketOnData (node:_http_client:509:22)
npm ERR! npm ERR!     at TLSSocket.emit (node:events:369:20)
npm ERR! npm ERR!     at addChunk (node:internal/streams/readable:313:12)
npm ERR! npm ERR!     at readableAddChunk (node:internal/streams/readable:288:9)
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/yogasetiawan/.npm/_logs/2021-04-13T09_38_03_322Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yogasetiawan/.npm/_logs/2021-04-13T09_38_36_959Z-debug.log
```

**Comment by arioki1** [comment]
npm ERR! npm ERR! Error: Failed to find Electron v2.0.0 for darwin-arm64 at https://github.com/electron/electron/releases/download/v2.0.0/chromedriver-v2.0.0-darwin-arm64.zip

**Comment by arioki1** [comment]
I have an m1 engine and I do not know how to solve this error, do you have a solution to this error  @vantezzen

**Comment by arioki1** [comment]
node --version
v15.13.0
npm --version
7.9.0

**Comment by vantezzen** [comment]
Hmm, I don't know why it would try to install Electron 2 when it should use Electron 11? The newer Electron releases like https://github.com/electron/electron/releases/tag/v11.4.2 have a darwin-arm64 builds but those old ones of course don't.

Can you make sure to update package.json (https://github.com/getferdi/ferdi/blob/e3898e2f47db4d056c03708221901d58eb47c8f5/package.json#L165) to use Electron "^11.4.2" and reinstall dependencies with "npx lerna bootstrap"?

**Comment by arioki1** [comment]
package.json
![image](https://user-images.githubusercontent.com/1139881/114541382-dd734c80-9c80-11eb-82c5-ddef351c25d5.png)

**Comment by arioki1** [comment]
command npx lerna bootstrap I get the same error

**Comment by vantezzen** [comment]
Hmm ok, looks like this error is due to somehow using "electron-chromedriver" v2 instead of v12. I don't know why electron-chromedriver is loaded though - we don't directly have a dependency on it.

Can you try running "npm why electron-chromedriver" to see if it can say why electron-chromedriver is loaded?

**Comment by arioki1** [comment]
➜  ferdi git:(develop) ✗ npm explain electron-chromedriver
npm ERR! No dependencies found matching electron-chromedriver
➜  ferdi git:(develop) ✗

**Comment by arioki1** [comment]
why so many errors :D whereas I run on linux smoothly :D

**Comment by vantezzen** [comment]
Oh, even weirder - why would it try to run "node_modules/electron-chromedriver/download-chromedriver.js:30" if electron-chromedriver is not even depended on? Also can't recreate this on my non-M1 mac

**Comment by arioki1** [comment]
i've also deleted the .npm directory to make sure there's no cache but I'm getting the same error

**Comment by vraravam** [comment]
I get a different error:
[image: Screenshot 2021-04-13 at 5.04.44 PM.png]

**Comment by arioki1** [comment]
for error `node_modules/electron-chromedriver/download-chromedriver.js:30` I've solved by removing electron-process-manager.
This PR is not as old as the road there are still some errors, maybe others can continue it
https://github.com/getferdi/ferdi/pull/1277

**Comment by arioki1** [comment]
on dev mode
![image](https://user-images.githubusercontent.com/1139881/114654029-7d79b600-9d13-11eb-99ff-fb94ba7a1aad.png)

**Comment by vraravam** [comment]
Which version of npm and node are you running @arioki1 ? I'm still getting the following error:

<img width="1266" alt="Screenshot 2021-04-14 at 10 12 36 AM" src="https://user-images.githubusercontent.com/69629/114655502-f2e08900-9d09-11eb-8c31-64a27f925a8a.png">

**Comment by arioki1** [comment]
try you pull back, I've pushed my changes @vraravam

**Comment by vraravam** [comment]
<img width="1236" alt="Screenshot 2021-04-14 at 10 25 16 AM" src="https://user-images.githubusercontent.com/69629/114656437-b746be80-9d0b-11eb-8669-1d8b7ce12f91.png">
With your latest code, this is the error I am getting when I run `npx lerna bootstrap`. All other pertinent info is in the screensthot.

**Comment by vraravam** [comment]
ok - found that I had node 15 - and dropped it back to 12.x as per the checked-in `.nvmrc` file, and now its progressing much farther

**Comment by arioki1** [comment]
@vraravam I run `git clean -fxd and npx lerna bootstrap` does not occur error, do you run the terminal in rosetta or use intel version nodes?
```
➜  ferdi git:(native_m1) git clean -fxd
Removing .idea/
Removing node_modules/
Removing packages/forms/lib/
Removing packages/forms/node_modules/
Removing packages/forms/tsconfig.tsbuildinfo
Removing packages/theme/lib/
Removing packages/theme/tsconfig.tsbuildinfo
Removing packages/ui/lib/
Removing packages/ui/tsconfig.tsbuildinfo
➜  ferdi git:(native_m1) npx lerna bootstrap
lerna notice cli v4.0.0
lerna info versioning independent
lerna info bootstrap root only
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> ferdi@5.6.0-nightly.18 postinstall
> npx lerna run prepare

lerna notice cli v3.19.0
lerna info versioning independent
lerna info Executing command in 3 packages: "npm run prepare"
lerna info run Ran npm script 'prepare' in '@meetfranz/theme' in 6.2s:

> @meetfranz/theme@1.0.14 preprepare
> npm run test


> @meetfranz/theme@1.0.14 test
> npx mocha



  0 passing (0ms)


> @meetfranz/theme@1.0.14 prepare
> tsc

lerna info run Ran npm script 'prepare' in '@meetfranz/ui' in 7.1s:

> @meetfranz/ui@1.1.0 prepare
> tsc

lerna info run Ran npm script 'prepare' in '@meetfranz/forms' in 7.3s:

> @meetfranz/forms@1.2.1 prepare
> tsc

lerna success run Ran npm script 'prepare' in 3 packages in 13.6s:
lerna success - @meetfranz/forms
lerna success - @meetfranz/theme
lerna success - @meetfranz/ui

added 3507 packages, and audited 3511 packages in 2m

35 packages are looking for funding
  run `npm fund` for details

72 vulnerabilities (28 low, 12 moderate, 30 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

**Comment by arioki1** [comment]
![image](https://user-images.githubusercontent.com/1139881/114657304-faa82980-9d19-11eb-8bc3-e206f818e586.png)

**Comment by vraravam** [comment]
I was able to run in dev mode with node v12.

**Comment by arioki1** [comment]
@vraravam whether you can build release version 
https://github.com/getferdi/ferdi#packaging

**Comment by vraravam** [comment]
yes - i will try that @arioki1

**Comment by vraravam** [comment]
@arioki1 : This is the error that I got when I ran `npm run build`:
```
  • Unpacking electron zip  zipPath=undefined
  ⨯ Application entry file "index.js" in the "/Users/vijay/dev/oss/ferdi/out/mac/Ferdi.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.  stackTrace=
                                                                                                                                                                             Error: Application entry file "index.js" in the "/Users/vijay/dev/oss/ferdi/out/mac/Ferdi.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
                                                                                                                                                                                 at error (/Users/vijay/dev/oss/ferdi/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
                                                                                                                                                                                 at checkFileInArchive (/Users/vijay/dev/oss/ferdi/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:33:11)
                                                                                                                                                                                 at MacPackager.checkFileInPackage (/Users/vijay/dev/oss/ferdi/node_modules/app-builder-lib/src/platformPackager.ts:430:7)
                                                                                                                                                                                 at MacPackager.sanityCheckPackage (/Users/vijay/dev/oss/ferdi/node_modules/app-builder-lib/src/platformPackager.ts:481:5)
                                                                                                                                                                                 at MacPackager.doPack (/Users/vijay/dev/oss/ferdi/node_modules/app-builder-lib/src/platformPackager.ts:253:5)
                                                                                                                                                                                 at MacPackager.pack (/Users/vijay/dev/oss/ferdi/node_modules/app-builder-lib/src/macPackager.ts:167:7)
                                                                                                                                                                                 at Packager.doBuild (/Users/vijay/dev/oss/ferdi/node_modules/app-builder-lib/src/packager.ts:434:9)
                                                                                                                                                                                 at executeFinally (/Users/vijay/dev/oss/ferdi/node_modules/builder-util/src/promise.ts:12:14)
                                                                                                                                                                                 at Packager._build (/Users/vijay/dev/oss/ferdi/node_modules/app-builder-lib/src/packager.ts:369:31)
                                                                                                                                                                                 at Packager.build (/Users/vijay/dev/oss/ferdi/node_modules/app-builder-lib/src/packager.ts:333:12)
                                                                                                                                                                                 at executeFinally (/Users/vijay/dev/oss/ferdi/node_modules/builder-util/src/promise.ts:12:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ferdi@5.6.0-nightly.18 build: `npx electron-builder`
npm ERR! Exit status 1
```
Inspite of that error, there was a file that had been generated in `out\mac\Ferdi.app` - and when I tried to open it, this is the error popup that was shown:
<img width="258" alt="Screenshot 2021-04-14 at 11 13 56 AM" src="https://user-images.githubusercontent.com/69629/114660202-86b65300-9d12-11eb-83f8-a22df0394534.png">

**Comment by arioki1** [comment]
can you remove target zip https://github.com/arioki1/ferdi/blob/native_m1/electron-builder.yml#L23 and re build, my process stuck when running npm run build

**Comment by arioki1** [comment]
i am stuck here @vraravam 
![image](https://user-images.githubusercontent.com/1139881/114661316-ff241080-9d20-11eb-8297-c94317d9a0da.png)

**Comment by vraravam** [comment]
I ran again with a clean folder (git clean -fxd .); and ran `npm run build` - but landed with the same error in the process and the same error popup if i clicked on the Ferdi.app that was generated. (This is after removing the entry for `zip` target in the `electron-builder.yml` file.

**Comment by vraravam** [comment]
@arioki1 - on oddity that I just noticed:
```
  • writing effective config  file=out/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=cld@2.7.0, macos-notification-state@1.3.5, sqlite3@4.1.0, windows-notification-state@1.3.4, windows-quiet-hours@1.2.7 platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=11.4.2 appOutDir=out/mac
```
If you see, the `arch` being targeted is still `x64`. I am not running rosetta, and when I run `uname -m` - I get: `arm64`. Weird!

**Comment by arioki1** [comment]
➜  ~ uname -a
Darwin Yogas-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64

**Comment by vraravam** [comment]
```
uname -a
Darwin Vijays-MacBook-Pro-Apple-M1.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
```

**Comment by arioki1** [comment]
Anda memiliki solusi, saya tidak menggunakan rosetta

**Comment by arioki1** [comment]
you have a solution, I do not using rosetta

**Comment by arioki1** [comment]
still the same?
```
To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=out/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=cld@2.7.0, macos-notification-state@1.3.5, sqlite3@4.1.0, windows-notification-state@1.3.4, windows-quiet-hours@1.2.7 platform=darwin arch=arm64
```

**Comment by vraravam** [comment]
same issue for me as well.

**Comment by arioki1** [comment]
@vantezzen can you try this PR build release on other platforms, linux example does it work? #1277

**Comment by arioki1** [comment]
i've created a build release for m1 https://github.com/arioki1/ferdi/releases/tag/5.6.0-nightly.18-m1

**Comment by vraravam** [comment]
Would you mind rebasing from the latest of the `develop` branch of the
parent? I see that your fork is 107 commits behind it - while testing, it
would be good to get the latest and test, wouldn't it?

thanks,
Vijay

**Comment by vraravam** [comment]
<img width="257" alt="Screenshot 2021-04-20 at 7 47 54 AM" src="https://user-images.githubusercontent.com/69629/115327750-18a7db00-a1ad-11eb-8e61-dc631fe97e66.png">
I get this error when I try to open your ARM-based Ferdi app. Please review?

**Comment by vraravam** [comment]
With the latest version from @arioki1 's fork, I'm now able to run the native version on my ARM-based M1 MBP.

**Comment by janjurek** [comment]
Hi there, would it be possible to create nightly build for with these latest changes? I've looked in `ferdi/nightlies` and it looks like latest one is from February, I'll probably go with the hassle of building the app myself locally if it's a problem, but I guess more people could benefit if the ARM build would be up there. Thank you :)

**Comment by vraravam** [comment]
@janjurek - I have been trying various commits/changes for fixing this hurdle - till now, I don't have much luck. I have created and tested on a M1 and an x86 MBP machines - and all the features that I use - work great. While we wait for the build process to get fixed, do you want to test with a version of the app that I can share via googleDrive?

**Comment by vraravam** [comment]
Here's the link to the [gDrive folder](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv?usp=sharing) with the builds for Mac x86 and ARM

**Comment by titolopolous** [comment]
I am using your gdrive build from may the fourth. It is working flawlessly on my M1 Air, thanks a bunch :).

**Comment by vraravam** [comment]
thanks for testing and reporting back @titolopolous - really appreciate it. If there are newer commits and fixes (and electron upgrades), I will be uploading to the same gDrive - so please check back from time to time.

**Comment by emign** [comment]
@vraravam Thanks for that.
https://github.com/meetfranz/franz/issues/1992

**Comment by vraravam** [comment]
@emign - thanks; I was referring to new feature requests or bugs logged against Ferdi - these, I can try to triage and find fixes/workarounds for.

**Comment by emign** [comment]
The May 05 ZIP seems corrupted

**Comment by vraravam** [comment]
let me recreate - i used a different zip utility - few mins pls

**Comment by vraravam** [comment]
@emign - please try now? (I am running the same build while posting this message.)

**Comment by emign** [comment]
Yes. Works Thanks.
Twitter does not load though. Maybe that's a Ferdi problem not one of your builds

**Comment by batoo696** [comment]
@vraravam thank you!
please since 7th of may I am not able to extract and install your arm builds.
It says it is platform incompatible.
Could you check it please? This problem is even for the 10th of May build.

Huge thanks!

**Comment by batoo696** [comment]
@vraravam I forgot to mention, I am downloading these builds from your gdrive, I am not sure if it is right place with the latest builds.

**Comment by vraravam** [comment]
@batoo696 - I have just uploaded the latest from today into my gDrive. Please try that version and report back?

**Comment by RamiAlzayat** [comment]
Hey guys, I'm very interested in testing out the arm m1 build.
I just checked `Ferdi-arm64-2021-May-13.app.zip` @vraravam build on my M1 mac and I'm getting this error

<img width="259" alt="Screenshot 2021-05-13 at 20 54 56" src="https://user-images.githubusercontent.com/18601660/118173139-7b4b6a00-b42d-11eb-8647-efd358f4e9e9.png">

 any idea how to solve it?
 Thanks in advance!

**Comment by vraravam** [comment]
Thanks for the interest in testing out the latest builds @RamiAlzayat !

I have just re-uploaded the same build (re-zipped and uploaded) - please download once again and check? (I had checked a couple of days ago - and the version that I uploaded to the gDrive was downnloadable and running on my M1 mac)

**Comment by vraravam** [comment]
@RamiAlzayat - I have gotten a successful M1 ARM build and uploaded it to the [gdrive here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv). The filename is: `Ferdi-arm64-2021-May-9-07e4ed3e1.app.zip` - please confirm if this works for you

**Comment by vraravam** [comment]
New working build: `Ferdi-arm64-2021-May-13-7cbee167.app.zip`

**Comment by vraravam** [comment]
New working build - this time, I'm trying out the dmg: Ferdi-arm64-2021-May-14-eb67ea98a4.dmg

**Comment by vraravam** [comment]
New verified build: Ferdi-arm64-2021-May-12-c8a3b959dd.dmg

**Comment by batoo696** [comment]
@vraravam unfortunately this dmg says application is damaged. Previous zip was working.

**Comment by vraravam** [comment]
Can you please post a screnshot? @batoo696

**Comment by batoo696** [comment]
![image](https://user-images.githubusercontent.com/77004030/118310512-0476a580-b4ef-11eb-8963-3771a393ae49.png)

**Comment by vraravam** [comment]
thanks @batoo696 - i figured out that the dmg itself was ok (when I shared between my macs using airdrop), but, when I uploaded to gDrive and subsequently downloaded again, it shows up as corrupted. We will have to find another way to share that does not corrupt the files.

**Comment by vraravam** [comment]
@batoo696 - could you please try with the latest builds uploaded into the subfolder? I will be uploading based on date and timestamps in the folder name - so that its easier to group all files based on date/commit. Please do report back on which file format works.

**Comment by batoo696** [comment]
In the subfolder build for arm DMG and ZIP both is the same message corrupted (the same one like on the screenshot above).

**Comment by kris7t** [comment]
@vraravam Can you try encrypting the files before uploading (and sharing the key here)? That way we could find out whether gdrive is corrupting the files because they are mac apps (maybe they have a very misguided "anti-malware" feature). Also, you can post (unencrypted) file hashes (or even sign them with GPG) to make sure @batoo696 is downloading the same file that you've uploaded.

**Comment by vraravam** [comment]
ok - found the issue: in the new (Catalina and above?) macos, there is a quarantine flag that is placed on applications that are not signed. This shwos up as the file being "damaged". It can be fixed by the following command:
`sudo xattr -rd com.apple.quarantine </path/to/Ferdi.app>`
FYI: https://proinsias.github.io/til/Mac-Remove-quarantine-flag-from-app/

@batoo696 - could you please try this? Also, btw, I have uploaded a new version of the app now - with the latest recipes bundled in as well.

**Comment by batoo696** [comment]
@vraravam Thanks I tried to apply this command on this one and it worked!

![image](https://user-images.githubusercontent.com/77004030/118375538-7bc93980-b5c2-11eb-983e-16bee6034dc3.png)

**Comment by vraravam** [comment]
@batoo696 - could you also please try the zip? IF both are working, I will upload only the `dmg` and save on some bandwidth usage. Also, if this is now done, can we close this issue please? The fixing of the nightly build process is being tracked in #1254

**Comment by RamiAlzayat** [comment]
> ok - found the issue: in the new (Catalina and above?) macos, there is a quarantine flag that is placed on applications that are not signed. This shows up as the file being "damaged". It can be fixed by the following command:
> `sudo xattr -rd com.apple.quarantine </path/to/Ferdi.app>`
> FYI: https://proinsias.github.io/til/Mac-Remove-quarantine-flag-from-app/
> 
> I followed the same command for the file downloaded from the same gDrive folder, and this is from the M1 machine:
> <img alt="Screenshot 2021-05-15 at 8 28 23 PM" width="281" src="https://user-images.githubusercontent.com/69629/118369032-75d25900-b5c0-11eb-899c-2eb0c8f8e453.png">
> 
> @batoo696 - could you please try this? Also, btw, I have uploaded a new version of the app now (as seen in the image above) - with the latest recipes bundled in as well.

Thanks a lot for your quick response, After running the command `sudo xattr -rd com.apple.quarantine </path/to/Ferdi.app>` the app is running without any issue :) Thanks a lot.

**Comment by batoo696** [comment]
@vraravam both were working. Everything is ok now!

**Comment by arioki1** [comment]
can build arm64 added to travis ci, I've tried it but it has not worked
https://github.com/getferdi/ferdi/blob/develop/.travis.yml

**Comment by vraravam** [comment]
@arioki1 - the travis CI build *is* able to build `arm64`, please see [here](https://travis-ci.org/github/getferdi/ferdi/jobs/771485739). Every travis build is separated into the build env - the one linked above is for macos, vs the sibling build (`.x`) is for linux.

**Comment by vraravam** [comment]
@arioki1 - we were able to get the nightlies back on track. The ARM build for Macos is also present in there - could you please check and close this issue? https://github.com/getferdi/nightlies/releases

**Comment by RamiAlzayat** [comment]
@vraravam Works for me Thanks! :) 👍

**Comment by vraravam** [comment]
@inteus707 - can we close this ticket please? I would love to get confirmation from you for the Windows Surface Pro X ARM hardware.

**Comment by vraravam** [comment]
Closing this ticket since we now have ARM builds published in the nightly channel.

**Comment by harryfear** [comment]
Hi, where can I find an ARM build? The normal Ferdi is killing my M1 :(

**Comment by vraravam** [comment]
@harryfear - the [donwload](https://getferdi.com/download/) page has the links for both arm and x86 builds for all OSes. If you are looking for the nightly builds, they are also farther down the same page

**Comment by mrksr** [comment]
@vraravam Thank you for your work on the ARM builds! I can't quite find an ARM build for Windows. The [download page](https://getferdi.com/download/) does not point towards an ARM build and I can't find one in the [nightlies](https://getferdi.com/nightlies/), either. Am I looking in the wrong places? Using the `msi` installer results in the x64 build being installed.

**Comment by vraravam** [comment]
@mrksr - please see [this comment](https://github.com/getferdi/ferdi/pull/2167#issuecomment-955622212) - this is an upstream dependency on `electron-builder` which will need to be raised.
