### ISSUE TITLE
Playary webapp won't work

### ISSUE THREAD

**Issue by Retriev3r** [getferdi/ferdi#879]
Hi at all,
I've tried to add [Playary](https://app.playary.com/) with this self-made recipe » https://github.com/Retriev3r/franz-recipe-playary (copy from » [https://github.com/badetitou/franz-youtube-music](https://github.com/badetitou/franz-youtube-music)) but somehow the webapp won't display anything… _maybe it has something to do with the user-agent_?

Any ideas?

**Comment by fatihozkan** [comment]
Hi @Retriev3r 

This issue has been fixed by Playary team. Can you try again?

**Comment by Retriev3r** [comment]
Hi @fatihozkan 
I am actually using Ferdi (an alternative version of Franz) and it is still a just a black screen.
The console says the following » [screenshot](https://imgshare.io/images/2020/08/14/Screen-Shot-2020-08-15-at-04.33.36.jpg)
I don't understand any of that ¯\_(ツ)_/¯ 
Hope it helps!

**Comment by Retriev3r** [comment]
@fatihozkan 
I love Playary by the way!!! Thank you for this 🙏
There is just one thing I am missing » If i am on music.youtube.com I can press "»" (F7) for next and "«" (F9) for previous song on my keyboard.
[Foto of the buttons](https://images.idgesg.net/images/article/2020/03/mac-keyboard-play-pause-100837087-large.3x2.jpg)
On Playary the play & pause button works fine, but the next and back buttons are dead.
It would be so cool if you could fix this, so we don't have to use the mouse any longer.

Again THANK YOU so much for the awesome Playary!!!
Cheers,
Ben

**Comment by Retriev3r** [comment]
@fatihozkan 
> Hi @Retriev3r
> This issue has been fixed by Playary team. Can you try again?

OMG … I just found the problem 
The serviceURL in » [package.json](https://github.com/Retriev3r/franz-recipe-playary/blob/master/package.json) was not correct (one / too much).
It has been fixed and Playary is now working fine inside Ferdi! ^^

Cheers

**Comment by fatihozkan** [comment]
Hi @Retriev3r 

Actually Playary has shortcut buttons.  To go to next song just press X or Ctrl + Right Arrow button, for previous song press Z or Ctrl + Left Arrow button. To view complete shortcuts just click your username on sidebar and click Shortcuts button. You can find all shortcuts in an dedicated page.

**Comment by Retriev3r** [comment]
@fatihozkan Ok, that's nice :)
But I have to switch to Playary first =/ 
If music.youtube or spotify is playing I can use the keyboard media buttons no matter what app is currently active.
And Playary does this too, but only with the play/pause button.

I just tried Soundcloud and they got it too: play/pause, next, back - no matter what app is in focus.
Soo I was thinking it is something you can program/integrate.

Anyways thank you for your consideration!
Cheers,
Ben
