### ISSUE TITLE
Whatsapp's window is not being displayed in full

### ISSUE THREAD

**Issue by yohannes** [getferdi/ferdi#886]
Hi all,

Does anyone else using whatsapp experience non-fullscreen window? Here's a [screenshot](https://imgur.com/a/0imoEoA) for reference. Using Franz's counterpart does display whatsapp window edge to edge. Is this behavior expected for Ferdi v5.5.0.2116?

**Comment by vantezzen** [comment]
This has been fixed via https://github.com/getferdi/recipes/pull/216. You should see the fix in the next release of Ferdi.
