### ISSUE TITLE
Ferdi Tools - Custom UserAgent

### ISSUE THREAD

**Issue by andreiverdes** [getferdi/ferdi#888]
**Is your feature request related to a problem? Please describe.**
I would like to open custom Microsoft ToDo server in the `Ferdi Tools` on MacOS. However I can't do that without enrolling my devices into their tracking service, because of the `UserAgent` value

**Describe the solution you'd like**
I want to change the `UserAgent` value for `Ferdi Tools` as we can do it for the receipts in `index.js`
Is there such an `index.js` for the `Ferdi Tools`?

**Describe alternatives you've considered**
Open a custom receipt in the `Ferdi Tools` section.

**Comment by dfhz-nestor** [comment]
Now it seems to be relevant again

![Screenshot from 2021-05-20 09-28-52](https://user-images.githubusercontent.com/83422408/118987022-e0cbb900-b94d-11eb-8473-3a87dbba3366.png)

**Comment by vraravam** [comment]
please upvote this PR: #1380 to get some traction going on there.

**Comment by vraravam** [comment]
please see if manually upgrading the recipes fixes the issue. Please follow steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)

**Comment by dfhz-nestor** [comment]
Using the nightly 5.6.0 Google Chat is working fine.
Thanks!
On Thu, 2021-05-20 at 06:53 -0700, Vijay Raghavan Aravamudhan wrote:
> please see if manually upgrading the recipes fixes the issue. Please
> follow steps outlined here
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
-- 
Nestor Alonso
Director of Information Technology
DFHeinz, LLC
(786) 230-8081
***@***.***

**Comment by vraravam** [comment]
thanks for confirming that it works @dfhz-nestor ! Please continue to use Ferdi and report bugs/suggest improvements.

@andreiverdes - could you also please confirm the fix? Also, if it does work, please close the issue.

**Comment by vraravam** [comment]
Closing since the OP hasn't responded in more than 2 months.
