### ISSUE TITLE
Facebook icon gone / "Custom Website-Server could not be verified"

### ISSUE THREAD

**Issue by VOOM108** [getferdi/ferdi#892]
**Bug description:**
Facebook as a custom service had a custom f-icon. One day it was gone. (No change to the Ferdi version) Since then when trying to save changes to the service, the error-message "Custom Website-Server could not be verified" appears under the "Custom Server" field. (wording may be different, I translated from German). The "custom-url" is https://www.facebook.com oder https://facebook.com so there is not much I can change about it. 

**Expected behavior**
Saving the custom service would enable me to save a new icon and get the icon back. The service itself still works. 

**Environment:**

- Operating System: Win 10
- Ferdi Version: 5.6.0 beta-2
- Server: Ferdi

**Comment by VOOM108** [comment]
When I set Facebook up, it did not exist as it's own recipe. I just found that today and that way it works perfectly. The custom service with Facebook I just deleted...

**Comment by ragusa87** [comment]
The icon problem may be related to https://github.com/getferdi/ferdi/issues/780

**Comment by mhatvan** [comment]
As reported by issue creator, Facebook exists as its own recipe now and works perfectly, closing.
