### ISSUE TITLE
Ferdi Window Unsnaps when I click a Notification in Windows 10

### ISSUE THREAD

**Issue by FingerlessGlov3s** [getferdi/ferdi#896]
**Bug description:**
When Ferdi is Snapped to the side of the screen in Windows 10 and I click on a notification in to go to it and see the service that initiated the notification, the Ferdi window unsnaps from the side of the screen. 
Same bug as here https://github.com/meetfranz/franz/issues/1585

**Steps to reproduce:**
1. Dock Ferdi to the side of the screen with windows snap.
2. Trigger a Ferdi desktop notification, I mainly use WhatsApp
3. Click the notification.
4. Window unsnaps and resizes, to where it was prior to snap. Which can move it to a place where you have to move the window to see what you need to see.

or
1. Dock Ferdi to the side of the screen with windows snap.
2. Hide Ferdi by double clicking the tray icon.
3. Show ferdi by double clicking the tray icon.
4. Window unsnaps and resizes, to where it was prior to snap. Which can move it to a place where you have to move the window to see what you need to see.

**Expected behavior**
Stays snapped.

**Environment:**

- Operating System: Windows 10 - 1909 (10.0.18363)
- Ferdi Version: 5.5.0
- Server: Self Hosted Ferdi

**Comment by FingerlessGlov3s** [comment]
Any update on this, its really annoying 😂

**Comment by globalnomad** [comment]
This is not stale - the bug continues to exist for two years now. Please work on this dev team.

**Comment by mastercko** [comment]
Just to bump this, it is still an ongoing issue.

**Comment by mastercko** [comment]
Bump

**Comment by FingerlessGlov3s** [comment]
@mastercko, I had to stop using Franz, due to many bugs, the project feels little abandoned unfortunately, shame really.
