### ISSUE TITLE
Flash Windows Taskbar Icon

### ISSUE THREAD

**Issue by dctr** [getferdi/ferdi#897]
**Is your feature request related to a problem? Please describe.**

> Reporting this for a friend using Windows but without a GitHub account.

Under Windows, other messengers like Line highlight the Taskbar icon on incoming messages. Some blink (annoying), some just highlight it.

**Describe the solution you'd like**

For reference, see the highlighted VMWare icon in the screenshot (between OneNote and Chrome).
If one receives a new message, make the Taskbar icon light up like in the screenshot.

MVP: A settings toggle to just enable this on Windows machines. Should definitely be optional, as it might annoy people. (I also know that macOS dock icons can jump, maybe this can be done in the same go?)

**Describe alternatives you've considered**

Currently the notification icon in the Tray shows a dot when a message comes in. It's a bit small and inconspicuous though.

The user in question has turned off notifications in Windows altogether, because they are too frequent and annoy them. Fair enough, as I too feel Windows over-uses them as far as I can see (not a Windows user myself). 

**Additional context**

![](https://pureinfotech.com/wp-content/uploads/2014/11/taskbar-flashing-icon-windows-large.jpg?x47118)

**Comment by mahadevans87** [comment]
@dctr Thank you for reporting. A PR has been raised against this feature

**Comment by vantezzen** [comment]
Feature merged
