### ISSUE TITLE
Whatsapp notification icon is a lightbulb on Gnome 3.36.4 (instead of Ferdi's/Whatsapp's logo)

### ISSUE THREAD

**Issue by ThracianKnight1907** [getferdi/ferdi#898]
**Bug description:**

Basically the title

**Steps to reproduce:**

1. Add whatsapp as a service
2. Receive a message
3. The notification icon is a lightbulb

**Expected behavior**
The notification icon is Ferdi's or Whatsapp's. I don't know what is the intended behaviour 

**Environment:**

- Operating System: Fedora 32
- Ferdi Version: 5.5.0
- Server: Using without an account

**Comment by mhatvan** [comment]
@ThracianKnight1907 Can you still reproduce this with the latest version of Ferdi? I haven’t experienced this before, using WhatsApp daily.
