### ISSUE TITLE
Unread message badges also counts silenced chats in Telegram React

### ISSUE THREAD

**Issue by tururay** [getferdi/ferdi#901]
I'm not sure if this is a bug but it could be annoying for people with channels and large groups.
Is it fixed in recipe or in service?

**Comment by tururay** [comment]
I found it in service recipe. Is it interesting to make a PR?

**Comment by fhloston** [comment]
> I found it in service recipe. Does it worth a PR?

How else is it supposed to get fixed?

**Comment by fhloston** [comment]
> I found it in service recipe. Does it worth a PR?

Would you please share how it is fixed?

**Comment by tururay** [comment]
> > I found it in service recipe. Does it worth a PR?
> 
> Would you please share how it is fixed?

@fhloston sorry, I haven't seen your comment before. Here is the code:

```
# file: ~/.config/Ferdi/recipes/telegram-react/webview.js

module.exports = Franz => {
  const isMuted = (element) => {
    return element.parentElement.classList.contains("dialog-badge-muted");
  }

  const getMessages = function getMessages() {
    let count = 0;
    const elements = document.querySelectorAll(".dialog-badge-text");

    if (elements) {
      for (let i = 0; i < elements.length; i += 1) {
        if (!isMuted(elements[i])) {
          count += parseInt(elements[i].innerHTML);
        }
      }
    }
    Franz.setBadge(count);
  };
  Franz.loop(getMessages);
};
```
