### ISSUE TITLE
Opening Ferdi greatly reduces FPS in most, if not all, other open programs.

### ISSUE THREAD

**Issue by StuffonGithub** [getferdi/ferdi#902]
**Bug description:**
I first noticed this when opening Ferdi to message someone while playing a video game (Rainbow 6: Siege). My usual FPS in-game (based on in-game counter) hovers around 200-300 fps while selection/loading screens would show it as 999. _(I know these aren't the actual rates as it still depends on my main monitor which is 240 hz.)_ But if I open Ferdi, it immediately drops to 60-80, sometimes going below 40, and there is a noticeable lag on my cursor movement, game animations, input responses, etc. Closing Ferdi immediately resolves the issue so I'm quite certain it's what's causing it but it only started happening about 3-4 weeks ago, I don't remember having this problem before that with Ferdi and whatever software open.

I also tried this on several other games I have installed (RDR2, Monster Hunter, and CoD: MW to name a few) and they all have noticeable drops or delay with Ferdi open. I haven't tried it on more software but it also affects Photoshop, Illustrator, and Bridge in my experience. I also noticed that tab switching, cursor movement, and input while browsing (Firefox, Opera, Brave) gets affected although only temporarily.

I already tried searching the issue here in the past week but nothing worked (like turning dark mode off, etc).

**Steps to reproduce:**
1. Run /software/ or run /Ferdi/.
2. Run /Ferdi/ or run /software/.
3. Move and click stuff around on /software/.
4. Wait for some milliseconds or sometime a second or so.
5. Observe input being executed.

Sorry. Just thought it'd be funny. 😁

**Screenshots**
Maybe a task manager screenshot of Ferdi resource consumption could help?
Running on an i7-8700k, 16 GB RAM, 1080TI, 64-bit OS.
![image](https://user-images.githubusercontent.com/65162653/89097325-9efa7200-d410-11ea-928f-cea195b3442d.png)

**Environment:**

- Operating System: Windows 10 Pro ver. 1909 build 18363.959 64-bit
- Ferdi Version: 5.5.0
- Server: Ferdi

**Comment by vantezzen** [comment]
Thank you for reporting this. We know Ferdi isn't the most efficient messenger (due to being Electron-based) and we are exploring ways to make it more efficient in #62 but such a high impact is stikll unusual and shouldn't happen.

Couyou please try opening Ferdi's build-in Process Manager via Ferdi's settings > "Open Process Manager" to see if there is a particular service or process that is causing these spikes?

**Comment by StuffonGithub** [comment]
Thanks for the efforts and yeah, I totally understand why but as you have mentioned, my Ferdi is causing a higher than normal/acceptable spike.

Here's a screenshot of my current process manager:
![image](https://user-images.githubusercontent.com/65162653/89131958-44156780-d543-11ea-8564-869cf6b79128.png)


I have 5 Discord tabs, 1 Github, 1 Instagram, 1 Epic, and 1 Steam tab open. The instagram tab and 3 of the discord tabs are logged out and I have the "Keep all workspaces loaded" option disabled.

**Comment by skewty** [comment]
Is there any way to eliminate sandboxing of tabs and have all services share the Ferdi.loop()?  While this wouldn't help memory usage, it may help CPU usage considerably.  I don't believe latency is an issue with these chat apps.  What if the frequency of the Ferdi.loop() was slowed when Ferdi is not in focus (use configurable, sliding scale, kinda like Android Doze)?  That might also help.  This may be the total wrong approach..  I am having these thoughts without having carefully inspecting the source code.

**Comment by oreillygshane** [comment]
This is still an issue

**Comment by vraravam** [comment]
Could you please try with the latest nightly? The original ticket was raised against Ferdi v5.5 - which is no longer supported. We have released v5.6.0 a couple of months ago.

Also, the latest nightlies are quite stable and have even more perf improvements on top of 5.6.0. The nightlies can also be found on the [downloads page](https://getferdi.com/download/#nightly-builds).

**Comment by vraravam** [comment]
@skewty : I will try to answer each of your points below independently

> Is there any way to eliminate sandboxing of tabs and have all services share the Ferdi.loop()? While this wouldn't help memory usage, it may help CPU usage considerably. I don't believe latency is an issue with these chat apps.

No, elimination of sandboxing is not possible - since that would defeat the purpose of privacy/security.

> What if the frequency of the Ferdi.loop() was slowed when Ferdi is not in focus (use configurable, sliding scale, kinda like Android Doze)? That might also help. This may be the total wrong approach.. I am having these thoughts without having carefully inspecting the source code.

This is actually a nice idea, and has been implemented as an enhancement 'wakeUpStrategy`. The hibernation has also been fixed in #1680 and has been available since [5.6.1-nightly4](https://github.com/getferdi/ferdi/blob/develop/CHANGELOG.md#561-nightly4-2021-07-25). Since this is not yet released in a public version, I would request you to try out the [latest nightly from here](https://getferdi.com/download/#nightly-builds) which is quite stable.

**Comment by vraravam** [comment]
Closing since the OP hasn't responded to the outstanding request/question. I am running the latest nightly on 2 machines (1 MBP 16" x86 and another 13" MBP arm64 - both running macos Big Sur) - and I don't see this behavior at all.
