### ISSUE TITLE
Installer results in deadlock at NtUserWaitMessage

### ISSUE THREAD

**Issue by DHentzschel** [getferdi/ferdi#903]
**Bug description:**
Running the setup will end in a deadlock.  
I've had a look at it using a debugger and created a kernel dump.   
The main thread results in a deadlock after calling `NtUserWaitMessage` in module `win32u.dll`.  
The portable version runs fine.  
Installing e.g. version 3.4.3 also works fine.

**Steps to reproduce:**
1. Run the setup and wait
2. See progress bar stuck

**Expected behavior**
Install ferdi on the local machine

**Screenshots**
![UI thread stuck](https://user-images.githubusercontent.com/5008270/89121988-f73e7c00-d4c3-11ea-9013-eced2e12924e.png)
![screenshot2_ferdi](https://user-images.githubusercontent.com/5008270/89122163-6ff20800-d4c5-11ea-83e0-fd1f73d01668.png)

**Environment:**
- Operating System: Windows 10 Version 2004 (Build 19041.388) x64
- Ferdi Version: `5.5.0` and `5.6.0 beta 2`
- Server: None

- Debug information:
None

**Comment by subzero234** [comment]
I have the same issue. It occurred after using windows system restore.

**Comment by DHentzschel** [comment]
> I have the same issue. It occurred after using windows system restore.

I fixed it by removing any ferdi related registry keys and files and directories.

**Comment by subzero234** [comment]
thanks, that fixed it for me!

> > I have the same issue. It occurred after using windows system restore.
> 
> I fixed it by removing any ferdi related registry keys and files and directories.

**Comment by mhatvan** [comment]
I am glad that both of you were able to fix the issue.

In case this becomes relevant again, feel free to reopen this ticket.
