### ISSUE TITLE
User can not add custom service

### ISSUE THREAD

**Issue by LVladymyr** [getferdi/ferdi#91]
Steps:
Try to add custom recipe.

![изображение](https://user-images.githubusercontent.com/3667837/65883563-fae30d00-e39f-11e9-9836-e76cfae86ae7.png)

Expected:
User can add any kind of recipe.

**Comment by vantezzen** [comment]
![Screenshot](https://user-images.githubusercontent.com/10333196/65904830-87e98e80-e3bf-11e9-9b80-b1d937a6d493.png)
 I can't reproduce this bug. Could you please provide me the following information:
- Your OS and OS Version
- Your Ferdi version

**Comment by LVladymyr** [comment]
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.16299 Build 16299
Ferdi:
Version 5.3.3
Electron 4.2.4

**Comment by LVladymyr** [comment]
In next version: 
Version: 5.3.4-beta.6
Electron: 6.0.10 / win32 / x64
This behavior is fixed.

**Comment by kytwb** [comment]
In case someone is running into the same issue, don't forget to include beta versions when checking for in-app updates:

<img width="568" alt="Screen Shot 2019-10-01 at 3 42 35 PM" src="https://user-images.githubusercontent.com/412895/65950906-30076200-e469-11e9-9586-510984655619.png">

**Comment by Ryonez** [comment]
Just popped in about this bug as well.

What's the expected time frame for this to hit stable?

**Comment by kytwb** [comment]
@Ryonez We keep our stable version in sync with Franz, so next stable release will be out around the same time as Franz's next stable release. In the meantime, we recommend you include the beta versions when checking for in-app updates as mentioned above to get all the latest Ferdi's features/fixes.

**Comment by Ryonez** [comment]
Got it, thanks for the info.

**Comment by vantezzen** [comment]
@kytwb I thought we settled on this:
> I also think we could release new patch versions of Ferdi without Franz having that version yet (e.g. 5.3.3) if we want to release new features for Ferdi
[#7 (comment)](https://github.com/getferdi/ferdi/issues/7#issuecomment-531718318)

In that case, we could publish our changes as 5.3.4 without waiting for Franz. 
It also looks like Franz developers are currently working on a [5.4.0 release](https://github.com/meetfranz/franz/compare/release/5.4.0) and are not adding anything to [5.3.X](https://github.com/meetfranz/franz/compare/develop). I think that will still take some time until the next Franz release, 5.4.0, gets published.

**Comment by kytwb** [comment]
@vantezzen thanks for the reminder, I honestly forgot and just kept going with the betas as it seemed to be working pretty well. The only thing I see now is: what happens if we minored up before Franz on, let's say, 5.4.1, then sync to include the patches from Franz. They will be available in 5.4.2 while needing to reference merging Franz 5.4.1 into Ferdi 5.4.2, is that right?

**Comment by vantezzen** [comment]
Yes, thats right. At least in my opinion this isn't too critical as it is only the patch version that isn't in sync.

**Comment by kytwb** [comment]
What about making beta updates checked by default and maybe adding a small in-app text to explain that the stable version is kept in sync with Franz, but we recommend getting the latest betas to enjoy Ferdi's very own latest features/patches?

**Comment by vantezzen** [comment]
I understand your arguments for using beta versions as release versions, but I also think it is nice to have a release channel that users can test if new features work as intended before publishing to all users.

I looked into how `electron-updater` works and it looks like it determines whether a release is a pre-release based on if it is marked as pre-release in GitHub. My idea would be to name Ferdi release versions as `5.X.X-ferdi.Y` with `X.X` being the next Franz release and `Y` being the release version of Ferdi.
This would mean that our next update is `5.3.4-ferdi.1`. As soon as Franz releases `5.3.4`, we can merge and release it as Ferdi `5.3.4` without problems.

`electron-updater` uses the `semver` package to check versions. Here is a demo of the update process to a ferdi-prerelease: <https://runkit.com/embed/3kxs7ye7nq97>, here is a demo of the update to a full Franz release: <https://runkit.com/embed/xg4f2ce7oho3>.

**Comment by kytwb** [comment]
Regarding the beta channel, it's better to keep it for that purpose for the longer term, you're right. Following your new versioning proposal, the beta channel would then be `X-ferdi.Y-beta.Z`, right?

**Comment by vantezzen** [comment]
No, the beta channel would still be `5.X.X-beta.Y` (e.g. `5.3.4-beta.3`).
