### ISSUE TITLE
Issues with saving slack services settings 

### ISSUE THREAD

**Issue by ygrange** [getferdi/ferdi#910]
**Bug description:**

I have a bunch of slacks in my Ferdi. All works neatly, but whenever I restart Ferdi, all slacks are loaded and I see the following issues:
1. Icon of each space is reset to slack default icon until I explicitly reload every space by hand
2. All slacks are back to light mode, while I configured them to dark the last time I started Ferdi (and in fact I do that every time). The weird thing here is that slack does remember that I am colour blind (yay)
3. Two slack spaces have an explicitly configured icon in the settings (which is the slack default icon), so that overrides the space icon. I have to go to the settings and delete it.

When I set all of this up, all goes well. But when I end Ferdi and start it again, none of this has survived the restart and I have to go through those steps again.  The point here is that also not all of those happen on all slack spaces, but it does consistently happen on the same ones (it's always the same that turn white, it's always the same that override the icon).

**Steps to reproduce:**

I think it is very hard to reproduce this I'm afraid. Any ideas on this would be great...

**Expected behavior**

Settings of my slack spaces come back the same after restart of Ferdi.

**Environment:**
- Operating System: macOS Catalina
- Ferdi Version: 5.6.0 beta 3
- Server: Franz (I think, I don't really know how to find out or change it for that mattter)

- Debug information:

**Comment by mhatvan** [comment]
I cannot reproduce this. When I change e.g. one of my Slack services to dark mode and restart Ferdi, then the service is still set to dark mode.

Please let me know if this is still an issue.
