### ISSUE TITLE
Disable hibernation setting resets after every restart?

### ISSUE THREAD

**Issue by 3d73a4a412** [getferdi/ferdi#911]
I use Whatsapp, skype, and teams for work and Ferdi has been great! One caveat though, the disabling hibernation setting seems to reset everytime i restart Ferdi? That is, I set it to stay on by "disabling hibernation" but when i turn Ferdi on hibernation is apparently back on? It a great option for the other services i use but as I really need to see incomming messages for skype whatsapp and teams the hibernation revering back to enabled everytime is a bit of a liability for me.

**Comment by jaklan** [comment]
The same behaviour.

**Comment by patrickrushton** [comment]
Same problem here on Ferdi 5.5.01,  macOS 10.4.6. After restart, all the services for which i set disable hibernation (Gmail and Slack) are reset to enable hibernation.

**Comment by 0xBABA** [comment]
I suffer from the same issue. 
According to #763 and #715 This should be fixed in the latest 5.6.0-beta.2 version.
