### ISSUE TITLE
Notification from google that I've signed in on a Mac after logging into my G accounts through Ferdi on a Windows machine

### ISSUE THREAD

**Issue by kelmee** [getferdi/ferdi#918]
I got a normal notification on my phone that I had a new sign in after signing into my account through ferdi, but it says I signed in on a Mac. Is it normal for google to see Ferdi as a Mac?

**Comment by mhatvan** [comment]
I never had this before running Ferdi on Ubuntu, macOS and Windows.

Please reply if this still occurs with new releases.
