### ISSUE TITLE
Make a blog post

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#92]
I just came off from a call with Pia from OpenCollective following up on https://github.com/getferdi/ferdi/issues/73. She recommended we do a blog post to talk about Ferdi (we could tell the back story with Franz, explain hard forks in the opensource community, why the collective and such). We could publish this on Medium, then share/repost on specific websites like DEV.to, subreddits, etc. At a later stage, we may be able to participate in an interview for OpenCollective's blog [case studies](https://blog.opencollective.com/tag/case-studies/).

**Comment by vantezzen** [comment]
Great! How would you go about this? Do you want to write a blog article and I should proof-read or do we brainstorm topics for the post together or something else?

Again, I would still suggest we try to set up a stable Ferdi API first as it wouldn't show a great image going public and asking for money on our OpenCollective while still "stealing" server resources from Franz.

**Comment by kytwb** [comment]
Let's make a call to brainstorm/outline the talking points together, then I can make the first draft and we iterate together from there 👍 
Agreed regarding shipping the Ferdi API before publishing, makes total sense.

**Comment by kytwb** [comment]
First notes outlining the talking points:

> WHY: Explain what is Franz and what pushed some users to fork Franz: agressive monetization attempts, unproductive paywall in a productivity app, more and more closed control (community feedback closed if not following Franz agenda).

> WHAT: Explain opensource/fork/licenses (to explain we’re legal) and includes other examples of opensource hard forks (NextCloud/ownCloud, Blink/WebKit, and Hamsket/Rambox). Results in: Ferdi!

> HOW: Hard fork kicked off with @vantezzen contribution (introduce Bennett) then with the help of the whole community (shoutout to all contributors and show numbers (issues, pull requests, 
Ferdi’s specific commits, downloads count)).

> CALL-TO-ACTION: Talk about freemium model of Franz vs free model of Ferdi. Introduce OpenCollective, what will we do with the money, etc. / CALL-TO-ACTION
Ref: https://medium.com/webpack/sustaining-webpack-for-the-future-part-1-32bea7f9e8a2

Thanks for your time and collaboration on this @vantezzen! I will come with a first draft as soon as possible and share the draft link for people to give their feedback.

**Comment by vantezzen** [comment]
How's the blog post going?

**Comment by kytwb** [comment]
Sharing a link to the draft over the week-end! 😉

**Comment by kytwb** [comment]
This one is taking me a bit longer; continuing in the evening and should be able to wrap up tomorrow. Stay tuned!

**Comment by vantezzen** [comment]
Any updates on this?

**Comment by kytwb** [comment]
@vantezzen Apologies for being deceptive on taking up this one 🙏  
I will update once it's done, can't say when for now.

**Comment by vantezzen** [comment]
What is the status on this? Have we abandoned the blog post?

**Comment by kytwb** [comment]
@vantezzen Other things took priorities over it. I wish we would have fixed the Windows issue before, but soon would be a good time for the blog post now that we have GitHub Sponsors setup. I should have a pairing session with @yourcontact tomorrow to help on his draft pull request, I will ask him his feedback on the existing draft and continue with him.

Current draft: https://medium.com/@kytwb/an-opensource-hard-fork-case-study-meet-franz-get-ferdi-85cd8393123e

**Comment by vantezzen** [comment]
Ok sound good. I think we can really gain some users using the blog post and ProductHunt post as many Franz users are probably interested in the project but don't yet know that it exists.

**Comment by kytwb** [comment]
Unfortunately no progress was made, I'm being blocked by something when it comes to this task somehow 😅 My apologies.

**Comment by JakeSteam** [comment]
Hey!

Spoke to Ferdi on twitter about a blog post I was about to put out to check it was okay, they suggested I posted it here.

Obviously it's not going to touch on the points you guys wanted, but it is my very positive opinion :) Feel free to use it for anything you want, with credit.

https://blog.jakelee.co.uk/recommendation-ferdi-the-messaging-service-aggregator/

**Comment by kytwb** [comment]
@all-contributors please add JakeSteam for content
