### ISSUE TITLE
Undo, Redo, Paste-as-text not working in Gmail

### ISSUE THREAD

**Issue by dzg** [getferdi/ferdi#922]
**Bug description:**
When composing a message in Gmail, the Undo & Redo functionality doesn't work right. Undo behaves erratically, and Redo often doesn't work at all.

Pasting-as-text (i.e., paste without formatting for richtext or HTML clipboard) with <kbd>Shift-Option-Cmd-V</kbd> does not work.

**Environment:**

- Operating System: macOS 10.15.4
- Ferdi Version: 5.4.3 (5.4.3.994)

**Comment by mhatvan** [comment]
Cannot reproduce this, and we fixed similar issues not long ago.

Please reply in case this still happens.
