### ISSUE TITLE
Version 5.6.0-beta.2 - Gmail and WhatsApp not working

### ISSUE THREAD

**Issue by patrickrushton** [getferdi/ferdi#928]
I thought I'd give the beta a try to see if it fixes the [hibernation issues](https://github.com/getferdi/ferdi/issues/911) I've been having.

Unfortunately, Gmail and WhatsApp both complain about the browser.

![Screenshot 2020-08-23 at 10 31 32](https://user-images.githubusercontent.com/6472595/90974497-06957000-e52c-11ea-9d3f-7a0a87233ec5.png)
![Screenshot 2020-08-23 at 10 31 53](https://user-images.githubusercontent.com/6472595/90974500-0a28f700-e52c-11ea-9282-a4c1391ced69.png)

**Comment by patrickrushton** [comment]
Deleted everything and started from scratch and it seems okay now, so I will close this.

**Comment by pirasalbe** [comment]
Same issue here.
@patrickrushton when you say you deleted everything you mean you reinstalled Ferdi?
