### ISSUE TITLE
Whatsapp web QR code not recognized in dark mode

### ISSUE THREAD

**Issue by AGCaesar** [getferdi/ferdi#93]
Not sure if it is just me or my phone/screen combination, but I just wanted to scan the whatsapp QR code link the phone and ferdi, and it did not work in dark mode. Switching to normal mode fixed this.
Can anyone replicate this issue? Could be highly confusing for new users.

**Comment by vantezzen** [comment]
DarkReader is changing the background of the QR code. A fix would be to implement a system that injects additional CSS based on the current host, similar to the ignore list in `src/webview/darkmode/ignore.js` but with a CSS string assigned to the domains.

**Comment by vantezzen** [comment]
Should be fixed via 38789f8 and will ship with the next release.
