### ISSUE TITLE
Custom 3rd Part Recipe Won't work

### ISSUE THREAD

**Issue by YuHengKit** [getferdi/ferdi#932]
**Bug description:**

After adding own script inside dev folder but it wont show in the 3rd party services
**Steps to reproduce:**

1. Go to '/dev'
2. add new custom script
3. After restart Ferdi,no see anything in the custom 3rd party space

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/42687320/91384235-a458aa00-e860-11ea-9e31-6e02e48b920d.png)

**Environment:**

- Operating System: Windows 10
- Ferdi Version:  5.5.0
- Server:  Using wihout an account

- Debug information:

{"host":{"platform":"win32","release":"10.0.19041","screens":[{"id":2528732444,"bounds":{"x":0,"y":0,"width":1536,"height":864},"workArea":{"x":0,"y":0,"width":1536,"height":824},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1536,"height":864},"workAreaSize":{"width":1536,"height":824},"scaleFactor":1.25,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":2779098405,"bounds":{"x":1536,"y":0,"width":1366,"height":768},"workArea":{"x":1536,"y":0,"width":1366,"height":728},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1366,"height":768},"workAreaSize":{"width":1366,"height":728},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.0-beta.2","electron":"8.2.3","installedRecipes":[{"id":"franz-custom-website","version":"1.0.2"},{"id":"gmail","version":"1.3.3"},{"id":"whatsapp","version":"2.0.5"}],"devRecipes":[],"services":[{"id":"a21b1a17-195c-4be1-ae86-d80839ee6576","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"0409248a-a3ec-4368-9a35-83517ee5e3b3","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"783a4d1c-1aa0-4fbe-8439-e2ebdb1e3a1c","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"1376e597-060a-4531-90dd-8d065d059533","recipe":"franz-custom-website","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","info":["error",{"path":"C:\\Users\\Heng1222\\AppData\\Roaming\\Ferdi\\recipes\\dev\\Lazada\\package.json"}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in WindowControls\n    in div\n    in Unknown (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)"]}],"workspaces":[],"windowSettings":{"width":824,"height":608,"x":532,"y":80,"isMaximized":true,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1536,"height":864}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"navigationBarBehaviour":"custom","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by beppe9000** [comment]
you need to quit and re-open ferdi

**Comment by vantezzen** [comment]
I cannot reproduce this error, trying to add my own dev recipes works fine. Please make sure to create a folder inside the dev folder with the recipe ID, e.g. a dev whatsapp recipe should be inside `.../Ferdi/recipes/dev/whatsapp`, not `.../Ferdi/recipes/dev` directly.

**Comment by YuHengKit** [comment]
Issues resolved. Noticed bugs in my package.json. Thanks
