### ISSUE TITLE
Ferdi randomly logs me out of Discord

### ISSUE THREAD

**Issue by 2br-2b** [getferdi/ferdi#936]
**Bug description:**
Discord logs me out sometimes randomly

**Steps to reproduce:**
1. Start ferdi
2. Log into Discord
3. Run `killall ferdi`
4. Start ferdi back up
5. Open the Discord tab
6. See if you're still logged in

**Expected behavior**
You should stay logged into Discord even when the app is killed externally

**Environment:**

- Operating System: Linux Mint
- Ferdi Version: 5.5.0 (x64)
- Server: Using without an account

- Debug information:
{"host":{"platform":"linux","release":"5.4.0-42-generic","screens":[{"id":15885743998107732,"bounds":{"x":0,"y":0,"width":1920,"height":1080},"workArea":{"x":0,"y":0,"width":1920,"height":1080},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:INVALID, transfer:INVALID, matrix:INVALID, range:INVALID}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1080},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"discord","version":"1.1.3"},{"id":"gmail","version":"1.3.1"},{"id":"groupme","version":"1.0.0"},{"id":"hangouts","version":"1.0.2"},{"id":"office365-owa","version":"1.1.0"},{"id":"riot","version":"1.0.3"},{"id":"skype","version":"1.3.0"},{"id":"slack","version":"1.0.15"},{}],"devRecipes":[],"services":[{"id":"4f2a3791-5a13-4d93-a703-fd028c6ab425","recipe":"discord","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"505b2efe-6f7c-4977-9f25-970badc27918","recipe":"groupme","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"2e060e6c-9ac5-4786-9b6f-2a4c0fcf34f8","recipe":"riot","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"06619f1a-8dfc-4a80-9a63-9e9240bbd4de","recipe":"skype","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"288cf73e-d56d-4bc7-b6b9-3e952a357da8","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"1c3952e1-ff8a-41f5-846b-7bef165c3d43","recipe":"office365-owa","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"1ec7f7c7-bb61-4f24-89dc-d4a370e59e9e","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"7418d384-2308-4ce1-9004-da974fb1723e","recipe":"gmail","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"latest"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getChangelog"},"error":{},"response":{},"server":"You are using Ferdi without a server"}],"workspaces":[{"id":"aa3be6a7-1896-44cf-9400-838ec6e2206d","services":["4f2a3791-5a13-4d93-a703-fd028c6ab425","505b2efe-6f7c-4977-9f25-970badc27918","1c3952e1-ff8a-41f5-846b-7bef165c3d43","288cf73e-d56d-4bc7-b6b9-3e952a357da8"]},{"id":"fe7917f8-b8e9-477d-9474-354314062eda","services":["1c3952e1-ff8a-41f5-846b-7bef165c3d43","288cf73e-d56d-4bc7-b6b9-3e952a357da8"]},{"id":"d90133b1-c129-4f7b-8bcc-ba8f7a1e0042","services":["7418d384-2308-4ce1-9004-da974fb1723e","1ec7f7c7-bb61-4f24-89dc-d4a370e59e9e"]}],"windowSettings":{"width":956,"height":348,"x":960,"y":376,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080},"isMaximized":false,"isFullScreen":false},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://todo.microsoft.com/?app#","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":true,"hibernateOnStartup":false,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by zkhcohen** [comment]
+1

**Comment by Drarig29** [comment]
Yes, for me it's not random at all. It's everytime I (really) quit the app. I don't have this problem if I use the browser version of Discord, so maybe cookies are cleared?

**Comment by Drarig29** [comment]
Same for me...

**Comment by mhatvan** [comment]
Closing as duplicate of https://github.com/getferdi/ferdi/issues/1198, which has more activity.
