### ISSUE TITLE
Prevent chromium audio stream from hijacking media overlay in windows

### ISSUE THREAD

**Issue by beppe9000** [getferdi/ferdi#939]
After the first audio is played in whatsapp this happens and I can't control spotify with my keyboards media keys.
![image](https://user-images.githubusercontent.com/6625123/91779456-e2095a00-ebf5-11ea-90e5-2cefc2f42ca7.png)
I suppose it is a chromium behaviour that can probably be disabled somewhere...

**Comment by beppe9000** [comment]
This is what likely needs to be replicated in chromium's configuration:
https://www.omgchrome.com/chrome-google-music-media-keys/

**Comment by kytwb** [comment]
@beppe9000 thanks for digging in! 

It seems related to https://github.com/electron/electron/issues/18253#issuecomment-589542934.

**Comment by kris7t** [comment]
It seems we could just add

```javascript
app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling,MediaSessionService');
```

to `index.js` and fix this. I don't think a configuration option is needed: we can't set this flag per-service (I guess it would still make sense for some services that actually play media), and most services just use it "steal" the media overlay (also happens on Linux with the MPRIS media overlay protocol).

**Comment by kris7t** [comment]
Guess we can close this, since #1023 is merged now.
