### ISSUE TITLE
Active vinium extension in Ferdi

### ISSUE THREAD

**Issue by Maxcrazy1** [getferdi/ferdi#945]
I cry every time I use Ferdi and I have to click in places where there is no keyboard shortcut.. 😭

I think using vinium in ferdi would be an incredible improvement.

Also be an improvement for everyone who wants to use it, the usability would be twice as fast.

It is only a recommendation if I had the necessary knowledge, I promise that instead of making this recommendation I would be making a pull request

I love Ferdi and if they apply this, Ferdi would be pure gold 🌟..

**Comment by vantezzen** [comment]
We are currently working on adding chrome extension support to Ferdi (#833). With this, you will hopefully be able to install and use vinium on Ferdi easily.
