### ISSUE TITLE
Is it just me or the development of this app died out?

### ISSUE THREAD

**Issue by avielc** [getferdi/ferdi#946]
Hi, 
Sorry for being the one to rise this questions, and I really hope I'm wrong.

I've been monitoring the issues, and commits, for the past few months, and only seen a rise in issues vs no comment from a dev\no new commits since 16th of July. 
I hope this project isn't dead...

If anyone has any info about it, i'd be happy to hear.

Thanks

**Comment by kytwb** [comment]
@avielc Thank you for asking! The development did slow down lately, you are right, but we are catching up and will be back with more frequent releases soon. We are getting started with [Preptember](https://dev.to/devteam/preptember-start-getting-ready-for-hacktoberfest-this-month-58cn), to get the project ready for Hacktoberfest! 

Stay tuned! ✨

**Comment by avielc** [comment]
Great hearing from you!
Thanks for the update :) I'm sure many will appreciate it!

Keep it up and thanks again!
