### ISSUE TITLE
Spellchecker stopped working

### ISSUE THREAD

**Issue by Gaboris** [getferdi/ferdi#95]
**Describe the bug**
Since 5.3.3 or 5.3.4 my spellchecker has stopped working on all services and doesn't seem to be language specific.

**To Reproduce**
Nothing to reproduce.
Just doesn't work and doesn't seem to give any errors. The option to turn it on and set it to any language is working. Even the quick changing context menu is there for the text fields, but changing anything has no effect.

**Desktop (please complete the following information):**

- OS: Windowns 7 Ultimate 64bit Hungarian
- Browser: Firefox, Chrome, Opera, Vivaldi, Internet Explorer
- Version: somewhere from 5.3.3 up to 5.3.4-beta6

Could this just be a broken update? Do I need to reinstall Ferdi?

**Comment by vantezzen** [comment]
I think this is due to #52 and it updating electron to v6. There are some bugs that come from this update. Franz is currently also experiencing this bug in v5.4.0 and its developer is [currently in the process of fixing these bugs](https://github.com/meetfranz/franz/compare/release/5.4.0).

**Comment by Gaboris** [comment]
OH! We're finally getting an Electron update? Sweet!

That'll solve stuff like some emoji not being supported, right? That thing's been driving me crazy.

**Comment by vantezzen** [comment]
Yes, versions of Ferdi from 5.3.4-beta.3 use Electron 6 instead of 4. I think @kytwb needed to update electron in order to sign the app?
While this comes with updates for Chromium, Ferdi still has some problems with features experiencing bugs.

**Comment by Gaboris** [comment]
Oh, so it's already using v6? Darn, that means the emoji thing is different...

Gonna make a separate issue about that then in case someone knows a fix.

**Comment by Makazzz** [comment]
In the Franz repo they are doing fix and update in a new branch and there is this [commit for the spellchecker](https://github.com/meetfranz/franz/commit/734732f1f901093ec78b166413aa3315f6f61248). Maybe it is related.

**Comment by vantezzen** [comment]
@Makazzz I have tried merging the new commits from that branch to Ferdi locally but it seems like they havn't yet fixed all problems with the spellchecker as it still throws errors and doesn't work as intended.

**Comment by Makazzz** [comment]
Then we will have to wait for the Franz team to fix and merge their own branch into Franz/master

**Comment by vantezzen** [comment]
We have now switched to another spellchecking method to fix #114. This will also allow spellchecker to work again.
