### ISSUE TITLE
Hangouts (Google) Chat does not show notification badges

### ISSUE THREAD

**Issue by kevdo475** [getferdi/ferdi#953]
**Bug description:**
Hangouts (Google) Chat does not show any notification badges for unread messages.

**Steps to reproduce:**
0. Enable notifications, Show unread message badges, Show message badge for all new messages are all turned on.
1. Receive a new DM or mention
2. Desktop notification is properly shown
3. Observe that no notification badges are shown on the service icon.

**Expected behavior**
A red notification icon

**Screenshots**
<img width="81" alt="Screen Shot 2020-09-09 at 09 19 33" src="https://user-images.githubusercontent.com/25485055/92567219-aae21b00-f27d-11ea-9066-23012bc039c2.png">

**Environment:**
- Operating System: macOS Catalina 10.15.6
- Ferdi Version: 5.5.0
- Server: Using without an account

**Comment by vraravam** [comment]
this is also happening in Ferdi 5.6.0-beta.2

**Comment by mahadevans87** [comment]
I will take this up and get back.
