### ISSUE TITLE
We need you! Help us maintain Ferdi 👩🏽‍💻

### ISSUE THREAD

**Issue by vantezzen** [getferdi/ferdi#956]
Some of you might have noticed that Ferdi's development has [slowed down in the last few months](https://github.com/getferdi/ferdi/graphs/commit-activity). The reason for this is that we as Ferdi's core team currently don't have much time to invest into developing Ferdi due to jobs, university etc.

Regardless of this, Ferdi is still a highly used application by our community and by us.

We always saw Ferdi as a "community-developed" project, meaning that anyone is welcome to contribute to Ferdi if they want to.

There are different areas you might be able to help us with - don't worry, you won't necessarily need coding experience to contribute to Ferdi!

# Help us develop new features for Ferdi 🚀

Our community constantly has awesome new feature that could be added to Ferdi. Even though we would like to see many of these ideas features being implemented into Ferdi, we often don't have the time to do so.

How about you look [at open Feature requests](https://github.com/getferdi/ferdi/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) or use your own ideas and implement them into Ferdi?

You can look at the "About Ferdi's code" section at the end of this issue to find out more about how you can get started hacking with Ferdi's code.

# Help us fix bugs in Ferdi 🐞

To be honest to you: Ferdi is not bug-free 😢 (yet?).

You can help us squash those nasty bugs in Ferdi's code and recipes to make using Ferdi more pleasant for everybody.

There are plenty of [issues with the "bug" label](https://github.com/getferdi/ferdi/issues?q=is%3Aopen+is%3Aissue+label%3Abug+) in our repositories. If you want to, you can take one or take one you found on your own and try to fix Ferdi's code.

You can look at the "About Ferdi's code" section at the end of this issue to find out more about how you can get started hacking with Ferdi's code.

# Help us manage issues (no coding required, yay 🎉)

We get countless new issues every day on our GitHub repositories. So many in fact, that we often can't look at each of them in detail.

So why don't you look at new issues comming into our repositories, try finding our if they are duplicated of existing issues or if they might need additional information added?

# Help us design Ferdi (also no coding required, amazing  🥳)

Do you have ideas on how Ferdi's or Ferdi's website design could be improved? Why don't you just create a new issue on one of our repositories to tell us about your ideas.

# Other areas of Ferdi?

Do you have other ideas on how you want to help out with Ferdi? Go for it! We are happy to accept any contribution 😄

# About Ferdi's code

Ferdi is built with this tech stack:

- Ferdi is writting in JavaScript
- [Electron](http://electronjs.org/) as our base
- [React](https://reactjs.org/) for most of the application
- [MobX](https://mobx.js.org/README.html) for managing stores

If you know these technologies or if you want to learn them, you can dive right into Ferdi's source code at https://github.com/getferdi/ferdi.

We are using GitHub to manage and collaborate on code. If you don't yet have experience with Git or GitHub, you can start learning about that on [GitHub's Getting Started Guide](https://docs.github.com/en/github/getting-started-with-github).

If you still have any questions about helping out with Ferdi or you need help, feel free to comment on this issue!

We are happy to accept your Pull Requests and happy hacking!

**Comment by yashsaxena** [comment]
Hello everyone, I went through the entire gamut of ferdi like tools & I can tell you that ferdi is the best bet in many ways.  I tried - tryshift ( too much private info shared), slapdash (Too expensive and very few apps - perhaps just nice colors if u want), getstation ( discontinued, just in), baasass (not for linux), onedock (no linux), rambox ( busy interface), mangeyum (discontinued). 

ferdi is great in that sense! I will take this post and paste it around in places. Thank you ferdi team for building this. But perhaps, a very huge community from getstation is about to look for alternatives. I hope this is it!

**Comment by mahadevans87** [comment]
@vantezzen I have been really busy with work these days and couldn't contribute to Ferdi as much as I would like to. However, I am hoping that I should be able to start contributing again hopefully from next month onwards and start taking up some issues to start with.

**Comment by bittner** [comment]
As for development, I'm worried to not see any tests in the codebase. From the [Travis builds](https://travis-ci.org/github/getferdi/ferdi), though, I see that there is "something" there, such a ESLint and Jest (triggered via [npm run lint && npm run test](https://github.com/getferdi/ferdi/blob/develop/.travis.yml#L51); the related [script entry points](https://github.com/getferdi/ferdi/blob/develop/package.json#L19-L21) are configured in `package.json`).

But where is the test code? What do I overlook? And can we try to create some transparency with the code to understand where test coverage is low? I think, these would be important bits for both bug hunting and (technically successful) contributions.

**Comment by vantezzen** [comment]
@bittner Unfortunately Ferdi doesn't really contain any tests for its whole functionality. As you know, Ferdi is forked from Franz which doesn't have any tests itself - only the jest infrastructure - and so far there wasn't any further focus on developing tests for Ferdi.
This would definitely be something that should be added in the future!

Currently, the only test Ferdi actually has is this file: https://github.com/getferdi/ferdi/blob/develop/src/features/utils/FeatureStore.test.js

**Comment by bittner** [comment]
Just a heads-up: I can help triaging issues (and review merge requests), but currently I lack the permissions to add/remove/change labels and edit text there.

**Comment by vantezzen** [comment]
Great. I just tried adding you to a new team that has access to triaging issues - let me know if that works as I haven't worked with GitHub Team Managing before.

**Comment by bittner** [comment]
@vantezzen It works for adding the labels and closing issues. I still can't edit comments (to correct typos or markup), though.

**Comment by vraravam** [comment]
pinging to remove staleness

**Comment by vraravam** [comment]
As a person who contributed the past 8+ months to making this project better, but was abused with the following, I would not recommend any contributors to such a project/codebase
<img width="1119" alt="Ferdi-quitting" src="https://user-images.githubusercontent.com/69629/147396509-51414ef4-1c5c-4abb-9cfc-0b1049270118.png">

And the other contributor who was very active has also quit due to the same (as you can see with both our usernames now appearing as `Ghostxxx`)
<img width="1072" alt="Ferdi-quitting2" src="https://user-images.githubusercontent.com/69629/147396562-10817e3e-ee4b-4c66-b3ea-58b4b84136e5.png">

**Comment by bittner** [comment]
It's very sad to see fighting happening. Where did this all come from? When did it start? Why? Interpersonal problems are rarely one-sided. Why did collaboration work well in the past, e.g. with @vantezzen? What happened?

Is there any chance to iron this out again and get back together for the good of the project? There should be.

**Comment by niebloomj** [comment]
@vraravam How do you recommend we repair the community here? This is a beautiful project.

**Comment by vraravam** [comment]
@bittner - I am not sure when/why it started.

> Interpersonal problems are rarely one-sided.

imo, this situation **was** one-sided (maybe one of those rare cases that you refer to).

> Is there any chance to iron this out again and get back together for the good of the project? There should be.

Not unless the ownership is dealt with a group of contributors who treat each other with mutual respect and equality. _An example_ of such an action would be to attribute the copyright to the group of contributors as opposed to a single person.

@niebloomj I agree that the project is good, and better than all the others (speaking as a user of this and similar apps); im not sure how else the community can regroup for collaboration. Maybe others can also speak up their opinions? If I have done something wrong - I am ready to apologize (for the collective benefit) - but, not where I'm not at fault (or) where accusations/insults are hurled.

As it stands, I will probably continue using Ferdi as an OSS tool, and if I find something better (hamsket comes to mind), I will offer my contributions to it and move on.
