### ISSUE TITLE
Two-Factor Auth for GetFerdi

### ISSUE THREAD

**Issue by DanitiKain** [getferdi/ferdi#960]
How safe is the account on GetFerdi could someone with the login get into all my saved accounts within the platform?

Can you offer two-factor auth to get into GetFerdi as it would help with security of account.

**Comment by JakeSteam** [comment]
I thought it just synced your services / config, not your actual logins? I've always had to log back in to each service when installing on a new PC.

**Comment by DanitiKain** [comment]
Ahh well if that is the case it might be less off an issue. I haven't logged in on another device.

**Comment by vantezzen** [comment]
As @JakeSteam already said: The Ferdi servers only store the list of services and workspaces you have set up and **doesn't** save any data from within these services (i.e. login information, messages, etc.)

**Comment by vraravam** [comment]
Closing
