### ISSUE TITLE
Can't connect with Franz credentials

### ISSUE THREAD

**Issue by sparzhaman** [getferdi/ferdi#961]
Can't login from https://api.getferdi.com/import page with right credentials (just logged with same login and password on Franz page). Each time it sends "Could not login into Franz with your supplied credentials. Please check and try again"

**Comment by vantezzen** [comment]
This is a known issue (https://github.com/getferdi/server/issues/38). Unfortunately, Franz seems to have recently made some changes to its servers which causes our Import Tool to break. We hope to fix this in the next weeks.
