### ISSUE TITLE
Desactivate auto-build Appveyor and Travis for l10n_master

### ISSUE THREAD

**Issue by Makazzz** [getferdi/ferdi#97]
**Is your feature request related to a problem? Please describe.**
When Crowdin get an update there is A LOT of build for these two. And Each round take one day it seem.

**Describe the solution you'd like**
Does an option exist to block auto-build from this branch?

**Comment by vantezzen** [comment]
I added the `l10n_master` branch to the ignore list, everything should be fixed now.

**Comment by vantezzen** [comment]
@kytwb Is there a way you can remove all the queued builds on Travis and AppVeyor from the queue? We don't need them.

**Comment by Makazzz** [comment]
> 
> 
> I added the `l10n_master` branch to the ignore list, everything should be fixed now.

Thank you.

**Comment by kytwb** [comment]
@vantezzen I invited you on AppVeyor, you should be able to have access to https://ci.appveyor.com/project/kytwb/ferdi/ (used your hello@ email). For Travis, you should already have access to https://travis-ci.org/getferdi/ferdi/builds as you're part of the getferdi organization on GitHub.
