### ISSUE TITLE
5.6.0-beta.3 - no download packages even though it was tagged 5 days ago

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#970]
As the title says, its been 5 days since the tag. The previous beta release was back in June. It would be good to have more active releases.

**Comment by kytwb** [comment]
@vraravam Thank you for letting us know, I have synced with @vantezzen on the issue and deleted the pre-release for now. We are taking care of a couple of issues and will come back with a new release soon enough 💪
