### ISSUE TITLE
Ability to add words to dictionary

### ISSUE THREAD

**Issue by HaleTom** [getferdi/ferdi#971]
**Description**
I'm frustrated seeing the same words with red underlines.  I can't say that a word is spelt correctly, and don't underline it.

**Describe the solution you'd like**
I'd like to be able to add words to the dictionary.

**Describe alternatives you've considered**
A work around (or alternate, additional feature) would be to ignore that spelling just for the current session.

**Comment by Gaboris** [comment]
As far as I can remember when Ferdi was first forked from Franz it had constant problems with its dedicated spell checking functionality and the way the Ferdi team was able to fix that was to remove the custom system and let Google's/Electron's own spellchecker take care of it.

I'm only saying this to set the stage in case this becomes a bigger topic, but this whole idea depends whether or not the built in function supports custom "libraries" or if it would need to reintroduce its own system all over again from scratch.

**Comment by vantezzen** [comment]
Starting with Ferdi v5.6.0-beta.2 we switched to using Electron's internal spell checker which in turn uses your system's built-in spell check.

It looks like is possible to add custom words to this dictionary: https://www.electronjs.org/docs/tutorial/spellchecker#how-do-i-put-the-results-of-the-spellchecker-in-my-context-menu

**Comment by Gaboris** [comment]
OH! So the current system wasn't even Electron's own, but probably some external one like Google or some such? Interesting and very happy to hear.

Hope this'll be the system we need.

**Comment by mhatvan** [comment]
I can confirm that "Add to dictionary" functionality works. 

Adding unknown words to the dictionary makes them not reappear as flagged again, closing.
