### ISSUE TITLE
Undo action (or Cmd+Z) doesn't work in Google Chat

### ISSUE THREAD

**Issue by Kayyow** [getferdi/ferdi#972]
**Bug description:**

When I'm writing some text in a Google Chat text input and then pressing Cmd+Z or clicking on Edit -> Undo, nothing happens. Cmd+Z shortcut highlights the Edit menu so it seems the Undo function itself isn't working correctly.

**Steps to reproduce:**

1. Go to 'Edit' menu
2. Click on 'Undo'
3. See that nothing happens

**Expected behavior**

Hitting Cmd+Z or clicking on the Undo button should undo my previous writing

**Environment:**

- Operating System: macOS Catalina
- Ferdi Version: 5.4.3
- Server: Using without an account

**Comment by mhatvan** [comment]
Hey @Kayyow, can you still reproduce this with the latest nightly? There were some code fixes regarding copy and pasting as well as handling shortcuts recently.

Here is the link: https://github.com/getferdi/nightlies/releases

**Comment by Kayyow** [comment]
Ow thanks for the news ! I'll try this nightly build tommorow for sure. I will let you know !

**Comment by Kayyow** [comment]
After trying again using the latest nightly release `v5.6.1-nightly.37`, I'm happy to see that the shortcut is now working fine 👍 😃
Thank you for the fix and for this great open-source software !

**Comment by vraravam** [comment]
Thanks for confirming @Kayyow - closing this ticket.
