### ISSUE TITLE
getDisplayMedia patch for screen sharing not working in all services

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#974]
**Bug description:**
Screen sharing is not working in all services. 
A [patch](https://github.com/getferdi/ferdi/pull/802) for getDisplayMedia is now being injected in all services, which seems to work fine in Skype and MSTeams, but not in Discord or Google Meet.

**Environment:**

- Ferdi Version: `develop` branch

**Comment by maxammann** [comment]
Same for me, Discord is not yet working.

**Comment by argosang** [comment]
Is there progress on this?

**Comment by Theyooo** [comment]
Same here, Discord screen share is not working.

**Comment by daedgoco** [comment]
Discord screenshare works for me but it doesn't share audio, which is a deal-breaker and I have been needing to move over to the discord app for streaming.

**Comment by vraravam** [comment]
Please checkout the [latest nightly](https://github.com/getferdi/nightlies/releases/tag/v5.6.1-nightly.3) that we just released a few minutes ago. This has support for fixing the screensharing on Discord, Teams, etc. Please verify the same and report back. Once we have corroboration that this is indeed working, we can even release a new beta soon! Thanks for all your help.

**Comment by vraravam** [comment]
Discord is working with the latest nightly. Please see [this comment](https://github.com/getferdi/ferdi/issues/1541#issuecomment-885996185). Closing.
