### ISSUE TITLE
Settings UI Feedback

### ISSUE THREAD

**Issue by happycoder97** [getferdi/ferdi#976]
The "pop out" effect in the settings window is confusing.  
It feels like it is actually two windows. 
So for navigating to different entries in the sidebar, I instinctively click on the close button.

Ideally, the sidebar and the settings window should be of same elevation.

![image](https://user-images.githubusercontent.com/40014472/94149744-e5f76780-fe95-11ea-892c-4b0ca1d0df8c.png)

**Comment by vantezzen** [comment]
<img width="1552" alt="Screenshot" src="https://user-images.githubusercontent.com/10333196/94185641-d849de00-fea5-11ea-967c-bd394a8510a7.png">

Is this the layout you were thinking about?

**Comment by happycoder97** [comment]
Yes! Exactly this.

**Comment by happycoder97** [comment]
One minor thing, I guess it would look nicer if the blue title bar was white as well.

**Comment by vantezzen** [comment]
You can change the color of the title bar by changing the accent color on Settings > Appearance

**Comment by happycoder97** [comment]
Ohh I didn't mean to get rid of the accent color.
The problem is giving the titlebar color without extending to the sidebar, makes it look like the close button only applies to the center pane. It is a less pronounced version of the effect caused by the elevation in the current ui.
So we can either extend the titlebar over the sidebar too, or make it the same color as the background.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Ahmeed2m** [comment]
I think this should be closed since #977 is merged now.
