### ISSUE TITLE
Reload services prompt never goes away

### ISSUE THREAD

**Issue by webworker01** [getferdi/ferdi#98]
**Describe the bug**
Prompt for "Your services have been updated. [Reload services]" constantly appears and never goes away after clicking "Reload services"

**To Reproduce**

1. Load Ferdi
2. See the prompt
3. Click "Reload services"
4. Goto step 2

**Expected behavior**
It happens once and stops.

**Desktop (please complete the following information):**
- Version 5.3.4-beta.6

**Comment by kytwb** [comment]
Thanks for the report @webworker01, we will investigate.

**Comment by vantezzen** [comment]
Hello @webworker01 , could you please try to do the following:
- In Ferdi's menubar, under "View" click "Toggle Developer Tools"
- In the now opened Developer Tools, in the top row, click "Network" (you may have to click on the two arrows to see it)
- In Ferdi's menubar, under "View" click "Reload Ferdi". You will now see all network requests that Ferdi is executing in the developer tools
- Wait a moment until the name of one of the requests is "Update"
![Screenshot](https://user-images.githubusercontent.com/10333196/66190416-3590c200-e68c-11e9-8e16-8a1574645197.png)
- Please take a screenshot of the list of requests that get execute *after* this request (if any)
- Click on the `update` request and on the right panel, click "Preview"
- Take a screenshot of this page as well
![Screenshot](https://user-images.githubusercontent.com/10333196/66190525-80aad500-e68c-11e9-8311-53ef605ad5bc.png)
- Now, please send these two screenshots as a reply to this issue.

**Comment by webworker01** [comment]
Nothing appeared after `update`, but the preview for the `update` request always shows skype. I had it disabled, tried enabling it but the `Reload services` loop persists.  ![image](https://user-images.githubusercontent.com/3256000/66225120-a5f80d00-e6a5-11e9-999a-6f9cae4c411b.png)

**Comment by vantezzen** [comment]
Hmm ok, I still havn't quite figured our how Franz's API update works, I'll look into that.

**Comment by vantezzen** [comment]
Coud you please also do this:
- Open the Developer Tools as described above
- This time, open "Console" instead of "Network"
- Click "Reload Services" and wait it has fully loaded
- Right-click anywhere in the Developer Tools Console and select "Save As..."
- Save this file anywhere on your PC, copy its content and upload it to <http://pastebin.com> (you don't need an account there to do that)
- Send your new Pastebin URL here

It looks like your Ferdi client might have problems installing the service updates. This shows us what error there are.

**Comment by Gaboris** [comment]
Just as a head up I have the same problem.

Here's my Consol log. It's set to last for a week so copy it in case you need it for later.
https://pastebin.com/ND80M62c

Just tell me if something's wrong or if I can delete the paste since I don't know if it has any real sensitive data in there.

**Comment by nessunluogo** [comment]
Same problem here. Update returns an array with one single element referencing Skype
```
["skype"]
   0: "skype"
```
After deleting Skype service, notification stops coming out.

**Comment by grmon** [comment]
Same problem here, but no update request in the Dev Tools.

**Comment by incace** [comment]
Same issue here. No Skype service installed. I have 8 of my own recipes installed along with calendar, keep, gmail, trello, whatsapp, messenger, and android messages. I've wiped all of them and am adding back one by one to try and see if there is a specific one causing the problem. I was thinking it might be one of the recipes inside my dev folder. So far after wiping everything, the reload services banner did NOT come back when I restarted Ferdi. I will post back on my findings.

**Comment by AbsolofDarkness** [comment]
I just started having this issue on 5.4.0

**Comment by dialytica** [comment]
In my case, It's always happened every time I got a notification from any services. I'm on 5.4.0

**Comment by tensor-programming** [comment]
Seeing the same issues on the latest beta build: 5.4.1-beta.2 on windows 10

**Comment by phi0529** [comment]
Same here - using latest version and see the reload message all the time

**Comment by dremacedo** [comment]
same problem here - tried to reinstall but no good.

**Comment by vantezzen** [comment]
If you experience this bug please try this:
On Windows:
- Press `Windows Key + R` to open the "Run" dialog
- Type `%appdata%` and hit `Enter` to open your appdata folder
- Continue below
On Linux:
- Navigate to `~/.config`
- Continue below
On Mac:
- In the Finder menu bar, click on Go > Library
- Navigate to `Application Support`
- Continue below
Continue:
- Navigate to `Ferdi/recipes`
- Delete **all** folders that are inside this folder
- Restart Ferdi

This will force Ferdi to reinstall all recipes to their latest version. 
If you **still getting this error** this means that [Ferdi's recipe repository](https://github.com/getferdi/recipes) is not up to date with Franz's one. In this case Ferdi will ask Franz's servers if there are updates - which they will ask they are. Ferdi will then try to update the recipe using its own database - meaning it will still get the older recipe. After the update it will again ask Franz's servers if there are updates ending in an endless loop.
We will be working on an update script for our recipe repository that will automatically update the repository from Franz's one but for now this script doesn't exist yet.
If you are experiencing this error, you can eather [switch to Ferdi's servers](https://github.com/getferdi/ferdi/wiki/Switching-to-Ferdi's-servers) or manually update the recipe.

To manually update the recipe:
- [Find out what recipe you have to update](https://github.com/getferdi/ferdi/issues/98#issuecomment-538287504)
- Download the recipe from `https://api.franzinfra.com/v1/recipes/download/ID`, replacing `ID` with the ID of the recipe.
- Extract the file, e.g. using 7zip. You should now have a folder with these files:
    - index.js
    - package.json
    - webview.js
    - icon.png
    - and some more, depending on your recipe
- Copy the extracted folder's content (the files mentioned above) into the recipe's subfolder in Ferdi's recipe folder that you opened above. You should already see the files in there - simply overwrite them

**Comment by nessunluogo** [comment]
> If you are experiencing this error, you can eather [switch to Ferdi's servers](https://github.com/getferdi/ferdi/wiki/Switching-to-Ferdi's-servers) or manually update the recipe.

Switching to Fersi's servers ([migrating Franz's account](https://api.getferdi.com/import)) solved for me.

**Comment by phi0529** [comment]
> Switching to Ferdi's servers ([migrating Franz's account](https://api.getferdi.com/import)) solved for me.
Thanks that was what I needed - migrated my account to Ferdi - problem solved!

**Comment by vantezzen** [comment]
I've just added a new update script to the recipe repository so we can always ship the latest recipes with Ferdi's releases. This will only be pushed with the next release though.

**Comment by AbsolofDarkness** [comment]
Clearing out the recipes folder worked for me! Will be eagerly awaiting for the next release.

**Comment by camiller2** [comment]
I just had this issue, and https://github.com/getferdi/ferdi/issues/98#issuecomment-564136409 appears to have resolved it.

**Comment by Aramatis** [comment]
Just had this issue in v5.4.3, fixed it deleting recipes and restarting. For me the outdated recipe was from WhatsApp.

**Comment by acook** [comment]
I think it happened to me because I edited `darkmode.css`.

**Comment by behinime** [comment]
Deleting recipes and restarting didn't fix the problem. The prompt is still popping-up.

**Comment by camiller2** [comment]
> I just had this issue, and [#98 (comment)](https://github.com/getferdi/ferdi/issues/98#issuecomment-564136409) appears to have resolved it. Thanks!

Yeah...I lied. It worked for a while but has kept coming back up again.

**Comment by spersico** [comment]
I'm having this issue.
Watching the network tab, in the developer tools, it seems to come from an update from the whatsap recipe:
![image](https://user-images.githubusercontent.com/10502605/80159792-4100f780-85a2-11ea-828e-0c985bc18eb6.png)
![image](https://user-images.githubusercontent.com/10502605/80159811-48280580-85a2-11ea-9eeb-43dd9270ff21.png)

**Comment by acook** [comment]
Yep I was mistaken too. After deleting everything it came back soon after.

I don't have Whatsapp or Skype.

**Comment by daedgoco** [comment]
I've been having the same issue for a long time now, but I've just got to investigate it now. It happens with Whatsapp for me,

**Comment by acook** [comment]
I'm not currently seeing this issue. Was this actually fixed or has there been a lack of service updates that have masked this bug temporarily?

**Comment by camiller2** [comment]
FYI this is still a consistent issue for me.

**Comment by mskrip** [comment]
I have this issue, but I have an empty array (`[]`) as an response for `update` request and removing `recipes` folder does not help. The bottom bar with `Your services have been updated. [Reload services]` appears after ~1 min after every launch.

**Comment by thepiwo** [comment]
I have the same issue as @mskrip the update request as debugged is `[]` ~1min after each start

**Comment by Stanzilla** [comment]
Getting the same on 5.6.0.beta6

![image](https://user-images.githubusercontent.com/75278/120289203-55ddad80-c2c1-11eb-94e4-9c0ced7a67fe.png)

**Comment by kytwb** [comment]
Removed a try/catch in https://github.com/getferdi/ferdi/commit/1f1b1a9696ccdd2155cece3c5dccdb08c01025fb that would trigger the infobar to show up even when a service update failed.
