### ISSUE TITLE
Moving to develop branch

### ISSUE THREAD

**Issue by kytwb** [getferdi/ferdi#99]
WDYT about creating a develop branch and making it the default branch? So we can directly push/merge pull requests into develop, then merge to master and tag for releases while keeping a stable master branch.

**Comment by vantezzen** [comment]
Great idea. I was actually using a local "develop" branch when trying to fix #95, I will publish that branch to GitHub.

**Comment by kytwb** [comment]
@vantezzen I've made sure develop isn't behind the master branch and made develop the default branch.

**Comment by kytwb** [comment]
Re-opening until the builds are fixed on develop.
