### ISSUE TITLE
Ferdi 5.5.0 not working on Macbook Pro 10.15.7

### ISSUE THREAD

**Issue by dzigner** [getferdi/ferdi#992]
**Bug description: ferdi quits on Macbook**

**Steps to reproduce: Macbook Pro with 10.15.7 Catalina. **

4. See error - no error, Ferdi just shuts down.
When I start Ferdi, it loads for sometime, I can see my accounts on the left hand side, but it shuts down immediately. There is no error shown.

**Expected behavior**

**Screenshots**

**Environment:**

- Operating System: macOS Catalina 10.15.7
- Ferdi Version: 5.5.0
- Server: Ferdi 

- Debug information:

**Comment by mhatvan** [comment]
Hey @dzigner, there have been a lot of code improvements since v5.5.0, so your issue might have been fixed in the meantime.

You can try the latest nightly from here: https://github.com/getferdi/nightlies/releases
