### ISSUE TITLE
"Your services have been updated" message keeps popping up

### ISSUE THREAD

**Issue by janhohner** [getferdi/ferdi#999]
**Bug description:**
"Your services have been updated" message keeps popping up even after I clicked it at least 10 times. It takes 1-2 minutes and reappears. I'm running 5.6.0-nightly.1 on pop!os 20.04 (based on Ubuntu 20.04)

**Steps to reproduce:**
Run Ferdi and wait 1-2 minutes.

**Expected behavior**
Message appears once, I click the button, services get updated, message does not reappear

**Environment:**

- Operating System: pop!os 20.04 (based on Ubuntu 20.04)
- Ferdi Version: 5.6.0-nightly.1
- Server: Ferdi without account

- Debug information:
[debug.txt](https://github.com/getferdi/ferdi/files/5325505/debug.txt)

**Comment by mahmoudhossam** [comment]
I can confirm, I'm having the same issue with the ferdi-git package from Archlinux AUR.

version is `20201004_152215-1`

**Comment by janhohner** [comment]
Still happens with 5.6.0-nightly.2

**Comment by janhohner** [comment]
And also in 5.6.0-nightly.3

**Comment by janhohner** [comment]
And also in 5.6.0-nightly.4

**Comment by janhohner** [comment]
The bug seems to have been fixed in 5.6.0-nightly.5

Thank you all for your great work! Ferdi is awesome!

**Comment by kytwb** [comment]
We might need to re-open as it looked like the "fix" was actually another bug 😅 see https://github.com/getferdi/ferdi/issues/1013

We will get there!

**Comment by janhohner** [comment]
Yeah the problem is back in 5.6.0-nightly.6

**Comment by janhohner** [comment]
And also in 5.6.0-nightly.7

**Comment by kytwb** [comment]
@janhohner we will update the ticket when we have taken a look at the issue.

**Comment by janhohner** [comment]
@kytwb I didn't want to nag with this, just to keep this ticket up to date to make sure you have all the information you need when you get the time to take a look :)

**Comment by kytwb** [comment]
@janhohner no problem, just letting you know as well so you know we are not ignoring it 😄

**Comment by janhohner** [comment]
Still exists in 5.6.0-nightly.10

**Comment by janhohner** [comment]
Still relevant

**Comment by matheusmb** [comment]
Facing same issue here @ 5.6.0-beta.5

**Comment by sbcgm** [comment]
Still an issue in 5.6.0-nightly.57 btw

**Comment by vraravam** [comment]
hi @sbcgm - please try with the latest unsigned nightlies [here](http://github.com/vraravam/nightlies/releases). The latest is v68 afaik.

**Comment by sbcgm** [comment]
Hi @vraravam, thanks for the hint to the "other" nightlies. Unfortunately, the issue still persists with v68

**Comment by packermann76** [comment]
just installed 5.6.0-nightly.88, still there (MacOS BigSur, x64)

**Comment by vraravam** [comment]
@packermann76 - Ferdi 5.6.0 (public GA) release was done approx 20 hrs ago. you might want to jump into that version.

**Comment by packermann76** [comment]
@vraravam thx for the heads-up, didn't realize that

**Comment by packermann76** [comment]
OK, installed the GA, same problem

**Comment by Schmouly** [comment]
Hi there- Same problem here for me. 

Version: 5.6.0
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
Platform: macOS Big Sur
Arch: x64
Build date: Sun Jul 18 2021 17:17:34 GMT+0200 (Central European Summer Time)
Git SHA: 7b09fe7
Git branch: release

**Comment by ltngonnguyen** [comment]
Yep, just updated to ferdi 5.6.0-2 from here: https://aur.archlinux.org/packages/ferdi/

And it's there. I've never experienced it before. Been using for a year or so.

**Comment by Stanzilla** [comment]
Yeah same, also all my services keep losing their settings on upgrades

**Comment by Schmouly** [comment]
I have just deleted completely Ferdi, re-installed it and relogged in my account and now the bug has disappeared.
Hope it can helps!

**Comment by packermann76** [comment]
@Schmouly that did the trick for me, as well. Remember to delete also /Users/<yourusername>/Library/Application Support/Ferdi/ (at least on a Mac, don't know the paths for that on Linux or Windows)

**Comment by vraravam** [comment]
Thanks @Schmouly + @packermann76 - the only thing I can guess is that this might be specific to your machines / permissions. I have upgraded without issues from the older builds to the latest one without experiencing this issue.

**Comment by gustavotrott** [comment]
Now it is happening to me too!

I used Ferdi 5.6.0 for months and didn't have this problem.
Than I start using the snap version with 5.6.1-beta and didn't have this problem.
Now I changed the snap to latest/edge (5.6.1-nightly.34) and then I started facing this message all the time :cry:

**Comment by vraravam** [comment]
@gustavotrott - others have verified that some corruption has occurred on linux in the ferdi profile folder (specifically the `recipes` subfolder). Please open your profile folder in the file explorer (there's a button in the settings/preferences area `Advanced` tab to help with this step), close ferdi and delete that folder. Of course, if you have customizations in there, you might want to take a backup and restore those content changes manually (after restarting ferdi once where it'll download the new versions of the services that you have signed up for/configured within Ferdi.)

Please try this out and report back.

**Comment by gustavotrott** [comment]
Hey @vraravam,
Actually now the message disappeared without any action of mine..
If this start happening again I will try your suggestion.

Anyway, thanks for your attention :smile:

**Comment by jthomaschewski** [comment]
Today I also got this issue out of the sudden.
I was on Ferdi 5.6.1 - upgrading to 5.6.2 didn't fix the issue.

What I've done which seemed to have fixed the issue for me:

- Quit Ferdi
- Go to profile folder
- Remove "receipes" folder
- Start Ferdi

==> Opens while keeping all services + service & ferdi login, issue gone

Be sure to backup the profile folder first.

**Comment by vraravam** [comment]
Yes - this is a known issue and what @jthomaschewski described is the only known/guaranteed fix (since the root cause is something on the installation folder ie permissions getting messed up). closing this ticket - there are other duplicates of the same with the same workaround.
